define({
  "_widgetLabel": "إحداثيات",
  "hintMessage": "انقر على الخريطة للحصول على الإحداثيات",
  "defaultLabel": "الوضع الافتراضي",
  "realtimeLabel": "حَرك الفأرة للحصول على الإحداثيات",
  "computing": "جارِ الحساب...",
  "latitudeLabel": "خط عرض",
  "longitudeLabel": "خط طول",
  "loading": "جارِ التحميل...",
  "enableClick": "انقر لتمكين النقر على الخريطة للحصول على الإحداثيات",
  "disableClick": "انقر لتعطيل النقر على الخريطة للحصول على الإحداثيات",
  "Default": "الوضع الافتراضي",
  "Inches": "بوصة",
  "Foot": "قدم",
  "Yards": "ياردات",
  "Miles": "أميال",
  "Nautical_Miles": "أميال بحرية",
  "Millimeters": "ميليمتر",
  "Centimeters": "سنتيمتر",
  "Meter": "مترات",
  "Kilometers": "كيلومترات",
  "Decimeters": "ديسيميتر",
  "Decimal_Degrees": "درجات",
  "Degree_Minutes_Seconds": "الدرجات بالدقائق والثواني",
  "MGRS": "MGRS",
  "USNG": "USNG"
});