define(
   ({
    id: 'ID',
    state: "สำหรับค่าตั้งต้น ค่าพิกัดจะแสดงในระบบพิกัดของแผนที่ที่แสดงอยู่ในปัจจุบัน  หากต้องการที่จะเปลี่ยนค่าพิกัดเป็นระบบพิกัดอื่น คุณต้องเพิ่มค่าพิกัดและกำหนดค่าใหม่ที่ต้องการลงไป",
    outputUnit: "หน่วยผลลัพธ์",
    wkid: "ผลลัพธ์ WKID",
    label: "ผลลัพธ์ของชื่อระบบพิกัด",
    transformationWkid: "การแปลง WKID",
    transformationLabel: "การแปลงป้ายชื่อ",
    transformForward: "แปลงไปข้างหน้า",
    actions: "กระทำ",
    warning: "โปรดนำเข้าข้อมูลการอ้างอิงเชิงพื้นที่ WKID ที่ถูกต้อง",
    tfWarning: "โปรดนำเข้าข้อมูลการแปลง datum WKID ที่ถูกต้อง",
    spinnerLabel: "วงกลมค่าพิกัดไปยัง: ",
    decimalPlace: "ตำแหน่งทศนิยม",
    separator: "แสดงตัวคั่นเลขหลักร้อย",
    getVersionError: "ไม่ได้รับเวอร์ชันของเซอร์วิสทางเราขาคณิต",

    add: "เพิ่มผลลัพธ์ระบบค่าพิกัด",
    edit: "แก้ไขระบบค่าพิกัด",
    output: "ผลลัพธ์ระบบค่าพิกัด",
    cName: "ชื่อระบบค่าพิกัด",
    units: "หน่วยการแสดง: ",
    datum: "การแปลงค่า Datum",
    tName: "ชื่อการแปลง",
    tWKIDPlaceHolder: "WKID ของการเปลี่ยนแปล",
    forward: "ใช้การแปลงไปข้างหน้า",
    ok: "ตกลง",
    cancel: 'ยกเลิก',
    olderVersion: "เซอร์วิสเรขาคณิตไม่รองรับการเปลี่ยนแปลง",
    REPEATING_ERROR: " ฟิลด์ต่อไปนี้มีการทำซ้ำ:",

    Default: "ค่าเริ่มต้น",
    Inches: "นิ้ว",
    Foot: "ฟุต",
    Yards: "หลา",
    Miles: "ไมล์",
    Nautical_Miles: "ไมล์ทะเล",
    Millimeters: "มิลลิเมตร",
    Centimeters: "เซ็นติเมตร",
    Meter: "เมตร",
    Kilometers: "กิโลเมตร",
    Decimeters: "เดซิเมตร",
    Decimal_Degrees: "องศาทศนิยม",
    Degree_Minutes_Seconds: "องศา ลิปดา ฟิลิปดา",
    MGRS: "หน่วยอ้างอิงทางทหาร MGRS",
    USNG: "หน่วย USNG"
  })
);