define({
  "sourceSetting": "Ieškoti šaltinio parametrų",
  "instruction": "Pridėti ir sukonfigūruoti geokodavimo paslaugas arba elementų sluoksnius kaip paieškos šaltinius. Šie nurodyti šaltiniai nustato, ką galima ieškoti paieškos lauke.",
  "add": "Pridėti paieškos šaltinį",
  "addGeocoder": "Pridėti geokoderį",
  "geocoder": "Geokoderis",
  "setLayerSource": "Nustatyti sluoksnio šaltinį",
  "setGeocoderURL": "Nustatyti geokoderio URL",
  "searchableLayer": "Elementų sluoksnis",
  "name": "Pavadinimas",
  "countryCode": "Šalies arba regiono kodas (-ai)",
  "countryCodeEg": "pvz., ",
  "countryCodeHint": "Jei ši reikšmė nebus nurodyta, bus ieškomos visos šalys ir regionai",
  "generalSetting": "Bendrieji parametrai",
  "allPlaceholder": "Vietos rezervavimo tekstas visų elementų paieškai: ",
  "showInfoWindowOnSelect": "Rodyti kontekstinį langą, skirtą rastam elementui arba vietai",
  "searchInCurrentMapExtent": "Ieškoti tik esamo žemėlapio aprėptyje",
  "zoomScale": "Mastelis",
  "locatorUrl": "Geokoderio URL",
  "locatorName": "Geokoderio pavadinimas",
  "locatorExample": "Pavyzdys",
  "locatorWarning": "Ši geokodavimo paslaugos versija nepalaikoma. Valdiklis palaiko geokodavimo paslaugos 10.1 ir vėlesnes versijas.",
  "locatorTips": "Pasiūlymų nėra, nes geokodavimo paslauga nepalaiko pasiūlymų galimybės.",
  "layerSource": "Sluoksnio šaltinis",
  "searchLayerTips": "Pasiūlymų nėra, nes elementų paslauga nepalaiko puslapių numeravimo galimybės.",
  "placeholder": "Vartotojui rodomas tekstas",
  "searchFields": "Paieškos laukai",
  "displayField": "Rodyti lauką",
  "exactMatch": "Tikslus atitikmuo",
  "maxSuggestions": "Maksimalūs pasiūlymai",
  "maxResults": "Maksimalus rezultatų skaičius",
  "enableLocalSearch": "Įgalinti vietinę paiešką",
  "minScale": "Minimalus mastelis",
  "minScaleHint": "Vietinė paieška bus taikoma, kai žemėlapio mastelis bus didesnis nei šis",
  "radius": "Spindulys",
  "radiusHint": "Nurodo ploto aplink dabartinį žemėlapio centrą spindulį, naudojamą geokodavimo objektams išdėstyti taip, kad arčiausiai vietos esantys objektai būtų pateikiami pirmiausia.",
  "meters": "Metrai",
  "setSearchFields": "Nustatyti paieškos laukus",
  "set": "Nustatyti",
  "fieldSearchable": "ieškotina",
  "fieldName": "Pavadinimas",
  "fieldAlias": "Pseudonimas",
  "ok": "Gerai",
  "cancel": "Atšaukti",
  "invalidUrlTip": "URL ${URL} yra neteisingas arba nepasiekiamas."
});