define(
   ({
    "sourceSetting": "Ieškoti šaltinio parametrų",
    "instruction": "Pridėti ir sukonfigūruoti geokodavimo paslaugas arba elementų sluoksnius kaip paieškos šaltinius. Šie nurodyti šaltiniai nustato, ką galima ieškoti paieškos lauke.",
    "add": "Pridėti paieškos šaltinį",
    "addGeocoder": "Pridėti geokoderį",
    "geocoder": "Geokoderis",
    "setLayerSource": "Nustatyti sluoksnio šaltinį",
    "setGeocoderURL": "Nustatyti geokoderio URL",
    "searchableLayer": "Elementų sluoksnis",
    "name": "Pavadinimas",
    "countryCode": "Šalies arba regiono kodas (-ai)",
    "countryCodeEg": "pvz., ",
    "countryCodeHint": "Jei ši reikšmė nebus nurodyta, bus ieškomos visos šalys ir regionai",
    "generalSetting": "Bendrieji parametrai",
    "allPlaceholder": "Vietos rezervavimo tekstas visų elementų paieškai: ",
    "showInfoWindowOnSelect": "Rodyti kontekstinį langą, skirtą rastam elementui arba vietai",
    "searchInCurrentMapExtent": "Ieškoti tik esamo žemėlapio aprėptyje",
    "locatorUrl": "Geokoderio URL",
    "locatorName": "Geokoderio pavadinimas",
    "locatorExample": "Pavyzdys",
    "locatorWarning": "Ši geokodavimo paslaugos versija nepalaikoma. Valdiklis palaiko 00.0 arba vėlesnę geokodavimo paslaugą.",
    "locatorTips": "Pasiūlymų nėra, nes geokodavimo paslauga nepalaiko pasiūlymų galimybės.",
    "layerSource": "Sluoksnio šaltinis",
    "searchLayerTips": "Pasiūlymų nėra, nes elementų paslauga nepalaiko puslapių numeravimo galimybės.",
    "placeholder": "Vartotojui rodomas tekstas",
    "searchFields": "Paieškos laukai",
    "displayField": "Rodyti lauką",
    "exactMatch": "Tikslus atitikmuo",
    "maxResults": "Maksimalus rezultatų skaičius",
    "setSearchFields": "Nustatyti paieškos laukus",
    "set": "Grupė",
    "fieldSearchable": "ieškotina",
    "fieldName": "Pavadinimas",
    "fieldAlias": "Pseudonimas",
    "ok": "Gerai",
    "cancel": "Atšaukti",
    "invalidUrlTip": "URL, kurį nurodėte yra arba neteisingas, arba nepasiekiamas."
  })
);