define({
  "instruction": "Selecteer en configureer lagen die eerst worden weergegeven in Attribuuttabel.",
  "label": "Kaartlaag",
  "show": "Weergeven",
  "actions": "Laagvelden configureren",
  "field": "Veld",
  "alias": "Alias",
  "visible": "Zichtbaar",
  "linkField": "Linkveld",
  "noLayers": "Er zijn geen objectlagen beschikbaar",
  "back": "Vorige",
  "exportCSV": "Exporteren naar CSV",
  "expand": "Klap de widget eerst uit",
  "filterByExtent": "Schakel Filteren op kaartextent standaard in",
  "restore": "Standaardwaarde herstellen",
  "ok": "OK",
  "cancel": "Annuleren",
  "includePoint": "Puntcoördinaten opnemen in het geëxporteerde bestand",
  "configureLayerFields": "Laagvelden configureren",
  "result": "Opslaan is gelukt",
  "warning": "Selecteer eerst de optie Weergeven.",
  "fieldCheckWarning": "Er moet minimaal één veld worden geselecteerd.",
  "unsupportQueryWarning": "De laag moet querybewerking ondersteunen voor weergave in de widget Attribuattabel. Zorg ervoor dat de bevragingsmogelijkheid in de service aan is.",
  "unsupportQueryLayers": "De volgende laag moet query ondersteunen voor weergave in de widget Attribuuttabel. Zorg ervoor dat de querymogelijkheden in de service is ingeschakeld.",
  "fieldName": "Naam",
  "fieldAlias": "Alias",
  "fieldVisibility": "Zichtbaarheid",
  "fieldActions": "Acties",
  "showAttachments": "Bijlagen weergeven"
});