define(
   ({
    _widgetLabel: "Tabela atrybutów",
    ok: "OK",
    cancel: "Anuluj",
    unsupportQueryWarning: "Warstwa musi obsługiwać zapytania w celu wyświetlenia w widżecie tabeli atrybutów. Upewnij się, że funkcja zapytania w usłudze jest włączona.",
    exportMessage: "Wyeksportować dane do pliku CSV?",
    exportFiles: "Eksportuj do pliku CSV",
    exportSelected: "Eksportuj wybrane do pliku CSV",
    exportAll: "Eksportuj wszystko do pliku CSV",
    options: "Opcje",
    zoomto: "Powiększ do",
    highlight: "Wyróżnij grafikę",
    selectAll: "Zaznacz rekordy na wszystkich stronach",
    selectPage: "Zaznacz rekordy na bieżącej stronie",
    clearSelection: "Wyczyść selekcję",
    filter: "Filtruj",
    setFilterTip: "Skonfiguruj poprawnie filtr.",
    noFilterTip: "Jeżeli wyrażenie filtru nie zostanie zdefiniowane, zadanie zapytania zwróci wszystkie obiekty w podanym źródle danych.",
    filterByExtent: "Filtruj wg zasięgu mapy",
    showSelectedRecords: "Pokaż wybrane rekordy",
    showAllRecords: "Pokaż wszystkie rekordy",
    showRelatedRecords: "Pokaż powiązane rekordy",
    noRelatedRecords: "Brak powiązanych rekordów",
    refresh: "Odśwież",
    features: "obiekty",
    selected: "wybrane",
    transparent: "Tryb przezroczysty",
    indicate: "Zlokalizuj wybrane",
    columns: "Pokaż/ukryj kolumny",
    selectionSymbol: "Symbol selekcji",
    closeMessage: "Ukryj tabelę [rozwiń ją ponownie od dołu]",
    dataNotAvailable: "Dane są niedostępne!<br>Kliknij przycisk [Odśwież], aby ponowić próbę.",
    openTableTip: "Otwórz tabelę atrybutów",
    closeTableTip: "Ukryj tabelę atrybutów"
  })
);