define(
   ({
    id: 'ID',
    state: "Standaard worden de coördinaten weergegeven in het huidige coördinaatsysteem van de kaart. Om de coördinaten in andere coördinatensystemen te krijgen, moet u ze toevoegen en toepasselijke transformaties specificeren..",
    outputUnit: "Uitvoereenheid",
    wkid: "Uitvoer-WKID",
    label: "Naam van uitvoercoördinatensysteem",
    transformationWkid: "Transformatie-WKID",
    transformationLabel: "Transformatielabel",
    transformForward: "Naar voren transformeren",
    actions: "Handelingen",
    warning: "Voer een geldige WKID van ruimtelijke referentie in.",
    tfWarning: "Voer een geldige WKID van datumtransformatie in.",
    spinnerLabel: "Coördinaten afronden op: ",
    decimalPlace: "decimalen",
    separator: "Scheidingsteken voor duizendtallen weergeven",
    getVersionError: "Kan de versie van de Geometrieservice niet vinden",

    add: "Uitvoercoördinatensysteem toevoegen",
    edit: "Coördinatensysteem bewerken",
    output: "Uitvoercoördinatensysteem",
    cName: "Naam van coördinatensysteem",
    units: "Weergave-eenheden: ",
    datum: "Datumtransformatie",
    tName: "Naam van transformatie",
    tWKIDPlaceHolder: "WKID van de transformatie",
    forward: "Voorwaartse transformatie gebruiken",
    ok: "OK",
    cancel: 'Annuleren',
    olderVersion: "De geometrieservice ondersteunt transformeren niet",
    REPEATING_ERROR: " Het volgende coördinaatsysteem bestaat in de uitvoerlijst:",

    Default: "Standaard",
    Inches: "Inch",
    Foot: "Voet",
    Yards: "Yard",
    Miles: "Mijl",
    Nautical_Miles: "Zeemijl",
    Millimeters: "Millimeter",
    Centimeters: "Centimeter",
    Meter: "Meter",
    Kilometers: "Kilometer",
    Decimeters: "Decimeter",
    Decimal_Degrees: "Decimale graden",
    Degree_Minutes_Seconds: "Graden minuten seconden",
    MGRS: "MGRS",
    USNG: "USNG"
  })
);