define({
  "sourceSetting": "Quelleinstellungen durchsuchen",
  "instruction": "Fügen Sie Geokodierungsservices oder Feature-Layer als Suchquellen hinzu, und konfigurieren Sie sie. Anhand dieser angegebenen Quellen wird bestimmt, welche Elemente im Suchfeld durchsucht werden können.",
  "add": "Suchquelle hinzufügen",
  "addGeocoder": "Geocoder hinzufügen",
  "geocoder": "Geocoder",
  "setLayerSource": "Layer-Quelle festlegen",
  "setGeocoderURL": "Geocoder-URL festlegen",
  "searchableLayer": "Feature-Layer",
  "name": "Name",
  "countryCode": "Länder- oder Regionscode(s)",
  "countryCodeEg": "z. B. ",
  "countryCodeHint": "Wenn dieser Wert leer gelassen wird, werden alle Länder und Regionen durchsucht.",
  "generalSetting": "Allgemeine Einstellungen",
  "allPlaceholder": "Platzhaltertext für die Suche in allen Quellen: ",
  "showInfoWindowOnSelect": "Pop-up für das gefundene Feature oder die gefundene Position anzeigen",
  "searchInCurrentMapExtent": "Nur in der aktuellen Kartenausdehnung suchen",
  "zoomScale": "Zoom-Maßstab",
  "locatorUrl": "Geocoder-URL",
  "locatorName": "Geocoder-Name",
  "locatorExample": "Beispiel",
  "locatorWarning": "Diese Version des Geokodierungsservice wird nicht unterstützt. Das Widget unterstützt Geokodierungsservices der Version 10.1 und höher.",
  "locatorTips": "Es sind keine Vorschläge verfügbar, da der Geokodierungsservice die Vorschlagsfunktion nicht unterstützt.",
  "layerSource": "Layer-Quelle",
  "searchLayerTips": "Es sind keine Vorschläge verfügbar, da der Feature-Service die Paginierungsfunktion nicht unterstützt.",
  "placeholder": "Platzhaltertext",
  "searchFields": "Suchfelder",
  "displayField": "Feld anzeigen",
  "exactMatch": "Exakte Übereinstimmung",
  "maxSuggestions": "Maximale Anzahl von Vorschlägen",
  "maxResults": "Maximale Anzahl von Ergebnissen",
  "enableLocalSearch": "Lokale Suche aktivieren",
  "minScale": "Min. Maßstab",
  "minScaleHint": "Wenn der Kartenmaßstab größer ist als dieser Maßstab, wird die lokale Suche angewendet.",
  "radius": "Radius",
  "radiusHint": "Ermöglicht die Festlegung des Radius einer Fläche um den aktuellen Kartenmittelpunkt, der dazu dient, die Rangfolge von Geokodierungskandidaten zu optimieren. Die Kandidaten, die der Position am nächsten liegen, werden auf diese Weise zuerst ausgegeben.",
  "meters": "Meter",
  "setSearchFields": "Suchfelder festlegen",
  "set": "Festlegen",
  "fieldSearchable": "Durchsuchbar",
  "fieldName": "Name",
  "fieldAlias": "Alias",
  "ok": "OK",
  "cancel": "Abbrechen",
  "invalidUrlTip": "Die URL ${URL} ist ungültig oder es kann nicht darauf zugegriffen werden."
});