define(
   ({
    "sourceSetting": "Suchquelleneinstellungen",
    "instruction": "Fügen Sie Geokodierungsservices oder Feature-Layer als Suchquellen hinzu, und konfigurieren Sie sie. Anhand dieser angegebenen Quellen wird bestimmt, welche Elemente im Suchfeld durchsucht werden können.",
    "add": "Suchquelle hinzufügen",
    "addGeocoder": "Geocoder hinzufügen",
    "geocoder": "Geocoder",
    "setLayerSource": "Layer-Quelle festlegen",
    "setGeocoderURL": "Geocoder-URL festlegen",
    "searchableLayer": "Feature-Layer",
    "name": "Name",
    "countryCode": "Länder- oder Regionscode(s)",
    "countryCodeEg": "z. B. ",
    "countryCodeHint": "Wenn dieser Wert leer gelassen wird, werden alle Länder und Regionen durchsucht",
    "generalSetting": "Allgemeine Einstellungen",
    "allPlaceholder": "Platzhaltertext, um alle zu durchsuchen: ",
    "showInfoWindowOnSelect": "Pop-up für das gefundene Feature oder die gefundene Position anzeigen",
    "searchInCurrentMapExtent": "Nur in der aktuellen Kartenausdehnung suchen",
    "locatorUrl": "Geocoder-URL",
    "locatorName": "Geocoder-Name",
    "locatorExample": "Beispiel",
    "locatorWarning": "Diese Version des Geokodierungsservice wird nicht unterstützt. Das Widget unterstützt den Geokodierungsservice 00.0 und höher.",
    "locatorTips": "Es sind keine Vorschläge verfügbar, da der Geokodierungsservice die Vorschlagsfunktion nicht unterstützt.",
    "layerSource": "Layer-Quelle",
    "searchLayerTips": "Es sind keine Vorschläge verfügbar, da der Feature-Service die Paginierungsfunktion nicht unterstützt.",
    "placeholder": "Platzhaltertext",
    "searchFields": "Suchfelder",
    "displayField": "Anzeigefeld",
    "exactMatch": "Exakte Übereinstimmung",
    "maxResults": "Maximale Anzahl von Ergebnissen",
    "setSearchFields": "Suchfelder festlegen",
    "set": "Festlegen",
    "fieldSearchable": "Durchsuchbar",
    "fieldName": "Name",
    "fieldAlias": "Alias",
    "ok": "OK",
    "cancel": "Abbrechen",
    "invalidUrlTip": "Die eingegebene URL ist ungültig oder es kann nicht darauf zugegriffen werden."
  })
);