define({
  "_widgetLabel": "Kartlagliste",
  "titleBasemap": "Bakgrunnskart",
  "titleLayers": "Operasjonelle lag",
  "labelLayer": "Lagnavn",
  "itemZoomTo": "Zoom til",
  "itemTransparency": "Gjennomsiktighet",
  "itemTransparent": "Gjennomsiktighet",
  "itemOpaque": "Ugjennomsiktig",
  "itemMoveUp": "Flytt opp",
  "itemMoveDown": "Flytt ned",
  "itemDesc": "Beskrivelse",
  "itemDownload": "Last ned",
  "itemToAttributeTable": "Vis i attributtabell",
  "itemShowItemDetails": "Vis elementdetaljer:",
  "empty": "tom",
  "removePopup": "Deaktiver popup",
  "enablePopup": "Aktiver popup",
  "turnAllLayersOff": "Aktiver alle lag",
  "turnAllLayersOn": "Deaktiver alle lag",
  "expandAllLayers": "Vis alle lag",
  "collapseAlllayers": "Skjul alle lag",
  "turnAllLabelsOff": "Deaktiver alle etiketter",
  "turnAllLabelsOn": "Aktiver alle etiketter",
  "showLabels": "Vis etiketter",
  "hideLables": "Skjul etiketter"
});