define({
  "_widgetLabel": "Layer-Liste",
  "titleBasemap": "Grundkarten",
  "titleLayers": "Operationale Layer",
  "labelLayer": "Layer-Name",
  "itemZoomTo": "Zoomen auf",
  "itemTransparency": "Transparenz",
  "itemTransparent": "Transparent",
  "itemOpaque": "Nicht transparent",
  "itemMoveUp": "Nach oben verschieben",
  "itemMoveDown": "Nach unten verschieben",
  "itemDesc": "Beschreibung",
  "itemDownload": "Herunterladen",
  "itemToAttributeTable": "In Attributtabelle anzeigen",
  "itemShowItemDetails": "Elementdetails anzeigen",
  "empty": "leer",
  "removePopup": "Pop-up deaktivieren",
  "enablePopup": "Pop-up aktivieren",
  "turnAllLayersOff": "Alle Layer deaktivieren",
  "turnAllLayersOn": "Alle Layer aktivieren",
  "expandAllLayers": "Alle Layer erweitern",
  "collapseAlllayers": "Alle Layer reduzieren",
  "turnAllLabelsOff": "Alle Beschriftungen deaktivieren",
  "turnAllLabelsOn": "Alle Beschriftungen aktivieren",
  "showLabels": "Beschriftungen anzeigen",
  "hideLables": "Beschriftungen ausblenden"
});