define({
  "sourceSetting": "搜索源设置",
  "instruction": "添加并配置地理编码服务或要素图层为搜索源。这些指定的源决定了搜索框中的可搜索内容。",
  "add": "添加搜索源",
  "addGeocoder": "添加地理编码器",
  "geocoder": "地理编码器",
  "setLayerSource": "设置图层源",
  "setGeocoderURL": "设置地理编码器 URL",
  "searchableLayer": "要素图层",
  "name": "名称",
  "countryCode": "国家或区域代码",
  "countryCodeEg": "例如 ",
  "countryCodeHint": "将此值留空可搜索所有国家和地区",
  "generalSetting": "常规设置",
  "allPlaceholder": "用于搜索全部内容的占位符文本： ",
  "showInfoWindowOnSelect": "显示已找到要素或位置的弹出窗口",
  "searchInCurrentMapExtent": "仅在当前地图范围内搜索",
  "zoomScale": "缩放比例",
  "locatorUrl": "地理编码器 URL",
  "locatorName": "地理编码器名称",
  "locatorExample": "示例",
  "locatorWarning": "不支持此版本的地理编码服务。该微件支持 10.1 及更高版本的地理编码服务。",
  "locatorTips": "由于地理编码服务不支持建议功能，因此建议不可用。",
  "layerSource": "图层源",
  "searchLayerTips": "由于要素服务不支持分页功能，因此建议不可用。",
  "placeholder": "占位符文本",
  "searchFields": "搜索字段",
  "displayField": "显示字段",
  "exactMatch": "完全匹配",
  "maxSuggestions": "最大建议数",
  "maxResults": "最大结果数",
  "enableLocalSearch": "启用本地搜索",
  "minScale": "最小比例",
  "minScaleHint": "如果地图比例大于此比例，将使用本地搜索",
  "radius": "半径",
  "radiusHint": "指定以当前地图中心为中心的区域半径，用于提升地理编码候选项的等级，以便先返回距离位置最近的候选项",
  "meters": "米",
  "setSearchFields": "设置搜索字段",
  "set": "设置",
  "fieldSearchable": "可搜索",
  "fieldName": "名称",
  "fieldAlias": "别名",
  "ok": "确定",
  "cancel": "取消",
  "invalidUrlTip": "URL ${URL} 无效或不可访问。"
});