define({
  "sourceSetting": "Kaynak ayarlarını ara",
  "instruction": "Coğrafi kodlama hizmetlerini veya detay katmanlarını arama kaynağı olarak ekleyin ve yapılandırın. Belirtilen bu kaynaklar arama kutusunda neyin aranabileceğini belirler.",
  "add": "Arama kaynağı ekle",
  "addGeocoder": "Coğrafi kodlayıcı ekle",
  "geocoder": "Coğrafi Kodlayıcı",
  "setLayerSource": "Kaynak katmanı ayarla",
  "setGeocoderURL": "Coğrafi kodlayıcı URL'si düzenle",
  "searchableLayer": "Detay katmanı",
  "name": "Ad",
  "countryCode": "Ülke veya bölge kodları",
  "countryCodeEg": "örneğin ",
  "countryCodeHint": "Bu değer boş bırakılırsa tüm ülkeler ve bölgeler aranır",
  "generalSetting": "Genel ayarlar",
  "allPlaceholder": "Tümünü aramak için yer tutucu metin: ",
  "showInfoWindowOnSelect": "Bulunan detay veya konum için açılır pencere göster",
  "searchInCurrentMapExtent": "Yalnızca geçerli harita yayılımını ara",
  "zoomScale": "Yakınlaştırma ölçeği",
  "locatorUrl": "Coğrafi Kodlayıcı URL'si",
  "locatorName": "Coğrafi kodlayıcı adı",
  "locatorExample": "Örnek",
  "locatorWarning": "Coğrafi kodlama servisinin bu sürümü desteklenmiyor. Araç, 10.1 veya üstü sürümdeki coğrafi kodlama servisini destekliyor.",
  "locatorTips": "Coğrafi kodlama hizmeti öneri özelliğini desteklemediğinden öneriler kullanılamıyor.",
  "layerSource": "Katman kaynağı",
  "searchLayerTips": "Detay hizmeti sayfalama özelliğini desteklemediğinden öneriler kullanılamıyor.",
  "placeholder": "Yer tutucu metni",
  "searchFields": "Arama alanları",
  "displayField": "Alan görüntüle",
  "exactMatch": "Tam eşleşme",
  "maxSuggestions": "Maksimum öneri sayısı",
  "maxResults": "Maksimum sonuç sayısı",
  "enableLocalSearch": "Yerel aramayı etkinleştir",
  "minScale": "Min ölçek",
  "minScaleHint": "Harita ölçeği bu ölçekten daha büyük olduğunda yerel arama uygulanır",
  "radius": "Yarıçap",
  "radiusHint": "Coğrafi kodlama adaylarının sıralamasını yükseltmek için kullanılan geçerli harita merkezi etrafındaki bir alanın yarı çapını belirtir, böylelikle konuma en yakın olan adaylar öncelikli olarak döndürülür",
  "meters": "Metre",
  "setSearchFields": "Arama alanlarını ayarla",
  "set": "Ayarla",
  "fieldSearchable": "aranabilir",
  "fieldName": "Ad",
  "fieldAlias": "Takma Ad",
  "ok": "Tamam",
  "cancel": "İptal",
  "invalidUrlTip": "${URL} URL'si geçersiz veya erişilemez durumda."
});