define({
  "_widgetLabel": "Elenco layer",
  "titleBasemap": "Mappe di base",
  "titleLayers": "Layer operativi",
  "labelLayer": "Nome layer",
  "itemZoomTo": "Zoom a",
  "itemTransparency": "Trasparenza",
  "itemTransparent": "Trasparente",
  "itemOpaque": "Opaco",
  "itemMoveUp": "Sposta su",
  "itemMoveDown": "Sposta giù",
  "itemDesc": "Descrizione",
  "itemDownload": "Download",
  "itemToAttributeTable": "Visualizza nella tabella degli attributi",
  "itemShowItemDetails": "Mostra dettagli elemento",
  "empty": "vuoto",
  "removePopup": "Disabilita popup",
  "enablePopup": "Abilita popup",
  "turnAllLayersOff": "Disattiva tutti i layer",
  "turnAllLayersOn": "Attiva tutti i layer",
  "expandAllLayers": "Espandi tutti i layer",
  "collapseAlllayers": "Comprimi tutti i layer",
  "turnAllLabelsOff": "Disattiva tutte le etichette",
  "turnAllLabelsOn": "Attiva tutte le etichette",
  "showLabels": "Mostra etichette",
  "hideLables": "Nascondi etichette"
});