<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0" xmlns:esri="http://www.esri.com/metadata/" xmlns:res="http://www.esri.com/metadata/res/" >

<!-- An XSLT template for displaying metadata in ArcGIS. These XSLT templates display the official ISO 3166 country name in place of a country code.

     Copyright (c) 2009-2010, Environmental Systems Research Institute, Inc. All rights reserved.
	
     Revision History: Created 6/8/2009 avienneau
     
     the res: namespace doesn't do anything outside of the ArcGIS environment, so just return the code that is passed in
-->

	<xsl:output method="xml" indent="yes"/>
	<xsl:template name="cntry3166_2letter">
		<xsl:param name="code"/>
<!--		<xsl:variable name="smallcase" select="'abcdefghijklmnopqrstuvwxyz'" />
		<xsl:variable name="uppercase" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZ'" />
		<xsl:variable name="lcCode">
			<xsl:value-of select="translate($code, $smallcase, $uppercase)" />
		</xsl:variable>
		<xsl:choose>
			<xsl:when test="(lcCode = 'af')"><res:idCountryName_AFG/></xsl:when>
			<xsl:when test="(lcCode = 'ax')"><res:idCountryName_ALA/></xsl:when>
			<xsl:when test="(lcCode = 'al')"><res:idCountryName_ALB/></xsl:when>
			<xsl:when test="(lcCode = 'dz')"><res:idCountryName_DZA/></xsl:when>
			<xsl:when test="(lcCode = 'as')"><res:idCountryName_ASM/></xsl:when>
			<xsl:when test="(lcCode = 'ad')"><res:idCountryName_AND/></xsl:when>
			<xsl:when test="(lcCode = 'ao')"><res:idCountryName_AGO/></xsl:when>
			<xsl:when test="(lcCode = 'ai')"><res:idCountryName_AIA/></xsl:when>
			<xsl:when test="(lcCode = 'aq')"><res:idCountryName_ATA/></xsl:when>
			<xsl:when test="(lcCode = 'ag')"><res:idCountryName_ATG/></xsl:when>
			<xsl:when test="(lcCode = 'ar')"><res:idCountryName_ARG/></xsl:when>
			<xsl:when test="(lcCode = 'am')"><res:idCountryName_ARM/></xsl:when>
			<xsl:when test="(lcCode = 'aw')"><res:idCountryName_ABW/></xsl:when>
			<xsl:when test="(lcCode = 'au')"><res:idCountryName_AUS/></xsl:when>
			<xsl:when test="(lcCode = 'at')"><res:idCountryName_AUT/></xsl:when>
			<xsl:when test="(lcCode = 'az')"><res:idCountryName_AZE/></xsl:when>
			<xsl:when test="(lcCode = 'bs')"><res:idCountryName_BHS/></xsl:when>
			<xsl:when test="(lcCode = 'bh')"><res:idCountryName_BHR/></xsl:when>
			<xsl:when test="(lcCode = 'bd')"><res:idCountryName_BGD/></xsl:when>
			<xsl:when test="(lcCode = 'bb')"><res:idCountryName_BRB/></xsl:when>
			<xsl:when test="(lcCode = 'by')"><res:idCountryName_BLR/></xsl:when>
			<xsl:when test="(lcCode = 'be')"><res:idCountryName_BEL/></xsl:when>
			<xsl:when test="(lcCode = 'bz')"><res:idCountryName_BLZ/></xsl:when>
			<xsl:when test="(lcCode = 'bj')"><res:idCountryName_BEN/></xsl:when>
			<xsl:when test="(lcCode = 'bm')"><res:idCountryName_BMU/></xsl:when>
			<xsl:when test="(lcCode = 'bt')"><res:idCountryName_BTN/></xsl:when>
			<xsl:when test="(lcCode = 'bo')"><res:idCountryName_BOL/></xsl:when>
			<xsl:when test="(lcCode = 'ba')"><res:idCountryName_BIH/></xsl:when>
			<xsl:when test="(lcCode = 'bw')"><res:idCountryName_BWA/></xsl:when>
			<xsl:when test="(lcCode = 'bv')"><res:idCountryName_BVT/></xsl:when>
			<xsl:when test="(lcCode = 'br')"><res:idCountryName_BRA/></xsl:when>
			<xsl:when test="(lcCode = 'io')"><res:idCountryName_IOT/></xsl:when>
			<xsl:when test="(lcCode = 'bn')"><res:idCountryName_BRN/></xsl:when>
			<xsl:when test="(lcCode = 'bg')"><res:idCountryName_BGR/></xsl:when>
			<xsl:when test="(lcCode = 'bf')"><res:idCountryName_BFA/></xsl:when>
			<xsl:when test="(lcCode = 'bi')"><res:idCountryName_BDI/></xsl:when>
			<xsl:when test="(lcCode = 'kh')"><res:idCountryName_KHM/></xsl:when>
			<xsl:when test="(lcCode = 'cm')"><res:idCountryName_CMR/></xsl:when>
			<xsl:when test="(lcCode = 'ca')"><res:idCountryName_CAN/></xsl:when>
			<xsl:when test="(lcCode = 'cv')"><res:idCountryName_CPV/></xsl:when>
			<xsl:when test="(lcCode = 'ky')"><res:idCountryName_CYM/></xsl:when>
			<xsl:when test="(lcCode = 'cf')"><res:idCountryName_CAF/></xsl:when>
			<xsl:when test="(lcCode = 'td')"><res:idCountryName_TCD/></xsl:when>
			<xsl:when test="(lcCode = 'cl')"><res:idCountryName_CHL/></xsl:when>
			<xsl:when test="(lcCode = 'cn')"><res:idCountryName_CHN/></xsl:when>
			<xsl:when test="(lcCode = 'cx')"><res:idCountryName_CXR/></xsl:when>
			<xsl:when test="(lcCode = 'cc')"><res:idCountryName_CCK/></xsl:when>
			<xsl:when test="(lcCode = 'co')"><res:idCountryName_COL/></xsl:when>
			<xsl:when test="(lcCode = 'km')"><res:idCountryName_COM/></xsl:when>
			<xsl:when test="(lcCode = 'cg')"><res:idCountryName_COG/></xsl:when>
			<xsl:when test="(lcCode = 'cd')"><res:idCountryName_COD/></xsl:when>
			<xsl:when test="(lcCode = 'ck')"><res:idCountryName_COK/></xsl:when>
			<xsl:when test="(lcCode = 'cr')"><res:idCountryName_CRI/></xsl:when>
			<xsl:when test="(lcCode = 'ci')"><res:idCountryName_CIV/></xsl:when>
			<xsl:when test="(lcCode = 'hr')"><res:idCountryName_HRV/></xsl:when>
			<xsl:when test="(lcCode = 'cu')"><res:idCountryName_CUB/></xsl:when>
			<xsl:when test="(lcCode = 'cy')"><res:idCountryName_CYP/></xsl:when>
			<xsl:when test="(lcCode = 'cz')"><res:idCountryName_CZE/></xsl:when>
			<xsl:when test="(lcCode = 'dk')"><res:idCountryName_DNK/></xsl:when>
			<xsl:when test="(lcCode = 'dj')"><res:idCountryName_DJI/></xsl:when>
			<xsl:when test="(lcCode = 'dm')"><res:idCountryName_DMA/></xsl:when>
			<xsl:when test="(lcCode = 'do')"><res:idCountryName_DOM/></xsl:when>
			<xsl:when test="(lcCode = 'ec')"><res:idCountryName_ECU/></xsl:when>
			<xsl:when test="(lcCode = 'eg')"><res:idCountryName_EGY/></xsl:when>
			<xsl:when test="(lcCode = 'sv')"><res:idCountryName_SLV/></xsl:when>
			<xsl:when test="(lcCode = 'gq')"><res:idCountryName_GNQ/></xsl:when>
			<xsl:when test="(lcCode = 'er')"><res:idCountryName_ERI/></xsl:when>
			<xsl:when test="(lcCode = 'ee')"><res:idCountryName_EST/></xsl:when>
			<xsl:when test="(lcCode = 'et')"><res:idCountryName_ETH/></xsl:when>
			<xsl:when test="(lcCode = 'fk')"><res:idCountryName_FLK/></xsl:when>
			<xsl:when test="(lcCode = 'fo')"><res:idCountryName_FRO/></xsl:when>
			<xsl:when test="(lcCode = 'fj')"><res:idCountryName_FJI/></xsl:when>
			<xsl:when test="(lcCode = 'fi')"><res:idCountryName_FIN/></xsl:when>
			<xsl:when test="(lcCode = 'fr')"><res:idCountryName_FRA/></xsl:when>
			<xsl:when test="(lcCode = 'gf')"><res:idCountryName_GUF/></xsl:when>
			<xsl:when test="(lcCode = 'pf')"><res:idCountryName_PYF/></xsl:when>
			<xsl:when test="(lcCode = 'tf')"><res:idCountryName_ATF/></xsl:when>
			<xsl:when test="(lcCode = 'ga')"><res:idCountryName_GAB/></xsl:when>
			<xsl:when test="(lcCode = 'gm')"><res:idCountryName_GMB/></xsl:when>
			<xsl:when test="(lcCode = 'ge')"><res:idCountryName_GEO/></xsl:when>
			<xsl:when test="(lcCode = 'de')"><res:idCountryName_DEU/></xsl:when>
			<xsl:when test="(lcCode = 'gh')"><res:idCountryName_GHA/></xsl:when>
			<xsl:when test="(lcCode = 'gi')"><res:idCountryName_GIB/></xsl:when>
			<xsl:when test="(lcCode = 'gr')"><res:idCountryName_GRC/></xsl:when>
			<xsl:when test="(lcCode = 'gl')"><res:idCountryName_GRL/></xsl:when>
			<xsl:when test="(lcCode = 'gd')"><res:idCountryName_GRD/></xsl:when>
			<xsl:when test="(lcCode = 'gp')"><res:idCountryName_GLP/></xsl:when>
			<xsl:when test="(lcCode = 'gu')"><res:idCountryName_GUM/></xsl:when>
			<xsl:when test="(lcCode = 'gt')"><res:idCountryName_GTM/></xsl:when>
			<xsl:when test="(lcCode = 'gg')"><res:idCountryName_GGY/></xsl:when>
			<xsl:when test="(lcCode = 'gn')"><res:idCountryName_GIN/></xsl:when>
			<xsl:when test="(lcCode = 'gw')"><res:idCountryName_GNB/></xsl:when>
			<xsl:when test="(lcCode = 'gy')"><res:idCountryName_GUY/></xsl:when>
			<xsl:when test="(lcCode = 'ht')"><res:idCountryName_HTI/></xsl:when>
			<xsl:when test="(lcCode = 'hm')"><res:idCountryName_HMD/></xsl:when>
			<xsl:when test="(lcCode = 'va')"><res:idCountryName_VAT/></xsl:when>
			<xsl:when test="(lcCode = 'hn')"><res:idCountryName_HND/></xsl:when>
			<xsl:when test="(lcCode = 'hk')"><res:idCountryName_HKG/></xsl:when>
			<xsl:when test="(lcCode = 'hu')"><res:idCountryName_HUN/></xsl:when>
			<xsl:when test="(lcCode = 'is')"><res:idCountryName_ISL/></xsl:when>
			<xsl:when test="(lcCode = 'in')"><res:idCountryName_IND/></xsl:when>
			<xsl:when test="(lcCode = 'id')"><res:idCountryName_IDN/></xsl:when>
			<xsl:when test="(lcCode = 'ir')"><res:idCountryName_IRN/></xsl:when>
			<xsl:when test="(lcCode = 'iq')"><res:idCountryName_IRQ/></xsl:when>
			<xsl:when test="(lcCode = 'ie')"><res:idCountryName_IRL/></xsl:when>
			<xsl:when test="(lcCode = 'im')"><res:idCountryName_IMN/></xsl:when>
			<xsl:when test="(lcCode = 'il')"><res:idCountryName_ISR/></xsl:when>
			<xsl:when test="(lcCode = 'it')"><res:idCountryName_ITA/></xsl:when>
			<xsl:when test="(lcCode = 'jm')"><res:idCountryName_JAM/></xsl:when>
			<xsl:when test="(lcCode = 'jp')"><res:idCountryName_JPN/></xsl:when>
			<xsl:when test="(lcCode = 'je')"><res:idCountryName_JEY/></xsl:when>
			<xsl:when test="(lcCode = 'jo')"><res:idCountryName_JOR/></xsl:when>
			<xsl:when test="(lcCode = 'kz')"><res:idCountryName_KAZ/></xsl:when>
			<xsl:when test="(lcCode = 'ke')"><res:idCountryName_KEN/></xsl:when>
			<xsl:when test="(lcCode = 'ki')"><res:idCountryName_KIR/></xsl:when>
			<xsl:when test="(lcCode = 'kp')"><res:idCountryName_PRK/></xsl:when>
			<xsl:when test="(lcCode = 'kr')"><res:idCountryName_KOR/></xsl:when>
			<xsl:when test="(lcCode = 'kw')"><res:idCountryName_KWT/></xsl:when>
			<xsl:when test="(lcCode = 'kg')"><res:idCountryName_KGZ/></xsl:when>
			<xsl:when test="(lcCode = 'la')"><res:idCountryName_LAO/></xsl:when>
			<xsl:when test="(lcCode = 'lv')"><res:idCountryName_LVA/></xsl:when>
			<xsl:when test="(lcCode = 'lb')"><res:idCountryName_LBN/></xsl:when>
			<xsl:when test="(lcCode = 'ls')"><res:idCountryName_LSO/></xsl:when>
			<xsl:when test="(lcCode = 'lr')"><res:idCountryName_LBR/></xsl:when>
			<xsl:when test="(lcCode = 'ly')"><res:idCountryName_LBY/></xsl:when>
			<xsl:when test="(lcCode = 'li')"><res:idCountryName_LIE/></xsl:when>
			<xsl:when test="(lcCode = 'lt')"><res:idCountryName_LTU/></xsl:when>
			<xsl:when test="(lcCode = 'lu')"><res:idCountryName_LUX/></xsl:when>
			<xsl:when test="(lcCode = 'mo')"><res:idCountryName_MAC/></xsl:when>
			<xsl:when test="(lcCode = 'mk')"><res:idCountryName_MKD/></xsl:when>
			<xsl:when test="(lcCode = 'mg')"><res:idCountryName_MDG/></xsl:when>
			<xsl:when test="(lcCode = 'mw')"><res:idCountryName_MWI/></xsl:when>
			<xsl:when test="(lcCode = 'my')"><res:idCountryName_MYS/></xsl:when>
			<xsl:when test="(lcCode = 'mv')"><res:idCountryName_MDV/></xsl:when>
			<xsl:when test="(lcCode = 'ml')"><res:idCountryName_MLI/></xsl:when>
			<xsl:when test="(lcCode = 'mt')"><res:idCountryName_MLT/></xsl:when>
			<xsl:when test="(lcCode = 'mh')"><res:idCountryName_MHL/></xsl:when>
			<xsl:when test="(lcCode = 'mq')"><res:idCountryName_MTQ/></xsl:when>
			<xsl:when test="(lcCode = 'mr')"><res:idCountryName_MRT/></xsl:when>
			<xsl:when test="(lcCode = 'mu')"><res:idCountryName_MUS/></xsl:when>
			<xsl:when test="(lcCode = 'yt')"><res:idCountryName_MYT/></xsl:when>
			<xsl:when test="(lcCode = 'mx')"><res:idCountryName_MEX/></xsl:when>
			<xsl:when test="(lcCode = 'fm')"><res:idCountryName_FSM/></xsl:when>
			<xsl:when test="(lcCode = 'md')"><res:idCountryName_MDA/></xsl:when>
			<xsl:when test="(lcCode = 'mc')"><res:idCountryName_MCO/></xsl:when>
			<xsl:when test="(lcCode = 'mn')"><res:idCountryName_MNG/></xsl:when>
			<xsl:when test="(lcCode = 'me')"><res:idCountryName_MNE/></xsl:when>
			<xsl:when test="(lcCode = 'ms')"><res:idCountryName_MSR/></xsl:when>
			<xsl:when test="(lcCode = 'ma')"><res:idCountryName_MAR/></xsl:when>
			<xsl:when test="(lcCode = 'mz')"><res:idCountryName_MOZ/></xsl:when>
			<xsl:when test="(lcCode = 'mm')"><res:idCountryName_MMR/></xsl:when>
			<xsl:when test="(lcCode = 'na')"><res:idCountryName_NAM/></xsl:when>
			<xsl:when test="(lcCode = 'nr')"><res:idCountryName_NRU/></xsl:when>
			<xsl:when test="(lcCode = 'np')"><res:idCountryName_NPL/></xsl:when>
			<xsl:when test="(lcCode = 'nl')"><res:idCountryName_NLD/></xsl:when>
			<xsl:when test="(lcCode = 'an')"><res:idCountryName_ANT/></xsl:when>
			<xsl:when test="(lcCode = 'nc')"><res:idCountryName_NCL/></xsl:when>
			<xsl:when test="(lcCode = 'nz')"><res:idCountryName_NZL/></xsl:when>
			<xsl:when test="(lcCode = 'ni')"><res:idCountryName_NIC/></xsl:when>
			<xsl:when test="(lcCode = 'ne')"><res:idCountryName_NER/></xsl:when>
			<xsl:when test="(lcCode = 'ng')"><res:idCountryName_NGA/></xsl:when>
			<xsl:when test="(lcCode = 'nu')"><res:idCountryName_NIU/></xsl:when>
			<xsl:when test="(lcCode = 'nf')"><res:idCountryName_NFK/></xsl:when>
			<xsl:when test="(lcCode = 'mp')"><res:idCountryName_MNP/></xsl:when>
			<xsl:when test="(lcCode = 'no')"><res:idCountryName_NOR/></xsl:when>
			<xsl:when test="(lcCode = 'om')"><res:idCountryName_OMN/></xsl:when>
			<xsl:when test="(lcCode = 'pk')"><res:idCountryName_PAK/></xsl:when>
			<xsl:when test="(lcCode = 'pw')"><res:idCountryName_PLW/></xsl:when>
			<xsl:when test="(lcCode = 'ps')"><res:idCountryName_PSE/></xsl:when>
			<xsl:when test="(lcCode = 'pa')"><res:idCountryName_PAN/></xsl:when>
			<xsl:when test="(lcCode = 'pg')"><res:idCountryName_PNG/></xsl:when>
			<xsl:when test="(lcCode = 'py')"><res:idCountryName_PRY/></xsl:when>
			<xsl:when test="(lcCode = 'pe')"><res:idCountryName_PER/></xsl:when>
			<xsl:when test="(lcCode = 'ph')"><res:idCountryName_PHL/></xsl:when>
			<xsl:when test="(lcCode = 'pn')"><res:idCountryName_PCN/></xsl:when>
			<xsl:when test="(lcCode = 'pl')"><res:idCountryName_POL/></xsl:when>
			<xsl:when test="(lcCode = 'pt')"><res:idCountryName_PRT/></xsl:when>
			<xsl:when test="(lcCode = 'pr')"><res:idCountryName_PRI/></xsl:when>
			<xsl:when test="(lcCode = 'qa')"><res:idCountryName_QAT/></xsl:when>
			<xsl:when test="(lcCode = 're')"><res:idCountryName_REU/></xsl:when>
			<xsl:when test="(lcCode = 'ro')"><res:idCountryName_ROU/></xsl:when>
			<xsl:when test="(lcCode = 'ru')"><res:idCountryName_RUS/></xsl:when>
			<xsl:when test="(lcCode = 'rw')"><res:idCountryName_RWA/></xsl:when>
			<xsl:when test="(lcCode = 'bl')"><res:idCountryName_BLM/></xsl:when>
			<xsl:when test="(lcCode = 'sh')"><res:idCountryName_SHN/></xsl:when>
			<xsl:when test="(lcCode = 'kn')"><res:idCountryName_KNA/></xsl:when>
			<xsl:when test="(lcCode = 'lc')"><res:idCountryName_LCA/></xsl:when>
			<xsl:when test="(lcCode = 'mf')"><res:idCountryName_MAF/></xsl:when>
			<xsl:when test="(lcCode = 'pm')"><res:idCountryName_SPM/></xsl:when>
			<xsl:when test="(lcCode = 'vc')"><res:idCountryName_VCT/></xsl:when>
			<xsl:when test="(lcCode = 'ws')"><res:idCountryName_WSM/></xsl:when>
			<xsl:when test="(lcCode = 'sm')"><res:idCountryName_SMR/></xsl:when>
			<xsl:when test="(lcCode = 'st')"><res:idCountryName_STP/></xsl:when>
			<xsl:when test="(lcCode = 'sa')"><res:idCountryName_SAU/></xsl:when>
			<xsl:when test="(lcCode = 'sn')"><res:idCountryName_SEN/></xsl:when>
			<xsl:when test="(lcCode = 'rs')"><res:idCountryName_SRB/></xsl:when>
			<xsl:when test="(lcCode = 'sc')"><res:idCountryName_SYC/></xsl:when>
			<xsl:when test="(lcCode = 'sl')"><res:idCountryName_SLE/></xsl:when>
			<xsl:when test="(lcCode = 'sg')"><res:idCountryName_SGP/></xsl:when>
			<xsl:when test="(lcCode = 'sk')"><res:idCountryName_SVK/></xsl:when>
			<xsl:when test="(lcCode = 'si')"><res:idCountryName_SVN/></xsl:when>
			<xsl:when test="(lcCode = 'sb')"><res:idCountryName_SLB/></xsl:when>
			<xsl:when test="(lcCode = 'so')"><res:idCountryName_SOM/></xsl:when>
			<xsl:when test="(lcCode = 'za')"><res:idCountryName_ZAF/></xsl:when>
			<xsl:when test="(lcCode = 'gs')"><res:idCountryName_SGS/></xsl:when>
			<xsl:when test="(lcCode = 'es')"><res:idCountryName_ESP/></xsl:when>
			<xsl:when test="(lcCode = 'lk')"><res:idCountryName_LKA/></xsl:when>
			<xsl:when test="(lcCode = 'sd')"><res:idCountryName_SDN/></xsl:when>
			<xsl:when test="(lcCode = 'sr')"><res:idCountryName_SUR/></xsl:when>
			<xsl:when test="(lcCode = 'sj')"><res:idCountryName_SJM/></xsl:when>
			<xsl:when test="(lcCode = 'sz')"><res:idCountryName_SWZ/></xsl:when>
			<xsl:when test="(lcCode = 'se')"><res:idCountryName_SWE/></xsl:when>
			<xsl:when test="(lcCode = 'ch')"><res:idCountryName_CHE/></xsl:when>
			<xsl:when test="(lcCode = 'sy')"><res:idCountryName_SYR/></xsl:when>
			<xsl:when test="(lcCode = 'tw')"><res:idCountryName_TWN/></xsl:when>
			<xsl:when test="(lcCode = 'tj')"><res:idCountryName_TJK/></xsl:when>
			<xsl:when test="(lcCode = 'tz')"><res:idCountryName_TZA/></xsl:when>
			<xsl:when test="(lcCode = 'th')"><res:idCountryName_THA/></xsl:when>
			<xsl:when test="(lcCode = 'tl')"><res:idCountryName_TLS/></xsl:when>
			<xsl:when test="(lcCode = 'tg')"><res:idCountryName_TGO/></xsl:when>
			<xsl:when test="(lcCode = 'tk')"><res:idCountryName_TKL/></xsl:when>
			<xsl:when test="(lcCode = 'to')"><res:idCountryName_TON/></xsl:when>
			<xsl:when test="(lcCode = 'tt')"><res:idCountryName_TTO/></xsl:when>
			<xsl:when test="(lcCode = 'tn')"><res:idCountryName_TUN/></xsl:when>
			<xsl:when test="(lcCode = 'tr')"><res:idCountryName_TUR/></xsl:when>
			<xsl:when test="(lcCode = 'tm')"><res:idCountryName_TKM/></xsl:when>
			<xsl:when test="(lcCode = 'tc')"><res:idCountryName_TCA/></xsl:when>
			<xsl:when test="(lcCode = 'tv')"><res:idCountryName_TUV/></xsl:when>
			<xsl:when test="(lcCode = 'ug')"><res:idCountryName_UGA/></xsl:when>
			<xsl:when test="(lcCode = 'ua')"><res:idCountryName_UKR/></xsl:when>
			<xsl:when test="(lcCode = 'ae')"><res:idCountryName_ARE/></xsl:when>
			<xsl:when test="(lcCode = 'gb')"><res:idCountryName_GBR/></xsl:when>
			<xsl:when test="(lcCode = 'us')"><res:idCountryName_USA/></xsl:when>
			<xsl:when test="(lcCode = 'um')"><res:idCountryName_UMI/></xsl:when>
			<xsl:when test="(lcCode = 'uy')"><res:idCountryName_URY/></xsl:when>
			<xsl:when test="(lcCode = 'uz')"><res:idCountryName_UZB/></xsl:when>
			<xsl:when test="(lcCode = 'vu')"><res:idCountryName_VUT/></xsl:when>
			<xsl:when test="(lcCode = 've')"><res:idCountryName_VEN/></xsl:when>
			<xsl:when test="(lcCode = 'vn')"><res:idCountryName_VNM/></xsl:when>
			<xsl:when test="(lcCode = 'vg')"><res:idCountryName_VGB/></xsl:when>
			<xsl:when test="(lcCode = 'vi')"><res:idCountryName_VIR/></xsl:when>
			<xsl:when test="(lcCode = 'wf')"><res:idCountryName_WLF/></xsl:when>
			<xsl:when test="(lcCode = 'eh')"><res:idCountryName_ESH/></xsl:when>
			<xsl:when test="(lcCode = 'ye')"><res:idCountryName_YEM/></xsl:when>
			<xsl:when test="(lcCode = 'zm')"><res:idCountryName_ZMB/></xsl:when>
			<xsl:when test="(lcCode = 'zw')"><res:idCountryName_ZWE/></xsl:when>
			<xsl:otherwise> -->
				<xsl:value-of select="."/>
<!--			</xsl:otherwise>
		</xsl:choose>-->
	</xsl:template>
	<xsl:template name="cntry3166_3letter">
		<xsl:param name="code"/>
<!--		<xsl:choose>
			<xsl:when test="(lcCode = 'afg')"><res:idCountryName_AFG/></xsl:when>
			<xsl:when test="(lcCode = 'ala')"><res:idCountryName_ALA/></xsl:when>
			<xsl:when test="(lcCode = 'alb')"><res:idCountryName_ALB/></xsl:when>
			<xsl:when test="(lcCode = 'dza')"><res:idCountryName_DZA/></xsl:when>
			<xsl:when test="(lcCode = 'asm')"><res:idCountryName_ASM/></xsl:when>
			<xsl:when test="(lcCode = 'and')"><res:idCountryName_AND/></xsl:when>
			<xsl:when test="(lcCode = 'ago')"><res:idCountryName_AGO/></xsl:when>
			<xsl:when test="(lcCode = 'aia')"><res:idCountryName_AIA/></xsl:when>
			<xsl:when test="(lcCode = 'ata')"><res:idCountryName_ATA/></xsl:when>
			<xsl:when test="(lcCode = 'atg')"><res:idCountryName_ATG/></xsl:when>
			<xsl:when test="(lcCode = 'arg')"><res:idCountryName_ARG/></xsl:when>
			<xsl:when test="(lcCode = 'arm')"><res:idCountryName_ARM/></xsl:when>
			<xsl:when test="(lcCode = 'abw')"><res:idCountryName_ABW/></xsl:when>
			<xsl:when test="(lcCode = 'aus')"><res:idCountryName_AUS/></xsl:when>
			<xsl:when test="(lcCode = 'aut')"><res:idCountryName_AUT/></xsl:when>
			<xsl:when test="(lcCode = 'aze')"><res:idCountryName_AZE/></xsl:when>
			<xsl:when test="(lcCode = 'bhs')"><res:idCountryName_BHS/></xsl:when>
			<xsl:when test="(lcCode = 'bhr')"><res:idCountryName_BHR/></xsl:when>
			<xsl:when test="(lcCode = 'bgd')"><res:idCountryName_BGD/></xsl:when>
			<xsl:when test="(lcCode = 'brb')"><res:idCountryName_BRB/></xsl:when>
			<xsl:when test="(lcCode = 'blr')"><res:idCountryName_BLR/></xsl:when>
			<xsl:when test="(lcCode = 'bel')"><res:idCountryName_BEL/></xsl:when>
			<xsl:when test="(lcCode = 'blz')"><res:idCountryName_BLZ/></xsl:when>
			<xsl:when test="(lcCode = 'ben')"><res:idCountryName_BEN/></xsl:when>
			<xsl:when test="(lcCode = 'bmu')"><res:idCountryName_BMU/></xsl:when>
			<xsl:when test="(lcCode = 'btn')"><res:idCountryName_BTN/></xsl:when>
			<xsl:when test="(lcCode = 'bol')"><res:idCountryName_BOL/></xsl:when>
			<xsl:when test="(lcCode = 'bih')"><res:idCountryName_BIH/></xsl:when>
			<xsl:when test="(lcCode = 'bwa')"><res:idCountryName_BWA/></xsl:when>
			<xsl:when test="(lcCode = 'bvt')"><res:idCountryName_BVT/></xsl:when>
			<xsl:when test="(lcCode = 'bra')"><res:idCountryName_BRA/></xsl:when>
			<xsl:when test="(lcCode = 'iot')"><res:idCountryName_IOT/></xsl:when>
			<xsl:when test="(lcCode = 'brn')"><res:idCountryName_BRN/></xsl:when>
			<xsl:when test="(lcCode = 'bgr')"><res:idCountryName_BGR/></xsl:when>
			<xsl:when test="(lcCode = 'bfa')"><res:idCountryName_BFA/></xsl:when>
			<xsl:when test="(lcCode = 'bdi')"><res:idCountryName_BDI/></xsl:when>
			<xsl:when test="(lcCode = 'khm')"><res:idCountryName_KHM/></xsl:when>
			<xsl:when test="(lcCode = 'cmr')"><res:idCountryName_CMR/></xsl:when>
			<xsl:when test="(lcCode = 'can')"><res:idCountryName_CAN/></xsl:when>
			<xsl:when test="(lcCode = 'cpv')"><res:idCountryName_CPV/></xsl:when>
			<xsl:when test="(lcCode = 'cym')"><res:idCountryName_CYM/></xsl:when>
			<xsl:when test="(lcCode = 'caf')"><res:idCountryName_CAF/></xsl:when>
			<xsl:when test="(lcCode = 'tcd')"><res:idCountryName_TCD/></xsl:when>
			<xsl:when test="(lcCode = 'chl')"><res:idCountryName_CHL/></xsl:when>
			<xsl:when test="(lcCode = 'chn')"><res:idCountryName_CHN/></xsl:when>
			<xsl:when test="(lcCode = 'cxr')"><res:idCountryName_CXR/></xsl:when>
			<xsl:when test="(lcCode = 'cck')"><res:idCountryName_CCK/></xsl:when>
			<xsl:when test="(lcCode = 'col')"><res:idCountryName_COL/></xsl:when>
			<xsl:when test="(lcCode = 'com')"><res:idCountryName_COM/></xsl:when>
			<xsl:when test="(lcCode = 'cog')"><res:idCountryName_COG/></xsl:when>
			<xsl:when test="(lcCode = 'cod')"><res:idCountryName_COD/></xsl:when>
			<xsl:when test="(lcCode = 'cok')"><res:idCountryName_COK/></xsl:when>
			<xsl:when test="(lcCode = 'cri')"><res:idCountryName_CRI/></xsl:when>
			<xsl:when test="(lcCode = 'civ')"><res:idCountryName_CIV/></xsl:when>
			<xsl:when test="(lcCode = 'hrv')"><res:idCountryName_HRV/></xsl:when>
			<xsl:when test="(lcCode = 'cub')"><res:idCountryName_CUB/></xsl:when>
			<xsl:when test="(lcCode = 'cyp')"><res:idCountryName_CYP/></xsl:when>
			<xsl:when test="(lcCode = 'cze')"><res:idCountryName_CZE/></xsl:when>
			<xsl:when test="(lcCode = 'dnk')"><res:idCountryName_DNK/></xsl:when>
			<xsl:when test="(lcCode = 'dji')"><res:idCountryName_DJI/></xsl:when>
			<xsl:when test="(lcCode = 'dma')"><res:idCountryName_DMA/></xsl:when>
			<xsl:when test="(lcCode = 'dom')"><res:idCountryName_DOM/></xsl:when>
			<xsl:when test="(lcCode = 'ecu')"><res:idCountryName_ECU/></xsl:when>
			<xsl:when test="(lcCode = 'egy')"><res:idCountryName_EGY/></xsl:when>
			<xsl:when test="(lcCode = 'slv')"><res:idCountryName_SLV/></xsl:when>
			<xsl:when test="(lcCode = 'gnq')"><res:idCountryName_GNQ/></xsl:when>
			<xsl:when test="(lcCode = 'eri')"><res:idCountryName_ERI/></xsl:when>
			<xsl:when test="(lcCode = 'est')"><res:idCountryName_EST/></xsl:when>
			<xsl:when test="(lcCode = 'eth')"><res:idCountryName_ETH/></xsl:when>
			<xsl:when test="(lcCode = 'flk')"><res:idCountryName_FLK/></xsl:when>
			<xsl:when test="(lcCode = 'fro')"><res:idCountryName_FRO/></xsl:when>
			<xsl:when test="(lcCode = 'fji')"><res:idCountryName_FJI/></xsl:when>
			<xsl:when test="(lcCode = 'fin')"><res:idCountryName_FIN/></xsl:when>
			<xsl:when test="(lcCode = 'fra')"><res:idCountryName_FRA/></xsl:when>
			<xsl:when test="(lcCode = 'guf')"><res:idCountryName_GUF/></xsl:when>
			<xsl:when test="(lcCode = 'pyf')"><res:idCountryName_PYF/></xsl:when>
			<xsl:when test="(lcCode = 'atf')"><res:idCountryName_ATF/></xsl:when>
			<xsl:when test="(lcCode = 'gab')"><res:idCountryName_GAB/></xsl:when>
			<xsl:when test="(lcCode = 'gmb')"><res:idCountryName_GMB/></xsl:when>
			<xsl:when test="(lcCode = 'geo')"><res:idCountryName_GEO/></xsl:when>
			<xsl:when test="(lcCode = 'deu')"><res:idCountryName_DEU/></xsl:when>
			<xsl:when test="(lcCode = 'gha')"><res:idCountryName_GHA/></xsl:when>
			<xsl:when test="(lcCode = 'gib')"><res:idCountryName_GIB/></xsl:when>
			<xsl:when test="(lcCode = 'grc')"><res:idCountryName_GRC/></xsl:when>
			<xsl:when test="(lcCode = 'grl')"><res:idCountryName_GRL/></xsl:when>
			<xsl:when test="(lcCode = 'grd')"><res:idCountryName_GRD/></xsl:when>
			<xsl:when test="(lcCode = 'glp')"><res:idCountryName_GLP/></xsl:when>
			<xsl:when test="(lcCode = 'gum')"><res:idCountryName_GUM/></xsl:when>
			<xsl:when test="(lcCode = 'gtm')"><res:idCountryName_GTM/></xsl:when>
			<xsl:when test="(lcCode = 'ggy')"><res:idCountryName_GGY/></xsl:when>
			<xsl:when test="(lcCode = 'gin')"><res:idCountryName_GIN/></xsl:when>
			<xsl:when test="(lcCode = 'gnb')"><res:idCountryName_GNB/></xsl:when>
			<xsl:when test="(lcCode = 'guy')"><res:idCountryName_GUY/></xsl:when>
			<xsl:when test="(lcCode = 'hti')"><res:idCountryName_HTI/></xsl:when>
			<xsl:when test="(lcCode = 'hmd')"><res:idCountryName_HMD/></xsl:when>
			<xsl:when test="(lcCode = 'vat')"><res:idCountryName_VAT/></xsl:when>
			<xsl:when test="(lcCode = 'hnd')"><res:idCountryName_HND/></xsl:when>
			<xsl:when test="(lcCode = 'hkg')"><res:idCountryName_HKG/></xsl:when>
			<xsl:when test="(lcCode = 'hun') "><res:idCountryName_HUN/></xsl:when>
			<xsl:when test="(lcCode = 'isl')"><res:idCountryName_ISL/></xsl:when>
			<xsl:when test="(lcCode = 'ind')"><res:idCountryName_IND/></xsl:when>
			<xsl:when test="(lcCode = 'idn')"><res:idCountryName_IDN/></xsl:when>
			<xsl:when test="(lcCode = 'irn')"><res:idCountryName_IRN/></xsl:when>
			<xsl:when test="(lcCode = 'irq')"><res:idCountryName_IRQ/></xsl:when>
			<xsl:when test="(lcCode = 'irl')"><res:idCountryName_IRL/></xsl:when>
			<xsl:when test="(lcCode = 'imn')"><res:idCountryName_IMN/></xsl:when>
			<xsl:when test="(lcCode = 'isr')"><res:idCountryName_ISR/></xsl:when>
			<xsl:when test="(lcCode = 'ita')"><res:idCountryName_ITA/></xsl:when>
			<xsl:when test="(lcCode = 'jam')"><res:idCountryName_JAM/></xsl:when>
			<xsl:when test="(lcCode = 'jpn')"><res:idCountryName_JPN/></xsl:when>
			<xsl:when test="(lcCode = 'jey')"><res:idCountryName_JEY/></xsl:when>
			<xsl:when test="(lcCode = 'jor')"><res:idCountryName_JOR/></xsl:when>
			<xsl:when test="(lcCode = 'kaz')"><res:idCountryName_KAZ/></xsl:when>
			<xsl:when test="(lcCode = 'ken')"><res:idCountryName_KEN/></xsl:when>
			<xsl:when test="(lcCode = 'kir')"><res:idCountryName_KIR/></xsl:when>
			<xsl:when test="(lcCode = 'prk')"><res:idCountryName_PRK/></xsl:when>
			<xsl:when test="(lcCode = 'kor')"><res:idCountryName_KOR/></xsl:when>
			<xsl:when test="(lcCode = 'kwt')"><res:idCountryName_KWT/></xsl:when>
			<xsl:when test="(lcCode = 'kgz')"><res:idCountryName_KGZ/></xsl:when>
			<xsl:when test="(lcCode = 'lao')"><res:idCountryName_LAO/></xsl:when>
			<xsl:when test="(lcCode = 'lva')"><res:idCountryName_LVA/></xsl:when>
			<xsl:when test="(lcCode = 'lbn')"><res:idCountryName_LBN/></xsl:when>
			<xsl:when test="(lcCode = 'lso')"><res:idCountryName_LSO/></xsl:when>
			<xsl:when test="(lcCode = 'lbr')"><res:idCountryName_LBR/></xsl:when>
			<xsl:when test="(lcCode = 'lby')"><res:idCountryName_LBY/></xsl:when>
			<xsl:when test="(lcCode = 'lie')"><res:idCountryName_LIE/></xsl:when>
			<xsl:when test="(lcCode = 'ltu')"><res:idCountryName_LTU/></xsl:when>
			<xsl:when test="(lcCode = 'lux')"><res:idCountryName_LUX/></xsl:when>
			<xsl:when test="(lcCode = 'mac')"><res:idCountryName_MAC/></xsl:when>
			<xsl:when test="(lcCode = 'mkd')"><res:idCountryName_MKD/></xsl:when>
			<xsl:when test="(lcCode = 'mdg')"><res:idCountryName_MDG/></xsl:when>
			<xsl:when test="(lcCode = 'mwi')"><res:idCountryName_MWI/></xsl:when>
			<xsl:when test="(lcCode = 'mys')"><res:idCountryName_MYS/></xsl:when>
			<xsl:when test="(lcCode = 'mdv')"><res:idCountryName_MDV/></xsl:when>
			<xsl:when test="(lcCode = 'mli')"><res:idCountryName_MLI/></xsl:when>
			<xsl:when test="(lcCode = 'mlt')"><res:idCountryName_MLT/></xsl:when>
			<xsl:when test="(lcCode = 'mhl')"><res:idCountryName_MHL/></xsl:when>
			<xsl:when test="(lcCode = 'mtq')"><res:idCountryName_MTQ/></xsl:when>
			<xsl:when test="(lcCode = 'mrt')"><res:idCountryName_MRT/></xsl:when>
			<xsl:when test="(lcCode = 'mus')"><res:idCountryName_MUS/></xsl:when>
			<xsl:when test="(lcCode = 'myt')"><res:idCountryName_MYT/></xsl:when>
			<xsl:when test="(lcCode = 'mex')"><res:idCountryName_MEX/></xsl:when>
			<xsl:when test="(lcCode = 'fsm')"><res:idCountryName_FSM/></xsl:when>
			<xsl:when test="(lcCode = 'mda')"><res:idCountryName_MDA/></xsl:when>
			<xsl:when test="(lcCode = 'mco')"><res:idCountryName_MCO/></xsl:when>
			<xsl:when test="(lcCode = 'mng')"><res:idCountryName_MNG/></xsl:when>
			<xsl:when test="(lcCode = 'mne')"><res:idCountryName_MNE/></xsl:when>
			<xsl:when test="(lcCode = 'msr')"><res:idCountryName_MSR/></xsl:when>
			<xsl:when test="(lcCode = 'mar')"><res:idCountryName_MAR/></xsl:when>
			<xsl:when test="(lcCode = 'moz')"><res:idCountryName_MOZ/></xsl:when>
			<xsl:when test="(lcCode = 'mmr')"><res:idCountryName_MMR/></xsl:when>
			<xsl:when test="(lcCode = 'nam')"><res:idCountryName_NAM/></xsl:when>
			<xsl:when test="(lcCode = 'nru')"><res:idCountryName_NRU/></xsl:when>
			<xsl:when test="(lcCode = 'npl')"><res:idCountryName_NPL/></xsl:when>
			<xsl:when test="(lcCode = 'nld')"><res:idCountryName_NLD/></xsl:when>
			<xsl:when test="(lcCode = 'ant')"><res:idCountryName_ANT/></xsl:when>
			<xsl:when test="(lcCode = 'ncl')"><res:idCountryName_NCL/></xsl:when>
			<xsl:when test="(lcCode = 'nzl')"><res:idCountryName_NZL/></xsl:when>
			<xsl:when test="(lcCode = 'nic')"><res:idCountryName_NIC/></xsl:when>
			<xsl:when test="(lcCode = 'ner')"><res:idCountryName_NER/></xsl:when>
			<xsl:when test="(lcCode = 'nga')"><res:idCountryName_NGA/></xsl:when>
			<xsl:when test="(lcCode = 'niu')"><res:idCountryName_NIU/></xsl:when>
			<xsl:when test="(lcCode = 'nfk')"><res:idCountryName_NFK/></xsl:when>
			<xsl:when test="(lcCode = 'mnp')"><res:idCountryName_MNP/></xsl:when>
			<xsl:when test="(lcCode = 'nor')"><res:idCountryName_NOR/></xsl:when>
			<xsl:when test="(lcCode = 'omn')"><res:idCountryName_OMN/></xsl:when>
			<xsl:when test="(lcCode = 'pak')"><res:idCountryName_PAK/></xsl:when>
			<xsl:when test="(lcCode = 'plw')"><res:idCountryName_PLW/></xsl:when>
			<xsl:when test="(lcCode = 'pse')"><res:idCountryName_PSE/></xsl:when>
			<xsl:when test="(lcCode = 'pan')"><res:idCountryName_PAN/></xsl:when>
			<xsl:when test="(lcCode = 'png')"><res:idCountryName_PNG/></xsl:when>
			<xsl:when test="(lcCode = 'pry')"><res:idCountryName_PRY/></xsl:when>
			<xsl:when test="(lcCode = 'per')"><res:idCountryName_PER/></xsl:when>
			<xsl:when test="(lcCode = 'phl')"><res:idCountryName_PHL/></xsl:when>
			<xsl:when test="(lcCode = 'pcn')"><res:idCountryName_PCN/></xsl:when>
			<xsl:when test="(lcCode = 'pol')"><res:idCountryName_POL/></xsl:when>
			<xsl:when test="(lcCode = 'prt')"><res:idCountryName_PRT/></xsl:when>
			<xsl:when test="(lcCode = 'pri')"><res:idCountryName_PRI/></xsl:when>
			<xsl:when test="(lcCode = 'qat')"><res:idCountryName_QAT/></xsl:when>
			<xsl:when test="(lcCode = 'reu')"><res:idCountryName_REU/></xsl:when>
			<xsl:when test="(lcCode = 'rou')"><res:idCountryName_ROU/></xsl:when>
			<xsl:when test="(lcCode = 'rus')"><res:idCountryName_RUS/></xsl:when>
			<xsl:when test="(lcCode = 'rwa')"><res:idCountryName_RWA/></xsl:when>
			<xsl:when test="(lcCode = 'blm')"><res:idCountryName_BLM/></xsl:when>
			<xsl:when test="(lcCode = 'shn')"><res:idCountryName_SHN/></xsl:when>
			<xsl:when test="(lcCode = 'kna')"><res:idCountryName_KNA/></xsl:when>
			<xsl:when test="(lcCode = 'lca')"><res:idCountryName_LCA/></xsl:when>
			<xsl:when test="(lcCode = 'maf')"><res:idCountryName_MAF/></xsl:when>
			<xsl:when test="(lcCode = 'spm')"><res:idCountryName_SPM/></xsl:when>
			<xsl:when test="(lcCode = 'vct')"><res:idCountryName_VCT/></xsl:when>
			<xsl:when test="(lcCode = 'wsm')"><res:idCountryName_WSM/></xsl:when>
			<xsl:when test="(lcCode = 'smr')"><res:idCountryName_SMR/></xsl:when>
			<xsl:when test="(lcCode = 'stp')"><res:idCountryName_STP/></xsl:when>
			<xsl:when test="(lcCode = 'sau')"><res:idCountryName_SAU/></xsl:when>
			<xsl:when test="(lcCode = 'sen')"><res:idCountryName_SEN/></xsl:when>
			<xsl:when test="(lcCode = 'srb')"><res:idCountryName_SRB/></xsl:when>
			<xsl:when test="(lcCode = 'syc')"><res:idCountryName_SYC/></xsl:when>
			<xsl:when test="(lcCode = 'sle')"><res:idCountryName_SLE/></xsl:when>
			<xsl:when test="(lcCode = 'sgp')"><res:idCountryName_SGP/></xsl:when>
			<xsl:when test="(lcCode = 'svk')"><res:idCountryName_SVK/></xsl:when>
			<xsl:when test="(lcCode = 'svn')"><res:idCountryName_SVN/></xsl:when>
			<xsl:when test="(lcCode = 'slb')"><res:idCountryName_SLB/></xsl:when>
			<xsl:when test="(lcCode = 'som')"><res:idCountryName_SOM/></xsl:when>
			<xsl:when test="(lcCode = 'zaf')"><res:idCountryName_ZAF/></xsl:when>
			<xsl:when test="(lcCode = 'sgs')"><res:idCountryName_SGS/></xsl:when>
			<xsl:when test="(lcCode = 'esp')"><res:idCountryName_ESP/></xsl:when>
			<xsl:when test="(lcCode = 'lka')"><res:idCountryName_LKA/></xsl:when>
			<xsl:when test="(lcCode = 'sdn')"><res:idCountryName_SDN/></xsl:when>
			<xsl:when test="(lcCode = 'sur')"><res:idCountryName_SUR/></xsl:when>
			<xsl:when test="(lcCode = 'sjm')"><res:idCountryName_SJM/></xsl:when>
			<xsl:when test="(lcCode = 'swz')"><res:idCountryName_SWZ/></xsl:when>
			<xsl:when test="(lcCode = 'swe')"><res:idCountryName_SWE/></xsl:when>
			<xsl:when test="(lcCode = 'che')"><res:idCountryName_CHE/></xsl:when>
			<xsl:when test="(lcCode = 'syr')"><res:idCountryName_SYR/></xsl:when>
			<xsl:when test="(lcCode = 'twn')"><res:idCountryName_TWN/></xsl:when>
			<xsl:when test="(lcCode = 'tjk')"><res:idCountryName_TJK/></xsl:when>
			<xsl:when test="(lcCode = 'tza')"><res:idCountryName_TZA/></xsl:when>
			<xsl:when test="(lcCode = 'tha')"><res:idCountryName_THA/></xsl:when>
			<xsl:when test="(lcCode = 'tls')"><res:idCountryName_TLS/></xsl:when>
			<xsl:when test="(lcCode = 'tgo')"><res:idCountryName_TGO/></xsl:when>
			<xsl:when test="(lcCode = 'tkl')"><res:idCountryName_TKL/></xsl:when>
			<xsl:when test="(lcCode = 'ton')"><res:idCountryName_TON/></xsl:when>
			<xsl:when test="(lcCode = 'tto')"><res:idCountryName_TTO/></xsl:when>
			<xsl:when test="(lcCode = 'tun')"><res:idCountryName_TUN/></xsl:when>
			<xsl:when test="(lcCode = 'tur')"><res:idCountryName_TUR/></xsl:when>
			<xsl:when test="(lcCode = 'tkm')"><res:idCountryName_TKM/></xsl:when>
			<xsl:when test="(lcCode = 'tca')"><res:idCountryName_TCA/></xsl:when>
			<xsl:when test="(lcCode = 'tuv')"><res:idCountryName_TUV/></xsl:when>
			<xsl:when test="(lcCode = 'uga')"><res:idCountryName_UGA/></xsl:when>
			<xsl:when test="(lcCode = 'ukr')"><res:idCountryName_UKR/></xsl:when>
			<xsl:when test="(lcCode = 'are')"><res:idCountryName_ARE/></xsl:when>
			<xsl:when test="(lcCode = 'gbr')"><res:idCountryName_GBR/></xsl:when>
			<xsl:when test="(lcCode = 'usa')"><res:idCountryName_USA/></xsl:when>
			<xsl:when test="(lcCode = 'umi')"><res:idCountryName_UMI/></xsl:when>
			<xsl:when test="(lcCode = 'ury')"><res:idCountryName_URY/></xsl:when>
			<xsl:when test="(lcCode = 'uzb')"><res:idCountryName_UZB/></xsl:when>
			<xsl:when test="(lcCode = 'vut')"><res:idCountryName_VUT/></xsl:when>
			<xsl:when test="(lcCode = 'ven')"><res:idCountryName_VEN/></xsl:when>
			<xsl:when test="(lcCode = 'vnm')"><res:idCountryName_VNM/></xsl:when>
			<xsl:when test="(lcCode = 'vgb')"><res:idCountryName_VGB/></xsl:when>
			<xsl:when test="(lcCode = 'vir')"><res:idCountryName_VIR/></xsl:when>
			<xsl:when test="(lcCode = 'wlf')"><res:idCountryName_WLF/></xsl:when>
			<xsl:when test="(lcCode = 'esh')"><res:idCountryName_ESH/></xsl:when>
			<xsl:when test="(lcCode = 'yem')"><res:idCountryName_YEM/></xsl:when>
			<xsl:when test="(lcCode = 'zmb')"><res:idCountryName_ZMB/></xsl:when>
			<xsl:when test="(lcCode = 'zwe')"><res:idCountryName_ZWE/></xsl:when>
			<xsl:otherwise>-->
				<xsl:value-of select="."/>
<!--			</xsl:otherwise>
		</xsl:choose>-->
	</xsl:template>
</xsl:stylesheet>