define({
  "sourceSetting": "Pengaturan sumber pencarian",
  "instruction": "Tambah dan konfigurasikan geocode service atau feature layer fitur sebagai sumber pencarian. Sumber yang ditentukan ini menentukan apa yang dapat dicari dalam kotak pencarian.",
  "add": "Tambahkan sumber pencarian",
  "addGeocoder": "Tambahkan geocoder",
  "geocoder": "Geocoder",
  "setLayerSource": "Atur sumber layer",
  "setGeocoderURL": "Atur URL geocoder",
  "searchableLayer": "Feature layer",
  "name": "Nama",
  "countryCode": "Kode negara atau wilayah",
  "countryCodeEg": "mis. ",
  "countryCodeHint": "Membiarkan nilai ini kosong berarti akan mencari semua negara dan wilayah",
  "generalSetting": "Pengaturan umum",
  "allPlaceholder": "Teks placehoder untuk mencari semua: ",
  "showInfoWindowOnSelect": "Tampilkan pop-up untuk fitur atau lokasi yang ditemukan",
  "searchInCurrentMapExtent": "Cari hanya dalam jangkauan peta saat ini",
  "zoomScale": "Skala zoom",
  "locatorUrl": "URL Geocoder",
  "locatorName": "Nama geocoder",
  "locatorExample": "Contoh",
  "locatorWarning": "Versi service geocoding ini tidak didukung. Widget mendukung service geocoding 10.1 dan di atasnya.",
  "locatorTips": "Saran tidak tersedia karena geocode service tidak mendukung kemampuan saran.",
  "layerSource": "Sumber layer",
  "searchLayerTips": "Saran tidak tersedia karena feature service tidak mendukung kemampuan penomoran halaman.",
  "placeholder": "Teks placeholder",
  "searchFields": "Kolom pencarian",
  "displayField": "Kolom tampilan",
  "exactMatch": "Persis",
  "maxSuggestions": "Saran maksimum",
  "maxResults": "Hasil maksimum",
  "enableLocalSearch": "Aktifkan pencarian lokal",
  "minScale": "Skala min",
  "minScaleHint": "Apabila skala peta lebih besar daripada skala ini, pencarian lokal akan diterapkan",
  "radius": "Radius",
  "radiusHint": "Menentukan radius dari area di sekitar pusat peta saat ini yang digunakan untuk mendorong peringkat calon geocoding sehingga calon terdekat dengan lokasi dimunculkan terlebih dahulu",
  "meters": "Meter",
  "setSearchFields": "Atur kolom pencarian",
  "set": "Atur",
  "fieldSearchable": "dapat dicari",
  "fieldName": "Nama",
  "fieldAlias": "Alias",
  "ok": "YA",
  "cancel": "Batal",
  "invalidUrlTip": "URL ${URL} tidak valid atau tidak dapat diakses."
});