/* See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * Esri Inc. licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.esri.geoportal.dcat3;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang3.StringUtils;

import com.esri.geoportal.dcat3.model.Dcat3Constants;
import com.esri.geoportal.dcat3.model.Dcat3ContactPoint;
import com.esri.geoportal.dcat3.model.Dcat3Organization;

/**
 * DCAT-US 3.0 configuration.
 *
 * <p>Spring managed bean (see <code>config/app-dcat3.xml</code>) holding all
 * catalog-wide defaults required by the DCAT-US 3.0 profile that cannot be
 * derived from the metadata index.</p>
 */
public class Dcat3Config {

  /* -------------------------------------------------------------- */
  /* Profile                                                        */
  /* -------------------------------------------------------------- */

  private String context = Dcat3Constants.DEFAULT_CONTEXT;
  private String conformsTo = Dcat3Constants.DEFAULT_CONFORMS_TO;
  private String describedBy = Dcat3Constants.DEFAULT_DESCRIBED_BY;

  /* -------------------------------------------------------------- */
  /* Catalog                                                        */
  /* -------------------------------------------------------------- */

  private String baseUrl = "http://localhost:8080/geoportal";
  private String catalogTitle = "Geoportal Catalog";
  private String catalogDescription = "DCAT-US 3.0 catalog generated by Esri Geoportal Server.";
  private String catalogIdentifier;
  private String homepage;
  private String language = "en-US";

  /* -------------------------------------------------------------- */
  /* Resource defaults                                              */
  /* -------------------------------------------------------------- */

  private String publisherName = "Your Publisher";
  private String publisherId;
  private String contactName = "Your contact point";
  private String contactEmail = "email@your.org";
  private String license = "http://www.usa.gov/publicdomain/label/1.0/";
  private String rights;
  private String accessLevel = Dcat3Constants.ACCESS_LEVEL_PUBLIC;
  private List<String> bureauCode = new ArrayList<>(List.of("010:04"));
  private List<String> programCode = new ArrayList<>(List.of("010:000"));
  private List<String> defaultKeywords = new ArrayList<>(List.of("metadata"));
  private String accrualPeriodicity;

  /* -------------------------------------------------------------- */
  /* Behavior                                                       */
  /* -------------------------------------------------------------- */

  /** Number of records fetched from the index per page. */
  private int pageSize = 100;

  /** Emit <code>dcat:DatasetSeries</code> entries derived from collections. */
  private boolean includeDatasetSeries = true;

  /** Emit <code>dcat:DataService</code> entries derived from service resources. */
  private boolean includeDataServices = true;

  /** Emit only publicly accessible / approved records. */
  private boolean publicRecordsOnly = true;

  /** Pretty print the generated document. */
  private boolean prettyPrint = true;

  /* -------------------------------------------------------------- */
  /* Derived helpers                                                */
  /* -------------------------------------------------------------- */

  /**
   * Builds a fresh publisher instance for a resource.
   * @return publisher or <code>null</code> when not configured
   */
  public Dcat3Organization newPublisher() {
    if (StringUtils.isBlank(publisherName)) return null;
    Dcat3Organization org = new Dcat3Organization(publisherName);
    org.atId = StringUtils.trimToNull(publisherId);
    return org;
  }

  /**
   * Builds a fresh contact point instance for a resource.
   * @return contact point or <code>null</code> when not configured
   */
  public Dcat3ContactPoint newContactPoint() {
    if (StringUtils.isBlank(contactName) && StringUtils.isBlank(contactEmail)) return null;
    return new Dcat3ContactPoint(StringUtils.trimToNull(contactName), StringUtils.trimToNull(contactEmail));
  }

  /**
   * Root URL of the DCAT-US 3.0 endpoints.
   * @return e.g. <code>http://host/geoportal/dcat3</code>
   */
  public String getDcat3BaseUrl() {
    return StringUtils.removeEnd(StringUtils.defaultString(baseUrl), "/") + "/dcat3";
  }

  /**
   * URL of a geoportal metadata item.
   * @param id the item id
   * @return the item URL
   */
  public String getItemUrl(String id) {
    return StringUtils.removeEnd(StringUtils.defaultString(baseUrl), "/")
            + "/rest/metadata/item/" + java.net.URLEncoder.encode(
                    StringUtils.defaultString(id), java.nio.charset.StandardCharsets.UTF_8);
  }

  /* -------------------------------------------------------------- */
  /* Getters / setters                                              */
  /* -------------------------------------------------------------- */

  public String getContext() { return context; }
  public void setContext(String context) { this.context = context; }

  public String getConformsTo() { return conformsTo; }
  public void setConformsTo(String conformsTo) { this.conformsTo = conformsTo; }

  public String getDescribedBy() { return describedBy; }
  public void setDescribedBy(String describedBy) { this.describedBy = describedBy; }

  public String getBaseUrl() { return baseUrl; }
  public void setBaseUrl(String baseUrl) { this.baseUrl = baseUrl; }

  public String getCatalogTitle() { return catalogTitle; }
  public void setCatalogTitle(String catalogTitle) { this.catalogTitle = catalogTitle; }

  public String getCatalogDescription() { return catalogDescription; }
  public void setCatalogDescription(String catalogDescription) { this.catalogDescription = catalogDescription; }

  public String getCatalogIdentifier() { return catalogIdentifier; }
  public void setCatalogIdentifier(String catalogIdentifier) { this.catalogIdentifier = catalogIdentifier; }

  public String getHomepage() { return homepage; }
  public void setHomepage(String homepage) { this.homepage = homepage; }

  public String getLanguage() { return language; }
  public void setLanguage(String language) { this.language = language; }

  public String getPublisherName() { return publisherName; }
  public void setPublisherName(String publisherName) { this.publisherName = publisherName; }

  public String getPublisherId() { return publisherId; }
  public void setPublisherId(String publisherId) { this.publisherId = publisherId; }

  public String getContactName() { return contactName; }
  public void setContactName(String contactName) { this.contactName = contactName; }

  public String getContactEmail() { return contactEmail; }
  public void setContactEmail(String contactEmail) { this.contactEmail = contactEmail; }

  public String getLicense() { return license; }
  public void setLicense(String license) { this.license = license; }

  public String getRights() { return rights; }
  public void setRights(String rights) { this.rights = rights; }

  public String getAccessLevel() { return accessLevel; }
  public void setAccessLevel(String accessLevel) { this.accessLevel = accessLevel; }

  public List<String> getBureauCode() { return bureauCode; }
  public void setBureauCode(List<String> bureauCode) { this.bureauCode = bureauCode; }

  public List<String> getProgramCode() { return programCode; }
  public void setProgramCode(List<String> programCode) { this.programCode = programCode; }

  public List<String> getDefaultKeywords() { return defaultKeywords; }
  public void setDefaultKeywords(List<String> defaultKeywords) { this.defaultKeywords = defaultKeywords; }

  public String getAccrualPeriodicity() { return accrualPeriodicity; }
  public void setAccrualPeriodicity(String accrualPeriodicity) { this.accrualPeriodicity = accrualPeriodicity; }

  public int getPageSize() { return pageSize; }
  public void setPageSize(int pageSize) { this.pageSize = pageSize > 0 ? pageSize : 100; }

  public boolean getIncludeDatasetSeries() { return includeDatasetSeries; }
  public void setIncludeDatasetSeries(boolean includeDatasetSeries) { this.includeDatasetSeries = includeDatasetSeries; }

  public boolean getIncludeDataServices() { return includeDataServices; }
  public void setIncludeDataServices(boolean includeDataServices) { this.includeDataServices = includeDataServices; }

  public boolean getPublicRecordsOnly() { return publicRecordsOnly; }
  public void setPublicRecordsOnly(boolean publicRecordsOnly) { this.publicRecordsOnly = publicRecordsOnly; }

  public boolean getPrettyPrint() { return prettyPrint; }
  public void setPrettyPrint(boolean prettyPrint) { this.prettyPrint = prettyPrint; }
}
