/* See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * Esri Inc. licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.esri.geoportal.dcat3;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.esri.geoportal.dcat3.model.Dcat3Constants;
import com.esri.geoportal.dcat3.model.Dcat3ContactPoint;
import com.esri.geoportal.dcat3.model.Dcat3Organization;
import com.fasterxml.jackson.databind.JsonNode;

/**
 * DCAT-US 3.0 configuration.
 *
 * <p>Spring managed bean (see <code>config/app-dcat3.xml</code>) holding all
 * catalog-wide defaults required by the DCAT-US 3.0 profile that cannot be
 * derived from the metadata index.</p>
 */
public class Dcat3Config {

  private static final Logger LOGGER = LoggerFactory.getLogger(Dcat3Config.class);

  private static final String DEFAULT_MAPPING_CONFIG_PATH = "service/config/dcat3.json";

  /* -------------------------------------------------------------- */
  /* Profile                                                        */
  /* -------------------------------------------------------------- */

  private String context = Dcat3Constants.DEFAULT_CONTEXT;
  private String conformsTo = Dcat3Constants.DEFAULT_CONFORMS_TO;
  private String describedBy = Dcat3Constants.DEFAULT_DESCRIBED_BY;

  /* -------------------------------------------------------------- */
  /* Catalog                                                        */
  /* -------------------------------------------------------------- */

  private String baseUrl = "http://localhost:8080/geoportal";
  private String catalogTitle = "Geoportal Catalog";
  private String catalogDescription = "DCAT-US 3.0 catalog generated by Esri Geoportal Server.";
  private String catalogIdentifier;
  private String homepage;
  private String language = "en-US";

  /* -------------------------------------------------------------- */
  /* Resource defaults                                              */
  /* -------------------------------------------------------------- */

  private String publisherName = "Your Publisher";
  private String publisherId;
  private String contactName = "Your contact point";
  private String contactEmail = "email@your.org";
  private String license = "http://www.usa.gov/publicdomain/label/1.0/";
  private String rights;
  private String accessLevel = Dcat3Constants.ACCESS_LEVEL_PUBLIC;
  private List<String> bureauCode = new ArrayList<>(List.of("010:04"));
  private List<String> programCode = new ArrayList<>(List.of("010:000"));
  private List<String> defaultKeywords = new ArrayList<>(List.of("metadata"));
  private String accrualPeriodicity;

  /* -------------------------------------------------------------- */
  /* Behavior                                                       */
  /* -------------------------------------------------------------- */

  /** Number of records fetched from the index per page. */
  private int pageSize = 100;

  /** Emit <code>dcat:DatasetSeries</code> entries derived from collections. */
  private boolean includeDatasetSeries = true;

  /** Emit <code>dcat:DataService</code> entries derived from service resources. */
  private boolean includeDataServices = true;

  /** Emit only publicly accessible / approved records. */
  private boolean publicRecordsOnly = true;

  /** Pretty print the generated document. */
  private boolean prettyPrint = true;

  /** Classpath resource with dcat3 field mappings and property order. */
  private String mappingConfigPath = DEFAULT_MAPPING_CONFIG_PATH;

  /** Configurable source-field aliases used by DCAT3 mapping code. */
  private Map<String, String> sourceFieldMappings = new LinkedHashMap<>(Map.ofEntries(
      Map.entry("query.sysAccess", "sys_access_s"),
      Map.entry("query.approvalStatus", "sys_approval_status_s"),
      Map.entry("query.collectionMembership", "src_collections_s"),
      Map.entry("dataset.title", "title"),
      Map.entry("dataset.description", "description"),
      Map.entry("dataset.keywords", "keywords_s"),
      Map.entry("dataset.theme", "itemType_s"),
      Map.entry("dataset.fileId", "fileid"),
      Map.entry("dataset.created", "sys_created_dt"),
      Map.entry("dataset.createdFallback", "sys_created_dt"),
      Map.entry("dataset.modified", "sys_modified_dt"),
      Map.entry("dataset.modifiedFallback", "sys_modified_dt"),
      Map.entry("dataset.rights", "rights_s"),
      Map.entry("dataset.envelope", "envelope_geo"),
      Map.entry("dataset.timePeriod", "timeperiod_nst"),
      Map.entry("dataset.metadataType", "sys_metadatatype_s"),
      Map.entry("dataset.thumbnail", "thumbnail_s"),
      Map.entry("dataset.resources", "resources_nst"),
      Map.entry("dataset.resource.url", "url_s"),
      Map.entry("dataset.resource.urlType", "url_type_s"),
      Map.entry("collection.id", "id"),
      Map.entry("collection.identifier", "identifier"),
      Map.entry("collection.title", "title"),
      Map.entry("collection.name", "name"),
      Map.entry("collection.description", "description"),
      Map.entry("collection.created", "created"),
      Map.entry("collection.createdFallback", "sys_created_dt"),
      Map.entry("collection.updated", "updated"),
      Map.entry("collection.updatedFallback", "sys_modified_dt"),
      Map.entry("collection.accrualPeriodicity", "accrualPeriodicity"),
      Map.entry("collection.envelope", "envelope_geo"),
      Map.entry("collection.timePeriod", "timeperiod_nst")
  ));

  /** Configurable JSON class property ordering by model type. */
  private Map<String, List<String>> classProperty = new LinkedHashMap<>(Map.ofEntries(
      Map.entry("Dcat3Resource", List.of("@id", "@type", "identifier", "title", "description",
          "issued", "modified", "keyword", "theme", "language", "publisher",
          "creator", "contactPoint", "landingPage", "license", "rights", "accessLevel",
          "accessRights", "accessLevelComment", "bureauCode", "programCode")),
      Map.entry("Dcat3Catalog", List.of("dataset", "conformsTo", "homepage", "issued",
          "language", "modified", "rights", "spatial", "themeTaxonomy")),
      Map.entry("Dcat3Dataset", List.of("@id", "@type", "identifier", "title", "description",
          "contactPoint", "accessRestriction", "cuiRestriction", "describedBy",
          "distribution", "inventoried", "keyword", "landingPage", "license",
          "modified", "publisher", "rights", "spatial", "temporal", "theme",
          "useRestriction")),
      Map.entry("Dcat3Distribution", List.of("title", "description", "accessURL", "accessRestriction",
          "cuiRestriction", "describedBy", "format", "license", "modified",
          "rights", "useRestriction")),
      Map.entry("Dcat3DataService", List.of("@id", "@type", "identifier", "title", "description",
          "endpointURL", "endpointDescription", "servesDataset", "conformsTo",
          "format", "mediaType", "issued", "modified", "keyword", "theme", "language",
          "publisher", "creator", "contactPoint", "landingPage", "license", "rights",
          "accessRights", "accessLevel", "accessLevelComment", "bureauCode", "programCode")),
      Map.entry("Dcat3DatasetSeries", List.of("@id", "@type", "title", "description", "issued",
          "modified", "accrualPeriodicity", "publisher", "contactPoint", "spatial",
          "temporal", "seriesMember", "first", "last")),
      Map.entry("Dcat3Organization", List.of("@id", "@type", "name", "subOrganizationOf")),
      Map.entry("Dcat3PeriodOfTime", List.of("@id", "@type", "startDate", "endDate"))
  ));

  public Dcat3Config() {
    loadMappingConfig();
  }

  /* -------------------------------------------------------------- */
  /* Derived helpers                                                */
  /* -------------------------------------------------------------- */

  /**
   * Builds a fresh publisher instance for a resource.
   * @return publisher or <code>null</code> when not configured
   */
  public Dcat3Organization newPublisher() {
    if (StringUtils.isBlank(publisherName)) return null;
    Dcat3Organization org = new Dcat3Organization(publisherName);
    org.atId = StringUtils.trimToNull(publisherId);
    return org;
  }

  /**
   * Builds a fresh contact point instance for a resource.
   * @return contact point or <code>null</code> when not configured
   */
  public Dcat3ContactPoint newContactPoint() {
    if (StringUtils.isBlank(contactName) && StringUtils.isBlank(contactEmail)) return null;
    return new Dcat3ContactPoint(StringUtils.trimToNull(contactName), StringUtils.trimToNull(contactEmail));
  }

  /**
   * Root URL of the DCAT-US 3.0 endpoints.
   * @return e.g. <code>http://host/geoportal/dcat3</code>
   */
  public String getDcat3BaseUrl() {
    return removeTrailingSlash(StringUtils.defaultString(baseUrl)) + "/dcat3";
  }

  /**
   * URL of a geoportal metadata item.
   * @param id the item id
   * @return the item URL
   */
  public String getItemUrl(String id) {
    return removeTrailingSlash(StringUtils.defaultString(baseUrl))
            + "/rest/metadata/item/" + java.net.URLEncoder.encode(
                    StringUtils.defaultString(id), java.nio.charset.StandardCharsets.UTF_8);
  }

  /* -------------------------------------------------------------- */
  /* Getters / setters                                              */
  /* -------------------------------------------------------------- */

  public String getContext() { return context; }
  public void setContext(String context) { this.context = context; }

  public String getConformsTo() { return conformsTo; }
  public void setConformsTo(String conformsTo) { this.conformsTo = conformsTo; }

  public String getDescribedBy() { return describedBy; }
  public void setDescribedBy(String describedBy) { this.describedBy = describedBy; }

  public String getBaseUrl() { return baseUrl; }
  public void setBaseUrl(String baseUrl) { this.baseUrl = baseUrl; }

  public String getCatalogTitle() { return catalogTitle; }
  public void setCatalogTitle(String catalogTitle) { this.catalogTitle = catalogTitle; }

  public String getCatalogDescription() { return catalogDescription; }
  public void setCatalogDescription(String catalogDescription) { this.catalogDescription = catalogDescription; }

  public String getCatalogIdentifier() { return catalogIdentifier; }
  public void setCatalogIdentifier(String catalogIdentifier) { this.catalogIdentifier = catalogIdentifier; }

  public String getHomepage() { return homepage; }
  public void setHomepage(String homepage) { this.homepage = homepage; }

  public String getLanguage() { return language; }
  public void setLanguage(String language) { this.language = language; }

  public String getPublisherName() { return publisherName; }
  public void setPublisherName(String publisherName) { this.publisherName = publisherName; }

  public String getPublisherId() { return publisherId; }
  public void setPublisherId(String publisherId) { this.publisherId = publisherId; }

  public String getContactName() { return contactName; }
  public void setContactName(String contactName) { this.contactName = contactName; }

  public String getContactEmail() { return contactEmail; }
  public void setContactEmail(String contactEmail) { this.contactEmail = contactEmail; }

  public String getLicense() { return license; }
  public void setLicense(String license) { this.license = license; }

  public String getRights() { return rights; }
  public void setRights(String rights) { this.rights = rights; }

  public String getAccessLevel() { return accessLevel; }
  public void setAccessLevel(String accessLevel) { this.accessLevel = accessLevel; }

  public List<String> getBureauCode() { return bureauCode; }
  public void setBureauCode(List<String> bureauCode) { this.bureauCode = bureauCode; }

  public List<String> getProgramCode() { return programCode; }
  public void setProgramCode(List<String> programCode) { this.programCode = programCode; }

  public List<String> getDefaultKeywords() { return defaultKeywords; }
  public void setDefaultKeywords(List<String> defaultKeywords) { this.defaultKeywords = defaultKeywords; }

  public String getAccrualPeriodicity() { return accrualPeriodicity; }
  public void setAccrualPeriodicity(String accrualPeriodicity) { this.accrualPeriodicity = accrualPeriodicity; }

  public int getPageSize() { return pageSize; }
  public void setPageSize(int pageSize) { this.pageSize = pageSize > 0 ? pageSize : 100; }

  public boolean getIncludeDatasetSeries() { return includeDatasetSeries; }
  public void setIncludeDatasetSeries(boolean includeDatasetSeries) { this.includeDatasetSeries = includeDatasetSeries; }

  public boolean getIncludeDataServices() { return includeDataServices; }
  public void setIncludeDataServices(boolean includeDataServices) { this.includeDataServices = includeDataServices; }

  public boolean getPublicRecordsOnly() { return publicRecordsOnly; }
  public void setPublicRecordsOnly(boolean publicRecordsOnly) { this.publicRecordsOnly = publicRecordsOnly; }

  public boolean getPrettyPrint() { return prettyPrint; }
  public void setPrettyPrint(boolean prettyPrint) { this.prettyPrint = prettyPrint; }

  public String getMappingConfigPath() { return mappingConfigPath; }
  public void setMappingConfigPath(String mappingConfigPath) {
    this.mappingConfigPath = StringUtils.defaultIfBlank(mappingConfigPath, DEFAULT_MAPPING_CONFIG_PATH);
    loadMappingConfig();
  }

  public Map<String, String> getSourceFieldMappings() {
    return sourceFieldMappings;
  }

  public void setSourceFieldMappings(Map<String, String> sourceFieldMappings) {
    if (sourceFieldMappings == null || sourceFieldMappings.isEmpty()) return;
    this.sourceFieldMappings = new LinkedHashMap<>(sourceFieldMappings);
  }

  public String getSourceField(String key, String fallback) {
    String field = sourceFieldMappings != null ? sourceFieldMappings.get(key) : null;
    return StringUtils.defaultIfBlank(field, fallback);
  }

  public String getSourceField(String key, String fieldName, String fallback) {
    String field = sourceFieldMappings != null ? sourceFieldMappings.get(key) : null;
    if (StringUtils.isNotBlank(field)) return field;
    if (StringUtils.isNotBlank(fieldName)) return fieldName;
    return fallback;
  }

  public Map<String, List<String>> getClassProperty() {
    return classProperty;
  }

  public void setClassProperty(Map<String, List<String>> classProperty) {
    if (classProperty == null || classProperty.isEmpty()) return;
    LinkedHashMap<String, List<String>> copy = new LinkedHashMap<>();
    for (Map.Entry<String, List<String>> e : classProperty.entrySet()) {
      if (StringUtils.isBlank(e.getKey()) || e.getValue() == null) continue;
      copy.put(e.getKey(), new ArrayList<>(e.getValue()));
    }
    if (!copy.isEmpty()) {
      this.classProperty = copy;
    }
  }

  public List<String> getClassProperty(String type) {
    if (classProperty == null || StringUtils.isBlank(type)) return Collections.emptyList();
    List<String> order = classProperty.get(type);
    return order != null ? order : Collections.emptyList();
  }

  private void loadMappingConfig() {
    try (InputStream in = Thread.currentThread().getContextClassLoader().getResourceAsStream(mappingConfigPath)) {
      if (in == null) return;
      JsonNode root = Dcat3Helper.MAPPER.readTree(in);
      JsonNode mappings = root.path("sourceFieldMappings");
      if (mappings.isObject()) {
        LinkedHashMap<String, String> merged = new LinkedHashMap<>(this.sourceFieldMappings);
        mappings.fields().forEachRemaining(e -> {
          String k = StringUtils.trimToNull(e.getKey());
          String v = StringUtils.trimToNull(e.getValue().asText(null));
          if (k != null && v != null) merged.put(k, v);
        });
        this.sourceFieldMappings = merged;
      }

      JsonNode classPropertyNode = root.path("classProperty");
      if (classPropertyNode.isObject()) {
        LinkedHashMap<String, List<String>> merged = new LinkedHashMap<>(this.classProperty);
        classPropertyNode.fields().forEachRemaining(e -> {
          List<String> values = jsonList(e.getValue());
          if (!values.isEmpty()) merged.put(e.getKey(), values);
        });
        this.classProperty = merged;
      }
    } catch (Exception ex) {
      LOGGER.warn("DCAT3: unable to load mapping config from '{}'.", mappingConfigPath, ex);
    }
  }

  private static List<String> jsonList(JsonNode node) {
    List<String> values = new ArrayList<>();
    if (node == null || !node.isArray()) return values;
    for (JsonNode n : node) {
      String value = StringUtils.trimToNull(n.asText(null));
      if (value != null) values.add(value);
    }
    return values;
  }

  private static String removeTrailingSlash(String value) {
    if (value == null) return null;
    return value.endsWith("/") ? value.substring(0, value.length() - 1) : value;
  }
}
