define({
  "_widgetLabel": "Lista de capas",
  "titleBasemap": "Mapas base",
  "titleLayers": "Capas operacionales",
  "labelLayer": "Nombre de capa",
  "itemZoomTo": "Acercar a",
  "itemTransparency": "Transparencia",
  "itemTransparent": "Transparente",
  "itemOpaque": "Opaco",
  "itemMoveUp": "Mover hacia arriba",
  "itemMoveDown": "Mover hacia abajo",
  "itemDesc": "Descripción",
  "itemDownload": "Descargar",
  "itemToAttributeTable": "Ver en la tabla de atributos",
  "itemShowItemDetails": "Mostrar detalles del elemento",
  "empty": "vacío",
  "removePopup": "Deshabilitar elemento emergente",
  "enablePopup": "Habilitar elemento emergente",
  "turnAllLayersOff": "Desactivar todas las capas",
  "turnAllLayersOn": "Activar todas las capas",
  "expandAllLayers": "Expandir todas las capas",
  "collapseAlllayers": "Contraer todas las capas",
  "turnAllLabelsOff": "Desactivar todas las etiquetas",
  "turnAllLabelsOn": "Activar todas las etiquetas",
  "showLabels": "Mostrar etiquetas",
  "hideLables": "Ocultar etiquetas"
});