define({
  "instruction": "Pasirinkite ir sukonfigūruokite sluoksnius, kurie bus pirmiausiai pateikiami atributų lentelėje.",
  "label": "Sluoksnis",
  "show": "Rodyti",
  "actions": "Konfigūruoti sluoksnio laukus",
  "field": "Laukas",
  "alias": "Pseudonimas",
  "visible": "Matoma",
  "linkField": "Nuorodos laukas",
  "noLayers": "Elementų sluoksnių nėra",
  "back": "Atgal",
  "exportCSV": "Leisti eksportuoti į CSV",
  "expand": "Atverti valdiklį iš pradžių",
  "filterByExtent": "Įgalinti numatytąjį filtravimą pagal žemėlapio aprėptį",
  "restore": "Atkurti numatytąją reikšmę",
  "ok": "Gerai",
  "cancel": "Atšaukti",
  "includePoint": "Įtraukti taško koordinates į eksportuotą failą",
  "configureLayerFields": "Konfigūruoti laukus",
  "result": "Išsaugota sėkmingai",
  "warning": "Pirmiausia pasirinkite parinktį Rodyti.",
  "fieldCheckWarning": "Būtina pasirinkti bent vieną lauką.",
  "unsupportQueryWarning": "Kad būtų rodomas atributų lentelės valdiklyje šis sluoksnis turi palaikyti užklausas. Įsitikinkite, kad paslaugoje įjungta užklausų galimybė.",
  "unsupportQueryLayers": "Kad būtų rodomas atributų lentelės valdiklyje šis sluoksnis turi palaikyti užklausas. Įsitikinkite, kad paslaugoje įjungta užklausų galimybė.",
  "fieldName": "Pavadinimas",
  "fieldAlias": "Pseudonimas",
  "fieldVisibility": "Matomumas",
  "fieldActions": "Veiksmai",
  "showAttachments": "Rodyti priedus"
});