define({
  root: ({
    _widgetLabel: "Coordinate",
    hintMessage: "Click the map to get coordinates",
    defaultLabel: "Default",
    realtimeLabel: "Move mouse to get coordinates",
    computing: "Computing...",
    latitudeLabel: "Latitude",
    longitudeLabel: "Longitude",
    loading: "loading...",
    enableClick: "Click to enable clicking map to get coordinates",
    disableClick: "Click to disable clicking map to get coordinates",

    Default: "Default",
    Inches: "Inches",
    Foot: "Feet",
    Yards: "Yards",
    Miles: "Miles",
    Nautical_Miles: "Nautical miles",
    Millimeters: "Millimeters",
    Centimeters: "Centimeters",
    Meter: "Meters",
    Kilometers: "Kilometers",
    Decimeters: "Decimeters",
    Decimal_Degrees: "Degrees",
    Degree_Minutes_Seconds: "Degrees minutes seconds",
    MGRS: "MGRS",
    USNG: "USNG"
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
