define({
  "_widgetLabel": "Koordinata",
  "hintMessage": "Kliknite na mapu da biste dobili koordinate",
  "defaultLabel": "Podrazumevano",
  "realtimeLabel": "Pomerajte miša da biste dobili koordinate",
  "computing": "Računanje...",
  "latitudeLabel": "Geografska širina",
  "longitudeLabel": "Geografska dužina",
  "loading": "učitavanje...",
  "enableClick": "Kliknite da biste omogućili klik na mapu za dobijanje koordinata",
  "disableClick": "Kliknite da biste onemogućili klik na mapu za dobijanje koordinata",
  "Default": "Podrazumevano",
  "Inches": "Inči",
  "Foot": "Stope",
  "Yards": "Jardi",
  "Miles": "Milje",
  "Nautical_Miles": "Nautičke milje",
  "Millimeters": "Milimetri",
  "Centimeters": "Centimetri",
  "Meter": "Metri",
  "Kilometers": "Kilometri",
  "Decimeters": "Decimetri",
  "Decimal_Degrees": "Stepeni",
  "Degree_Minutes_Seconds": "Stepeni minuti sekunde",
  "MGRS": "Referentni sistem vojne pravougle koordinatne mreže (MGRS)",
  "USNG": "Nacionalna koordinatna mreža SAD (USNG)"
});