define({
  "common": {
    "apply": "Применить",
    "ok": "OK",
    "cancel": "Отмена",
    "yes": "Да",
    "no": "Нет",
    "next": "Далее",
    "previous": "Предыдущий",
    "back": "Назад",
    "selected": "выбрано",
    "name": "Имя",
    "usage": "Использование",
    "settings": "Настройки",
    "home": "На главную",
    "link": "Связь",
    "messages": "Сообщения",
    "outputs": "Выходные данные",
    "title": "Заголовок",
    "thumbnail": "Образец",
    "url": "URL-адрес",
    "actions": "Действия",
    "layer": "Слой",
    "action": "Действие",
    "input": "Входные данные",
    "output": "Выход",
    "type": "Тип",
    "required": "Необходимо",
    "options": "Опции",
    "label": "Надпись",
    "tooltip": "Подсказка инструмента",
    "visible": "Видимый",
    "symbol": "Символ",
    "popup": "Popup",
    "upload": "Загрузить",
    "execute": "Выполнить",
    "help": "Справка",
    "executing": "Запуск",
    "clear": "Очистить",
    "error": "Ошибка",
    "zoomTo": "Приблизить к",
    "attribute": "Атрибут",
    "exports": "Экспорт",
    "check": "Проверить",
    "save": "Сохранить",
    "close": "Закрыть",
    "deleteText": "Удалить",
    "map": "Карта",
    "scene": "Сцена",
    "reset": "Сбросить",
    "icon": "Значок",
    "folder": "Папка",
    "share": "Опубликовать",
    "view": "Просмотреть",
    "newText": "Новый",
    "edit": "Редактировать",
    "wkid": "WKID",
    "table": "Таблица",
    "zoomIn": "Увеличить",
    "zoomOut": "Уменьшить",
    "continue1": "Продолжить",
    "longitude": "Долгота",
    "latitude": "Широта",
    "custom": "Пользовательский",
    "image": "Изображение",
    "font": "Шрифт",
    "text": "Текст",
    "all": "все",
    "number": "Число",
    "percentage": "Процент",
    "unit": "Единица измерения",
    "thousand": "Тысяча",
    "billion": "Миллиард",
    "million": "Миллион",
    "none": "Нет",
    "field": "Поле",
    "operation": "Операция",
    "disableUpdateGeometry": "DisableUpdateGeometry",
    "preview": "Просмотр"
  },
  "errorCode": "Код",
  "errorMessage": "Сообщение",
  "errorDetail": "Подробности",
  "widgetPlaceholderTooltip": "Чтобы настроить его, перейдите в Виджеты и щелкните соответствующий ограничитель",
  "fieldStatistics": {
    "selectField": "Выбрать поле",
    "statistics": "Статистика",
    "field": "Поле",
    "count": "Число значений",
    "sum": "Сумма значений",
    "min": "Минимум",
    "max": "Максимум",
    "ave": "Среднее",
    "stddev": "Среднеквадратическое отклонение"
  },
  "symbolChooser": {
    "preview": "Предварительный просмотр",
    "basic": "Базовый",
    "arrows": "Стрелки",
    "business": "Бизнес",
    "cartographic": "Картография",
    "nationalParkService": "Служба национальных парков",
    "outdoorRecreation": "Отдых на природе",
    "peoplePlaces": "Общественные места",
    "safetyHealth": "Безопасность, здоровье",
    "shapes": "Формы",
    "transportation": "Транспорт",
    "symbolSize": "Размер символа",
    "color": "Цвет",
    "alpha": "Альфа",
    "outlineColor": "Цвет контура",
    "outlineWidth": "Ширина контура",
    "style": "Стиль",
    "width": "Ширина",
    "text": "Текст",
    "fontColor": "Цвет шрифта",
    "fontSize": "Размер шрифта",
    "transparency": "Прозрачность",
    "solid": "Заливка",
    "dash": "Тире",
    "dot": "Точка",
    "dashDot": "Штрих-пунктир",
    "dashDotDot": "Тире и две точки",
    "customImage": "Пользовательское изображение",
    "chooseFile": "Выберите файл",
    "noFileChoosen": "Файл не выбран."
  },
  "transparency": {
    "opaque": "Непрозрачный",
    "transparent": "Прозрачный"
  },
  "rendererChooser": {
    "domain": "Домен",
    "use": "Использовать",
    "singleSymbol": "Единый символ",
    "uniqueSymbol": "Уникальные символы",
    "color": "Цвет",
    "size": "Размер",
    "toShow": "Показать",
    "colors": "Цвета",
    "classes": "Классы",
    "symbolSize": "Размер символа",
    "addValue": "Добавить значение",
    "setDefaultSymbol": "Настроить символ по умолчанию",
    "defaultSymbol": "Символ по умолчанию",
    "selectedSymbol": "Выбранный символ",
    "value": "Значение",
    "label": "Надпись",
    "range": "Диапазон"
  },
  "drawBox": {
    "point": "Точка",
    "line": "Линия",
    "polyline": "Линия",
    "freehandPolyline": "Произвольная полилиния",
    "triangle": "Треугольник",
    "extent": "Экстент",
    "circle": "Круг",
    "ellipse": "Эллипс",
    "polygon": "Полигон",
    "freehandPolygon": "Произвольный полигон",
    "text": "Текст",
    "clear": "Сброс"
  },
  "popupConfig": {
    "title": "Заголовок",
    "add": "Добавить",
    "fields": "Поля",
    "noField": "Нет поля",
    "visibility": "Видимый",
    "name": "Имя",
    "alias": "Псевдоним",
    "actions": "Действия"
  },
  "includeButton": {
    "include": "Включить"
  },
  "loadingShelter": {
    "loading": "Загрузка"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Сервисы не найдены.",
    "unableConnectTo": "Не удается подключиться к",
    "invalidUrlTip": "Введенный URL-адрес недопустим или недоступен."
  },
  "serviceBrowser": {
    "noGpFound": "Сервисы геообработки не найдены.",
    "unableConnectTo": "Не удается подключиться к"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Картографические сервисы или сервисы пространственных объектов не найдены.",
    "unableConnectTo": "Не удается подключиться к"
  },
  "basicServiceChooser": {
    "validate": "Проверить",
    "example": "Пример",
    "set": "Задать"
  },
  "urlInput": {
    "invalidUrl": "Недопустимый URL-адрес."
  },
  "urlComboBox": {
    "invalidUrl": "Недопустимый URL-адрес."
  },
  "filterBuilder": {
    "addAnotherExpression": "Добавить выражение",
    "addSet": "Добавить набор",
    "matchMsg": "Получить объекты слоя, которые соответствуют ${any_or_all} из следующих выражений",
    "matchMsgSet": "${any_or_all} из следующих выражений в этом наборе равно true",
    "all": "Все",
    "any": "Любые",
    "value": "Значение",
    "field": "Поле",
    "unique": "Уникальное",
    "none": "Нет",
    "and": "и",
    "valueTooltip": "Введите значение",
    "fieldTooltip": "Выбрать из существующего поля",
    "uniqueValueTooltip": "Выбрать из уникальных значений в выбранном поле",
    "stringOperatorIs": "соответствует",
    "stringOperatorIsNot": "не соответствует",
    "stringOperatorStartsWith": "начинается с",
    "stringOperatorEndsWith": "заканчивается",
    "stringOperatorContains": "содержит",
    "stringOperatorDoesNotContain": "не содержит",
    "stringOperatorIsBlank": "является пустым",
    "stringOperatorIsNotBlank": "не является пустым",
    "dateOperatorIsOn": "соответствует",
    "dateOperatorIsNotOn": "не соответствует",
    "dateOperatorIsBefore": "перед",
    "dateOperatorIsAfter": "после",
    "dateOperatorIsOnOrBefore": "соответствует или до",
    "dateOperatorIsOnOrAfter": "соответствует или после",
    "dateOperatorMinutes": "минуты",
    "dateOperatorHours": "часы",
    "dateOperatorDays": "дней",
    "dateOperatorWeeks": "недель",
    "dateOperatorMonths": "месяцев",
    "dateOperatorYears": "года",
    "dateOperatorInTheLast": "в последние",
    "dateOperatorNotInTheLast": "не в последние",
    "dateOperatorIsBetween": "между",
    "dateOperatorIsNotBetween": "не между",
    "dateOperatorIsBlank": "является пустым",
    "dateOperatorIsNotBlank": "не является пустым",
    "numberOperatorIs": "соответствует",
    "numberOperatorIsNot": "не соответствует",
    "numberOperatorIsAtLeast": "больше или равно",
    "numberOperatorIsLessThan": "меньше чем",
    "numberOperatorIsAtMost": "меньше или равно",
    "numberOperatorIsGreaterThan": "больше чем",
    "numberOperatorIsBetween": "между",
    "numberOperatorIsNotBetween": "не между",
    "numberOperatorIsBlank": "является пустым",
    "numberOperatorIsNotBlank": "не является пустым",
    "string": "Строка",
    "number": "Число",
    "date": "Дата",
    "askForValues": "Запросить значения",
    "prompt": "Рекомендация",
    "hint": "Подсказка",
    "error": {
      "invalidParams": "Некорректные параметры.",
      "invalidUrl": "Недопустимый URL-адрес.",
      "noFilterFields": "Слой не имеет полей, которые могут использоваться для фильтрации.",
      "invalidSQL": "Некорректное sql выражение.",
      "cantParseSQL": "Не возможно разобрать sql выражение."
    },
    "caseSensitive": "Чувствительный к регистру",
    "notSupportCaseSensitiveTip": "Опубликованные сервисы не поддерживают запрос с чувствительностью к регистру.",
    "setFilterTip": "Настройте фильтры правильно.",
    "listValues": "Список значений",
    "cascadeFilterTip": "Показывать значения только для предыдущих выражений фильтра.",
    "noneCascadeFilterTip": "Все уникальные значения этого поля",
    "previousCascadeFilterTip": "Значения предыдущих выражений фильтра",
    "allCascadeFilterTip": "Значения всех остальных выражений фильтра"
  },
  "featureLayerSource": {
    "layer": "Слой",
    "browse": "Обзор",
    "selectFromMap": "Карты",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL Сервиса",
    "inputLayerUrl": "URL-адрес входного слоя",
    "selectLayer": "Выбрать слой объектов на текущей карте.",
    "chooseItem": "Выбрать элемент слоя объектов.",
    "setServiceUrl": "Введите URL сервиса объектов или картографического сервиса.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Выберите векторный слой."
  },
  "queryableLayerSource": {
    "layer": "Слой",
    "browse": "Обзор",
    "selectFromMap": "Карта",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL Сервиса",
    "inputLayerUrl": "URL-адрес входного слоя",
    "selectLayer": "Выбрать слой из текущей карты.",
    "chooseItem": "Выбрать элемент.",
    "setServiceUrl": "Ввести URL сервиса.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Выбор слоя."
  },
  "gpSource": {
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL Сервиса",
    "selectFromOnline": "ArcGIS Online",
    "setServiceUrl": "Введите URL-адрес сервиса геообработки.",
    "chooseItem": "Выберите элемент сервиса геообработки.",
    "chooseTask": "Выберите задачу геообработки."
  },
  "itemSelector": {
    "map": "Карта",
    "selectWebMap": "Выбор веб-карты",
    "addMapFromOnlineOrPortal": "Найти и добавить в приложение веб-карты из открытых ресурсов ArcGIS Online или собственных частных ресурсов ArcGIS Online или Portal.",
    "searchMapName": "Поиск по названию карты...",
    "searchNone": "Мы не смогли найти то, что вы искали. Пожалуйста, попробуйте снова.",
    "groups": "Группы",
    "noneGroups": "Нет групп",
    "signInTip": "Ваш сеанс работы под данной учетной записью истек, обновите свой браузер, чтобы войти в портал снова.",
    "signIn": "Войти",
    "publicMap": "Для всех",
    "myOrganization": "Моя организация",
    "myGroup": "Мои группы",
    "myContent": "Мои ресурсы",
    "count": "Количество",
    "fromPortal": "из Portal",
    "fromOnline": "из ArcGIS.com",
    "noneThumbnail": "Образец недоступен",
    "owner": "владелец",
    "signInTo": "Войти в",
    "lastModified": "Последние изменения",
    "moreDetails": "Подробнее",
    "mostRecent": "Самые свежие",
    "mostViewed": "Самые просматриваемые",
    "highestRated": "Самые рейтинговые",
    "viewItemDetails": "Просмотр информации об элементе"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Сервис не поддерживает запросы."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "На карте нет доступного подходящего слоя."
  },
  "layerInfosMenu": {
    "titleBasemap": "Базовые карты",
    "titleLayers": "Рабочие слои",
    "labelLayer": "Имя слоя",
    "itemZoomTo": "Приблизить к",
    "itemTransparency": "Прозрачность",
    "itemTransparent": "Прозрачный",
    "itemOpaque": "Непрозрачный",
    "itemMoveUp": "Выше",
    "itemMoveDown": "Ниже",
    "itemDesc": "Описание",
    "itemDownload": "Загрузить",
    "itemToAttributeTable": "Просмотреть в таблице атрибутов"
  },
  "imageChooser": {
    "unsupportReaderAPI": "Todo: Браузер не поддерживает API чтения файлов",
    "readError": "Не удалось считать файл.",
    "unknowError": "невозможно завершить операции",
    "invalidType": "Недопустимый тип файла.",
    "cropImage": "Обрезать изображение",
    "exceed": "Размер файла не может превышать 1024 КБ",
    "enableFlash": "Активируйте Adobe Flash до того, как начнете поиск изображения.",
    "cropWaining": "Выберите фото размером как минимум ${width} x ${height} пикселов.",
    "toolTip": "Для получения наилучших результатов, изображение должно быть ${width} пикселов шириной и ${height} пикселов высотой. Изображения других размеров будут настроены. Допустимые форматы изображений: PNG, GIF и JPEG."
  },
  "simpleTable": {
    "moveUp": "Выше",
    "moveDown": "Ниже",
    "deleteRow": "Удалить",
    "edit": "Изменить"
  },
  "urlParams": {
    "invalidToken": "Неверный токен",
    "validateTokenError": "Недопустимый токен или ошибка сети"
  },
  "exportTo": {
    "exportTo": "Экспорт",
    "toCSV": "Экспорт в файл CSV",
    "toFeatureCollection": "Экспорт в Коллекцию объектов",
    "toGeoJSON": "Экспорт в GeoJSON"
  },
  "appState": {
    "title": "Состояние приложения",
    "restoreMap": "Щелкните, чтобы сохранить заново экстент карты и видимость слоев в том виде, в котором вы их оставляете."
  },
  "featureActions": {
    "featureActions": "Действия с объектами",
    "ZoomTo": "Приблизить к",
    "PanTo": "Переместить к",
    "Flash": "Подсветить",
    "ShowPopup": "Показать всплывающее окно",
    "CreateLayer": "Создать слой",
    "ShowStatistics": "Статистика...",
    "ClearSelection": "Щелкните, чтобы очистить выборку слоя",
    "ExportToCSV": "Экспорт в файл CSV",
    "ShowSelectedFeature": "Показывать выбранные объекты",
    "ExportToFeatureCollection": "Экспорт в Коллекцию объектов",
    "ExportToGeoJSON": "Экспорт в GeoJSON",
    "EditAttributes": "Редактирование атрибутов",
    "AddMarker": "Добавить маркер",
    "RemoveMarker": "Удалить маркер",
    "SaveToMyContent": "Сохранить в Моих ресурсах"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Связанный слой",
    "selectedFeatures": "Использовать выбранные объекты",
    "drawShapesTip": "Нарисуйте рамки, чтобы выбрать объекты",
    "pleaseDrawShapesTip": "Нарисуйте рамки, чтобы выбрать объекты",
    "allFeaturesTip": "Все объекты слоя",
    "selectFeaturesOrDrawShapesTip": "Используйте выбранные объекты этого слоя или обведите рамки на карте, чтобы уменьшить число объектов."
  },
  "searchDistance": {
    "applySearchDistance": "Применить расстояние поиска",
    "applySearchDistanceToFeatures": "Применить расстояние поиска к выбранным объектам"
  },
  "units": {
    "miles": "Мили",
    "milesAbbr": "мили",
    "kilometers": "Километры",
    "kilometersAbbr": "км",
    "feet": "Футы",
    "feetAbbr": "футы",
    "meters": "Метры",
    "metersAbbr": "м",
    "yards": "Ярды",
    "yardsAbbr": "ярды",
    "acres": "Акры",
    "acresAbbr": "акров",
    "nauticalMiles": "Морские мили",
    "nauticalMilesAbbr": "мор.миль",
    "uSSurveyFeet": "Геодезические футы США",
    "uSSurveyFeetAbbr": "ftUS",
    "decimalDegree": "Десятичные градусы",
    "decimalDegreeAbbr": "дг",
    "degreeMinuteSeconds": "Градусы минуты секунды",
    "degreeMinuteSecondsAbbr": "г-м-с",
    "squareMiles": "Квадратные мили",
    "squareMilesAbbr": "кв. мили",
    "squareKilometer": "Квадратные километры",
    "squareKilometerAbbr": "кв. км",
    "squareFeet": "Квадратные футы",
    "squareFeetAbbr": "кв.фт",
    "squareMeters": "Квадратные метры",
    "squareMetersAbbr": "кв.м",
    "squareYards": "Квадратные ярды",
    "squareYardsAbbr": "кв.ярд",
    "squareUSSurveyFeet": "Квадратные геодезические футы США",
    "squareUSSurveyFeetAbbr": "sq ftUS"
  },
  "featureSetChooser": {
    "select": "Выбрать",
    "dragBox": "Передвинуть",
    "dragMouse": "Перетащите курсор мыши",
    "selectByRectangle": "Выбрать прямоугольником",
    "selectFeaturesTip": "Выбрать объекты с помощью прямоугольной рамки",
    "newSelectionTip": "Создать новую выборку",
    "addSelectionTip": "Добавить к выборке",
    "removeSelectionTip": "Удалить из выборки",
    "selectFromCurrentSelectionTip": "Выбрать из текущей выборки",
    "unselectAllSelectionTip": "Снять выделение со всех выбранных в данный момент объектов",
    "selectByPolygon": "Выбрать полигоном",
    "selectByCircle": "Выбрать окружностью",
    "selectByLine": "Выбрать линией",
    "chooseSelectingTools": "Выбрать инструменты выборки",
    "darw": "Нарисовать",
    "drawShap": "Нарисовать форму"
  },
  "widgetManager": {
    "createWidgetError": "Ошибка создания виджета",
    "createWidgetSettingPageError": "Ошибка создания страницы настроек виджета",
    "loadWidgetResourceError": "Ошибка загрузки ресурсов виджета"
  },
  "shareOptions": {
    "shareMap": "Выберите, кто может просматривать это приложение",
    "shareMapTips": "В настоящее время приложение используется совместно с этими людьми",
    "everyone": "Все",
    "theseGroups": "Эти группы"
  },
  "shareLink": {
    "email": "email",
    "shareEmail": "Email",
    "facebook": "facebook",
    "shareFacebook": "Facebook",
    "twitter": "twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "Встроить это приложение в веб-сайт",
    "shareEmailSubject": "Публикация веб-приложения:",
    "shareEmailTxt1": "Доступное для вас веб-приложение, опубликованное с помощью Web AppBuilder for ArcGIS.",
    "shareEmailTxt2": "Вы можете создать и опубликовать собственное веб-приложение с помощью Web AppBuilder for ArcGIS.",
    "shareEmailTxt3": "Посетите http://www.esri.com/software/web-appbuilder, чтобы получить дополнительные сведения.",
    "smallSize": "Малая",
    "mediumSize": "Средняя",
    "largeSize": "Большая",
    "customSize": "Пользовательская",
    "embed": "Встроить это приложение в веб-сайт",
    "more": "Опции встраивания",
    "changeShareSettings": "Изменить настройки публикации",
    "shareLinkText": "Опубликовать ссылку на это приложение",
    "linkOptions": "Опции связывания",
    "linkOptionsUrlParameters": "Выберите параметры URL, включенные в ссылку",
    "currentMapExtent": "Текущий экстент карты",
    "chooseCenterWithLevel": "Щелкните карту, чтобы задать ее центр с уровнем масштабирования",
    "chooseCenterWithScale": "Щелкните карту, чтобы задать ее центр с масштабом карты",
    "findLocation": "Найдите местоположение или объект и приблизьтесь к нему",
    "findLocation_inputPlaceholder": "Ваше местоположение или объект",
    "queryFeature": "Выполните запрос к объекту и приблизьтесь к нему",
    "addMarker": "Добавить маркер на карту",
    "addMarker_titlePlaceholder": "Заголовок всплывающего окна маркера",
    "addMarker_symbolURL": "URL-адрес символа маркера",
    "addMarker_label": "Надпись маркера",
    "popupTitle": "Заголовок всплывающего окна",
    "zoomLevel": "Уровень масштабирования",
    "overwirteMobileLayout": "Не использовать размер экрана мобильной компоновки по умолчанию",
    "language": "Задать язык интерфейса приложения",
    "auth": "Автоматически проверять подлинность пользователя",
    "linkPreview": "Просмотр ссылки",
    "useShortenLink": "Короткая ссылка",
    "shareMapUrlExtent": "Опубликовать текущий экстент карты",
    "shareToWebTips": "Это приложение не доступно для всех. Пользователи могут не увидеть его."
  },
  "webSceneLoader": {
    "webglSupportTip": "3D веб-приложения не поддерживаются в вашем браузере."
  },
  "map": {
    "basemapNotAvailable": "Базовая карта не доступна.",
    "displayDefaultBasemap": "Вместо нее отображается базовая карта, используемая по умолчанию.",
    "layerLoadedError": "Слой ${layers} не может быть добавлен к карте."
  },
  "popup": {
    "relatedTables": "Связанные таблицы:",
    "relatedRecords": "Связанные записи:",
    "noRelatedRecotds": "Связанных записей не найдено.",
    "chooseFieldTip": "Выбрать атрибут для отображения списка",
    "saveAsPopupTitle": "Так же, как в заголовке всплывающего окна"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "Слишком много объектов в вашей выборке. Для отображения всех данных на карте может потребоваться значительное время.",
    "askForContinue": "Хотите продолжить?"
  },
  "colorPalette": {
    "transparent": "Прозрачный",
    "custom": "Пользовательский"
  },
  "temperature": {
    "celsius": "По Цельсию",
    "fahrenheit": "По Фаренгейту"
  },
  "report": {
    "printButtonLabel": "Печать",
    "reportDimensionsMsg": "Этот отчет предназначен для печати на бумаге формата ${paperSize}",
    "unableToPrintMapMsg": "Во время печати карты произошла ошибка.",
    "notesHint": "Введите комментарий здесь",
    "landscape": "Альбомная",
    "portrait": "Книжная",
    "mapOnly": "MAP_ONLY",
    "a0": "A0",
    "a1": "A1",
    "a2": "A2",
    "a3": "A3",
    "a4": "A4",
    "a5": "A5",
    "letterANSIA": "Letter ANSI A",
    "tabloidANSIB": "Tabloid ANSI B",
    "letter": "Letter",
    "legal": "Правовая информация",
    "tabloid": "Tabloid",
    "ansi_a": "ANSI A",
    "ansi_b": "ANSI B",
    "ansi_c": "ANSI C",
    "ansi_d": "ANSI D",
    "ansi_e": "ANSI E"
  },
  "snapshot": {
    "snapshot_complete": "Снимок успешно создан.",
    "snapshot_failed": "Не удалось создать снимок.",
    "snapshot_append": "Снимок",
    "utc": "UTC"
  },
  "statisticsChart": {
    "enlarge": "Увеличить",
    "setting": "Установки",
    "count": "Количество",
    "horizontalAxis": "Горизонтальная ось",
    "verticalAxis": "Вертикальная ось",
    "dataLabels": "Надписи данных",
    "color": "Цвет"
  },
  "frameworkDatasource": {
    "setDataSource": "Задать источник данных",
    "customDataSource": "Внешний источник данных",
    "selectCustomDataTip": "Выберите источник данных из этого приложения.",
    "widgetOutputs": "Выходные данные виджета",
    "noExtraDsAvailable": "Нет дополнительных источников данных.",
    "addExtraDsTip": "Перейдите на вкладку конструктора Атрибуты и щелкните Дополнительный источник данных, чтобы добавить данные.",
    "widgetOutpusListTip": "Выходные данные виджета (при наличии) также перечислены здесь."
  },
  "gridLayout": {
    "addWidgetTip": "Добавьте виджет из вкладки Виджеты",
    "modifyLayout": "Изменить компоновку",
    "dragToAdd": "Потяните, чтобы добавить",
    "mapArea": "ОБЛАСТЬ КАРТЫ"
  },
  "noEditPrivileges": "У вашей учетной записи нет прав на создание или изменение данных.",
  "invalidConfiguration": "Виджет не настроен, или на карте больше нет слоёв из конфигурации. Откройте приложение в режиме конструктора и настройте виджет."
});