define({
  "id": "ID",
  "state": "Prema zadanim postavkama, koordinate će se prikazati u trenutačnom koordinatnom sustavu karte. Za dobivanje koordinata u drugim koordinatnim sustavima trebate ih dodati i odrediti odgovarajuće transformacije.",
  "outputUnit": "Izlazna jedinica",
  "wkid": "Izlazni WKID",
  "label": "Naziv izlaznog koordinatnog sustava",
  "transformationWkid": "WKID transformacije",
  "transformationLabel": "Oznaka transformacije",
  "transformForward": "Transformacija prema naprijed",
  "actions": "Radnje",
  "warning": "Unesite važeći WKID prostorne reference!",
  "tfWarning": "Unesite važeći WKID datuma transformacije!",
  "spinnerLabel": "Zaokruži koordinate na: ",
  "decimalPlace": "decimalna mjesta",
  "separator": "Prikaži razdjelnik tisućica",
  "getVersionError": "Nije moguće dobiti verziju Geometrijske usluge",
  "add": "Dodaj izlazni koordinatni sustav",
  "edit": "Uredi koordinatni sustav",
  "output": "Izlazni koordinatni sustav",
  "cName": "Naziv koordinatnog sustava",
  "units": "Jedinice prikaza: ",
  "datum": "Geodetska transformacija datuma",
  "tName": "Naziv transformacije",
  "tWKIDPlaceHolder": "WKID transformacije",
  "forward": "Upotrijebite transformaciju prema naprijed",
  "ok": "U redu",
  "cancel": "Odustani",
  "olderVersion": "Geometrijska usluga ne podržava izvođenje transformacije",
  "REPEATING_ERROR": " Koordinatni sustav postoji na izlaznom popisu.",
  "Default": "Zadano",
  "Inches": "Inči",
  "Foot": "Stope",
  "Yards": "Jardi",
  "Miles": "Milje",
  "Nautical_Miles": "Nautičke milje",
  "Millimeters": "Millimetri",
  "Centimeters": "Centimetri",
  "Meter": "Metri",
  "Kilometers": "Kilometri",
  "Decimeters": "Decimetri",
  "Decimal_Degrees": "Decimalni stupnjevi",
  "Degrees_Decimal_Minutes": "Stupnjevi decimale minute",
  "Degree_Minutes_Seconds": "Stupnjevi minute sekunde",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Redoslijed prikaza koordinata:",
  "lonLatTips": "Geografska dužina / geografska širina (X, Y)",
  "latLonTips": "Geografska širina / geografska dužina (Y, X)"
});