define({
  "instruction": "หน้าจอจะปรากฏขึ้นก่อนที่เข้าถึงโปรแกรมประยุกต์",
  "defaultContent": "เพิ่มข้อความ, ลิงค์, และกราฟฟิคเล็กๆ ที่นี่",
  "requireConfirm": "ต้องการการยืนยันเพื่อดำเนินการต่อ",
  "noRequireConfirm": "ไม่จำเป็นต้องยืนยันที่จะดำเนินการ",
  "optionText": "การตั้งค่าสำหรับผู้ใช้งานในการปิดการแสดงผลสกรีนบนแอพพลิเคชั่นเริ่มต้น",
  "confirmLabel": "ข้อความยืนยัน: ",
  "confirmLabelColor": "ยืนยันสีของตัวอักษร",
  "defaultConfirmText": "ฉันยอมรับในข้อตกลงและข้อกำหนดต่างๆ ด้านบน",
  "confirmOption": "แสดง Splash screen ทุกครั้งที่เปิดแอพพลิเคชัน",
  "backgroundColor": "สีพื้นหลัง",
  "content": "เนื้อหา",
  "contentDescription": "กำหนดเนื้อหาที่แสดงบนหน้าจอ",
  "appearance": "รูปลักษณ์",
  "appearanceDescription": "ตั้งลักษณะของหน้าจอในขณะเริ่ม",
  "size": "ขนาด",
  "width": "ความกว้าง",
  "height": "ความสูง",
  "custom": "แก้ไขเอง",
  "background": "พื้นหลัง",
  "colorFill": "เติมสี",
  "imageFill": "เติมภาพ",
  "chooseFile": "เลือกไฟล์",
  "noFileChosen": "ไม่มีไฟล์ที่ถูกเลือก",
  "transparency": "โปร่งแสง",
  "sizeFill": "กรอก",
  "sizeFit": "พอดี",
  "sizeStretch": "ยืดเพื่อเติม",
  "sizeCenter": "ศูนย์กลาง",
  "sizeTile": "ข้อมูล tile",
  "buttonColor": "สีของปุ่ม",
  "buttonText": "ตัวอักษรของปุ่ม",
  "buttonTextColor": "ตัวอักษร",
  "contentAlign": "การจัดตำแหน่งเนื้อหา",
  "alignTop": "บน",
  "alignMiddle": "กลาง",
  "maskColor": "สีของหน้ากาก",
  "options": "ตัวเลือก",
  "optionsDescription": "ตั้งค่าการทำงานของหน้าจอในขณะเริ่ม"
});