define({
  "_widgetLabel": "รายการชั้นข้อมูล",
  "titleBasemap": "แผนที่ฐาน",
  "titleLayers": "ชั้นข้อมูลแสดงผล",
  "labelLayer": "ชื่อชั้นข้อมูล",
  "itemZoomTo": "ขยายไปยัง",
  "itemTransparency": "โปร่งแสง",
  "itemTransparent": "โปร่งแสง",
  "itemOpaque": "ทึบแสง",
  "itemMoveUp": "เลื่อนขึ้น",
  "itemMoveDown": "เลื่อนลง",
  "itemDesc": "คำอธิบาย",
  "itemDownload": "ดาวน์โหลด",
  "itemToAttributeTable": "ดูในตารางแอตทริบิวต์",
  "itemShowItemDetails": "แสดงรายละเอียดของรายการ",
  "empty": "ว่าง",
  "removePopup": "ปิดการใช้งานป๊อปอัพ",
  "enablePopup": "ป๊อปอัพสามารถใช้งานได้",
  "turnAllLayersOff": "ปิดชั้นข้อมูลทั้งหมด",
  "turnAllLayersOn": "เปิดชั้นข้อมูลทั้งหมด",
  "expandAllLayers": "ขยายชั้นข้อมูลทั้งหมด",
  "collapseAlllayers": "ยุบชั้นข้อมูลทั้งหมด",
  "turnAllLabelsOff": "ปิดป้ายกำกับทั้งหมด",
  "turnAllLabelsOn": "เปิดป้ายกำกับทั้งหมด",
  "showLabels": "แสดงตัวหนังสือ",
  "hideLables": "ซ่อนป้ายกำกับ"
});