define({
  "_widgetLabel": "Danh sách Lớp",
  "titleBasemap": "Bản đồ nền",
  "titleLayers": "Các lớp hoạt động",
  "labelLayer": "Tên lớp",
  "itemZoomTo": "Phóng tới",
  "itemTransparency": "Độ trong suốt",
  "itemTransparent": "Độ trong suốt",
  "itemOpaque": "Độ mờ",
  "itemMoveUp": "Di chuyển lên trên",
  "itemMoveDown": "Di chuyển xuống dưới",
  "itemDesc": "Mô tả",
  "itemDownload": "Tải xuống",
  "itemToAttributeTable": "Xem trong Bảng Thuộc tính",
  "itemShowItemDetails": "Hiển thị chi tiết của mục",
  "empty": "trống",
  "removePopup": "Tắt cửa sổ pop-up",
  "enablePopup": "Bật cửa sổ pop-up",
  "turnAllLayersOff": "Tắt tất cả lớp",
  "turnAllLayersOn": "Bật tất cả lớp",
  "expandAllLayers": "Mở rộng tất cả lớp",
  "collapseAlllayers": "Thu gọn tất cả lớp",
  "turnAllLabelsOff": "Tắt tất cả nhãn",
  "turnAllLabelsOn": "Bật tất cả nhãn",
  "showLabels": "Hiển thị nhãn",
  "hideLables": "Ẩn nhãn"
});