define({
  "_widgetLabel": "Daftar Layer",
  "titleBasemap": "Peta Dasar",
  "titleLayers": "Layer operasional",
  "labelLayer": "Nama layer",
  "itemZoomTo": "Perbesar hingga",
  "itemTransparency": "Transparansi",
  "itemTransparent": "Transparan",
  "itemOpaque": "Buram",
  "itemMoveUp": "Pindahkan ke atas",
  "itemMoveDown": "Pindahkan ke bawah",
  "itemDesc": "Deskripsi",
  "itemDownload": "Unduhan",
  "itemToAttributeTable": "Tampilkan dalam Tabel Atribut",
  "itemShowItemDetails": "Tampilkan detail item",
  "empty": "kosong",
  "removePopup": "Nonaktifkan pop-up",
  "enablePopup": "Aktifkan pop-up",
  "turnAllLayersOff": "Matikan semua layer",
  "turnAllLayersOn": "Hidupkan semua layer",
  "expandAllLayers": "Perluas semua layer",
  "collapseAlllayers": "Ciutkan semua layer",
  "turnAllLabelsOff": "Matikan semua label",
  "turnAllLabelsOn": "Hidupkan semua label",
  "showLabels": "Tampilkan label",
  "hideLables": "Sembunyikan label"
});