define({
  "_widgetLabel": "Coordonnées",
  "hintMessage": "Cliquez sur la carte pour obtenir les coordonnées",
  "defaultLabel": "Par défaut",
  "realtimeLabel": "Déplacez la souris pour obtenir les coordonnées",
  "computing": "Calcul...",
  "latitudeLabel": "Latitude",
  "longitudeLabel": "Longitude",
  "loading": "chargement...",
  "enableClick": "Cliquez pour activer l’obtention des coordonnées à l’aide d’un clic sur la carte",
  "disableClick": "Cliquez pour désactiver l’obtention des coordonnées à l’aide d’un clic sur la carte",
  "Default": "Par défaut",
  "Inches": "Pouces",
  "Foot": "Pieds",
  "Yards": "Yards",
  "Miles": "Miles",
  "Nautical_Miles": "Milles marins",
  "Millimeters": "Millimètres",
  "Centimeters": "Centimètres",
  "Meter": "Mètres",
  "Kilometers": "Kilomètres",
  "Decimeters": "Décimètres",
  "Decimal_Degrees": "Degrés",
  "Degree_Minutes_Seconds": "Degrés minutes secondes",
  "MGRS": "MGRS",
  "USNG": "USNG"
});