define({
  "sourceSetting": "Cerca impostazioni origine",
  "instruction": "Aggiungere e configurare servizi di geocodifica o feature layer come fonti di ricerca. Queste fonti specificate determinano ciò che è possibile cercare nella casella di ricerca.",
  "add": "Aggiungi origine di ricerca",
  "addGeocoder": "Aggiungi geocodificatore",
  "geocoder": "Geocodificatore",
  "setLayerSource": "Imposta layer di origine",
  "setGeocoderURL": "Imposta URL geocodificatore",
  "searchableLayer": "Feature layer",
  "name": "Nome",
  "countryCode": "Codici paesi o regioni",
  "countryCodeEg": "es. ",
  "countryCodeHint": "Se si lascia vuoto questo campo, la ricerca verrà effettuata in tutti i paesi e le regioni",
  "generalSetting": "Impostazioni generali",
  "allPlaceholder": "Testo segnaposto per la ricerca in tutti: ",
  "showInfoWindowOnSelect": "Mostra popup per la feature o la posizione trovata",
  "searchInCurrentMapExtent": "Esegui la ricerca nell'estensione mappa corrente",
  "zoomScale": "Scala zoom",
  "locatorUrl": "URL geocodificatore",
  "locatorName": "Nome geocodificatore",
  "locatorExample": "Esempio",
  "locatorWarning": "Questa versione del servizio di geocodifica non è supportata. Il widget supporta il servizio di geocodifica 10.1 e versioni successive.",
  "locatorTips": "I suggerimenti non sono disponibili perché il servizio di geocodifica non supporta tale funzionalità.",
  "layerSource": "Origine del layer",
  "searchLayerTips": "I suggerimenti non sono disponibili perché il feature service non supporta la funzionalità di paginazione.",
  "placeholder": "Testo segnaposto",
  "searchFields": "Campi di ricerca",
  "displayField": "Campo di visualizzazione",
  "exactMatch": "Corrispondenza esatta",
  "maxSuggestions": "Suggerimenti massimi",
  "maxResults": "Risultati massimi",
  "enableLocalSearch": "Abilita ricerca locale",
  "minScale": "Scala minima",
  "minScaleHint": "Quando la scala della mappa è più grande di questa scala, verrà applicata la ricerca locale",
  "radius": "Raggio",
  "radiusHint": "Specifica il raggio di un'area intorno al centro della mappa corrente che viene utilizzato per assegnare la priorità alla classificazione dei candidati di geocodifica in modo che i canditati più vicini alla posizione vengano restituiti per primi",
  "meters": "Metri",
  "setSearchFields": "Imposta campi di ricerca",
  "set": "Imposta",
  "fieldSearchable": "incluso nella ricerca",
  "fieldName": "Nome",
  "fieldAlias": "Alias",
  "ok": "OK",
  "cancel": "Annulla",
  "invalidUrlTip": "URL ${URL} non valido o non accessibile."
});