define(
   ({
    "sourceSetting": "Cerca impostazioni origine",
    "instruction": "Aggiungere e configurare servizi di geocodifica o feature layer come fonti di ricerca. Queste fonti specificate determinano ciò che è possibile cercare nella casella di ricerca.",
    "add": "Aggiungi fonte di ricerca",
    "addGeocoder": "Aggiungi geocodificatore",
    "geocoder": "Geocodificatore",
    "setLayerSource": "Imposta layer di origine",
    "setGeocoderURL": "Imposta URL geocodificatore",
    "searchableLayer": "Feature layer",
    "name": "Nome",
    "countryCode": "Codici paesi o regioni",
    "countryCodeEg": "es. ",
    "countryCodeHint": "Se si lascia vuoto questo campo, la ricerca verrà effettuata in tutti i paesi e le regioni",
    "generalSetting": "Impostazioni generali",
    "allPlaceholder": "Testo segnaposto per la ricerca in tutti: ",
    "showInfoWindowOnSelect": "Mostra popup per la feature o la posizione trovata",
    "searchInCurrentMapExtent": "Esegui la ricerca nell\'estensione mappa corrente",
    "locatorUrl": "URL geocodificatore",
    "locatorName": "Nome geocodificatore",
    "locatorExample": "Esempio",
    "locatorWarning": "Questa versione del servizio di geocodifica non è supportata. Il widget supporta il servizio di geocodifica versione 00.0 e successiva.",
    "locatorTips": "I suggerimenti non sono disponibili perché il servizio di geocodifica non supporta tale funzionalità.",
    "layerSource": "Origine del layer",
    "searchLayerTips": "I suggerimenti non sono disponibili perché il feature service non supporta la funzionalità di paginazione.",
    "placeholder": "Testo segnaposto",
    "searchFields": "Campi di ricerca",
    "displayField": "Campo visualizzazione",
    "exactMatch": "Corrispondenza esatta",
    "maxResults": "Risultati massimi",
    "setSearchFields": "Imposta campi di ricerca",
    "set": "Imposta",
    "fieldSearchable": "incluso nella ricerca",
    "fieldName": "Nome",
    "fieldAlias": "Alias",
    "ok": "OK",
    "cancel": "Annulla",
    "invalidUrlTip": "L\'URL immesso non è valido o non è accessibile."
  })
);