define({
  "_widgetLabel": "Popis slojeva",
  "titleBasemap": "Kartografske podloge",
  "titleLayers": "Operativni slojevi",
  "labelLayer": "Naziv sloja",
  "itemZoomTo": "Povećaj na",
  "itemTransparency": "Prozirnost",
  "itemTransparent": "Transparentno",
  "itemOpaque": "Neprozirno",
  "itemMoveUp": "Premjesti gore",
  "itemMoveDown": "Premjesti dolje",
  "itemDesc": "Opis",
  "itemDownload": "Preuzmi",
  "itemToAttributeTable": "Prikaži u atributnoj tablici",
  "itemShowItemDetails": "Prikaži pojedinosti stavke",
  "empty": "prazno",
  "removePopup": "Onemogući skočni prozor",
  "enablePopup": "Omogući skočni prozor",
  "turnAllLayersOff": "Isključi sve slojeve",
  "turnAllLayersOn": "Uključi sve slojeve",
  "expandAllLayers": "Proširi sve slojeve",
  "collapseAlllayers": "Sažmi sve slojeve",
  "turnAllLabelsOff": "Isključi sve oznake",
  "turnAllLabelsOn": "Uključi sve oznake",
  "showLabels": "Prikaži oznake",
  "hideLables": "Sakrij oznake"
});