define({
  "instruction": "Pozdravni zaslon se pojavi, preden je mogoče dostopati do aplikacije.",
  "defaultContent": "Tukaj dodajte besedilo, povezave in majhne grafike.",
  "requireConfirm": "Za nadaljevanje je potrebna potrditev.",
  "noRequireConfirm": "Za nadaljevanje ni potrebna potrditev.",
  "optionText": "Možnost, da uporabnik onemogoči pozdravni zaslov pri zagonu aplikacije",
  "confirmLabel": "Potrditvena besedila: ",
  "confirmLabelColor": "Barva potrditvenih besedil",
  "defaultConfirmText": "Soglašam z zgornjimi določili in pogoji",
  "confirmOption": "Pozdravni zaslon pokaži ob zagonu aplikacije",
  "backgroundColor": "Barva ozadja",
  "content": "Vsebina",
  "contentDescription": "Določi vsebino pozdravnega zaslona",
  "appearance": "Videz",
  "appearanceDescription": "Nastavite videz pozdravnega zaslona.",
  "size": "Velikost",
  "width": "Širina",
  "height": "Višina",
  "custom": "Po meri",
  "background": "Ozadje",
  "colorFill": "Barvno polnilo",
  "imageFill": "Polnilo slike",
  "chooseFile": "Izberite datoteko",
  "noFileChosen": "Datoteka ni izbrana",
  "transparency": "Prosojnost",
  "sizeFill": "Polnilo",
  "sizeFit": "Prilagodi",
  "sizeStretch": "Raztegni do polnitve",
  "sizeCenter": "Na sredino",
  "sizeTile": "Ploščica",
  "buttonColor": "Barva gumba",
  "buttonText": "Besedilo gumba",
  "buttonTextColor": "Barva besedila gumba",
  "contentAlign": "Poravnava vsebine",
  "alignTop": "Zgoraj",
  "alignMiddle": "Na sredino",
  "maskColor": "Barva maske",
  "options": "Možnosti",
  "optionsDescription": "Nastavite vedenje pozdravnega zaslona."
});