define({
  "sourceSetting": "Postavke izvora pretraživanja",
  "instruction": "Dodajte i konfigurirajte usluge geokodiranja ili slojeve geoobjekata kao izvore pretraživanja. Ti zadani izvori određuju što se može pretraživati u okviru za pretraživanje.",
  "add": "Dodaj izvor pretraživanja",
  "addGeocoder": "Dodaj geokoder",
  "geocoder": "geokoder",
  "setLayerSource": "Postavi izvor sloja",
  "setGeocoderURL": "Postavi URL geokodera",
  "searchableLayer": "Slojevi geoobjekta",
  "name": "Naziv",
  "countryCode": "Pozivni broj za državu ili regiju",
  "countryCodeEg": "npr. ",
  "countryCodeHint": "Ako ostavite ovu vrijednost praznom, pretražit će se sve države i regije",
  "generalSetting": "Opće postavke",
  "allPlaceholder": "Mjesto za unos teksta za pretraživanje svega: ",
  "showInfoWindowOnSelect": "Prikaži skočni prozor za pronađeni geoobjekt ili lokaciju",
  "searchInCurrentMapExtent": "Pretraži samo trenutačni obuhvat karte",
  "zoomScale": "Mjerilo uvećanja",
  "locatorUrl": "URL geokodera",
  "locatorName": "Naziv geokodera",
  "locatorExample": "Primjer",
  "locatorWarning": "Ova verzija usluge geokodiranja nije podržana. Widget podržava verziju usluge geokodiranja 10.1 i novije verzije.",
  "locatorTips": "Prijedlozi nisu dostupni jer usluga geokodiranja ne podržava mogućnost predlaganja.",
  "layerSource": "Izvor sloja",
  "searchLayerTips": "Prijedlozi nisu dostupni jer usluga geoobjekata ne podržava mogućnost numeriranja stranica.",
  "placeholder": "Mjesto za unos teksta",
  "searchFields": "Polja za pretraživanje",
  "displayField": "Polja za prikaz",
  "exactMatch": "Točno podudaranje",
  "maxSuggestions": "Maksimalni broj prijedloga",
  "maxResults": "Maksimalni rezultati",
  "enableLocalSearch": "Omogući lokalno pretraživanje",
  "minScale": "Min. mjerilo",
  "minScaleHint": "Kad je mjerilo karte veće od ovog mjerila, primijenit će se lokalno pretraživanje",
  "radius": "Polumjer",
  "radiusHint": "Određuje polumjer područja oko trenutačnog središta karte koje se upotrebljava za povećanje broja kandidata za geokodiranje kako bi se prvi prikazali kandidati koji su najbliži lokaciji",
  "meters": "Metri",
  "setSearchFields": "Postavi polja za pretraživanje",
  "set": "Postavi",
  "fieldSearchable": "pretraživo",
  "fieldName": "Naziv",
  "fieldAlias": "Alias",
  "ok": "U redu",
  "cancel": "Odustani",
  "invalidUrlTip": "URL ${URL} nije valjan ili dostupan."
});