define({
  "instruction": "Startskärmen visas innan applikationen kan börja användas.",
  "defaultContent": "Lägg till texter, länkar och små bilder här.",
  "requireConfirm": "Kräv bekräftelse för att fortsätta",
  "noRequireConfirm": "Kräv inte bekräftelse för att fortsätta",
  "optionText": "Alternativ för att användaren ska kunna inaktivera välkomstskärmen när programmet startas.",
  "confirmLabel": "Bekräftelsetext: ",
  "confirmLabelColor": "Textfärg för bekräftelse",
  "defaultConfirmText": "Jag godkänner villkoren ovan",
  "confirmOption": "Visa alltid denna startskärm när som appen startas",
  "backgroundColor": "Bakgrundsfärg",
  "content": "Innehåll",
  "contentDescription": "Ange vilket innehåll som ska visas på startskärmen.",
  "appearance": "Utseende",
  "appearanceDescription": "Ange visningsinställningar för startskärmen.",
  "size": "Storlek",
  "width": "Bredd",
  "height": "Höjd",
  "custom": "Anpassat",
  "background": "Bakgrund",
  "colorFill": "Fyllningsfärg",
  "imageFill": "Bildfyllning",
  "chooseFile": "Välj fil",
  "noFileChosen": "Ingen fil har valts",
  "transparency": "Transparens",
  "sizeFill": "Fyllning",
  "sizeFit": "Anpassa",
  "sizeStretch": "Sträck ut för utfyllning",
  "sizeCenter": "Centrera",
  "sizeTile": "Tile",
  "buttonColor": "Knappfärg",
  "buttonText": "Knapptext",
  "buttonTextColor": "Textfärg för knappar",
  "contentAlign": "Innehållsjustering",
  "alignTop": "Övre",
  "alignMiddle": "Mitten",
  "maskColor": "Maskfärg",
  "options": "Alternativ",
  "optionsDescription": "Ange beteendeinställningar för startskärmen."
});