define({
  "instruction": "Valitse ja määritä karttatasot, jotka näytetään ominaisuustietotaulussa alun perin.",
  "label": "Karttataso",
  "show": "Näytä",
  "actions": "Määritä karttatason kentät",
  "field": "Kenttä",
  "alias": "Alias",
  "visible": "Näkyvä",
  "linkField": "Linkkikenttä",
  "noLayers": "Kohdekarttatasoja ei ole käytettävissä",
  "back": "Takaisin",
  "exportCSV": "Salli vienti CSV-tiedostoon",
  "expand": "Laajenna pienoisohjelma aluksi",
  "filterByExtent": "Ota käyttöön Suodata kartan laajuuden mukaan oletusarvoisesti",
  "restore": "Palauta oletusarvo",
  "ok": "OK",
  "cancel": "Peruuta",
  "includePoint": "Sisällystä vietyyn tiedostoon pistekoordinaatit",
  "configureLayerFields": "Määritä karttatason kentät",
  "result": "Tallennus onnistui",
  "warning": "Valitse ensin Näytä-vaihtoehto.",
  "fieldCheckWarning": "Vähintään yksi kenttä on valittava.",
  "unsupportQueryWarning": "Karttatason on tuettava kyselytoimintoa, jotta karttatason voi näyttää Ominaisuustietotaulu-pienoisohjelmassa. Varmista, että palvelun kyselyominaisuus on käytössä.",
  "unsupportQueryLayers": "Seuraavien karttatasojen on tuettava kyselytoimintoa, jotta ne voi näyttää Ominaisuustietotaulu-pienoisohjelmassa. Varmista, että palvelun kyselyominaisuus on käytössä.",
  "fieldName": "Nimi",
  "fieldAlias": "Alias",
  "fieldVisibility": "Näkyvyys",
  "fieldActions": "Toimet",
  "showAttachments": "Näytä liitteet"
});