define({
  "common": {
    "apply": "Bruk",
    "ok": "OK",
    "cancel": "Avbryt",
    "yes": "Ja",
    "no": "Nei",
    "next": "Neste",
    "previous": "Forrige",
    "back": "Bak",
    "selected": "valgte",
    "name": "Navn",
    "usage": "Bruk",
    "settings": "Innstillinger",
    "home": "Hjem",
    "link": "Kobling",
    "messages": "Meldinger",
    "outputs": "Utdata",
    "title": "Tittel",
    "thumbnail": "Miniatyrbilde",
    "url": "URL",
    "actions": "Handlinger",
    "layer": "Lag",
    "action": "Handling",
    "input": "Inndata",
    "output": "Resultat",
    "type": "Type",
    "required": "Påkrevd",
    "options": "Alternativer",
    "label": "Etikett",
    "tooltip": "Verktøytips",
    "visible": "Synlig",
    "symbol": "Symbol",
    "popup": "Sprettoppvindu",
    "upload": "Opplasting",
    "execute": "Utfør",
    "help": "Hjelp",
    "executing": "Utfører",
    "clear": "Fjern",
    "error": "Feil",
    "zoomTo": "Zoom til",
    "attribute": "Attributt",
    "exports": "Eksporter",
    "check": "Kontroller",
    "save": "Lagre",
    "close": "Ja",
    "deleteText": "Slett",
    "map": "Kart",
    "scene": "Scene",
    "reset": "Tilbakestill",
    "icon": "Ikon",
    "folder": "Mappe",
    "share": "Dele",
    "view": "Vis",
    "newText": "Ny",
    "edit": "Rediger",
    "wkid": "WKID",
    "table": "Tabell",
    "zoomIn": "Zoom inn",
    "zoomOut": "Zoom ut",
    "continue1": "Fortsett",
    "longitude": "Lengdegrad",
    "latitude": "Breddegrad",
    "custom": "Tilpasset",
    "image": "Bilde",
    "font": "Skrifttype",
    "text": "Tekst",
    "all": "Alle",
    "number": "Tall",
    "percentage": "Prosentandel",
    "unit": "Enhet",
    "thousand": "Tusen",
    "billion": "Milliard",
    "million": "Million",
    "none": "Ingen",
    "field": "Felt",
    "operation": "Operasjon",
    "disableUpdateGeometry": "Deaktiver geometrioppdatering",
    "preview": "Forhåndsvisning"
  },
  "errorCode": "Kode",
  "errorMessage": "Melding",
  "errorDetail": "Detaljer",
  "widgetPlaceholderTooltip": "For å konfigurere går du til Widgeter og klikker på tilsvarende plassholder",
  "fieldStatistics": {
    "selectField": "Velg felt",
    "statistics": "Statistikk",
    "field": "Felt",
    "count": "Antall verdier",
    "sum": "Summen av verdier",
    "min": "Minimum",
    "max": "Maksimum",
    "ave": "Gjennomsnitt",
    "stddev": "Standardavvik"
  },
  "symbolChooser": {
    "preview": "Forhåndsvisning",
    "basic": "Grunnleggende",
    "arrows": "Piler",
    "business": "Næringsliv",
    "cartographic": "Kartografisk",
    "nationalParkService": "National Park Service",
    "outdoorRecreation": "Utendørsaktiviteter",
    "peoplePlaces": "Folk og steder",
    "safetyHealth": "Helse og sikkerhet",
    "shapes": "Former",
    "transportation": "Transport",
    "symbolSize": "Symbolstørrelse",
    "color": "Farge",
    "alpha": "Alfa",
    "outlineColor": "Omrissfarge",
    "outlineWidth": "Omrissbredde",
    "style": "Stil",
    "width": "Bredde",
    "text": "Tekst",
    "fontColor": "Skriftfarge",
    "fontSize": "Skriftstørrelse",
    "transparency": "Gjennomsiktighet",
    "solid": "Heltrukket",
    "dash": "Strek",
    "dot": "Prikk",
    "dashDot": "Strek prikk",
    "dashDotDot": "Strek prikk prikk",
    "customImage": "Egendefinert bilde",
    "chooseFile": "Velg fil",
    "noFileChoosen": "Ingen fil er valgt."
  },
  "transparency": {
    "opaque": "Ugjennomsiktig",
    "transparent": "Gjennomsiktighet"
  },
  "rendererChooser": {
    "domain": "Domene",
    "use": "Bruke",
    "singleSymbol": "Et enkeltsymbol",
    "uniqueSymbol": "Unike symboler",
    "color": "Farge",
    "size": "Størrelse",
    "toShow": "For å vise",
    "colors": "Farger",
    "classes": "Klasser:",
    "symbolSize": "Symbolstørrelse",
    "addValue": "Legg til verdi",
    "setDefaultSymbol": "Angi standardsymbol",
    "defaultSymbol": "Standardsymbol",
    "selectedSymbol": "Valgt symbol",
    "value": "Verdi",
    "label": "Etikett",
    "range": "Område"
  },
  "drawBox": {
    "point": "Punkt",
    "line": "Linje",
    "polyline": "Polylinje",
    "freehandPolyline": "Frihåndspolylinje",
    "triangle": "Trekant",
    "extent": "Utstrekning",
    "circle": "Sirkel",
    "ellipse": "Ellipse",
    "polygon": "Polygon",
    "freehandPolygon": "Frihåndspolygon",
    "text": "Tekst",
    "clear": "Tøm"
  },
  "popupConfig": {
    "title": "Tittel",
    "add": "Legg til",
    "fields": "Felter",
    "noField": "Ingen felt",
    "visibility": "Synlig",
    "name": "Navn",
    "alias": "Alias",
    "actions": "Handlinger"
  },
  "includeButton": {
    "include": "Inkluder"
  },
  "loadingShelter": {
    "loading": "Laster inn"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Fant ingen tjeneste.",
    "unableConnectTo": "Kan ikke koble til",
    "invalidUrlTip": "URL-en du har angitt, er ugyldig eller ikke tilgjengelig."
  },
  "serviceBrowser": {
    "noGpFound": "Fant ingen geoprosesseringstjeneste.",
    "unableConnectTo": "Kan ikke koble til"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Fant ingen karttjeneste eller geoobjektstjeneste.",
    "unableConnectTo": "Kan ikke koble til"
  },
  "basicServiceChooser": {
    "validate": "Valider",
    "example": "Eksempel",
    "set": "Angi"
  },
  "urlInput": {
    "invalidUrl": "Ugyldig URL."
  },
  "urlComboBox": {
    "invalidUrl": "Ugyldig URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Legg til et uttrykk",
    "addSet": "Legg til et sett",
    "matchMsg": "Hent geoobjekter i laget som samsvarer med ${any_or_all} av følgende uttrykk",
    "matchMsgSet": "${any_or_all} av de følgende uttrykkene i dette settet er sanne",
    "all": "Alt",
    "any": "Noen",
    "value": "Verdi",
    "field": "Felt",
    "unique": "Unike",
    "none": "Ingen",
    "and": "og",
    "valueTooltip": "Angi verdi",
    "fieldTooltip": "Velg fra et eksisterende felt",
    "uniqueValueTooltip": "Velg blant unike verdier i det valgte feltet",
    "stringOperatorIs": "er",
    "stringOperatorIsNot": "er ikke",
    "stringOperatorStartsWith": "begynner på",
    "stringOperatorEndsWith": "slutter på",
    "stringOperatorContains": "inneholder",
    "stringOperatorDoesNotContain": "inneholder ikke",
    "stringOperatorIsBlank": "er tomt",
    "stringOperatorIsNotBlank": "er ikke tomt",
    "dateOperatorIsOn": "er den",
    "dateOperatorIsNotOn": "er ikke den",
    "dateOperatorIsBefore": "er før",
    "dateOperatorIsAfter": "er etter",
    "dateOperatorIsOnOrBefore": "er på eller før",
    "dateOperatorIsOnOrAfter": "er på eller etter",
    "dateOperatorMinutes": "minutter",
    "dateOperatorHours": "timer",
    "dateOperatorDays": "dagene",
    "dateOperatorWeeks": "ukene",
    "dateOperatorMonths": "månedene",
    "dateOperatorYears": "år",
    "dateOperatorInTheLast": "i de/den siste",
    "dateOperatorNotInTheLast": "ikke i de/den siste",
    "dateOperatorIsBetween": "er mellom",
    "dateOperatorIsNotBetween": "er ikke mellom",
    "dateOperatorIsBlank": "er tomt",
    "dateOperatorIsNotBlank": "er ikke tomt",
    "numberOperatorIs": "er",
    "numberOperatorIsNot": "er ikke",
    "numberOperatorIsAtLeast": "er minst",
    "numberOperatorIsLessThan": "er mindre enn",
    "numberOperatorIsAtMost": "er maksimalt",
    "numberOperatorIsGreaterThan": "er større enn",
    "numberOperatorIsBetween": "er mellom",
    "numberOperatorIsNotBetween": "er ikke mellom",
    "numberOperatorIsBlank": "er tomt",
    "numberOperatorIsNotBlank": "er ikke tomt",
    "string": "Streng",
    "number": "Tall",
    "date": "Dato",
    "askForValues": "Spør om verdier",
    "prompt": "Spør",
    "hint": "Tips:",
    "error": {
      "invalidParams": "Ugyldige parametere.",
      "invalidUrl": "Ugyldig URL.",
      "noFilterFields": "Laget har ingen felter som kan brukes til å opprette filtre.",
      "invalidSQL": "Ugyldig SQL-uttrykk.",
      "cantParseSQL": "Kan ikke analysere SQL-uttrykket."
    },
    "caseSensitive": "Skille mellom store og små bokstaver",
    "notSupportCaseSensitiveTip": "Administrerte tjenester støtter ikke spørringer som skiller mellom små og store bokstaver.",
    "setFilterTip": "Angi filtre på riktig måte.",
    "listValues": "Listeverdier",
    "cascadeFilterTip": "Vis kun verdier filtrert av tidligere uttrykk.",
    "noneCascadeFilterTip": "Alle unike verdier i dette feltet",
    "previousCascadeFilterTip": "Verdier filtrert etter tidligere uttrykk",
    "allCascadeFilterTip": "Verdier filtrert etter alle andre uttrykk"
  },
  "featureLayerSource": {
    "layer": "Lag",
    "browse": "Bla gjennom",
    "selectFromMap": "Kart",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "Tjeneste-URL",
    "inputLayerUrl": "Angi kartlag-URL",
    "selectLayer": "Velg et geoobjektslag i gjeldende kart.",
    "chooseItem": "Velg et geoobjektslagelement.",
    "setServiceUrl": "Angi URL-adressen for en geoobjekts- eller karttjeneste.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Velg et geoobjektslag."
  },
  "queryableLayerSource": {
    "layer": "Lag",
    "browse": "Bla gjennom",
    "selectFromMap": "Kart",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "Tjeneste-URL",
    "inputLayerUrl": "Angi kartlag-URL",
    "selectLayer": "Velg et lag fra det gjeldende kartet.",
    "chooseItem": "Velg et element.",
    "setServiceUrl": "Angi URL-adressen til tjenesten.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Velg et lag."
  },
  "gpSource": {
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "Tjeneste-URL",
    "selectFromOnline": "ArcGIS Online",
    "setServiceUrl": "Angi URL-en for en geoprosesseringstjeneste.",
    "chooseItem": "Velg et element for geoprosesseringstjenesten.",
    "chooseTask": "Velg en geoprosesseringsoppgave."
  },
  "itemSelector": {
    "map": "Kart",
    "selectWebMap": "Velg webkart",
    "addMapFromOnlineOrPortal": "Finn og legg til et webkart som skal brukes i applikasjonen, fra ArcGIS Onlines offentlige ressurser eller ditt private innhold på ArcGIS Online eller Portal.",
    "searchMapName": "Søk etter kartnavn ...",
    "searchNone": "Vi finner ikke det du leter etter. Prøv på nytt.",
    "groups": "Grupper",
    "noneGroups": "Ingen grupper",
    "signInTip": "Påloggingsøkten har utløpt. Oppdater websiden for å logge på portalen din igjen.",
    "signIn": "Logg inn",
    "publicMap": "Felles",
    "myOrganization": "Min organisasjon",
    "myGroup": "Mine grupper",
    "myContent": "Mitt innhold",
    "count": "Antall",
    "fromPortal": "fra Portal",
    "fromOnline": "fra ArcGIS.com",
    "noneThumbnail": "Miniatyrbilde ikke tilgjengelig",
    "owner": "owner",
    "signInTo": "Logg inn på",
    "lastModified": "Sist endret",
    "moreDetails": "Flere detaljer",
    "mostRecent": "Nyest",
    "mostViewed": "Mest viste",
    "highestRated": "Høyest rangering",
    "viewItemDetails": "Vis elementdetaljer"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Tjenesten støtter ikke spørringer."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Det er ingen aktuelle lag tilgjengelig i kartet."
  },
  "layerInfosMenu": {
    "titleBasemap": "Bakgrunnskart",
    "titleLayers": "Operasjonelle lag",
    "labelLayer": "Lagnavn",
    "itemZoomTo": "Zoom til",
    "itemTransparency": "Gjennomsiktighet",
    "itemTransparent": "Gjennomsiktig",
    "itemOpaque": "Ugjennomsiktig",
    "itemMoveUp": "Flytt opp",
    "itemMoveDown": "Flytt ned",
    "itemDesc": "Beskrivelse",
    "itemDownload": "Last ned",
    "itemToAttributeTable": "Vis i attributtabell"
  },
  "imageChooser": {
    "unsupportReaderAPI": "Todo: Leseren støtter ikke filleser-API",
    "readError": "Kan ikke lese filen.",
    "unknowError": "kan ikke fullføre operasjonene",
    "invalidType": "Ugyldig filtype.",
    "cropImage": "Beskjær bilde",
    "exceed": "Filstørrelsen må ikke overskride 1 024 kB",
    "enableFlash": "Aktiver Adobe Flash før du blar til et bilde.",
    "cropWaining": "Velg et bilde som er minst ${width} x ${height} piksler.",
    "toolTip": "Resultatet blir best hvis bildet er ${width} piksler bredt og ${height} piksler høyt. Andre størrelser må justeres for at de skal passe. Godkjente bildeformater er: PNG, GIF og JPEG."
  },
  "simpleTable": {
    "moveUp": "Flytt opp",
    "moveDown": "Flytt ned",
    "deleteRow": "Slett",
    "edit": "Rediger"
  },
  "urlParams": {
    "invalidToken": "Ugyldig token",
    "validateTokenError": "Ugyldig token eller nettverksfeil"
  },
  "exportTo": {
    "exportTo": "Eksporter",
    "toCSV": "Eksporter til CSV-fil",
    "toFeatureCollection": "Eksporter til geoobjektssamling",
    "toGeoJSON": "Eksporter til GeoJSON"
  },
  "appState": {
    "title": "Apptilstand",
    "restoreMap": "Klikk for å gjenopprette kartutstrekningen og synligheten for lagene der du slapp."
  },
  "featureActions": {
    "featureActions": "Geoobjekthandlinger",
    "ZoomTo": "Zoom til",
    "PanTo": "Panorer til",
    "Flash": "Blits",
    "ShowPopup": "Vis oppsprettvindu",
    "CreateLayer": "Opprett lag",
    "ShowStatistics": "Statistikk...",
    "ClearSelection": "Tøm utvalg",
    "ExportToCSV": "Eksporter til CSV-fil",
    "ShowSelectedFeature": "Vis valgte geoobjekter",
    "ExportToFeatureCollection": "Eksporter til geoobjektssamling",
    "ExportToGeoJSON": "Eksporter til GeoJSON",
    "EditAttributes": "Rediger attributter",
    "AddMarker": "Legg til en markør",
    "RemoveMarker": "Fjern markør",
    "SaveToMyContent": "Lagre i Mitt innhold"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Relatert lag",
    "selectedFeatures": "Bruk valgte geoobjekter",
    "drawShapesTip": "Tegn former for å velge geoobjekter",
    "pleaseDrawShapesTip": "Tegn former for å velge geoobjekter",
    "allFeaturesTip": "Alle geoobjekter i laget",
    "selectFeaturesOrDrawShapesTip": "Bruk geoobjektene som er valgt i laget, eller tegne former på kartet for å begrense antall geoobjekter."
  },
  "searchDistance": {
    "applySearchDistance": "Bruk en søkeavstand",
    "applySearchDistanceToFeatures": "Bruk en søkeavstand for geoobjektene som er valgt"
  },
  "units": {
    "miles": "Miles",
    "milesAbbr": "mi",
    "kilometers": "Kilometer",
    "kilometersAbbr": "km",
    "feet": "Fot",
    "feetAbbr": "ft",
    "meters": "Meter",
    "metersAbbr": "m",
    "yards": "Yard",
    "yardsAbbr": "yd",
    "acres": "Acre",
    "acresAbbr": "acre",
    "nauticalMiles": "Nautiske mil",
    "nauticalMilesAbbr": "nmi",
    "uSSurveyFeet": "US survey feet",
    "uSSurveyFeetAbbr": "ftUS",
    "decimalDegree": "Desimalgrader",
    "decimalDegreeAbbr": "dd",
    "degreeMinuteSeconds": "Grader minutter sekunder",
    "degreeMinuteSecondsAbbr": "d-m-s",
    "squareMiles": "Kvadratmiles",
    "squareMilesAbbr": "mi²",
    "squareKilometer": "Kvadratkilometer",
    "squareKilometerAbbr": "km²",
    "squareFeet": "Kvadratfot",
    "squareFeetAbbr": "ft²",
    "squareMeters": "Kvadratmeter",
    "squareMetersAbbr": "m²",
    "squareYards": "Kvadratyard",
    "squareYardsAbbr": "yd²",
    "squareUSSurveyFeet": "US survey feet²",
    "squareUSSurveyFeetAbbr": "sq ftUS"
  },
  "featureSetChooser": {
    "select": "Velg",
    "dragBox": "Dra",
    "dragMouse": "Dra med musen",
    "selectByRectangle": "Velg etter rektangel",
    "selectFeaturesTip": "Velg geoobjekter ved å dra en ramme rundt dem på kartet",
    "newSelectionTip": "Opprett nytt utvalg",
    "addSelectionTip": "Legg til utvalg",
    "removeSelectionTip": "Fjern fra utvalg",
    "selectFromCurrentSelectionTip": "Velg fra gjeldende utvalg",
    "unselectAllSelectionTip": "Opphev valget av alle valgte geoobjekter",
    "selectByPolygon": "Velg etter polygon",
    "selectByCircle": "Velg etter sirkel",
    "selectByLine": "Velg etter linje",
    "chooseSelectingTools": "Velg utvalgsverktøy",
    "darw": "Tegn",
    "drawShap": "Tegne en form"
  },
  "widgetManager": {
    "createWidgetError": "Feil ved oppretting av miniprogram",
    "createWidgetSettingPageError": "Feil under oppretting av side med innstillinger for miniprogram",
    "loadWidgetResourceError": "Feil under lasting av miniprogramressurs"
  },
  "shareOptions": {
    "shareMap": "Velg hvem som kan se denne appen",
    "shareMapTips": "Appen er for tiden delt med disse personene",
    "everyone": "Alle",
    "theseGroups": "Disse gruppene"
  },
  "shareLink": {
    "email": "e-post",
    "shareEmail": "E-post",
    "facebook": "facebook",
    "shareFacebook": "Facebook",
    "twitter": "twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "Bygg inn denne appen på et webområde",
    "shareEmailSubject": "Deler webapp:",
    "shareEmailTxt1": "Her er en webapp som er delt med deg ved hjelp av Web AppBuilder for ArcGIS.",
    "shareEmailTxt2": "Du kan opprette og dele din egen webapp med Esri Web AppBuilder for ArcGIS.",
    "shareEmailTxt3": "Du finner detaljert informasjon på http://www.esri.com/software/web-appbuilder.",
    "smallSize": "Liten",
    "mediumSize": "Middels",
    "largeSize": "Stor",
    "customSize": "Tilpasset",
    "embed": "Bygg inn denne appen på et webområde",
    "more": "Alternativer for innbygging",
    "changeShareSettings": "Endre delingsinnstillinger",
    "shareLinkText": "Del en kobling til denne appen",
    "linkOptions": "Koblingsalternativer",
    "linkOptionsUrlParameters": "Velg URL-parametere for koblingen",
    "currentMapExtent": "Gjeldende kartutstrekning",
    "chooseCenterWithLevel": "Klikk på kartet for å definere kartets midtpunkt med zoomnivå",
    "chooseCenterWithScale": "Klikk på kartet for å definere kartets midtpunkt med kartmålestokk",
    "findLocation": "Finn lokasjonen eller geoobjektet og zoom til den/det",
    "findLocation_inputPlaceholder": "Ditt sted eller geoobjekt",
    "queryFeature": "Finn et geoobjekt ved hjelp av en spørring og zoom til det",
    "addMarker": "Legg til en markør i kartet",
    "addMarker_titlePlaceholder": "Tittel på popup for markør",
    "addMarker_symbolURL": "URL for markørsymbol",
    "addMarker_label": "Markøretikett",
    "popupTitle": "Popuptittel",
    "zoomLevel": "Zoomnivå",
    "overwirteMobileLayout": "Overskriv standard skjermstørrelse for mobillayout",
    "language": "Angi visningsspråk for appen",
    "auth": "Godkjenn bruker automatisk",
    "linkPreview": "Forhåndsvis kobling",
    "useShortenLink": "Kort kobling",
    "shareMapUrlExtent": "Del gjeldende kartutstrekning",
    "shareToWebTips": "Denne appen er ikke delt offentlig. Det kan hende at andre ikke kan se den."
  },
  "webSceneLoader": {
    "webglSupportTip": "Nettleseren støtter ikke 3D-webapper."
  },
  "map": {
    "basemapNotAvailable": "Bakgrunnskart ikke tilgjengelig.",
    "displayDefaultBasemap": "Viser i stedet standardbakgrunnskartet.",
    "layerLoadedError": "Laget ${layers} kan ikke legges til i kartet."
  },
  "popup": {
    "relatedTables": "Relaterte tabeller:",
    "relatedRecords": "Relaterte poster:",
    "noRelatedRecotds": "Ingen relaterte poster ble funnet.",
    "chooseFieldTip": "Velg et attributt for å vise listen",
    "saveAsPopupTitle": "Samme som tittel på popup"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "Det er for mange geoobjekter i utvalget. Det kan ta lang tid å hente og vise dem i kartet.",
    "askForContinue": "Vil du fortsette?"
  },
  "colorPalette": {
    "transparent": "Gjennomsiktig",
    "custom": "Tilpasset"
  },
  "temperature": {
    "celsius": "Celsius",
    "fahrenheit": "Fahrenheit"
  },
  "report": {
    "printButtonLabel": "Skriv ut",
    "reportDimensionsMsg": "Denne rapporten er beregnet på utskrift på ${paperSize}-papir",
    "unableToPrintMapMsg": "Det oppstod en feil under utskrift av kartet/kartene.",
    "notesHint": "Skriv inn kommentarer her",
    "landscape": "Landskap",
    "portrait": "Stående",
    "mapOnly": "MAP_ONLY",
    "a0": "A0",
    "a1": "A1",
    "a2": "A2",
    "a3": "A3",
    "a4": "A4",
    "a5": "A5",
    "letterANSIA": "Letter ANSI A",
    "tabloidANSIB": "Tabloid ANSI B",
    "letter": "Letter",
    "legal": "Juridisk",
    "tabloid": "Tabloid",
    "ansi_a": "ANSI A",
    "ansi_b": "ANSI B",
    "ansi_c": "ANSI C",
    "ansi_d": "ANSI D",
    "ansi_e": "ANSI E"
  },
  "snapshot": {
    "snapshot_complete": "Oppretting av øyeblikksbilde var vellykket.",
    "snapshot_failed": "Kunne ikke opprette øyeblikksbilde.",
    "snapshot_append": "Snapshot",
    "utc": "UTC"
  },
  "statisticsChart": {
    "enlarge": "Forstørr",
    "setting": "Innstilling",
    "count": "Antall",
    "horizontalAxis": "Horisontal akse",
    "verticalAxis": "Vertikal akse",
    "dataLabels": "Dataetikketter",
    "color": "Farge"
  },
  "frameworkDatasource": {
    "setDataSource": "Angi datakilde",
    "customDataSource": "Ekstra datakilde",
    "selectCustomDataTip": "Velg en datakilde fra denne appen.",
    "widgetOutputs": "Widget-utdata",
    "noExtraDsAvailable": "Ingen ekstra datakilder er tilgjengelig.",
    "addExtraDsTip": "Gå til Attributt-fanen i byggeverktøyet, og klikk på Ekstra datakilde for å legge til data.",
    "widgetOutpusListTip": "Widget-utdata (hvis slike finnes) er også oppført her."
  },
  "gridLayout": {
    "addWidgetTip": "Legg til widgeter her via Widget-fanen",
    "modifyLayout": "Endre oppsett",
    "dragToAdd": "Dra for å legge til",
    "mapArea": "KARTOMRÅDE"
  },
  "noEditPrivileges": "Kontoen har ikke rettigheter til å opprette eller endre data.",
  "invalidConfiguration": "Widgeten er ikke konfigurert eller lagene i konfigurasjonen finnes ikke i kartet lenger. Åpne appen i byggemodus, og konfigurer widgeten på nytt."
});