define({
  "_widgetLabel": "Koordinat",
  "hintMessage": "Klikk på kartet for å få koordinater",
  "defaultLabel": "Standard",
  "realtimeLabel": "Beveg musen for å få koordinater",
  "computing": "Behandler...",
  "latitudeLabel": "Breddegrad",
  "longitudeLabel": "Lengdegrad",
  "loading": "laster inn...",
  "enableClick": "Klikk for å aktivere funksjonen for å klikke på kartet for å få koordinater",
  "disableClick": "Klikk for å deaktivere funksjonen for å klikke på kartet for å få koordinater",
  "Default": "Standard",
  "Inches": "Tommer",
  "Foot": "Fot",
  "Yards": "Yards",
  "Miles": "Miles",
  "Nautical_Miles": "Nautiske mil",
  "Millimeters": "Millimeter",
  "Centimeters": "Centimeter",
  "Meter": "Meter",
  "Kilometers": "Kilometer",
  "Decimeters": "Desimeter",
  "Decimal_Degrees": "Grader",
  "Degree_Minutes_Seconds": "Grader minutter sekunder",
  "MGRS": "MGRS",
  "USNG": "USNG"
});