define({
  "_widgetLabel": "Koordinaat",
  "hintMessage": "Klikkige koordinaatide hankimiseks kaardile",
  "defaultLabel": "Vaikimisi",
  "realtimeLabel": "Koordinaatide hankimiseks liigutage kursorit",
  "computing": "Arvutamine...",
  "latitudeLabel": "Laius",
  "longitudeLabel": "Pikkus",
  "loading": "laadimine...",
  "enableClick": "Klikkige, et lubada klikkimise kaudu kaardilt koordinaate hankida",
  "disableClick": "Klikkige, et keelata klikkimise kaudu kaardilt koordinaate hankida",
  "Default": "Vaikimisi",
  "Inches": "tolli",
  "Foot": "Jalga",
  "Yards": "jardi",
  "Miles": "miili",
  "Nautical_Miles": "Meremiili",
  "Millimeters": "millimeeter",
  "Centimeters": "sentimeetrit",
  "Meter": "Meetrit",
  "Kilometers": "kilomeetrit",
  "Decimeters": "detsimeetrit",
  "Decimal_Degrees": "Kraadi",
  "Degree_Minutes_Seconds": "Kraadid minutid sekundid",
  "MGRS": "MGRS",
  "USNG": "USNG"
});