define(
   ({
    id: 'מספר זיהוי',
    state: "כברירת מחדל, הקואורדינטות יוצגו במערכת הקואורדינטות של המפה הנוכחית. להצגת קואורדינטות במערכת קואורדינטות אחרת, יש להוסיף אותן ולהגדיר המרה מתאימה.",
    outputUnit: "יחידת פלט",
    wkid: "פלט WKID",
    label: "שם מערכת קואורדינטות הפלט",
    transformationWkid: "המרת WKID",
    transformationLabel: "תוית המרה",
    transformForward: "המרה קדימה",
    actions: "פעולות",
    warning: "אנא הכנס WKID של ייחוס מרחבי תקין!",
    tfWarning: "אנא הכנס WKID של דטום ייחוס מרחבי תקין!",
    spinnerLabel: "בצע עיגול קואורדינטות ל: ",
    decimalPlace: "מיקום עשרוני",
    separator: "הצג מפריד אלפים",
    getVersionError: "לא ניתן לקבל את הוורסיה של שירות הגיאומטריה",

    add: "הוסף מערכת קואורדינטות לפלט",
    edit: "ערוך מערכת קואורדינטות",
    output: "מערכת קואורדינטות לפלט",
    cName: "שם מערכת קואורדינטות",
    units: "יחידות תצוגה: ",
    datum: "דטום המרה",
    tName: "שם המרה",
    tWKIDPlaceHolder: "WKID של ההמרה",
    forward: "השתמש בהמרה לאחור",
    ok: "אישור",
    cancel: 'ביטול',
    olderVersion: "שירות הישויות לא תומך בפעולת המרה",
    REPEATING_ERROR: " מערכת קואורדינטות קיימת ברשימת הפלט.",

    Default: "ברירת מחדל",
    Inches: "אינצ׳ים",
    Foot: "רגל",
    Yards: "יארד",
    Miles: "מיילים",
    Nautical_Miles: "מיילים ימיים",
    Millimeters: "מילימטרים",
    Centimeters: "סנטימטרים",
    Meter: "מטרים",
    Kilometers: "קילומטרים",
    Decimeters: "דצימטרים",
    Decimal_Degrees: "מעלות עשרוניות",
    Degree_Minutes_Seconds: "מעלות דקות שניות",
    MGRS: "MGRS",
    USNG: "USNG"
  })
);