define({
  "_widgetLabel": "座標",
  "hintMessage": "マップをクリックして座標を取得",
  "defaultLabel": "デフォルト",
  "realtimeLabel": "マウスを移動して座標を取得",
  "computing": "計算中...",
  "latitudeLabel": "緯度",
  "longitudeLabel": "経度",
  "loading": "読み込んでいます...",
  "enableClick": "クリックして、マップのクリックを有効化して座標を取得",
  "disableClick": "クリックして、マップのクリックを無効化して座標を取得",
  "Default": "デフォルト",
  "Inches": "インチ",
  "Foot": "フィート",
  "Yards": "ヤード",
  "Miles": "マイル",
  "Nautical_Miles": "海里",
  "Millimeters": "ミリメートル",
  "Centimeters": "センチメートル",
  "Meter": "メートル",
  "Kilometers": "キロメートル",
  "Decimeters": "デシメートル",
  "Decimal_Degrees": "度",
  "Degree_Minutes_Seconds": "度分秒",
  "MGRS": "MGRS",
  "USNG": "USNG"
});