define(
   ({
    id: 'ID',
    state: "Koordinaterne vises som standard i det aktuelle korts koordinatsystem. Hvis du vil have koordinaterne vist i andre koordinatsystemer, skal du tilføje dem og angive passende transformationer.",
    outputUnit: "Output-enhed",
    wkid: "Output-WKID",
    label: "Oplys navnet på koordinatsystemet",
    transformationWkid: "Transformations-WKID",
    transformationLabel: "Transformationsetiket",
    transformForward: "Transformér fremad",
    actions: "Handlinger",
    warning: "Angiv et gyldigt geografisk reference-WKID!",
    tfWarning: "Angiv et gyldigt WKID for datotransformation!",
    spinnerLabel: "Afrund koordinater til: ",
    decimalPlace: "decimalpladser",
    separator: "Vis tusindseparatorer",
    getVersionError: "Kan ikke hente versionen af geometritjenesten",

    add: "Tilføj koordinatsystem for output",
    edit: "Redigér koordinatsystem",
    output: "Koordinatsystem for output",
    cName: "Koordinatsystemets navn",
    units: "Enheder for visning: ",
    datum: "Datotransformation",
    tName: "Transformationsnavn",
    tWKIDPlaceHolder: "WKID for transformationen",
    forward: "Brug transformation fremad",
    ok: "OK",
    cancel: 'Annuller',
    olderVersion: "Geometritjenesten understøtter ikke transformation",
    REPEATING_ERROR: " Koordinatsystemet findes på output-listen.",

    Default: "Standard",
    Inches: "Inches",
    Foot: "Fod",
    Yards: "Yards",
    Miles: "Miles",
    Nautical_Miles: "Sømil",
    Millimeters: "Millimeter",
    Centimeters: "Centimeter",
    Meter: "Meter",
    Kilometers: "Kilometer",
    Decimeters: "Decimeter",
    Decimal_Degrees: "Decimalgrader",
    Degree_Minutes_Seconds: "Grader Minutter Sekunder",
    MGRS: "MGRS",
    USNG: "USNG"
  })
);