define({
  "_widgetLabel": "Coordonată",
  "hintMessage": "Faceţi clic pe hartă pentru a obţine coordonate",
  "defaultLabel": "Implicit",
  "realtimeLabel": "Deplasaţi mouse-ul pentru a obţine coordonate",
  "computing": "Se calculează...",
  "latitudeLabel": "Latitudine",
  "longitudeLabel": "Longitudine",
  "loading": "se încarcă...",
  "enableClick": "Faceţi clic pentru a activa obţinerea de coordonate prin intermediul clicurilor pe hartă",
  "disableClick": "Faceţi clic pentru a dezactiva obţinerea de coordonate prin intermediul clicurilor pe hartă",
  "Default": "Implicit",
  "Inches": "Inci",
  "Foot": "Ft",
  "Yards": "Yarzi",
  "Miles": "Mile",
  "Nautical_Miles": "Mile marine",
  "Millimeters": "Milimetri",
  "Centimeters": "Centimetri",
  "Meter": "Metri",
  "Kilometers": "Kilometri",
  "Decimeters": "Decimetri",
  "Decimal_Degrees": "Grade",
  "Degree_Minutes_Seconds": "Grade minute secunde",
  "MGRS": "MGRS",
  "USNG": "USNG"
});