define({
  "_widgetLabel": "Lijst met lagen",
  "titleBasemap": "Basiskaarten",
  "titleLayers": "Operationele lagen",
  "labelLayer": "Kaartlaagnaam",
  "itemZoomTo": "Zoomen naar",
  "itemTransparency": "Transparant",
  "itemTransparent": "Transparant",
  "itemOpaque": "Niet transparant",
  "itemMoveUp": "Naar boven verplaatsen",
  "itemMoveDown": "Naar beneden verplaatsen",
  "itemDesc": "Beschrijving",
  "itemDownload": "Downloaden",
  "itemToAttributeTable": "Bekijken in Attribuuttabel",
  "itemShowItemDetails": "Itemdetails weergeven",
  "empty": "leeg",
  "removePopup": "Pop-up uitschakelen",
  "enablePopup": "Pop-up inschakelen",
  "turnAllLayersOff": "Zet alle lagen uit",
  "turnAllLayersOn": "Zet alle lagen aan",
  "expandAllLayers": "Alle lagen uitvouwen",
  "collapseAlllayers": "Alle lagen samenvouwen",
  "turnAllLabelsOff": "Zet alle labels uit",
  "turnAllLabelsOn": "Zet alle labels aan",
  "showLabels": "Labels weergeven",
  "hideLables": "Labels verbergen"
});