define({
  "instruction": "Wybierz i skonfiguruj warstwy, które będą wyświetlane początkowo w tabeli atrybutów.",
  "label": "Warstwa",
  "show": "Pokaż",
  "actions": "Skonfiguruj pola warstwy",
  "field": "Pole",
  "alias": "Alias",
  "visible": "Widoczne",
  "linkField": "Pole łącza",
  "noLayers": "Brak warstw obiektu",
  "back": "Wstecz",
  "exportCSV": "Zezwalaj na eksport do pliku CSV",
  "expand": "Wstępnie rozwiń widżet",
  "filterByExtent": "Domyślnie włącz opcję Filtruj wg zasięgu mapy",
  "restore": "Przywróć wartość domyślną",
  "ok": "OK",
  "cancel": "Anuluj",
  "includePoint": "Dołącz współrzędne punktów do wyeksportowanego pliku",
  "configureLayerFields": "Skonfiguruj pola warstwy",
  "result": "Zapisano pomyślnie",
  "warning": "Wybierz najpierw element Pokaż opcję.",
  "fieldCheckWarning": "Należy zaznaczyć co najmniej jedno pole.",
  "unsupportQueryWarning": "Warstwa musi obsługiwać zapytania w celu wyświetlenia w widżecie tabeli atrybutów. Upewnij się, że funkcja zapytania w usłudze jest włączona.",
  "unsupportQueryLayers": "Ta warstwa musi obsługiwać zapytania w celu wyświetlenia w widżecie tabeli atrybutów.  Upewnij się, że funkcja zapytania w usłudze jest włączona.",
  "fieldName": "Nazwa",
  "fieldAlias": "Alias",
  "fieldVisibility": "Widoczność",
  "fieldActions": "Operacje",
  "showAttachments": "Pokaż załączniki"
});