define({
  "sourceSetting": "חפש הגדרות מקור",
  "instruction": "הוסף והגדר שירותי עיגון כתובות או שכבות ישויות בתור מקורות חיפוש. מקורות אלה שמצוינים קובעים מה ניתן לחיפוש בתוך תיבת החיפוש.",
  "add": "הוסף מקור חיפוש",
  "addGeocoder": "הוסף מעגן כתובות",
  "geocoder": "מעגן כתובות",
  "setLayerSource": "הגדר מקור שכבה",
  "setGeocoderURL": "הגדר URL של מעגן הכתובות",
  "searchableLayer": "שכבת יישויות",
  "name": "שם",
  "countryCode": "קוד/ים של ארצות או אזורים",
  "countryCodeEg": "לדוגמה ",
  "countryCodeHint": "השארת הערך הזה ריק תפעיל חיפוש בכל הארצות והאזורים",
  "generalSetting": "הגדרות כלליות",
  "allPlaceholder": "טקסט Placeholder לחיפוש מלא: ",
  "showInfoWindowOnSelect": "הצג חלון קופץ עבור הישות או המיקום שנמצאו",
  "searchInCurrentMapExtent": "חפש רק בתיחום המפה הנוכחי",
  "zoomScale": "קנה מידה להתמקדות",
  "locatorUrl": "URL של מעגן הכתובות",
  "locatorName": "שם מעגן הכתובות",
  "locatorExample": "דוגמה",
  "locatorWarning": "גרסה זו של שירות עיגון הכתובות אינה נתמכת. הווידג'ט תומך בשירות עיגון הכתובות בגרסה 10.1 ואילך.",
  "locatorTips": "אין הצעות זמינות מפני ששירות עיגון הכתובות אינו תומך ביכולת הצעה.",
  "layerSource": "מקור שכבה",
  "searchLayerTips": "אין הצעות זמינות מפני ששירות התמיכה אינו תומך ביכולת עימוד.",
  "placeholder": "טקסט מציין מיקום (Placeholder)",
  "searchFields": "שדות חיפוש",
  "displayField": "הצג שדה",
  "exactMatch": "התאמה מדויקת",
  "maxSuggestions": "מקסימום הצעות",
  "maxResults": "מקסימום תוצאות",
  "enableLocalSearch": "הפעל חיפוש מקומי",
  "minScale": "קנ\"מ מינימלי",
  "minScaleHint": "כאשר קנה המידה גדול יותר מקנה מידה זה, החיפוש המקומי יבוצע",
  "radius": "רדיוס",
  "radiusHint": "מציין את רדיוס האזור מסביב למרכז המפה הנוכחית שמשמש להגדלת הדירוג של מועמדים לעיגון כתובות, כך שהמועמדים הקרובים ביותר למיקום יוחזרו ראשונים.",
  "meters": "מטרים",
  "setSearchFields": "הגדר שדות חיפוש",
  "set": "הגדר",
  "fieldSearchable": "ניתן לחיפוש",
  "fieldName": "שם",
  "fieldAlias": "כינוי",
  "ok": "אישור",
  "cancel": "חזור",
  "invalidUrlTip": "ה-URL ‏${URL} שגוי או אינו נגיש."
});