define(
   ({
    "sourceSetting": "חפש הגדרות מקור",
    "instruction": "הוסף וקבע קונפיגורציה של שירותי עיגון כתובות או שכבות של תכונות כמקורות חיפוש. המקורות שצוינו קובעים אילו פריטים ניתנים לחיפוש בתוך תיבת החיפוש.",
    "add": "הוסף מקור חיפוש",
    "addGeocoder": "הוסף מעגן כתובות",
    "geocoder": "מעגן כתובות",
    "setLayerSource": "הגדר מקור שכבה",
    "setGeocoderURL": "הגדר URL של מעגן הכתובות",
    "searchableLayer": "שכבת ישות",
    "name": "שם",
    "countryCode": "קודי ארצות או אזורים",
    "countryCodeEg": "לדוגמה, ",
    "countryCodeHint": "השארת הערך הזה ריק תפעיל חיפוש בכל הארצות והאזורים",
    "generalSetting": "הגדרות כלליות",
    "allPlaceholder": "טקסט Placeholder לחיפוש מלא: ",
    "showInfoWindowOnSelect": "הצג חלונית קופצת עבור הישות או המיקום שנמצאו",
    "searchInCurrentMapExtent": "חפש רק בתיחום המפה הנוכחי",
    "locatorUrl": "URL של מעגן הכתובות",
    "locatorName": "שם מעגן הכתובות",
    "locatorExample": "דוגמה",
    "locatorWarning": "גרסה זו של שירות עיגון הכתובות אינה נתמכת. הווידג\'ט תומך בשירות עיגון כתובות 00.0 ואילך.",
    "locatorTips": "אין הצעות זמינות מפני ששירות עיגון הכתובות אינו תומך ביכולת הצעה.",
    "layerSource": "מקור שכבה",
    "searchLayerTips": "אין הצעות זמינות מפני ששירות התמיכה אינו תומך ביכולת עימוד.",
    "placeholder": "טקסט מציין מיקום (Placeholder)",
    "searchFields": "שדות חיפוש",
    "displayField": "שדה תצוגה",
    "exactMatch": "התאמה מדויקת",
    "maxResults": "מקסימום תוצאות",
    "setSearchFields": "הגדר שדות חיפוש",
    "set": "הגדר",
    "fieldSearchable": "ניתן לחיפוש",
    "fieldName": "שם",
    "fieldAlias": "כינוי",
    "ok": "אישור",
    "cancel": "בטל",
    "invalidUrlTip": "ה-URL שהזנת לא חוקי או שלא ניתן לגשת אליו."
  })
);