define({
  "instruction": "A tela de abertura aparece antes do aplicativo estar acessível.",
  "defaultContent": "Adicione texto, links e gráficos pequenos aqui.",
  "requireConfirm": "Exige confirmação para continuar",
  "noRequireConfirm": "Não exige confirmação para continuar",
  "optionText": "Opção do usuário para desativar a tela de abertura na inicialização do aplicativo.",
  "confirmLabel": "Textos de confirmação: ",
  "confirmLabelColor": "Cor de textos de confirmação",
  "defaultConfirmText": "Eu concordo com os termos e condições acima",
  "confirmOption": "Sempre mostrar esta tela de abertura cada vez que o aplicativo iniciar",
  "backgroundColor": "Cor do Plano de Fundo",
  "content": "Conteúdo",
  "contentDescription": "Define o conteúdo que é exibido na tela de abertura.",
  "appearance": "Aparência",
  "appearanceDescription": "Configura a aparência da tela de abertura.",
  "size": "Tamanho",
  "width": "Largura",
  "height": "Altura",
  "custom": "Personalizar",
  "background": "Plano de Fundo",
  "colorFill": "Preenchimento de cor",
  "imageFill": "Preenchimento de imagem",
  "chooseFile": "Escolher arquivo",
  "noFileChosen": "Nenhum arquivo escolhido",
  "transparency": "Transparência",
  "sizeFill": "Preencher",
  "sizeFit": "Ajustar",
  "sizeStretch": "Estender para preencher",
  "sizeCenter": "Centralizar",
  "sizeTile": "Mosaico",
  "buttonColor": "Cor do botão",
  "buttonText": "Texto do botão",
  "buttonTextColor": "Cor de texto do botão",
  "contentAlign": "Alinhamento de conteúdo",
  "alignTop": "Superior",
  "alignMiddle": "Meio",
  "maskColor": "Cor da máscara",
  "options": "Opções",
  "optionsDescription": "Configura o comportamento da tela de abertura."
});