define({
  "sourceSetting": "Keresési forrás beállításai",
  "instruction": "Geokódoló szolgáltatások vagy vektoros rétegek hozzáadása és konfigurálása keresési forrásként. Ezek a megadott források határozzák meg, mi kereshető a keresőmezőben.",
  "add": "Keresési forrás hozzáadása",
  "addGeocoder": "Geokódoló hozzádása",
  "geocoder": "Geokódoló",
  "setLayerSource": "Rétegforrás beállítása",
  "setGeocoderURL": "Geokódoló URL-címének beállítása",
  "searchableLayer": "Vektoros réteg",
  "name": "Név",
  "countryCode": "Ország- vagy régiókód(ok)",
  "countryCodeEg": "pl. ",
  "countryCodeHint": "Ha üresen hagyja ezt az értéket, a keresés minden országra és régióra ki fog terjedni",
  "generalSetting": "Általános beállítások",
  "allPlaceholder": "Helyőrző szöveg az összes kereséséhez: ",
  "showInfoWindowOnSelect": "Felugró ablak megjelenítése a megtalált vektoros elemhez vagy helyhez",
  "showInfoWindowOnSelect2": "Felugró ablak megjelenítése a vektoros elem vagy a hely megtalálásakor.",
  "searchInCurrentMapExtent": "Csak az aktuális térképkiterjedésen belül keressen",
  "zoomScale": "Zoom-méretarány",
  "locatorUrl": "Geokódoló URL-címe",
  "locatorName": "Geokódoló neve",
  "locatorExample": "Példa",
  "locatorWarning": "A geokódoló szolgáltatás ezen verziója nem támogatott. A widget csak a 10.1 és újabb verziójú geokódoló szolgáltatást támogatja.",
  "locatorTips": "Nem érhetők el a javaslatok, mert a geokódoló szolgáltatás nem támogatja ezt a funkciót.",
  "layerSource": "Rétegforrás",
  "searchLayerTips": "Nem érhetők el a javaslatok, mert a vektoros adatszolgáltatás nem támogatja az oldalszámozást.",
  "placeholder": "Helyőrző szöveg",
  "searchFields": "Mezők keresése",
  "displayField": "Megjelenítési mező",
  "exactMatch": "Pontos találat",
  "maxSuggestions": "Javaslatok maximális száma",
  "maxResults": "Találatok maximális száma",
  "enableLocalSearch": "Helyi keresés engedélyezése",
  "minScale": "Min. méretarány",
  "minScaleHint": "Ha a térkép méretaránya nagyobb, mint ez a méretarány, akkor a helyi keresés lesz aktív",
  "radius": "Sugár",
  "radiusHint": "A térkép aktuális középpontja körül annak a területnek a sugarát határozza meg, amelyen belül megnő a geokódoló jelöltjeinek prioritása, hogy az adott helyhez legközelebb lévő jelöltek elsőbbséget élvezzenek",
  "meters": "méter",
  "setSearchFields": "Keresőmezők beállítása",
  "set": "Beállítás",
  "fieldSearchable": "kereshető",
  "fieldName": "Név",
  "fieldAlias": "Aliasnév",
  "ok": "OK",
  "cancel": "Mégse",
  "invalidUrlTip": "A(z) ${URL} URL-cím érvénytelen vagy nem érhető el."
});