define({
  "instruction": "Velg og konfigurer lag som skal vises i attributttabellen i begynnelsen.",
  "label": "Lag",
  "show": "Vis",
  "actions": "Konfigurer lagfelt",
  "field": "Felt",
  "alias": "Alias",
  "visible": "Synlig",
  "linkField": "Lenkefelt",
  "noLayers": "Ingen tilgjengelige geoobjektlag",
  "back": "Tilbake",
  "exportCSV": "Tillat eksport til CSV",
  "expand": "Utvid widget i begynnelsen",
  "filterByExtent": "Aktiver filter etter kartutstrekning som standard",
  "restore": "Gjenopprett til standardverdi",
  "ok": "OK",
  "cancel": "Avbryt",
  "includePoint": "Inkluder punktkoordinater i filen som eksporteres",
  "configureLayerFields": "Konfigurer felter for lagene",
  "result": "Lagring vellykket",
  "warning": "Velg Vis-alternativet først.",
  "fieldCheckWarning": "Du må velge minst ett felt.",
  "unsupportQueryWarning": "Laget må støtte spørringsoperasjoner for å kunne vises i attributtabell-widget. Sørg for at spørringsfunksjonen i tjenesten er slått på.",
  "unsupportQueryLayers": "Følgende lag må støtte spørringsfunksjonen for å vises i Attributtabell-widget. Kontroller at spørringsfunksjonen er tjenesten er aktivert.",
  "fieldName": "Navn",
  "fieldAlias": "Alias",
  "fieldVisibility": "Synlighet",
  "fieldActions": "Handlinger",
  "showAttachments": "Vis vedlegg"
});