define({
  "id": "ID",
  "state": "預設情況下，該坐標將顯示在目前地圖的坐標系。要取得其他坐標系的坐標，必須新增這些坐標系並指定相應變換。",
  "outputUnit": "輸出單位",
  "wkid": "輸出 WKID",
  "label": "輸出坐標系統名稱",
  "transformationWkid": "變換 WKID",
  "transformationLabel": "變換標籤",
  "transformForward": "正向轉換",
  "actions": "操作",
  "warning": "請輸入有效的空間參考 WKID!",
  "tfWarning": "請輸入有效的基準面轉換 WKID!",
  "spinnerLabel": "將坐標四捨五入為： ",
  "decimalPlace": "個小數位",
  "separator": "顯示千分位符號",
  "getVersionError": "無法取得幾何服務的版本",
  "add": "新增輸出座標系統",
  "edit": "編輯座標系統",
  "output": "輸出座標系統",
  "cName": "座標系統名稱",
  "units": "顯示單位: ",
  "datum": "基準面轉換",
  "tName": "轉換名稱",
  "tWKIDPlaceHolder": "轉換的 WKID",
  "forward": "使用正向轉換",
  "ok": "確定",
  "cancel": "取消",
  "olderVersion": "幾何服務不支援轉換操作",
  "REPEATING_ERROR": " 輸出清單中存在坐標系統。",
  "Default": "預設",
  "Inches": "英吋",
  "Foot": "英呎",
  "Yards": "碼",
  "Miles": "英里",
  "Nautical_Miles": "海浬",
  "Millimeters": "公釐",
  "Centimeters": "公分",
  "Meter": "公尺",
  "Kilometers": "公里",
  "Decimeters": "公寸",
  "Decimal_Degrees": "十進制度",
  "Degrees_Decimal_Minutes": "度十進制分",
  "Degree_Minutes_Seconds": "度分秒",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "座標顯示順序:",
  "lonLatTips": "經度 / 緯度(X, Y)",
  "latLonTips": "緯度 / 經度(Y, X)"
});