define({
  "id": "ID",
  "state": "Koordinaterne vises som standard i det aktuelle korts koordinatsystem. Hvis du vil have koordinaterne vist i andre koordinatsystemer, skal du tilføje dem og angive passende transformationer.",
  "outputUnit": "Outputenhed",
  "wkid": "Output-WKID",
  "label": "Navn på output-koordinatsystem",
  "transformationWkid": "Transformations-WKID",
  "transformationLabel": "Transformationsetiket",
  "transformForward": "Transformér fremad",
  "actions": "Handlinger",
  "warning": "Angiv et gyldigt geografisk reference-WKID!",
  "tfWarning": "Angiv et gyldigt WKID for datotransformation!",
  "spinnerLabel": "Afrund koordinater til: ",
  "decimalPlace": "decimalpladser",
  "separator": "Vis tusindseparatorer",
  "getVersionError": "Kan ikke hente versionen af geometritjeneste",
  "add": "Tilføj output-koordinatsystem",
  "edit": "Redigér koordinatsystem",
  "output": "Koordinatsystem for output",
  "cName": "Koordinatsystemets navn",
  "units": "Visningsenheder: ",
  "datum": "Datumtransformation",
  "tName": "Transformationsnavn",
  "tWKIDPlaceHolder": "WKID for transformationen",
  "forward": "Brug transformation fremad",
  "ok": "OK",
  "cancel": "Annuller",
  "olderVersion": "Geometritjenesten understøtter ikke transformationshandlingen",
  "REPEATING_ERROR": " Koordinatsystemet findes på output-listen.",
  "Default": "Standard",
  "Inches": "Inches",
  "Foot": "Fod",
  "Yards": "Yards",
  "Miles": "Miles",
  "Nautical_Miles": "Sømil",
  "Millimeters": "Millimeter",
  "Centimeters": "Centimeter",
  "Meter": "Meter",
  "Kilometers": "Kilometer",
  "Decimeters": "Decimeter",
  "Decimal_Degrees": "Decimalgrader",
  "Degrees_Decimal_Minutes": "Grader Decimal Minutter",
  "Degree_Minutes_Seconds": "Grader Minutter Sekunder",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Visningsrækkefølge for koordinater:",
  "lonLatTips": "Længdegrader/Breddegrader (X, Y)",
  "latLonTips": "Breddegrader/Længdegrader (Y, X)"
});