define({
  "sourceSetting": "搜尋來源設定",
  "instruction": "新增並配置地理編碼服務或圖徵圖層為搜尋來源。這些指定的來源決定了搜尋方塊中的可搜尋內容。",
  "add": "新增搜尋來源",
  "addGeocoder": "新增地理編碼器",
  "geocoder": "地理編碼器",
  "setLayerSource": "設定圖層來源",
  "setGeocoderURL": "設定地理編碼器 URL",
  "searchableLayer": "圖徵圖層",
  "name": "名稱",
  "countryCode": "國碼或地區代碼",
  "countryCodeEg": "例如 ",
  "countryCodeHint": "留空此值會搜尋所有國家和地區",
  "generalSetting": "一般設定",
  "allPlaceholder": "用於全部搜尋的占位符文字: ",
  "showInfoWindowOnSelect": "顯示發現的圖徵或位置的快顯視窗",
  "searchInCurrentMapExtent": "僅在目前的地圖範圍中搜尋",
  "zoomScale": "縮放比例",
  "locatorUrl": "地理編碼器 URL",
  "locatorName": "地理編碼器名稱",
  "locatorExample": "範例",
  "locatorWarning": "不支援此版本的地理編碼服務。該 widget支援 10.1 及更高版本的地理編碼服務。",
  "locatorTips": "由於地理編碼服務不支援建議功能，因此建議無法使用。",
  "layerSource": "圖層來源",
  "searchLayerTips": "由於圖徵服務不支援分頁功能，因此建議無法使用。",
  "placeholder": "佔位符文字",
  "searchFields": "搜尋欄位",
  "displayField": "顯示欄位",
  "exactMatch": "完全符合",
  "maxSuggestions": "最大建議數",
  "maxResults": "最大結果數",
  "enableLocalSearch": "啟用本機搜尋",
  "minScale": "最小比例",
  "minScaleHint": "當地圖比例大於此比例時，將套用本機搜尋",
  "radius": "半徑",
  "radiusHint": "指定目前地圖中心周圍的區域半徑，可用來提升地理編碼候選者的等級，以優先傳回離位置最近的候選者",
  "meters": "公尺",
  "setSearchFields": "設定搜尋欄位",
  "set": "設定",
  "fieldSearchable": "可搜尋",
  "fieldName": "名稱",
  "fieldAlias": "別名",
  "ok": "確定",
  "cancel": "取消",
  "invalidUrlTip": "URL ${URL} 無效或不可存取。"
});