define(
   ({
    _widgetLabel: "Таблица атрибутов",
    ok: "OK",
    cancel: "Отмена",
    unsupportQueryWarning: "Для отображения в виджете Атрибутивная таблица слой должен поддерживать операции запросов. Убедитесь, что функция запросов в сервисе включена.",
    exportMessage: "Экспорт данных в CSV-файл?",
    exportFiles: "Экспорт в CSV",
    exportSelected: "Экспорт выборки в CSV",
    exportAll: "Экспортировать все в CSV",
    options: "Опции",
    zoomto: "Приблизить к",
    highlight: "Выделить графику",
    selectAll: "Выбрать записи на всех страницах",
    selectPage: "Выбрать записи на текущей странице",
    clearSelection: "Очистить выборку",
    filter: "Фильтр",
    setFilterTip: "Задайте корректный фильтр.",
    noFilterTip: "Если не задано выражение для фильтра, этот запрос перечислит все объекты указанного источника данных.",
    filterByExtent: "Фильтр по экстенту карты",
    showSelectedRecords: "Показать выбранные записи",
    showAllRecords: "Показать все записи",
    showRelatedRecords: "Показать связанные записи",
    noRelatedRecords: "Нет связанных записей",
    refresh: "Обновить",
    features: "объекты",
    selected: "выбрано",
    transparent: "Прозрачный режим",
    indicate: "Найти выборку",
    columns: "Показать/Скрыть столбцы",
    selectionSymbol: "Символ выборки",
    closeMessage: "Скрыть таблицу (развернуть - снизу)",
    dataNotAvailable: "Данные не доступны!<br>Нажмите кнопку [Обновить], чтобы попробовать снова",
    openTableTip: "Открыть таблицу атрибутов",
    closeTableTip: "Скрыть таблицу атрибутов"
  })
);