define({
  "sourceSetting": "Thiết lập nguồn tìm kiếm",
  "instruction": "Thêm và cấu hình dịch vụ mã hóa địa lý hoặc lớp đối tượng như mã nguồn. Các nguồn đặc thù này xác định yếu tố nào có thể tìm kiếm được trong hộp tìm kiếm.",
  "add": "Thêm nguồn tìm kiếm",
  "addGeocoder": "Thêm bộ mã địa lý",
  "geocoder": "Trình mã hóa địa lý",
  "setLayerSource": "Thiết lập nguồn lớp",
  "setGeocoderURL": "Thiết lập URL trình mã hóa địa lý",
  "searchableLayer": "Lớp đối tượng",
  "name": "Tên",
  "countryCode": "Mã quốc gia hoặc khu vực",
  "countryCodeEg": "ví dụ ",
  "countryCodeHint": "Để trống giá trị này sẽ tìm kiếm tất cả các quốc gia và khu vực",
  "generalSetting": "Thiết lập tổng quan",
  "allPlaceholder": "Văn bản giữ chỗ để tìm kiếm tất cả: ",
  "showInfoWindowOnSelect": "Hiển thị cửa sổ pop-up cho vị trí hoặc đối tượng được tìm thấy",
  "searchInCurrentMapExtent": "Chỉ tìm kiếm trong kích thước bản đồ hiện tại",
  "zoomScale": "Tỷ lệ thu phóng",
  "locatorUrl": "URL Bộ mã địa lý",
  "locatorName": "Tên bộ mã địa lý",
  "locatorExample": "Ví dụ",
  "locatorWarning": "Phiên bản dịch vụ mã hóa địa lý này không được hỗ trợ. Tiện ích này hỗ trợ dịch vụ mã hóa địa lý 10.1 trở lên.",
  "locatorTips": "Các gợi ý không khả dụng do dịch vụ mã hóa địa lý không hỗ trợ khả năng gợi ý.",
  "layerSource": "Nguồn lớp",
  "searchLayerTips": "Các gợi ý không khả dụng do dịch vụ mã hóa địa lý không hỗ trợ khả năng phân trang.",
  "placeholder": "Văn bản trình giữ chỗ",
  "searchFields": "Tìm kiếm trường",
  "displayField": "Hiển thị trường",
  "exactMatch": "Kết quả khớp chính xác",
  "maxSuggestions": "Số đề xuất tối đa",
  "maxResults": "Kết quả tối đa",
  "enableLocalSearch": "Bật tính năng tìm kiếm nội bộ",
  "minScale": "Tỷ lệ tối thiểu",
  "minScaleHint": "Khi tỷ lệ bản đồ lớn hơn tỷ lệ này, tìm kiếm cục bộ sẽ được áp dụng",
  "radius": "Bán kính",
  "radiusHint": "Xác định bán kính của một khu vực xung quanh trung tâm bản đồ hiện tại sẽ làm tăng thứ hạng của các đối tượng mã hóa địa lý, giúp các đối tượng ở gần nhất với vị trí được trả về đầu tiên nhất",
  "meters": "Mét",
  "setSearchFields": "Thiết lập trường tìm kiếm",
  "set": "Thiết lập",
  "fieldSearchable": "có thể tìm kiếm",
  "fieldName": "Tên",
  "fieldAlias": "Bí danh",
  "ok": "OK",
  "cancel": "Hủy",
  "invalidUrlTip": "URL ${URL} không hợp lệ hoặc không thể truy cập được."
});