define(
   ({
    "sourceSetting": "Thiết lập Nguồn Tìm kiếm",
    "instruction": "Thêm và cấu hình dịch vụ mã hóa địa lý hoặc lớp đối tượng như mã nguồn. Các nguồn đặc thù này xác định yếu tố nào có thể tìm kiếm được trong hộp tìm kiếm.",
    "add": "Thêm Nguồn Tìm kiếm",
    "addGeocoder": "Thêm Bộ mã địa lý",
    "geocoder": "Trình mã hóa địa lý",
    "setLayerSource": "Thiết lập Nguồn Lớp",
    "setGeocoderURL": "Thiết lập URL Trình mã hóa địa lý",
    "searchableLayer": "Lớp đối tượng",
    "name": "Tên",
    "countryCode": "Mã Quốc gia hoặc Khu vực",
    "countryCodeEg": "ví dụ ",
    "countryCodeHint": "Để trống giá trị này sẽ tìm kiếm tất cả các quốc gia và khu vực",
    "generalSetting": "Thiết lập Tổng quan",
    "allPlaceholder": "Văn bản giữ chỗ để tìm kiếm tất cả: ",
    "showInfoWindowOnSelect": "Hiển thị cửa sổ pop-up cho vị trí hoặc đối tượng được tìm thấy",
    "searchInCurrentMapExtent": "Chỉ tìm kiếm trong kích thước bản đồ hiện tại",
    "locatorUrl": "URL Bộ mã địa lý",
    "locatorName": "Tên Bộ mã địa lý",
    "locatorExample": "Ví dụ",
    "locatorWarning": "Phiên bản dịch vụ mã hóa địa lý này không được hỗ trợ. Tiện ích này hỗ trợ dịch vụ mã hóa địa lý 00.0 trở lên.",
    "locatorTips": "Các gợi ý không khả dụng do dịch vụ mã hóa địa lý không hỗ trợ khả năng gợi ý.",
    "layerSource": "Nguồn Lớp",
    "searchLayerTips": "Các gợi ý không khả dụng do dịch vụ mã hóa địa lý không hỗ trợ khả năng phân trang.",
    "placeholder": "Văn bản trình giữ chỗ",
    "searchFields": "Trường Tìm kiếm",
    "displayField": "Hiển thị Trường",
    "exactMatch": "Kết quả khớp Chính xác",
    "maxResults": "Kết quả Tối đa",
    "setSearchFields": "Thiết lập Trường Tìm kiếm",
    "set": "Thiết lập",
    "fieldSearchable": "có thể tìm kiếm",
    "fieldName": "Tên",
    "fieldAlias": "Bí danh",
    "ok": "OK",
    "cancel": "Hủy",
    "invalidUrlTip": "URL bạn vừa nhập không hợp lệ hoặc không thể truy cập được."
  })
);