define({
  "instruction": "Uygulama erişilebilir olmadan önce başlangıç ekranı görüntülenir.",
  "defaultContent": "Buraya metin, bağlantılar ve küçük grafikler ekleyin.",
  "requireConfirm": "Devam etmek için onay gerekiyor",
  "noRequireConfirm": "Devam etmek için onay gerekmesin",
  "optionText": "Kullanıcının uygulama başlatılırken açılış ekranını devre dışı bırakma seçeneği.",
  "confirmLabel": "Onay Metinleri: ",
  "confirmLabelColor": "Onaylama metni rengi",
  "defaultConfirmText": "Yukarıdaki şartları ve koşulları kabul ediyorum",
  "confirmOption": "Uygulama başlatılırken her zaman için bu açılış ekranını göster",
  "backgroundColor": "Arkaplan Rengi",
  "content": "İçerik",
  "contentDescription": "Başlangıç ekranında görüntülenen içeriği tanımlayın.",
  "appearance": "Görünüm",
  "appearanceDescription": "Başlangıç ekranının görüntüsünü ayarlayın.",
  "size": "Boyut",
  "width": "Genişlik",
  "height": "Yükseklik",
  "custom": "Özel",
  "background": "Arkaplan",
  "colorFill": "Renk dolgusu",
  "imageFill": "Görüntü dolgusu",
  "chooseFile": "Dosya seç",
  "noFileChosen": "Seçili dosya yok",
  "transparency": "Şeffaflık",
  "sizeFill": "Dolgu",
  "sizeFit": "Uydur",
  "sizeStretch": "Doldurmak için uzat",
  "sizeCenter": "Merkez",
  "sizeTile": "Sıra",
  "buttonColor": "Düğme rengi",
  "buttonText": "Düğme metni",
  "buttonTextColor": "Düğme metni rengi",
  "contentAlign": "İçerik hizalama",
  "alignTop": "En Üst",
  "alignMiddle": "Orta",
  "maskColor": "Maske rengi",
  "options": "Seçenekler",
  "optionsDescription": "Başlangıç ekranı davranışını ayarlayın."
});