define({
  "_widgetLabel": "Koordinat",
  "hintMessage": "Klik på kortet for at hente koordinater",
  "defaultLabel": "Standard",
  "realtimeLabel": "Flyt musen for at få koordinaterne",
  "computing": "Behandler...",
  "latitudeLabel": "Breddegrad",
  "longitudeLabel": "Længdegrad",
  "loading": "indlæser...",
  "enableClick": "Klik for at aktivere klik på kortet for at få koordinater",
  "disableClick": "Klik for at deaktivere klik på kortet for at få koordinater",
  "Default": "Standard",
  "Inches": "Inches",
  "Foot": "Fod",
  "Yards": "Yards",
  "Miles": "Miles",
  "Nautical_Miles": "Sømil",
  "Millimeters": "Millimeter",
  "Centimeters": "Centimeter",
  "Meter": "Meter",
  "Kilometers": "Kilometer",
  "Decimeters": "Decimeter",
  "Decimal_Degrees": "Grader",
  "Degree_Minutes_Seconds": "Grader Minutter Sekunder",
  "MGRS": "MGRS",
  "USNG": "USNG"
});