define({
  "id": "ID",
  "state": "Privzeto se bodo koordinate prikazovale v trenutnem koordinatnem sistemu karte. Za pridobitev koordinat v drugih koordinatnih sistemih jih morate dodati in določiti ustrezne transformacije.",
  "outputUnit": "Izhodna enota",
  "wkid": "Izhodni WKID",
  "label": "Ime izhodnega koordinatnega sistema",
  "transformationWkid": "Transformacijski WKID",
  "transformationLabel": "Transformacijski napis",
  "transformForward": "Transformiraj naprej",
  "actions": "Dejanja",
  "warning": "Vnesi veljaven koordinatni sistem WKID!",
  "tfWarning": "Vnesi veljavno transformacijo geodetskega datuma WKID!",
  "spinnerLabel": "Zaokroži koordinate na: ",
  "decimalPlace": "decimalna mesta",
  "separator": "Prikaži ločilo tisočic",
  "getVersionError": "Ni mogoče pridobiti različice geometrijske storitve",
  "add": "Dodaj izhodni koordinatni sistem",
  "edit": "Uredi koordinatni sistem",
  "output": "Izhodni koordinatni sistem",
  "cName": "Ime koordinatnega sistema",
  "units": "Prikaži enote: ",
  "datum": "Transformacija geodetskega datuma",
  "tName": "Ime transformacije",
  "tWKIDPlaceHolder": "WKID transformacije",
  "forward": "Uporabi posredovanje transformacije",
  "ok": "V redu",
  "cancel": "Prekliči",
  "olderVersion": "Geometrijska storitev ne podpira operacije transformacije",
  "REPEATING_ERROR": " Na izhodnem seznamu obstaja koordinacijski sistem.",
  "Default": "Privzeto",
  "Inches": "Palci",
  "Foot": "Čevlji",
  "Yards": "Jardi",
  "Miles": "Milje",
  "Nautical_Miles": "Morske milje",
  "Millimeters": "Milimetri",
  "Centimeters": "Centimetri",
  "Meter": "Metri",
  "Kilometers": "Kilometri",
  "Decimeters": "Decimetri",
  "Decimal_Degrees": "Decimalne stopinje",
  "Degrees_Decimal_Minutes": "Stopinje decimalne minute",
  "Degree_Minutes_Seconds": "Stopinje minute sekunde",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Vrstni red prikaza koordinat:",
  "lonLatTips": "Geografska dolžina/širina (X, Y)",
  "latLonTips": "Geografska širina/dolžina (Y, X)"
});