define({
  "_widgetLabel": "Coordenar",
  "hintMessage": "Clique no mapa para obter coordenada",
  "defaultLabel": "Padrão",
  "realtimeLabel": "Mova o rato para obter coordenadas",
  "computing": "processando...",
  "latitudeLabel": "Latitude",
  "longitudeLabel": "Longitude",
  "loading": "a carregar...",
  "enableClick": "Clique para ativar a obtenção de coordenadas ao clicar no mapa",
  "disableClick": "Clique para desativar a obtenção de coordenadas ao clicar no mapa",
  "Default": "Padrão",
  "Inches": "Polegadas",
  "Foot": "Pés",
  "Yards": "Jardas",
  "Miles": "Milhas",
  "Nautical_Miles": "Milhas Náuticas",
  "Millimeters": "Milímetros",
  "Centimeters": "Centímetros",
  "Meter": "Metros",
  "Kilometers": "Quilômetros",
  "Decimeters": "Decímetros",
  "Decimal_Degrees": "Graus",
  "Degree_Minutes_Seconds": "Graus minutos segundos",
  "MGRS": "MGRS",
  "USNG": "USNG"
});