define({
  "instruction": "Seleccioneu i configureu les capes que es mostraran inicialment a la taula d'atributs.",
  "label": "Capa",
  "show": "Mostra",
  "actions": "Configura els camps de capa",
  "field": "Camp",
  "alias": "Àlies",
  "url": "URL",
  "sortField": "Ordena el camp",
  "sortOrderTooltips": {
    "toDescending": "Canvia a ordre descendent",
    "toAscending": "Canvia a ordre ascendent"
  },
  "visible": "Visible",
  "linkField": "Camp d'enllaç",
  "noLayers": "No hi ha cap capa d'entitats disponible",
  "back": "Enrere",
  "exportCSV": "Permet l'exportació a CSV",
  "expand": "Expandeix el widget inicialment",
  "filterByExtent": "Habilita Filtra per extensió de mapa per defecte",
  "allowTextSelection": "Permet la selecció de text",
  "highlightColor": "Ressalta el color",
  "restore": "Restaura al valor per defecte",
  "ok": "D'acord",
  "cancel": "Cancel·la",
  "includePoint": "Inclou les coordenades de punt al fitxer exportat",
  "configureLayerFields": "Configura els camps de capa",
  "result": "S'ha desat correctament",
  "warning": "Selecciona primer l'opció Mostra.",
  "fieldCheckWarning": "Hi ha d'haver un camp seleccionat com a mínim.",
  "unsupportQueryWarning": "La capa ha d'admetre l'operació de consulta per mostrar-se al widget Taula d'atributs. Assegureu-vos que la funció de consulta del servei estigui activada.",
  "unsupportQueryLayers": "La capa següent ha d'admetre l'operació de consulta per mostrar-se al widget Taula d'atributs. Assegureu-vos que la funció de consulta del servei estigui activada.",
  "fieldName": "Nom",
  "fieldAlias": "Àlies",
  "fieldVisibility": "Visibilitat",
  "fieldActions": "Accions",
  "showAttachments": "Mostra els fitxers adjunts"
});