define({
  "instruction": "Pilih dan konfigurasikan layer yang akan ditampilkan di Tabel Atribut awalnya.",
  "label": "Layer",
  "show": "Tampilkan",
  "actions": "Konfigurasikan kolom layer",
  "field": "Kolom",
  "alias": "Alias",
  "visible": "Terlihat",
  "linkField": "Kolom tautan",
  "noLayers": "Tidak ada layer fitur yang tersedia",
  "back": "Kembali",
  "exportCSV": "Izinkan mengekspor ke CSV",
  "expand": "Perbesar widget sebagai langkah pertama",
  "filterByExtent": "Aktifkan Filter menurut luas peta secara default",
  "restore": "Pulihkan ke nilai default",
  "ok": "Ya",
  "cancel": "Batal",
  "includePoint": "Sertakan kordinat titik ke file yang diekspor",
  "configureLayerFields": "Konfigurasikan Kolom Layer",
  "result": "Berhasil disimpan",
  "warning": "Harap pilih opsi Tampilkan terlebih dahulu.",
  "fieldCheckWarning": "Paling sedikit satu kolom harus dipilih.",
  "unsupportQueryWarning": "Layer harus mendukung operasi query untuk menampilkannya di widget Tabel Atribut. Pastikan kapabilitas query di layanan aktif.",
  "unsupportQueryLayers": "Layer berikut harus mendukung operasi query untuk menampilkan di widget Tabel Atribut. Pastikan kapabilitas query di layanan aktif.",
  "fieldName": "Nama",
  "fieldAlias": "Alias",
  "fieldVisibility": "Visibilitas",
  "fieldActions": "Tindakan",
  "showAttachments": "Tampilkan lampiran"
});