<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0" xmlns:esri="http://www.esri.com/metadata/" xmlns:res="http://www.esri.com/metadata/res/" >

<!-- An XSLT template for displaying metadata in ArcGIS. These XSLT templates display the official ISO 639 language name in place of a language code.

     Copyright (c) 2009-2010, Environmental Systems Research Institute, Inc. All rights reserved.
	
     Revision History: Created 6/8/2009 avienneau
	 still won't work outsid ArcGIS because res: lookups are internal to ArcGIS environment 
	 the res: namespace doesn't do anything, so just return the original code...
	 Slick solution would be to conjure up an anchor from the 2 or 3 letter code
	 to the SIL page for the code using links like
	 http://www-01.sil.org/iso639-3/documentation.asp?id=gre
-->

	<xsl:output method="xml" indent="yes"/>
	<xsl:template name="lang639_2letter">
		<xsl:param name="code"/>
<!--		<xsl:variable name="smallcase" select="'abcdefghijklmnopqrstuvwxyz'" />
		<xsl:variable name="uppercase" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZ'" />
		<xsl:variable name="lcCode">
			<xsl:value-of select="translate($code, $smallcase, $uppercase)" />
		</xsl:variable>
		<xsl:choose>
			<xsl:when test="($lcCode = 'aa')"><res:idLanguageName_AAR/></xsl:when>
			<xsl:when test="($lcCode = 'ab')"><res:idLanguageName_ABK/></xsl:when>
			<xsl:when test="($lcCode = 'af')"><res:idLanguageName_AFR/></xsl:when>
			<xsl:when test="($lcCode = 'ak')"><res:idLanguageName_AKA/></xsl:when>
			<xsl:when test="($lcCode = 'sq')"><res:idLanguageName_ALB/></xsl:when>
			<xsl:when test="($lcCode = 'am')"><res:idLanguageName_AMH/></xsl:when>
			<xsl:when test="($lcCode = 'ar')"><res:idLanguageName_ARA/></xsl:when>
			<xsl:when test="($lcCode = 'an')"><res:idLanguageName_ARG/></xsl:when>
			<xsl:when test="($lcCode = 'hy')"><res:idLanguageName_ARM/></xsl:when>
			<xsl:when test="($lcCode = 'as')"><res:idLanguageName_ASM/></xsl:when>
			<xsl:when test="($lcCode = 'av')"><res:idLanguageName_AVA/></xsl:when>
			<xsl:when test="($lcCode = 'ae')"><res:idLanguageName_AVE/></xsl:when>
			<xsl:when test="($lcCode = 'ay')"><res:idLanguageName_AYM/></xsl:when>
			<xsl:when test="($lcCode = 'az')"><res:idLanguageName_AZE/></xsl:when>
			<xsl:when test="($lcCode = 'ba')"><res:idLanguageName_BAK/></xsl:when>
			<xsl:when test="($lcCode = 'bm')"><res:idLanguageName_BAM/></xsl:when>
			<xsl:when test="($lcCode = 'eu')"><res:idLanguageName_BAQ/></xsl:when>
			<xsl:when test="($lcCode = 'be')"><res:idLanguageName_BEL/></xsl:when>
			<xsl:when test="($lcCode = 'bn')"><res:idLanguageName_BEN/></xsl:when>
			<xsl:when test="($lcCode = 'bh')"><res:idLanguageName_BIH/></xsl:when>
			<xsl:when test="($lcCode = 'bi')"><res:idLanguageName_BIS/></xsl:when>
			<xsl:when test="($lcCode = 'bs')"><res:idLanguageName_BOS/></xsl:when>
			<xsl:when test="($lcCode = 'br')"><res:idLanguageName_BRE/></xsl:when>
			<xsl:when test="($lcCode = 'bg')"><res:idLanguageName_BUL/></xsl:when>
			<xsl:when test="($lcCode = 'my')"><res:idLanguageName_BUR/></xsl:when>
			<xsl:when test="($lcCode = 'ca')"><res:idLanguageName_CAT/></xsl:when>
			<xsl:when test="($lcCode = 'ch')"><res:idLanguageName_CHA/></xsl:when>
			<xsl:when test="($lcCode = 'ce')"><res:idLanguageName_CHE/></xsl:when>
			<xsl:when test="($lcCode = 'zh')"><res:idLanguageName_CHI/></xsl:when>
			<xsl:when test="($lcCode = 'cu')"><res:idLanguageName_CHU/></xsl:when>
			<xsl:when test="($lcCode = 'cv')"><res:idLanguageName_CHV/></xsl:when>
			<xsl:when test="($lcCode = 'kw')"><res:idLanguageName_COR/></xsl:when>
			<xsl:when test="($lcCode = 'co')"><res:idLanguageName_COS/></xsl:when>
			<xsl:when test="($lcCode = 'cr')"><res:idLanguageName_CRE/></xsl:when>
			<xsl:when test="($lcCode = 'cs')"><res:idLanguageName_CZE/></xsl:when>
			<xsl:when test="($lcCode = 'da')"><res:idLanguageName_DAN/></xsl:when>
			<xsl:when test="($lcCode = 'dv')"><res:idLanguageName_DIV/></xsl:when>
			<xsl:when test="($lcCode = 'nl')"><res:idLanguageName_DUT/></xsl:when>
			<xsl:when test="($lcCode = 'dz')"><res:idLanguageName_DZO/></xsl:when>
			<xsl:when test="($lcCode = 'en')"><res:idLanguageName_ENG/></xsl:when>
			<xsl:when test="($lcCode = 'eo')"><res:idLanguageName_EPO/></xsl:when>
			<xsl:when test="($lcCode = 'et')"><res:idLanguageName_EST/></xsl:when>
			<xsl:when test="($lcCode = 'ee')"><res:idLanguageName_EWE/></xsl:when>
			<xsl:when test="($lcCode = 'fo')"><res:idLanguageName_FAO/></xsl:when>
			<xsl:when test="($lcCode = 'fj')"><res:idLanguageName_FIJ/></xsl:when>
			<xsl:when test="($lcCode = 'fi')"><res:idLanguageName_FIN/></xsl:when>
			<xsl:when test="($lcCode = 'fr')"><res:idLanguageName_FRE/></xsl:when>
			<xsl:when test="($lcCode = 'fy')"><res:idLanguageName_FRY/></xsl:when>
			<xsl:when test="($lcCode = 'ff')"><res:idLanguageName_FUL/></xsl:when>
			<xsl:when test="($lcCode = 'ka')"><res:idLanguageName_GEO/></xsl:when>
			<xsl:when test="($lcCode = 'de')"><res:idLanguageName_GER/></xsl:when>
			<xsl:when test="($lcCode = 'gd')"><res:idLanguageName_GLA/></xsl:when>
			<xsl:when test="($lcCode = 'ga')"><res:idLanguageName_GLE/></xsl:when>
			<xsl:when test="($lcCode = 'gl')"><res:idLanguageName_GLG/></xsl:when>
			<xsl:when test="($lcCode = 'gv')"><res:idLanguageName_GLV/></xsl:when>
			<xsl:when test="($lcCode = 'el')"><res:idLanguageName_GRE/></xsl:when>
			<xsl:when test="($lcCode = 'gn')"><res:idLanguageName_GRN/></xsl:when>
			<xsl:when test="($lcCode = 'gu')"><res:idLanguageName_GUJ/></xsl:when>
			<xsl:when test="($lcCode = 'ht')"><res:idLanguageName_HAT/></xsl:when>
			<xsl:when test="($lcCode = 'ha')"><res:idLanguageName_HAU/></xsl:when>
			<xsl:when test="($lcCode = 'he')"><res:idLanguageName_HEB/></xsl:when>
			<xsl:when test="($lcCode = 'hz')"><res:idLanguageName_HER/></xsl:when>
			<xsl:when test="($lcCode = 'hi')"><res:idLanguageName_HIN/></xsl:when>
			<xsl:when test="($lcCode = 'ho')"><res:idLanguageName_HMO/></xsl:when>
			<xsl:when test="($lcCode = 'hr')"><res:idLanguageName_HRV/></xsl:when>
			<xsl:when test="($lcCode = 'hu')"><res:idLanguageName_HUN/></xsl:when>
			<xsl:when test="($lcCode = 'ig')"><res:idLanguageName_IBO/></xsl:when>
			<xsl:when test="($lcCode = 'is')"><res:idLanguageName_ICE/></xsl:when>
			<xsl:when test="($lcCode = 'io')"><res:idLanguageName_IDO/></xsl:when>
			<xsl:when test="($lcCode = 'ii')"><res:idLanguageName_III/></xsl:when>
			<xsl:when test="($lcCode = 'iu')"><res:idLanguageName_IKU/></xsl:when>
			<xsl:when test="($lcCode = 'ie')"><res:idLanguageName_ILE/></xsl:when>
			<xsl:when test="($lcCode = 'ia')"><res:idLanguageName_INA/></xsl:when>
			<xsl:when test="($lcCode = 'id')"><res:idLanguageName_IND/></xsl:when>
			<xsl:when test="($lcCode = 'ik')"><res:idLanguageName_IPK/></xsl:when>
			<xsl:when test="($lcCode = 'it')"><res:idLanguageName_ITA/></xsl:when>
			<xsl:when test="($lcCode = 'jv')"><res:idLanguageName_JAV/></xsl:when>
			<xsl:when test="($lcCode = 'ja')"><res:idLanguageName_JPN/></xsl:when>
			<xsl:when test="($lcCode = 'kl')"><res:idLanguageName_KAL/></xsl:when>
			<xsl:when test="($lcCode = 'kn')"><res:idLanguageName_KAN/></xsl:when>
			<xsl:when test="($lcCode = 'ks')"><res:idLanguageName_KAS/></xsl:when>
			<xsl:when test="($lcCode = 'kr')"><res:idLanguageName_KAU/></xsl:when>
			<xsl:when test="($lcCode = 'kk')"><res:idLanguageName_KAZ/></xsl:when>
			<xsl:when test="($lcCode = 'km')"><res:idLanguageName_KHM/></xsl:when>
			<xsl:when test="($lcCode = 'ki')"><res:idLanguageName_KIK/></xsl:when>
			<xsl:when test="($lcCode = 'rw')"><res:idLanguageName_KIN/></xsl:when>
			<xsl:when test="($lcCode = 'ky')"><res:idLanguageName_KIR/></xsl:when>
			<xsl:when test="($lcCode = 'kv')"><res:idLanguageName_KOM/></xsl:when>
			<xsl:when test="($lcCode = 'kg')"><res:idLanguageName_KON/></xsl:when>
			<xsl:when test="($lcCode = 'ko')"><res:idLanguageName_KOR/></xsl:when>
			<xsl:when test="($lcCode = 'kj')"><res:idLanguageName_KUA/></xsl:when>
			<xsl:when test="($lcCode = 'ku')"><res:idLanguageName_KUR/></xsl:when>
			<xsl:when test="($lcCode = 'lo')"><res:idLanguageName_LAO/></xsl:when>
			<xsl:when test="($lcCode = 'la')"><res:idLanguageName_LAT/></xsl:when>
			<xsl:when test="($lcCode = 'lv')"><res:idLanguageName_LAV/></xsl:when>
			<xsl:when test="($lcCode = 'li')"><res:idLanguageName_LIM/></xsl:when>
			<xsl:when test="($lcCode = 'ln')"><res:idLanguageName_LIN/></xsl:when>
			<xsl:when test="($lcCode = 'lt')"><res:idLanguageName_LIT/></xsl:when>
			<xsl:when test="($lcCode = 'lb')"><res:idLanguageName_LTZ/></xsl:when>
			<xsl:when test="($lcCode = 'lu')"><res:idLanguageName_LUB/></xsl:when>
			<xsl:when test="($lcCode = 'lg')"><res:idLanguageName_LUG/></xsl:when>
			<xsl:when test="($lcCode = 'mk')"><res:idLanguageName_MAC/></xsl:when>
			<xsl:when test="($lcCode = 'mh')"><res:idLanguageName_MAH/></xsl:when>
			<xsl:when test="($lcCode = 'ml')"><res:idLanguageName_MAL/></xsl:when>
			<xsl:when test="($lcCode = 'mi')"><res:idLanguageName_MAO/></xsl:when>
			<xsl:when test="($lcCode = 'mr')"><res:idLanguageName_MAR/></xsl:when>
			<xsl:when test="($lcCode = 'ms')"><res:idLanguageName_MAY/></xsl:when>
			<xsl:when test="($lcCode = 'mg')"><res:idLanguageName_MLG/></xsl:when>
			<xsl:when test="($lcCode = 'mt')"><res:idLanguageName_MLT/></xsl:when>
			<xsl:when test="($lcCode = 'mn')"><res:idLanguageName_MON/></xsl:when>
			<xsl:when test="($lcCode = 'na')"><res:idLanguageName_NAU/></xsl:when>
			<xsl:when test="($lcCode = 'nv')"><res:idLanguageName_NAV/></xsl:when>
			<xsl:when test="($lcCode = 'nr')"><res:idLanguageName_NBL/></xsl:when>
			<xsl:when test="($lcCode = 'nd')"><res:idLanguageName_NDE/></xsl:when>
			<xsl:when test="($lcCode = 'ng')"><res:idLanguageName_NDO/></xsl:when>
			<xsl:when test="($lcCode = 'ne')"><res:idLanguageName_NEP/></xsl:when>
			<xsl:when test="($lcCode = 'nn')"><res:idLanguageName_NNO/></xsl:when>
			<xsl:when test="($lcCode = 'nb')"><res:idLanguageName_NOB/></xsl:when>
			<xsl:when test="($lcCode = 'no')"><res:idLanguageName_NOR/></xsl:when>
			<xsl:when test="($lcCode = 'ny')"><res:idLanguageName_NYA/></xsl:when>
			<xsl:when test="($lcCode = 'oc')"><res:idLanguageName_OCI/></xsl:when>
			<xsl:when test="($lcCode = 'oj')"><res:idLanguageName_OJI/></xsl:when>
			<xsl:when test="($lcCode = 'or')"><res:idLanguageName_ORI/></xsl:when>
			<xsl:when test="($lcCode = 'om')"><res:idLanguageName_ORM/></xsl:when>
			<xsl:when test="($lcCode = 'os')"><res:idLanguageName_OSS/></xsl:when>
			<xsl:when test="($lcCode = 'pa')"><res:idLanguageName_PAN/></xsl:when>
			<xsl:when test="($lcCode = 'fa')"><res:idLanguageName_PER/></xsl:when>
			<xsl:when test="($lcCode = 'pi')"><res:idLanguageName_PLI/></xsl:when>
			<xsl:when test="($lcCode = 'pl')"><res:idLanguageName_POL/></xsl:when>
			<xsl:when test="($lcCode = 'pt')"><res:idLanguageName_POR/></xsl:when>
			<xsl:when test="($lcCode = 'ps')"><res:idLanguageName_PUS/></xsl:when>
			<xsl:when test="($lcCode = 'qu')"><res:idLanguageName_QUE/></xsl:when>
			<xsl:when test="($lcCode = 'rm')"><res:idLanguageName_ROH/></xsl:when>
			<xsl:when test="($lcCode = 'ro')"><res:idLanguageName_RUM/></xsl:when>
			<xsl:when test="($lcCode = 'rn')"><res:idLanguageName_RUN/></xsl:when>
			<xsl:when test="($lcCode = 'ru')"><res:idLanguageName_RUS/></xsl:when>
			<xsl:when test="($lcCode = 'sg')"><res:idLanguageName_SAG/></xsl:when>
			<xsl:when test="($lcCode = 'sa')"><res:idLanguageName_SAN/></xsl:when>
			<xsl:when test="($lcCode = 'si')"><res:idLanguageName_SIN/></xsl:when>
			<xsl:when test="($lcCode = 'sk')"><res:idLanguageName_SLO/></xsl:when>
			<xsl:when test="($lcCode = 'sl')"><res:idLanguageName_SLV/></xsl:when>
			<xsl:when test="($lcCode = 'se')"><res:idLanguageName_SME/></xsl:when>
			<xsl:when test="($lcCode = 'sm')"><res:idLanguageName_SMO/></xsl:when>
			<xsl:when test="($lcCode = 'sn')"><res:idLanguageName_SNA/></xsl:when>
			<xsl:when test="($lcCode = 'sd')"><res:idLanguageName_SND/></xsl:when>
			<xsl:when test="($lcCode = 'so')"><res:idLanguageName_SOM/></xsl:when>
			<xsl:when test="($lcCode = 'st')"><res:idLanguageName_SOT/></xsl:when>
			<xsl:when test="($lcCode = 'es')"><res:idLanguageName_SPA/></xsl:when>
			<xsl:when test="($lcCode = 'sc')"><res:idLanguageName_SRD/></xsl:when>
			<xsl:when test="($lcCode = 'sr')"><res:idLanguageName_SRP/></xsl:when>
			<xsl:when test="($lcCode = 'ss')"><res:idLanguageName_SSW/></xsl:when>
			<xsl:when test="($lcCode = 'su')"><res:idLanguageName_SUN/></xsl:when>
			<xsl:when test="($lcCode = 'sw')"><res:idLanguageName_SWA/></xsl:when>
			<xsl:when test="($lcCode = 'sv')"><res:idLanguageName_SWE/></xsl:when>
			<xsl:when test="($lcCode = 'ty')"><res:idLanguageName_TAH/></xsl:when>
			<xsl:when test="($lcCode = 'ta')"><res:idLanguageName_TAM/></xsl:when>
			<xsl:when test="($lcCode = 'tt')"><res:idLanguageName_TAT/></xsl:when>
			<xsl:when test="($lcCode = 'te')"><res:idLanguageName_TEL/></xsl:when>
			<xsl:when test="($lcCode = 'tg')"><res:idLanguageName_TGK/></xsl:when>
			<xsl:when test="($lcCode = 'tl')"><res:idLanguageName_TGL/></xsl:when>
			<xsl:when test="($lcCode = 'th')"><res:idLanguageName_THA/></xsl:when>
			<xsl:when test="($lcCode = 'bo')"><res:idLanguageName_TIB/></xsl:when>
			<xsl:when test="($lcCode = 'ti')"><res:idLanguageName_TIR/></xsl:when>
			<xsl:when test="($lcCode = 'to')"><res:idLanguageName_TON/></xsl:when>
			<xsl:when test="($lcCode = 'tn')"><res:idLanguageName_TSN/></xsl:when>
			<xsl:when test="($lcCode = 'ts')"><res:idLanguageName_TSO/></xsl:when>
			<xsl:when test="($lcCode = 'tk')"><res:idLanguageName_TUK/></xsl:when>
			<xsl:when test="($lcCode = 'tr')"><res:idLanguageName_TUR/></xsl:when>
			<xsl:when test="($lcCode = 'tw')"><res:idLanguageName_TWI/></xsl:when>
			<xsl:when test="($lcCode = 'ug')"><res:idLanguageName_UIG/></xsl:when>
			<xsl:when test="($lcCode = 'uk')"><res:idLanguageName_UKR/></xsl:when>
			<xsl:when test="($lcCode = 'ur')"><res:idLanguageName_URD/></xsl:when>
			<xsl:when test="($lcCode = 'uz')"><res:idLanguageName_UZB/></xsl:when>
			<xsl:when test="($lcCode = 've')"><res:idLanguageName_VEN/></xsl:when>
			<xsl:when test="($lcCode = 'vi')"><res:idLanguageName_VIE/></xsl:when>
			<xsl:when test="($lcCode = 'vo')"><res:idLanguageName_VOL/></xsl:when>
			<xsl:when test="($lcCode = 'cy')"><res:idLanguageName_WEL/></xsl:when>
			<xsl:when test="($lcCode = 'wa')"><res:idLanguageName_WLN/></xsl:when>
			<xsl:when test="($lcCode = 'wo')"><res:idLanguageName_WOL/></xsl:when>
			<xsl:when test="($lcCode = 'xh')"><res:idLanguageName_XHO/></xsl:when>
			<xsl:when test="($lcCode = 'yi')"><res:idLanguageName_YID/></xsl:when>
			<xsl:when test="($lcCode = 'yo')"><res:idLanguageName_YOR/></xsl:when>
			<xsl:when test="($lcCode = 'za')"><res:idLanguageName_ZHA/></xsl:when>
			<xsl:when test="($lcCode = 'zu')"><res:idLanguageName_ZUL/></xsl:when>
			<xsl:otherwise>-->
				<xsl:value-of select="."/>
<!--			</xsl:otherwise>
		</xsl:choose>-->
	</xsl:template>
	<xsl:template name="lang639_3letter">
		<xsl:param name="code"/>
<!--just return the original code for now, so comment this out.
			
			<xsl:variable name="smallcase" select="'abcdefghijklmnopqrstuvwxyz'" />
		<xsl:variable name="uppercase" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZ'" />
		<xsl:variable name="lcCode">
			<xsl:value-of select="translate($code, $smallcase, $uppercase)" />
		</xsl:variable>
		<xsl:choose>
			<xsl:when test="($lcCode = 'aar')"><res:idLanguageName_AAR/></xsl:when>
			<xsl:when test="($lcCode = 'abk')"><res:idLanguageName_ABK/></xsl:when>
			<xsl:when test="($lcCode = 'ace')"><res:idLanguageName_ACE/></xsl:when>
			<xsl:when test="($lcCode = 'ach')"><res:idLanguageName_ACH/></xsl:when>
			<xsl:when test="($lcCode = 'ada')"><res:idLanguageName_ADA/></xsl:when>
			<xsl:when test="($lcCode = 'ady')"><res:idLanguageName_ADY/></xsl:when>
			<xsl:when test="($lcCode = 'afa')"><res:idLanguageName_AFA/></xsl:when>
			<xsl:when test="($lcCode = 'afh')"><res:idLanguageName_AFH/></xsl:when>
			<xsl:when test="($lcCode = 'afr')"><res:idLanguageName_AFR/></xsl:when>
			<xsl:when test="($lcCode = 'ain')"><res:idLanguageName_AIN/></xsl:when>
			<xsl:when test="($lcCode = 'aka')"><res:idLanguageName_AKA/></xsl:when>
			<xsl:when test="($lcCode = 'akk')"><res:idLanguageName_AKK/></xsl:when>
			<xsl:when test="($lcCode = 'alb')"><res:idLanguageName_ALB/></xsl:when>
			<xsl:when test="($lcCode = 'sqi')"><res:idLanguageName_SQI/></xsl:when>
			<xsl:when test="($lcCode = 'ale')"><res:idLanguageName_ALE/></xsl:when>
			<xsl:when test="($lcCode = 'alg')"><res:idLanguageName_ALG/></xsl:when>
			<xsl:when test="($lcCode = 'alt')"><res:idLanguageName_ALT/></xsl:when>
			<xsl:when test="($lcCode = 'amh')"><res:idLanguageName_AMH/></xsl:when>
			<xsl:when test="($lcCode = 'ang')"><res:idLanguageName_ANG/></xsl:when>
			<xsl:when test="($lcCode = 'anp')"><res:idLanguageName_ANP/></xsl:when>
			<xsl:when test="($lcCode = 'apa')"><res:idLanguageName_APA/></xsl:when>
			<xsl:when test="($lcCode = 'ara')"><res:idLanguageName_ARA/></xsl:when>
			<xsl:when test="($lcCode = 'arc')"><res:idLanguageName_ARC/></xsl:when>
			<xsl:when test="($lcCode = 'arg')"><res:idLanguageName_ARG/></xsl:when>
			<xsl:when test="($lcCode = 'arm')"><res:idLanguageName_ARM/></xsl:when>
			<xsl:when test="($lcCode = 'hye')"><res:idLanguageName_HYE/></xsl:when>
			<xsl:when test="($lcCode = 'arn')"><res:idLanguageName_ARN/></xsl:when>
			<xsl:when test="($lcCode = 'arp')"><res:idLanguageName_ARP/></xsl:when>
			<xsl:when test="($lcCode = 'art')"><res:idLanguageName_ART/></xsl:when>
			<xsl:when test="($lcCode = 'arw')"><res:idLanguageName_ARW/></xsl:when>
			<xsl:when test="($lcCode = 'asm')"><res:idLanguageName_ASM/></xsl:when>
			<xsl:when test="($lcCode = 'ast')"><res:idLanguageName_AST/></xsl:when>
			<xsl:when test="($lcCode = 'ath')"><res:idLanguageName_ATH/></xsl:when>
			<xsl:when test="($lcCode = 'aus')"><res:idLanguageName_AUS/></xsl:when>
			<xsl:when test="($lcCode = 'ava')"><res:idLanguageName_AVA/></xsl:when>
			<xsl:when test="($lcCode = 'ave')"><res:idLanguageName_AVE/></xsl:when>
			<xsl:when test="($lcCode = 'awa')"><res:idLanguageName_AWA/></xsl:when>
			<xsl:when test="($lcCode = 'aym')"><res:idLanguageName_AYM/></xsl:when>
			<xsl:when test="($lcCode = 'aze')"><res:idLanguageName_AZE/></xsl:when>
			<xsl:when test="($lcCode = 'bad')"><res:idLanguageName_BAD/></xsl:when>
			<xsl:when test="($lcCode = 'bai')"><res:idLanguageName_BAI/></xsl:when>
			<xsl:when test="($lcCode = 'bak')"><res:idLanguageName_BAK/></xsl:when>
			<xsl:when test="($lcCode = 'bal')"><res:idLanguageName_BAL/></xsl:when>
			<xsl:when test="($lcCode = 'bam')"><res:idLanguageName_BAM/></xsl:when>
			<xsl:when test="($lcCode = 'ban')"><res:idLanguageName_BAN/></xsl:when>
			<xsl:when test="($lcCode = 'baq')"><res:idLanguageName_BAQ/></xsl:when>
			<xsl:when test="($lcCode = 'eus')"><res:idLanguageName_EUS/></xsl:when>
			<xsl:when test="($lcCode = 'bas')"><res:idLanguageName_BAS/></xsl:when>
			<xsl:when test="($lcCode = 'bat')"><res:idLanguageName_BAT/></xsl:when>
			<xsl:when test="($lcCode = 'bej')"><res:idLanguageName_BEJ/></xsl:when>
			<xsl:when test="($lcCode = 'bel')"><res:idLanguageName_BEL/></xsl:when>
			<xsl:when test="($lcCode = 'bem')"><res:idLanguageName_BEM/></xsl:when>
			<xsl:when test="($lcCode = 'ben')"><res:idLanguageName_BEN/></xsl:when>
			<xsl:when test="($lcCode = 'ber')"><res:idLanguageName_BER/></xsl:when>
			<xsl:when test="($lcCode = 'bho')"><res:idLanguageName_BHO/></xsl:when>
			<xsl:when test="($lcCode = 'bih')"><res:idLanguageName_BIH/></xsl:when>
			<xsl:when test="($lcCode = 'bik')"><res:idLanguageName_BIK/></xsl:when>
			<xsl:when test="($lcCode = 'bin')"><res:idLanguageName_BIN/></xsl:when>
			<xsl:when test="($lcCode = 'bis')"><res:idLanguageName_BIS/></xsl:when>
			<xsl:when test="($lcCode = 'bla')"><res:idLanguageName_BLA/></xsl:when>
			<xsl:when test="($lcCode = 'bnt')"><res:idLanguageName_BNT/></xsl:when>
			<xsl:when test="($lcCode = 'bos')"><res:idLanguageName_BOS/></xsl:when>
			<xsl:when test="($lcCode = 'bra')"><res:idLanguageName_BRA/></xsl:when>
			<xsl:when test="($lcCode = 'bre')"><res:idLanguageName_BRE/></xsl:when>
			<xsl:when test="($lcCode = 'btk')"><res:idLanguageName_BTK/></xsl:when>
			<xsl:when test="($lcCode = 'bua')"><res:idLanguageName_BUA/></xsl:when>
			<xsl:when test="($lcCode = 'bug')"><res:idLanguageName_BUG/></xsl:when>
			<xsl:when test="($lcCode = 'bul')"><res:idLanguageName_BUL/></xsl:when>
			<xsl:when test="($lcCode = 'bur')"><res:idLanguageName_BUR/></xsl:when>
			<xsl:when test="($lcCode = 'mya')"><res:idLanguageName_MYA/></xsl:when>
			<xsl:when test="($lcCode = 'byn')"><res:idLanguageName_BYN/></xsl:when>
			<xsl:when test="($lcCode = 'cad')"><res:idLanguageName_CAD/></xsl:when>
			<xsl:when test="($lcCode = 'cai')"><res:idLanguageName_CAI/></xsl:when>
			<xsl:when test="($lcCode = 'car')"><res:idLanguageName_CAR/></xsl:when>
			<xsl:when test="($lcCode = 'cat')"><res:idLanguageName_CAT/></xsl:when>
			<xsl:when test="($lcCode = 'cau')"><res:idLanguageName_CAU/></xsl:when>
			<xsl:when test="($lcCode = 'ceb')"><res:idLanguageName_CEB/></xsl:when>
			<xsl:when test="($lcCode = 'cel')"><res:idLanguageName_CEL/></xsl:when>
			<xsl:when test="($lcCode = 'cha')"><res:idLanguageName_CHA/></xsl:when>
			<xsl:when test="($lcCode = 'chb')"><res:idLanguageName_CHB/></xsl:when>
			<xsl:when test="($lcCode = 'che')"><res:idLanguageName_CHE/></xsl:when>
			<xsl:when test="($lcCode = 'chg')"><res:idLanguageName_CHG/></xsl:when>
			<xsl:when test="($lcCode = 'chi')"><res:idLanguageName_CHI/></xsl:when>
			<xsl:when test="($lcCode = 'zho')"><res:idLanguageName_ZHO/></xsl:when>
			<xsl:when test="($lcCode = 'chk')"><res:idLanguageName_CHK/></xsl:when>
			<xsl:when test="($lcCode = 'chm')"><res:idLanguageName_CHM/></xsl:when>
			<xsl:when test="($lcCode = 'chn')"><res:idLanguageName_CHN/></xsl:when>
			<xsl:when test="($lcCode = 'cho')"><res:idLanguageName_CHO/></xsl:when>
			<xsl:when test="($lcCode = 'chp')"><res:idLanguageName_CHP/></xsl:when>
			<xsl:when test="($lcCode = 'chr')"><res:idLanguageName_CHR/></xsl:when>
			<xsl:when test="($lcCode = 'chu')"><res:idLanguageName_CHU/></xsl:when>
			<xsl:when test="($lcCode = 'chv')"><res:idLanguageName_CHV/></xsl:when>
			<xsl:when test="($lcCode = 'chy')"><res:idLanguageName_CHY/></xsl:when>
			<xsl:when test="($lcCode = 'cmc')"><res:idLanguageName_CMC/></xsl:when>
			<xsl:when test="($lcCode = 'cop')"><res:idLanguageName_COP/></xsl:when>
			<xsl:when test="($lcCode = 'cor')"><res:idLanguageName_COR/></xsl:when>
			<xsl:when test="($lcCode = 'cos')"><res:idLanguageName_COS/></xsl:when>
			<xsl:when test="($lcCode = 'cpe')"><res:idLanguageName_CPE/></xsl:when>
			<xsl:when test="($lcCode = 'cpf')"><res:idLanguageName_CPF/></xsl:when>
			<xsl:when test="($lcCode = 'cpp')"><res:idLanguageName_CPP/></xsl:when>
			<xsl:when test="($lcCode = 'cre')"><res:idLanguageName_CRE/></xsl:when>
			<xsl:when test="($lcCode = 'crh')"><res:idLanguageName_CRH/></xsl:when>
			<xsl:when test="($lcCode = 'crp')"><res:idLanguageName_CRP/></xsl:when>
			<xsl:when test="($lcCode = 'csb')"><res:idLanguageName_CSB/></xsl:when>
			<xsl:when test="($lcCode = 'cus')"><res:idLanguageName_CUS/></xsl:when>
			<xsl:when test="($lcCode = 'cze')"><res:idLanguageName_CZE/></xsl:when>
			<xsl:when test="($lcCode = 'ces')"><res:idLanguageName_CES/></xsl:when>
			<xsl:when test="($lcCode = 'dak')"><res:idLanguageName_DAK/></xsl:when>
			<xsl:when test="($lcCode = 'dan')"><res:idLanguageName_DAN/></xsl:when>
			<xsl:when test="($lcCode = 'dar')"><res:idLanguageName_DAR/></xsl:when>
			<xsl:when test="($lcCode = 'day')"><res:idLanguageName_DAY/></xsl:when>
			<xsl:when test="($lcCode = 'del')"><res:idLanguageName_DEL/></xsl:when>
			<xsl:when test="($lcCode = 'den')"><res:idLanguageName_DEN/></xsl:when>
			<xsl:when test="($lcCode = 'dgr')"><res:idLanguageName_DGR/></xsl:when>
			<xsl:when test="($lcCode = 'din')"><res:idLanguageName_DIN/></xsl:when>
			<xsl:when test="($lcCode = 'div')"><res:idLanguageName_DIV/></xsl:when>
			<xsl:when test="($lcCode = 'doi')"><res:idLanguageName_DOI/></xsl:when>
			<xsl:when test="($lcCode = 'dra')"><res:idLanguageName_DRA/></xsl:when>
			<xsl:when test="($lcCode = 'dsb')"><res:idLanguageName_DSB/></xsl:when>
			<xsl:when test="($lcCode = 'dua')"><res:idLanguageName_DUA/></xsl:when>
			<xsl:when test="($lcCode = 'dum')"><res:idLanguageName_DUM/></xsl:when>
			<xsl:when test="($lcCode = 'dut')"><res:idLanguageName_DUT/></xsl:when>
			<xsl:when test="($lcCode = 'nld')"><res:idLanguageName_NLD/></xsl:when>
			<xsl:when test="($lcCode = 'dyu')"><res:idLanguageName_DYU/></xsl:when>
			<xsl:when test="($lcCode = 'dzo')"><res:idLanguageName_DZO/></xsl:when>
			<xsl:when test="($lcCode = 'efi')"><res:idLanguageName_EFI/></xsl:when>
			<xsl:when test="($lcCode = 'egy')"><res:idLanguageName_EGY/></xsl:when>
			<xsl:when test="($lcCode = 'eka')"><res:idLanguageName_EKA/></xsl:when>
			<xsl:when test="($lcCode = 'elx')"><res:idLanguageName_ELX/></xsl:when>
			<xsl:when test="($lcCode = 'eng')"><res:idLanguageName_ENG/></xsl:when>
			<xsl:when test="($lcCode = 'enm')"><res:idLanguageName_ENM/></xsl:when>
			<xsl:when test="($lcCode = 'epo')"><res:idLanguageName_EPO/></xsl:when>
			<xsl:when test="($lcCode = 'est')"><res:idLanguageName_EST/></xsl:when>
			<xsl:when test="($lcCode = 'ewe')"><res:idLanguageName_EWE/></xsl:when>
			<xsl:when test="($lcCode = 'ewo')"><res:idLanguageName_EWO/></xsl:when>
			<xsl:when test="($lcCode = 'fan')"><res:idLanguageName_FAN/></xsl:when>
			<xsl:when test="($lcCode = 'fao')"><res:idLanguageName_FAO/></xsl:when>
			<xsl:when test="($lcCode = 'fat')"><res:idLanguageName_FAT/></xsl:when>
			<xsl:when test="($lcCode = 'fij')"><res:idLanguageName_FIJ/></xsl:when>
			<xsl:when test="($lcCode = 'fil')"><res:idLanguageName_FIL/></xsl:when>
			<xsl:when test="($lcCode = 'fin')"><res:idLanguageName_FIN/></xsl:when>
			<xsl:when test="($lcCode = 'fiu')"><res:idLanguageName_FIU/></xsl:when>
			<xsl:when test="($lcCode = 'fon')"><res:idLanguageName_FON/></xsl:when>
			<xsl:when test="($lcCode = 'fre')"><res:idLanguageName_FRE/></xsl:when>
			<xsl:when test="($lcCode = 'fra')"><res:idLanguageName_FRA/></xsl:when>
			<xsl:when test="($lcCode = 'frm')"><res:idLanguageName_FRM/></xsl:when>
			<xsl:when test="($lcCode = 'fro')"><res:idLanguageName_FRO/></xsl:when>
			<xsl:when test="($lcCode = 'frr')"><res:idLanguageName_FRR/></xsl:when>
			<xsl:when test="($lcCode = 'frs')"><res:idLanguageName_FRS/></xsl:when>
			<xsl:when test="($lcCode = 'fry')"><res:idLanguageName_FRY/></xsl:when>
			<xsl:when test="($lcCode = 'ful')"><res:idLanguageName_FUL/></xsl:when>
			<xsl:when test="($lcCode = 'fur')"><res:idLanguageName_FUR/></xsl:when>
			<xsl:when test="($lcCode = 'gaa')"><res:idLanguageName_GAA/></xsl:when>
			<xsl:when test="($lcCode = 'gay')"><res:idLanguageName_GAY/></xsl:when>
			<xsl:when test="($lcCode = 'gba')"><res:idLanguageName_GBA/></xsl:when>
			<xsl:when test="($lcCode = 'gem')"><res:idLanguageName_GEM/></xsl:when>
			<xsl:when test="($lcCode = 'geo')"><res:idLanguageName_GEO/></xsl:when>
			<xsl:when test="($lcCode = 'kat')"><res:idLanguageName_KAT/></xsl:when>
			<xsl:when test="($lcCode = 'ger')"><res:idLanguageName_GER/></xsl:when>
			<xsl:when test="($lcCode = 'deu')"><res:idLanguageName_DEU/></xsl:when>
			<xsl:when test="($lcCode = 'gez')"><res:idLanguageName_GEZ/></xsl:when>
			<xsl:when test="($lcCode = 'gil')"><res:idLanguageName_GIL/></xsl:when>
			<xsl:when test="($lcCode = 'gla')"><res:idLanguageName_GLA/></xsl:when>
			<xsl:when test="($lcCode = 'gle')"><res:idLanguageName_GLE/></xsl:when>
			<xsl:when test="($lcCode = 'glg')"><res:idLanguageName_GLG/></xsl:when>
			<xsl:when test="($lcCode = 'glv')"><res:idLanguageName_GLV/></xsl:when>
			<xsl:when test="($lcCode = 'gmh')"><res:idLanguageName_GMH/></xsl:when>
			<xsl:when test="($lcCode = 'goh')"><res:idLanguageName_GOH/></xsl:when>
			<xsl:when test="($lcCode = 'gon')"><res:idLanguageName_GON/></xsl:when>
			<xsl:when test="($lcCode = 'gor')"><res:idLanguageName_GOR/></xsl:when>
			<xsl:when test="($lcCode = 'got')"><res:idLanguageName_GOT/></xsl:when>
			<xsl:when test="($lcCode = 'grb')"><res:idLanguageName_GRB/></xsl:when>
			<xsl:when test="($lcCode = 'grc')"><res:idLanguageName_GRC/></xsl:when>
			<xsl:when test="($lcCode = 'gre')"><res:idLanguageName_GRE/></xsl:when>
			<xsl:when test="($lcCode = 'ell')"><res:idLanguageName_ELL/></xsl:when>
			<xsl:when test="($lcCode = 'grn')"><res:idLanguageName_GRN/></xsl:when>
			<xsl:when test="($lcCode = 'gsw')"><res:idLanguageName_GSW/></xsl:when>
			<xsl:when test="($lcCode = 'guj')"><res:idLanguageName_GUJ/></xsl:when>
			<xsl:when test="($lcCode = 'gwi')"><res:idLanguageName_GWI/></xsl:when>
			<xsl:when test="($lcCode = 'hai')"><res:idLanguageName_HAI/></xsl:when>
			<xsl:when test="($lcCode = 'hat')"><res:idLanguageName_HAT/></xsl:when>
			<xsl:when test="($lcCode = 'hau')"><res:idLanguageName_HAU/></xsl:when>
			<xsl:when test="($lcCode = 'haw')"><res:idLanguageName_HAW/></xsl:when>
			<xsl:when test="($lcCode = 'heb')"><res:idLanguageName_HEB/></xsl:when>
			<xsl:when test="($lcCode = 'her')"><res:idLanguageName_HER/></xsl:when>
			<xsl:when test="($lcCode = 'hil')"><res:idLanguageName_HIL/></xsl:when>
			<xsl:when test="($lcCode = 'him')"><res:idLanguageName_HIM/></xsl:when>
			<xsl:when test="($lcCode = 'hin')"><res:idLanguageName_HIN/></xsl:when>
			<xsl:when test="($lcCode = 'hit')"><res:idLanguageName_HIT/></xsl:when>
			<xsl:when test="($lcCode = 'hmn')"><res:idLanguageName_HMN/></xsl:when>
			<xsl:when test="($lcCode = 'hmo')"><res:idLanguageName_HMO/></xsl:when>
			<xsl:when test="($lcCode = 'hrv')"><res:idLanguageName_HRV/></xsl:when>
			<xsl:when test="($lcCode = 'hsb')"><res:idLanguageName_HSB/></xsl:when>
			<xsl:when test="($lcCode = 'hun')"><res:idLanguageName_HUN/></xsl:when>
			<xsl:when test="($lcCode = 'hup')"><res:idLanguageName_HUP/></xsl:when>
			<xsl:when test="($lcCode = 'iba')"><res:idLanguageName_IBA/></xsl:when>
			<xsl:when test="($lcCode = 'ibo')"><res:idLanguageName_IBO/></xsl:when>
			<xsl:when test="($lcCode = 'ice')"><res:idLanguageName_ICE/></xsl:when>
			<xsl:when test="($lcCode = 'isl')"><res:idLanguageName_ISL/></xsl:when>
			<xsl:when test="($lcCode = 'ido')"><res:idLanguageName_IDO/></xsl:when>
			<xsl:when test="($lcCode = 'iii')"><res:idLanguageName_III/></xsl:when>
			<xsl:when test="($lcCode = 'ijo')"><res:idLanguageName_IJO/></xsl:when>
			<xsl:when test="($lcCode = 'iku')"><res:idLanguageName_IKU/></xsl:when>
			<xsl:when test="($lcCode = 'ile')"><res:idLanguageName_ILE/></xsl:when>
			<xsl:when test="($lcCode = 'ilo')"><res:idLanguageName_ILO/></xsl:when>
			<xsl:when test="($lcCode = 'ina')"><res:idLanguageName_INA/></xsl:when>
			<xsl:when test="($lcCode = 'inc')"><res:idLanguageName_INC/></xsl:when>
			<xsl:when test="($lcCode = 'ind')"><res:idLanguageName_IND/></xsl:when>
			<xsl:when test="($lcCode = 'ine')"><res:idLanguageName_INE/></xsl:when>
			<xsl:when test="($lcCode = 'inh')"><res:idLanguageName_INH/></xsl:when>
			<xsl:when test="($lcCode = 'ipk')"><res:idLanguageName_IPK/></xsl:when>
			<xsl:when test="($lcCode = 'ira')"><res:idLanguageName_IRA/></xsl:when>
			<xsl:when test="($lcCode = 'iro')"><res:idLanguageName_IRO/></xsl:when>
			<xsl:when test="($lcCode = 'ita')"><res:idLanguageName_ITA/></xsl:when>
			<xsl:when test="($lcCode = 'jav')"><res:idLanguageName_JAV/></xsl:when>
			<xsl:when test="($lcCode = 'jbo')"><res:idLanguageName_JBO/></xsl:when>
			<xsl:when test="($lcCode = 'jpn')"><res:idLanguageName_JPN/></xsl:when>
			<xsl:when test="($lcCode = 'jpr')"><res:idLanguageName_JPR/></xsl:when>
			<xsl:when test="($lcCode = 'jrb')"><res:idLanguageName_JRB/></xsl:when>
			<xsl:when test="($lcCode = 'kaa')"><res:idLanguageName_KAA/></xsl:when>
			<xsl:when test="($lcCode = 'kab')"><res:idLanguageName_KAB/></xsl:when>
			<xsl:when test="($lcCode = 'kac')"><res:idLanguageName_KAC/></xsl:when>
			<xsl:when test="($lcCode = 'kal')"><res:idLanguageName_KAL/></xsl:when>
			<xsl:when test="($lcCode = 'kam')"><res:idLanguageName_KAM/></xsl:when>
			<xsl:when test="($lcCode = 'kan')"><res:idLanguageName_KAN/></xsl:when>
			<xsl:when test="($lcCode = 'kar')"><res:idLanguageName_KAR/></xsl:when>
			<xsl:when test="($lcCode = 'kas')"><res:idLanguageName_KAS/></xsl:when>
			<xsl:when test="($lcCode = 'kau')"><res:idLanguageName_KAU/></xsl:when>
			<xsl:when test="($lcCode = 'kaw')"><res:idLanguageName_KAW/></xsl:when>
			<xsl:when test="($lcCode = 'kaz')"><res:idLanguageName_KAZ/></xsl:when>
			<xsl:when test="($lcCode = 'kbd')"><res:idLanguageName_KBD/></xsl:when>
			<xsl:when test="($lcCode = 'kha')"><res:idLanguageName_KHA/></xsl:when>
			<xsl:when test="($lcCode = 'khi')"><res:idLanguageName_KHI/></xsl:when>
			<xsl:when test="($lcCode = 'khm')"><res:idLanguageName_KHM/></xsl:when>
			<xsl:when test="($lcCode = 'kho')"><res:idLanguageName_KHO/></xsl:when>
			<xsl:when test="($lcCode = 'kik')"><res:idLanguageName_KIK/></xsl:when>
			<xsl:when test="($lcCode = 'kin')"><res:idLanguageName_KIN/></xsl:when>
			<xsl:when test="($lcCode = 'kir')"><res:idLanguageName_KIR/></xsl:when>
			<xsl:when test="($lcCode = 'kmb')"><res:idLanguageName_KMB/></xsl:when>
			<xsl:when test="($lcCode = 'kok')"><res:idLanguageName_KOK/></xsl:when>
			<xsl:when test="($lcCode = 'kom')"><res:idLanguageName_KOM/></xsl:when>
			<xsl:when test="($lcCode = 'kon')"><res:idLanguageName_KON/></xsl:when>
			<xsl:when test="($lcCode = 'kor')"><res:idLanguageName_KOR/></xsl:when>
			<xsl:when test="($lcCode = 'kos')"><res:idLanguageName_KOS/></xsl:when>
			<xsl:when test="($lcCode = 'kpe')"><res:idLanguageName_KPE/></xsl:when>
			<xsl:when test="($lcCode = 'krc')"><res:idLanguageName_KRC/></xsl:when>
			<xsl:when test="($lcCode = 'krl')"><res:idLanguageName_KRL/></xsl:when>
			<xsl:when test="($lcCode = 'kro')"><res:idLanguageName_KRO/></xsl:when>
			<xsl:when test="($lcCode = 'kru')"><res:idLanguageName_KRU/></xsl:when>
			<xsl:when test="($lcCode = 'kua')"><res:idLanguageName_KUA/></xsl:when>
			<xsl:when test="($lcCode = 'kum')"><res:idLanguageName_KUM/></xsl:when>
			<xsl:when test="($lcCode = 'kur')"><res:idLanguageName_KUR/></xsl:when>
			<xsl:when test="($lcCode = 'kut')"><res:idLanguageName_KUT/></xsl:when>
			<xsl:when test="($lcCode = 'lad')"><res:idLanguageName_LAD/></xsl:when>
			<xsl:when test="($lcCode = 'lah')"><res:idLanguageName_LAH/></xsl:when>
			<xsl:when test="($lcCode = 'lam')"><res:idLanguageName_LAM/></xsl:when>
			<xsl:when test="($lcCode = 'lao')"><res:idLanguageName_LAO/></xsl:when>
			<xsl:when test="($lcCode = 'lat')"><res:idLanguageName_LAT/></xsl:when>
			<xsl:when test="($lcCode = 'lav')"><res:idLanguageName_LAV/></xsl:when>
			<xsl:when test="($lcCode = 'lez')"><res:idLanguageName_LEZ/></xsl:when>
			<xsl:when test="($lcCode = 'lim')"><res:idLanguageName_LIM/></xsl:when>
			<xsl:when test="($lcCode = 'lin')"><res:idLanguageName_LIN/></xsl:when>
			<xsl:when test="($lcCode = 'lit')"><res:idLanguageName_LIT/></xsl:when>
			<xsl:when test="($lcCode = 'lol')"><res:idLanguageName_LOL/></xsl:when>
			<xsl:when test="($lcCode = 'loz')"><res:idLanguageName_LOZ/></xsl:when>
			<xsl:when test="($lcCode = 'ltz')"><res:idLanguageName_LTZ/></xsl:when>
			<xsl:when test="($lcCode = 'lua')"><res:idLanguageName_LUA/></xsl:when>
			<xsl:when test="($lcCode = 'lub')"><res:idLanguageName_LUB/></xsl:when>
			<xsl:when test="($lcCode = 'lug')"><res:idLanguageName_LUG/></xsl:when>
			<xsl:when test="($lcCode = 'lui')"><res:idLanguageName_LUI/></xsl:when>
			<xsl:when test="($lcCode = 'lun')"><res:idLanguageName_LUN/></xsl:when>
			<xsl:when test="($lcCode = 'luo')"><res:idLanguageName_LUO/></xsl:when>
			<xsl:when test="($lcCode = 'lus')"><res:idLanguageName_LUS/></xsl:when>
			<xsl:when test="($lcCode = 'mac')"><res:idLanguageName_MAC/></xsl:when>
			<xsl:when test="($lcCode = 'mkd')"><res:idLanguageName_MKD/></xsl:when>
			<xsl:when test="($lcCode = 'mad')"><res:idLanguageName_MAD/></xsl:when>
			<xsl:when test="($lcCode = 'mag')"><res:idLanguageName_MAG/></xsl:when>
			<xsl:when test="($lcCode = 'mah')"><res:idLanguageName_MAH/></xsl:when>
			<xsl:when test="($lcCode = 'mai')"><res:idLanguageName_MAI/></xsl:when>
			<xsl:when test="($lcCode = 'mak')"><res:idLanguageName_MAK/></xsl:when>
			<xsl:when test="($lcCode = 'mal')"><res:idLanguageName_MAL/></xsl:when>
			<xsl:when test="($lcCode = 'man')"><res:idLanguageName_MAN/></xsl:when>
			<xsl:when test="($lcCode = 'mao')"><res:idLanguageName_MAO/></xsl:when>
			<xsl:when test="($lcCode = 'mri')"><res:idLanguageName_MRI/></xsl:when>
			<xsl:when test="($lcCode = 'map')"><res:idLanguageName_MAP/></xsl:when>
			<xsl:when test="($lcCode = 'mar')"><res:idLanguageName_MAR/></xsl:when>
			<xsl:when test="($lcCode = 'mas')"><res:idLanguageName_MAS/></xsl:when>
			<xsl:when test="($lcCode = 'may')"><res:idLanguageName_MAY/></xsl:when>
			<xsl:when test="($lcCode = 'msa')"><res:idLanguageName_MSA/></xsl:when>
			<xsl:when test="($lcCode = 'mdf')"><res:idLanguageName_MDF/></xsl:when>
			<xsl:when test="($lcCode = 'mdr')"><res:idLanguageName_MDR/></xsl:when>
			<xsl:when test="($lcCode = 'men')"><res:idLanguageName_MEN/></xsl:when>
			<xsl:when test="($lcCode = 'mga')"><res:idLanguageName_MGA/></xsl:when>
			<xsl:when test="($lcCode = 'mic')"><res:idLanguageName_MIC/></xsl:when>
			<xsl:when test="($lcCode = 'min')"><res:idLanguageName_MIN/></xsl:when>
			<xsl:when test="($lcCode = 'mis')"><res:idLanguageName_MIS/></xsl:when>
			<xsl:when test="($lcCode = 'mkh')"><res:idLanguageName_MKH/></xsl:when>
			<xsl:when test="($lcCode = 'mlg')"><res:idLanguageName_MLG/></xsl:when>
			<xsl:when test="($lcCode = 'mlt')"><res:idLanguageName_MLT/></xsl:when>
			<xsl:when test="($lcCode = 'mnc')"><res:idLanguageName_MNC/></xsl:when>
			<xsl:when test="($lcCode = 'mni')"><res:idLanguageName_MNI/></xsl:when>
			<xsl:when test="($lcCode = 'mno')"><res:idLanguageName_MNO/></xsl:when>
			<xsl:when test="($lcCode = 'moh')"><res:idLanguageName_MOH/></xsl:when>
			<xsl:when test="($lcCode = 'mon')"><res:idLanguageName_MON/></xsl:when>
			<xsl:when test="($lcCode = 'mos')"><res:idLanguageName_MOS/></xsl:when>
			<xsl:when test="($lcCode = 'mul')"><res:idLanguageName_MUL/></xsl:when>
			<xsl:when test="($lcCode = 'mun')"><res:idLanguageName_MUN/></xsl:when>
			<xsl:when test="($lcCode = 'mus')"><res:idLanguageName_MUS/></xsl:when>
			<xsl:when test="($lcCode = 'mwl')"><res:idLanguageName_MWL/></xsl:when>
			<xsl:when test="($lcCode = 'mwr')"><res:idLanguageName_MWR/></xsl:when>
			<xsl:when test="($lcCode = 'myn')"><res:idLanguageName_MYN/></xsl:when>
			<xsl:when test="($lcCode = 'myv')"><res:idLanguageName_MYV/></xsl:when>
			<xsl:when test="($lcCode = 'nah')"><res:idLanguageName_NAH/></xsl:when>
			<xsl:when test="($lcCode = 'nai')"><res:idLanguageName_NAI/></xsl:when>
			<xsl:when test="($lcCode = 'nap')"><res:idLanguageName_NAP/></xsl:when>
			<xsl:when test="($lcCode = 'nau')"><res:idLanguageName_NAU/></xsl:when>
			<xsl:when test="($lcCode = 'nav')"><res:idLanguageName_NAV/></xsl:when>
			<xsl:when test="($lcCode = 'nbl')"><res:idLanguageName_NBL/></xsl:when>
			<xsl:when test="($lcCode = 'nde')"><res:idLanguageName_NDE/></xsl:when>
			<xsl:when test="($lcCode = 'ndo')"><res:idLanguageName_NDO/></xsl:when>
			<xsl:when test="($lcCode = 'nds')"><res:idLanguageName_NDS/></xsl:when>
			<xsl:when test="($lcCode = 'nep')"><res:idLanguageName_NEP/></xsl:when>
			<xsl:when test="($lcCode = 'new')"><res:idLanguageName_NEW/></xsl:when>
			<xsl:when test="($lcCode = 'nia')"><res:idLanguageName_NIA/></xsl:when>
			<xsl:when test="($lcCode = 'nic')"><res:idLanguageName_NIC/></xsl:when>
			<xsl:when test="($lcCode = 'niu')"><res:idLanguageName_NIU/></xsl:when>
			<xsl:when test="($lcCode = 'nno')"><res:idLanguageName_NNO/></xsl:when>
			<xsl:when test="($lcCode = 'nob')"><res:idLanguageName_NOB/></xsl:when>
			<xsl:when test="($lcCode = 'nog')"><res:idLanguageName_NOG/></xsl:when>
			<xsl:when test="($lcCode = 'non')"><res:idLanguageName_NON/></xsl:when>
			<xsl:when test="($lcCode = 'nor')"><res:idLanguageName_NOR/></xsl:when>
			<xsl:when test="($lcCode = 'nqo')"><res:idLanguageName_NQO/></xsl:when>
			<xsl:when test="($lcCode = 'nso')"><res:idLanguageName_NSO/></xsl:when>
			<xsl:when test="($lcCode = 'nub')"><res:idLanguageName_NUB/></xsl:when>
			<xsl:when test="($lcCode = 'nwc')"><res:idLanguageName_NWC/></xsl:when>
			<xsl:when test="($lcCode = 'nya')"><res:idLanguageName_NYA/></xsl:when>
			<xsl:when test="($lcCode = 'nym')"><res:idLanguageName_NYM/></xsl:when>
			<xsl:when test="($lcCode = 'nyn')"><res:idLanguageName_NYN/></xsl:when>
			<xsl:when test="($lcCode = 'nyo')"><res:idLanguageName_NYO/></xsl:when>
			<xsl:when test="($lcCode = 'nzi')"><res:idLanguageName_NZI/></xsl:when>
			<xsl:when test="($lcCode = 'oci')"><res:idLanguageName_OCI/></xsl:when>
			<xsl:when test="($lcCode = 'oji')"><res:idLanguageName_OJI/></xsl:when>
			<xsl:when test="($lcCode = 'ori')"><res:idLanguageName_ORI/></xsl:when>
			<xsl:when test="($lcCode = 'orm')"><res:idLanguageName_ORM/></xsl:when>
			<xsl:when test="($lcCode = 'osa')"><res:idLanguageName_OSA/></xsl:when>
			<xsl:when test="($lcCode = 'oss')"><res:idLanguageName_OSS/></xsl:when>
			<xsl:when test="($lcCode = 'ota')"><res:idLanguageName_OTA/></xsl:when>
			<xsl:when test="($lcCode = 'oto')"><res:idLanguageName_OTO/></xsl:when>
			<xsl:when test="($lcCode = 'paa')"><res:idLanguageName_PAA/></xsl:when>
			<xsl:when test="($lcCode = 'pag')"><res:idLanguageName_PAG/></xsl:when>
			<xsl:when test="($lcCode = 'pal')"><res:idLanguageName_PAL/></xsl:when>
			<xsl:when test="($lcCode = 'pam')"><res:idLanguageName_PAM/></xsl:when>
			<xsl:when test="($lcCode = 'pan')"><res:idLanguageName_PAN/></xsl:when>
			<xsl:when test="($lcCode = 'pap')"><res:idLanguageName_PAP/></xsl:when>
			<xsl:when test="($lcCode = 'pau')"><res:idLanguageName_PAU/></xsl:when>
			<xsl:when test="($lcCode = 'peo')"><res:idLanguageName_PEO/></xsl:when>
			<xsl:when test="($lcCode = 'per')"><res:idLanguageName_PER/></xsl:when>
			<xsl:when test="($lcCode = 'fas')"><res:idLanguageName_FAS/></xsl:when>
			<xsl:when test="($lcCode = 'phi')"><res:idLanguageName_PHI/></xsl:when>
			<xsl:when test="($lcCode = 'phn')"><res:idLanguageName_PHN/></xsl:when>
			<xsl:when test="($lcCode = 'pli')"><res:idLanguageName_PLI/></xsl:when>
			<xsl:when test="($lcCode = 'pol')"><res:idLanguageName_POL/></xsl:when>
			<xsl:when test="($lcCode = 'pon')"><res:idLanguageName_PON/></xsl:when>
			<xsl:when test="($lcCode = 'por')"><res:idLanguageName_POR/></xsl:when>
			<xsl:when test="($lcCode = 'pra')"><res:idLanguageName_PRA/></xsl:when>
			<xsl:when test="($lcCode = 'pro')"><res:idLanguageName_PRO/></xsl:when>
			<xsl:when test="($lcCode = 'pus')"><res:idLanguageName_PUS/></xsl:when>
			<xsl:when test="($lcCode = 'que')"><res:idLanguageName_QUE/></xsl:when>
			<xsl:when test="($lcCode = 'raj')"><res:idLanguageName_RAJ/></xsl:when>
			<xsl:when test="($lcCode = 'rap')"><res:idLanguageName_RAP/></xsl:when>
			<xsl:when test="($lcCode = 'rar')"><res:idLanguageName_RAR/></xsl:when>
			<xsl:when test="($lcCode = 'roa')"><res:idLanguageName_ROA/></xsl:when>
			<xsl:when test="($lcCode = 'roh')"><res:idLanguageName_ROH/></xsl:when>
			<xsl:when test="($lcCode = 'rom')"><res:idLanguageName_ROM/></xsl:when>
			<xsl:when test="($lcCode = 'rum')"><res:idLanguageName_RUM/></xsl:when>
			<xsl:when test="($lcCode = 'ron')"><res:idLanguageName_RON/></xsl:when>
			<xsl:when test="($lcCode = 'run')"><res:idLanguageName_RUN/></xsl:when>
			<xsl:when test="($lcCode = 'rup')"><res:idLanguageName_RUP/></xsl:when>
			<xsl:when test="($lcCode = 'rus')"><res:idLanguageName_RUS/></xsl:when>
			<xsl:when test="($lcCode = 'sad')"><res:idLanguageName_SAD/></xsl:when>
			<xsl:when test="($lcCode = 'sag')"><res:idLanguageName_SAG/></xsl:when>
			<xsl:when test="($lcCode = 'sah')"><res:idLanguageName_SAH/></xsl:when>
			<xsl:when test="($lcCode = 'sai')"><res:idLanguageName_SAI/></xsl:when>
			<xsl:when test="($lcCode = 'sal')"><res:idLanguageName_SAL/></xsl:when>
			<xsl:when test="($lcCode = 'sam')"><res:idLanguageName_SAM/></xsl:when>
			<xsl:when test="($lcCode = 'san')"><res:idLanguageName_SAN/></xsl:when>
			<xsl:when test="($lcCode = 'sas')"><res:idLanguageName_SAS/></xsl:when>
			<xsl:when test="($lcCode = 'sat')"><res:idLanguageName_SAT/></xsl:when>
			<xsl:when test="($lcCode = 'scn')"><res:idLanguageName_SCN/></xsl:when>
			<xsl:when test="($lcCode = 'sco')"><res:idLanguageName_SCO/></xsl:when>
			<xsl:when test="($lcCode = 'sel')"><res:idLanguageName_SEL/></xsl:when>
			<xsl:when test="($lcCode = 'sem')"><res:idLanguageName_SEM/></xsl:when>
			<xsl:when test="($lcCode = 'sga')"><res:idLanguageName_SGA/></xsl:when>
			<xsl:when test="($lcCode = 'sgn')"><res:idLanguageName_SGN/></xsl:when>
			<xsl:when test="($lcCode = 'shn')"><res:idLanguageName_SHN/></xsl:when>
			<xsl:when test="($lcCode = 'sid')"><res:idLanguageName_SID/></xsl:when>
			<xsl:when test="($lcCode = 'sin')"><res:idLanguageName_SIN/></xsl:when>
			<xsl:when test="($lcCode = 'sio')"><res:idLanguageName_SIO/></xsl:when>
			<xsl:when test="($lcCode = 'sit')"><res:idLanguageName_SIT/></xsl:when>
			<xsl:when test="($lcCode = 'sla')"><res:idLanguageName_SLA/></xsl:when>
			<xsl:when test="($lcCode = 'slo')"><res:idLanguageName_SLO/></xsl:when>
			<xsl:when test="($lcCode = 'slk')"><res:idLanguageName_SLK/></xsl:when>
			<xsl:when test="($lcCode = 'slv')"><res:idLanguageName_SLV/></xsl:when>
			<xsl:when test="($lcCode = 'sma')"><res:idLanguageName_SMA/></xsl:when>
			<xsl:when test="($lcCode = 'sme')"><res:idLanguageName_SME/></xsl:when>
			<xsl:when test="($lcCode = 'smi')"><res:idLanguageName_SMI/></xsl:when>
			<xsl:when test="($lcCode = 'smj')"><res:idLanguageName_SMJ/></xsl:when>
			<xsl:when test="($lcCode = 'smn')"><res:idLanguageName_SMN/></xsl:when>
			<xsl:when test="($lcCode = 'smo')"><res:idLanguageName_SMO/></xsl:when>
			<xsl:when test="($lcCode = 'sms')"><res:idLanguageName_SMS/></xsl:when>
			<xsl:when test="($lcCode = 'sna')"><res:idLanguageName_SNA/></xsl:when>
			<xsl:when test="($lcCode = 'snd')"><res:idLanguageName_SND/></xsl:when>
			<xsl:when test="($lcCode = 'snk')"><res:idLanguageName_SNK/></xsl:when>
			<xsl:when test="($lcCode = 'sog')"><res:idLanguageName_SOG/></xsl:when>
			<xsl:when test="($lcCode = 'som')"><res:idLanguageName_SOM/></xsl:when>
			<xsl:when test="($lcCode = 'son')"><res:idLanguageName_SON/></xsl:when>
			<xsl:when test="($lcCode = 'sot')"><res:idLanguageName_SOT/></xsl:when>
			<xsl:when test="($lcCode = 'spa')"><res:idLanguageName_SPA/></xsl:when>
			<xsl:when test="($lcCode = 'srd')"><res:idLanguageName_SRD/></xsl:when>
			<xsl:when test="($lcCode = 'srn')"><res:idLanguageName_SRN/></xsl:when>
			<xsl:when test="($lcCode = 'srp')"><res:idLanguageName_SRP/></xsl:when>
			<xsl:when test="($lcCode = 'srr')"><res:idLanguageName_SRR/></xsl:when>
			<xsl:when test="($lcCode = 'ssa')"><res:idLanguageName_SSA/></xsl:when>
			<xsl:when test="($lcCode = 'ssw')"><res:idLanguageName_SSW/></xsl:when>
			<xsl:when test="($lcCode = 'suk')"><res:idLanguageName_SUK/></xsl:when>
			<xsl:when test="($lcCode = 'sun')"><res:idLanguageName_SUN/></xsl:when>
			<xsl:when test="($lcCode = 'sus')"><res:idLanguageName_SUS/></xsl:when>
			<xsl:when test="($lcCode = 'sux')"><res:idLanguageName_SUX/></xsl:when>
			<xsl:when test="($lcCode = 'swa')"><res:idLanguageName_SWA/></xsl:when>
			<xsl:when test="($lcCode = 'swe')"><res:idLanguageName_SWE/></xsl:when>
			<xsl:when test="($lcCode = 'syc')"><res:idLanguageName_SYC/></xsl:when>
			<xsl:when test="($lcCode = 'syr')"><res:idLanguageName_SYR/></xsl:when>
			<xsl:when test="($lcCode = 'tah')"><res:idLanguageName_TAH/></xsl:when>
			<xsl:when test="($lcCode = 'tai')"><res:idLanguageName_TAI/></xsl:when>
			<xsl:when test="($lcCode = 'tam')"><res:idLanguageName_TAM/></xsl:when>
			<xsl:when test="($lcCode = 'tat')"><res:idLanguageName_TAT/></xsl:when>
			<xsl:when test="($lcCode = 'tel')"><res:idLanguageName_TEL/></xsl:when>
			<xsl:when test="($lcCode = 'tem')"><res:idLanguageName_TEM/></xsl:when>
			<xsl:when test="($lcCode = 'ter')"><res:idLanguageName_TER/></xsl:when>
			<xsl:when test="($lcCode = 'tet')"><res:idLanguageName_TET/></xsl:when>
			<xsl:when test="($lcCode = 'tgk')"><res:idLanguageName_TGK/></xsl:when>
			<xsl:when test="($lcCode = 'tgl')"><res:idLanguageName_TGL/></xsl:when>
			<xsl:when test="($lcCode = 'tha')"><res:idLanguageName_THA/></xsl:when>
			<xsl:when test="($lcCode = 'tib')"><res:idLanguageName_TIB/></xsl:when>
			<xsl:when test="($lcCode = 'bod')"><res:idLanguageName_BOD/></xsl:when>
			<xsl:when test="($lcCode = 'tig')"><res:idLanguageName_TIG/></xsl:when>
			<xsl:when test="($lcCode = 'tir')"><res:idLanguageName_TIR/></xsl:when>
			<xsl:when test="($lcCode = 'tiv')"><res:idLanguageName_TIV/></xsl:when>
			<xsl:when test="($lcCode = 'tkl')"><res:idLanguageName_TKL/></xsl:when>
			<xsl:when test="($lcCode = 'tlh')"><res:idLanguageName_TLH/></xsl:when>
			<xsl:when test="($lcCode = 'tli')"><res:idLanguageName_TLI/></xsl:when>
			<xsl:when test="($lcCode = 'tmh')"><res:idLanguageName_TMH/></xsl:when>
			<xsl:when test="($lcCode = 'tog')"><res:idLanguageName_TOG/></xsl:when>
			<xsl:when test="($lcCode = 'ton')"><res:idLanguageName_TON/></xsl:when>
			<xsl:when test="($lcCode = 'tpi')"><res:idLanguageName_TPI/></xsl:when>
			<xsl:when test="($lcCode = 'tsi')"><res:idLanguageName_TSI/></xsl:when>
			<xsl:when test="($lcCode = 'tsn')"><res:idLanguageName_TSN/></xsl:when>
			<xsl:when test="($lcCode = 'tso')"><res:idLanguageName_TSO/></xsl:when>
			<xsl:when test="($lcCode = 'tuk')"><res:idLanguageName_TUK/></xsl:when>
			<xsl:when test="($lcCode = 'tum')"><res:idLanguageName_TUM/></xsl:when>
			<xsl:when test="($lcCode = 'tup')"><res:idLanguageName_TUP/></xsl:when>
			<xsl:when test="($lcCode = 'tur')"><res:idLanguageName_TUR/></xsl:when>
			<xsl:when test="($lcCode = 'tut')"><res:idLanguageName_TUT/></xsl:when>
			<xsl:when test="($lcCode = 'tvl')"><res:idLanguageName_TVL/></xsl:when>
			<xsl:when test="($lcCode = 'twi')"><res:idLanguageName_TWI/></xsl:when>
			<xsl:when test="($lcCode = 'tyv')"><res:idLanguageName_TYV/></xsl:when>
			<xsl:when test="($lcCode = 'udm')"><res:idLanguageName_UDM/></xsl:when>
			<xsl:when test="($lcCode = 'uga')"><res:idLanguageName_UGA/></xsl:when>
			<xsl:when test="($lcCode = 'uig')"><res:idLanguageName_UIG/></xsl:when>
			<xsl:when test="($lcCode = 'ukr')"><res:idLanguageName_UKR/></xsl:when>
			<xsl:when test="($lcCode = 'umb')"><res:idLanguageName_UMB/></xsl:when>
			<xsl:when test="($lcCode = 'und')"><res:idLanguageName_UND/></xsl:when>
			<xsl:when test="($lcCode = 'urd')"><res:idLanguageName_URD/></xsl:when>
			<xsl:when test="($lcCode = 'uzb')"><res:idLanguageName_UZB/></xsl:when>
			<xsl:when test="($lcCode = 'vai')"><res:idLanguageName_VAI/></xsl:when>
			<xsl:when test="($lcCode = 'ven')"><res:idLanguageName_VEN/></xsl:when>
			<xsl:when test="($lcCode = 'vie')"><res:idLanguageName_VIE/></xsl:when>
			<xsl:when test="($lcCode = 'vol')"><res:idLanguageName_VOL/></xsl:when>
			<xsl:when test="($lcCode = 'vot')"><res:idLanguageName_VOT/></xsl:when>
			<xsl:when test="($lcCode = 'wak')"><res:idLanguageName_WAK/></xsl:when>
			<xsl:when test="($lcCode = 'wal')"><res:idLanguageName_WAL/></xsl:when>
			<xsl:when test="($lcCode = 'war')"><res:idLanguageName_WAR/></xsl:when>
			<xsl:when test="($lcCode = 'was')"><res:idLanguageName_WAS/></xsl:when>
			<xsl:when test="($lcCode = 'wel')"><res:idLanguageName_WEL/></xsl:when>
			<xsl:when test="($lcCode = 'cym')"><res:idLanguageName_CYM/></xsl:when>
			<xsl:when test="($lcCode = 'wen')"><res:idLanguageName_WEN/></xsl:when>
			<xsl:when test="($lcCode = 'wln')"><res:idLanguageName_WLN/></xsl:when>
			<xsl:when test="($lcCode = 'wol')"><res:idLanguageName_WOL/></xsl:when>
			<xsl:when test="($lcCode = 'xal')"><res:idLanguageName_XAL/></xsl:when>
			<xsl:when test="($lcCode = 'xho')"><res:idLanguageName_XHO/></xsl:when>
			<xsl:when test="($lcCode = 'yao')"><res:idLanguageName_YAO/></xsl:when>
			<xsl:when test="($lcCode = 'yap')"><res:idLanguageName_YAP/></xsl:when>
			<xsl:when test="($lcCode = 'yid')"><res:idLanguageName_YID/></xsl:when>
			<xsl:when test="($lcCode = 'yor')"><res:idLanguageName_YOR/></xsl:when>
			<xsl:when test="($lcCode = 'ypk')"><res:idLanguageName_YPK/></xsl:when>
			<xsl:when test="($lcCode = 'zap')"><res:idLanguageName_ZAP/></xsl:when>
			<xsl:when test="($lcCode = 'zbl')"><res:idLanguageName_ZBL/></xsl:when>
			<xsl:when test="($lcCode = 'zen')"><res:idLanguageName_ZEN/></xsl:when>
			<xsl:when test="($lcCode = 'zha')"><res:idLanguageName_ZHA/></xsl:when>
			<xsl:when test="($lcCode = 'znd')"><res:idLanguageName_ZND/></xsl:when>
			<xsl:when test="($lcCode = 'zul')"><res:idLanguageName_ZUL/></xsl:when>
			<xsl:when test="($lcCode = 'zun')"><res:idLanguageName_ZUN/></xsl:when>
			<xsl:when test="($lcCode = 'zxx')"><res:idLanguageName_ZXX/></xsl:when>
			<xsl:when test="($lcCode = 'zza')"><res:idLanguageName_ZZA/></xsl:when>
			<xsl:otherwise>-->
				<xsl:value-of select="."/>
<!--			</xsl:otherwise>
		</xsl:choose>-->
	</xsl:template>
</xsl:stylesheet>