define(
   ({
    id: 'ID',
    state: "Domyślnie współrzędne są wyświetlane w bieżącym układzie współrzędnych mapy.  Aby uzyskać współrzędne w innych układach współrzędnych, konieczne jest ich dodanie i podanie odpowiednich transformacji.",
    outputUnit: "Jednostka danych wynikowych",
    wkid: "Identyfikator WKID wynikowych danych",
    label: "Wynikowa nazwa układu współrzędnych",
    transformationWkid: "Identyfikator (WKID) transformacji",
    transformationLabel: "Etykieta transformacji",
    transformForward: "Transfomuj dalej",
    actions: "Operacje",
    warning: "Wprowadź prawidłowy identyfikator WKID odniesienia przestrzennego!",
    tfWarning: "Wprowadź prawidłowy identyfikator WKID transformacji układu odniesienia!",
    spinnerLabel: "Zaokrąglaj współrzędne do: ",
    decimalPlace: "miejsca dziesiętne",
    separator: "Pokaż separatory tysięcy",
    getVersionError: "Nie można pobrać informacji o wersji usługi geometrii",

    add: "Dodaj wynikowy układ współrzędnych",
    edit: "Edytuj układ współrzędnych",
    output: "Wynikowy układ współrzędnych",
    cName: "Nazwa układu współrzędnych",
    units: "Wyświetl jednostki: ",
    datum: "Transformacja układu odniesienia",
    tName: "Nazwa transformacji",
    tWKIDPlaceHolder: "Identyfikator WKID transformacji",
    forward: "Użyj dalszej transformacji",
    ok: "OK",
    cancel: 'Anuluj',
    olderVersion: "Usługa geometrii nie obsługuje operacji transformacji",
    REPEATING_ERROR: " Układ współrzędnych znajduje się już na liście danych wyjściowych.",

    Default: "Domyślnie",
    Inches: "Cale",
    Foot: "Stopy",
    Yards: "Jardy",
    Miles: "Mile",
    Nautical_Miles: "Mile Morskie",
    Millimeters: "Milimetry",
    Centimeters: "Centymetry",
    Meter: "Metry",
    Kilometers: "Kilometry",
    Decimeters: "Decymetry",
    Decimal_Degrees: "Stopnie dziesiętne",
    Degree_Minutes_Seconds: "Stopnie, minuty i sekundy",
    MGRS: "MGRS",
    USNG: "USNG"
  })
);