define({
  "sourceSetting": "Søkekildeinnstillinger",
  "instruction": "Legg til og konfigurer geokodingstjenester eller geoobjektslag som søkekilder. Disse angitte kildene avgjør hva som er søkbart i søkeboksen.",
  "add": "Legg til søkekilde",
  "addGeocoder": "Legg til geokoder",
  "geocoder": "Geokoder",
  "setLayerSource": "Angi lagkilde",
  "setGeocoderURL": "Angi geokoder-URL",
  "searchableLayer": "Geoobjektslag",
  "name": "Navn",
  "countryCode": "Lands- eller regionskode(r)",
  "countryCodeEg": "f.eks. ",
  "countryCodeHint": "Hvis du lar dette feltet stå tomt, søkes det i alle land og regioner",
  "generalSetting": "Generelle innstillinger",
  "allPlaceholder": "Plassholdertekst for søk i alt: ",
  "showInfoWindowOnSelect": "Vis popuptekst for funnet geoobjekt eller lokasjon",
  "searchInCurrentMapExtent": "Søk kun i gjeldende kartutstrekning",
  "zoomScale": "Zoomeskala",
  "locatorUrl": "Geokoder-URL",
  "locatorName": "Geokodernavn",
  "locatorExample": "Eksempel",
  "locatorWarning": "Denne versjonen av geokodingstjenesten støttes ikke. Widgeten støtter versjon 10.1 og nyere av geokodingstjenesten.",
  "locatorTips": "Forslag er ikke tilgjengelige fordi geokodingstjenesten ikke har støtte for forslag.",
  "layerSource": "Lagkilde",
  "searchLayerTips": "Forslag er ikke tilgjengelige, fordi featuretjenesten ikke har støtte for paginering.",
  "placeholder": "Plassholdertekst",
  "searchFields": "Søkefelter",
  "displayField": "Visningsfelt",
  "exactMatch": "Nøyaktig samsvar",
  "maxSuggestions": "Maksimum antall forslag",
  "maxResults": "Maksimum antall resultater",
  "enableLocalSearch": "Aktiver lokalt søk",
  "minScale": "Minste målestokk",
  "minScaleHint": "Når kartmålestokken er større enn denne målestokken, brukes lokalt søk",
  "radius": "Radius",
  "radiusHint": "Angir radiusen for et område rundt det gjeldende midtpunktet i kartet som brukes til å styrke rangeringen til geokodingskandidater, slik at kandidater nærmest lokasjonen returneres først",
  "meters": "Meter",
  "setSearchFields": "Angi søkefelter",
  "set": "Angi",
  "fieldSearchable": "søkbar(t)",
  "fieldName": "Navn",
  "fieldAlias": "Alias",
  "ok": "OK",
  "cancel": "Avbryt",
  "invalidUrlTip": "URL-en ${URL} er ugyldig eller ikke tilgjengelig."
});