define({
  "_widgetLabel": "Table attributaire",
  "_featureAction_ShowRelatedRecords": "Afficher les enregistrements liés",
  "_featureAction_ViewInTable": "Afficher dans la table attributaire",
  "ok": "OK",
  "cancel": "Annuler",
  "unsupportQueryWarning": "La couche doit prendre en charge l’opération de requête pour s’afficher dans le widget Table attributaire. Vérifiez que la fonction de requête dans le service est activée.",
  "exportMessage": "Voulez-vous exporter les données au format CSV ?",
  "exportFiles": "Exporter au format CSV",
  "exportSelected": "Exporter la sélection au format CSV",
  "exportAll": "Tout exporter au format CSV",
  "options": "Options",
  "zoomto": "Zoom",
  "highlight": "Mettre en surbrillance les graphiques",
  "selectAll": "Sélectionner les enregistrements de toutes les pages",
  "selectPage": "Sélectionner les enregistrements de la page en cours",
  "clearSelection": "Vider la sélection",
  "filter": "Filtrer",
  "setFilterTip": "Définissez les filtres correctement.",
  "noFilterTip": "Sans expressions de filtre définies, cette tâche de requête répertorie toutes les entités dans la source de données spécifiée.",
  "filterByExtent": "Filtrer selon l'étendue de la carte",
  "showSelectedRecords": "Afficher les enregistrements sélectionnés",
  "showAllRecords": "Afficher tous les enregistrements",
  "showRelatedRecords": "Afficher les enregistrements liés",
  "noRelatedRecords": "Aucun enregistrement associé n'a été trouvé",
  "attachmentColumn": "Photos et fichiers",
  "refresh": "Actualiser",
  "features": "entités",
  "records": "enregistrements",
  "selected": "sélectionné",
  "transparent": "Mode transparent",
  "indicate": "Localiser la sélection",
  "columns": "Afficher/masquer les colonnes",
  "selectionSymbol": "Symbole de la sélection",
  "closeMessage": "Masquer la table (la redévelopper à partir du bas)",
  "dataNotAvailable": "Données non disponibles !<br>Cliquez sur le bouton [Actualiser] pour réessayer.",
  "openTableTip": "Ouvrir la table attributaire",
  "closeTableTip": "Masquer la table attributaire",
  "sortAsc": "Tri croissant",
  "sortDes": "Tri décroissant",
  "statistics": "Statistiques",
  "attachments": "Pièces jointes",
  "files": "fichiers"
});