define({
  "id": "ID",
  "state": "Pagal nutylėjimą, koordinatės bus rodomos dabartinėje žemėlapių koordinačių sistemoje. Norėdami gauti koordinates kitose koordinačių sistemose, turite pridėti jas ir nurodyti atitinkamas transformacijas.",
  "outputUnit": "Išvesties vienetas",
  "wkid": "Išvesties WKID",
  "label": "Išvesties koordinačių sistemos pavadinimas",
  "transformationWkid": "Transformacijos WKID",
  "transformationLabel": "Transformacijos žymė",
  "transformForward": "Transformuoti į priekį",
  "actions": "Veiksmai",
  "warning": "Įveskite leistiną erdvinės charakteristikos WKID!",
  "tfWarning": "Įveskite leistiną atraminių duomenų transformacijos WKID!",
  "spinnerLabel": "Apvalinti koordinates iki: ",
  "decimalPlace": "dešimtainės skiltys",
  "separator": "Rodyti tūkstančių skyriklius",
  "getVersionError": "Nepavyko gauti geometrijos paslaugos versijos",
  "add": "Pridėti išvesties koordinačių sistemą",
  "edit": "Redaguoti koordinačių sistemą",
  "output": "Išvesties koordinačių sistema",
  "cName": "Koordinačių sistemos pavadinimas",
  "units": "Rodymo vienetai: ",
  "datum": "Duomenų transformacija",
  "tName": "Transformacijos pavadinimas",
  "tWKIDPlaceHolder": "Transformacijos WKID",
  "forward": "Naudoti perspektyvinę transformaciją",
  "ok": "Gerai",
  "cancel": "Atšaukti",
  "olderVersion": "Geometrijos paslauga nepalaiko transformavimo veiksmo",
  "REPEATING_ERROR": " Koordinačių sistema yra išvesties sąraše.",
  "Default": "Numatytasis",
  "Inches": "Coliai",
  "Foot": "Pėdos",
  "Yards": "Jardai",
  "Miles": "Mylios",
  "Nautical_Miles": "Jūrmylės",
  "Millimeters": "Milimetrai",
  "Centimeters": "Centimetrai",
  "Meter": "Metrai",
  "Kilometers": "Kilometrai",
  "Decimeters": "Decimetrai",
  "Decimal_Degrees": "Dešimtainiai laipsniai",
  "Degrees_Decimal_Minutes": "Laipsniai dešimtainės dalys minutės",
  "Degree_Minutes_Seconds": "Laipsniai minutės sekundės",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Koordinačių rodymo tvarka:",
  "lonLatTips": "Ilguma / platuma (X, Y)",
  "latLonTips": "Platuma / Ilguma (Y, X)"
});