define({
  "_widgetLabel": "Kihiloend",
  "titleBasemap": "Aluskaardid",
  "titleLayers": "Töökihid",
  "labelLayer": "Kihi nimi",
  "itemZoomTo": "Suumi",
  "itemTransparency": "Läbipaistvus",
  "itemTransparent": "Läbipaistev",
  "itemOpaque": "Läbipaistmatu",
  "itemMoveUp": "Liiguta ülespoole",
  "itemMoveDown": "Liiguta allapoole",
  "itemDesc": "Kirjeldus",
  "itemDownload": "Laadi alla",
  "itemToAttributeTable": "Vaata atribuuditabelis",
  "itemShowItemDetails": "Kuva sisuobjekti detaile",
  "empty": "tühi",
  "removePopup": "Keela hüpikaknad",
  "enablePopup": "Luba hüpikaknad",
  "turnAllLayersOff": "Lülita kõik kihid välja",
  "turnAllLayersOn": "Lülita kõik kihid sisse",
  "expandAllLayers": "Laienda kõik kihid",
  "collapseAlllayers": "Ahenda kõik kihid",
  "turnAllLabelsOff": "Lülita kõik märgised välja",
  "turnAllLabelsOn": "Lülita kõik märgised sisse",
  "showLabels": "Kuva märgised",
  "hideLables": "Peida märgised"
});