define({
  "id": "ID",
  "state": "Die Koordinaten werden standardmäßig im Koordinatensystem der aktuellen Karte angezeigt. Um Koordinaten in anderen Koordinatensystemen abzurufen, müssen Sie sie hinzufügen und entsprechende Transformationen festlegen.",
  "outputUnit": "Ausgabeeinheit",
  "wkid": "Ausgabe-WKID",
  "label": "Name des Ausgabe-Koordinatensystems",
  "transformationWkid": "Transformations-WKID",
  "transformationLabel": "Transformationsbeschriftung",
  "transformForward": "Vorwärts transformieren",
  "actions": "Aktionen",
  "warning": "Geben Sie eine gültige Raumbezug-WKID ein!",
  "tfWarning": "Geben Sie eine gültige Datumstransformations-WKID ein!",
  "spinnerLabel": "Koordinaten runden auf: ",
  "decimalPlace": "Dezimalstellen",
  "separator": "Tausendertrennzeichen anzeigen",
  "getVersionError": "Die Version des Geometrieservice kann nicht abgerufen werden.",
  "add": "Ausgabe-Koordinatensystem hinzufügen",
  "edit": "Koordinatensystem bearbeiten",
  "output": "Ausgabe-Koordinatensystem",
  "cName": "Name des Koordinatensystems",
  "units": "Anzeigeeinheiten: ",
  "datum": "Datumstransformation",
  "tName": "Transformationsname",
  "tWKIDPlaceHolder": "WKID der Transformation",
  "forward": "Vorwärts-Transformation verwenden",
  "ok": "OK",
  "cancel": "Abbrechen",
  "olderVersion": "Der Geometrieservice unterstützt keinen Transformationsvorgang.",
  "REPEATING_ERROR": " Koordinatensystem ist in der Ausgabeliste vorhanden.",
  "Default": "Standard",
  "Inches": "Zoll",
  "Foot": "Fuß",
  "Yards": "Yard",
  "Miles": "Meilen",
  "Nautical_Miles": "Seemeilen",
  "Millimeters": "Millimeter",
  "Centimeters": "Zentimeter",
  "Meter": "Meter",
  "Kilometers": "Kilometer",
  "Decimeters": "Dezimeter",
  "Decimal_Degrees": "Dezimalgrad",
  "Degrees_Decimal_Minutes": "Grad Dezimalminuten",
  "Degree_Minutes_Seconds": "Grad, Minuten, Sekunden",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Anzeigereihenfolge für Koordinaten:",
  "lonLatTips": "Längengrad/Breitengrad (X, Y)",
  "latLonTips": "Breitengrad/Längengrad (Y, X)"
});