define({
  "instruction": "Odaberite i konfigurirajte slojeve koji će se inicijalno prikazati u atributnoj tablici.",
  "label": "Sloj",
  "show": "Prikaži",
  "actions": "Konfiguriraj polja sloja",
  "field": "Polje",
  "alias": "Alias",
  "url": "URL",
  "sortField": "Sortiraj polje",
  "sortOrderTooltips": {
    "toDescending": "Promijeni u silazni redoslijed",
    "toAscending": "Promijeni u uzlazni redoslijed"
  },
  "visible": "Vidljivo",
  "linkField": "Poveži polje",
  "noLayers": "Nema dostupnih slojeva geoobjekta",
  "back": "Natrag",
  "exportCSV": "Omogući izvoz u CSV",
  "expand": "Na početku proširite widget",
  "filterByExtent": "Omogućite filtriranje prema obuhvatu karte kao zadanu opciju",
  "allowTextSelection": "Omogući odabir teksta",
  "highlightColor": "Boja isticanja",
  "restore": "Vrati na zadanu vrijednost",
  "ok": "U redu",
  "cancel": "Odustani",
  "includePoint": "Uključi koordinate točke u izvezenu datoteku",
  "configureLayerFields": "Konfiguriraj polja sloja",
  "result": "Uspješno spremljeno",
  "warning": "Prvo odaberite opciju Prikaži.",
  "fieldCheckWarning": "Treba odabrati barem jedno polje.",
  "unsupportQueryWarning": "Sloj treba podržavati prikazivanje upita u widgetu atributne tablice. Provjerite je li uključena mogućnost upita u usluzi.",
  "unsupportQueryLayers": "Sljedeći sloj treba podržavati prikazivanje upita u widgetu atributne tablice. Provjerite je li uključena mogućnost upita u usluzi.",
  "fieldName": "Naziv",
  "fieldAlias": "Alias",
  "fieldVisibility": "Vidljivost",
  "fieldActions": "Radnje",
  "showAttachments": "Prikaži privitke"
});