define({
  root: ({
    instruction: "Layar pembuka muncul sebelum aplikasi dapat diakses.",
    defaultContent: "Tambah teks, tautan, dan grafis kecil di sini.",
    requireConfirm: "Memerlukan konfirmasi untuk melanjutkan",
    noRequireConfirm: "Tidak memerlukan konfirmasi untuk melanjutkan",
    optionText: "Opsi bagi pengguna untuk menonaktifkan layar pembuka pada saat memulai aplikasi.",
    confirmLabel: "Teks Konfirmasi: ",
    confirmLabelColor: "Warna teks konfirmasi",
    defaultConfirmText: "Saya menyetujui syarat dan ketentuan di atas",
    confirmOption: "Selalu tampilkan layar pembuka setiap kali aplikasi diluncurkan",
    backgroundColor: "Warna Latar Belakang",
    content: "Konten",
    contentDescription: "ng_Define the content that displays on the splash screen_________________ny.",
    appearance: "Tampilan",
    appearanceDescription: "ng_Set the appearance of the splash screen_____________ny.",
    size: "Ukuran",
    width: "Lebar",
    height: "Tinggi",
    custom: "Kustom",
    background: "Latar belakang",
    colorFill: "Isian Warna",
    imageFill: "Isian gambar",
    chooseFile: "Pilih file",
    noFileChosen: "Tidak ada file dipilih",
    transparency: "Transparansi",
    sizeFill: "Isi",
    sizeFit: "Sesuai",
    sizeStretch: "Bentangkan untuk mengisi (Stretch to fill)",
    sizeCenter: "Pusat",
    sizeTile: "Tile",
    buttonColor: "Warna tombol",
    buttonText: "Teks tombol",
    buttonTextColor: "Warna teks tombol",
    contentAlign:"ng_Content Alignment______ny",
    alignTop:"ng_Top__ny",
    alignMiddle:"ng_Middle___ny",
    maskColor: "Warna mask",
    options: "Opsi",
    optionsDescription: "ng_Set the behavior of the splash screen____________ny."
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});