define({
  "instruction": "La schermata di avvio appare prima che l'applicazione sia accessibile.",
  "defaultContent": "Aggiungere qui testo, collegamenti e piccole immagini.",
  "requireConfirm": "Per continuare, è necessario confermare",
  "noRequireConfirm": "Non richiedere conferma per continuare.",
  "optionText": "Opzione per utente per disabilitare la schermata di avvio all'avvio dell'applicazione.",
  "confirmLabel": "Testi di conferma: ",
  "confirmLabelColor": "Colore testi di conferma",
  "defaultConfirmText": "Accetto le seguenti condizioni d'uso",
  "confirmOption": "Visualizza sempre questa schermata iniziale a ogni avvio dell'app",
  "backgroundColor": "Colore di sfondo",
  "content": "Contenuto",
  "contentDescription": "Definire il contenuto visualizzato nella schermata di avvio.",
  "appearance": "Aspetto",
  "appearanceDescription": "Impostare l'aspetto della schermata di avvio.",
  "size": "Dimensione",
  "width": "Larghezza",
  "height": "Altezza",
  "custom": "Personalizzata",
  "background": "Sfondo",
  "colorFill": "Colore di riempimento",
  "imageFill": "Immagine di riempimento",
  "chooseFile": "Seleziona file",
  "noFileChosen": "Nessun file selezionato",
  "transparency": "Trasparenza",
  "sizeFill": "Riempi",
  "sizeFit": "Misura",
  "sizeStretch": "Adatta allo sfondo",
  "sizeCenter": "Al centro",
  "sizeTile": "Affianca",
  "buttonColor": "Colore pulsante",
  "buttonText": "Testo pulsante",
  "buttonTextColor": "Colore testo pulsante",
  "contentAlign": "Allineamento contenuto",
  "alignTop": "In alto",
  "alignMiddle": "Mezzo",
  "maskColor": "Colore maschera",
  "options": "Opzioni",
  "optionsDescription": "Impostare il comportamento della schermata di avvio."
});