define({
  "_widgetLabel": "قائمة الطبقات",
  "titleBasemap": "خرائط الأساس",
  "titleLayers": "الطبقات الجاهزة للتشغيل",
  "labelLayer": "اسم الطبقة",
  "itemZoomTo": "تكبير إلى",
  "itemTransparency": "معدل الشفافية:",
  "itemTransparent": "شفاف",
  "itemOpaque": "غير شفاف",
  "itemMoveUp": "نقل لأعلى",
  "itemMoveDown": "نقل لأسفل",
  "itemDesc": "الوصف",
  "itemDownload": "تنزيل",
  "itemToAttributeTable": "عرض في جدول البيانات",
  "itemShowItemDetails": "إظهار تفاصيل العنصر",
  "empty": "فارغ",
  "removePopup": "تعطيل العنصر المنبثق",
  "enablePopup": "تمكين العنصر المنبثق",
  "turnAllLayersOff": "إيقاف تشغيل كل الطبقات",
  "turnAllLayersOn": "تشغيل كل الطبقات",
  "expandAllLayers": "توسيع كل الطبقات",
  "collapseAlllayers": "طي كل الطبقات",
  "turnAllLabelsOff": "إيقاف تشغيل كل التسميات",
  "turnAllLabelsOn": "تشغيل كل التسميات",
  "showLabels": "إظهار لافتات التسمية",
  "hideLables": "إخفاء التسميات"
});