define(
   ({
    "sourceSetting": "検索ソースの設定",
    "instruction": "ジオコード サービスまたはフィーチャ レイヤーを検索ソースとして追加および構成します。 指定されたこれらのソースは、検索ボックス内で検索可能な対象を決定します。",
    "add": "検索ソースの追加",
    "addGeocoder": "ジオコーダーの追加",
    "geocoder": "ジオコーダー",
    "setLayerSource": "レイヤー ソースの設定",
    "setGeocoderURL": "ジオコーダーの URL の設定",
    "searchableLayer": "フィーチャ レイヤー",
    "name": "名前",
    "countryCode": "国コードまたは地域コード",
    "countryCodeEg": "例: ",
    "countryCodeHint": "この値を空白のままにすると、すべての国および地域を検索します",
    "generalSetting": "一般設定",
    "allPlaceholder": "すべてを検索するためのプレースホルダー テキスト: ",
    "showInfoWindowOnSelect": "検出されたフィーチャまたは位置のポップアップを表示",
    "searchInCurrentMapExtent": "現在のマップ範囲内のみを検索",
    "locatorUrl": "ジオコーダーの URL",
    "locatorName": "ジオコーダー名",
    "locatorExample": "例",
    "locatorWarning": "このジオコーディング サービスのバージョンはサポートされていません。 ウィジェットは、00.0 以上のジオコーディング サービスをサポートしています。",
    "locatorTips": "ジオコーディング サービスがヒント機能をサポートしていないため、ヒントは使用できません。",
    "layerSource": "レイヤー ソース",
    "searchLayerTips": "フィーチャ サービスがページネーション機能をサポートしていないため、ヒントは使用できません。",
    "placeholder": "プレースホルダー テキスト",
    "searchFields": "検索フィールド",
    "displayField": "表示フィールド",
    "exactMatch": "完全一致",
    "maxResults": "結果の最大数",
    "setSearchFields": "検索フィールドの設定",
    "set": "設定",
    "fieldSearchable": "検索可能",
    "fieldName": "名前",
    "fieldAlias": "エイリアス",
    "ok": "OK",
    "cancel": "キャンセル",
    "invalidUrlTip": "入力した URL は無効であるか、アクセスできません。"
  })
);