define({
  "id": "Kimlik",
  "state": "Varsayılan olarak koordinatlar geçerli haritanın koordinat sisteminde görüntülenecek. Diğer koordinat sistemlerindeki koordinatları almak için bunları eklemeniz ve uygun dönüşümleri belirtmeniz gerekir.",
  "outputUnit": "Çıktı birimi",
  "wkid": "Çıktı WKID'si",
  "label": "Çıktı koordinat sistemi adı",
  "transformationWkid": "Dönüştürme WKID'si",
  "transformationLabel": "Dönüştürme etiketi",
  "transformForward": "İleri doğru dönüştür",
  "actions": "İşlemler",
  "warning": "Geçerli mekansal başvuru WKID'si girin!",
  "tfWarning": "Geçerli veri dönüştürme WKID'si girin!",
  "spinnerLabel": "Koordinatları şu değere yuvarla: ",
  "decimalPlace": "ondalık haneler",
  "separator": "Binlik ayırıcıyı göster",
  "getVersionError": "Geometri servisi sürümü alınamıyor",
  "add": "Çıktı koordinat sistemi ekle",
  "edit": "Koordinat sistemini düzenle",
  "output": "Çıktı koordinat sistemi",
  "cName": "Koordinat sistemi adı",
  "units": "Görüntüleme birimleri: ",
  "datum": "Veri dönüştürme",
  "tName": "Dönüştürme adı",
  "tWKIDPlaceHolder": "Dönüşüm WKID'si",
  "forward": "İleri dönüştürme kullan",
  "ok": "Tamam",
  "cancel": "İptal",
  "olderVersion": "Geometri servisi, dönüşüm işlemini desteklemiyor",
  "REPEATING_ERROR": " Koordinat sistemi çıktı listesinde yer alır.",
  "Default": "Varsayılan",
  "Inches": "İnç",
  "Foot": "Fit",
  "Yards": "Yarda",
  "Miles": "Mil",
  "Nautical_Miles": "Deniz mili",
  "Millimeters": "Milimetre",
  "Centimeters": "Santimetre",
  "Meter": "Metre",
  "Kilometers": "Kilometre",
  "Decimeters": "Desimetre",
  "Decimal_Degrees": "Ondalık derece",
  "Degrees_Decimal_Minutes": "Derece ondalık dakika",
  "Degree_Minutes_Seconds": "Derece dakika saniye",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Koordinat görüntüleme sırası:",
  "lonLatTips": "Boylam / Enlem(X, Y)",
  "latLonTips": "Enlem / Boylam(Y, X)"
});