define(
   ({
    id: 'Kimlik',
    state: "Varsayılan olarak koordinatlar geçerli haritanın koordinat sisteminde görüntülenecek. Diğer koordinat sistemlerindeki koordinatları almak için bunları eklemeniz ve uygun dönüşümleri belirtmeniz gerekir.",
    outputUnit: "Çıktı Birimi",
    wkid: "Çıktı WKID\'si",
    label: "Çıktı Koordinat Sistemi Adı",
    transformationWkid: "Dönüştürme WKID\'si",
    transformationLabel: "Dönüştürme Etiketi",
    transformForward: "İleri Doğru Dönüştür",
    actions: "İşlemler",
    warning: "Geçerli mekansal başvuru WKID\'si girin!",
    tfWarning: "Geçerli veri dönüştürme WKID\'si girin!",
    spinnerLabel: "Koordinatları şu değere yuvarla: ",
    decimalPlace: "ondalık haneler",
    separator: "Binlik ayırıcıyı göster",
    getVersionError: "Geometri Servisi sürümü alınamıyor",

    add: "Çıktı Koordinat Sistemi Ekle",
    edit: "Koordinat Sistemini Düzenle",
    output: "Çıktı Koordinat Sistemi",
    cName: "Koordinat Sistemi Adı",
    units: "Görüntüleme Birimleri: ",
    datum: "Datum Dönüştürme",
    tName: "Dönüştürme Adı",
    tWKIDPlaceHolder: "Dönüşüm WKID\'si",
    forward: "İleri dönüştürme kullan",
    ok: "Tamam",
    cancel: 'İptal',
    olderVersion: "Geometri Servisi, dönüşüm hizmetini desteklemiyor",
    REPEATING_ERROR: " Koordinat sistemi çıktı listesinde yer alır.",

    Default: "Varsayılan",
    Inches: "İnç",
    Foot: "Fit",
    Yards: "Yarda",
    Miles: "Mil",
    Nautical_Miles: "Deniz Mili",
    Millimeters: "Milimetre",
    Centimeters: "Santimetre",
    Meter: "Metre",
    Kilometers: "Kilometre",
    Decimeters: "Desimetre",
    Decimal_Degrees: "Ondalık Derece",
    Degree_Minutes_Seconds: "Derece Dakika Saniye",
    MGRS: "MGRS",
    USNG: "USNG"
  })
);