define({
  "_widgetLabel": "Lagliste",
  "titleBasemap": "Baggrundskort",
  "titleLayers": "Operationelle lag",
  "labelLayer": "Navn på lag",
  "itemZoomTo": "Zoom til",
  "itemTransparency": "Gennemsigtighed",
  "itemTransparent": "Gennemsigtig",
  "itemOpaque": "Uigennemsigtig",
  "itemMoveUp": "Flyt op",
  "itemMoveDown": "Flyt ned",
  "itemDesc": "Beskrivelse",
  "itemDownload": "Hent",
  "itemToAttributeTable": "Vis i attributtabel",
  "itemShowItemDetails": "Vis elementoplysninger",
  "empty": "tom",
  "removePopup": "Deaktivér pop-up",
  "enablePopup": "Aktivér pop-up",
  "turnAllLayersOff": "Deaktivér alle lag",
  "turnAllLayersOn": "Aktivér alle lag",
  "expandAllLayers": "Vis alle lag",
  "collapseAlllayers": "Skjul alle lag",
  "turnAllLabelsOff": "Deaktivér alle etiketter",
  "turnAllLabelsOn": "Aktivér alle etiketter",
  "showLabels": "Vis etiketter",
  "hideLables": "Skjul etiketter"
});