define({
  "instruction": "Velkomstskærmen vises, før applikationen bliver tilgængelig.",
  "defaultContent": "Tilføj tekst, links og små billeder her.",
  "requireConfirm": "Kræver bekræftelse for at fortsætte",
  "noRequireConfirm": "Kræver ikke bekræftelse for at fortsætte",
  "optionText": "Mulighed for, at brugeren kan deaktivere velkomstskærmen ved applikationsstart.",
  "confirmLabel": "Bekræftelsestekster: ",
  "confirmLabelColor": "Bekræftelsestekstfarve",
  "defaultConfirmText": "Jeg er enig i ovenstående vilkår og betingelser",
  "confirmOption": "Vis altid denne velkomstskærm, hver gang app'en startes",
  "backgroundColor": "Baggrundsfarve",
  "content": "Indhold",
  "contentDescription": "Definér det indhold, der skal vises på velkomstskærmen.",
  "appearance": "Udseende",
  "appearanceDescription": "Definér velkomstskærmens udseende.",
  "size": "Størrelse",
  "width": "Bredde",
  "height": "Højde",
  "custom": "Brugerdefineret",
  "background": "Baggrund",
  "colorFill": "Farvefyld",
  "imageFill": "Billedfyld",
  "chooseFile": "Vælg fil",
  "noFileChosen": "Der er ikke valgt nogen fil",
  "transparency": "Transparency",
  "sizeFill": "Fyld",
  "sizeFit": "Tilpas",
  "sizeStretch": "Stræk og udfyld",
  "sizeCenter": "Midt",
  "sizeTile": "Tile",
  "buttonColor": "Knapfarve",
  "buttonText": "Knaptekst",
  "buttonTextColor": "Knaptekstfarve",
  "contentAlign": "Indholdsjustering",
  "alignTop": "Top",
  "alignMiddle": "Mellem",
  "maskColor": "Maskefarve",
  "options": "Indstillinger",
  "optionsDescription": "Definér velkomstskærmens funktionsmåde."
});