define({
  "instruction": "تظهر شاشة البداية قبل التطبيق الذي يمكن الوصول إليه.",
  "defaultContent": "أضف نصًا وروابط ورسومات بيانية صغيرة هنا.",
  "requireConfirm": "يتطلب التأكيد للاستمرار",
  "noRequireConfirm": "لا يتطلب التأكيد للمتابعة",
  "optionText": "خيار للمستخدم لتعطيل شاشة البداية عند تشغيل التطبيق.",
  "confirmLabel": "نصوص التأكيد: ",
  "confirmLabelColor": "لون نصوص التأكيد",
  "defaultConfirmText": "أوافق على الشروط والأحكام المذكورة أعلاه",
  "confirmOption": "عرض شاشة البداية دائمًا في كل مرة يتم فيها تشغيل التطبيق",
  "backgroundColor": "لون الخلفية",
  "content": "المحتوى",
  "contentDescription": "يقوم بتعريف المحتوى الذي يُعرض على شاشة البداية.",
  "appearance": "المظهر",
  "appearanceDescription": "إعداد مظهر شاشة البداية.",
  "size": "الحجم",
  "width": "العرض",
  "height": "ارتفاع",
  "custom": "تخصيص",
  "background": "الخلفية",
  "colorFill": "تعبئة اللون",
  "imageFill": "تعبئة صورة",
  "chooseFile": "اختيار ملف",
  "noFileChosen": "لم يتم اختيار الملف",
  "transparency": "الشفافية",
  "sizeFill": "ملء",
  "sizeFit": "احتواء",
  "sizeStretch": "تمدد للتعبئة",
  "sizeCenter": "الوسط",
  "sizeTile": "تجانب",
  "buttonColor": "لون الزر",
  "buttonText": "نص الزر",
  "buttonTextColor": "لون نص الزر",
  "contentAlign": "محاذاة المحتوى",
  "alignTop": "أعلى",
  "alignMiddle": "وسط",
  "maskColor": "لون القناع",
  "options": "خيارات",
  "optionsDescription": "إعداد سلوك شاشة البداية."
});