define({
  "sourceSetting": "Configuració de l'origen de la cerca",
  "instruction": "Afegiu i configureu serveis de geocodificació o capes d'entitats com a orígens de cerca. Aquests orígens especificats determinen què es pot cercar al quadre de cerca.",
  "add": "Afegeix un origen de cerca",
  "addGeocoder": "Afegeix un geocodificador",
  "geocoder": "Geocodificador",
  "setLayerSource": "Defineix l'origen de la capa",
  "setGeocoderURL": "Defineix la URL del geocodificador",
  "searchableLayer": "Capa d'entitats",
  "name": "Nom",
  "countryCode": "Codis de país o regió",
  "countryCodeEg": "per exemple, ",
  "countryCodeHint": "Si aquest valor es deixa en blanc, la cerca es farà en tots els països i regions",
  "generalSetting": "Configuració general",
  "allPlaceholder": "Text del marcador de posició per cercar-ho tot: ",
  "showInfoWindowOnSelect": "Mostra la finestra emergent de l'entitat o la ubicació trobada",
  "showInfoWindowOnSelect2": "Mostra la finestra emergent quan es trobi l'entitat o la ubicació.",
  "searchInCurrentMapExtent": "Cerca només a l'extensió de mapa actual",
  "zoomScale": "Escala de zoom",
  "locatorUrl": "URL del geocodificador",
  "locatorName": "Nom del geocodificador",
  "locatorExample": "Exemple",
  "locatorWarning": "Aquesta versió del servei de geocodificació no s'admet. El widget admet el servei de geocodificació 10.1 i versions posteriors.",
  "locatorTips": "Els suggeriments no estan disponibles perquè el servei de geocodificació no admet la funció de suggeriments.",
  "layerSource": "Origen de la capa",
  "searchLayerTips": "Els suggeriments no estan disponibles perquè el servei d'entitats no admet la funció de paginació.",
  "placeholder": "Text del marcador de posició",
  "searchFields": "Camps de cerca",
  "displayField": "Camp que es mostra",
  "exactMatch": "Coincidència exacta",
  "maxSuggestions": "Màxim de suggeriments",
  "maxResults": "Màxim de resultats",
  "enableLocalSearch": "Habilita la cerca local",
  "minScale": "Escala mínima",
  "minScaleHint": "Si l'escala del mapa és més gran que aquesta escala, s'aplicarà la cerca local",
  "radius": "Radi",
  "radiusHint": "Permet especificar el radi d'una àrea al voltant del centre del mapa actual que s'utilitzarà per millorar la classificació dels candidats de geocodificació per tal que es retornin primer aquells més propers a la ubicació",
  "meters": "Metres",
  "setSearchFields": "Defineix els camps de cerca",
  "set": "Defineix",
  "fieldSearchable": "permet la cerca",
  "fieldName": "Nom",
  "fieldAlias": "Àlies",
  "ok": "D'acord",
  "cancel": "Cancel·la",
  "invalidUrlTip": "L'adreça URL ${URL} no és vàlida o no s'hi pot accedir."
});