define({
  "_widgetLabel": "Koordináta",
  "hintMessage": "Kattintson a térképre a koordináták meghatározásához",
  "defaultLabel": "Alapértelmezett",
  "realtimeLabel": "Mozgassa az egeret a koordináták meghatározásához",
  "computing": "Kiszámítás...",
  "latitudeLabel": "Szélesség",
  "longitudeLabel": "Hosszúság",
  "loading": "betöltés...",
  "enableClick": "Ide kattintva engedélyezheti a koordinátáknak a térképre való kattintással történő meghatározását",
  "disableClick": "Ide kattintva letilthatja a koordinátáknak a térképre való kattintással történő meghatározását",
  "Default": "Alapértelmezett",
  "Inches": "hüvelyk",
  "Foot": "láb",
  "Yards": "yard",
  "Miles": "mérföld",
  "Nautical_Miles": "tengeri mérföld",
  "Millimeters": "milliméter",
  "Centimeters": "centiméter",
  "Meter": "méter",
  "Kilometers": "kilométer",
  "Decimeters": "deciméter",
  "Decimal_Degrees": "fok",
  "Degree_Minutes_Seconds": "fok - perc - másodperc",
  "MGRS": "MGRS",
  "USNG": "USNG"
});