define({
  "common": {
    "apply": "Applica",
    "ok": "OK",
    "cancel": "Annulla",
    "yes": "Sì",
    "no": "No",
    "next": "Avanti",
    "previous": "Precedente",
    "back": "Indietro",
    "selected": "selezionato",
    "name": "Nome",
    "usage": "Utilizzo",
    "settings": "Impostazioni",
    "home": "Home",
    "link": "Collega",
    "messages": "Messaggi",
    "outputs": "Output",
    "title": "Titolo",
    "thumbnail": "Anteprima",
    "url": "URL",
    "actions": "Azioni",
    "layer": "Layer",
    "action": "Azione",
    "input": "Input",
    "output": "Output",
    "type": "Tipo",
    "required": "Richiesto",
    "options": "Opzioni",
    "label": "Etichetta",
    "tooltip": "Descrizione comandi",
    "visible": "Visibile",
    "symbol": "Simbolo",
    "popup": "Popup",
    "upload": "Carica",
    "execute": "Esegui",
    "help": "Guida",
    "executing": "Esecuzione",
    "clear": "Cancella",
    "error": "Errore",
    "zoomTo": "Zoom a",
    "attribute": "Attributo",
    "exports": "Esporta",
    "check": "Seleziona",
    "save": "Salva",
    "close": "Chiudi",
    "deleteText": "Può eliminare",
    "map": "Mappa",
    "scene": "Scena",
    "reset": "Reimposta",
    "icon": "Icona",
    "folder": "Cartella",
    "share": "Condividi",
    "view": "Visualizza",
    "newText": "Nuovo",
    "edit": "Modifica",
    "wkid": "WKID",
    "table": "Tabella",
    "zoomIn": "Zoom avanti",
    "zoomOut": "Zoom indietro",
    "continue1": "Continua",
    "longitude": "Longitudine",
    "latitude": "Latitudine",
    "custom": "Personalizzata",
    "image": "Immagine",
    "font": "Carattere",
    "text": "Testo",
    "all": "tutte le",
    "number": "Numero",
    "percentage": "Percentuale",
    "unit": "Unità",
    "thousand": "Migliaia",
    "billion": "Miliardo",
    "million": "Milione",
    "none": "Nessuno",
    "field": "Campo",
    "operation": "Operazione",
    "disableUpdateGeometry": "Disabilita aggiornamento geometria",
    "preview": "Anteprima"
  },
  "errorCode": "Codice",
  "errorMessage": "Messaggio",
  "errorDetail": "Dettagli",
  "widgetPlaceholderTooltip": "Per configurarlo, passare a Widget e fare clic sul segnaposto corrispondente",
  "fieldStatistics": {
    "selectField": "Seleziona campo",
    "statistics": "Statistiche",
    "field": "Campo",
    "count": "Numero di valori",
    "sum": "Somma dei valori",
    "min": "Minima",
    "max": "Massima",
    "ave": "Mediocre",
    "stddev": "Deviazione standard"
  },
  "symbolChooser": {
    "preview": "Anteprima",
    "basic": "Base",
    "arrows": "Frecce",
    "business": "Aziende",
    "cartographic": "Cartografico",
    "nationalParkService": "Servizio parco nazionale",
    "outdoorRecreation": "Attività ricreative all'aperto",
    "peoplePlaces": "Luoghi e persone",
    "safetyHealth": "Sicurezza e salute",
    "shapes": "Forme",
    "transportation": "Trasporti",
    "symbolSize": "Dimensioni simbolo",
    "color": "Colore",
    "alpha": "Alfa",
    "outlineColor": "Colore contorno",
    "outlineWidth": "Spessore contorno",
    "style": "Stile",
    "width": "Larghezza",
    "text": "Testo",
    "fontColor": "Colore carattere",
    "fontSize": "Dimensione carattere",
    "transparency": "Trasparenza",
    "solid": "Continua",
    "dash": "Tratteggiata",
    "dot": "Punteggiata",
    "dashDot": "Trattino punto",
    "dashDotDot": "Trattino punto trattino",
    "customImage": "Immagine personalizzata",
    "chooseFile": "Seleziona file",
    "noFileChoosen": "Nessun file selezionato."
  },
  "transparency": {
    "opaque": "Opaco",
    "transparent": "Trasparente"
  },
  "rendererChooser": {
    "domain": "Dominio",
    "use": "Utilizzare",
    "singleSymbol": "Un singolo simbolo",
    "uniqueSymbol": "Simboli univoci",
    "color": "Colore",
    "size": "Dimensione",
    "toShow": "Da mostrare",
    "colors": "Colori",
    "classes": "Classi",
    "symbolSize": "Dimensioni simbolo",
    "addValue": "Aggiungi valore",
    "setDefaultSymbol": "Imposta simbolo predefinito",
    "defaultSymbol": "Simbolo di default",
    "selectedSymbol": "Simbolo selezionato",
    "value": "Valore",
    "label": "Etichetta",
    "range": "Intervallo"
  },
  "drawBox": {
    "point": "Punto",
    "line": "Linea",
    "polyline": "Polilinea",
    "freehandPolyline": "Polilinea a mano libera",
    "triangle": "Triangolo",
    "extent": "Estensione",
    "circle": "Cerchio",
    "ellipse": "Ellisse",
    "polygon": "Poligono",
    "freehandPolygon": "Poligono a mano libera",
    "text": "Testo",
    "clear": "Cancella"
  },
  "popupConfig": {
    "title": "Titolo",
    "add": "Aggiungi",
    "fields": "Campi",
    "noField": "Campi non disponibili",
    "visibility": "Visibile",
    "name": "Nome",
    "alias": "Alias",
    "actions": "Azioni"
  },
  "includeButton": {
    "include": "Includi"
  },
  "loadingShelter": {
    "loading": "Caricamento in corso"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Nessun servizio trovato.",
    "unableConnectTo": "Impossibile connettersi a",
    "invalidUrlTip": "L'URL immesso non è valido o non è accessibile."
  },
  "serviceBrowser": {
    "noGpFound": "Nessun servizio di geoprocessing trovato.",
    "unableConnectTo": "Impossibile connettersi a"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Nessun map service o feature service trovato.",
    "unableConnectTo": "Impossibile connettersi a"
  },
  "basicServiceChooser": {
    "validate": "Convalida",
    "example": "Esempio",
    "set": "Imposta"
  },
  "urlInput": {
    "invalidUrl": "URL non valido."
  },
  "urlComboBox": {
    "invalidUrl": "URL non valido."
  },
  "filterBuilder": {
    "addAnotherExpression": "Aggiungi espressione",
    "addSet": "Aggiungi un set",
    "matchMsg": "Ottieni le feature nel layer corrispondenti a ${any_or_all} tra le seguenti espressioni",
    "matchMsgSet": "In questo set ${any_or_all} seguenti espressioni sono vere",
    "all": "Tutto",
    "any": "una qualsiasi delle",
    "value": "Valore",
    "field": "Campo",
    "unique": "Univoci",
    "none": "Nessuno",
    "and": "e",
    "valueTooltip": "Immetti valore",
    "fieldTooltip": "Seleziona da campo esistente",
    "uniqueValueTooltip": "Seleziona da valori univoci nel campo selezionato",
    "stringOperatorIs": "è",
    "stringOperatorIsNot": "non è",
    "stringOperatorStartsWith": "inizia con",
    "stringOperatorEndsWith": "termina con",
    "stringOperatorContains": "contiene",
    "stringOperatorDoesNotContain": "non contiene",
    "stringOperatorIsBlank": "è vuoto",
    "stringOperatorIsNotBlank": "non è vuoto",
    "dateOperatorIsOn": "ricorre il giorno",
    "dateOperatorIsNotOn": "non ricorre il giorno",
    "dateOperatorIsBefore": "ricorre prima del giorno",
    "dateOperatorIsAfter": "ricorre dopo il giorno",
    "dateOperatorIsOnOrBefore": "è uguale o precedente",
    "dateOperatorIsOnOrAfter": "è uguale o successivo",
    "dateOperatorMinutes": "minuti",
    "dateOperatorHours": "ore",
    "dateOperatorDays": "giorni",
    "dateOperatorWeeks": "settimane",
    "dateOperatorMonths": "mesi",
    "dateOperatorYears": "anni",
    "dateOperatorInTheLast": "negli ultimi/nelle ultime",
    "dateOperatorNotInTheLast": "non negli ultimi/nelle ultime",
    "dateOperatorIsBetween": "è compreso tra",
    "dateOperatorIsNotBetween": "non è compreso tra",
    "dateOperatorIsBlank": "è vuoto",
    "dateOperatorIsNotBlank": "non è vuoto",
    "numberOperatorIs": "è",
    "numberOperatorIsNot": "non è",
    "numberOperatorIsAtLeast": "è almeno",
    "numberOperatorIsLessThan": "è minore di",
    "numberOperatorIsAtMost": "è al massimo",
    "numberOperatorIsGreaterThan": "è maggiore di",
    "numberOperatorIsBetween": "è compreso tra",
    "numberOperatorIsNotBetween": "non è compreso tra",
    "numberOperatorIsBlank": "è vuoto",
    "numberOperatorIsNotBlank": "non è vuoto",
    "string": "Stringa",
    "number": "Numero",
    "date": "Data",
    "askForValues": "Richiedi valori",
    "prompt": "Prompt",
    "hint": "Suggerimento",
    "error": {
      "invalidParams": "Parametri non validi.",
      "invalidUrl": "URL non valido.",
      "noFilterFields": "Il layer non contiene campi utilizzabili per creare filtri.",
      "invalidSQL": "Espressione SQL non valida.",
      "cantParseSQL": "Impossibile analizzare l'espressione SQL."
    },
    "caseSensitive": "Distinzione maiuscole/minuscole",
    "notSupportCaseSensitiveTip": "I servizi ospitati non supportano query con distinzione tra maiuscole e minuscole.",
    "setFilterTip": "Impostare i filtri correttamente.",
    "listValues": "Valori elenco",
    "cascadeFilterTip": "Mostrare solo valori filtrati in base a espressioni precedenti.",
    "noneCascadeFilterTip": "Tutti i valori univoci di questo campo",
    "previousCascadeFilterTip": "Valori filtrati in base a espressioni precedenti",
    "allCascadeFilterTip": "Valori filtrati in base a tutte le altre espressioni"
  },
  "featureLayerSource": {
    "layer": "Layer",
    "browse": "Sfoglia",
    "selectFromMap": "Mappa",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL di Servizio",
    "inputLayerUrl": "URL layer di input",
    "selectLayer": "Seleziona un layer feature dalla mappa corrente.",
    "chooseItem": "Scegli un elemento layer feature.",
    "setServiceUrl": "Immettere l'URL di un feature service o di un map service.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Scegliere un feature layer."
  },
  "queryableLayerSource": {
    "layer": "Layer",
    "browse": "Esplora",
    "selectFromMap": "Mappa",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL di Servizio",
    "inputLayerUrl": "URL layer di input",
    "selectLayer": "Selezionare un layer dalla mappa corrente.",
    "chooseItem": "Scegliere un elemento.",
    "setServiceUrl": "Immettere l'URL del servizio.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Selezionare un layer."
  },
  "gpSource": {
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL di Servizio",
    "selectFromOnline": "ArcGIS Online",
    "setServiceUrl": "Immettere l'URL di un servizio di geoprocessing.",
    "chooseItem": "Scegliere un elemento del servizio di geoprocessing.",
    "chooseTask": "Scegliere un'attività di geoprocessing."
  },
  "itemSelector": {
    "map": "Mappa",
    "selectWebMap": "Selezionare una mappa Web",
    "addMapFromOnlineOrPortal": "Cercare e aggiungere una mappa Web nell'applicazione da risorse pubbliche di ArcGIS Online o da contenuti privati disponibili in ArcGIS Online o nel portale.",
    "searchMapName": "Cerca per nome applicazione...",
    "searchNone": "Impossibile trovare l'elemento cercato. Riprovare.",
    "groups": "Gruppi",
    "noneGroups": "Gruppi non disponibili",
    "signInTip": "La sessione di accesso è scaduta. Aggiornare il browser per accedere nuovamente al portale.",
    "signIn": "Accedi",
    "publicMap": "Pubblico",
    "myOrganization": "La mia organizzazione",
    "myGroup": "I miei gruppi",
    "myContent": "I miei contenuti",
    "count": "Conteggio",
    "fromPortal": "da portale",
    "fromOnline": "da ArcGIS.com",
    "noneThumbnail": "Anteprima non disponibile",
    "owner": "proprietario",
    "signInTo": "Accedi a",
    "lastModified": "Data ultima modifica",
    "moreDetails": "Ulteriori dettagli",
    "mostRecent": "Più recente",
    "mostViewed": "Più visualizzato",
    "highestRated": "Con valutazione più alta",
    "viewItemDetails": "Visualizza dettagli elemento"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Il servizio non supporta la query."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Nessun layer appropriato disponibile nella mappa."
  },
  "layerInfosMenu": {
    "titleBasemap": "Mappe di base",
    "titleLayers": "Layer operativi",
    "labelLayer": "Nome layer",
    "itemZoomTo": "Zoom a",
    "itemTransparency": "Trasparenza",
    "itemTransparent": "Trasparente",
    "itemOpaque": "Opaco",
    "itemMoveUp": "Sposta su",
    "itemMoveDown": "Sposta giù",
    "itemDesc": "Descrizione",
    "itemDownload": "Download",
    "itemToAttributeTable": "Visualizza nella tabella degli attributi"
  },
  "imageChooser": {
    "unsupportReaderAPI": "Da fare: il browser non supporta L'API del lettore di file",
    "readError": "Lettura del file non riuscita.",
    "unknowError": "impossibile completare le operazioni",
    "invalidType": "Tipo di file non valido.",
    "cropImage": "Ritaglia immagine",
    "exceed": "Le dimensioni del file non possono superare 1024 KB",
    "enableFlash": "Abilitare Adobe Flash prima di passare a un'immagine.",
    "cropWaining": "Scegliere una foto di almeno ${width} x ${height} pixel.",
    "toolTip": "Per ottimizzare i risultati, l'immagine deve avere una larghezza pari a ${width} pixel e un'altezza pari a ${height} pixel. Dimensioni diverse verranno adattate. I formati di immagine supportati sono PNG, GIF e JPEG."
  },
  "simpleTable": {
    "moveUp": "Sposta su",
    "moveDown": "Sposta giù",
    "deleteRow": "Elimina",
    "edit": "Modifica"
  },
  "urlParams": {
    "invalidToken": "Token non valido",
    "validateTokenError": "Token non valido o errore di rete"
  },
  "exportTo": {
    "exportTo": "Esporta",
    "toCSV": "Esporta in file CSV",
    "toFeatureCollection": "Esporta in raccolta di feature",
    "toGeoJSON": "Esporta in GeoJSON"
  },
  "appState": {
    "title": "Stato dell'app",
    "restoreMap": "Fare clic per ripristinare l'estensione mappa e la visibilità dei layer dove si era rimasti."
  },
  "featureActions": {
    "featureActions": "Azioni feature",
    "ZoomTo": "Zoom a",
    "PanTo": "Effettua Zoom A",
    "Flash": "Flash",
    "ShowPopup": "Mostra popup",
    "CreateLayer": "Crea layer",
    "ShowStatistics": "Statistiche...",
    "ClearSelection": "Cancella selezione",
    "ExportToCSV": "Esporta in file CSV",
    "ShowSelectedFeature": "Mostra feature selezionate",
    "ExportToFeatureCollection": "Esporta in raccolta di feature",
    "ExportToGeoJSON": "Esporta in GeoJSON",
    "EditAttributes": "Modifica attributi",
    "AddMarker": "Aggiungi un marcatore",
    "RemoveMarker": "Rimuovi marcatore",
    "SaveToMyContent": "Salva in I miei contenuti"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Layer correlato",
    "selectedFeatures": "Usa feature selezionate",
    "drawShapesTip": "Disegna forme per selezionare feature",
    "pleaseDrawShapesTip": "Disegnare le forme per selezionare le feature",
    "allFeaturesTip": "Tutte le caratteristiche del layer",
    "selectFeaturesOrDrawShapesTip": "Utilizzare le feature selezionate in questo layer o disegnare forme sulla mappa per limitare le feature."
  },
  "searchDistance": {
    "applySearchDistance": "Applica a distanza di ricerca",
    "applySearchDistanceToFeatures": "Applica una distanza di ricerca alle feature"
  },
  "units": {
    "miles": "Miglia",
    "milesAbbr": "mi",
    "kilometers": "Chilometri",
    "kilometersAbbr": "km",
    "feet": "Piedi",
    "feetAbbr": "piedi",
    "meters": "Metri",
    "metersAbbr": "m",
    "yards": "Iarde",
    "yardsAbbr": "yd",
    "acres": "Acri",
    "acresAbbr": "acri",
    "nauticalMiles": "Miglia nautiche",
    "nauticalMilesAbbr": "nmi",
    "uSSurveyFeet": "Piedi US rilevamento",
    "uSSurveyFeetAbbr": "ftUS",
    "decimalDegree": "Gradi decimali",
    "decimalDegreeAbbr": "dd",
    "degreeMinuteSeconds": "Grado minuti secondi",
    "degreeMinuteSecondsAbbr": "g-m-s",
    "squareMiles": "Miglia quadrate",
    "squareMilesAbbr": "mi²",
    "squareKilometer": "Chilometri quadrati",
    "squareKilometerAbbr": "km²",
    "squareFeet": "Piedi quadrati",
    "squareFeetAbbr": "ft²",
    "squareMeters": "Metri quadrati",
    "squareMetersAbbr": "m²",
    "squareYards": "Iarde quadrate",
    "squareYardsAbbr": "yd²",
    "squareUSSurveyFeet": "Piedi quadrati USA rilevamento",
    "squareUSSurveyFeetAbbr": "ft²USA"
  },
  "featureSetChooser": {
    "select": "Seleziona",
    "dragBox": "Trascina",
    "dragMouse": "Trascinare il mouse",
    "selectByRectangle": "Seleziona tramite rettangolo",
    "selectFeaturesTip": "Selezionare le feature trascinando la casella intorno ad esse sulla mappa",
    "newSelectionTip": "Crea nuova selezione",
    "addSelectionTip": "Aggiungi a selezione",
    "removeSelectionTip": "Rimuovi da selezione",
    "selectFromCurrentSelectionTip": "Seleziona dalla selezione corrente",
    "unselectAllSelectionTip": "Deseleziona tutte le feature attualmente selezionate",
    "selectByPolygon": "Seleziona tramite poligono",
    "selectByCircle": "Seleziona tramite cerchio",
    "selectByLine": "Seleziona tramite linea",
    "chooseSelectingTools": "Scegli strumenti di selezione",
    "darw": "Disegna",
    "drawShap": "Disegnare una forma"
  },
  "widgetManager": {
    "createWidgetError": "Errore di creazione del widget",
    "createWidgetSettingPageError": "Errore di creazione della pagina di impostazione del widget",
    "loadWidgetResourceError": "Errore di caricamento della risorsa del widget"
  },
  "shareOptions": {
    "shareMap": "Specificare gli utenti autorizzati a visualizzare questa app",
    "shareMapTips": "L'app è attualmente condivisa con gli utenti seguenti",
    "everyone": "Tutti",
    "theseGroups": "Questi gruppi"
  },
  "shareLink": {
    "email": "e-mail",
    "shareEmail": "E-mail",
    "facebook": "Facebook",
    "shareFacebook": "Facebook",
    "twitter": "Twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "Incorpora questa app in un sito Web",
    "shareEmailSubject": "Condivisione app Web:",
    "shareEmailTxt1": "App Web condivisa con l'utente utilizzando Web AppBuilder for ArcGIS.",
    "shareEmailTxt2": "È possibile creare e condividere proprie app Web con Web AppBuilder for ArcGIS di Esri.",
    "shareEmailTxt3": "Per ulteriori dettagli, visitare http://www.esri.com/software/web-appbuilder.",
    "smallSize": "Piccolo",
    "mediumSize": "Media",
    "largeSize": "Grande",
    "customSize": "Personalizzata",
    "embed": "Incorpora questa app in un sito Web",
    "more": "Opzioni incorporate",
    "changeShareSettings": "Modifica impostazioni di condivisione",
    "shareLinkText": "Condividi un collegamento a questa app",
    "linkOptions": "Opzioni di collegamento",
    "linkOptionsUrlParameters": "Seleziona parametri URL inclusi nel collegamento",
    "currentMapExtent": "Estensione mappa corrente",
    "chooseCenterWithLevel": "Fare clic sulla mappa per definire il centro della mappa con livello di zoom",
    "chooseCenterWithScale": "Fare clic sulla mappa per definire il centro della mappa con scala della mappa",
    "findLocation": "Trova la posizione o la feature e applica lo zoom",
    "findLocation_inputPlaceholder": "Località o feature",
    "queryFeature": "Interroga una feature e applica lo zoom",
    "addMarker": "Aggiungi un marcatore sulla mappa",
    "addMarker_titlePlaceholder": "Titolo del pop-up del marcatore",
    "addMarker_symbolURL": "URL simbolo di marcatore",
    "addMarker_label": "Etichetta marcatore",
    "popupTitle": "Titolo popup",
    "zoomLevel": "Livello di zoom",
    "overwirteMobileLayout": "Sovrascrivi dimensioni schermo predefinite del layout per dispositivi mobili",
    "language": "Imposta la lingua di visualizzazione dell'app",
    "auth": "Autentica un utente automaticamente",
    "linkPreview": "Anteprima collegamento",
    "useShortenLink": "Collegamento breve",
    "shareMapUrlExtent": "Condividi estensione mappa corrente",
    "shareToWebTips": "Questa app non è condivisa con il pubblico. È possibile che le persone non siano in grado di visualizzarla."
  },
  "webSceneLoader": {
    "webglSupportTip": "Le app Web 3D non sono supportate nel browser."
  },
  "map": {
    "basemapNotAvailable": "La mappa di base non è disponibile.",
    "displayDefaultBasemap": "Visualizzare invece la mappa di base predefinita.",
    "layerLoadedError": "Impossibile aggiungere il layer ${layer} alla mappa."
  },
  "popup": {
    "relatedTables": "Tabelle correlate:",
    "relatedRecords": "Record correlati:",
    "noRelatedRecotds": "Nessun record correlato trovato.",
    "chooseFieldTip": "Scegliere un attributo da visualizzare nell'elenco",
    "saveAsPopupTitle": "Uguale a titolo pop-up"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "La selezione include troppe feature. Potrebbe essere necessario molto tempo per recuperarle e visualizzarle sulla mappa.",
    "askForContinue": "Continuare?"
  },
  "colorPalette": {
    "transparent": "Trasparente",
    "custom": "Personalizzata"
  },
  "temperature": {
    "celsius": "Celsius",
    "fahrenheit": "Fahrenheit"
  },
  "report": {
    "printButtonLabel": "Stampa",
    "reportDimensionsMsg": "Questo report è concepito per la stampa su carta ${paperSize}",
    "unableToPrintMapMsg": "Si è verificato un errore durante la stampa della/e mappa/e.",
    "notesHint": "Inserire i commenti qui",
    "landscape": "Paesaggio",
    "portrait": "Ritratto",
    "mapOnly": "SOLO_MAPPA",
    "a0": "A0",
    "a1": "A1",
    "a2": "A2",
    "a3": "A3",
    "a4": "A4",
    "a5": "A5",
    "letterANSIA": "Lettera ANSI A",
    "tabloidANSIB": "Tabloid ANSI B",
    "letter": "Lettera",
    "legal": "Legale",
    "tabloid": "Tabloid",
    "ansi_a": "ANSI A",
    "ansi_b": "ANSI B",
    "ansi_c": "ANSI C",
    "ansi_d": "ANSI D",
    "ansi_e": "ANSI E"
  },
  "snapshot": {
    "snapshot_complete": "Creazione snapshot riuscita.",
    "snapshot_failed": "Impossibile creare istantanea.",
    "snapshot_append": "Snapshot",
    "utc": "UTC"
  },
  "statisticsChart": {
    "enlarge": "Allarga",
    "setting": "Impostazione",
    "count": "Conteggio",
    "horizontalAxis": "Asse orizzontale",
    "verticalAxis": "Asse verticale",
    "dataLabels": "Etichette dati",
    "color": "Colore"
  },
  "frameworkDatasource": {
    "setDataSource": "Imposta origine dati",
    "customDataSource": "Origine dati extra",
    "selectCustomDataTip": "Selezionare un'origine dati da questa app.",
    "widgetOutputs": "Output widget",
    "noExtraDsAvailable": "Nessuna origine dati aggiuntiva disponibile.",
    "addExtraDsTip": "Andare alla scheda Attributi del generatore e fare clic su Origine dati extra per aggiungere dati.",
    "widgetOutpusListTip": "Qui sono elencati anche gli output widget, se presenti."
  },
  "gridLayout": {
    "addWidgetTip": "Aggiungi widget qui dalla scheda Widget",
    "modifyLayout": "Modifica layout",
    "dragToAdd": "Trascina per aggiungere",
    "mapArea": "AREA MAPPA"
  },
  "noEditPrivileges": "L'account non dispone dell'autorizzazione per creare o modificare dati.",
  "invalidConfiguration": "Il widget non è configurato o i layer nella configurazione non sono più presenti nella mappa. Aprire l'app nella modalità generatore e riconfigurare il widget."
});