define({
  "id": "Azonosító",
  "state": "Alapértelmezés szerint a koordináták az aktuális térkép koordináta-rendszere alapján jelennek meg. Más koordináta-rendszerben történő megjelenítéshez adja hozzá a kívánt koordináta-rendszereket, és határozza meg a megfelelő transzformációkat.",
  "outputUnit": "Kimeneti mértékegység",
  "wkid": "Kimeneti WKID",
  "label": "Kimeneti koordináta-rendszer neve",
  "transformationWkid": "Transzformációs WKID",
  "transformationLabel": "Transzformáció felirata",
  "transformForward": "Transzformáció előre",
  "actions": "Műveletek",
  "warning": "Adjon meg érvényes WKID azonosítót a térbeli referenciához!",
  "tfWarning": "Adjon meg érvényes WKID azonosítót a dátumtranszformációhoz!",
  "spinnerLabel": "Koordináták kerekítése: ",
  "decimalPlace": "tizedesjegyre",
  "separator": "Ezreselválasztók megjelenítése",
  "getVersionError": "Nem sikerült beolvasni a geometriai adatszolgáltatás verzióját",
  "add": "Kimeneti koordináta-rendszer hozzáadása",
  "edit": "Koordináta-rendszer szerkesztése",
  "output": "Kimeneti koordináta-rendszer",
  "cName": "Koordináta-rendszer neve",
  "units": "Megjelenítési mértékegységek: ",
  "datum": "Dátumtranszformáció",
  "tName": "Transzformáció neve",
  "tWKIDPlaceHolder": "Transzformáció WKID azonosítója",
  "forward": "Előre történő transzformáció használata",
  "ok": "OK",
  "cancel": "Mégse",
  "olderVersion": "A geometriai adatszolgáltatás nem támogatja a transzformációs műveletet",
  "REPEATING_ERROR": " A koordináta-rendszer szerepel a kimeneti listán.",
  "Default": "Alapértelmezett",
  "Inches": "hüvelyk",
  "Foot": "láb",
  "Yards": "yard",
  "Miles": "mérföld",
  "Nautical_Miles": "tengeri mérföld",
  "Millimeters": "milliméter",
  "Centimeters": "centiméter",
  "Meter": "méter",
  "Kilometers": "kilométer",
  "Decimeters": "deciméter",
  "Decimal_Degrees": "tizedes fok",
  "Degrees_Decimal_Minutes": "Fokok és tizedes fokpercek",
  "Degree_Minutes_Seconds": "Fokok, fokpercek és fokmásodpercek",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Koordináták megjelenítési sorrendje:",
  "lonLatTips": "Hosszúság / szélesség (X, Y)",
  "latLonTips": "Szélesség / hosszúság (Y, X)"
});