define({
  "_widgetLabel": "圖層清單",
  "titleBasemap": "底圖",
  "titleLayers": "操作圖層",
  "labelLayer": "圖層名稱",
  "itemZoomTo": "縮放至",
  "itemTransparency": "透明度",
  "itemTransparent": "透明",
  "itemOpaque": "不透明",
  "itemMoveUp": "上移",
  "itemMoveDown": "下移",
  "itemDesc": "描述",
  "itemDownload": "下載",
  "itemToAttributeTable": "屬性表中的視圖",
  "itemShowItemDetails": "顯示項目詳細資訊",
  "empty": "空",
  "removePopup": "停用快顯視窗",
  "enablePopup": "啟用快顯視窗",
  "turnAllLayersOff": "關閉所有圖層",
  "turnAllLayersOn": "開啟所有圖層",
  "expandAllLayers": "展開所有圖層",
  "collapseAlllayers": "折疊所有圖層",
  "turnAllLabelsOff": "關閉所有標籤",
  "turnAllLabelsOn": "開啟所有標籤",
  "showLabels": "顯示標籤",
  "hideLables": "隱藏標籤"
});