define(
   ({
    id: 'ID',
    state: "Koordinatene vises som standard i koordinatsystemet for gjeldende kart. Hvis vil vil ha koordinater fra andre koordinatsystem, må du legge dem til og angi nødvendige transformasjoner.",
    outputUnit: "Måleenhet på resultat",
    wkid: "Utdata-WKID",
    label: "Koordinatsystemnavn på resultat",
    transformationWkid: "Transformasjon-WKID",
    transformationLabel: "Transformasjonpåskrift",
    transformForward: "Transformer Fremover",
    actions: "Handlinger",
    warning: "Angi en gyldig geografisk referanse-WKID!",
    tfWarning: "Legg inn gyldig datumtransformasjon-WKID!",
    spinnerLabel: "Avrund koordinater til: ",
    decimalPlace: "desimaler",
    separator: "Vis tusenskilletegn",
    getVersionError: "Finner ikke geometritjenestens versjon",

    add: "Legg til koordinatsystem for resultat",
    edit: "Rediger koordinatsystem",
    output: "Koordinatsystem for resultat",
    cName: "Koordinatsystemnavn",
    units: "Visningsenheter: ",
    datum: "Datum-transformasjon",
    tName: "Transformasjonsnavn",
    tWKIDPlaceHolder: "WKID for transformasjonen",
    forward: "Bruk transformasjon fremover",
    ok: "OK",
    cancel: 'Avbryt',
    olderVersion: "Geometritjenesten støtter ikke transformasjonoperasjoner",
    REPEATING_ERROR: " Koordinatsystemet finnes i resultatliste.",

    Default: "Standard",
    Inches: "Tommer",
    Foot: "Fot",
    Yards: "Yards",
    Miles: "Miles",
    Nautical_Miles: "Nautiske mil",
    Millimeters: "Millimeter",
    Centimeters: "Centimeter",
    Meter: "Meter",
    Kilometers: "Kilometer",
    Decimeters: "Desimeter",
    Decimal_Degrees: "Desimalgrader",
    Degree_Minutes_Seconds: "Grader Minutter Sekunder",
    MGRS: "MGRS",
    USNG: "USNG"
  })
);