define(
   ({
    _widgetLabel: "Attributtabel",
    ok: "OK",
    cancel: "Annuller",
    unsupportQueryWarning: "Laget skal understøtte, at forespørgsler bliver vist i attributtabel-widget. Kontrollér, at forespørgselsfunktionen er aktiveret i tjenesten.",
    exportMessage: "Skal dataene eksporteres til en CSV-fil?",
    exportFiles: "Eksportér til CSV",
    exportSelected: "Eksportér markeringen til CSV",
    exportAll: "Eksportér alt til CSV",
    options: "Indstillinger",
    zoomto: "Zoom til",
    highlight: "Fremhæv grafik",
    selectAll: "Markér poster på alle sider",
    selectPage: "Markér poster på den aktuelle side",
    clearSelection: "Ryd markering",
    filter: "Filtrér",
    setFilterTip: "Angiv filteret korrekt.",
    noFilterTip: "Defineres der ikke et filterudtryk, viser denne forespørgsel alle objekter i den angivne datakilde.",
    filterByExtent: "Filtrér efter kortudstrækning",
    showSelectedRecords: "Vis udvalgte poster",
    showAllRecords: "Vis alle poster",
    showRelatedRecords: "Vis relaterede poster",
    noRelatedRecords: "Ingen relaterede poster",
    refresh: "Opdatér",
    features: "objekter",
    selected: "valgt",
    transparent: "Transparent tilstand",
    indicate: "Valg af landeindstillinger",
    columns: "Vis/Skjul kolonner",
    selectionSymbol: "Markeringssymbol",
    closeMessage: "Skjul tabel [Vis den igen nedefra]",
    dataNotAvailable: "Dataene er ikke tilgængelige!<br>Klik på knappen [Opdater] for at prøve igen",
    openTableTip: "Åbn attributtabel",
    closeTableTip: "Skjul attributtabel"
  })
);