define({
  "_widgetLabel": "レイヤー リスト",
  "titleBasemap": "ベースマップ",
  "titleLayers": "操作レイヤー",
  "labelLayer": "レイヤー名",
  "itemZoomTo": "ズーム",
  "itemTransparency": "透過表示",
  "itemTransparent": "透明",
  "itemOpaque": "不透明",
  "itemMoveUp": "上に移動",
  "itemMoveDown": "下に移動",
  "itemDesc": "説明",
  "itemDownload": "ダウンロード",
  "itemToAttributeTable": "属性テーブルの表示",
  "itemShowItemDetails": "アイテムの詳細の表示",
  "empty": "空",
  "removePopup": "ポップアップの無効化",
  "enablePopup": "ポップアップの有効化",
  "turnAllLayersOff": "すべてのレイヤーを非表示",
  "turnAllLayersOn": "すべてのレイヤーを表示",
  "expandAllLayers": "すべてのレイヤーを展開",
  "collapseAlllayers": "すべてのレイヤーをたたむ",
  "turnAllLabelsOff": "すべてのラベルを非表示",
  "turnAllLabelsOn": "すべてのラベルを表示",
  "showLabels": "ラベルを表示",
  "hideLables": "ラベルを非表示"
});