define({
  "_widgetLabel": "Coordenada",
  "hintMessage": "Clique no mapa para obter coordenadas",
  "defaultLabel": "Padrão",
  "realtimeLabel": "Mover mouse para obter coordenadas",
  "computing": "Calculando...",
  "latitudeLabel": "Latitude",
  "longitudeLabel": "Longitude",
  "loading": "carregando...",
  "enableClick": "Clique para habilitar o clique no mapa para obter coordenadas",
  "disableClick": "Clique para desabilitar o clique no mapa para obter coordenadas",
  "Default": "Padrão",
  "Inches": "Polegadas",
  "Foot": "Pés",
  "Yards": "Jardas",
  "Miles": "Milhas",
  "Nautical_Miles": "Milhas náuticas",
  "Millimeters": "Milímetros",
  "Centimeters": "Centímetros",
  "Meter": "Metros",
  "Kilometers": "Quilômetros",
  "Decimeters": "Decímetros",
  "Decimal_Degrees": "Graus",
  "Degree_Minutes_Seconds": "Graus minutos segundos",
  "MGRS": "MGRS",
  "USNG": "USNG"
});