define(
   ({
    "sourceSetting": "Otsinguallika seaded",
    "instruction": "Lisa ja seadista geokodeerimise teenuseid või objektikihte otsinguallikatena. Need allikad määravad, mis info on leitav otsingukasti kaudu.",
    "add": "Määra otsinguallikas",
    "addGeocoder": "Lisa geokodeerija",
    "geocoder": "Geokodeerija",
    "setLayerSource": "Määra kihi allikas",
    "setGeocoderURL": "Määra geokodeerija URL",
    "searchableLayer": "Objektikiht",
    "name": "Nimi",
    "countryCode": "Riigi või piirkonna kood(id)",
    "countryCodeEg": "nt ",
    "countryCodeHint": "Kui jätate selle välja tühjaks, teostatakse otsing kõikides riikides ja piirkondades",
    "generalSetting": "Üldseaded",
    "allPlaceholder": "Kohatäitetekst kõigi otsimiseks: ",
    "showInfoWindowOnSelect": "Kuva leitud objekti või asukoha hüpikaken",
    "searchInCurrentMapExtent": "Otsi ainult praegusest kaardiulatusest",
    "locatorUrl": "Geokodeerija URL",
    "locatorName": "Geokodeerija nimi",
    "locatorExample": "Näide",
    "locatorWarning": "Seda geokodeermise teenuse versiooni ei toetata. Vidin toetab geokodeerimise teenust alates 00.0 ja uuemates versioonides.",
    "locatorTips": "Soovitused pole saadaval, sest geokodeerimisteenus ei toeta soovituste võimalust.",
    "layerSource": "Kihi allikas",
    "searchLayerTips": "Soovitused pole saadaval, sest objektiteenus ei toeta leheküljelise jaotuse võimalust.",
    "placeholder": "Kohatäitja tekst",
    "searchFields": "Otsinguväljad",
    "displayField": "Kuvamisväli",
    "exactMatch": "Täpne vaste",
    "maxResults": "Maksimaalsed tulemused",
    "setSearchFields": "Määra otsinguväljad",
    "set": "Määra",
    "fieldSearchable": "otsitav",
    "fieldName": "Nimi",
    "fieldAlias": "Alias",
    "ok": "OK",
    "cancel": "Tühista",
    "invalidUrlTip": "Sisestatud URL ei sobi või pole kättesaadav."
  })
);