define({
  "sourceSetting": "Otsinguallika seaded",
  "instruction": "Lisa ja seadista geokodeerimise teenuseid või objektikihte otsinguallikatena. Need allikad määravad, mis info on leitav otsingukasti kaudu.",
  "add": "Lisa otsinguallikas",
  "addGeocoder": "Lisa geokodeerija",
  "geocoder": "Geokodeerija",
  "setLayerSource": "Määra kihi allikas",
  "setGeocoderURL": "Määra geokodeerija URL",
  "searchableLayer": "Objektikiht",
  "name": "Nimi",
  "countryCode": "Riigi või piirkonna kood(id)",
  "countryCodeEg": "nt ",
  "countryCodeHint": "Kui jätate selle välja tühjaks, teostatakse otsing kõikides riikides ja piirkondades",
  "generalSetting": "Üldseaded",
  "allPlaceholder": "Kohatäite tekst kõigi otsimiseks: ",
  "showInfoWindowOnSelect": "Kuva leitud objekti või asukoha hüpikaken",
  "searchInCurrentMapExtent": "Otsi ainult praegusest kaardiulatusest",
  "zoomScale": "Suumiskaala",
  "locatorUrl": "Geokodeerija URL",
  "locatorName": "Geokodeerija nimi",
  "locatorExample": "Näide",
  "locatorWarning": "Seda geokodeerimisteenuse versiooni ei toetata. Vidin toetab geokodeerimisteenust alates versioonist 10.1 ja uuemates versioonides.",
  "locatorTips": "Soovitused pole saadaval, sest geokodeerimisteenus ei toeta soovituste võimalust.",
  "layerSource": "Kihi allikas",
  "searchLayerTips": "Soovitused pole saadaval, sest objektiteenus ei toeta leheküljelise jaotuse võimalust.",
  "placeholder": "Kohatäitja tekst",
  "searchFields": "Otsinguväljad",
  "displayField": "Kuvamise väli",
  "exactMatch": "Täpne vaste",
  "maxSuggestions": "Maksimaalsed soovitused",
  "maxResults": "Maksimaalsed tulemused",
  "enableLocalSearch": "Luba kohalik otsing",
  "minScale": "Min mõõtkava",
  "minScaleHint": "Kui kaardi mõõkava on sellest mõõtkavast suurem, rakendatakse kohalik otsing",
  "radius": "Raadius",
  "radiusHint": "Määrab praeguse kaardi keskpunkti ümber asuva ala raadiuse, mida kasutatakse geokodeerimise kandidaatide järjestuse võimendamiseks nii, et asukohale lähimad kandidaadid tagastatakse esimesena",
  "meters": "Meetrit",
  "setSearchFields": "Määra otsinguväljad",
  "set": "Määra",
  "fieldSearchable": "otsitav",
  "fieldName": "Nimi",
  "fieldAlias": "Alias",
  "ok": "OK",
  "cancel": "Tühista",
  "invalidUrlTip": "URL ${URL} ei sobi või pole kättesaadav."
});