define({
  "instruction": "La pantalla de presentación aparece antes de que se pueda acceder a la aplicación.",
  "defaultContent": "Agrega texto, vínculos y pequeños gráficos aquí.",
  "requireConfirm": "Requiere confirmación para continuar",
  "noRequireConfirm": "No se requiere confirmación para continuar",
  "optionText": "Opción que permite al usuario deshabilitar la pantalla de presentación al iniciar la aplicación.",
  "confirmLabel": "Textos de confirmación: ",
  "confirmLabelColor": "Color de textos de confirmación",
  "defaultConfirmText": "Acepto los términos y las condiciones anteriores",
  "confirmOption": "Mostrar esta pantalla de presentación cada vez que se inicie la aplicación",
  "backgroundColor": "Color de Fondo",
  "content": "Contenido",
  "contentDescription": "Defina el contenido que se muestra en la pantalla de presentación.",
  "appearance": "Apariencia",
  "appearanceDescription": "Establezca la apariencia de la pantalla de presentación.",
  "size": "Tamaño",
  "width": "Ancho",
  "height": "Altura",
  "custom": "Personalizada",
  "background": "Fondo",
  "colorFill": "Relleno de color",
  "imageFill": "Relleno de imagen",
  "chooseFile": "Elegir archivo",
  "noFileChosen": "No se ha seleccionado ningún archivo",
  "transparency": "Transparencia",
  "sizeFill": "Relleno",
  "sizeFit": "Ajustar",
  "sizeStretch": "Expandir a relleno",
  "sizeCenter": "Centro",
  "sizeTile": "Tesela",
  "buttonColor": "Color de botón",
  "buttonText": "Texto de botón",
  "buttonTextColor": "Color de texto de botón",
  "contentAlign": "Alineación del contenido",
  "alignTop": "Superior",
  "alignMiddle": "Medio",
  "maskColor": "Color de máscara",
  "options": "Opciones",
  "optionsDescription": "Establezca el comportamiento de la pantalla de presentación."
});