define({
  root: ({
    "sourceSetting": "Search Source Settings",
    "instruction": "Add and configure geocode services or feature layers as search sources. These specified sources determine what is searchable within the search box.",
    "add": "Add Search Source",
    "addGeocoder": "Add Geocoder",
    "geocoder": "Geocoder",
    "setLayerSource": "Set Layer Source",
    "setGeocoderURL": "Set Geocoder URL",
    "searchableLayer": "Feature Layer",
    "name": "Name",
    "countryCode": "Country or Region Code(s)",
    "countryCodeEg": "e.g. ",
    "countryCodeHint": "Leaving this value blank will search all countries and regions",
    "generalSetting": "General Settings",
    "allPlaceholder": "Placeholder text for searching all: ",
    "showInfoWindowOnSelect": "Show pop-up for the found feature or location",
    "searchInCurrentMapExtent": "Only search in current map extent",
    "locatorUrl": "Geocoder URL",
    "locatorName": "Geocoder Name",
    "locatorExample": "Example",
    "locatorWarning": "This version of geocoding service is not supported. The widget supports geocoding service 00.0 and above.",
    "locatorTips": "Suggestions are not available because the geocoding service doesn't support suggest capability.",
    "layerSource": "Layer Source",
    "searchLayerTips": "Suggestions are not available because the feature service doesn't support pagination capability.",
    "placeholder": "Placeholder Text",
    "searchFields": "Search Fields",
    "displayField": "Display Field",
    "exactMatch": "Exact Match",
    "maxResults": "Maximum Results",
    "setSearchFields": "Set Search Fields",
    "set": "Set",
    "fieldSearchable": "searchable",
    "fieldName": "Name",
    "fieldAlias": "Alias",
    "ok": "OK",
    "cancel": "Cancel",
    "invalidUrlTip": "The URL you have entered is invalid or inaccessible."
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});