define({
  "sourceSetting": "Paramètres de source de recherche",
  "instruction": "Ajoutez et configurez des services de géocodage ou des couches d’entités en tant que sources de recherche. Ces sources déterminent les éléments pouvant faire l’objet d’une recherche dans la zone de recherche.",
  "add": "Ajouter une source de recherche",
  "addGeocoder": "Ajouter un géocodeur",
  "geocoder": "Géocodeur",
  "setLayerSource": "Définir une source de couche",
  "setGeocoderURL": "Définir l'URL du géocodeur",
  "searchableLayer": "Couche d'entités",
  "name": "Nom",
  "countryCode": "Codes de pays ou de régions",
  "countryCodeEg": "par ex. ",
  "countryCodeHint": "Si cette valeur n'est pas renseignée, la recherche s'effectue dans tous les pays et toutes les régions",
  "generalSetting": "paramètres généraux",
  "allPlaceholder": "Texte d'espace réservé pour tout parcourir : ",
  "showInfoWindowOnSelect": "Afficher la fenêtre contextuelle de l'entité ou de l'emplacement trouvé",
  "searchInCurrentMapExtent": "Rechercher uniquement dans l'étendue de la carte actuelle",
  "zoomScale": "Echelle de zoom",
  "locatorUrl": "URL du géocodeur",
  "locatorName": "Nom du géocodeur",
  "locatorExample": "Exemple",
  "locatorWarning": "Cette version du service de géocodage n'est pas prise en charge. Le widget prend en charge le service de géocodage version 10.1 et ultérieures.",
  "locatorTips": "Les suggestions ne sont pas disponibles, car le service de géocodage ne prend pas en charge la fonction de suggestion.",
  "layerSource": "Source de la couche",
  "searchLayerTips": "Les suggestions ne sont pas disponibles, car le service d'entités ne prend pas en charge la fonction de pagination.",
  "placeholder": "Texte de l'espace réservé",
  "searchFields": "Champs de recherche",
  "displayField": "Champ d’affichage",
  "exactMatch": "Correspondance parfaite",
  "maxSuggestions": "Nombre maximal de suggestions",
  "maxResults": "Nombre maximal de résultats",
  "enableLocalSearch": "Activer la recherche locale",
  "minScale": "Echelle min.",
  "minScaleHint": "Lorsque l'échelle de la carte est supérieure à cette échelle, la recherche locale est appliquée",
  "radius": "Rayon",
  "radiusHint": "Indique le rayon d'une surface autour du centre de la carte qui permet d'optimiser le classement des candidats de géocodage, afin que les plus proches de l'emplacement soient renvoyés en premier",
  "meters": "Mètres",
  "setSearchFields": "Définir les champs de recherche",
  "set": "Définir",
  "fieldSearchable": "Peut faire l'objet d’une recherche",
  "fieldName": "Nom",
  "fieldAlias": "Alias",
  "ok": "OK",
  "cancel": "Annuler",
  "invalidUrlTip": "L’URL ${URL} est incorrecte ou inaccessible."
});