define(
   ({
    "sourceSetting": "Paramètres de la source de recherche",
    "instruction": "Ajoutez et configurez des services de géocodage ou des couches d\'entités en tant que source de recherche. Ces sources spécifiées déterminent ce qui peut faire l\'objet d\'une recherche au sein de la zone de recherche.",
    "add": "Ajouter une source de recherche",
    "addGeocoder": "Ajouter un géocodeur",
    "geocoder": "Géocodeur",
    "setLayerSource": "Définir la source de la couche",
    "setGeocoderURL": "Définir l\'URL du géocodeur",
    "searchableLayer": "Couche d\'entités",
    "name": "Nom",
    "countryCode": "Codes de pays ou de régions",
    "countryCodeEg": "par ex. ",
    "countryCodeHint": "Si cette valeur n\'est pas renseignée, la recherche s\'effectue dans tous les pays et toutes les régions",
    "generalSetting": "Paramètres généraux",
    "allPlaceholder": "Texte d\'espace réservé pour tout parcourir : ",
    "showInfoWindowOnSelect": "Afficher la fenêtre contextuelle de l\'entité ou de l\'emplacement trouvé",
    "searchInCurrentMapExtent": "Rechercher uniquement dans l\'étendue de la carte actuelle",
    "locatorUrl": "URL du géocodeur",
    "locatorName": "Nom du géocodeur",
    "locatorExample": "Exemple",
    "locatorWarning": "Cette version du service de géocodage n\'est pas prise en charge. Le widget prend en charge le service de géocodage 00.0 et version supérieure.",
    "locatorTips": "Les suggestions ne sont pas disponibles, car le service de géocodage ne prend pas en charge la fonction de suggestion.",
    "layerSource": "Source de la couche",
    "searchLayerTips": "Les suggestions ne sont pas disponibles, car le service d\'entités ne prend pas en charge la fonction de pagination.",
    "placeholder": "Texte de l\'espace réservé",
    "searchFields": "Champs de recherche",
    "displayField": "Champ d\'affichage",
    "exactMatch": "Correspondance parfaite",
    "maxResults": "Nombre maximum de résultats",
    "setSearchFields": "Définir les champs de recherche",
    "set": "Définir",
    "fieldSearchable": "Peut faire l\'objet d’une recherche",
    "fieldName": "Nom",
    "fieldAlias": "Alias",
    "ok": "OK",
    "cancel": "Annuler",
    "invalidUrlTip": "L\'URL que vous avez saisie est incorrecte ou inaccessible."
  })
);