define({
  root: ({
    id: 'ID',
    state: "By default, coordinates will display in current map’s coordinate system. To get coordinates in other coordinate systems, you need to add them and specify appropriate transformations.",
    outputUnit: "Output unit",
    wkid: "Output WKID",
    label: "Output coordinate system name",
    transformationWkid: "Transformation WKID",
    transformationLabel: "Transformation label",
    transformForward: "Transform forward",
    actions: "Actions",
    warning: "Please input valid spatial reference WKID!",
    tfWarning: "Please input valid datum transformation WKID!",
    spinnerLabel: "Round coordinates to: ",
    decimalPlace: "decimal places",
    separator: "Show thousand separators",
    getVersionError: "Can't get the version of geometry service",

    add: "Add output coordinate system",
    edit: "Edit coordinate system",
    output: "Output coordinate system",
    cName: "Coordinate system name",
    units: "Display units: ",
    datum: "Datum transformation",
    tName: "Transformation name",
    tWKIDPlaceHolder: "WKID of the transformation",
    forward: "Use transformation forward",
    ok: "OK",
    cancel: 'Cancel',
    olderVersion: "The geometry service doesn't support transforming operation",
    REPEATING_ERROR: " Coordinate system exists in the output list.",

    Default: "Default",
    Inches: "Inches",
    Foot: "Feet",
    Yards: "Yards",
    Miles: "Miles",
    Nautical_Miles: "Nautical miles",
    Millimeters: "Millimeters",
    Centimeters: "Centimeters",
    Meter: "Meters",
    Kilometers: "Kilometers",
    Decimeters: "Decimeters",
    Decimal_Degrees: "Decimal degrees",
    Degrees_Decimal_Minutes: "Degrees decimal minutes",
    Degree_Minutes_Seconds: "Degrees minutes seconds",
    MGRS: "MGRS",
    USNG: "USNG",

    displayOrderLonLatTips: "Coordinates display order:",
    lonLatTips: "Longitude / Latitude(X, Y)",
    latLonTips: "Latitude / Longitude(Y, X)"
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});