define({
  "instruction": "Pozdravni zaslon prikazuje se prije nego što aplikacija postane dostupna.",
  "defaultContent": "Ovdje dodajte tekst, poveznice i male grafičke elemente.",
  "requireConfirm": "Potrebna je potvrda za nastavak",
  "noRequireConfirm": "Nije potrebna potvrda za nastavak",
  "optionText": "Korisnička opcija za onemogućavanje pozdravnog zaslona pri pokretanju aplikacije.",
  "confirmLabel": "Tekstovi potvrde: ",
  "confirmLabelColor": "Boja tekstova potvrde",
  "defaultConfirmText": "Prihvaćam prethodno navedene uvjete i odredbe",
  "confirmOption": "Uvijek prikaži pozdravni zaslon svaki put kad se app pokrene",
  "backgroundColor": "Boja pozadine",
  "content": "Sadržaj",
  "contentDescription": "Definirajte sadržaj koji se prikazuje na pozdravnom zaslonu.",
  "appearance": "Izgled",
  "appearanceDescription": "Postavite izgled pozdravnog zaslona.",
  "size": "Veličina",
  "width": "Širina",
  "height": "Visina",
  "custom": "Prilagođeno",
  "background": "Pozadina",
  "colorFill": "Ispuna boje",
  "imageFill": "Ispuna slike",
  "chooseFile": "Izaberi datoteku",
  "noFileChosen": "Nije izabrana datoteka",
  "transparency": "Prozirnost",
  "sizeFill": "Ispuna",
  "sizeFit": "Prilagodi",
  "sizeStretch": "Rastegni za ispunu",
  "sizeCenter": "Središte",
  "sizeTile": "Ploča",
  "buttonColor": "Boja gumba",
  "buttonText": "Tekst gumba",
  "buttonTextColor": "Boja teksta gumba",
  "contentAlign": "Poravnanje sadržaja",
  "alignTop": "Vrh",
  "alignMiddle": "Sredina",
  "maskColor": "Boja maske",
  "options": "Opcije",
  "optionsDescription": "Postavite ponašanje pozdravnog zaslona."
});