define({
  "_widgetLabel": "Koordinate",
  "hintMessage": "Zum Abrufen von Koordinaten auf die Karte klicken",
  "defaultLabel": "Standard",
  "realtimeLabel": "Maus zum Abrufen von Koordinaten auf der Karte bewegen",
  "computing": "Wird berechnet...",
  "latitudeLabel": "Breitengrad",
  "longitudeLabel": "Längengrad",
  "loading": "wird geladen...",
  "enableClick": "Klicken Sie, um das Abrufen von Koordinaten durch Klicken auf die Karte zu aktivieren",
  "disableClick": "Klicken Sie, um das Abrufen von Koordinaten durch Klicken auf die Karte zu deaktivieren",
  "Default": "Standard",
  "Inches": "Zoll",
  "Foot": "Fuß",
  "Yards": "Yard",
  "Miles": "Meilen",
  "Nautical_Miles": "Seemeilen",
  "Millimeters": "Millimeter",
  "Centimeters": "Zentimeter",
  "Meter": "Meter",
  "Kilometers": "Kilometer",
  "Decimeters": "Dezimeter",
  "Decimal_Degrees": "Grad",
  "Degree_Minutes_Seconds": "Grad, Minuten, Sekunden",
  "MGRS": "MGRS",
  "USNG": "USNG"
});