define({
  "instruction": "属性テーブルに最初に表示されるレイヤーを選択して構成します。",
  "label": "レイヤー",
  "show": "表示",
  "actions": "レイヤー フィールドの構成",
  "field": "フィールド",
  "alias": "エイリアス",
  "visible": "表示",
  "linkField": "リンク フィールド",
  "noLayers": "使用できるフィーチャ レイヤーはありません",
  "back": "戻る",
  "exportCSV": "CSV へのエクスポートを許可",
  "expand": "初期画面よりウィジェットを表示",
  "filterByExtent": "デフォルトでマップ範囲によるフィルターを有効化します",
  "restore": "デフォルト値に戻す",
  "ok": "OK",
  "cancel": "キャンセル",
  "includePoint": "ポイントの座標をエクスポートされたファイルに含めます",
  "configureLayerFields": "レイヤー フィールドの構成",
  "result": "正常に保存されました",
  "warning": "最初に [表示] オプションを選択してください。",
  "fieldCheckWarning": "最低 1 つのフィールドを選択する必要があります。",
  "unsupportQueryWarning": "レイヤーを属性テーブル ウィジェットで表示するには、レイヤーがクエリ操作をサポートしている必要があります。サービスのクエリ機能が有効化されていることを確認してください。",
  "unsupportQueryLayers": "次のレイヤーを属性テーブル ウィジェットで表示するには、レイヤーがクエリ操作をサポートしている必要があります。サービスのクエリ機能が有効化されていることを確認してください。",
  "fieldName": "名前",
  "fieldAlias": "エイリアス",
  "fieldVisibility": "表示設定",
  "fieldActions": "アクション",
  "showAttachments": "添付ファイルの表示"
});