define({
  "instruction": "アプリケーションが使用可能になる前にスプラッシュ画面が表示されます。",
  "defaultContent": "テキスト、リンク、および小さなグラフィックスをここに追加します。",
  "requireConfirm": "続行するには確認が必要です",
  "noRequireConfirm": "確認なしでも続行できます",
  "optionText": "アプリケーションの起動時にユーザーがスプラッシュ スクリーンを無効にするオプション。",
  "confirmLabel": "確認のテキスト: ",
  "confirmLabelColor": "確認用テキストの色",
  "defaultConfirmText": "上記の利用条件に同意します",
  "confirmOption": "アプリが起動するたびに、必ずこのスプラッシュ スクリーンを表示します。",
  "backgroundColor": "背景色",
  "content": "コンテンツ",
  "contentDescription": "スプラッシュ画面に表示されるコンテンツを定義します。",
  "appearance": "表示設定",
  "appearanceDescription": "スプラッシュ画面の外観を設定します。",
  "size": "サイズ",
  "width": "幅",
  "height": "高さ",
  "custom": "カスタム",
  "background": "背景",
  "colorFill": "カラー塗りつぶし",
  "imageFill": "画像塗りつぶし",
  "chooseFile": "ファイルの選択",
  "noFileChosen": "ファイルが選択されていません",
  "transparency": "透過表示",
  "sizeFill": "塗りつぶし",
  "sizeFit": "調整",
  "sizeStretch": "引き伸ばして塗りつぶし",
  "sizeCenter": "中央",
  "sizeTile": "タイル",
  "buttonColor": "ボタンの色",
  "buttonText": "ボタンのテキスト",
  "buttonTextColor": "ボタンのテキスト色",
  "contentAlign": "コンテンツの配置",
  "alignTop": "上",
  "alignMiddle": "中",
  "maskColor": "マスク色",
  "options": "オプション",
  "optionsDescription": "スプラッシュ画面の振舞いを設定します。"
});