define({
  "sourceSetting": "Pesquisar definições de origem",
  "instruction": "Adicionar e configurar serviços de geocodificação ou camadas de elemento como fontes de pesquisa. Estas fontes especificadas determinam o que é pesquisável dentro da caixa de pesquisa.",
  "add": "Adicionar origem de pesquisa",
  "addGeocoder": "Adicionar geocodificador",
  "geocoder": "Geocodificador",
  "setLayerSource": "Definir origem da camada",
  "setGeocoderURL": "Definir URL do geocodificador",
  "searchableLayer": "Camada de elementos",
  "name": "Nome",
  "countryCode": "Código(s) de país ou região",
  "countryCodeEg": "e.g ",
  "countryCodeHint": "Ao deixar este valor em branco irá pesquisar em todos os países e regiões",
  "generalSetting": "Configurações gerais",
  "allPlaceholder": "Texto de placeholder para pesquisar todos: ",
  "showInfoWindowOnSelect": "Exibir janela pop-up para o elemento ou local encontrado.",
  "searchInCurrentMapExtent": "Procurar apenas na extensão de mapa actual.",
  "zoomScale": "Escala de zoom",
  "locatorUrl": "Geocoder URL",
  "locatorName": "Nome do geocodificador",
  "locatorExample": "Exemplo",
  "locatorWarning": "Esta versão do serviço de geocodificação não é suportada. O widget suporta serviço de geocodificação 10.1 e posterior.",
  "locatorTips": "Sugestões não estão disponíveis porque o serviço de geocodificação não suporta a capacidade sugerida.",
  "layerSource": "Origem de camada",
  "searchLayerTips": "Sugestões não estão disponíveis porque o serviço de elemento não suporta capacidades de paginação.",
  "placeholder": "Espaço reservado a texto",
  "searchFields": "Campos de pesquisa",
  "displayField": "Campo de visualização",
  "exactMatch": "Correspondência exata",
  "maxSuggestions": "Máximo de sugestões",
  "maxResults": "Máximo de resultados",
  "enableLocalSearch": "Ativar pesquisa local",
  "minScale": "Escala mínima",
  "minScaleHint": "Quando a escala do mapa é superior a esta escala, será aplicada a pesquisa local",
  "radius": "Raio",
  "radiusHint": "Especifica o raio de uma área em torno do atual centro do mapa, que é utilizada para impulsionar a classificação de candidatos a geocodificação para que os candidatos que se encontram mais perto do local sejam apresentados nas primeiras posições.",
  "meters": "Metros",
  "setSearchFields": "Definir campos de pesquisa",
  "set": "Definir",
  "fieldSearchable": "pesquisável",
  "fieldName": "Nome",
  "fieldAlias": "Nome Alternativo",
  "ok": "OK",
  "cancel": "Cancelar",
  "invalidUrlTip": "O URL ${URL} é inválido ou inacessível."
});