define({
  "sourceSetting": "Sök källinställningar",
  "instruction": "Lägg till och konfigurera geokodningstjänster eller geoobjektslager som sökkällor. Dessa angivna källor avgör vad som går att söka i sökrutan.",
  "add": "Lägg till sökkälla",
  "addGeocoder": "Lägg till geokodare",
  "geocoder": "Geokodare",
  "setLayerSource": "Ange lagerkälla",
  "setGeocoderURL": "Ange URL till geokodare",
  "searchableLayer": "Geoobjektslager",
  "name": "Namn",
  "countryCode": "Lands- eller regionkoder",
  "countryCodeEg": "till exempel ",
  "countryCodeHint": "Om du lämnar det här värdet tomt sker sökningen i alla länder och regioner",
  "generalSetting": "Allmänna inställningar",
  "allPlaceholder": "Platshållartext för sökning i alla: ",
  "showInfoWindowOnSelect": "Visa popup för det hittade geoobjekt eller den hittade platsen",
  "searchInCurrentMapExtent": "Sök bara i den aktuella kartutbredningen",
  "zoomScale": "Zoomningsskala",
  "locatorUrl": "Geokodarens URL",
  "locatorName": "Geokodarens namn",
  "locatorExample": "Exempel",
  "locatorWarning": "Den här versionen av geokodningstjänsten stöds inte. Widgeten har stöd för geokodningstjänsten 10.1 och högre.",
  "locatorTips": "Förslag finns inte tillgängliga eftersom geokodningstjänsten inte har stöd för förslagsfunktionen.",
  "layerSource": "Lagerkälla",
  "searchLayerTips": "Förslag finns inte tillgängliga eftersom geoobjektstjänsten inte har stöd för pagineringsfunktionen.",
  "placeholder": "Platshållartext",
  "searchFields": "Sökfält",
  "displayField": "Visningsfält",
  "exactMatch": "Exakt matchning",
  "maxSuggestions": "Maximalt antal förslag",
  "maxResults": "Maximalt antal resultat",
  "enableLocalSearch": "Aktivera lokal sökning",
  "minScale": "Minimiskala",
  "minScaleHint": "När kartans skala är större än denna skala används lokal sökning",
  "radius": "Radie",
  "radiusHint": "Anger radien för ett område kring den aktuella kartans mitt som ska användas för att höja rangordningen för geokodningskandidater så att de kandidater som är närmast platsen returneras först",
  "meters": "Meter",
  "setSearchFields": "Ange sökfält",
  "set": "Ange",
  "fieldSearchable": "sökbar",
  "fieldName": "Namn",
  "fieldAlias": "Alias",
  "ok": "OK",
  "cancel": "Avbryt",
  "invalidUrlTip": "URL:en ${URL} är ogiltig eller går inte att öppna."
});