define({
  "common": {
    "apply": "Anvend",
    "ok": "OK",
    "cancel": "Annuller",
    "yes": "Ja",
    "no": "Nej",
    "next": "Næste",
    "previous": "Forrige",
    "back": "Tilbage",
    "selected": "valgt",
    "name": "Navn",
    "usage": "Brug",
    "settings": "Indstillinger",
    "home": "Hjem",
    "link": "Link",
    "messages": "Meddelelser",
    "outputs": "Output",
    "title": "Titel",
    "thumbnail": "Miniaturebillede",
    "url": "URL",
    "actions": "Handlinger",
    "layer": "Lag",
    "action": "Handling",
    "input": "Input",
    "output": "Output",
    "type": "Type",
    "required": "Krævet",
    "options": "Indstillinger",
    "label": "Mærke",
    "tooltip": "Værktøjstip",
    "visible": "Synlig",
    "symbol": "Symbol",
    "popup": "Pop-up",
    "upload": "Overfør",
    "execute": "Udfør",
    "help": "Hjælp",
    "executing": "Udfører",
    "clear": "Ryd",
    "error": "Fejl",
    "zoomTo": "Zoom til",
    "attribute": "Attribut",
    "exports": "Eksportér",
    "check": "Kontrollér",
    "save": "Gem",
    "close": "Luk",
    "deleteText": "Slet",
    "map": "Kort",
    "scene": "Scene",
    "reset": "Nulstil",
    "icon": "Ikon",
    "folder": "Mappe",
    "share": "Opdatér",
    "view": "Vis",
    "newText": "Ny",
    "edit": "Redigér",
    "wkid": "WKID",
    "table": "Tabel",
    "zoomIn": "Zoom ind",
    "zoomOut": "Zoom ud",
    "continue1": "Fortsæt",
    "longitude": "Længde",
    "latitude": "Bredde",
    "custom": "Brugerdefineret",
    "image": "Billede",
    "font": "Skrifttype",
    "text": "Tekst",
    "all": "Alle",
    "number": "Nummer",
    "percentage": "procentdel",
    "unit": "Enhed",
    "thousand": "Tusind",
    "billion": "Milliard",
    "million": "Million",
    "none": "Ingen",
    "field": "Felt",
    "operation": "Handling",
    "disableUpdateGeometry": "Deaktiver Opdatér geomatri",
    "preview": "Forhåndsvisning"
  },
  "errorCode": "Kode",
  "errorMessage": "Meddelelse",
  "errorDetail": "Detalje",
  "widgetPlaceholderTooltip": "Gå til Widgets. og klik på den tilhørende pladsholder, for at oprette den",
  "fieldStatistics": {
    "selectField": "Vælg felt",
    "statistics": "Statistik",
    "field": "Mark",
    "count": "Antal værdier",
    "sum": "Summen af værdier",
    "min": "Minimum",
    "max": "Maksimum",
    "ave": "Gennemsnit",
    "stddev": "Standardafvigelse"
  },
  "symbolChooser": {
    "preview": "Eksempel",
    "basic": "Grundlæggende principper",
    "arrows": "Pile",
    "business": "Forretning",
    "cartographic": "Kartografisk",
    "nationalParkService": "Nationalparkforvaltning",
    "outdoorRecreation": "Udendørs rekreation",
    "peoplePlaces": "Offentlige steder",
    "safetyHealth": "Sikkerhed og sundhed",
    "shapes": "Former",
    "transportation": "Transport",
    "symbolSize": "Symbolstørrelse",
    "color": "Farve",
    "alpha": "Alfa",
    "outlineColor": "Konturfarve",
    "outlineWidth": "Kantbredde",
    "style": "Typografi",
    "width": "Bredde",
    "text": "Tekst",
    "fontColor": "Skriftfarve",
    "fontSize": "Skriftstørrelse",
    "transparency": "Gennemsigtighed",
    "solid": "Udfyldt",
    "dash": "Streg",
    "dot": "Punktum",
    "dashDot": "Streg-prik",
    "dashDotDot": "Streg-prik-prik",
    "customImage": "Brugerdefineret billede",
    "chooseFile": "Vælg fil",
    "noFileChoosen": "Der er ikke valgt nogen fil."
  },
  "transparency": {
    "opaque": "Uigennemsigtig",
    "transparent": "Gennemsigtig"
  },
  "rendererChooser": {
    "domain": "Domæne",
    "use": "Brug",
    "singleSymbol": "Et enkelt symbol",
    "uniqueSymbol": "Unikke symboler",
    "color": "Farve",
    "size": "Størrelse",
    "toShow": "At vise",
    "colors": "Farver",
    "classes": "Klasser",
    "symbolSize": "Symbolstørrelse",
    "addValue": "Tilføj værdi",
    "setDefaultSymbol": "Indstil standardsymbol",
    "defaultSymbol": "Standardsymbol",
    "selectedSymbol": "Valgt symbol",
    "value": "Værdi",
    "label": "Mærke",
    "range": "Interval"
  },
  "drawBox": {
    "point": "Punkt",
    "line": "Linje",
    "polyline": "Polylinje",
    "freehandPolyline": "Frihåndspolylinje",
    "triangle": "Triangel",
    "extent": "Område",
    "circle": "Cirkel",
    "ellipse": "Ellipse",
    "polygon": "Polygon",
    "freehandPolygon": "Frihåndspolygon",
    "text": "Tekst",
    "clear": "Ryd"
  },
  "popupConfig": {
    "title": "Titel",
    "add": "Tilføj",
    "fields": "Felter",
    "noField": "Intet felt",
    "visibility": "Synlig",
    "name": "Navn",
    "alias": "Alias",
    "actions": "Handlinger"
  },
  "includeButton": {
    "include": "Medtag"
  },
  "loadingShelter": {
    "loading": "Indlæser"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Der blev ikke fundet nogen tjenester.",
    "unableConnectTo": "Der kunne ikke oprettes forbindelse til",
    "invalidUrlTip": "Den URL, du har angivet, er ugyldig eller utilgængelig."
  },
  "serviceBrowser": {
    "noGpFound": "Der blev ikke fundet nogen geoprocesseringstjenester.",
    "unableConnectTo": "Der kunne ikke oprettes forbindelse til"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Der blev ikke fundet nogen kort- eller featuretjenester",
    "unableConnectTo": "Der kunne ikke oprettes forbindelse til"
  },
  "basicServiceChooser": {
    "validate": "Bekræft",
    "example": "Eksempel",
    "set": "Indstil"
  },
  "urlInput": {
    "invalidUrl": "Ugyldig URL."
  },
  "urlComboBox": {
    "invalidUrl": "Ugyldig URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Tilføj et udtryk",
    "addSet": "Tilføj et sæt",
    "matchMsg": "Hent objekter i det lag, der passer til ${any_or_all} af følgende udtryk",
    "matchMsgSet": "${any_or_all} af følgende udtryk i dette sæt er sande",
    "all": "Alle",
    "any": "Hvilket som helst",
    "value": "Værdi",
    "field": "Felt",
    "unique": "Unik",
    "none": "Ingen",
    "and": "og",
    "valueTooltip": "Angiv værdi",
    "fieldTooltip": "Pluk fra eksisterende felt",
    "uniqueValueTooltip": "Pluk fra unikke værdier i det valgte felt",
    "stringOperatorIs": "er",
    "stringOperatorIsNot": "er ikke",
    "stringOperatorStartsWith": "starter med",
    "stringOperatorEndsWith": "slutter med",
    "stringOperatorContains": "indeholder",
    "stringOperatorDoesNotContain": "indeholder ikke",
    "stringOperatorIsBlank": "er tomt",
    "stringOperatorIsNotBlank": "er ikke tomt",
    "dateOperatorIsOn": "er d.",
    "dateOperatorIsNotOn": "er ikke d.",
    "dateOperatorIsBefore": "er før",
    "dateOperatorIsAfter": "er efter",
    "dateOperatorIsOnOrBefore": "er på eller før",
    "dateOperatorIsOnOrAfter": "er på eller efter",
    "dateOperatorMinutes": "minutter",
    "dateOperatorHours": "timer",
    "dateOperatorDays": "dage",
    "dateOperatorWeeks": "uger",
    "dateOperatorMonths": "måneder",
    "dateOperatorYears": "år",
    "dateOperatorInTheLast": "i de seneste",
    "dateOperatorNotInTheLast": "ikke i de seneste",
    "dateOperatorIsBetween": "er mellem",
    "dateOperatorIsNotBetween": "er ikke mellem",
    "dateOperatorIsBlank": "er tomt",
    "dateOperatorIsNotBlank": "er ikke tomt",
    "numberOperatorIs": "er",
    "numberOperatorIsNot": "er ikke",
    "numberOperatorIsAtLeast": "er mindst",
    "numberOperatorIsLessThan": "er mindre end",
    "numberOperatorIsAtMost": "er højest",
    "numberOperatorIsGreaterThan": "er større end",
    "numberOperatorIsBetween": "er mellem",
    "numberOperatorIsNotBetween": "er ikke mellem",
    "numberOperatorIsBlank": "er tomt",
    "numberOperatorIsNotBlank": "er ikke tomt",
    "string": "Streng",
    "number": "Nummer",
    "date": "Dato",
    "askForValues": "Spørg efter værdier",
    "prompt": "Prompt",
    "hint": "Tip",
    "error": {
      "invalidParams": "Ugyldige parametre.",
      "invalidUrl": "Ugyldig URL.",
      "noFilterFields": "Laget har ingen felter, der kan anvendes til oprettelse af filtre.",
      "invalidSQL": "Ugyldigt SQL-udtryk.",
      "cantParseSQL": "SQL-udtrykket kan ikke parses."
    },
    "caseSensitive": "Skelner mellem store og små bogstaver",
    "notSupportCaseSensitiveTip": "\"Hostede\" tjenester understøtter ikke forespørgsler, der skelner mellem store og små bogstaver.",
    "setFilterTip": "Angiv filteret korrekt.",
    "listValues": "Listeværdier",
    "cascadeFilterTip": "Vis kun værdier filtreret efter de forrige udtryk.",
    "noneCascadeFilterTip": "Alle entydige værdier i dette felt",
    "previousCascadeFilterTip": "Værdier filtreret efter de forrige udtryk",
    "allCascadeFilterTip": "Værdier filtreret efter alle andre udtryk"
  },
  "featureLayerSource": {
    "layer": "Lag",
    "browse": "Gennemse",
    "selectFromMap": "Kort",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "Tjeneste-URL",
    "inputLayerUrl": "Inputlagets URL",
    "selectLayer": "Vælg et vektorlag fra det aktuelle kort.",
    "chooseItem": "Vælg et vektorlagelement.",
    "setServiceUrl": "Angiv URL'en for en feature- eller korttjeneste.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Vælg et vektorlag."
  },
  "queryableLayerSource": {
    "layer": "Lag",
    "browse": "Gennemse",
    "selectFromMap": "Kort",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "Tjeneste-URL",
    "inputLayerUrl": "Inputlagets URL",
    "selectLayer": "Vælg et lag fra det aktuelle kort.",
    "chooseItem": "Vælg et element.",
    "setServiceUrl": "Indtast URL'en til tjenesten.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Vælg et lag."
  },
  "gpSource": {
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "Tjeneste-URL",
    "selectFromOnline": "ArcGIS Online",
    "setServiceUrl": "Indtast URL'en til en geoprocesseringstjeneste.",
    "chooseItem": "Vælg et geoprocesseringstjenesteelement.",
    "chooseTask": "Vælg en geoprocesseringsopgave."
  },
  "itemSelector": {
    "map": "Kort",
    "selectWebMap": "Vælg webkort",
    "addMapFromOnlineOrPortal": "Find og tilføj et webkort i applikationen fra offentlige ArcGIS Online-ressourcer eller dit private indhold i ArcGIS Online eller Portal.",
    "searchMapName": "Søg efter kortnavn...",
    "searchNone": "Vi kan ikke finde det, du søger. Prøv igen.",
    "groups": "Grupper",
    "noneGroups": "Ingen grupper",
    "signInTip": "Din login-session er udløbet. Opdater browseren for at logge på portalen igen.",
    "signIn": "Log ind",
    "publicMap": "Offentlig",
    "myOrganization": "Min organisation",
    "myGroup": "Mine grupper",
    "myContent": "Mit indhold",
    "count": "Tælling",
    "fromPortal": "fra Portal",
    "fromOnline": "fra ArcGIS.com",
    "noneThumbnail": "Miniaturen er ikke tilgængelig",
    "owner": "ejer",
    "signInTo": "Log ind på",
    "lastModified": "Senest ændret",
    "moreDetails": "Flere oplysninger",
    "mostRecent": "Seneste",
    "mostViewed": "Mest viste",
    "highestRated": "Højest klassificerede",
    "viewItemDetails": "Vis oplysninger om element"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Tjenesten understøtter ikke forespørgsler."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Der er intet passende lag tilgængeligt i kortet."
  },
  "layerInfosMenu": {
    "titleBasemap": "Baggrundskort",
    "titleLayers": "Operationelle lag",
    "labelLayer": "Navn på lag",
    "itemZoomTo": "Zoom til",
    "itemTransparency": "Gennemsigtighed",
    "itemTransparent": "Gennemsigtig",
    "itemOpaque": "Uigennemsigtig",
    "itemMoveUp": "Flyt op",
    "itemMoveDown": "Flyt ned",
    "itemDesc": "Beskrivelse",
    "itemDownload": "Hent",
    "itemToAttributeTable": "Vis i attributtabel"
  },
  "imageChooser": {
    "unsupportReaderAPI": "Opgave: Browseren understøtter ikke fillæser-API",
    "readError": "Kunne ikke læse filen.",
    "unknowError": "kan ikke fuldføre handlinger",
    "invalidType": "Ugyldig filtype.",
    "cropImage": "Beskær billede",
    "exceed": "Filstørrelsen må ikke være over 1.024 KB",
    "enableFlash": "Aktivér Adobe Flash, før du browser til et billede.",
    "cropWaining": "Vælg et foto, der er mindst ${width} x ${height} pixels.",
    "toolTip": "For at opnå det bedste resultat bør billedet være ${width} pixels bredt x ${height} pixels højt. Andre størrelser tilpasses, så de passer. Acceptable billedformater er: PNG, GIF og JPEG."
  },
  "simpleTable": {
    "moveUp": "Flyt op",
    "moveDown": "Flyt ned",
    "deleteRow": "Slet",
    "edit": "Redigér"
  },
  "urlParams": {
    "invalidToken": "Ugyldigt token",
    "validateTokenError": "Ugyldigt token eller netværksfejl"
  },
  "exportTo": {
    "exportTo": "Eksportér",
    "toCSV": "Eksportér til CSV-fil",
    "toFeatureCollection": "Eksportér til objektsamling",
    "toGeoJSON": "Eksportér til GeoJSON"
  },
  "appState": {
    "title": "App-tilstand",
    "restoreMap": "Klik for at gendanne kortudstrækningen og lagenes synlighed dér, hvor du var nået til."
  },
  "featureActions": {
    "featureActions": "Objekthandlinger",
    "ZoomTo": "Zoom til",
    "PanTo": "Panorér til",
    "Flash": "Blitz",
    "ShowPopup": "Vis pop-up-vindue",
    "CreateLayer": "Opret lag",
    "ShowStatistics": "Statistik...",
    "ClearSelection": "Clear selection",
    "ExportToCSV": "Eksportér til CSV-fil",
    "ShowSelectedFeature": "Vis udvalgte objekter",
    "ExportToFeatureCollection": "Eksportér til objektsamling",
    "ExportToGeoJSON": "Eksportér til GeoJSON",
    "EditAttributes": "Redigér attributter",
    "AddMarker": "Tilføj en markør",
    "RemoveMarker": "Fjern markør",
    "SaveToMyContent": "Gem til Mit indhold"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Relateret lag",
    "selectedFeatures": "Brug de valgte objekter",
    "drawShapesTip": "Tegn former for at vælge objekter",
    "pleaseDrawShapesTip": "Tegn former for at vælge objekter",
    "allFeaturesTip": "Alle objekter i laget",
    "selectFeaturesOrDrawShapesTip": "Brug de valgte objekter i dette lag, eller tegn former på kortet for at afgrænse objekterne."
  },
  "searchDistance": {
    "applySearchDistance": "Anvend en søgeafstand",
    "applySearchDistanceToFeatures": "Anvend en søgeafstand til de valgte objekter"
  },
  "units": {
    "miles": "Miles",
    "milesAbbr": "mile",
    "kilometers": "Kilometer",
    "kilometersAbbr": "km",
    "feet": "Fod",
    "feetAbbr": "fod",
    "meters": "Meter",
    "metersAbbr": "m",
    "yards": "Yards",
    "yardsAbbr": "yard",
    "acres": "Acres",
    "acresAbbr": "acres",
    "nauticalMiles": "Sømil",
    "nauticalMilesAbbr": "nmi",
    "uSSurveyFeet": "US survey feet",
    "uSSurveyFeetAbbr": "ftUS",
    "decimalDegree": "Decimalgrader",
    "decimalDegreeAbbr": "dd",
    "degreeMinuteSeconds": "Grader Minutter Sekunder",
    "degreeMinuteSecondsAbbr": "d-m-s",
    "squareMiles": "Kvadrat-miles",
    "squareMilesAbbr": "kvadratmil",
    "squareKilometer": "Kvadratkilometer",
    "squareKilometerAbbr": "kv.-km",
    "squareFeet": "Kvadratfod",
    "squareFeetAbbr": "kvadratfod",
    "squareMeters": "Kvadratmeter",
    "squareMetersAbbr": "kv.-m",
    "squareYards": "Kvadrat-yards",
    "squareYardsAbbr": "kvadratyard",
    "squareUSSurveyFeet": "Square US survey feet",
    "squareUSSurveyFeetAbbr": "sq ftUS"
  },
  "featureSetChooser": {
    "select": "Vælg",
    "dragBox": "Træk",
    "dragMouse": "Træk med musen",
    "selectByRectangle": "Vælg efter rektangel",
    "selectFeaturesTip": "Vælg objekter ved at trække en boks rundt om dem på kortet",
    "newSelectionTip": "Opret en ny markering",
    "addSelectionTip": "Føj til markering",
    "removeSelectionTip": "Fjern fra markeringen",
    "selectFromCurrentSelectionTip": "Vælg ud fra den aktuelle markering",
    "unselectAllSelectionTip": "Fravælg alle aktuelt valgte objekter",
    "selectByPolygon": "Vælg efter polygon",
    "selectByCircle": "Vælg efter cirkel",
    "selectByLine": "Vælg efter linje",
    "chooseSelectingTools": "Vælg markeringsværktøjer",
    "darw": "Tegn",
    "drawShap": "Tegn en form"
  },
  "widgetManager": {
    "createWidgetError": "Fejl ved oprettelse af widget",
    "createWidgetSettingPageError": "Fejl på indstillingsside ved oprettelse af widget",
    "loadWidgetResourceError": "Ressourcefejl ved indlæsning af widget"
  },
  "shareOptions": {
    "shareMap": "Vælg, hvem der kan se denne app",
    "shareMapTips": "Den app deles på nuværende tidspunkt med følgende personer",
    "everyone": "Alle",
    "theseGroups": "Disse grupper"
  },
  "shareLink": {
    "email": "e-mail",
    "shareEmail": "E-mail",
    "facebook": "facebook",
    "shareFacebook": "Facebook",
    "twitter": "twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "Indlejr denne app i et websted",
    "shareEmailSubject": "Deller webapplikation:",
    "shareEmailTxt1": "Her er en webapplikation, der deles med dig ved hjælp af Web AppBuilder for ArcGIS.",
    "shareEmailTxt2": "Du kan oprette og dele din egen webapplikation med Esri Web AppBuilder for ArcGIS.",
    "shareEmailTxt3": "Besøg http://www.esri.com/software/web-appbuilder for at få yderligere oplysninger.",
    "smallSize": "Lille",
    "mediumSize": "Mellem",
    "largeSize": "Stor",
    "customSize": "Brugerdefineret",
    "embed": "Indlejr denne app i et websted",
    "more": "Indlejringsindstillinger",
    "changeShareSettings": "Redigér delingsindstillinger",
    "shareLinkText": "Del et link til denne app",
    "linkOptions": "Link-indstillinger",
    "linkOptionsUrlParameters": "Vælg de URL-parametre, der skal medtages i linket",
    "currentMapExtent": "Aktuel kortudstrækning",
    "chooseCenterWithLevel": "Klik på kortet for at definere kortets centrum med zoomniveau",
    "chooseCenterWithScale": "Klik på kortet for at definere kortets centrum med kortmålestok",
    "findLocation": "Find stedet eller objektet, og zoom til det",
    "findLocation_inputPlaceholder": "Dit sted eller objekt",
    "queryFeature": "Forespørg på et objekt, og zoom til det",
    "addMarker": "Tilføj en markør på kortet",
    "addMarker_titlePlaceholder": "Titlen på markørens pop-up",
    "addMarker_symbolURL": "Markørsymbol-URL",
    "addMarker_label": "Markøretiket",
    "popupTitle": "Pop-up-titel",
    "zoomLevel": "Zoomniveau",
    "overwirteMobileLayout": "Overskriv standardskærmstørrelsen for de mobile layout",
    "language": "Indstil visningssprog for app'en",
    "auth": "Godkend en bruger automatisk",
    "linkPreview": "Link-eksempel",
    "useShortenLink": "Kort link",
    "shareMapUrlExtent": "Del aktuelt kortområde",
    "shareToWebTips": "Denne app er ikke blevet delt med offentligheden. Folk vil muligvis ikke kunne se den."
  },
  "webSceneLoader": {
    "webglSupportTip": "3D-webapplikationer understøttes ikke i din browser."
  },
  "map": {
    "basemapNotAvailable": "Baggrundskortet er ikke tilgængeligt.",
    "displayDefaultBasemap": "Viser standardbaggrundskort i stedet for.",
    "layerLoadedError": "Laget, ${layers}, kan ikke føjes til kortet."
  },
  "popup": {
    "relatedTables": "Relatereder tabeller:",
    "relatedRecords": "Relaterede poster:",
    "noRelatedRecotds": "Ingen relaterede poster fundet.",
    "chooseFieldTip": "Vælg en attribut for at vise listen",
    "saveAsPopupTitle": "Samme som pop-up-titel"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "Der er for mange objekter i din markering. Det kan tage lang tid at hente og vise dem på kortet.",
    "askForContinue": "Vil du fortsætte?"
  },
  "colorPalette": {
    "transparent": "Gennemsigtig",
    "custom": "Brugerdefineret"
  },
  "temperature": {
    "celsius": "Celsius",
    "fahrenheit": "Fahrenheit"
  },
  "report": {
    "printButtonLabel": "Udskriv",
    "reportDimensionsMsg": "Denne rapport er designet til udskrivning på ${paperSize} papir",
    "unableToPrintMapMsg": "Der opstod en fejl under udskrivning af kort(ene)",
    "notesHint": "Angiv kommentarer her",
    "landscape": "På langs",
    "portrait": "På højkant",
    "mapOnly": "MAP_ONLY",
    "a0": "A0",
    "a1": "A1",
    "a2": "A2",
    "a3": "A3",
    "a4": "A4",
    "a5": "A5",
    "letterANSIA": "Letter ANSI A",
    "tabloidANSIB": "Tabloid ANSI B",
    "letter": "Letter",
    "legal": "Juridisk",
    "tabloid": "Tabloid",
    "ansi_a": "ANSI A",
    "ansi_b": "ANSI B",
    "ansi_c": "ANSI C",
    "ansi_d": "ANSI D",
    "ansi_e": "ANSI E"
  },
  "snapshot": {
    "snapshot_complete": "Har oprettet snapshot med succes.",
    "snapshot_failed": "Kunne ikke oprette snapshot.",
    "snapshot_append": "Snapshot",
    "utc": "UTC"
  },
  "statisticsChart": {
    "enlarge": "Forstør",
    "setting": "Indstilling",
    "count": "Tælling",
    "horizontalAxis": "Horisontal akse",
    "verticalAxis": "Vertikal akse",
    "dataLabels": "Dataetiketter",
    "color": "Farve"
  },
  "frameworkDatasource": {
    "setDataSource": "Angiv datakilde",
    "customDataSource": "Ekstra datakilde",
    "selectCustomDataTip": "Vælg en datakilde fra denne app.",
    "widgetOutputs": "Widget-output",
    "noExtraDsAvailable": "Ingen ekstra datakilder er til rådighed.",
    "addExtraDsTip": "Gå til builder-programmets Attribut-fane, og klik på Ekstra datakilde for at tilføje data.",
    "widgetOutpusListTip": "Widget-outputs (hvis der er nogen) er også angivet her."
  },
  "gridLayout": {
    "addWidgetTip": "Tilføj widgets her via Widget-fanen",
    "modifyLayout": "Redigér layout",
    "dragToAdd": "Træk for at tilføje",
    "mapArea": "KORTOMRÅDE"
  },
  "noEditPrivileges": "Din konto har ikke rettigheder til at oprette eller redigere data.",
  "invalidConfiguration": "Widget'en er enten ikke konfigureret, eller lagene i konfigurationen findes ikke længere i kortet. Åbn app'en i builder-tilstand, og omkonfigurér widget'en."
});