define({
  "_widgetLabel": "Koordinat",
  "hintMessage": "Koordinatları almak için haritaya tıkla",
  "defaultLabel": "Varsayılan",
  "realtimeLabel": "Koordinatları almak için fareyi hareket ettirin",
  "computing": "Hesaplıyor...",
  "latitudeLabel": "Enlem",
  "longitudeLabel": "Boylam",
  "loading": "yükleniyor...",
  "enableClick": "Koordinat almak için haritaya tıklama özelliğini etkinleştirmek için tıklayın",
  "disableClick": "Koordinat almak için haritaya tıklama özelliğini devre dışı bırakmak için tıklayın",
  "Default": "Varsayılan",
  "Inches": "İnç",
  "Foot": "Fit",
  "Yards": "Yarda",
  "Miles": "Mil",
  "Nautical_Miles": "Deniz mili",
  "Millimeters": "Milimetre",
  "Centimeters": "Santimetre",
  "Meter": "Metre",
  "Kilometers": "Kilometre",
  "Decimeters": "Desimetre",
  "Decimal_Degrees": "Derece",
  "Degree_Minutes_Seconds": "Derece dakika saniye",
  "MGRS": "MGRS",
  "USNG": "USNG"
});