define({
  "instruction": "Prieš aplikaciją padarant pasiekiamą, parodomas pristatymo langas.",
  "defaultContent": "Čia pridėkite teksto, nuorodų ir mažų grafinių elementų.",
  "requireConfirm": "Reikalauti patvirtinimo norint tęsti",
  "noRequireConfirm": "Norint tęsti, patvirtinimo nereikia",
  "optionText": "Galimybė išjungti pristatymo langą, rodomą aplikacijos paleidimo metu.",
  "confirmLabel": "Patvirtinimo tekstai: ",
  "confirmLabelColor": "Patvirtinimo teksto spalva",
  "defaultConfirmText": "Sutinku su anksčiau pateiktomis sąlygomis",
  "confirmOption": "Pristatymo ekraną rodyti kiekvieną kartą paleidus aplikaciją",
  "backgroundColor": "Fono spalva",
  "content": "Turinys",
  "contentDescription": "Apibrėžkite turinį, rodomą pristatymo lange.",
  "appearance": "Išvaizda",
  "appearanceDescription": "Nustatykite pristatymo lango išvaizdą.",
  "size": "Dydis",
  "width": "Plotis",
  "height": "Aukštis",
  "custom": "Adaptuotas",
  "background": "Fonas",
  "colorFill": "Spalvinis užpildymas",
  "imageFill": "Užpildymas atvaizdu",
  "chooseFile": "Pasirinkite failą",
  "noFileChosen": "Nepasirinktas joks failas",
  "transparency": "Permatomumas",
  "sizeFill": "Užpildyti",
  "sizeFit": "Talpinti",
  "sizeStretch": "Ištempti iki užpildymo dydžio",
  "sizeCenter": "Centruoti",
  "sizeTile": "Išklotinė",
  "buttonColor": "Mygtukų spalva",
  "buttonText": "Mygtukų tekstas",
  "buttonTextColor": "Mygtukų teksto spalva",
  "contentAlign": "Turinio lygiavimas",
  "alignTop": "Viršus",
  "alignMiddle": "Vidurys",
  "maskColor": "Kaukės spalva",
  "options": "Parinktys",
  "optionsDescription": "Nustatykite pristatymo lango veikimą."
});