define(
   ({
    _widgetLabel: "属性テーブル",
    ok: "OK",
    cancel: "キャンセル",
    unsupportQueryWarning: "レイヤーを属性テーブル ウィジェットで表示するには、レイヤーがクエリ操作をサポートしている必要があります。サービスのクエリ機能が有効化されていることを確認してください。",
    exportMessage: "データを CSV ファイルにエクスポートしますか？",
    exportFiles: "CSV にエクスポート",
    exportSelected: "選択内容を CSV にエクスポート",
    exportAll: "すべてを CSV にエクスポート",
    options: "オプション",
    zoomto: "ズーム",
    highlight: "グラフィックのハイライト表示",
    selectAll: "すべてのページのレコードを選択",
    selectPage: "現在のページのレコードを選択",
    clearSelection: "選択の解除",
    filter: "フィルター",
    setFilterTip: "フィルターを正しく設定してください。",
    noFilterTip: "フィルターの条件式が定義されていない場合、このクエリ タスクは、指定したデータ ソース内のすべてのフィーチャをリストします。",
    filterByExtent: "マップ範囲によるフィルター",
    showSelectedRecords: "選択レコードの表示",
    showAllRecords: "すべてのレコードを表示",
    showRelatedRecords: "関連レコードの表示",
    noRelatedRecords: "関連するレコードがありません",
    refresh: "更新",
    features: "フィーチャ",
    selected: "件のフィーチャを選択",
    transparent: "透過モード",
    indicate: "選択フィーチャの表示",
    columns: "列の表示/非表示",
    selectionSymbol: "選択シンボル",
    closeMessage: "テーブルの非表示 (再度展開するには下部から)",
    dataNotAvailable: "データを使用できません<br>[更新] ボタンをクリックしてからもう一度試してください。",
    openTableTip: "属性テーブルを開く",
    closeTableTip: "属性テーブルの非表示"
  })
);