define({
  "_widgetLabel": "Bảng Thuộc tính",
  "_featureAction_ShowRelatedRecords": "Hiện các bản ghi liên quan",
  "_featureAction_ViewInTable": "Xem trong Bảng Thuộc tính",
  "ok": "OK",
  "cancel": "Hủy",
  "unsupportQueryWarning": "Lớp cần hỗ trợ hoạt động truy vấn để hiển thị trong tiện ích Bảng Thuộc tính. Đảm bảo khả năng truy vấn trong dịch vụ được bật.",
  "exportMessage": "Xuất dữ liệu ra tệp CSV?",
  "exportFiles": "Xuất ra CSV",
  "exportSelected": "Xuất mục đã chọn sang CSV",
  "exportAll": "Xuất tất cả sang CSV",
  "options": "Tùy chọn",
  "zoomto": "Phóng tới",
  "highlight": "Đồ họa đánh dấu",
  "selectAll": "Chọn bản ghi trong tất cả các trang",
  "selectPage": "Chọn bản ghi trong trang hiện tại",
  "clearSelection": "Xóa lựa chọn",
  "filter": "Bộ lọc",
  "setFilterTip": "Vui lòng thiết lập bộ lọc chính xác.",
  "noFilterTip": "Nếu biểu thức bộ lọc không được xác định, tác vụ truy vấn này sẽ liệt kê tất cả các đối tượng trong nguồn dữ liệu đã chỉ định.",
  "filterByExtent": "Lọc theo phạm vi bản đồ",
  "showSelectedRecords": "Hiện các bản ghi được chọn",
  "showAllRecords": "Hiện tất cả bản ghi",
  "showRelatedRecords": "Hiện các bản ghi liên quan",
  "noRelatedRecords": "Không tìm thấy hồ sơ liên quan",
  "attachmentColumn": "Ảnh và tệp",
  "refresh": "Làm mới",
  "features": "đối tượng",
  "records": "bản ghi",
  "selected": "đã chọn",
  "transparent": "Chế độ trong suốt",
  "indicate": "Xác định lựa chọn",
  "columns": "Hiển thị/Ẩn cột",
  "selectionSymbol": "Ký hiệu lựa chọn",
  "closeMessage": "Ẩn bảng (mở rộng lại từ dưới cùng)",
  "dataNotAvailable": "Dữ liệu không khả dụng!<br>Bấm vào nút [Làm mới] để thử lại.",
  "openTableTip": "Mở Bảng Thuộc tính",
  "closeTableTip": "Ẩn Bảng Thuộc tính",
  "sortAsc": "Sắp xếp tăng dần",
  "sortDes": "Sắp xếp giảm dần",
  "statistics": "Thống kê",
  "attachments": "Tệp đính kèm",
  "files": "tệp"
});