define(
   ({
    _widgetLabel: "Bảng Thuộc tính",
    ok: "OK",
    cancel: "Hủy",
    unsupportQueryWarning: "Lớp cần hỗ trợ hoạt động truy vấn để hiển thị trong tiện ích Bảng Thuộc tính. Đảm bảo khả năng truy vấn trong dịch vụ được bật.",
    exportMessage: "Xuất dữ liệu ra tệp CSV?",
    exportFiles: "Xuất ra CSV",
    exportSelected: "Xuất Mục đã chọn sang CSV",
    exportAll: "Xuất Tất cả sang CSV",
    options: "Tùy chọn",
    zoomto: "Phóng tới",
    highlight: "Đồ họa Đánh dấu",
    selectAll: "Chọn Bản ghi trong Tất cả Các trang",
    selectPage: "Chọn Bản ghi trong Trang Hiện tại",
    clearSelection: "Xóa lựa chọn",
    filter: "Bộ lọc",
    setFilterTip: "Vui lòng thiết lập bộ lọc chính xác.",
    noFilterTip: "Nếu biểu thức bộ lọc không được xác định, tác vụ truy vấn này sẽ liệt kê tất cả các đối tượng trong nguồn dữ liệu đã chỉ định.",
    filterByExtent: "Lọc theo Phạm vi Bản đồ",
    showSelectedRecords: "Hiện các Bản ghi được Chọn",
    showAllRecords: "Hiện Tất cả Bản ghi",
    showRelatedRecords: "Hiện các Bản ghi Liên quan",
    noRelatedRecords: "Không có các Bản ghi Liên quan",
    refresh: "Làm mới",
    features: "đối tượng",
    selected: "đã chọn",
    transparent: "Chế độ Trong suốt",
    indicate: "Xác định Lựa chọn",
    columns: "Hiển thị/Ẩn Cột",
    selectionSymbol: "Ký hiệu Lựa chọn",
    closeMessage: "Ẩn Bảng (mở rộng lại từ dưới cùng)",
    dataNotAvailable: "Dữ liệu không khả dụng!<br>Bấm vào nút [Làm mới] để thử lại.",
    openTableTip: "Mở Bảng Thuộc tính",
    closeTableTip: "Ẩn Bảng Thuộc tính"
  })
);