define({
  "common": {
    "apply": "Primijeni",
    "ok": "U redu",
    "cancel": "Odustani",
    "yes": "Da",
    "no": "Ne",
    "next": "Sljedeće",
    "previous": "Prethodno",
    "back": "Natrag",
    "selected": "odabrano",
    "name": "Naziv",
    "usage": "Upotreba",
    "settings": "Postavke",
    "home": "Početna",
    "link": "Poveznica",
    "messages": "Poruke",
    "outputs": "Izvozi",
    "title": "Naslov",
    "thumbnail": "Sličica",
    "url": "URL",
    "actions": "Radnje",
    "layer": "Sloj",
    "action": "Radnja",
    "input": "Unos",
    "output": "Izvoz",
    "type": "Vrsta",
    "required": "Potrebno",
    "options": "Opcije",
    "label": "Oznaka",
    "tooltip": "Opis elementa",
    "visible": "Vidljivo",
    "symbol": "Simbol",
    "popup": "Skočni prozor",
    "upload": "Učitaj",
    "execute": "Izvrši",
    "help": "Pomoć",
    "executing": "Izvršavanje",
    "clear": "Očisti",
    "error": "Pogreška",
    "zoomTo": "Povećaj na",
    "attribute": "Atribut",
    "exports": "Izvezi",
    "check": "Provjera",
    "save": "Spremi",
    "close": "Zatvori",
    "deleteText": "Izbriši",
    "map": "Karta",
    "scene": "Scena",
    "reset": "Vrati izvorno",
    "icon": "Ikona",
    "folder": "Mapa",
    "share": "Podijeli",
    "view": "Prikaz",
    "newText": "Novo",
    "edit": "Uredi",
    "wkid": "WKID",
    "table": "Tablica",
    "zoomIn": "Povećaj",
    "zoomOut": "Smanji",
    "continue1": "Nastavak",
    "longitude": "Geografska dužina",
    "latitude": "Geografska širina",
    "custom": "Prilagođeno",
    "image": "Slika",
    "font": "Font",
    "text": "Tekst",
    "all": "Sve",
    "number": "Broj",
    "percentage": "Postotak",
    "unit": "Jedinica",
    "thousand": "Tisuću",
    "billion": "Milijarda",
    "million": "Milijun",
    "none": "Nema",
    "field": "Polje",
    "operation": "Radnja",
    "disableUpdateGeometry": "Onemogući ažuriranje geometrije",
    "preview": "Pretpregled"
  },
  "errorCode": "Kod",
  "errorMessage": "Poruka",
  "errorDetail": "Pojedinost",
  "widgetPlaceholderTooltip": "Za postavljanje idite u Widgete i kliknite na odgovarajuće mjesto",
  "fieldStatistics": {
    "selectField": "Odaberi polje",
    "statistics": "Statistike",
    "field": "Polje",
    "count": "Broj vrijednosti",
    "sum": "Zbroj vrijednosti",
    "min": "Minimum",
    "max": "Maksimum",
    "ave": "Prosječno",
    "stddev": "Standardno odstupanje"
  },
  "symbolChooser": {
    "preview": "Pretpregled",
    "basic": "Osnovno",
    "arrows": "Strelice",
    "business": "Poduzeće",
    "cartographic": "Kartografsko",
    "nationalParkService": "Nacionalni park",
    "outdoorRecreation": "Vanjska rekreacija",
    "peoplePlaces": "Ljudi i mjesta",
    "safetyHealth": "Sigurnost i zdravlje",
    "shapes": "Oblici",
    "transportation": "Prijevoz",
    "symbolSize": "Veličina simbola",
    "color": "Boja",
    "alpha": "Alfa",
    "outlineColor": "Boja obrisa",
    "outlineWidth": "Širina obrisa",
    "style": "Stil",
    "width": "Širina",
    "text": "Tekst",
    "fontColor": "Boja fonta",
    "fontSize": "Veličina fonta",
    "transparency": "Prozirnost",
    "solid": "Puna linija",
    "dash": "Linija s crticom",
    "dot": "Točka",
    "dashDot": "Linija s crticom i točkom",
    "dashDotDot": "Linija s crticom i dvije točke",
    "customImage": "Prilagođena slika",
    "chooseFile": "Izaberi datoteku",
    "noFileChoosen": "Nije izabrana datoteka."
  },
  "transparency": {
    "opaque": "Neprozirno",
    "transparent": "Transparentno"
  },
  "rendererChooser": {
    "domain": "Domena",
    "use": "Upotrijebi",
    "singleSymbol": "Jedan simbol",
    "uniqueSymbol": "Jedinstveni simboli",
    "color": "Boja",
    "size": "Veličina",
    "toShow": "Za prikaz",
    "colors": "Boje",
    "classes": "Razredi",
    "symbolSize": "Veličina simbola",
    "addValue": "Dodaj vrijednost",
    "setDefaultSymbol": "Postavi zadani simbol",
    "defaultSymbol": "Zadani simbol",
    "selectedSymbol": "Odabrani simbol",
    "value": "Vrijednost",
    "label": "Oznaka",
    "range": "Raspon"
  },
  "drawBox": {
    "point": "Točka",
    "line": "Linija",
    "polyline": "Polilinija",
    "freehandPolyline": "Prostoručna polilinija",
    "triangle": "Trokut",
    "extent": "Obuhvat",
    "circle": "Krug",
    "ellipse": "Elipsa",
    "polygon": "Poligon",
    "freehandPolygon": "Prostoručni poligon",
    "text": "Tekst",
    "clear": "Očisti"
  },
  "popupConfig": {
    "title": "Naslov",
    "add": "Dodaj",
    "fields": "Polja",
    "noField": "Nema polja",
    "visibility": "Vidljivo",
    "name": "Naziv",
    "alias": "Alias",
    "actions": "Radnje"
  },
  "includeButton": {
    "include": "Uključi"
  },
  "loadingShelter": {
    "loading": "Učitavanje"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Usluga nije pronađena.",
    "unableConnectTo": "Nije moguće povezivanje na",
    "invalidUrlTip": "URL koji ste unijeli nije valjan ili dostupan."
  },
  "serviceBrowser": {
    "noGpFound": "Usluga geoprocesiranja nije pronađena.",
    "unableConnectTo": "Nije moguće povezivanje na"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Nema usluge karte ili usluge geoobjekta.",
    "unableConnectTo": "Nije moguće povezivanje na"
  },
  "basicServiceChooser": {
    "validate": "Provjera",
    "example": "Primjer",
    "set": "Postavi"
  },
  "urlInput": {
    "invalidUrl": "Nevažeći URL."
  },
  "urlComboBox": {
    "invalidUrl": "Nevažeći URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Dodaj izraz",
    "addSet": "Dodaj niz",
    "matchMsg": "Pribavite geoobjekte u sloju koji odgovaraju ${any_or_all} sljedećim izrazima",
    "matchMsgSet": "${any_or_all} od sljedećih izraza u ovom nizu jesu istiniti",
    "all": "Svi",
    "any": "Bilo koji",
    "value": "Vrijednost",
    "field": "Polje",
    "unique": "Jedinstveno",
    "none": "Nema",
    "and": "i",
    "valueTooltip": "Unesite vrijednost",
    "fieldTooltip": "Izaberite iz postojećih polja",
    "uniqueValueTooltip": "Izaberite iz jedinstvenih vrijednosti u odabranom polju",
    "stringOperatorIs": "je",
    "stringOperatorIsNot": "nije",
    "stringOperatorStartsWith": "počinje s",
    "stringOperatorEndsWith": "završava s",
    "stringOperatorContains": "sadrži",
    "stringOperatorDoesNotContain": "ne sadrži",
    "stringOperatorIsBlank": "prazno je",
    "stringOperatorIsNotBlank": "nije prazno",
    "dateOperatorIsOn": "je na",
    "dateOperatorIsNotOn": "nije na",
    "dateOperatorIsBefore": "je prije",
    "dateOperatorIsAfter": "je poslije",
    "dateOperatorIsOnOrBefore": "je na ili prije",
    "dateOperatorIsOnOrAfter": "je na ili kasnije",
    "dateOperatorMinutes": "minute",
    "dateOperatorHours": "sata",
    "dateOperatorDays": "dani",
    "dateOperatorWeeks": "tjedni",
    "dateOperatorMonths": "mjeseci",
    "dateOperatorYears": "godine",
    "dateOperatorInTheLast": "u posljednjem",
    "dateOperatorNotInTheLast": "nije u posljednjem",
    "dateOperatorIsBetween": "jest između",
    "dateOperatorIsNotBetween": "nije između",
    "dateOperatorIsBlank": "prazno je",
    "dateOperatorIsNotBlank": "nije prazno",
    "numberOperatorIs": "je",
    "numberOperatorIsNot": "nije",
    "numberOperatorIsAtLeast": "barem je",
    "numberOperatorIsLessThan": "manje je od",
    "numberOperatorIsAtMost": "najviše je",
    "numberOperatorIsGreaterThan": "veće je od",
    "numberOperatorIsBetween": "jest između",
    "numberOperatorIsNotBetween": "nije između",
    "numberOperatorIsBlank": "prazno je",
    "numberOperatorIsNotBlank": "nije prazno",
    "string": "Tekst",
    "number": "Broj",
    "date": "Datum",
    "askForValues": "Zatražite vrijednosti",
    "prompt": "Pitanje",
    "hint": "Podsjetnik",
    "error": {
      "invalidParams": "Nevažeći parametri.",
      "invalidUrl": "Nevažeći URL.",
      "noFilterFields": "Sloj nema polja koja se mogu upotrijebiti za stvaranje filtara.",
      "invalidSQL": "Nevažeći SQL izraz.",
      "cantParseSQL": "Ne može analizirati SQL izraz."
    },
    "caseSensitive": "Osjetljivo na velika i mala slova",
    "notSupportCaseSensitiveTip": "Hostirane usluge ne podržavaju upit osjetljiv na velika i mala slova.",
    "setFilterTip": "Ispravno postavite filtre.",
    "listValues": "Popis vrijednosti",
    "cascadeFilterTip": "Prikaži samo vrijednosti filtrirane prethodnim izrazima.",
    "noneCascadeFilterTip": "Sve jedinstvene vrijednosti ovog polja",
    "previousCascadeFilterTip": "Vrijednosti filtrirane prethodnim izrazima",
    "allCascadeFilterTip": "Vrijednosti filtrirane svim ostalim izrazima"
  },
  "featureLayerSource": {
    "layer": "Sloj",
    "browse": "Pregledaj",
    "selectFromMap": "Karta",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL usluge",
    "inputLayerUrl": "Unesite URL sloja",
    "selectLayer": "Odaberite sloj geoobjekta s trenutačne karte.",
    "chooseItem": "Izaberite stavku sloja geoobjekata.",
    "setServiceUrl": "Unesite URL usluge geoobjekata ili usluge karte.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Odaberite sloj geoobjekata."
  },
  "queryableLayerSource": {
    "layer": "Sloj",
    "browse": "Pregledaj",
    "selectFromMap": "Karta",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL usluge",
    "inputLayerUrl": "Unesite URL sloja",
    "selectLayer": "Odaberite sloj s trenutačne karte.",
    "chooseItem": "Odaberite stavku.",
    "setServiceUrl": "Unesite URL usluge.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Izaberite sloj."
  },
  "gpSource": {
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL usluge",
    "selectFromOnline": "ArcGIS Online",
    "setServiceUrl": "Unesite URL usluge geoprocesiranja.",
    "chooseItem": "Izaberite stavku usluge geoprocesiranja.",
    "chooseTask": "Izaberite zadatak geoprocesiranja."
  },
  "itemSelector": {
    "map": "Karta",
    "selectWebMap": "Izaberi web-kartu",
    "addMapFromOnlineOrPortal": "Pronađite i dodajte web-kartu iz aplikacije iz javnih resursa ArcGIS Onlinea ili iz vašeg privatnog sadržaja u ArcGIS Onlineu ili Portalu.",
    "searchMapName": "Pretraži prema nazivu karte...",
    "searchNone": "Nismo mogli pronaći to što tražite. Pokušajte ponovno.",
    "groups": "Grupe",
    "noneGroups": "Nema grupa",
    "signInTip": "Istekla je vaša sesija prijave pa osvježite svoj preglednik kako biste se ponovno prijavili na portal.",
    "signIn": "Prijava",
    "publicMap": "Javno",
    "myOrganization": "Moja organizacija",
    "myGroup": "Moje grupe",
    "myContent": "Moj sadržaj",
    "count": "Broj",
    "fromPortal": "s Portala",
    "fromOnline": "sa stranice ArcGIS.com",
    "noneThumbnail": "Sličica nije dostupna",
    "owner": "vlasnik",
    "signInTo": "Prijavi se u",
    "lastModified": "Posljednja izmjena",
    "moreDetails": "Više pojedinosti",
    "mostRecent": "Najnovije",
    "mostViewed": "Najviše prikaza",
    "highestRated": "Najbolje ocjenjeno",
    "viewItemDetails": "Prikaži pojedinosti o stavci"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Usluga ne podržava upit."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Nema odgovarajućeg sloja dostupnog na karti."
  },
  "layerInfosMenu": {
    "titleBasemap": "Kartografske podloge",
    "titleLayers": "Operativni slojevi",
    "labelLayer": "Naziv sloja",
    "itemZoomTo": "Povećaj na",
    "itemTransparency": "Prozirnost",
    "itemTransparent": "Transparentno",
    "itemOpaque": "Neprozirno",
    "itemMoveUp": "Premjesti gore",
    "itemMoveDown": "Premjesti dolje",
    "itemDesc": "Opis",
    "itemDownload": "Preuzmi",
    "itemToAttributeTable": "Prikaži u atributnoj tablici"
  },
  "imageChooser": {
    "unsupportReaderAPI": "Obveza: preglednik ne podržava čitač datoteka API",
    "readError": "Nije uspjelo čitanje datoteke.",
    "unknowError": "nije moguće dovršiti radnje",
    "invalidType": "Nevažeća vrsta datoteke.",
    "cropImage": "Obreži sliku",
    "exceed": "Veličina datoteke ne može premašiti 1024 KB",
    "enableFlash": "Uključite Adobe Flash prije pretraživanja slike.",
    "cropWaining": "Izaberite fotografiju koja je barem ${width} x ${height} piksela.",
    "toolTip": "Za najbolje rezultate slika bi trebala imati ${width} piksela u širini i ${height} piksela u visini. Ostale će se veličine prilagoditi kako bi odgovarale. Prihvatljivi formati slika: PNG, GIF i JPEG."
  },
  "simpleTable": {
    "moveUp": "Premjesti gore",
    "moveDown": "Premjesti dolje",
    "deleteRow": "Izbriši",
    "edit": "Uredi"
  },
  "urlParams": {
    "invalidToken": "Nevažeći token",
    "validateTokenError": "Nevažeći token ili mrežna pogreška"
  },
  "exportTo": {
    "exportTo": "Izvezi",
    "toCSV": "Izvezi u CSV datoteku",
    "toFeatureCollection": "Izvezi u kolekciju geoobjekata",
    "toGeoJSON": "Izvezi u GeoJSON"
  },
  "appState": {
    "title": "Stanje appa",
    "restoreMap": "Kliknite da biste vratili obuhvat karte i vidljivost slojeva na posljednju vrijednost."
  },
  "featureActions": {
    "featureActions": "Radnje za geoobjekte",
    "ZoomTo": "Povećaj na",
    "PanTo": "Kreći se na",
    "Flash": "Bljeskalica",
    "ShowPopup": "Prikaži skočni prozor",
    "CreateLayer": "Stvori sloj",
    "ShowStatistics": "Statistike...",
    "ClearSelection": "Očisti odabir",
    "ExportToCSV": "Izvezi u CSV datoteku",
    "ShowSelectedFeature": "Prikaži odabrane geoobjekte",
    "ExportToFeatureCollection": "Izvezi u kolekciju geoobjekata",
    "ExportToGeoJSON": "Izvezi u GeoJSON",
    "EditAttributes": "Uredi atribute",
    "AddMarker": "Dodaj oznaku",
    "RemoveMarker": "Ukloni oznaku",
    "SaveToMyContent": "Spremi u Moj sadržaj"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Povezani sloj",
    "selectedFeatures": "Upotrijebi odabrane geoobjekte",
    "drawShapesTip": "Crtajte oblike da biste odabrali geoobjekte",
    "pleaseDrawShapesTip": "Nacrtajte oblike da biste odabrali geoobjekte",
    "allFeaturesTip": "Svi geoobjekti u sloju",
    "selectFeaturesOrDrawShapesTip": "Upotrijebite odabrane geoobjekte u ovom sloju ili nacrtajte oblike na karti da biste ograničili geoobjekte."
  },
  "searchDistance": {
    "applySearchDistance": "Primijenite udaljenost za pretraživanje",
    "applySearchDistanceToFeatures": "Primijenite udaljenost za pretraživanje na odabrane geoobjekte"
  },
  "units": {
    "miles": "Milje",
    "milesAbbr": "mi",
    "kilometers": "Kilometri",
    "kilometersAbbr": "km",
    "feet": "Stope",
    "feetAbbr": "ft",
    "meters": "Metri",
    "metersAbbr": "m",
    "yards": "Jardi",
    "yardsAbbr": "yd",
    "acres": "Hektari",
    "acresAbbr": "hektari",
    "nauticalMiles": "Nautičke milje",
    "nauticalMilesAbbr": "nmi",
    "uSSurveyFeet": "Američke stope",
    "uSSurveyFeetAbbr": "ftUS",
    "decimalDegree": "Decimalni stupnjevi",
    "decimalDegreeAbbr": "dd",
    "degreeMinuteSeconds": "Stupnjevi minuta sekunde",
    "degreeMinuteSecondsAbbr": "d-m-s",
    "squareMiles": "Kvadratne milje",
    "squareMilesAbbr": "kvadr. mi",
    "squareKilometer": "Kvadratni kilometri",
    "squareKilometerAbbr": "kvadr. km",
    "squareFeet": "Kvadratne stope",
    "squareFeetAbbr": "kvadr. ft",
    "squareMeters": "Kvadratni metri",
    "squareMetersAbbr": "kvadr. m",
    "squareYards": "Kvadratni jardi",
    "squareYardsAbbr": "kvadr. yd",
    "squareUSSurveyFeet": "Američke Kvadratne stope",
    "squareUSSurveyFeetAbbr": "sq ftUS"
  },
  "featureSetChooser": {
    "select": "Odaberi",
    "dragBox": "Povuci",
    "dragMouse": "Povuci miš",
    "selectByRectangle": "Odaberi prema pravokutniku",
    "selectFeaturesTip": "Odaberite geoobjekte povlačenjem okvira oko njih na karti",
    "newSelectionTip": "Stvori novi odabir",
    "addSelectionTip": "Dodaj odabiru",
    "removeSelectionTip": "Ukloni iz odabira",
    "selectFromCurrentSelectionTip": "Odaberi iz trenutačnog odabira",
    "unselectAllSelectionTip": "Odznači sve trenutačno odabrane geoobjekte",
    "selectByPolygon": "Odaberi prema poligonu",
    "selectByCircle": "Odaberi prema krugu",
    "selectByLine": "Odaberi prema liniji",
    "chooseSelectingTools": "Izaberi alate za odabir",
    "darw": "Crtaj",
    "drawShap": "Nacrtaj oblik"
  },
  "widgetManager": {
    "createWidgetError": "Pogreška pri stvaranju widgeta",
    "createWidgetSettingPageError": "Pogreška stranice za postavke za stvaranje widgeta",
    "loadWidgetResourceError": "Pogreška učitavanja izvora widgeta"
  },
  "shareOptions": {
    "shareMap": "Izaberite tko može vidjeti ovaj app",
    "shareMapTips": "Vaš se app trenutačno dijeli s ovim ljudima",
    "everyone": "Svi",
    "theseGroups": "Ove grupe"
  },
  "shareLink": {
    "email": "e-pošta",
    "shareEmail": "E-pošta",
    "facebook": "facebook",
    "shareFacebook": "Facebook",
    "twitter": "twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "Ugradi ovaj app u web-mjesto",
    "shareEmailSubject": "Dijeljenje web-appa:",
    "shareEmailTxt1": "Ovdje je web-app koji se dijeli s vama pomoću alata Web AppBuilder for ArcGIS.",
    "shareEmailTxt2": "Možete stvoriti i podijeliti svoj web-app a Esrijevim alatom Web AppBuilder for ArcGIS.",
    "shareEmailTxt3": "Posjetite http://www.esri.com/software/web-appbuilder za pojedinosti.",
    "smallSize": "Malo",
    "mediumSize": "Srednje",
    "largeSize": "Veliko",
    "customSize": "Prilagođeno",
    "embed": "Ugradi ovaj app u web-mjesto",
    "more": "Umetni opcije",
    "changeShareSettings": "Promijenite postavke dijeljenja",
    "shareLinkText": "Podijelite poveznicu na ovaj app",
    "linkOptions": "Opcije poveznice",
    "linkOptionsUrlParameters": "Odaberite URL parametre uključene u poveznicu",
    "currentMapExtent": "Trenutačni obuhvat karte",
    "chooseCenterWithLevel": "Kliknite na kartu da biste definirali središte karte s razinom povećanja",
    "chooseCenterWithScale": "Kliknite na kartu da biste definirali središte karte s omjerom karte",
    "findLocation": "Pronađite lokaciju ili geoobjekt i povećajte je/ga",
    "findLocation_inputPlaceholder": "Vaše mjesto ili geoobjekt",
    "queryFeature": "Pronađite geoobjekt upitom i povećajte ga",
    "addMarker": "Dodajte oznaku na kartu",
    "addMarker_titlePlaceholder": "Naslov skočnog prozora oznake",
    "addMarker_symbolURL": "URL simbola oznake",
    "addMarker_label": "Tekst oznake",
    "popupTitle": "Naslov skočnog prozora",
    "zoomLevel": "Razina uvećanja",
    "overwirteMobileLayout": "Zamijeni zadanu veličinu zaslona mobilnog izgleda",
    "language": "Postavi jezik prikaza appa",
    "auth": "Automatski provjeri autentičnost korisnika",
    "linkPreview": "Pretpregled poveznice",
    "useShortenLink": "Kratka poveznica",
    "shareMapUrlExtent": "Podijeli trenutačni obuhvat karte",
    "shareToWebTips": "Ovaj se app ne dijeli s javnošću. Ljudi ga možda neće moći vidjeti."
  },
  "webSceneLoader": {
    "webglSupportTip": "3D web-appovi nisu podržani u vašem pregledniku."
  },
  "map": {
    "basemapNotAvailable": "Kartografska podloga nije dostupna.",
    "displayDefaultBasemap": "Umjesto toga prikazuje se zadana kartografska podloga.",
    "layerLoadedError": "Sloj ${layers} ne može se dodati na kartu."
  },
  "popup": {
    "relatedTables": "Povezane tablice:",
    "relatedRecords": "Povezani zapisi:",
    "noRelatedRecotds": "Nema povezanih zapisa.",
    "chooseFieldTip": "Odaberite atribut za prikaz popisa",
    "saveAsPopupTitle": "Isto kao naziv skočnog prozora"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "U vašem je odabiru previše geoobjekata. Njihovo dohvaćanje i prikaz na karti mogu potrajati dugo.",
    "askForContinue": "Želite li nastaviti?"
  },
  "colorPalette": {
    "transparent": "Transparentno",
    "custom": "Prilagođeno"
  },
  "temperature": {
    "celsius": "Celzijus",
    "fahrenheit": "Fahrenheit"
  },
  "report": {
    "printButtonLabel": "Ispis",
    "reportDimensionsMsg": "Ovo je izvješće osmišljeno za ispis na ${paperSize} papiru",
    "unableToPrintMapMsg": "Došlo je do pogreške prilikom ispisa karte ili karata.",
    "notesHint": "Unesite komentare ovdje",
    "landscape": "Vodoravno",
    "portrait": "Okomito",
    "mapOnly": "MAP_ONLY",
    "a0": "A0",
    "a1": "A1",
    "a2": "A2",
    "a3": "A3",
    "a4": "A4",
    "a5": "A5",
    "letterANSIA": "Pismo ANSI A",
    "tabloidANSIB": "Tabloid ANSI B",
    "letter": "Pismo",
    "legal": "Pravno",
    "tabloid": "Tabloid",
    "ansi_a": "ANSI A",
    "ansi_b": "ANSI B",
    "ansi_c": "ANSI C",
    "ansi_d": "ANSI D",
    "ansi_e": "ANSI E"
  },
  "snapshot": {
    "snapshot_complete": "Uspješno stvorena snimka.",
    "snapshot_failed": "Stvaranje snimke nije uspjelo.",
    "snapshot_append": "Snimka",
    "utc": "UTC"
  },
  "statisticsChart": {
    "enlarge": "Uvećaj",
    "setting": "Postavka",
    "count": "Broj",
    "horizontalAxis": "Vodoravna os",
    "verticalAxis": "Okomita os",
    "dataLabels": "Oznake podataka",
    "color": "Boja"
  },
  "frameworkDatasource": {
    "setDataSource": "Postavite izvor podataka",
    "customDataSource": "Dodatni izvor podataka",
    "selectCustomDataTip": "Odaberite izvor podataka iz ovog appa.",
    "widgetOutputs": "Izlazi widgeta",
    "noExtraDsAvailable": "Nema dodatnih izvora podataka.",
    "addExtraDsTip": "Idite na karticu Atributi sastavljača i kliknite na Dodatni izvor podataka da biste dodali podatke.",
    "widgetOutpusListTip": "Izlazi widgeta (ako postoje) također su ovdje navedeni."
  },
  "gridLayout": {
    "addWidgetTip": "Ovdje dodajte widgete putem kartice widgeta",
    "modifyLayout": "Izmijeni izgled",
    "dragToAdd": "Povuci za dodavanje",
    "mapArea": "PODRUČJE KARTE"
  },
  "noEditPrivileges": "Vaš račun nema dopuštenje za stvaranje ili mijenjanje podataka.",
  "invalidConfiguration": "Widget nije konfiguriran ili slojevi u konfiguraciji više nisu u karti. Otvorite app u načinu sastavljača i ponovo konfigurirajte widget."
});