define({
  "_widgetLabel": "Lista de Camada",
  "titleBasemap": "Mapas Base",
  "titleLayers": "Camadas operacionais",
  "labelLayer": "Nome da Camada",
  "itemZoomTo": "Zoom para",
  "itemTransparency": "Transparência",
  "itemTransparent": "Transparente",
  "itemOpaque": "Opaco",
  "itemMoveUp": "Mover para cima",
  "itemMoveDown": "Mover para baixo",
  "itemDesc": "Descrição",
  "itemDownload": "Download",
  "itemToAttributeTable": "Visualizar na Tabela de Atributos",
  "itemShowItemDetails": "Mostrar detalhes do item",
  "empty": "vazio",
  "removePopup": "Desabilitar pop-up",
  "enablePopup": "Habilitar pop-up",
  "turnAllLayersOff": "Desativar todas as camadas",
  "turnAllLayersOn": "Ativar todas as camadas",
  "expandAllLayers": "Expandir todas as camadas",
  "collapseAlllayers": "Recolher todas as camadas",
  "turnAllLabelsOff": "Desativar todos os rótulos",
  "turnAllLabelsOn": "Ativar todos os rótulos",
  "showLabels": "Mostrar rótulos",
  "hideLables": "Ocultar rótulos"
});