define({
  "instruction": "選擇和配置將在「屬性」表格中初始顯示的圖層。",
  "label": "圖層",
  "show": "顯示",
  "actions": "配置圖層欄位",
  "field": "欄位",
  "alias": "別名",
  "visible": "可見",
  "linkField": "連結欄位",
  "noLayers": "沒有可用的圖徵圖層",
  "back": "上一步",
  "exportCSV": "允許匯出為 CSV",
  "expand": "最初展開的 widget",
  "filterByExtent": "預設會按地圖範圍啟用篩選器",
  "restore": "恢復至預設值",
  "ok": "確定",
  "cancel": "取消",
  "includePoint": "包含至匯出之檔案的點座標",
  "configureLayerFields": "配置圖層欄位",
  "result": "已成功儲存",
  "warning": "請先選擇“顯示”選項。",
  "fieldCheckWarning": "必須至少選擇一個欄位。",
  "unsupportQueryWarning": "要顯示在“屬性表” widget 中，該圖層需要支援查詢操作。請確保服務中的查詢功能已打開。",
  "unsupportQueryLayers": "要顯示在“屬性表” widget 中，以下圖層需要支援查詢操作。請確保服務中的查詢功能已打開。",
  "fieldName": "名稱",
  "fieldAlias": "別名",
  "fieldVisibility": "能見度",
  "fieldActions": "操作",
  "showAttachments": "顯示附件"
});