define({
  "instruction": "Izberite in konfigurirajte sloje, ki bodo najprej prikazani v atributni tabeli.",
  "label": "Sloj",
  "show": "Pokaži",
  "actions": "Konfigurirajte polja slojev",
  "field": "Polje",
  "alias": "Vzdevek",
  "url": "URL",
  "sortField": "Razvrsti polje",
  "sortOrderTooltips": {
    "toDescending": "Spremeni na padajoč vrstni red",
    "toAscending": "Spremeni na naraščajoč vrstni red"
  },
  "visible": "Vidno",
  "linkField": "Polje povezave",
  "noLayers": "Geoobjektni sloji niso na voljo",
  "back": "Nazaj",
  "exportCSV": "Dovoli izvoz v CSV",
  "expand": "Na začetku razširi pripomoček",
  "filterByExtent": "Omogoči privzeto filtriranje po obsegu karte",
  "allowTextSelection": "Dovoli izbiro besedila",
  "highlightColor": "Osvetli barvo",
  "restore": "Obnovi na privzeto vrednost",
  "ok": "V redu",
  "cancel": "Prekliči",
  "includePoint": "Vključi točkovne koordinate v izvoženo datoteko",
  "configureLayerFields": "Konfigurirajte polja sloja",
  "result": "Uspešno shranjeno",
  "warning": "Izberite Najprej pokaži možnost.",
  "fieldCheckWarning": "Izbrano mora biti vsaj eno polje.",
  "unsupportQueryWarning": "Sloj mora podpirati operacijo poizvedbe, da je prikazan v atributni tabeli pripomočka. Prepričajte se, da je možnost poizvedbe v storitvi vklopljena.",
  "unsupportQueryLayers": "Naslednji sloj mora podpirati operacijo poizvedbe, da je prikazan v atributni tabeli pripomočka. Prepričajte se, da je možnost poizvedbe v storitvi vklopljena.",
  "fieldName": "Ime",
  "fieldAlias": "Vzdevek",
  "fieldVisibility": "Vidnost",
  "fieldActions": "Dejanja",
  "showAttachments": "Pokaži priloge"
});