define({
  "_widgetLabel": "Tabla de atributos",
  "_featureAction_ShowRelatedRecords": "Mostrar registros relacionados",
  "_featureAction_ViewInTable": "Ver en la tabla de atributos",
  "ok": "Aceptar",
  "cancel": "Cancelar",
  "unsupportQueryWarning": "La capa debe ser compatible con la operación de consulta para mostrar el widget Tabla de atributos. Asegúrate de que la función de consulta en el servicio está activada.",
  "exportMessage": "¿Exportar datos a archivo CSV?",
  "exportFiles": "Exportar a CSV",
  "exportSelected": "Exportar selección a CSV",
  "exportAll": "Exportar todo a CSV",
  "options": "Opciones",
  "zoomto": "Acercar a",
  "highlight": "Resaltar gráficos",
  "selectAll": "Seleccionar registros en todas las páginas",
  "selectPage": "Seleccionar registros en la página actual",
  "clearSelection": "Borrar selección",
  "filter": "Filtro",
  "setFilterTip": "Defina los filtros correctamente.",
  "noFilterTip": "Sin expresiones de filtro definidas, esta tarea de consulta mostrará todas las entidades de la fuente de datos especificada.",
  "filterByExtent": "Filtrar por extensión de mapa",
  "showSelectedRecords": "Mostrar registros seleccionados",
  "showAllRecords": "Mostrar todos los registros",
  "showRelatedRecords": "Mostrar registros relacionados",
  "noRelatedRecords": "No se encontraron registros relacionados",
  "attachmentColumn": "Fotos y archivos",
  "refresh": "Actualizar",
  "features": "entidades",
  "records": "registros",
  "selected": "seleccionado",
  "transparent": "Modo transparente",
  "indicate": "Localizar selección",
  "columns": "Mostrar/Ocultar columnas",
  "selectionSymbol": "Símbolo de selección",
  "closeMessage": "Ocultar tabla (volver a expandirla desde la parte inferior)",
  "dataNotAvailable": "¡Datos no disponibles!<br>Haz clic en el botón [Actualizar] para intentarlo de nuevo.",
  "openTableTip": "Abrir tabla de atributos",
  "closeTableTip": "Ocultar tabla de atributos",
  "sortAsc": "Orden ascendente",
  "sortDes": "Orden descendente",
  "statistics": "Estadísticas",
  "attachments": "Adjuntos",
  "files": "archivos"
});