define(
   ({
    id: 'Tunnus',
    state: "Oletusarvon mukaan koordinaatit näytetään nykyisen kartan koordinaattijärjestelmässä. Jos haluat noutaa koordinaatit toisesta koordinaattijärjestelmästä, sinun on lisättävä ne ja määritettävä asianmukaiset transformaatiot.",
    outputUnit: "Tulosyksikkö",
    wkid: "Tulosaineiston WKID",
    label: "Anna koordinaattijärjestelmän nimi",
    transformationWkid: "Transformaatio WKID",
    transformationLabel: "Transformaation tunnusteksti",
    transformForward: "Transformoi eteenpäin",
    actions: "Toimet",
    warning: "Anna kelvollinen koordinaattijärjestelmän WKID!",
    tfWarning: "Anna kelvollinen datumin transformaatio WKID!",
    spinnerLabel: "Pyöristä koordinaatit: ",
    decimalPlace: "desimaalit",
    separator: "Näytä tuhaterottimet",
    getVersionError: "Geometriapalvelun versiotietoja ei voi noutaa",

    add: "Lisää tulosaineiston koordinaattijärjestelmä",
    edit: "Muokkaa koordinaattijärjestelmää",
    output: "Tulosaineiston koordinaattijärjestelmä",
    cName: "Koordinaattijärjestelmän nimi",
    units: "Näyttöyksiköt: ",
    datum: "Datumin transformaatio",
    tName: "Transformaation nimi",
    tWKIDPlaceHolder: "Transformaation WKID",
    forward: "Käytä transformaatiota eteenpäin",
    ok: "OK",
    cancel: 'Peruuta',
    olderVersion: "Geometriapalvelu ei tue transformaatiota",
    REPEATING_ERROR: " Koordinaattijärjestelmä on syöteluettelossa.",

    Default: "Oletus",
    Inches: "tuumaa",
    Foot: "Jalkaa",
    Yards: "Jaardia",
    Miles: "Mailia",
    Nautical_Miles: "Meripeninkulmaa",
    Millimeters: "millimetriä",
    Centimeters: "senttimetriä",
    Meter: "Metriä",
    Kilometers: "Kilometriä",
    Decimeters: "desimetriä",
    Decimal_Degrees: "desimaaliastetta",
    Degree_Minutes_Seconds: "astetta, minuuttia, sekuntia",
    MGRS: "MGRS",
    USNG: "USNG"
  })
);