define(
   ({
    "sourceSetting": "Nastavení zdroje vyhledávání",
    "instruction": "Umožňuje přidat a konfigurovat služby Geocode nebo prvky vrstev jako zdroje vyhledávání. Tyto zadané zdroje určují, jaký obsah je možné vyhledávat v rámci pole vyhledávání.",
    "add": "Přidat zdroj vyhledávání",
    "addGeocoder": "Přidat geokodér",
    "geocoder": "Geokodér",
    "setLayerSource": "Nastavit zdroj vrstvy",
    "setGeocoderURL": "Nastavit adresu URL geokodéru",
    "searchableLayer": "Vrstva prvků",
    "name": "Jméno",
    "countryCode": "Kódy země nebo oblasti",
    "countryCodeEg": "např. ",
    "countryCodeHint": "Pokud toto pole ponecháte prázdné, prohledají se všechny země a oblasti",
    "generalSetting": "Obecná nastavení",
    "allPlaceholder": "Zástupný text pro vyhledávání všech výsledků: ",
    "showInfoWindowOnSelect": "Zobrazit vyskakovací okno pro nalezený prvek nebo umístění",
    "searchInCurrentMapExtent": "Vyhledávat pouze v aktuálním rozsahu mapy",
    "locatorUrl": "URL geokodéru",
    "locatorName": "Název geokodéru",
    "locatorExample": "Příklad",
    "locatorWarning": "Tato verze služby geokódování není podporována. Tento widget podporuje služby geokódování ve verzi 00.0 a vyšší.",
    "locatorTips": "Návrhy nejsou k dispozici, protože služba geokódování nepodporuje funkcionalitu návrhů.",
    "layerSource": "Zdroj vrstvy",
    "searchLayerTips": "Návrhy nejsou k dispozici, protože služba Feature Service nepodporuje funkcionalitu stránkování.",
    "placeholder": "Zástupný text",
    "searchFields": "Prohledávané pole",
    "displayField": "Zobrazované pole",
    "exactMatch": "Přesná shoda",
    "maxResults": "Maximální počet výsledků",
    "setSearchFields": "Nastavit prohledávané pole",
    "set": "Nastavit",
    "fieldSearchable": "prohledávatelné",
    "fieldName": "Jméno",
    "fieldAlias": "Alternativní jméno",
    "ok": "OK",
    "cancel": "Storno",
    "invalidUrlTip": "Zadaná adresa URL je neplatná nebo nepřístupná."
  })
);