define({
  "id": "ID",
  "state": "Secara default, koordinat akan ditampilkan sama dengan sistem koordinat peta saat ini. Untuk mendapatkan koordinat dengan sistem koordinat lain, Anda harus menambahkannya dan menentukan transformasi yang tepat.",
  "outputUnit": "Unit output",
  "wkid": "WKID Output",
  "label": "Nama sistem koordinat output",
  "transformationWkid": "Transformasi WKID",
  "transformationLabel": "Label transformasi",
  "transformForward": "Transformasikan ke depan",
  "actions": "Tindakan",
  "warning": "Masukkan referensi spasial WKID yang valid!",
  "tfWarning": "Masukkan transformasi datum WKID yang valid!",
  "spinnerLabel": "Bulatkan koordinat menjadi: ",
  "decimalPlace": "decimal places",
  "separator": "Tampilkan pemisah ribuan",
  "getVersionError": "Tidak bisa mendapatkan versi service geometri",
  "add": "Tambahkan sistem koordinat output",
  "edit": "Edit sistem koordinat",
  "output": "Sistem koordinat output",
  "cName": "Nama sistem koordinat",
  "units": "Unit tampilan: ",
  "datum": "Transformasi datum",
  "tName": "Nama transformasi",
  "tWKIDPlaceHolder": "transformasi WKID",
  "forward": "Gunakan transformasi ke depan",
  "ok": "Ya",
  "cancel": "Batal",
  "olderVersion": "Service geometri tidak mendukung operasi transformasi",
  "REPEATING_ERROR": " Terdapat sistem koordinat di daftar output.",
  "Default": "Default",
  "Inches": "Inci",
  "Foot": "Kaki",
  "Yards": "Yard",
  "Miles": "Mil",
  "Nautical_Miles": "Mil laut",
  "Millimeters": "Milimeter",
  "Centimeters": "Sentimeter",
  "Meter": "Meter",
  "Kilometers": "Kilometer",
  "Decimeters": "Desimeter",
  "Decimal_Degrees": "Derajat desimal",
  "Degrees_Decimal_Minutes": "Derajat menit desimal",
  "Degree_Minutes_Seconds": "Derajat menit detik",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Urutan tampilan kordinat:",
  "lonLatTips": "Garis Bujur / Garis Lintang (X, Y)",
  "latLonTips": "Garis Lintang / Garis Bujur (Y, X)"
});