define({
  "_widgetLabel": "Slāņu saraksts",
  "titleBasemap": "Pamatkartes",
  "titleLayers": "Operacionālie slāņi",
  "labelLayer": "Slāņa nosaukums",
  "itemZoomTo": "Pietuvināt",
  "itemTransparency": "Caurspīdīgums",
  "itemTransparent": "Caurspīdīgs",
  "itemOpaque": "Necaurredzams",
  "itemMoveUp": "Pārvietot uz augšu",
  "itemMoveDown": "Pārvietot uz leju",
  "itemDesc": "Apraksts",
  "itemDownload": "Lejupielāde",
  "itemToAttributeTable": "Skatīt atribūtu tabulā",
  "itemShowItemDetails": "Parādīt vienību detaļas",
  "empty": "tukšs",
  "removePopup": "Deaktivizēt uznirstošo logu",
  "enablePopup": "Aktivizēt uznirstošo logu",
  "turnAllLayersOff": "Izslēgt visus slāņus",
  "turnAllLayersOn": "Ieslēgt visus slāņus",
  "expandAllLayers": "Izvērst visus slāņus",
  "collapseAlllayers": "Sakļaut visus slāņus",
  "turnAllLabelsOff": "Izslēgt visus kartes tekstus",
  "turnAllLabelsOn": "Ieslēgt visus kartes tekstus",
  "showLabels": "Rādīt kartes tekstus",
  "hideLables": "Paslēpt kartes tekstus"
});