define({
  "_widgetLabel": "Karttatasot",
  "titleBasemap": "Taustakartat",
  "titleLayers": "Toiminnalliset karttatasot",
  "labelLayer": "Karttatason nimi",
  "itemZoomTo": "Tarkenna kohteeseen",
  "itemTransparency": "Läpinäkyvyys",
  "itemTransparent": "Läpinäkyvä",
  "itemOpaque": "Läpinäkymätön",
  "itemMoveUp": "Siirrä ylös",
  "itemMoveDown": "Siirrä alas",
  "itemDesc": "Kuvaus",
  "itemDownload": "Lataa",
  "itemToAttributeTable": "Näytä ominaisuustaulukossa",
  "itemShowItemDetails": "Näytä kohteen tiedot",
  "empty": "tyhjä",
  "removePopup": "Poista ponnahdusikkunat käytöstä",
  "enablePopup": "Ota ponnahdusikkunat käyttöön",
  "turnAllLayersOff": "Poista kaikki karttatasot käytöstä",
  "turnAllLayersOn": "Ota kaikki karttatasot käyttöön",
  "expandAllLayers": "Laajenna kaikki karttatasot",
  "collapseAlllayers": "Tiivistä kaikki karttatasot",
  "turnAllLabelsOff": "Poista kaikki tunnustekstit käytöstä",
  "turnAllLabelsOn": "Ota kaikki tunnustekstit käyttöön",
  "showLabels": "Näytä tunnustekstit",
  "hideLables": "Piilota tunnustekstit"
});