define({
  "_widgetLabel": "מערכת קואורדינטות",
  "hintMessage": "הקש במפה לקבלת קואורדינטות.",
  "defaultLabel": "ברירת מחדל",
  "realtimeLabel": "הזז את העכבר כדי לקבל קואורדינטות",
  "computing": "מחשב...",
  "latitudeLabel": "קו רוחב",
  "longitudeLabel": "קו אורך",
  "loading": "טוען...",
  "enableClick": "לחץ כדי להפעיל לחיצה על המפה לקבלת קואורדינטות",
  "disableClick": "לחץ כדי לבטל לחיצה על המפה לקבלת קואורדינטות",
  "Default": "ברירת מחדל",
  "Inches": "אינצ׳ים",
  "Foot": "רגל",
  "Yards": "יארד",
  "Miles": "מיילים",
  "Nautical_Miles": "מיילים ימיים",
  "Millimeters": "מילימטרים",
  "Centimeters": "סנטימטרים",
  "Meter": "מטרים",
  "Kilometers": "קילומטרים",
  "Decimeters": "דצימטרים",
  "Decimal_Degrees": "מעלות",
  "Degree_Minutes_Seconds": "מעלות דקות שניות",
  "MGRS": "MGRS",
  "USNG": "USNG"
});