define({
  "_widgetLabel": "Sluoksniai",
  "titleBasemap": "Pagrindo žemėlapiai",
  "titleLayers": "Darbiniai sluoksniai",
  "labelLayer": "Sluoksnio pavadinimas",
  "itemZoomTo": "Parodyti visą",
  "itemTransparency": "Permatomumas",
  "itemTransparent": "Permatomas",
  "itemOpaque": "Nepermatomas",
  "itemMoveUp": "Pakelti aukštyn",
  "itemMoveDown": "Nuleisti žemyn",
  "itemDesc": "Aprašas",
  "itemDownload": "Atsiųsti",
  "itemToAttributeTable": "Peržiūrėti atributų lentelėje",
  "itemShowItemDetails": "Rodyti elemento aprašą",
  "empty": "tuščia",
  "removePopup": "Išjungti iškylančius langus",
  "enablePopup": "Įjungti iškylančius langus",
  "turnAllLayersOff": "Išjungti visus sluoksnius",
  "turnAllLayersOn": "Įjungti visus sluoksnius",
  "expandAllLayers": "Išskleisti visus sluoksnius",
  "collapseAlllayers": "Sutraukti visus sluoksnius",
  "turnAllLabelsOff": "Išjungti visas žymes",
  "turnAllLabelsOn": "Įjungti visas žymes",
  "showLabels": "Rodyti žymes",
  "hideLables": "Slėpti žymes"
});