define({
  "instruction": "Vyberte a nakonfigurujte vrstvy, které se zpočátku zobrazí v atributové tabulce.",
  "label": "Vrstva",
  "show": "Zobrazit",
  "actions": "Konfigurovat pole vrstvy",
  "field": "Pole",
  "alias": "Přezdívka",
  "visible": "Viditelná",
  "linkField": "Pole odkazů",
  "noLayers": "Nejsou k dispozici žádné vrstvy",
  "back": "Zpět",
  "exportCSV": "Povolit export do CSV",
  "expand": "Rozšířit widget po přidání",
  "filterByExtent": "Povolit výchozí filtrování podle rozsahu mapy",
  "restore": "Obnovit výchozí hodnotu",
  "ok": "OK",
  "cancel": "Storno",
  "includePoint": "Do exportovaného souboru zahrnout bodové souřadnice",
  "configureLayerFields": "Konfigurovat pole vrstvy",
  "result": "Úspěšně uloženo",
  "warning": "Nejprve zvolte možnost zobrazení.",
  "fieldCheckWarning": "Musí být vybráno nejméně jedno pole.",
  "unsupportQueryWarning": "Vrstva musí podporovat operace založené na dotazu, aby bylo možné ji zobrazovat ve widgetu Atributová tabulka. Ujistěte se, že je ve službě aktivní možnost dotazování.",
  "unsupportQueryLayers": "Následující vrstva musí podporovat operace na základě dotazu, aby bylo možné ji zobrazovat ve widgetu Atributová tabulka. Ujistěte se, že je ve službě povolena možnost dotazování.",
  "fieldName": "Název",
  "fieldAlias": "Přezdívka",
  "fieldVisibility": "Viditelnost",
  "fieldActions": "Akce",
  "showAttachments": "Zobrazit přílohy"
});