define({
  "instruction": "Käivituskuva kuvatakse enne seda, kui rakendus on kättesaadav.",
  "defaultContent": "Siia saate lisada teksti, lingid ja väiksemad pildid.",
  "requireConfirm": "Jätkamiseks nõua kinnitust",
  "noRequireConfirm": "Ei vaja jätkamiseks kinnitust",
  "optionText": "Kasutajal on võimalus keelata käivituskuva kuvamine rakenduse käivitamisel.",
  "confirmLabel": "Kinnituse tekstid: ",
  "confirmLabelColor": "Kinnitustekstide värv",
  "defaultConfirmText": "Nõustun ülaltoodud tingimustega",
  "confirmOption": "Kuva vastav käivitamise aken alati, kui rakendus aktiveeritakse",
  "backgroundColor": "Taustvärv",
  "content": "Sisu",
  "contentDescription": "Saate käivituskuval näidatavat sisu määratleda.",
  "appearance": "Välimus",
  "appearanceDescription": "Saate määrata käivituskuva ilme.",
  "size": "Suurus",
  "width": "Laius",
  "height": "Kõrgus",
  "custom": "Kohandatud",
  "background": "Taust",
  "colorFill": "Värvitäide",
  "imageFill": "Pilditäide",
  "chooseFile": "Vali fail",
  "noFileChosen": "Faili pole valitud",
  "transparency": "Läbipaistvus",
  "sizeFill": "Täitevärv",
  "sizeFit": "Sobita",
  "sizeStretch": "Venita täitmiseks",
  "sizeCenter": "Keskel",
  "sizeTile": "Pildiüksus",
  "buttonColor": "Nupu värv",
  "buttonText": "Nupu tekst",
  "buttonTextColor": "Nupu teksti värv",
  "contentAlign": "Sisu paigutamine",
  "alignTop": "Ülemine",
  "alignMiddle": "Keskmine",
  "maskColor": "Maski värv",
  "options": "Valikud",
  "optionsDescription": "Saate määrata käivituskuva käitumise."
});