define({
  "instruction": "Der Einführungsbildschirm wird angezeigt, bevor auf die Anwendung zugegriffen werden kann.",
  "defaultContent": "Hier können Sie Text, Links und kleine Grafiken hinzufügen.",
  "requireConfirm": "Bestätigung zum Fortfahren erforderlich",
  "noRequireConfirm": "Keine Bestätigung zum Fortfahren erforderlich",
  "optionText": "Option für Benutzer zum Deaktivieren des Einführungsbildschirms beim Starten der Anwendung.",
  "confirmLabel": "Bestätigungstext: ",
  "confirmLabelColor": "Schriftfarbe für Bestätigungstext",
  "defaultConfirmText": "Ich stimme den vorgenannten Bedingungen zu",
  "confirmOption": "Diesen Einführungsbildschirm bei jedem Starten der App anzeigen",
  "backgroundColor": "Hintergrundfarbe",
  "content": "Inhalt",
  "contentDescription": "Den Inhalt definieren, der auf dem Einführungsbildschirm angezeigt wird.",
  "appearance": "Aussehen",
  "appearanceDescription": "Das Aussehen des Einführungsbildschirms festlegen.",
  "size": "Größe",
  "width": "Breite",
  "height": "Höhe",
  "custom": "Benutzerdefiniert",
  "background": "Hintergrund",
  "colorFill": "Farbfüllung",
  "imageFill": "Bildfüllung",
  "chooseFile": "Datei auswählen",
  "noFileChosen": "Keine Datei ausgewählt",
  "transparency": "Transparenz",
  "sizeFill": "Füllung",
  "sizeFit": "Einpassen",
  "sizeStretch": "Zu füllende Streckung",
  "sizeCenter": "Mittelpunkt",
  "sizeTile": "Kachel",
  "buttonColor": "Schaltflächenfarbe",
  "buttonText": "Schaltflächentext",
  "buttonTextColor": "Textfarbe der Schaltfläche",
  "contentAlign": "Ausrichtung des Inhalts",
  "alignTop": "Oben",
  "alignMiddle": "Mitte",
  "maskColor": "Maskenfarbe",
  "options": "Optionen",
  "optionsDescription": "Das Verhalten des Einführungsbildschirms festlegen."
});