define({
  "common": {
    "apply": "Áp dụng",
    "ok": "OK",
    "cancel": "Hủy",
    "yes": "Có",
    "no": "Không",
    "next": "Tiếp",
    "previous": "Trước",
    "back": "Quay lại",
    "selected": "đã chọn",
    "name": "Tên",
    "usage": "Sử dụng",
    "settings": "Thiết lập",
    "home": "Trang chủ",
    "link": "Liên kết",
    "messages": "Thông báo",
    "outputs": "Đầu ra",
    "title": "Tiêu đề",
    "thumbnail": "Hình thu nhỏ",
    "url": "URL",
    "actions": "Các hành động",
    "layer": "Lớp",
    "action": "Hành động",
    "input": "Đầu vào",
    "output": "Đầu ra",
    "type": "Loại",
    "required": "Yêu cầu",
    "options": "Tùy chọn",
    "label": "Nhãn",
    "tooltip": "Chú giải công cụ",
    "visible": "Hiển thị",
    "symbol": "Ký hiệu",
    "popup": "Cửa sổ pop-up",
    "upload": "Tải lên",
    "execute": "Thực hiện",
    "help": "Trợ giúp",
    "executing": "Thực hiện",
    "clear": "Xóa",
    "error": "Lỗi",
    "zoomTo": "Phóng tới",
    "attribute": "Thuộc tính",
    "exports": "Xuất",
    "check": "Kiểm tra",
    "save": "Lưu",
    "close": "Đóng",
    "deleteText": "Xóa",
    "map": "Bản đồ",
    "scene": "Scene",
    "reset": "Thiết lập lại",
    "icon": "Biểu tượng",
    "folder": "Thư mục",
    "share": "Chia sẻ",
    "view": "Xem",
    "newText": "Mới",
    "edit": "Chỉnh sửa",
    "wkid": "WKID",
    "table": "Bảng",
    "zoomIn": "Thu nhỏ",
    "zoomOut": "Phóng to",
    "continue1": "Tiếp",
    "longitude": "Kinh độ",
    "latitude": "Vĩ độ",
    "custom": "Tùy chỉnh",
    "image": "Hình ảnh",
    "font": "Phông chữ",
    "text": "Văn bản",
    "all": "Tất cả",
    "number": "Số",
    "percentage": "Phần trăm",
    "unit": "Đơn vị",
    "thousand": "Ngàn",
    "billion": "Tỷ",
    "million": "Triệu",
    "none": "Không có",
    "field": "Trường",
    "operation": "Hoạt động",
    "disableUpdateGeometry": "Tắt Cập nhật Hình học",
    "preview": "Xem trước"
  },
  "errorCode": "Mã",
  "errorMessage": "Thông báo",
  "errorDetail": "Chi tiết",
  "widgetPlaceholderTooltip": "Để thiết lập, đi tới Tiện ích và bấm vào trình giữ chỗ tương ứng",
  "fieldStatistics": {
    "selectField": "Chọn trường",
    "statistics": "Thống kê",
    "field": "Trường",
    "count": "Số lượng các giá trị",
    "sum": "Tổng số các giá trị",
    "min": "Tối thiểu",
    "max": "Tối đa",
    "ave": "Trung bình",
    "stddev": "Độ lệch chuẩn"
  },
  "symbolChooser": {
    "preview": "Xem trước",
    "basic": "Cơ bản",
    "arrows": "Mũi tên",
    "business": "Kinh doanh",
    "cartographic": "Bản đồ",
    "nationalParkService": "Cục công viên quốc gia",
    "outdoorRecreation": "Giải trí ngoài trời",
    "peoplePlaces": "Địa điểm công cộng",
    "safetyHealth": "Sức khỏe an toàn",
    "shapes": "Các hình dạng",
    "transportation": "Giao thông Vận tải",
    "symbolSize": "Kích cỡ ký hiệu",
    "color": "Màu sắc",
    "alpha": "Alpha",
    "outlineColor": "Màu đường viền",
    "outlineWidth": "Độ rộng đường viền",
    "style": "Kiểu",
    "width": "Chiều rộng",
    "text": "Văn bản",
    "fontColor": "Màu phông chữ",
    "fontSize": "Cỡ chữ",
    "transparency": "Độ trong suốt",
    "solid": "Đậm",
    "dash": "Gạch",
    "dot": "Chấm",
    "dashDot": "Chấm gạch",
    "dashDotDot": "Gạch chấm chấm",
    "customImage": "Hình ảnh tùy chỉnh",
    "chooseFile": "Chọn tệp",
    "noFileChoosen": "Không có tệp được chọn."
  },
  "transparency": {
    "opaque": "Độ mờ",
    "transparent": "Độ trong suốt"
  },
  "rendererChooser": {
    "domain": "Miền",
    "use": "Sử dụng",
    "singleSymbol": "Một ký hiệu đơn",
    "uniqueSymbol": "Các ký hiệu duy nhất",
    "color": "Màu sắc",
    "size": "Kích cỡ",
    "toShow": "Thể hiện",
    "colors": "Màu sắc",
    "classes": "Các lớp",
    "symbolSize": "Kích cỡ ký hiệu",
    "addValue": "Thêm giá trị",
    "setDefaultSymbol": "Thiết lập ký hiệu mặc định",
    "defaultSymbol": "Ký hiệu mặc định",
    "selectedSymbol": "Ký hiệu đã chọn",
    "value": "Giá trị",
    "label": "Nhãn",
    "range": "Phạm vi"
  },
  "drawBox": {
    "point": "Điểm",
    "line": "Đường",
    "polyline": "Đa tuyến",
    "freehandPolyline": "Đa tuyến vẽ tay",
    "triangle": "Hình tam giác",
    "extent": "Phạm vi",
    "circle": "Hình tròn",
    "ellipse": "Hình Elip",
    "polygon": "Vùng",
    "freehandPolygon": "Vùng vẽ tự do",
    "text": "Văn bản",
    "clear": "Xóa"
  },
  "popupConfig": {
    "title": "Tiêu đề",
    "add": "Thêm",
    "fields": "Trường",
    "noField": "Không có trường nào",
    "visibility": "Hiển thị",
    "name": "Tên",
    "alias": "Bí danh",
    "actions": "Các hành động"
  },
  "includeButton": {
    "include": "Bao gồm"
  },
  "loadingShelter": {
    "loading": "Đang tải"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Không tìm thấy dịch vụ nào.",
    "unableConnectTo": "Không thể kết nối với",
    "invalidUrlTip": "URL bạn vừa nhập không hợp lệ hoặc không thể truy cập được."
  },
  "serviceBrowser": {
    "noGpFound": "Không tìm thấy dịch vụ địa xử lý thông tin nào.",
    "unableConnectTo": "Không thể kết nối với"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Không tìm thấy dịch vụ bản đồ hoặc dịch vụ đối tượng nào.",
    "unableConnectTo": "Không thể kết nối với"
  },
  "basicServiceChooser": {
    "validate": "Xác minh",
    "example": "Ví dụ",
    "set": "Thiết lập"
  },
  "urlInput": {
    "invalidUrl": "Url không hợp lệ."
  },
  "urlComboBox": {
    "invalidUrl": "Url không hợp lệ."
  },
  "filterBuilder": {
    "addAnotherExpression": "Thêm biểu thức",
    "addSet": "Thêm một bộ",
    "matchMsg": "Lấy các đối tượng trong lớp trùng khớp với ${any_or_all} các biểu thức sau",
    "matchMsgSet": "${any_or_all} của các biểu thức sau trong tập hợp này là đúng",
    "all": "Tất cả",
    "any": "Bất kỳ",
    "value": "Giá trị",
    "field": "Trường",
    "unique": "Duy nhất",
    "none": "Không có",
    "and": "và",
    "valueTooltip": "Nhập vào giá trị",
    "fieldTooltip": "Chọn từ trường hiện có",
    "uniqueValueTooltip": "Lấy từ các giá trị duy nhất trong trường được chọn",
    "stringOperatorIs": "là",
    "stringOperatorIsNot": "không phải là",
    "stringOperatorStartsWith": "bắt đầu với",
    "stringOperatorEndsWith": "kết thúc với",
    "stringOperatorContains": "chứa",
    "stringOperatorDoesNotContain": "không chứa",
    "stringOperatorIsBlank": "trống",
    "stringOperatorIsNotBlank": "không trống",
    "dateOperatorIsOn": "vào ngày",
    "dateOperatorIsNotOn": "không vào ngày",
    "dateOperatorIsBefore": "trước",
    "dateOperatorIsAfter": "sau",
    "dateOperatorIsOnOrBefore": "vào ngày hoặc trước",
    "dateOperatorIsOnOrAfter": "vào ngày hoặc sau",
    "dateOperatorMinutes": "phút",
    "dateOperatorHours": "giờ",
    "dateOperatorDays": "ngày",
    "dateOperatorWeeks": "tuần",
    "dateOperatorMonths": "tháng",
    "dateOperatorYears": "các năm",
    "dateOperatorInTheLast": "trong ngày cuối",
    "dateOperatorNotInTheLast": "không phải cuối cùng",
    "dateOperatorIsBetween": "ở giữa",
    "dateOperatorIsNotBetween": "không ở giữa",
    "dateOperatorIsBlank": "trống",
    "dateOperatorIsNotBlank": "không trống",
    "numberOperatorIs": "là",
    "numberOperatorIsNot": "không phải là",
    "numberOperatorIsAtLeast": "tối thiểu",
    "numberOperatorIsLessThan": "ít hơn",
    "numberOperatorIsAtMost": "tối đa",
    "numberOperatorIsGreaterThan": "nhiều hơn",
    "numberOperatorIsBetween": "ở giữa",
    "numberOperatorIsNotBetween": "không ở giữa",
    "numberOperatorIsBlank": "trống",
    "numberOperatorIsNotBlank": "không trống",
    "string": "String",
    "number": "Số",
    "date": "Ngày",
    "askForValues": "Yêu cầu các giá trị",
    "prompt": "Lời nhắc",
    "hint": "Gợi ý",
    "error": {
      "invalidParams": "Tham số không hợp lệ.",
      "invalidUrl": "Url không hợp lệ.",
      "noFilterFields": "Lớp không có trường nào có thể dùng để tạo bộ lọc.",
      "invalidSQL": "Biểu thức SQL không hợp lệ.",
      "cantParseSQL": "Không thể phân tích biểu thức SQL."
    },
    "caseSensitive": "Phân biệt chữ hoa chữ thường",
    "notSupportCaseSensitiveTip": "Dịch vụ được lưu trữ không hỗ trợ truy vấn phân biệt chữ hoa chữ thường.",
    "setFilterTip": "Vui lòng thiết lập bộ lọc chính xác.",
    "listValues": "Liệt kê giá trị",
    "cascadeFilterTip": "Chỉ hiện các giá trị được lọc bởi các biểu thức trước đó.",
    "noneCascadeFilterTip": "Tất cả các giá trị riêng của trường này",
    "previousCascadeFilterTip": "Các giá trị được lọc bởi các biểu thức trước đó",
    "allCascadeFilterTip": "Các giá trị được lọc bởi tất cả các biểu thức khác"
  },
  "featureLayerSource": {
    "layer": "Lớp",
    "browse": "Duyệt",
    "selectFromMap": "Bản đồ",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL Dịch vụ",
    "inputLayerUrl": "URL lớp đầu vào",
    "selectLayer": "Chọn một lớp đối tượng từ bản đồ hiện tại.",
    "chooseItem": "Chọn một mục lớp đối tượng.",
    "setServiceUrl": "Nhập URL của dịch vụ đối tượng hoặc dịch vụ bản đồ.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Chọn một lớp đối tượng."
  },
  "queryableLayerSource": {
    "layer": "Lớp",
    "browse": "Duyệt",
    "selectFromMap": "Bản đồ",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL Dịch vụ",
    "inputLayerUrl": "URL lớp đầu vào",
    "selectLayer": "Chọn một lớp từ bản đồ hiện tại.",
    "chooseItem": "Chọn một mục.",
    "setServiceUrl": "Nhập URL của dịch vụ.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Chọn lớp."
  },
  "gpSource": {
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL Dịch vụ",
    "selectFromOnline": "ArcGIS Online",
    "setServiceUrl": "Nhập URL của dịch vụ địa xử lý.",
    "chooseItem": "Chọn một mục dịch vụ địa xử lý.",
    "chooseTask": "Chọn một tác vụ địa xử lý."
  },
  "itemSelector": {
    "map": "Bản đồ",
    "selectWebMap": "Chọn bản đồ web",
    "addMapFromOnlineOrPortal": "Tìm và thêm bản đồ web trong ứng dụng từ các tài nguyên công khai của ArcGIS Online hoặc nội dung riêng tư của bạn trong ArcGIS Online hoặc Portal.",
    "searchMapName": "Tìm kiếm theo tên bản đồ...",
    "searchNone": "Chúng tôi không thể tìm thấy nội dung bạn đang tìm kiếm. Vui lòng thử lại.",
    "groups": "Nhóm",
    "noneGroups": "Không có nhóm nào",
    "signInTip": "Lần đăng nhập của bạn đã hết hạn, vui lòng làm mới trình duyệt để đăng nhập lại vào cổng thông tin.",
    "signIn": "Đăng nhập",
    "publicMap": "Công khai",
    "myOrganization": "Tổ chức của tôi",
    "myGroup": "Nhóm của tôi",
    "myContent": "Nội dung của tôi",
    "count": "Số lượng",
    "fromPortal": "từ Cổng thông tin",
    "fromOnline": "từ ArcGIS.com",
    "noneThumbnail": "Hình thu nhỏ không khả dụng",
    "owner": "chủ sở hữu",
    "signInTo": "Đăng nhập vào",
    "lastModified": "Chỉnh sửa lần cuối",
    "moreDetails": "Chi tiết khác",
    "mostRecent": "Gần đây nhất",
    "mostViewed": "Được xem nhiều nhất",
    "highestRated": "Đánh giá cao nhất",
    "viewItemDetails": "Xem chi tiết mục"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Dịch vụ không hỗ trợ truy vấn."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Không có lớp thích hợp nào trong bản đồ."
  },
  "layerInfosMenu": {
    "titleBasemap": "Bản đồ nền",
    "titleLayers": "Các lớp hoạt động",
    "labelLayer": "Tên lớp",
    "itemZoomTo": "Phóng tới",
    "itemTransparency": "Độ trong suốt",
    "itemTransparent": "Độ trong suốt",
    "itemOpaque": "Độ mờ",
    "itemMoveUp": "Di chuyển lên trên",
    "itemMoveDown": "Di chuyển xuống dưới",
    "itemDesc": "Mô tả",
    "itemDownload": "Tải xuống",
    "itemToAttributeTable": "Xem trong Bảng Thuộc tính"
  },
  "imageChooser": {
    "unsupportReaderAPI": "Cần làm: Trình duyệt này không hỗ trợ API bộ đọc tệp",
    "readError": "Không thể đọc tệp.",
    "unknowError": "không thể hoàn thành hoạt động",
    "invalidType": "Loại tệp không hợp lệ.",
    "cropImage": "Xén Ảnh",
    "exceed": "Kích cỡ tệp không được vượt quá 1024 KB",
    "enableFlash": "Vui lòng kích hoạt Adobe Flash trước khi duyệt tìm hình ảnh.",
    "cropWaining": "Vui lòng chọn ảnh có kích thước tối thiểu ${width} x ${height} pixel.",
    "toolTip": "Để có kết quả tốt nhất, hình ảnh phải rộng ${width} pixel và cao ${height} pixel. Các kích cỡ khác sẽ được điều chỉnh cho phù hợp. Các định dạng hình ảnh được chấp nhận là: PNG, GIF và JPEG."
  },
  "simpleTable": {
    "moveUp": "Di chuyển lên trên",
    "moveDown": "Di chuyển xuống dưới",
    "deleteRow": "Xóa",
    "edit": "Chỉnh sửa"
  },
  "urlParams": {
    "invalidToken": "Mã token không hợp lệ",
    "validateTokenError": "Mã token không hợp lệ hoặc lỗi Mạng"
  },
  "exportTo": {
    "exportTo": "Xuất",
    "toCSV": "Xuất ra tệp CSV",
    "toFeatureCollection": "Xuất ra bộ sưu tập đối tượng",
    "toGeoJSON": "Xuất ra GeoJSON"
  },
  "appState": {
    "title": "Trạng thái Ứng dụng",
    "restoreMap": "Bấm vào để khôi phục khả năng hiển thị của phạm vi bản đồ và các lớp khi bạn rời đi."
  },
  "featureActions": {
    "featureActions": "Các hoạt động cho đối tượng",
    "ZoomTo": "Phóng tới",
    "PanTo": "Quay để",
    "Flash": "Đèn flash",
    "ShowPopup": "Hiển thị cửa sổ pop-up",
    "CreateLayer": "Tạo lớp",
    "ShowStatistics": "Thống kê...",
    "ClearSelection": "Xóa lựa chọn",
    "ExportToCSV": "Xuất ra tệp CSV",
    "ShowSelectedFeature": "Hiển thị đối tượng được chọn",
    "ExportToFeatureCollection": "Xuất ra bộ sưu tập đối tượng",
    "ExportToGeoJSON": "Xuất ra GeoJSON",
    "EditAttributes": "Chỉnh sửa thuộc tính",
    "AddMarker": "Thêm điểm đánh dấu",
    "RemoveMarker": "Xóa điểm đánh dấu",
    "SaveToMyContent": "Lưu vào Nội dung của Tôi"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Lớp có liên quan",
    "selectedFeatures": "Sử dụng các đối tượng được chọn",
    "drawShapesTip": "Vẽ các hình để chọn đối tượng",
    "pleaseDrawShapesTip": "Hãy vẽ các hình để chọn đối tượng",
    "allFeaturesTip": "Tất cả đối tượng trong lớp",
    "selectFeaturesOrDrawShapesTip": "Hãy sử dụng các đối tượng được chọn trong lớp này hoặc vẽ các hình trên bản đồ để giới hạn đối tượng."
  },
  "searchDistance": {
    "applySearchDistance": "Áp dụng khoảng cách tìm kiếm",
    "applySearchDistanceToFeatures": "Áp dụng khoảng cách tìm kiếm cho đối tượng được chọn"
  },
  "units": {
    "miles": "Dặm",
    "milesAbbr": "mi",
    "kilometers": "Kilômét",
    "kilometersAbbr": "km",
    "feet": "Bộ",
    "feetAbbr": "ft",
    "meters": "Mét",
    "metersAbbr": "m",
    "yards": "Thước",
    "yardsAbbr": "yd",
    "acres": "Acre",
    "acresAbbr": "acre",
    "nauticalMiles": "Hải lý",
    "nauticalMilesAbbr": "nmi",
    "uSSurveyFeet": "Feet khảo sát US",
    "uSSurveyFeetAbbr": "ftUS",
    "decimalDegree": "Độ thập phân",
    "decimalDegreeAbbr": "dd",
    "degreeMinuteSeconds": "Độ phút giây",
    "degreeMinuteSecondsAbbr": "độ-phút-giây",
    "squareMiles": "Dặm vuông",
    "squareMilesAbbr": "mi2",
    "squareKilometer": "Kilômét vuông",
    "squareKilometerAbbr": "km2",
    "squareFeet": "Feet vuông",
    "squareFeetAbbr": "ft2",
    "squareMeters": "Mét vuông",
    "squareMetersAbbr": "m2",
    "squareYards": "Thước vuông",
    "squareYardsAbbr": "yd2",
    "squareUSSurveyFeet": "Feet khảo sát US vuông",
    "squareUSSurveyFeetAbbr": "sq ftUS"
  },
  "featureSetChooser": {
    "select": "Chọn",
    "dragBox": "Kéo",
    "dragMouse": "Kéo chuột",
    "selectByRectangle": "Chọn theo hình chữ nhật",
    "selectFeaturesTip": "Chọn đối tượng bằng cách kéo ô xung quanh đối tượng trên bản đồ",
    "newSelectionTip": "Tạo lựa chọn mới",
    "addSelectionTip": "Thêm vào lựa chọn",
    "removeSelectionTip": "Gỡ bỏ khỏi lựa chọn",
    "selectFromCurrentSelectionTip": "Chọn từ lựa chọn hiện tại",
    "unselectAllSelectionTip": "Bỏ chọn tất cả đối tượng được chọn hiện tại",
    "selectByPolygon": "Chọn theo hình đa giác",
    "selectByCircle": "Chọn theo hình tròn",
    "selectByLine": "Chọn theo đường thẳng",
    "chooseSelectingTools": "Chọn các công cụ lựa chọn",
    "darw": "Vẽ",
    "drawShap": "Vẽ một hình"
  },
  "widgetManager": {
    "createWidgetError": "Lỗi tạo tiện ích",
    "createWidgetSettingPageError": "Lỗi tạo trang cài đặt tiện ích",
    "loadWidgetResourceError": "Lỗi tải nguồn tiện ích"
  },
  "shareOptions": {
    "shareMap": "Chọn người có thể xem ứng dụng này",
    "shareMapTips": "Ứng dụng của bạn hiện đang được chia sẻ với những người sau",
    "everyone": "Mọi người",
    "theseGroups": "Những nhóm sau"
  },
  "shareLink": {
    "email": "email",
    "shareEmail": "Email",
    "facebook": "facebook",
    "shareFacebook": "Facebook",
    "twitter": "twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "Nhúng ứng dụng này vào trang web",
    "shareEmailSubject": "Chia sẻ ứng dụng web:",
    "shareEmailTxt1": "Đây là ứng dụng web được chia sẻ với bạn bằng cách sử dụng Web AppBuilder for ArcGIS.",
    "shareEmailTxt2": "Bạn có thể tạo và chia sẻ ứng dụng web của riêng mình bằng Esri Web AppBuilder for ArcGIS.",
    "shareEmailTxt3": "Hãy truy cập http://www.esri.com/software/web-appbuilder để biết thêm chi tiết.",
    "smallSize": "Nhỏ",
    "mediumSize": "Trung bình",
    "largeSize": "Lớn",
    "customSize": "Tùy chỉnh",
    "embed": "Nhúng ứng dụng này vào trang web",
    "more": "Tùy chọn nhúng",
    "changeShareSettings": "Thay đổi thiết lập chia sẻ",
    "shareLinkText": "Chia sẻ liên kết đến ứng dụng này",
    "linkOptions": "Tùy chọn liên kết",
    "linkOptionsUrlParameters": "Chọn tham số URL bao gồm trong liên kết",
    "currentMapExtent": "Phạm vi bản đồ hiện tại",
    "chooseCenterWithLevel": "Nhấp vào bản đồ để xác định tâm bản đồ bằng độ thu phóng",
    "chooseCenterWithScale": "Nhấp vào bản đồ để xác định tâm bản đồ bằng tỷ lệ bản đồ",
    "findLocation": "Tìm vị trí hoặc đối tượng và phóng tới vị trí hoặc đối tượng đó",
    "findLocation_inputPlaceholder": "Vị trí hoặc đối tượng của bạn",
    "queryFeature": "Truy vấn đối tượng và phóng tới đối tượng đó",
    "addMarker": "Thêm điểm đánh dấu trên bản đồ",
    "addMarker_titlePlaceholder": "Tiêu đề của cửa sổ pop-up điểm đánh dấu",
    "addMarker_symbolURL": "URL ký hiệu điểm đánh dấu",
    "addMarker_label": "Nhãn điểm đánh dấu",
    "popupTitle": "Tiêu đề pop-up:",
    "zoomLevel": "Độ thu phóng",
    "overwirteMobileLayout": "Ghi đè kích thước màn hình mặc định của bố cục dành cho thiết bị di động",
    "language": "Đặt ngôn ngữ hiển thị của ứng dụng",
    "auth": "Tự động xác thực người dùng",
    "linkPreview": "Liên kết xem trước",
    "useShortenLink": "Liên kết ngắn",
    "shareMapUrlExtent": "Chia sẻ phạm vi bản đồ hiện tại",
    "shareToWebTips": "Ứng dụng này không được chia sẻ công khai. Mọi người sẽ không thể xem ứng dụng."
  },
  "webSceneLoader": {
    "webglSupportTip": "Trình duyệt của bạn không hỗ trợ ứng dụng web 3D."
  },
  "map": {
    "basemapNotAvailable": "Bản đồ nền không khả dụng.",
    "displayDefaultBasemap": "Thay vào đó hiển thị bản đồ nền mặc định.",
    "layerLoadedError": "Lớp, ${layers} không thể thêm vào bản đồ."
  },
  "popup": {
    "relatedTables": "Bảng liên quan:",
    "relatedRecords": "Bản ghi liên quan:",
    "noRelatedRecotds": "Không tìm thấy bản ghi liên quan.",
    "chooseFieldTip": "Chọn thuộc tính để hiển thị danh sách",
    "saveAsPopupTitle": "Giống như tiêu đề pop-up"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "Có quá nhiều tính năng trong phần lựa chọn của bạn. Có thể sẽ mất nhiều thời gian để truy xuất và hiển thị chúng lên bản đồ.",
    "askForContinue": "Bạn có muốn tiếp tục không?"
  },
  "colorPalette": {
    "transparent": "Độ trong suốt",
    "custom": "Tùy chỉnh"
  },
  "temperature": {
    "celsius": "Độ Celsius",
    "fahrenheit": "Độ Fahrenheit"
  },
  "report": {
    "printButtonLabel": "In",
    "reportDimensionsMsg": "Báo cáo này được thiết kế để in trên Giấy ${paperSize}",
    "unableToPrintMapMsg": "Đã xảy ra lỗi trong khi in (các) bản đồ.",
    "notesHint": "Nhập ý kiến ở đây",
    "landscape": "Cảnh quan",
    "portrait": "Hướng dọc",
    "mapOnly": "MAP_ONLY",
    "a0": "A0",
    "a1": "A1",
    "a2": "A2",
    "a3": "A3",
    "a4": "A4",
    "a5": "A5",
    "letterANSIA": "Thư ANSI A",
    "tabloidANSIB": "Báo khổ nhỏ ANSI B",
    "letter": "Thư",
    "legal": "Pháp lý",
    "tabloid": "Báo khổ nhỏ",
    "ansi_a": "ANSI A",
    "ansi_b": "ANSI B",
    "ansi_c": "ANSI C",
    "ansi_d": "ANSI D",
    "ansi_e": "ANSI E"
  },
  "snapshot": {
    "snapshot_complete": "Đả tạo ảnh chụp nhanh thành công.",
    "snapshot_failed": "Không thể tạo ảnh chụp nhanh.",
    "snapshot_append": "Ảnh chụp nhanh",
    "utc": "UTC"
  },
  "statisticsChart": {
    "enlarge": "Phóng to",
    "setting": "Thiết lập",
    "count": "Số lượng",
    "horizontalAxis": "Trục ngang",
    "verticalAxis": "Trục dọc",
    "dataLabels": "Nhãn dữ liệu",
    "color": "Màu sắc"
  },
  "frameworkDatasource": {
    "setDataSource": "Thiết lập nguồn Dữ liệu",
    "customDataSource": "Nguồn dữ liệu thêm",
    "selectCustomDataTip": "Chọn nguồn dữ liệu từ ứng dụng này.",
    "widgetOutputs": "Đầu ra tiện ích",
    "noExtraDsAvailable": "Không có nguồn dữ liệu thêm.",
    "addExtraDsTip": "Vào tab Thuộc tính của bộ dựng, và nhấp vào Nguồn dữ liệu thêm để thêm dữ liệu.",
    "widgetOutpusListTip": "Các đầu ra tiện ích (nếu có) cũng được liệt kê ở đây."
  },
  "gridLayout": {
    "addWidgetTip": "Thêm tiện ích ở đây thông qua tab tiện ích",
    "modifyLayout": "Chỉnh sửa bố cục",
    "dragToAdd": "Kéo để thêm",
    "mapArea": "VÙNG BẢN ĐỒ"
  },
  "noEditPrivileges": "Tài khoản của bạn không có quyền tạo hoặc sửa đổi dữ liệu.",
  "invalidConfiguration": "Tiện ích chưa được cấu hình hoặc lớp trong cấu hình không còn trong bản đồ. Vui lòng mở ứng dụng trong chế độ bộ thiết lập và cấu hình lại tiện ích."
});