define({
  "_widgetLabel": "Lista slojeva",
  "titleBasemap": "Pozadinske mape",
  "titleLayers": "Operativni slojevi",
  "labelLayer": "Ime sloja",
  "itemZoomTo": "Uveličaj na",
  "itemTransparency": "Prozirnost",
  "itemTransparent": "Prozirno",
  "itemOpaque": "Neprozirno",
  "itemMoveUp": "Pomeri se na gore",
  "itemMoveDown": "Pomeri se na dole",
  "itemDesc": "Opis",
  "itemDownload": "Preuzmi",
  "itemToAttributeTable": "Prikaži u tabeli atributa",
  "itemShowItemDetails": "Prikaži detalje stavke",
  "empty": "prazno",
  "removePopup": "Onemogući iskačuće prozore",
  "enablePopup": "Omogući iskačuće prozore",
  "turnAllLayersOff": "Isključi sve slojeve",
  "turnAllLayersOn": "Uključi sve slojeve",
  "expandAllLayers": "Razvij sve slojeve",
  "collapseAlllayers": "Skupi sve slojeve",
  "turnAllLabelsOff": "Isključi sve oznake",
  "turnAllLabelsOn": "Uključi sve oznake",
  "showLabels": "Prikaži oznake",
  "hideLables": "Sakrij oznake"
});