define(
   ({
    "sourceSetting": "Søgekildeindstillinger",
    "instruction": "Tilføj og konfigurér geokodningstjenester eller vektorlag som søgekilder. Disse specificerede kilder bestemmer, hvad der kan søges efter i søgeboksen.",
    "add": "Tilføj søgekilde",
    "addGeocoder": "Tilføj geokodningsfunktion",
    "geocoder": "Geokoder",
    "setLayerSource": "Angiv lagkilde",
    "setGeocoderURL": "Angiv geokodnings-URL",
    "searchableLayer": "Vektorlag",
    "name": "Navn",
    "countryCode": "Lande- eller regionskode(r)",
    "countryCodeEg": "f.eks. ",
    "countryCodeHint": "Hvis denne værdi er tom, bliver der søgt efter alle lande og regioner",
    "generalSetting": "Generelle indstillinger",
    "allPlaceholder": "Pladsholdertekst for søgning efter alle: ",
    "showInfoWindowOnSelect": "Vis pop-up for det fundne objekt eller den fundne position",
    "searchInCurrentMapExtent": "Søg kun inden for den aktuelle kortudstrækning",
    "locatorUrl": "Geokodnings-URL",
    "locatorName": "Navn på geokodningsfunktion",
    "locatorExample": "Eksempel",
    "locatorWarning": "Denne version af geokodningstjenesten understøttes ikke. Widget\'en understøtter Geokodningstjeneste version 00.0 og nyere.",
    "locatorTips": "Forslag er ikke tilgængelige, fordi geokodningstjenesten ikke understøtter forslagsfunktionen.",
    "layerSource": "Lagkilde",
    "searchLayerTips": "Forslag er ikke tilgængelige, fordi featuretjenesten ikke understøtter forslagsfunktionen.",
    "placeholder": "Pladsholdertekst",
    "searchFields": "Søgefelter",
    "displayField": "Visningsfelt:",
    "exactMatch": "Nøjagtigt match",
    "maxResults": "Maksimalt antal resultater",
    "setSearchFields": "Indstil søgefelter",
    "set": "Indstil",
    "fieldSearchable": "søgbar",
    "fieldName": "Navn",
    "fieldAlias": "Alias",
    "ok": "OK",
    "cancel": "Annuller",
    "invalidUrlTip": "Den URL, du har angivet, er ugyldig eller utilgængelig."
  })
);