define({
  "sourceSetting": "Søgekildeindstillinger",
  "instruction": "Tilføj og konfigurér geokodningstjenester eller vektorlag som søgekilder. Disse specificerede kilder bestemmer, hvad der kan søges efter i søgeboksen.",
  "add": "Tilføj søgekilde",
  "addGeocoder": "Tilføj geokodningsfunktion",
  "geocoder": "Geokoder",
  "setLayerSource": "Angiv lagkilde",
  "setGeocoderURL": "Angiv geokodnings-URL",
  "searchableLayer": "Vektorlag",
  "name": "Navn",
  "countryCode": "Lande- eller regionskode(r)",
  "countryCodeEg": "f.eks. ",
  "countryCodeHint": "Hvis denne værdi er tom, bliver der søgt efter alle lande og regioner",
  "generalSetting": "Generelle indstillinger",
  "allPlaceholder": "Pladsholdertekst for søgning efter alle: ",
  "showInfoWindowOnSelect": "Vis pop-up for det fundne objekt eller den fundne position",
  "searchInCurrentMapExtent": "Søg kun inden for den aktuelle kortudstrækning",
  "zoomScale": "Zoom-skala",
  "locatorUrl": "Geokodnings-URL",
  "locatorName": "Navn på geokodningsfunktion",
  "locatorExample": "Eksempel",
  "locatorWarning": "Denne version af geokodningstjenesten understøttes ikke. Widget'en understøtter Geokodningstjeneste version 10.1 og nyere.",
  "locatorTips": "Forslag er ikke tilgængelige, fordi geokodningstjenesten ikke understøtter forslagsfunktionen.",
  "layerSource": "Lagkilde",
  "searchLayerTips": "Forslag er ikke tilgængelige, fordi featuretjenesten ikke understøtter forslagsfunktionen.",
  "placeholder": "Pladsholdertekst",
  "searchFields": "Søgefelter",
  "displayField": "Visningsfelt",
  "exactMatch": "Nøjagtigt match",
  "maxSuggestions": "Maksimalt antal forslag",
  "maxResults": "Maksimalt antal resultater",
  "enableLocalSearch": "Aktivér lokal søgning",
  "minScale": "Min. målestok",
  "minScaleHint": "Når kortmålestokken er større end denne målstok, anvendes lokal søgning",
  "radius": "Radius",
  "radiusHint": "Angiver radius for et område omkring det aktuelle kortcentrum, der benyttes til at booste rangordningen af geokodningsforslag, så de forslag, der ligger tættest på placeringen, returneres først",
  "meters": "Meter",
  "setSearchFields": "Indstil søgefelter",
  "set": "Angiv",
  "fieldSearchable": "søgbar",
  "fieldName": "Navn",
  "fieldAlias": "Alias",
  "ok": "OK",
  "cancel": "Annullér",
  "invalidUrlTip": "URL’en ${URL} er ugyldig eller utilgængelig."
});