define({
  "id": "ID",
  "state": "Som standard visas koordinaterna i den aktuella kartans koordinatsystem. Om du vill hämta koordinater i andra koordinatsystem måste du lägga till dem och ange lämpliga omvandlingar.",
  "outputUnit": "Utdataenhet",
  "wkid": "Utdata-WKID",
  "label": "Namn på koordinatsystem för utdata",
  "transformationWkid": "Omvandlings-WKID",
  "transformationLabel": "Omvandlingsetikett",
  "transformForward": "Framåtomvandling",
  "actions": "Åtgärder",
  "warning": "Ange giltig WKID för geografisk referens!",
  "tfWarning": "Ange giltig WKID för datumomvandling!",
  "spinnerLabel": "Avrunda koordinater till: ",
  "decimalPlace": "decimaler",
  "separator": "Visa tusentalsavgränsare",
  "getVersionError": "Det går inte att hämta versionsnumret för geometritjänsten",
  "add": "Lägg till koordinatsystem för utdata",
  "edit": "Redigera koordinatsystem",
  "output": "Utdatakoordinatsystem",
  "cName": "Koordinatsystemets namn",
  "units": "Visningsenheter: ",
  "datum": "Datumomvandling",
  "tName": "Omvandlingsnamn",
  "tWKIDPlaceHolder": "WKID för omvandlingen",
  "forward": "Använd framåtomvandling",
  "ok": "OK",
  "cancel": "Avbryt",
  "olderVersion": "Geometritjänsten har inte stöd för omvandlingsåtgärden",
  "REPEATING_ERROR": " Koordinatsystemet finns med i utdatalistan.",
  "Default": "Standard",
  "Inches": "Tum",
  "Foot": "Fot",
  "Yards": "Yard",
  "Miles": "Engelska mil",
  "Nautical_Miles": "Nautiska mil",
  "Millimeters": "Millimeter",
  "Centimeters": "Centimeter",
  "Meter": "Meter",
  "Kilometers": "Kilometer",
  "Decimeters": "Decimeter",
  "Decimal_Degrees": "Decimalgrader",
  "Degrees_Decimal_Minutes": "Grader decimalminuter",
  "Degree_Minutes_Seconds": "Grader minuter sekunder",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Koordinatvisningsordning:",
  "lonLatTips": "Longitud/latitud (X, Y)",
  "latLonTips": "Latitud/longitud (Y, X)"
});