define({
  "_widgetLabel": "Attributtabell",
  "_featureAction_ShowRelatedRecords": "Vis relaterte poster",
  "_featureAction_ViewInTable": "Vis i attributtabell",
  "ok": "OK",
  "cancel": "Avbryt",
  "unsupportQueryWarning": "Laget må støtte spørringsoperasjoner for å kunne vises i attributtabell-widget. Sørg for at spørringsfunksjonen i tjenesten er slått på.",
  "exportMessage": "Eksportere data til CSV-fil?",
  "exportFiles": "Eksporter til CSV",
  "exportSelected": "Eksporter utvalg til CSV",
  "exportAll": "Eksporter alt til CSV",
  "options": "Alternativer",
  "zoomto": "Zoom til",
  "highlight": "Uthev grafikk",
  "selectAll": "Velg poster på alle sider",
  "selectPage": "Velg poster på gjeldende side",
  "clearSelection": "Tøm utvalg",
  "filter": "Filter",
  "setFilterTip": "Angi filtre på riktig måte.",
  "noFilterTip": "Uten definerte filteruttrykk viser denne spørringoppgaven alle geoobjekter i den angitte datakilden.",
  "filterByExtent": "Filtrer etter kartutstrekning",
  "showSelectedRecords": "Vis valgte poster",
  "showAllRecords": "Vis alle poster",
  "showRelatedRecords": "Vis relaterte poster",
  "noRelatedRecords": "Ingen tilknyttede oppføringer funnet",
  "attachmentColumn": "Bilder og filer",
  "refresh": "Oppdater",
  "features": "geoobjekter",
  "records": "poster",
  "selected": "valgte",
  "transparent": "Gjennomsiktig modus",
  "indicate": "Finn utvalg",
  "columns": "Vis/skjul kolonner",
  "selectionSymbol": "Utvalgsymbol",
  "closeMessage": "Skjul tabell (utvid den igjen fra bunnen)",
  "dataNotAvailable": "Data ikke tilgjengelig!<br>Klikk på [Oppdater] for å prøve på nytt.",
  "openTableTip": "Åpne attributtabell",
  "closeTableTip": "Skjul attributt-tabell",
  "sortAsc": "Sorter stigende",
  "sortDes": "Sorter synkende",
  "statistics": "Statistikk",
  "attachments": "Vedlegg",
  "files": "filer"
});