define({
  "_widgetLabel": "Koordinat",
  "hintMessage": "Klik peta untuk mendapatkan koordinat",
  "defaultLabel": "Default",
  "realtimeLabel": "Gerakkan mouse untuk mendapatkan koordinat",
  "computing": "Menghitung...",
  "latitudeLabel": "Garis Lintang",
  "longitudeLabel": "Garis Bujur",
  "loading": "memuat...",
  "enableClick": "Klik untuk mengaktifkan pengeklikan peta untuk mendapatkan koordinat",
  "disableClick": "Klik untuk menonaktifkan pengeklikan peta untuk mendapatkan koordinat",
  "Default": "Default",
  "Inches": "Inci",
  "Foot": "Kaki",
  "Yards": "Yard",
  "Miles": "Mil",
  "Nautical_Miles": "Mil laut",
  "Millimeters": "Milimeter",
  "Centimeters": "Sentimeter",
  "Meter": "Meter",
  "Kilometers": "Kilometer",
  "Decimeters": "Desimeter",
  "Decimal_Degrees": "Derajat",
  "Degree_Minutes_Seconds": "Derajat menit detik",
  "MGRS": "MGRS",
  "USNG": "USNG"
});