define({
  "_widgetLabel": "Tabel de atribute",
  "_featureAction_ShowRelatedRecords": "Afişare înregistrări corelate",
  "_featureAction_ViewInTable": "Vizualizare în tabelul de atribute",
  "ok": "OK",
  "cancel": "Anulare",
  "unsupportQueryWarning": "Stratul tematic trebuie să suporte operarea de interogări pentru a fi afişat în widgetul Tabel atribute. Asiguraţi-vă că capacitatea de interogare din serviciu este activată.",
  "exportMessage": "Exportaţi datele în fişier CSV?",
  "exportFiles": "Export în CSV",
  "exportSelected": "Export selecţie către CSV",
  "exportAll": "Export toate către CSV",
  "options": "Opţiuni",
  "zoomto": "Transfocare la",
  "highlight": "Evidenţiere elemente grafice",
  "selectAll": "Selectare înregistrări din toate paginile",
  "selectPage": "Selectare înregistrări din pagina curentă",
  "clearSelection": "Golire selecţie",
  "filter": "Filtru",
  "setFilterTip": "Setaţi corect filtrele.",
  "noFilterTip": "Fără a avea expresiile de filtrare definite, această operaţie de interogare va lista toate obiectele spaţiale din sursa de date specificată.",
  "filterByExtent": "Filtrare după extinderea hărţii",
  "showSelectedRecords": "Afişare înregistrări selectate",
  "showAllRecords": "Afişare toate înregistrările",
  "showRelatedRecords": "Afişare înregistrări corelate",
  "noRelatedRecords": "Nu au fost găsite înregistrări corelate",
  "attachmentColumn": "Fotografii şi fişiere",
  "refresh": "Reîmprospătare",
  "features": "obiecte spaţiale",
  "records": "înregistrări",
  "selected": "selectat",
  "transparent": "Mod Transparent",
  "indicate": "Selectare locaţie",
  "columns": "Afişare/Ascundere coloane",
  "selectionSymbol": "Simbol pentru selectare",
  "closeMessage": "Ascundere tabel (se extinde din nou de jos)",
  "dataNotAvailable": "Nu există date disponibile!<br>Faceţi clic pe butonul [Reîmprospătare] pentru a încerca din nou.",
  "openTableTip": "Deschidere tabel de atribute",
  "closeTableTip": "Ascundere tabel de atribute",
  "sortAsc": "Sortare ascendentă",
  "sortDes": "Sortare descendentă",
  "statistics": "Statistică",
  "attachments": "Ataşări",
  "files": "fişiere"
});