define(
   ({
    "sourceSetting": "Configuración de fuente de búsqueda",
    "instruction": "Agrega y configura servicios de geocodificación o capas de entidades como orígenes de búsqueda. Estos orígenes especificados determinan qué se puede buscar dentro del cuadro de búsqueda.",
    "add": "Agregar origen de búsqueda",
    "addGeocoder": "Agregar geocodificador",
    "geocoder": "Geocodificador",
    "setLayerSource": "Establecer origen de capa",
    "setGeocoderURL": "Establecer dirección URL de geocodificador",
    "searchableLayer": "Capa de la Entidad",
    "name": "Nombre",
    "countryCode": "Código(s) de país o región",
    "countryCodeEg": "p. ej., ",
    "countryCodeHint": "Si se deja este valor en blanco, se buscará en todos los países y regiones",
    "generalSetting": "Configuración general",
    "allPlaceholder": "Texto del marcador de posición para buscar en todo: ",
    "showInfoWindowOnSelect": "Mostrar ventana emergente de la entidad o la ubicación encontrada",
    "searchInCurrentMapExtent": "Buscar solo en la extensión de mapa actual",
    "zoomScale": "Aplicar zoom a escala",
    "locatorUrl": "Dirección URL del geocodificador",
    "locatorName": "Nombre del geocodificador",
    "locatorExample": "Ejemplo",
    "locatorWarning": "No se admite esta versión del servicio de geocodificación. El widget admite servicios de geocodificación 10.0 y superiores.",
    "locatorTips": "No hay sugerencias disponibles porque el servicio de geocodificación no admite la opción de sugerencias.",
    "layerSource": "Origen de capa",
    "searchLayerTips": "No hay sugerencias disponibles porque el servicio de entidades no admite la opción de paginación.",
    "placeholder": "Texto del marcador de posición",
    "searchFields": "Campos de búsqueda",
    "displayField": "Campo de visualización",
    "exactMatch": "Coincidencia exacta",
    "maxSuggestions": "Máximo de sugerencias",
    "maxResults": "Resultados máximos",
    "setSearchFields": "Establecer campos de búsqueda",
    "set": "Definir",
    "fieldSearchable": "permite búsqueda",
    "fieldName": "Nombre",
    "fieldAlias": "Alias",
    "ok": "Aceptar",
    "cancel": "Cancelar",
    "invalidUrlTip": "No se puede acceder a la dirección URL ${URL} o bien no es válida."
  })
);