define({
  "sourceSetting": "Configuración de origen de búsqueda",
  "instruction": "Agrega y configura servicios de geocodificación o capas de entidades como fuentes de búsqueda. Estas fuentes especificadas determinan qué se puede buscar en el cuadro de búsqueda.",
  "add": "Agregar origen de búsqueda",
  "addGeocoder": "Agregar geocodificador",
  "geocoder": "Geocodificador",
  "setLayerSource": "Definir origen de capa",
  "setGeocoderURL": "Definir dirección URL de geocodificador",
  "searchableLayer": "Capa de entidades",
  "name": "Nombre",
  "countryCode": "Código(s) de país o región",
  "countryCodeEg": "p. ej., ",
  "countryCodeHint": "Si se deja este valor en blanco, se buscará en todos los países y regiones",
  "generalSetting": "Configuración general",
  "allPlaceholder": "Texto del marcador de posición para buscar en todo: ",
  "showInfoWindowOnSelect": "Mostrar ventana emergente de la entidad o la ubicación encontrada",
  "searchInCurrentMapExtent": "Buscar solo en la extensión de mapa actual",
  "zoomScale": "Escala de zoom",
  "locatorUrl": "Dirección URL del geocodificador",
  "locatorName": "Nombre del geocodificador",
  "locatorExample": "Ejemplo",
  "locatorWarning": "No se admite esta versión del servicio de geocodificación. El widget admite servicios de geocodificación 10.1 y superiores.",
  "locatorTips": "No hay sugerencias disponibles porque el servicio de geocodificación no admite la opción de sugerencias.",
  "layerSource": "Origen de capa",
  "searchLayerTips": "No hay sugerencias disponibles porque el servicio de entidades no admite la opción de paginación.",
  "placeholder": "Texto del marcador de posición",
  "searchFields": "Campos de búsqueda",
  "displayField": "Mostrar campo",
  "exactMatch": "Coincidencia exacta",
  "maxSuggestions": "Máximo de sugerencias",
  "maxResults": "Resultados máximos",
  "enableLocalSearch": "Habilitar búsqueda local",
  "minScale": "Escala mínima",
  "minScaleHint": "Si la escala del mapa es mayor que esta escala, se aplicará la búsqueda local",
  "radius": "Radio",
  "radiusHint": "Permite especificar el radio de un área alrededor del centro del mapa actual que se utilizará para mejorar la clasificación de los candidatos de geocodificación a fin de que se devuelvan primero aquellos más cercanos a la ubicación",
  "meters": "Metros",
  "setSearchFields": "Definir campos de búsqueda",
  "set": "Definir",
  "fieldSearchable": "permite búsqueda",
  "fieldName": "Nombre",
  "fieldAlias": "Alias",
  "ok": "Aceptar",
  "cancel": "Cancelar",
  "invalidUrlTip": "No se puede acceder a la dirección URL ${URL} o bien no es válida."
});