define({
  "_widgetLabel": "Koordinate",
  "hintMessage": "Kliknite na kartu za dobivanje koordinata",
  "defaultLabel": "Zadano",
  "realtimeLabel": "Pomaknite miš za dobivanje koordinata",
  "computing": "Izračunavanje...",
  "latitudeLabel": "Geografska širina",
  "longitudeLabel": "Geografska dužina",
  "loading": "učitavanje...",
  "enableClick": "Kliknite da omogućite dobivanje koordinata klikom na kartu",
  "disableClick": "Kliknite da onemogućite dobivanje koordinata klikom na kartu",
  "Default": "Zadano",
  "Inches": "Inči",
  "Foot": "Stope",
  "Yards": "Jardi",
  "Miles": "Milje",
  "Nautical_Miles": "Nautičke milje",
  "Millimeters": "Millimetri",
  "Centimeters": "Centimetri",
  "Meter": "Metri",
  "Kilometers": "Kilometri",
  "Decimeters": "Decimetri",
  "Decimal_Degrees": "Stupnjevi",
  "Degree_Minutes_Seconds": "Stupnjevi minute sekunde",
  "MGRS": "MGRS",
  "USNG": "USNG"
});