define({
  root: ({
    _widgetLabel: "Layer List",
    titleBasemap: "Basemaps",
    titleLayers: "Operational layers",
    labelLayer: "Layer name",
    itemZoomTo: "Zoom to",
    itemTransparency: "Transparency",
    itemTransparent: "Transparent",
    itemOpaque: "Opaque",
    itemMoveUp: "Move up",
    itemMoveDown: "Move down",
    itemDesc: "Description",
    itemDownload: "Download",
    itemToAttributeTable: "View in Attribute Table",
    itemShowItemDetails: "Show item details",
    empty: "empty",
    removePopup: "Disable pop-up",
    enablePopup: "Enable pop-up",
    turnAllLayersOff: "Turn all layers off",
    turnAllLayersOn: "Turn all layers on",
    expandAllLayers: "Expand all layers",
    collapseAlllayers: "Collapse all layers",
    turnAllLabelsOff: "Turn all labels off",
    turnAllLabelsOn: "Turn all labels on",
    showLabels: "Show labels",
    hideLables: "Hide labels"
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
