define({
  "instruction": "Заставка появляется до того, как приложение становится доступным.",
  "defaultContent": "Добавьте сюда текст, ссылки и небольшие изображения.",
  "requireConfirm": "Для продолжения требуется подтверждение",
  "noRequireConfirm": "Для продолжения подтверждение не требуется",
  "optionText": "Опция для пользователя для отключения показа заставки при запуске приложения.",
  "confirmLabel": "Текст подтверждения: ",
  "confirmLabelColor": "Цвет текста подтверждения",
  "defaultConfirmText": "Я принимаю вышеуказанные условия использования",
  "confirmOption": "Всегда отображать заставку при каждом запуске выражения",
  "backgroundColor": "Цвет фона",
  "content": "Содержание",
  "contentDescription": "Задайте содержание, которое будет отображаться на заставке.",
  "appearance": "Оформление",
  "appearanceDescription": "Настройте внешний вид окна заставки.",
  "size": "Размер",
  "width": "Ширина",
  "height": "Высота",
  "custom": "Пользовательская",
  "background": "Фон",
  "colorFill": "Заливка цветом",
  "imageFill": "Заполнение изображением",
  "chooseFile": "Выберите файл",
  "noFileChosen": "Файл не выбран",
  "transparency": "Прозрачность",
  "sizeFill": "Заполнить",
  "sizeFit": "Вписать",
  "sizeStretch": "Растянуть для заполнения",
  "sizeCenter": "По центру",
  "sizeTile": "Лист",
  "buttonColor": "Цвет кнопки",
  "buttonText": "Текст кнопки",
  "buttonTextColor": "Цвет текста кнопки",
  "contentAlign": "Выравнивание содержания",
  "alignTop": "Сверху",
  "alignMiddle": "По центру",
  "maskColor": "Цвет маски",
  "options": "Опции",
  "optionsDescription": "Настройте поведение окна заставки."
});