define({
  "_widgetLabel": "Tabella attributi",
  "_featureAction_ShowRelatedRecords": "Mostra record correlati",
  "_featureAction_ViewInTable": "Visualizza nella tabella degli attributi",
  "ok": "OK",
  "cancel": "Annulla",
  "unsupportQueryWarning": "Il layer deve supportare la funzionalità delle query per essere visualizzato nel widget Tabella attributi. Accertarsi che la funzionalità delle query in questo servizio sia abilitata.",
  "exportMessage": "Esportare i dati nel file CSV?",
  "exportFiles": "Esporta in CSV",
  "exportSelected": "Esporta selezionato in CSV",
  "exportAll": "Esporta tutto in CSV",
  "options": "Opzioni",
  "zoomto": "Zoom a",
  "highlight": "Evidenzia elementi grafici",
  "selectAll": "Seleziona record in tutte le pagine",
  "selectPage": "Seleziona record nella pagina corrente",
  "clearSelection": "Cancella selezione",
  "filter": "Filtro",
  "setFilterTip": "Impostare i filtri correttamente.",
  "noFilterTip": "Se non si definisce nessuna espressione di filtro, questa attività di interrogazione restituirà tutte le feature presenti nell'origine dati specificata.",
  "filterByExtent": "Filtro per estensione mappa",
  "showSelectedRecords": "Mostra i record selezionati",
  "showAllRecords": "Mostra tutti i record",
  "showRelatedRecords": "Mostra record correlati",
  "noRelatedRecords": "Nessun record correlato trovato",
  "attachmentColumn": "Foto e file",
  "refresh": "Aggiorna",
  "features": "feature",
  "records": "dei record",
  "selected": "selezionate",
  "transparent": "Modalità trasparente",
  "indicate": "Individua selezione",
  "columns": "Mostra/nascondi colonne",
  "selectionSymbol": "Simbolo di selezione",
  "closeMessage": "Nascondi tabella (espanderla di nuovo dalla parte inferiore)",
  "dataNotAvailable": "Dati non disponibili.<br>Fare clic su [Aggiorna] per riprovare.",
  "openTableTip": "Apri tabella attributi",
  "closeTableTip": "Nascondi tabella attributi",
  "sortAsc": "Ordinamento crescente",
  "sortDes": "Ordinamento decrescente",
  "statistics": "Statistiche",
  "attachments": "Allegati",
  "files": "file"
});