define({
  "common": {
    "apply": "적용",
    "ok": "확인",
    "cancel": "취소",
    "yes": "예",
    "no": "아니요",
    "next": "다음",
    "previous": "이전",
    "back": "뒤로",
    "selected": "선택함",
    "name": "이름",
    "usage": "사용",
    "settings": "설정",
    "home": "홈",
    "link": "링크",
    "messages": "메시지",
    "outputs": "결과",
    "title": "제목",
    "thumbnail": "섬네일",
    "url": "URL",
    "actions": "작업",
    "layer": "레이어",
    "action": "작업",
    "input": "입력",
    "output": "출력",
    "type": "유형",
    "required": "필수",
    "options": "옵션",
    "label": "레이블",
    "tooltip": "도구 팁",
    "visible": "가시",
    "symbol": "심볼",
    "popup": "팝업",
    "upload": "업로드",
    "execute": "실행",
    "help": "도움말",
    "executing": "실행",
    "clear": "지우기",
    "error": "오류",
    "zoomTo": "확대/축소",
    "attribute": "속성",
    "exports": "내보내기",
    "check": "확인",
    "save": "저장",
    "close": "닫기",
    "deleteText": "삭제",
    "map": "맵",
    "scene": "씬",
    "reset": "재설정",
    "icon": "아이콘",
    "folder": "폴더",
    "share": "공유",
    "view": "보기",
    "newText": "새로 만들기",
    "edit": "편집",
    "wkid": "WKID",
    "table": "테이블",
    "zoomIn": "확대",
    "zoomOut": "축소",
    "continue1": "계속",
    "longitude": "경도",
    "latitude": "위도",
    "custom": "사용자 정의",
    "image": "이미지",
    "font": "글꼴",
    "text": "텍스트",
    "all": "모두",
    "number": "숫자",
    "percentage": "백분율",
    "unit": "단위",
    "thousand": "천",
    "billion": "10억",
    "million": "백만",
    "none": "없음",
    "field": "필드",
    "operation": "작업",
    "disableUpdateGeometry": "지오메트리 업데이트 사용 안 함",
    "preview": "미리보기"
  },
  "errorCode": "코드",
  "errorMessage": "메시지",
  "errorDetail": "세부정보",
  "widgetPlaceholderTooltip": "설정하려면, 위젯으로 이동한 다음 해당 개체 틀을 클릭",
  "fieldStatistics": {
    "selectField": "필드 선택",
    "statistics": "통계",
    "field": "필드",
    "count": "값 수",
    "sum": "값 합계",
    "min": "최소",
    "max": "최대",
    "ave": "평균",
    "stddev": "표준편차"
  },
  "symbolChooser": {
    "preview": "미리 보기",
    "basic": "기본",
    "arrows": "화살표",
    "business": "비즈니스",
    "cartographic": "지도",
    "nationalParkService": "국립공원관리청",
    "outdoorRecreation": "실외 레크리에이션",
    "peoplePlaces": "사용자 장소",
    "safetyHealth": "안전 보건",
    "shapes": "모양",
    "transportation": "교통",
    "symbolSize": "심볼 크기",
    "color": "색상",
    "alpha": "알파",
    "outlineColor": "윤곽선 색상",
    "outlineWidth": "윤곽선 너비",
    "style": "스타일",
    "width": "너비",
    "text": "텍스트",
    "fontColor": "글꼴 색상",
    "fontSize": "글꼴 크기",
    "transparency": "투명도",
    "solid": "실선",
    "dash": "대시",
    "dot": "점",
    "dashDot": "대시 점",
    "dashDotDot": "대시 점 점",
    "customImage": "사용자 정의 이미지",
    "chooseFile": "파일 선택",
    "noFileChoosen": "선택한 파일이 없습니다."
  },
  "transparency": {
    "opaque": "불투명",
    "transparent": "투명"
  },
  "rendererChooser": {
    "domain": "도메인",
    "use": "사용",
    "singleSymbol": "단일 심볼",
    "uniqueSymbol": "고유 심볼",
    "color": "색상",
    "size": "크기",
    "toShow": "다음 항목 나타내기",
    "colors": "색상",
    "classes": "클래스",
    "symbolSize": "심볼 크기",
    "addValue": "값 추가",
    "setDefaultSymbol": "기본 심볼 설정",
    "defaultSymbol": "기본 심볼",
    "selectedSymbol": "선택한 심볼",
    "value": "값",
    "label": "레이블",
    "range": "범위"
  },
  "drawBox": {
    "point": "포인트",
    "line": "라인",
    "polyline": "폴리라인",
    "freehandPolyline": "자유곡선 폴리라인",
    "triangle": "삼각형",
    "extent": "범위",
    "circle": "원",
    "ellipse": "타원",
    "polygon": "폴리곤",
    "freehandPolygon": "자유곡선 폴리곤",
    "text": "텍스트",
    "clear": "선택 해제"
  },
  "popupConfig": {
    "title": "제목",
    "add": "추가",
    "fields": "필드",
    "noField": "필드 없음",
    "visibility": "표시",
    "name": "이름",
    "alias": "별칭",
    "actions": "작업"
  },
  "includeButton": {
    "include": "포함"
  },
  "loadingShelter": {
    "loading": "불러오는 중"
  },
  "basicServiceBrowser": {
    "noServicesFound": "서비스를 찾을 수 없습니다.",
    "unableConnectTo": "다음과 연결할 수 없습니다.",
    "invalidUrlTip": "입력한 URL이 잘못되었거나 접근할 수 없습니다."
  },
  "serviceBrowser": {
    "noGpFound": "지오프로세싱 서비스를 찾을 수 없습니다.",
    "unableConnectTo": "다음과 연결할 수 없습니다."
  },
  "layerServiceBrowser": {
    "noServicesFound": "맵 서비스 또는 피처 서비스를 찾을 수 없습니다.",
    "unableConnectTo": "다음과 연결할 수 없습니다."
  },
  "basicServiceChooser": {
    "validate": "유효성 검사",
    "example": "예",
    "set": "설정"
  },
  "urlInput": {
    "invalidUrl": "잘못된 URL입니다."
  },
  "urlComboBox": {
    "invalidUrl": "잘못된 URL입니다."
  },
  "filterBuilder": {
    "addAnotherExpression": "식 추가",
    "addSet": "세트 추가",
    "matchMsg": "다음 식 ${any_or_all}와 일치하는 레이어의 피처를 가져옵니다.",
    "matchMsgSet": "이 세트의 다음 식 ${any_or_all}가 true입니다.",
    "all": "모두",
    "any": "일부",
    "value": "값",
    "field": "필드",
    "unique": "고유 값",
    "none": "없음",
    "and": "그리고",
    "valueTooltip": "값 입력",
    "fieldTooltip": "기존 필드에서 선택",
    "uniqueValueTooltip": "선택한 필드에서 고유한 값 선택",
    "stringOperatorIs": "다음과 같음",
    "stringOperatorIsNot": "다음과 같지 않음",
    "stringOperatorStartsWith": "다음으로 시작함",
    "stringOperatorEndsWith": "다음으로 끝남",
    "stringOperatorContains": "다음을 포함함",
    "stringOperatorDoesNotContain": "다음을 포함하지 않음",
    "stringOperatorIsBlank": "비어 있음",
    "stringOperatorIsNotBlank": "비어 있지 않음",
    "dateOperatorIsOn": "다음 날짜임",
    "dateOperatorIsNotOn": "다음 날짜가 아님",
    "dateOperatorIsBefore": "다음 이전 날짜임",
    "dateOperatorIsAfter": "다음 이후 날짜임",
    "dateOperatorIsOnOrBefore": "다음 시간 또는 그 이전",
    "dateOperatorIsOnOrAfter": "다음 시간 또는 그 이후",
    "dateOperatorMinutes": "분",
    "dateOperatorHours": "시간",
    "dateOperatorDays": "일",
    "dateOperatorWeeks": "주",
    "dateOperatorMonths": "개월",
    "dateOperatorYears": "수 년",
    "dateOperatorInTheLast": "다음 기간에 이내에 속함",
    "dateOperatorNotInTheLast": "다음 기간에 이내에 속하지 않음",
    "dateOperatorIsBetween": "다음 사이에 속함",
    "dateOperatorIsNotBetween": "다음 사이에 속하지 않음",
    "dateOperatorIsBlank": "비어 있음",
    "dateOperatorIsNotBlank": "비어 있지 않음",
    "numberOperatorIs": "다음과 같음",
    "numberOperatorIsNot": "다음과 같지 않음",
    "numberOperatorIsAtLeast": "다음 이상",
    "numberOperatorIsLessThan": "다음 미만",
    "numberOperatorIsAtMost": "다음 이하",
    "numberOperatorIsGreaterThan": "다음 초과",
    "numberOperatorIsBetween": "다음 사이에 속함",
    "numberOperatorIsNotBetween": "다음 사이에 속하지 않음",
    "numberOperatorIsBlank": "비어 있음",
    "numberOperatorIsNotBlank": "비어 있지 않음",
    "string": "문자열",
    "number": "숫자",
    "date": "날짜",
    "askForValues": "값 요청",
    "prompt": "프롬프트",
    "hint": "힌트",
    "error": {
      "invalidParams": "잘못된 매개변수입니다.",
      "invalidUrl": "잘못된 URL입니다.",
      "noFilterFields": "레이어에는 필터를 생성하는 데 사용할 수 있는 필드가 없습니다.",
      "invalidSQL": "잘못된 SQL 식입니다.",
      "cantParseSQL": "SQL 식의 구문을 분석할 수 없습니다."
    },
    "caseSensitive": "대소문자 구분",
    "notSupportCaseSensitiveTip": "호스팅된 서비스는 대소문자 구분 쿼리를 지원하지 않습니다.",
    "setFilterTip": "필터를 올바르게 설정하세요.",
    "listValues": "목록 값",
    "cascadeFilterTip": "이전 식으로 필터링된 값만 보여 줍니다.",
    "noneCascadeFilterTip": "이 필드의 모든 고유값",
    "previousCascadeFilterTip": "이전 식으로 필터링된 값",
    "allCascadeFilterTip": "다른 모든 식으로 필터링된 값"
  },
  "featureLayerSource": {
    "layer": "레이어",
    "browse": "찾아보기",
    "selectFromMap": "맵",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "서비스 URL",
    "inputLayerUrl": "입력 레이어 URL",
    "selectLayer": "현재 맵에서 피처 레이어를 선택합니다.",
    "chooseItem": "피처 레이어 항목을 선택합니다.",
    "setServiceUrl": "피처 서비스 또는 맵 서비스의 URL을 입력합니다.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "피처 레이어를 선택합니다."
  },
  "queryableLayerSource": {
    "layer": "레이어",
    "browse": "찾아보기",
    "selectFromMap": "맵",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "서비스 URL",
    "inputLayerUrl": "입력 레이어 URL",
    "selectLayer": "현재 맵에서 레이어를 선택합니다.",
    "chooseItem": "항목을 선택합니다.",
    "setServiceUrl": "서비스 URL을 입력합니다.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "레이어를 선택합니다."
  },
  "gpSource": {
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "서비스 URL",
    "selectFromOnline": "ArcGIS Online",
    "setServiceUrl": "지오프로세싱 서비스 URL을 입력합니다.",
    "chooseItem": "지오프로세싱 서비스 항목을 선택합니다.",
    "chooseTask": "지오프로세싱 작업을 선택합니다."
  },
  "itemSelector": {
    "map": "맵",
    "selectWebMap": "웹 맵 선택",
    "addMapFromOnlineOrPortal": "ArcGIS Online 공용 리소스 또는 ArcGIS Online이나 포털의 개인 콘텐츠에서 응용프로그램에 있는 웹 맵을 찾아 추가합니다.",
    "searchMapName": "맵 이름별 검색...",
    "searchNone": "검색한 항목을 찾을 수 없습니다. 다시 시도하세요.",
    "groups": "그룹",
    "noneGroups": "그룹 없음",
    "signInTip": "로그인 세션이 만료되었습니다. 포털에 다시 로그인하려면 브라우저를 새로 고치세요.",
    "signIn": "로그인",
    "publicMap": "공용",
    "myOrganization": "내 기관",
    "myGroup": "내 그룹",
    "myContent": "내 콘텐츠",
    "count": "개수",
    "fromPortal": "포털에서",
    "fromOnline": "ArcGIS.com에서",
    "noneThumbnail": "섬네일을 사용할 수 없음",
    "owner": "소유자",
    "signInTo": "로그인:",
    "lastModified": "최근 수정일",
    "moreDetails": "자세한 정보",
    "mostRecent": "최신순",
    "mostViewed": "인기순",
    "highestRated": "최고 평점순",
    "viewItemDetails": "항목 세부정보 보기"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "서비스가 쿼리를 지원하지 않습니다."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "맵에서 사용할 수 있는 적합한 레이어가 없습니다."
  },
  "layerInfosMenu": {
    "titleBasemap": "베이스맵",
    "titleLayers": "운영 레이어",
    "labelLayer": "레이어 이름",
    "itemZoomTo": "확대",
    "itemTransparency": "투명도",
    "itemTransparent": "투명",
    "itemOpaque": "불투명",
    "itemMoveUp": "위로 이동",
    "itemMoveDown": "아래로 이동",
    "itemDesc": "설명",
    "itemDownload": "다운로드",
    "itemToAttributeTable": "속성 테이블에서 보기"
  },
  "imageChooser": {
    "unsupportReaderAPI": "해야 할 일: 브라우저가 파일 리더 API를 지원하지 않습니다.",
    "readError": "파일을 읽지 못했습니다.",
    "unknowError": "작업을 완료할 수 없음",
    "invalidType": "잘못된 파일 유형입니다.",
    "cropImage": "이미지 자르기",
    "exceed": "파일 크기는 1024KB를 넘을 수 없습니다.",
    "enableFlash": "이미지를 찾아보려면 먼저 Adobe Flash를 활성화하세요.",
    "cropWaining": "${가로} x ${세로} 픽셀 이상의 사진을 선택하세요.",
    "toolTip": "최상의 결과를 얻으려면 이미지의 폭은 ${width}픽셀, 높이는 ${height}픽셀이어야 합니다. 그 밖의 다른 크기는 맞게 조정됩니다. PNG, GIF 및 JPEG 형식의 이미지를 사용할 수 있습니다."
  },
  "simpleTable": {
    "moveUp": "위로 이동",
    "moveDown": "아래로 이동",
    "deleteRow": "삭제",
    "edit": "편집"
  },
  "urlParams": {
    "invalidToken": "잘못된 토큰",
    "validateTokenError": "잘못된 토큰 또는 네트워크 오류"
  },
  "exportTo": {
    "exportTo": "내보내기",
    "toCSV": "CSV 파일로 내보내기",
    "toFeatureCollection": "피처 컬렉션으로 내보내기",
    "toGeoJSON": "GeoJSON으로 내보내기"
  },
  "appState": {
    "title": "앱 상태",
    "restoreMap": "작업을 중지한 지점의 맵 범위와 레이어 가시성을 복원하려면 클릭하세요."
  },
  "featureActions": {
    "featureActions": "피처 동작",
    "ZoomTo": "확대/축소",
    "PanTo": "이동",
    "Flash": "깜박이기",
    "ShowPopup": "팝업 표시",
    "CreateLayer": "레이어 생성",
    "ShowStatistics": "통계...",
    "ClearSelection": "선택 해제",
    "ExportToCSV": "CSV 파일로 내보내기",
    "ShowSelectedFeature": "선택한 피처 표시",
    "ExportToFeatureCollection": "피처 컬렉션으로 내보내기",
    "ExportToGeoJSON": "GeoJSON으로 내보내기",
    "EditAttributes": "속성 편집",
    "AddMarker": "표시 추가",
    "RemoveMarker": "표시 제거",
    "SaveToMyContent": "내 콘텐츠에 저장"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "릴레이트된 레이어",
    "selectedFeatures": "선택한 피처 사용",
    "drawShapesTip": "모양을 그려 피처 선택",
    "pleaseDrawShapesTip": "모양을 그려 피처를 선택하세요.",
    "allFeaturesTip": "레이어 내 모든 피처",
    "selectFeaturesOrDrawShapesTip": "피처를 제한하려면 이 레이어에서 선택한 피처를 사용하거나 맵에 도형을 그리세요."
  },
  "searchDistance": {
    "applySearchDistance": "검색 거리 적용",
    "applySearchDistanceToFeatures": "검색 거리를 선택한 피처에 적용"
  },
  "units": {
    "miles": "마일",
    "milesAbbr": "마일",
    "kilometers": "킬로미터",
    "kilometersAbbr": "킬로미터",
    "feet": "피트",
    "feetAbbr": "피트",
    "meters": "미터",
    "metersAbbr": "미터",
    "yards": "야드",
    "yardsAbbr": "야드",
    "acres": "에이커",
    "acresAbbr": "에이커",
    "nauticalMiles": "해리",
    "nauticalMilesAbbr": "nmi",
    "uSSurveyFeet": "미국 측량 피트",
    "uSSurveyFeetAbbr": "ftUS",
    "decimalDegree": "십진수(DD)",
    "decimalDegreeAbbr": "dd",
    "degreeMinuteSeconds": "도-분-초",
    "degreeMinuteSecondsAbbr": "d-m-s",
    "squareMiles": "제곱마일",
    "squareMilesAbbr": "제곱마일",
    "squareKilometer": "제곱킬로미터",
    "squareKilometerAbbr": "제곱킬로미터",
    "squareFeet": "제곱피트",
    "squareFeetAbbr": "제곱피트",
    "squareMeters": "제곱미터",
    "squareMetersAbbr": "제곱미터",
    "squareYards": "제곱야드",
    "squareYardsAbbr": "제곱야드",
    "squareUSSurveyFeet": "미국 측량 평방 피트",
    "squareUSSurveyFeetAbbr": "sq ftUS"
  },
  "featureSetChooser": {
    "select": "선택",
    "dragBox": "드래그",
    "dragMouse": "마우스 드래그",
    "selectByRectangle": "사각형으로 선택",
    "selectFeaturesTip": "맵에서 주위에 있는 상자를 드래그하여 피처 선택",
    "newSelectionTip": "새로운 선택 생성",
    "addSelectionTip": "선택에 추가",
    "removeSelectionTip": "선택 영역에서 제거",
    "selectFromCurrentSelectionTip": "현재 선택에서 다시 선택",
    "unselectAllSelectionTip": "현재 선택한 모든 피처 선택 해제",
    "selectByPolygon": "폴리곤으로 선택",
    "selectByCircle": "원으로 선택",
    "selectByLine": "라인으로 선택",
    "chooseSelectingTools": "선택 도구 선택",
    "darw": "그리기",
    "drawShap": "도형 그리기"
  },
  "widgetManager": {
    "createWidgetError": "위젯 생성 오류",
    "createWidgetSettingPageError": "위젯 설정 페이지 생성 오류",
    "loadWidgetResourceError": "위젯 리소스 로드 오류"
  },
  "shareOptions": {
    "shareMap": "이 앱을 볼 수 있는 사람 선택",
    "shareMapTips": "앱이 현재 이 사람들과 공유되고 있습니다.",
    "everyone": "모든 사람",
    "theseGroups": "다음 그룹"
  },
  "shareLink": {
    "email": "이메일",
    "shareEmail": "이메일",
    "facebook": "Facebook",
    "shareFacebook": "Facebook",
    "twitter": "Twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "Google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "웹 사이트에 이 앱 임베드",
    "shareEmailSubject": "웹 앱 공유:",
    "shareEmailTxt1": "Web AppBuilder for ArcGIS를 사용하여 웹 앱을 공유할 수 있습니다.",
    "shareEmailTxt2": "Esri Web AppBuilder for ArcGIS로 고유 웹 앱을 생성하고 공유할 수 있습니다.",
    "shareEmailTxt3": "자세한 내용은 http://www.esri.com/software/web-appbuilder를 방문하세요.",
    "smallSize": "작게",
    "mediumSize": "중간",
    "largeSize": "크게",
    "customSize": "사용자 정의",
    "embed": "웹 사이트에 이 앱 임베드",
    "more": "옵션 임베드",
    "changeShareSettings": "공유 설정 변경",
    "shareLinkText": "링크를 이 앱에 공유",
    "linkOptions": "링크 옵션",
    "linkOptionsUrlParameters": "링크에 포함된 URL 매개변수 선택",
    "currentMapExtent": "현재 맵 범위",
    "chooseCenterWithLevel": "맵을 클릭한 후 맵의 중심을 확대/축소 수준으로 정의",
    "chooseCenterWithScale": "맵을 클릭한 후 맵의 중심을 맵 축척으로 정의",
    "findLocation": "위치 또는 피처를 찾은 후 확대",
    "findLocation_inputPlaceholder": "장소 또는 피처",
    "queryFeature": "피처를 쿼리하고 확대",
    "addMarker": "맵에 표식 추가",
    "addMarker_titlePlaceholder": "표식 팝업 제목",
    "addMarker_symbolURL": "표식 심볼 URL",
    "addMarker_label": "표식 레이블",
    "popupTitle": "팝업 제목",
    "zoomLevel": "확대 수준",
    "overwirteMobileLayout": "모바일 레이아웃의 기본 화면 크기 덮어쓰기",
    "language": "앱의 표시 언어 설정",
    "auth": "사용자를 자동으로 인증",
    "linkPreview": "링크 미리보기",
    "useShortenLink": "짧은 링크",
    "shareMapUrlExtent": "현재 맵 범위 공유",
    "shareToWebTips": "이 앱은 공개적으로 공유되어 있지 않으므로 사람들은 이 앱을 볼 수 없습니다."
  },
  "webSceneLoader": {
    "webglSupportTip": "3D 웹 앱이 브라우저에서 지원되지 않습니다."
  },
  "map": {
    "basemapNotAvailable": "베이스맵을 사용할 수 없습니다.",
    "displayDefaultBasemap": "기본 베이스맵을 대신 표시합니다.",
    "layerLoadedError": "${layers} 레이어를 맵에 추가할 수 없습니다."
  },
  "popup": {
    "relatedTables": "릴레이트된 테이블:",
    "relatedRecords": "릴레이트된 레코드:",
    "noRelatedRecotds": "릴레이트된 레코드를 찾을 수 없습니다.",
    "chooseFieldTip": "목록에 표시할 속성을 선택합니다.",
    "saveAsPopupTitle": "팝업 제목과 동일"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "선택 항목에 피처가 너무 많습니다. 맵에서 이러한 피처를 검색하고 나타나는 데 시간이 오래 걸릴 수 있습니다.",
    "askForContinue": "계속하시겠습니까?"
  },
  "colorPalette": {
    "transparent": "투명",
    "custom": "사용자 정의"
  },
  "temperature": {
    "celsius": "섭씨",
    "fahrenheit": "화씨"
  },
  "report": {
    "printButtonLabel": "인쇄",
    "reportDimensionsMsg": "이 보고서는 ${paperSize} 용지에 인쇄되도록 만들어졌습니다.",
    "unableToPrintMapMsg": "맵을 인쇄하는 중 오류가 발생했습니다.",
    "notesHint": "여기에 의견 입력",
    "landscape": "가로",
    "portrait": "세로",
    "mapOnly": "MAP_ONLY",
    "a0": "A0",
    "a1": "A1",
    "a2": "A2",
    "a3": "A3",
    "a4": "A4",
    "a5": "A5",
    "letterANSIA": "Letter ANSI A",
    "tabloidANSIB": "Tabloid ANSI B",
    "letter": "Letter",
    "legal": "Legal",
    "tabloid": "Tabloid",
    "ansi_a": "ANSI A",
    "ansi_b": "ANSI B",
    "ansi_c": "ANSI C",
    "ansi_d": "ANSI D",
    "ansi_e": "ANSI E"
  },
  "snapshot": {
    "snapshot_complete": "스냅샷을 생성했습니다.",
    "snapshot_failed": "스냅샷 생성에 실패했습니다.",
    "snapshot_append": "스냅샷",
    "utc": "UTC"
  },
  "statisticsChart": {
    "enlarge": "확대",
    "setting": "설정",
    "count": "개수",
    "horizontalAxis": "수평축",
    "verticalAxis": "수직축",
    "dataLabels": "데이터 레이블",
    "color": "색상"
  },
  "frameworkDatasource": {
    "setDataSource": "데이터 원본 설정",
    "customDataSource": "추가 데이터 원본",
    "selectCustomDataTip": "이 앱에서 데이터 원본을 선택하세요.",
    "widgetOutputs": "위젯 결과",
    "noExtraDsAvailable": "사용 가능한 추가 데이터 원본이 없습니다.",
    "addExtraDsTip": "빌더의 속성 탭으로 이동한 다음, 데이터를 추가할 추가 데이터 원본을 클릭합니다.",
    "widgetOutpusListTip": "위젯 결과(있는 경우)도 여기에 나열됩니다."
  },
  "gridLayout": {
    "addWidgetTip": "위젯 탭을 통해 여기에 위젯 추가",
    "modifyLayout": "레이아웃 수정",
    "dragToAdd": "드래그하여 추가",
    "mapArea": "맵 영역"
  },
  "noEditPrivileges": "내 계정에 데이터를 만들거나 수정할 권한이 없습니다.",
  "invalidConfiguration": "위젯이 구성되지 않았거나 구성의 레이어가 더 이상 맵에 없습니다. 빌더 모드에서 앱을 열고 위젯을 다시 구성하세요."
});