define(
   ({
    _widgetLabel: "جدول البيانات",
    ok: "موافق",
    cancel: "إلغاء الأمر",
    unsupportQueryWarning: "تحتاج الطبقة لدعم عملية الاستعلام لعرضها في عناصر واجهة استخدام البيانات الجدولية. تأكد من تشغيل إمكانات الاستعلام في الخدمة.",
    exportMessage: "هل ترغب في تصدير البيانات إلى ملف CSV؟",
    exportFiles: "التصدير إلى CSV",
    exportSelected: "استيراد المُحدد إلى CSV",
    exportAll: "تصدير الجميع إلى CSV.",
    options: "خيارات",
    zoomto: "تكبير إلى",
    highlight: "تمييز الرسومات",
    selectAll: "حدد جميع التسجيلات بالصفحات",
    selectPage: "حدد التسجيلات بالصفحة الحالية",
    clearSelection: "مسح التحديد",
    filter: "تصفية",
    setFilterTip: "يرجى تعيين عامل التصفية بشكل صحيح.",
    noFilterTip: "بدون تعريف تعبير عوامل التصفية، ستقوم هذه المهمة بإدراج جميع المعالم في مصدر البيانات المًحدد.",
    filterByExtent: "التصفية تبعًا لنطاق الخريطة",
    showSelectedRecords: "عرض السجلات المحددة",
    showAllRecords: "إظهار جميع السجلات",
    showRelatedRecords: "عرض السجلات ذات الصلة",
    noRelatedRecords: "لا توجد سجلات ذات صلة",
    refresh: "تحديث",
    features: "معالم",
    selected: "تم التحديد",
    transparent: "وضع الرسومات",
    indicate: "تحديد موقع التحديد",
    columns: "إظهار/إخفاء الأعمدة",
    selectionSymbol: "رمز التحديد",
    closeMessage: "قم بإخفاء الجدول [أظهره مرة أخرى من الأسفل]",
    dataNotAvailable: "البيانات غير متاحة!<br>انقر على زر [تنشيط] للمحاولة مرة أخرى.",
    openTableTip: "فتح جدول البيانات الجدولية",
    closeTableTip: "إخفاء جدول البيانات"
  })
);