define({
  "_widgetLabel": "坐標",
  "hintMessage": "按一下地圖以取得坐標",
  "defaultLabel": "預設",
  "realtimeLabel": "移動滑鼠以取得坐標",
  "computing": "正在計算...",
  "latitudeLabel": "緯度",
  "longitudeLabel": "經度",
  "loading": "正在載入...",
  "enableClick": "按一下啟用點選地圖以取得坐標",
  "disableClick": "按一下停用點選地圖以取得坐標",
  "Default": "預設",
  "Inches": "英吋",
  "Foot": "英呎",
  "Yards": "碼",
  "Miles": "英里",
  "Nautical_Miles": "海浬",
  "Millimeters": "公釐",
  "Centimeters": "公分",
  "Meter": "公尺",
  "Kilometers": "公里",
  "Decimeters": "公寸",
  "Decimal_Degrees": "度",
  "Degree_Minutes_Seconds": "度分秒",
  "MGRS": "MGRS",
  "USNG": "USNG"
});