define({
  "id": "ID",
  "state": "デフォルトでは、座標は現在のマップの座標系で表示されます。その他の座標系の座標を取得するには、座標系を追加して適切な変換方法を指定する必要があります。",
  "outputUnit": "出力単位",
  "wkid": "出力 WKID",
  "label": "出力座標系名",
  "transformationWkid": "変換 WKID",
  "transformationLabel": "変換ラベル",
  "transformForward": "正方向に変換",
  "actions": "アクション",
  "warning": "有効な空間参照 WKID を入力してください",
  "tfWarning": "有効な測地基準系変換 WKID を入力してください",
  "spinnerLabel": "座標の丸め位置: ",
  "decimalPlace": "小数桁 (複数)",
  "separator": "桁区切り記号を表示",
  "getVersionError": "ジオメトリ サービスのバージョンを取得できません",
  "add": "出力座標系の追加",
  "edit": "座標系の編集",
  "output": "出力座標系",
  "cName": "座標系名",
  "units": "表示単位: ",
  "datum": "測地基準系変換",
  "tName": "変換名",
  "tWKIDPlaceHolder": "変換の WKID",
  "forward": "変換を正方向に使用",
  "ok": "OK",
  "cancel": "キャンセル",
  "olderVersion": "ジオメトリ サービスは変換操作をサポートしていません",
  "REPEATING_ERROR": " 座標系が出力リスト内に存在します。",
  "Default": "デフォルト",
  "Inches": "インチ",
  "Foot": "フィート",
  "Yards": "ヤード",
  "Miles": "マイル",
  "Nautical_Miles": "海里",
  "Millimeters": "ミリメートル",
  "Centimeters": "センチメートル",
  "Meter": "メートル",
  "Kilometers": "キロメートル",
  "Decimeters": "デシメートル",
  "Decimal_Degrees": "度 (10 進)",
  "Degrees_Decimal_Minutes": "度分 (10 進)",
  "Degree_Minutes_Seconds": "度分秒",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "座標の表示順序:",
  "lonLatTips": "経度/緯度 (X、Y)",
  "latLonTips": "緯度/経度 (Y、X)"
});