define({
  "_widgetLabel": "Attribuuttabel",
  "_featureAction_ShowRelatedRecords": "Gerelateerde records weergeven",
  "_featureAction_ViewInTable": "Bekijken in Attribuuttabel",
  "ok": "OK",
  "cancel": "Annuleren",
  "unsupportQueryWarning": "De laag moet querybewerking ondersteunen voor weergave in de widget Attribuuttabel. Zorg ervoor dat de querybewerking in de service aan is.",
  "exportMessage": "Gegevens exporteren naar CSV-bestand?",
  "exportFiles": "Exporteren naar CSV",
  "exportSelected": "Selectie naar CSV exporteren",
  "exportAll": "Alles naar CSV exporteren",
  "options": "Opties",
  "zoomto": "Zoomen naar",
  "highlight": "Grafische elementen markeren",
  "selectAll": "Records op alle pagina´s selecteren",
  "selectPage": "Records op huidige pagina selecteren",
  "clearSelection": "Clear selection",
  "filter": "Filter",
  "setFilterTip": "Stel filters correct in.",
  "noFilterTip": "Zonder filterexpressie zal deze querytaak alle functies in de opgegeven gegevensbron weergeven.",
  "filterByExtent": "Filteren op kaartextent",
  "showSelectedRecords": "Geselecteerde records weergeven",
  "showAllRecords": "Alle records weergeven",
  "showRelatedRecords": "Gerelateerde records weergeven",
  "noRelatedRecords": "Geen verwante records gevonden",
  "attachmentColumn": "Foto's en bestanden",
  "refresh": "Vernieuwen",
  "features": "objecten",
  "records": "records",
  "selected": "geselecteerd",
  "transparent": "Transparante modus",
  "indicate": "Selectie zoeken",
  "columns": "Kolommen weergeven/verbergen",
  "selectionSymbol": "Selectiesymbool",
  "closeMessage": "Tabel verbergen (opnieuw uitvouwen vanaf de onderkant)",
  "dataNotAvailable": "Gegevens niet beschikbaar!<br>Klik op de knop [Vernieuwen] om het nog eens te proberen.",
  "openTableTip": "Attributentabel openen",
  "closeTableTip": "Attributentabel verbergen",
  "sortAsc": "Oplopend sorteren",
  "sortDes": "Aflopend sorteren",
  "statistics": "Statistieken",
  "attachments": "Bijlagen",
  "files": "bestanden"
});