define({
  "_widgetLabel": "Tabel Atribut",
  "_featureAction_ShowRelatedRecords": "Tampilkan rekaman terkait",
  "_featureAction_ViewInTable": "Tampilkan dalam Tabel Atribut",
  "ok": "Ya",
  "cancel": "Batal",
  "unsupportQueryWarning": "Layer harus mendukung operasi query untuk menampilkannya di widget Tabel Atribut. Pastikan kapabilitas query di layanan aktif.",
  "exportMessage": "Ekspor data ke file CSV?",
  "exportFiles": "Ekspor ke CSV",
  "exportSelected": "Ekspor yang dipilih ke CSV",
  "exportAll": "Ekspor semua ke CSV",
  "options": "Opsi",
  "zoomto": "Perbesar hingga",
  "highlight": "Sorot grafik",
  "selectAll": "Pilih catatan di semua halaman",
  "selectPage": "Pilih catatan di halaman saat ini",
  "clearSelection": "Bersihkan pilihan",
  "filter": "Filter",
  "setFilterTip": "Atur filter dengan benar.",
  "noFilterTip": "Tanpa ekspresi filter yang ditetapkan, tugas kueri ini akan mencantumkan semua fitur di sumber data yang ditentukan.",
  "filterByExtent": "Filter menurut jangkauan peta",
  "showSelectedRecords": "Tampilkan catatan yang dipilih",
  "showAllRecords": "Tampilkan semua catatan",
  "showRelatedRecords": "Tampilkan rekaman terkait",
  "noRelatedRecords": "Tidak Ada Catatan Terkait",
  "attachmentColumn": "Foto dan file",
  "refresh": "Segarkan",
  "features": "fitur",
  "records": "rekaman",
  "selected": "terpilih",
  "transparent": "Mode transparan",
  "indicate": "Tentukan lokasi pilihan",
  "columns": "Tampilkan/Sembunyikan kolom",
  "selectionSymbol": "Simbol pilihan",
  "closeMessage": "Sembunyikan tabel (perluas lagi dari bawah)",
  "dataNotAvailable": "Data tidak tersedia!<br>Klik tombol [Refresh] untuk mencoba kembali.",
  "openTableTip": "Buka Tabel Atribut",
  "closeTableTip": "Sembunyikan Tabel Atribut",
  "sortAsc": "Urutkan naik",
  "sortDes": "Urutkan turun",
  "statistics": "Statistik",
  "attachments": "Lampiran",
  "files": "file"
});