define({
  "common": {
    "apply": "Primeni",
    "ok": "U redu",
    "cancel": "Otkaži",
    "yes": "Da",
    "no": "Ne",
    "next": "Sledeće",
    "previous": "Prethodno",
    "back": "Nazad",
    "selected": "izabrano",
    "name": "Naziv",
    "usage": "Korišćenje",
    "settings": "Postavke",
    "home": "Matična stranica",
    "link": "Link",
    "messages": "Poruke",
    "outputs": "Rezultati",
    "title": "Naslov",
    "thumbnail": "Sličica",
    "url": "URL adresa",
    "actions": "Radnje",
    "layer": "Sloj",
    "action": "Radnja",
    "input": "Ulaz",
    "output": "Izlaz",
    "type": "Tip",
    "required": "Obavezno",
    "options": "Opcije",
    "label": "Oznaka",
    "tooltip": "Opis alatke",
    "visible": "Vidljivo",
    "symbol": "Simbol",
    "popup": "Iskačući prozor",
    "upload": "Otpremi",
    "execute": "Izvrši",
    "help": "Pomoć",
    "executing": "Izvršavanje",
    "clear": "Izbriši",
    "error": "Greška",
    "zoomTo": "Uveličaj na",
    "attribute": "Atribut",
    "exports": "Izvezi",
    "check": "Proverite",
    "save": "Sačuvaj",
    "close": "Zatvori",
    "deleteText": "Izbriši",
    "map": "Mapa",
    "scene": "Scena",
    "reset": "Poništi",
    "icon": "Ikona",
    "folder": "Fascikla",
    "share": "Podeli",
    "view": "Prikaži",
    "newText": "Novo",
    "edit": "Izmeni",
    "wkid": "WKID",
    "table": "Tabela",
    "zoomIn": "Uvećanje",
    "zoomOut": "Umanjenje",
    "continue1": "Nastavi",
    "longitude": "Geografska dužina",
    "latitude": "Geografska širina",
    "custom": "Prilagođeno",
    "image": "Snimak",
    "font": "Font",
    "text": "Tekst",
    "all": "Sve",
    "number": "Broj",
    "percentage": "Procenat",
    "unit": "Jedinica",
    "thousand": "Hiljada",
    "billion": "Milijarda",
    "million": "Milion",
    "none": "Ništa",
    "field": "Polje",
    "operation": "Radnja",
    "disableUpdateGeometry": "Onemogući ažuriranje geometrije",
    "preview": "Pregledaj"
  },
  "errorCode": "Kôd",
  "errorMessage": "Poruka",
  "errorDetail": "Detalj",
  "widgetPlaceholderTooltip": "Da biste postavili, idite na „Vidžet“ i kliknite na odgovarajućeg čuvara mesta",
  "fieldStatistics": {
    "selectField": "Izaberite polje",
    "statistics": "Statistika",
    "field": "Polje",
    "count": "Broj vrednosti",
    "sum": "Zbir vrednosti",
    "min": "Minimum",
    "max": "Maksimum",
    "ave": "Prosečno",
    "stddev": "Standardna devijacija"
  },
  "symbolChooser": {
    "preview": "Prikaži",
    "basic": "Osnovna verzija",
    "arrows": "Strelice",
    "business": "Privreda",
    "cartographic": "Kartografija",
    "nationalParkService": "Servis nacionalnih parkova u SAD (National Park Service)",
    "outdoorRecreation": "Rekreacija napolju",
    "peoplePlaces": "Ljudi i mesta",
    "safetyHealth": "Bezbednost i zdravlje",
    "shapes": "Oblici",
    "transportation": "Transport",
    "symbolSize": "Veličina simbola",
    "color": "Boja",
    "alpha": "Alpha",
    "outlineColor": "Boja kontura",
    "outlineWidth": "Širina kontura",
    "style": "Stil",
    "width": "Širina",
    "text": "Tekst",
    "fontColor": "Boja fonta",
    "fontSize": "Veličina fonta",
    "transparency": "Prozirnost",
    "solid": "Neprozirno",
    "dash": "Crta",
    "dot": "Tačka",
    "dashDot": "Crta tačka",
    "dashDotDot": "Crta tačka tačka",
    "customImage": "Prilagođeni snimak",
    "chooseFile": "Izaberite datoteku",
    "noFileChoosen": "Nijedna datoteka nije odabrana."
  },
  "transparency": {
    "opaque": "Neprozirno",
    "transparent": "Prozirno"
  },
  "rendererChooser": {
    "domain": "Domen",
    "use": "Koristi",
    "singleSymbol": "Pojedinačan simbol",
    "uniqueSymbol": "Jedinstveni simboli",
    "color": "Boja",
    "size": "Veličina",
    "toShow": "Za prikaz",
    "colors": "Boje",
    "classes": "Klase",
    "symbolSize": "Veličina simbola",
    "addValue": "Dodaj vrednost",
    "setDefaultSymbol": "Postavi podrazumevani simbol",
    "defaultSymbol": "Podrazumevani simbol",
    "selectedSymbol": "Izabrani simbol",
    "value": "Vrednost",
    "label": "Oznaka",
    "range": "Opseg"
  },
  "drawBox": {
    "point": "Tačka",
    "line": "Linija",
    "polyline": "Poligon",
    "freehandPolyline": "Polilinija slobodnom rukom",
    "triangle": "Trougao",
    "extent": "Obuhvat",
    "circle": "Krug",
    "ellipse": "Elipsa",
    "polygon": "Polilinija",
    "freehandPolygon": "Poligon crtan slobodnom rukom",
    "text": "Tekst",
    "clear": "Izbriši"
  },
  "popupConfig": {
    "title": "Naslov",
    "add": "Dodaj",
    "fields": "Polja",
    "noField": "Nema polja",
    "visibility": "Vidljivo",
    "name": "Naziv",
    "alias": "Pseudonim",
    "actions": "Radnje"
  },
  "includeButton": {
    "include": "Uključi"
  },
  "loadingShelter": {
    "loading": "Učitavanje"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Nema pronađenog servisa.",
    "unableConnectTo": "Nije moguće povezivanje na",
    "invalidUrlTip": "Uneta URL adresa je nevažeća ili nedostupna."
  },
  "serviceBrowser": {
    "noGpFound": "Nema pronađenog servisa geoprocesiranja.",
    "unableConnectTo": "Nije moguće povezivanje na"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Nema pronađenog servisa mape ili servisa geoobjekata.",
    "unableConnectTo": "Nije moguće povezivanje na"
  },
  "basicServiceChooser": {
    "validate": "Proveri valjanost",
    "example": "Primer",
    "set": "Postavi"
  },
  "urlInput": {
    "invalidUrl": "Nevažeća URL adresa."
  },
  "urlComboBox": {
    "invalidUrl": "Nevažeća URL adresa."
  },
  "filterBuilder": {
    "addAnotherExpression": "Dodaj izraz",
    "addSet": "Dodaj skup",
    "matchMsg": "Ubaci u sloj geoobjekte koji se podudaraju sa ${any_or_all} od sledećih izraza",
    "matchMsgSet": "${any_or_all} sledeći izrazi u ovom setu su istiniti",
    "all": "Sve",
    "any": "Bilo koje",
    "value": "Vrednost",
    "field": "Polje",
    "unique": "Jedinstveno",
    "none": "Ništa",
    "and": "i",
    "valueTooltip": "Unesite vrednost",
    "fieldTooltip": "Izaberi iz postojećeg polja",
    "uniqueValueTooltip": "Izaberi iz jedinstvenih vrednosti u izabranom polju",
    "stringOperatorIs": "je",
    "stringOperatorIsNot": "nije",
    "stringOperatorStartsWith": "počinje sa",
    "stringOperatorEndsWith": "završava se sa",
    "stringOperatorContains": "sadrži",
    "stringOperatorDoesNotContain": "ne sadrži",
    "stringOperatorIsBlank": "je prazno",
    "stringOperatorIsNotBlank": "nije prazno",
    "dateOperatorIsOn": "je na",
    "dateOperatorIsNotOn": "nije na",
    "dateOperatorIsBefore": "je ispred",
    "dateOperatorIsAfter": "je iza",
    "dateOperatorIsOnOrBefore": "je na ili pre",
    "dateOperatorIsOnOrAfter": "je na ili posle",
    "dateOperatorMinutes": "minuti",
    "dateOperatorHours": "časova",
    "dateOperatorDays": "dani",
    "dateOperatorWeeks": "sedmice",
    "dateOperatorMonths": "meseci",
    "dateOperatorYears": "godina",
    "dateOperatorInTheLast": "u poslednjih",
    "dateOperatorNotInTheLast": "nije u poslednjih",
    "dateOperatorIsBetween": "je između",
    "dateOperatorIsNotBetween": "nije između",
    "dateOperatorIsBlank": "je prazno",
    "dateOperatorIsNotBlank": "nije prazno",
    "numberOperatorIs": "je",
    "numberOperatorIsNot": "nije",
    "numberOperatorIsAtLeast": "je najmanje",
    "numberOperatorIsLessThan": "je manje od",
    "numberOperatorIsAtMost": "je najviše",
    "numberOperatorIsGreaterThan": "je veće od",
    "numberOperatorIsBetween": "je između",
    "numberOperatorIsNotBetween": "nije između",
    "numberOperatorIsBlank": "je prazno",
    "numberOperatorIsNotBlank": "nije prazno",
    "string": "Niska",
    "number": "Broj",
    "date": "Datum",
    "askForValues": "Traži vrednosti",
    "prompt": "Odziv",
    "hint": "Napomena",
    "error": {
      "invalidParams": "Nevažeći parametri.",
      "invalidUrl": "Nevažeća URL adresa.",
      "noFilterFields": "Sloj nema polja koja mogu da budu korišćena za kreiranje filtera.",
      "invalidSQL": "Nevažeći SQL izraz.",
      "cantParseSQL": "Parsiranje SQL izraza nije moguće."
    },
    "caseSensitive": "Razlikuje velika i mala slova",
    "notSupportCaseSensitiveTip": "Hostovani servisi ne podržavaju upite koji razlikuju velika i mala slova.",
    "setFilterTip": "Pravilno postavite filtere.",
    "listValues": "Izlistaj vrednosti",
    "cascadeFilterTip": "Prikažite samo vrednosti filtrirane po prethodnim izrazima.",
    "noneCascadeFilterTip": "Sve jedinstvene vrednosti u ovom polju",
    "previousCascadeFilterTip": "Vrednosti filtrirane po prethodnim izrazima.",
    "allCascadeFilterTip": "Vrednosti filtrirane po svim drugim izrazima."
  },
  "featureLayerSource": {
    "layer": "Sloj",
    "browse": "Pretraži",
    "selectFromMap": "Mapa",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL servisa",
    "inputLayerUrl": "URL adresa ulaznog sloja",
    "selectLayer": "Izaberite sloj geoobjekata iz trenutne mape.",
    "chooseItem": "Odaberite stavku sloja geoobjekata.",
    "setServiceUrl": "Unesite URL adresu servisa geoobjekata ili servisa mape.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Odaberite sloj geoobjekata."
  },
  "queryableLayerSource": {
    "layer": "Sloj",
    "browse": "Pretraži",
    "selectFromMap": "Mapa",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL servisa",
    "inputLayerUrl": "URL adresa ulaznog sloja",
    "selectLayer": "Izaberi sloj iz trenutne mape.",
    "chooseItem": "Odaberite stavku.",
    "setServiceUrl": "Unesite URL adresu servisa.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Odaberite sloj."
  },
  "gpSource": {
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL servisa",
    "selectFromOnline": "ArcGIS Online",
    "setServiceUrl": "Unesite URL adresu servisa geoprocesiranja.",
    "chooseItem": "Odaberite stavku servisa geoprocesiranja.",
    "chooseTask": "Odaberite zadatak geoprocesiranja."
  },
  "itemSelector": {
    "map": "Mapa",
    "selectWebMap": "Odaberite veb mapu",
    "addMapFromOnlineOrPortal": "Pronađite i dodajte veb mapu u aplikaciju sa ArcGIS Online javnih resursa ili vašeg privatnog sadržaja u ArcGIS Online ili na Portalu.",
    "searchMapName": "Pretraži po imenu mape...",
    "searchNone": "Nismo uspeli da nađemo ono što tražite. Pokušajte ponovo.",
    "groups": "Grupe",
    "noneGroups": "Nema grupa",
    "signInTip": "Vaša sesija prijavljivanja je istekla, osvežite pregledač da biste se ponovo prijavili u portal.",
    "signIn": "Prijavite se",
    "publicMap": "Javni",
    "myOrganization": "Moja organizacija",
    "myGroup": "Moje grupe",
    "myContent": "Moj sadržaj",
    "count": "Brojač",
    "fromPortal": "sa portala",
    "fromOnline": "sa ArcGIS.com",
    "noneThumbnail": "Sličica nije dostupna",
    "owner": "vlasnik",
    "signInTo": "Prijavite se na",
    "lastModified": "Poslednja izmena",
    "moreDetails": "Više detalja",
    "mostRecent": "Najnovije",
    "mostViewed": "Najviše pregledano",
    "highestRated": "Najbolje ocenjeno",
    "viewItemDetails": "Prikaži detalje stavke"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Servis ne podržava upit."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Nema odgovarajućeg sloja dostupnog u mapi."
  },
  "layerInfosMenu": {
    "titleBasemap": "Pozadinske mape",
    "titleLayers": "Operativni slojevi",
    "labelLayer": "Ime sloja",
    "itemZoomTo": "Uveličaj na",
    "itemTransparency": "Prozirnost",
    "itemTransparent": "Prozirno",
    "itemOpaque": "Neprozirno",
    "itemMoveUp": "Pomeri se na gore",
    "itemMoveDown": "Pomeri se na dole",
    "itemDesc": "Opis",
    "itemDownload": "Preuzmi",
    "itemToAttributeTable": "Prikaži u tabeli atributa"
  },
  "imageChooser": {
    "unsupportReaderAPI": "Zaduženja: pregledač ne podržava API čitač podataka",
    "readError": "Čitanje datoteke nije uspelo.",
    "unknowError": "završetak operacija nije moguć",
    "invalidType": "Nevažeći tip datoteke.",
    "cropImage": "Izreži snimak",
    "exceed": "Veličina datoteke ne može da premaši 1024 KB",
    "enableFlash": "Omogućite Adobe Flash pre nego što potražite snimak.",
    "cropWaining": "Odaberite fotografiju čije su dimenzije najmanje ${width} x ${height} piksela.",
    "toolTip": "Za najbolje rezultate, snimak treba da bude ${width} piksela širok i ${height} piksela visok. Ostale veličine će biti prilagođene da se uklope. Prihvatljivi formati snimaka su: PNG, GIF i JPEG."
  },
  "simpleTable": {
    "moveUp": "Pomeri se na gore",
    "moveDown": "Pomeri se na dole",
    "deleteRow": "Obriši",
    "edit": "Izmeni"
  },
  "urlParams": {
    "invalidToken": "Nevažeći token",
    "validateTokenError": "Nevažeći token ili greška na mreži"
  },
  "exportTo": {
    "exportTo": "Izvezi",
    "toCSV": "Izvezi u CSV datoteku",
    "toFeatureCollection": "Izvezi u kolekciju geoobjekata",
    "toGeoJSON": "Izvezi u GeoJSON"
  },
  "appState": {
    "title": "Status aplikacije",
    "restoreMap": "Kliknite da biste vratili obuhvat mape i vidljivost slojeva gde ste stali."
  },
  "featureActions": {
    "featureActions": "Radnje sa geoobjektima",
    "ZoomTo": "Zumiraj na",
    "PanTo": "Pomeri do",
    "Flash": "Blic",
    "ShowPopup": "Prikaži iskačući prozor",
    "CreateLayer": "Kreiraj sloj",
    "ShowStatistics": "Statistika...",
    "ClearSelection": "Izbriši izbor",
    "ExportToCSV": "Izvezi u CSV datoteku",
    "ShowSelectedFeature": "Prikaži izabrane geoobjekte",
    "ExportToFeatureCollection": "Izvezi u kolekciju geoobjekata",
    "ExportToGeoJSON": "Izvezi u GeoJSON",
    "EditAttributes": "Izmeni atribute",
    "AddMarker": "Dodaj marker",
    "RemoveMarker": "Ukloni marker",
    "SaveToMyContent": "Sačuvaj u Mom sadržaju"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Povezani sloj",
    "selectedFeatures": "Koristi izabrane geoobjekte",
    "drawShapesTip": "Nacrtajte oblike da biste izabrali geoobjekte",
    "pleaseDrawShapesTip": "Nacrtajte oblike da biste izabrali geoobjekte",
    "allFeaturesTip": "Svi geoobjekti u sloju",
    "selectFeaturesOrDrawShapesTip": "Koristite selektovane geoobjekte u ovom sloju ili nacrtajte oblike na mapi da biste ograničili geoobjekte."
  },
  "searchDistance": {
    "applySearchDistance": "Primeni rastojanje pretrage",
    "applySearchDistanceToFeatures": "Primeni rastojanje pretrage na izabrane geoobjekte"
  },
  "units": {
    "miles": "Milje",
    "milesAbbr": "mi",
    "kilometers": "Kilometri",
    "kilometersAbbr": "km",
    "feet": "Stope",
    "feetAbbr": "ft",
    "meters": "Metri",
    "metersAbbr": "m",
    "yards": "Jardi",
    "yardsAbbr": "yd",
    "acres": "Ari",
    "acresAbbr": "acres",
    "nauticalMiles": "Nautičke milje",
    "nauticalMilesAbbr": "nmi",
    "uSSurveyFeet": "stope",
    "uSSurveyFeetAbbr": "ftUS",
    "decimalDegree": "Decimalni stepeni",
    "decimalDegreeAbbr": "dd",
    "degreeMinuteSeconds": "Stepeni minuti sekunde",
    "degreeMinuteSecondsAbbr": "st-min-sek",
    "squareMiles": "Kvadratne milje",
    "squareMilesAbbr": "mi²",
    "squareKilometer": "Kvadratni kilometri",
    "squareKilometerAbbr": "km²",
    "squareFeet": "Kvadratne stope",
    "squareFeetAbbr": "ft²",
    "squareMeters": "Kvadratni metri",
    "squareMetersAbbr": "m²",
    "squareYards": "Kvadratne jarde",
    "squareYardsAbbr": "yd²",
    "squareUSSurveyFeet": "Kvadratne stope",
    "squareUSSurveyFeetAbbr": "sq ftUS"
  },
  "featureSetChooser": {
    "select": "Izaberi",
    "dragBox": "Prevuci",
    "dragMouse": "Prevucite mišem",
    "selectByRectangle": "Selektuj pomoću pravougaonika",
    "selectFeaturesTip": "Izaberite geoobjekat prevlačenjem pravougaonika oko njih na mapi",
    "newSelectionTip": "Kreiraj novi izbor",
    "addSelectionTip": "Dodaj u izbor",
    "removeSelectionTip": "Ukloni iz izbora",
    "selectFromCurrentSelectionTip": "Izaberi iz trenutnog izbora",
    "unselectAllSelectionTip": "Poništi sve trenutno izabrane geoobjekte",
    "selectByPolygon": "Selektuj pomoću poligona",
    "selectByCircle": "Selektuj pomoću kruga",
    "selectByLine": "Selektuj pomoću linije",
    "chooseSelectingTools": "Izaberi alate za selekciju",
    "darw": "Nacrtaj",
    "drawShap": "Nacrtajte oblik"
  },
  "widgetManager": {
    "createWidgetError": "Greška pri kreiranju vidžeta",
    "createWidgetSettingPageError": "Greška na stranici za podešavanja pri kreiranju vidžeta",
    "loadWidgetResourceError": "Greška pri učitavanju resursa vidžeta"
  },
  "shareOptions": {
    "shareMap": "Odaberite ko može da pregleda ovu aplikaciju",
    "shareMapTips": "Vaša aplikacija se trenutno deli sa ovim osobama",
    "everyone": "Svi",
    "theseGroups": "Ove grupe"
  },
  "shareLink": {
    "email": "e-pošta",
    "shareEmail": "E-mail",
    "facebook": "facebook",
    "shareFacebook": "Facebook",
    "twitter": "twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "Ugradi ovu aplikaciju u veb sajt",
    "shareEmailSubject": "Deljenje veb aplikacije:",
    "shareEmailTxt1": "Evo veb aplikacije koja se deli sa vama pomoću Veb AppBuilder-a za ArcGIS.",
    "shareEmailTxt2": "Možete da kreirate i delite svoju veb aplikaciju pomoću Esri Veb AppBuilder-a za ArcGIS.",
    "shareEmailTxt3": "Posetite http://www.esri.com/software/web-appbuilder za detalje.",
    "smallSize": "Malo",
    "mediumSize": "Srednje",
    "largeSize": "Veliko",
    "customSize": "Prilagođeno",
    "embed": "Ugradi ovu aplikaciju u veb sajt",
    "more": "Opcije za ugrađivanje",
    "changeShareSettings": "Promeni postavke za deljenje",
    "shareLinkText": "Deli link do ove aplikacije",
    "linkOptions": "Opcije linka",
    "linkOptionsUrlParameters": "Izaberite URL parametre uključene u link",
    "currentMapExtent": "Trenutni obuhvat mape",
    "chooseCenterWithLevel": "Kliknite na mapu da biste definisali centar mape sa nivoom zumiranja",
    "chooseCenterWithScale": "Kliknite na mapu da biste definisali centar mape sa razmerom mape",
    "findLocation": "Nađite lokaciju ili geoobjekat i zumirajte do njega",
    "findLocation_inputPlaceholder": "Vaše mesto ili geoobjekat",
    "queryFeature": "Izvršite upit za geoobjekat i zumirajte do njega",
    "addMarker": "Dodaj obeleživač na mapi",
    "addMarker_titlePlaceholder": "Naslov iskačućeg prozora obeleživača",
    "addMarker_symbolURL": "URL adresa simbola obeleživača",
    "addMarker_label": "Oznaka obeleživača",
    "popupTitle": "Naslov iskačućeg prozora",
    "zoomLevel": "Nivo zumiranja",
    "overwirteMobileLayout": "Piši preko podrazumevane veličine ekrana mobilnog rasporeda",
    "language": "Podesi jezik za prikaz aplikacije",
    "auth": "Automatski potvrdi identitet korisnika",
    "linkPreview": "Pregled linka",
    "useShortenLink": "Kratak link",
    "shareMapUrlExtent": "Podeli trenutni obuhvat mape",
    "shareToWebTips": "Ova aplikacija nije deljena javno. Druge osobe možda neće moći da je vide."
  },
  "webSceneLoader": {
    "webglSupportTip": "3D veb aplikacije nisu podržane u vašem pregledaču."
  },
  "map": {
    "basemapNotAvailable": "Pozadinska mapa nije dostupna.",
    "displayDefaultBasemap": "Prikazuje se podrazumevana pozadinska mapa.",
    "layerLoadedError": "Sloj, ${layers} nije moguće dodati na mapu."
  },
  "popup": {
    "relatedTables": "Povezane tabele:",
    "relatedRecords": "Povezani zapisi:",
    "noRelatedRecotds": "Nema pronađenih povezanih zapisa.",
    "chooseFieldTip": "Odaberite atribut za prikaz liste",
    "saveAsPopupTitle": "Isti kao naslov iskačućeg prozora"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "Vaš izbor sadrži previše geoobjekata. Njihovo preuzimanje i prikazivanje na mapi može da potraje.",
    "askForContinue": "Želite li da nastavite?"
  },
  "colorPalette": {
    "transparent": "Prozirno",
    "custom": "Prilagođeno"
  },
  "temperature": {
    "celsius": "Celzijus",
    "fahrenheit": "Farenhajt"
  },
  "report": {
    "printButtonLabel": "Odštampaj",
    "reportDimensionsMsg": "Ovaj izveštaj je dizajniran za štampanje na ${paperSize} papiru",
    "unableToPrintMapMsg": "Došlo je do greške prilikom štampanja mape/mapa.",
    "notesHint": "Unesite komentare ovde",
    "landscape": "Pejzaž",
    "portrait": "Uspravno",
    "mapOnly": "MAP_ONLY",
    "a0": "A0",
    "a1": "A1",
    "a2": "A2",
    "a3": "A3",
    "a4": "A4",
    "a5": "A5",
    "letterANSIA": "Pismo ANSI A",
    "tabloidANSIB": "Tabloid ANSI B",
    "letter": "Pismo",
    "legal": "Pravno",
    "tabloid": "Tabloid",
    "ansi_a": "ANSI A",
    "ansi_b": "ANSI B",
    "ansi_c": "ANSI C",
    "ansi_d": "ANSI D",
    "ansi_e": "ANSI E"
  },
  "snapshot": {
    "snapshot_complete": "Uspešno kreiranje snapshot-a.",
    "snapshot_failed": "Kreiranje snapshot-a nije uspelo.",
    "snapshot_append": "Snapshot",
    "utc": "UTC"
  },
  "statisticsChart": {
    "enlarge": "Uvećaj",
    "setting": "Postavka",
    "count": "Brojač",
    "horizontalAxis": "Horizontalna osa",
    "verticalAxis": "Vertikalna osa",
    "dataLabels": "Oznake podataka",
    "color": "Boja"
  },
  "frameworkDatasource": {
    "setDataSource": "Postavi izvor podataka",
    "customDataSource": "Dodatni izvor podataka",
    "selectCustomDataTip": "Odaberite izvor podataka iz ove aplikacije.",
    "widgetOutputs": "Izlazni vidžet",
    "noExtraDsAvailable": "Nema dostupnih dodatnih izvora podataka.",
    "addExtraDsTip": "Otvorite karticu Atribut u alatki za izradu, pa kliknite na Dodatni izvor podataka da biste dodali podatke.",
    "widgetOutpusListTip": "Izlaz vidžeta (ako postoji) takođe se navodi ovde."
  },
  "gridLayout": {
    "addWidgetTip": "Dodajte vidžet ovde pomoću vidžet kartice",
    "modifyLayout": "Izmenite raspored",
    "dragToAdd": "Prevucite za dodavanje",
    "mapArea": "OBLAST MAPE"
  },
  "noEditPrivileges": "Vaš nalog nema dozvolu za kreiranje ili izmenu podataka.",
  "invalidConfiguration": "Vidžet nije konfigurisan ili slojevi u konfiguraciji više nisu na mapi. Otvorite aplikaciju u režimu za izradu i ponovo konfigurišite vidžet."
});