define({
  "instruction": "Selezionare e configurare layer che verranno mostrati inizialmente nella Tabella attributi.",
  "label": "Layer",
  "show": "Mostra",
  "actions": "Configura campi layer",
  "field": "Campo",
  "alias": "Alias",
  "visible": "Visibile",
  "linkField": "Campo collegamento",
  "noLayers": "Nessun feature layer non disponibile",
  "back": "Indietro",
  "exportCSV": "Consenti esportazione in CSV",
  "expand": "Espandere innanzitutto il widget",
  "filterByExtent": "Abilita Filtra per estensione mappa per impostazione predefinita",
  "restore": "Ripristina valore predefinito",
  "ok": "OK",
  "cancel": "Annulla",
  "includePoint": "Includi coordinate del punto nel file esportato",
  "configureLayerFields": "Configura campi layer",
  "result": "Salvataggio riuscito",
  "warning": "Selezionare prima l'opzione Mostra.",
  "fieldCheckWarning": "È necessario selezionare almeno un campo.",
  "unsupportQueryWarning": "Il layer deve supportare la funzionalità delle query per essere visualizzato nel widget Tabella attributi. Accertarsi che la funzionalità delle query in questo servizio sia abilitata.",
  "unsupportQueryLayers": "I seguenti layer devono supportare la funzionalità delle query per essere visualizzati nel widget Tabella attributi. Accertarsi che la funzionalità delle query in questo servizio sia abilitata.",
  "fieldName": "Nome",
  "fieldAlias": "Alias",
  "fieldVisibility": "Visibilità",
  "fieldActions": "Azioni",
  "showAttachments": "Mostra allegati"
});