define({
  "common": {
    "apply": "Aplicar",
    "ok": "Ok",
    "cancel": "Cancelar",
    "yes": "Sim",
    "no": "Não",
    "next": "Seguinte",
    "previous": "Anterior",
    "back": "Regressar",
    "selected": "selecionadas",
    "name": "Nome",
    "usage": "Utilização",
    "settings": "Configurações",
    "home": "Início",
    "link": "Ligação",
    "messages": "Mensagens",
    "outputs": "Dados de Saída",
    "title": "Título",
    "thumbnail": "Miniatura",
    "url": "URL",
    "actions": "Ações",
    "layer": "Camada",
    "action": "Ação",
    "input": "Introdução",
    "output": "Saída",
    "type": "Tipo",
    "required": "Exigido",
    "options": "Opções",
    "label": "Rótulo",
    "tooltip": "Conselho de utilização",
    "visible": "Visível",
    "symbol": "Símbolo",
    "popup": "Janela popup",
    "upload": "Carregar",
    "execute": "Executar",
    "help": "Ajuda",
    "executing": "A executar",
    "clear": "Limpar",
    "error": "Erro",
    "zoomTo": "Efectuar zoom para",
    "attribute": "Atributo",
    "exports": "Exportar",
    "check": "Verificar",
    "save": "Guardar",
    "close": "Fechar",
    "deleteText": "Excluir",
    "map": "Mapa",
    "scene": "Cena 3D",
    "reset": "Redefinir",
    "icon": "Ícone",
    "folder": "Pasta",
    "share": "Partilhar",
    "view": "Ver",
    "newText": "Novo",
    "edit": "Editar",
    "wkid": "WKID",
    "table": "Tabela",
    "zoomIn": "Aumentar Zoom",
    "zoomOut": "Reduzir zoom",
    "continue1": "Continuar",
    "longitude": "Longitude",
    "latitude": "Latitude",
    "custom": "Personalizar",
    "image": "Imagem",
    "font": "Fonte",
    "text": "Texto",
    "all": "Todas",
    "number": "Número",
    "percentage": "Percentagem",
    "unit": "Unidade",
    "thousand": "Milhar",
    "billion": "Bilião",
    "million": "Milhão",
    "none": "Nenhum",
    "field": "Campo",
    "operation": "Operação",
    "disableUpdateGeometry": "Desativar Atualizar Geometria",
    "preview": "Pré-Visualizar"
  },
  "errorCode": "Código",
  "errorMessage": "Mensagem",
  "errorDetail": "Detalhe",
  "widgetPlaceholderTooltip": "Para configurar, vá a Widgets e clique no placehorlder correspondente",
  "fieldStatistics": {
    "selectField": "Selecionar Campo",
    "statistics": "Estatísticas",
    "field": "Campo",
    "count": "Número de valores",
    "sum": "Soma de valores",
    "min": "Mínimo",
    "max": "Máximo",
    "ave": "Média",
    "stddev": "Desvio padrão"
  },
  "symbolChooser": {
    "preview": "Pré-visualizar",
    "basic": "Básico",
    "arrows": "Setas",
    "business": "Negócio",
    "cartographic": "Cartográfico",
    "nationalParkService": "Serviço nacional de parques",
    "outdoorRecreation": "Lazer no exterior",
    "peoplePlaces": "Locais de pessoas",
    "safetyHealth": "Segurança saúde",
    "shapes": "Formas",
    "transportation": "Transportes",
    "symbolSize": "Tamanho de símbolos",
    "color": "Cor",
    "alpha": "Alfa",
    "outlineColor": "Cor do contorno",
    "outlineWidth": "Largura do contorno",
    "style": "Estilo",
    "width": "Largura",
    "text": "Texto",
    "fontColor": "Cor da letra",
    "fontSize": "Tamanho de letra",
    "transparency": "Transparência",
    "solid": "Sólido",
    "dash": "Traço",
    "dot": "Ponto",
    "dashDot": "Traço ponto",
    "dashDotDot": "Traço, ponto ponto",
    "customImage": "Imagem personalizada",
    "chooseFile": "Escolher ficheiro",
    "noFileChoosen": "Nenhum ficheiro escolhido."
  },
  "transparency": {
    "opaque": "Opaco",
    "transparent": "Transparente"
  },
  "rendererChooser": {
    "domain": "Domínio",
    "use": "Utilize",
    "singleSymbol": "Um único símbolo",
    "uniqueSymbol": "Símbolos únicos",
    "color": "Cor",
    "size": "Tamanho",
    "toShow": "Para exibir",
    "colors": "Cores",
    "classes": "Classes",
    "symbolSize": "Tamanho de símbolos",
    "addValue": "Adicionar valor",
    "setDefaultSymbol": "Definir símbolo padrão",
    "defaultSymbol": "Símbolo Padrão",
    "selectedSymbol": "Símbolo selecionado",
    "value": "Valor",
    "label": "Rótulo",
    "range": "Intervalo"
  },
  "drawBox": {
    "point": "Ponto",
    "line": "Linha",
    "polyline": "Polilinha",
    "freehandPolyline": "Polilinha à mão livre",
    "triangle": "Triângulo",
    "extent": "Extensão",
    "circle": "Círculo",
    "ellipse": "Elipse",
    "polygon": "Polígono",
    "freehandPolygon": "Polígono à mão livre",
    "text": "Texto",
    "clear": "Apagar"
  },
  "popupConfig": {
    "title": "Título",
    "add": "Adicionar",
    "fields": "Campos",
    "noField": "Sem Campo",
    "visibility": "Visível",
    "name": "Nome",
    "alias": "Nome Alternativo",
    "actions": "Acções"
  },
  "includeButton": {
    "include": "Incluir"
  },
  "loadingShelter": {
    "loading": "A carregar"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Não foi encontrado qualquer serviço.",
    "unableConnectTo": "Impossível ligar a",
    "invalidUrlTip": "O URL que introduziu é inválido ou encontra-se inacessível."
  },
  "serviceBrowser": {
    "noGpFound": "Não foi encontrado qualquer serviço de geoprocessamento.",
    "unableConnectTo": "Impossível ligar a"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Não foi encontrado qualquer serviço de mapa ou de elementos.",
    "unableConnectTo": "Impossível ligar a"
  },
  "basicServiceChooser": {
    "validate": "Validar",
    "example": "Exemplo",
    "set": "Definir"
  },
  "urlInput": {
    "invalidUrl": "Url inválido."
  },
  "urlComboBox": {
    "invalidUrl": "Url inválido."
  },
  "filterBuilder": {
    "addAnotherExpression": "Adicionar uma expressão",
    "addSet": "Adicionar um conjunto",
    "matchMsg": "Obter elementos na camada que correspondam a ${any_or_all} das expressões seguintes",
    "matchMsgSet": "${any_or_all} (d)as expressões seguintes neste conjunto são verdadeiras",
    "all": "Todos",
    "any": "Qualquer",
    "value": "Valor",
    "field": "Campo",
    "unique": "Único",
    "none": "Nenhum",
    "and": "e",
    "valueTooltip": "Introduzir valor",
    "fieldTooltip": "Escolher a partir de um campo existente",
    "uniqueValueTooltip": "Escolher a partir de valores únicos no campo selecionado",
    "stringOperatorIs": "é",
    "stringOperatorIsNot": "não é",
    "stringOperatorStartsWith": "começa por",
    "stringOperatorEndsWith": "acaba em",
    "stringOperatorContains": "contém",
    "stringOperatorDoesNotContain": "não contém",
    "stringOperatorIsBlank": "está vazio",
    "stringOperatorIsNotBlank": "não está vazio",
    "dateOperatorIsOn": "é em",
    "dateOperatorIsNotOn": "não é em",
    "dateOperatorIsBefore": "é anterior a",
    "dateOperatorIsAfter": "é posterior a",
    "dateOperatorIsOnOrBefore": "está em ou antes",
    "dateOperatorIsOnOrAfter": "está em ou depois",
    "dateOperatorMinutes": "minutos",
    "dateOperatorHours": "horas",
    "dateOperatorDays": "dias",
    "dateOperatorWeeks": "semanas",
    "dateOperatorMonths": "meses",
    "dateOperatorYears": "anos",
    "dateOperatorInTheLast": "nos(as) últimos(as)",
    "dateOperatorNotInTheLast": "não nos(as) últimos(as)",
    "dateOperatorIsBetween": "é entre",
    "dateOperatorIsNotBetween": "não é entre",
    "dateOperatorIsBlank": "está vazio",
    "dateOperatorIsNotBlank": "não está vazio",
    "numberOperatorIs": "é",
    "numberOperatorIsNot": "não é",
    "numberOperatorIsAtLeast": "é no mínimo",
    "numberOperatorIsLessThan": "é inferior a",
    "numberOperatorIsAtMost": "é no máximo",
    "numberOperatorIsGreaterThan": "é superior a",
    "numberOperatorIsBetween": "é entre",
    "numberOperatorIsNotBetween": "não é entre",
    "numberOperatorIsBlank": "está vazio",
    "numberOperatorIsNotBlank": "não está vazio",
    "string": "Texto",
    "number": "Número",
    "date": "Data",
    "askForValues": "Solicitar valores",
    "prompt": "Solicitação",
    "hint": "Dica",
    "error": {
      "invalidParams": "Parâmetros inválidos.",
      "invalidUrl": "Url inválido.",
      "noFilterFields": "A camada não tem quaisquer campos que possam ser utilizados para criar filtros.",
      "invalidSQL": "Expressão sql inválida.",
      "cantParseSQL": "Impossível analisar a expressão sql."
    },
    "caseSensitive": "Diferencia letras maiúsculas de minúsculas",
    "notSupportCaseSensitiveTip": "Os serviços alojados não suportam consultas que diferenciam maiúsculas de minúsculas.",
    "setFilterTip": "Por favor, defina os filtros corretamente.",
    "listValues": "Listar valores",
    "cascadeFilterTip": "Apenas valores filtrados por expressões anteriores.",
    "noneCascadeFilterTip": "Todos os valores únicos deste campo",
    "previousCascadeFilterTip": "Valores filtrados por expressões anteriores",
    "allCascadeFilterTip": "Valores filtrados por todas as restantes expressões"
  },
  "featureLayerSource": {
    "layer": "Camada",
    "browse": "Procurar",
    "selectFromMap": "Mapa",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL de Serviço",
    "inputLayerUrl": "URL da camada de entrada",
    "selectLayer": "Selecionar uma camada de elementos do mapa atual.",
    "chooseItem": "Escolher um item da camada de elementos.",
    "setServiceUrl": "Introduza o URL de um serviço de elementos ou de um serviço de mapas.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Escolha uma camada de elementos."
  },
  "queryableLayerSource": {
    "layer": "Camada",
    "browse": "Procurar",
    "selectFromMap": "Mapa",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL de Serviço",
    "inputLayerUrl": "URL da camada de entrada",
    "selectLayer": "Seleccionar uma camada do mapa actual.",
    "chooseItem": "Escolher um item.",
    "setServiceUrl": "Introduza o URL do serviço.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Escolher uma camada."
  },
  "gpSource": {
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL de Serviço",
    "selectFromOnline": "ArcGIS Online",
    "setServiceUrl": "Insira o URL de um serviço de geoprocessamento.",
    "chooseItem": "Escolha um item de serviço de geoprocessamento.",
    "chooseTask": "Escolha uma tarefa de geoprocessamento."
  },
  "itemSelector": {
    "map": "Mapa",
    "selectWebMap": "Escolha mapa web",
    "addMapFromOnlineOrPortal": "Encontre e adicione um mapa web na aplicação a partir dos recursos públicos ArcGIS Online ou do seu conteúdo privado, no ArcGIS Online ou no Portal.",
    "searchMapName": "Pesquisar por nome do mapa...",
    "searchNone": "Não conseguimos encontrar aquilo que procura. Por favor, tente outra pesquisa.",
    "groups": "Grupos",
    "noneGroups": "Sem grupos",
    "signInTip": "Por favor, inicie sessão para aceder ao seu conteúdo privado.",
    "signIn": "Iniciar sessão",
    "publicMap": "Público",
    "myOrganization": "A Organização",
    "myGroup": "Os Meus Grupos",
    "myContent": "O Meu Conteúdo",
    "count": "Contagem",
    "fromPortal": "do Portal",
    "fromOnline": "de ArcGIS.com",
    "noneThumbnail": "Imagem miniatura indisponível",
    "owner": "proprietário",
    "signInTo": "Iniciar sessão em",
    "lastModified": "Última atualização",
    "moreDetails": "Mais detalhes",
    "mostRecent": "Mais recente",
    "mostViewed": "Mais visualizado",
    "highestRated": "Com maior classificação",
    "viewItemDetails": "Visualizar detalhes do item"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "O serviço não suporta consultas."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Não existe uma camada apropriada disponível no mapa."
  },
  "layerInfosMenu": {
    "titleBasemap": "Mapas base",
    "titleLayers": "Camadas operacionais",
    "labelLayer": "Nome da camada",
    "itemZoomTo": "Efetuar zoom para",
    "itemTransparency": "Transparência",
    "itemTransparent": "Transparente",
    "itemOpaque": "Opaco",
    "itemMoveUp": "Mover para cima",
    "itemMoveDown": "Mover para baixo",
    "itemDesc": "Descrição",
    "itemDownload": "Descarregar",
    "itemToAttributeTable": "Visualizar em Tabela de Atributos"
  },
  "imageChooser": {
    "unsupportReaderAPI": "Todo: O navegador não suporta a API do leitor de ficheiros",
    "readError": "Falha ao ler o ficheiro.",
    "unknowError": "impossível completar operações",
    "invalidType": "Tipo de ficheiro inválido.",
    "cropImage": "Recortar Imagem",
    "exceed": "O tamanho do ficheiro não pode exceder 1024 KB",
    "enableFlash": "Por favor, ative o Adobe Flash antes de navegar até uma imagem.",
    "cropWaining": "Por favor escolha uma fotografa que tenha pelo menos ${width} x ${height} pixels.",
    "toolTip": "Para obter melhores resultados, a imagem deverá ter ${width} pixéis de largura por ${height} pixéis de altura. Outros tamanhos serão ajustados para caberem. Os formatos de imagem aceitáveis são: PNG, GIF e JPEG."
  },
  "simpleTable": {
    "moveUp": "Mover para cima",
    "moveDown": "Mover para baixo",
    "deleteRow": "Eliminar",
    "edit": "Editar"
  },
  "urlParams": {
    "invalidToken": "Token inválido",
    "validateTokenError": "Token inválido ou erro de Rede"
  },
  "exportTo": {
    "exportTo": "Exportar",
    "toCSV": "Exportar para ficheiro CSV",
    "toFeatureCollection": "Exportar para coleção de elementos",
    "toGeoJSON": "Exportar para GeoJSON"
  },
  "appState": {
    "title": "Estado de Aplicação",
    "restoreMap": "Clique para restaurar a extensão de mapa e camadas de visibilidade de onde saiu."
  },
  "featureActions": {
    "featureActions": "Acções de elementos",
    "ZoomTo": "Efectuar zoom para",
    "PanTo": "Mover para",
    "Flash": "Flash",
    "ShowPopup": "Mostrar janela pop-up",
    "CreateLayer": "Criar camada",
    "ShowStatistics": "Estatísticas...",
    "ClearSelection": "Limpar seleção",
    "ExportToCSV": "Exportar para ficheiro CSV",
    "ShowSelectedFeature": "Exibir elementos selecionados",
    "ExportToFeatureCollection": "Exportar para coleção de elementos",
    "ExportToGeoJSON": "Exportar para GeoJSON",
    "EditAttributes": "Editar atributos",
    "AddMarker": "Adicionar um marcador",
    "RemoveMarker": "Remover marcador",
    "SaveToMyContent": "Guardar em O Meu Conteúdo"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Camada relacionada",
    "selectedFeatures": "Utilizar elementos seleccionados",
    "drawShapesTip": "Desenhar formas para selecionar elementos",
    "pleaseDrawShapesTip": "Por favor, desenhe formas para selecionar elementos",
    "allFeaturesTip": "Todos os elementos presentes na camada",
    "selectFeaturesOrDrawShapesTip": "Por favor, utilize elementos selecionados nesta camada ou desenhe formas no mapa para limitar elementos."
  },
  "searchDistance": {
    "applySearchDistance": "Aplique uma distância de pesquisa",
    "applySearchDistanceToFeatures": "Aplicar uma distência de seleção para os elementos selecionados"
  },
  "units": {
    "miles": "Milhas",
    "milesAbbr": "milhas",
    "kilometers": "Quilómetros",
    "kilometersAbbr": "km",
    "feet": "Pés",
    "feetAbbr": "ft",
    "meters": "Metros",
    "metersAbbr": "m",
    "yards": "Jardas",
    "yardsAbbr": "yd",
    "acres": "Acres",
    "acresAbbr": "acres",
    "nauticalMiles": "Milhas Náuticas",
    "nauticalMilesAbbr": "nmi",
    "uSSurveyFeet": "Pés US survey",
    "uSSurveyFeetAbbr": "ftUS",
    "decimalDegree": "Graus decimais",
    "decimalDegreeAbbr": "dd",
    "degreeMinuteSeconds": "Grau minuto segundos",
    "degreeMinuteSecondsAbbr": "d-m-s",
    "squareMiles": "Milhas quadradas",
    "squareMilesAbbr": "milhas2",
    "squareKilometer": "Quilómetros quadrados",
    "squareKilometerAbbr": "km2",
    "squareFeet": "Pés quadrados",
    "squareFeetAbbr": "pés2",
    "squareMeters": "Metros quadrados",
    "squareMetersAbbr": "m2",
    "squareYards": "Jardas quadradas",
    "squareYardsAbbr": "jardas2",
    "squareUSSurveyFeet": "Pés quadrados US survey",
    "squareUSSurveyFeetAbbr": "sq ftUS"
  },
  "featureSetChooser": {
    "select": "Seleccionar",
    "dragBox": "Arrastar",
    "dragMouse": "Arrastar o ponteiro do rato",
    "selectByRectangle": "Selecionar por retângulo",
    "selectFeaturesTip": "Selecionar elementos arrastando uma caixa ao redor dos mesmos no mapa",
    "newSelectionTip": "Criar nova seleção",
    "addSelectionTip": "Adicionar à seleção",
    "removeSelectionTip": "Remover da seleção",
    "selectFromCurrentSelectionTip": "Selecionar da seleção atual",
    "unselectAllSelectionTip": "Desselecionar todos os elementos atualmente selecionados",
    "selectByPolygon": "Selecionar por polígono",
    "selectByCircle": "Selecionar por círculo",
    "selectByLine": "Selecionar por linha",
    "chooseSelectingTools": "Escolha ferramentas de seleção",
    "darw": "Desenhar",
    "drawShap": "Desenhar a forma"
  },
  "widgetManager": {
    "createWidgetError": "Criar erro de widget",
    "createWidgetSettingPageError": "Criar erro de página de definição de widget",
    "loadWidgetResourceError": "Carregar erro de recurso de widget"
  },
  "shareOptions": {
    "shareMap": "Escolher quem pode visualizar esta aplicação",
    "shareMapTips": "A sua aplicação está atualmente partilhada com estas pessoas",
    "everyone": "Todos",
    "theseGroups": "Estes grupos"
  },
  "shareLink": {
    "email": "correio eletrónico",
    "shareEmail": "Correio Eletrónico",
    "facebook": "facebook",
    "shareFacebook": "Facebook",
    "twitter": "twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "Incorporar este mapa num site web",
    "shareEmailSubject": "Incorporar esta aplicação num site web",
    "shareEmailTxt1": "Aqui está uma aplicação web partilhada consigo utilizando o Web AppBuilder for ArcGIS.",
    "shareEmailTxt2": "Pode criar e partilhar a sua própria aplicação com o Esri Web AppBuilder for ArcGIS.",
    "shareEmailTxt3": "Visite http://www.esri.com/software/web-appbuilder para obter detalhes.",
    "smallSize": "Pequeno",
    "mediumSize": "Média",
    "largeSize": "Grande",
    "customSize": "Personalizar",
    "embed": "Incorporar este mapa num site web",
    "more": "Opções de Incorporação",
    "changeShareSettings": "Alterar definições de partilha",
    "shareLinkText": "Partilhar uma ligação para esta aplicação",
    "linkOptions": "Opções de ligação",
    "linkOptionsUrlParameters": "Selecionar parâmetros de URL incluídos na ligação",
    "currentMapExtent": "Mapa extensão actual",
    "chooseCenterWithLevel": "Clicar no mapa para definir o centro do mapa com nível de zoom",
    "chooseCenterWithScale": "Clicar no mapa para definir o centro do mapa com escala de mapa",
    "findLocation": "Encontrar a localização ou elemento e aplicar zoom no mesmo",
    "findLocation_inputPlaceholder": "O seu local ou elemento",
    "queryFeature": "Consultar um elemento e aplicar zoom ao mesmo",
    "addMarker": "Adicionar um marcador no mapa",
    "addMarker_titlePlaceholder": "Título da janela pop-up do marcador",
    "addMarker_symbolURL": "URL de símbolo do marcador",
    "addMarker_label": "Rótulo do marcador",
    "popupTitle": "Título da janela Pop-up",
    "zoomLevel": "Nível de Zoom",
    "overwirteMobileLayout": "Substituir dimensão de ecrã predefinida para o layout móvel",
    "language": "Definir idioma de exibição da aplicação",
    "auth": "Autenticar um utilizador automaticamente",
    "linkPreview": "Pré-visualização da ligação",
    "useShortenLink": "Ligação curta",
    "shareMapUrlExtent": "Partilhar a atual extensão de mapa",
    "shareToWebTips": "Esta aplicação não está partilhada com o público. As pessoas poderão não ser capazes de visualizá-la."
  },
  "webSceneLoader": {
    "webglSupportTip": "As aplicações web 3D não são suportadas no seu navegador."
  },
  "map": {
    "basemapNotAvailable": "O Mapa Base não se encontra disponível.",
    "displayDefaultBasemap": "Exibir o mapa base predefinido ao invés.",
    "layerLoadedError": "A camada, ${layers} não pode ser adicionada ao mapa."
  },
  "popup": {
    "relatedTables": "Tabelas relacionadas:",
    "relatedRecords": "Registos relacionados:",
    "noRelatedRecotds": "Não foram encontrados quaisquer registos relacionados.",
    "chooseFieldTip": "Escolha um atributo para exibir a lista.",
    "saveAsPopupTitle": "Igual ao título da janela pop-up"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "Existem demasiados elementos na sua seleção. Poderá demorar bastante a obtê-los e a exibi-los no mapa.",
    "askForContinue": "Deseja continuar?"
  },
  "colorPalette": {
    "transparent": "Transparente",
    "custom": "Personalizar"
  },
  "temperature": {
    "celsius": "Celsius",
    "fahrenheit": "Fahrenheit"
  },
  "report": {
    "printButtonLabel": "Imprimir",
    "reportDimensionsMsg": "Este relatório foi concebido para ser imprimido em Papel ${paperSize}",
    "unableToPrintMapMsg": "Ocorreu um erro ao imprimir o(s) mapa(s).",
    "notesHint": "Introduzir comentários aqui",
    "landscape": "Paisagem",
    "portrait": "Retrato",
    "mapOnly": "MAP_ONLY",
    "a0": "A0",
    "a1": "A1",
    "a2": "A2",
    "a3": "A3",
    "a4": "A4",
    "a5": "A5",
    "letterANSIA": "Letra ANSI A",
    "tabloidANSIB": "Tablóide ANSI B",
    "letter": "Carta",
    "legal": "Aviso Legal",
    "tabloid": "Tablóide",
    "ansi_a": "ANSI A",
    "ansi_b": "ANSI B",
    "ansi_c": "ANSI C",
    "ansi_d": "ANSI D",
    "ansi_e": "ANSI E"
  },
  "snapshot": {
    "snapshot_complete": "Imagem instantânea criada com sucesso.",
    "snapshot_failed": "Ocorreu uma falha ao criar imagem instantânea.",
    "snapshot_append": "Snapshot",
    "utc": "UTC"
  },
  "statisticsChart": {
    "enlarge": "Aumentar",
    "setting": "Definição",
    "count": "Contagem",
    "horizontalAxis": "Eixo horizontal",
    "verticalAxis": "Eixo vertical",
    "dataLabels": "Rótulos de dados",
    "color": "Cor"
  },
  "frameworkDatasource": {
    "setDataSource": "Definir fonte de dados",
    "customDataSource": "Fonte de dados extra",
    "selectCustomDataTip": "Selecione uma fonte de dados desta aplicação.",
    "widgetOutputs": "Saídas de widgets",
    "noExtraDsAvailable": "Não existem fontes de dados extra disponíveis.",
    "addExtraDsTip": "Dirija-se ao separador Atributo do builder e clique em Fonte de dados extra para adicionar dados.",
    "widgetOutpusListTip": "As saídas de widgets (caso existam) são também listadas aqui"
  },
  "gridLayout": {
    "addWidgetTip": "Adicionar widgets aqui através do separador Widget",
    "modifyLayout": "Modificar layout",
    "dragToAdd": "Arrastar para adicionar",
    "mapArea": "ÁREA DO MAPA"
  },
  "noEditPrivileges": "A sua conta não tem permissão para criar ou modificar dados.",
  "invalidConfiguration": "O widget não se encontra configurado ou as camadas da configuração já não se encontram no mapa.  Por favor, abra a aplicação no modo de builder e reconfigure o widget."
});