define({
  root: ({
    instruction: "Select and configure layers that will be shown in Attribute Table initially.",
    label: "Layer",
    show: "Show",
    actions: "Configure layer fields",
    field: "Field",
    alias: "Alias",
    visible: "Visible",
    linkField: "Link field",
    noLayers: "No feature layers are available",
    back: "Back",
    exportCSV: "Allow exporting to CSV",
    expand: "Initially expand the widget",
    filterByExtent: "Enable Filter by map extent by default",
    restore: "Restore to default value",
    ok: "OK",
    cancel: "Cancel",
    includePoint: "Inlcude point coordinates to the exported file",
    configureLayerFields: "Configure Layer Fields",
    result: "Saved successfully",
    warning: "Please select the Show option first.",
    fieldCheckWarning: "At least one field must be selected.",
    unsupportQueryWarning: "The layer needs to support query operation to display in Attribute Table widget. Make sure the query capability in the service is turned on.",
    unsupportQueryLayers: "The following layer needs to support query operation to display in Attribute Table widget. Make sure the query capability in the service is turned on.",

    fieldName: "Name",
    fieldAlias: "Alias",
    fieldVisibility: "Visibility",
    fieldActions: "Actions",
    showAttachments: "Show attachments"
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});