define({
  "id": "مُعرف",
  "state": "افتراضيًا، سيتم عرض الإحداثيات في النظام الإحداثي الحالي للخريطة. للحصول على الإحداثيات في الأنظمة الإحداثية الأخرى، يتعين عليك إضافتها وتحديد عمليات التحويل المناسبة.",
  "outputUnit": "الوحدة الناتجة",
  "wkid": "WKID الناتجة",
  "label": "اسم النظام الإحداثي الناتج",
  "transformationWkid": "تحويل WKID",
  "transformationLabel": "تسمية التحويل",
  "transformForward": "تحويل للأمام",
  "actions": "الأفعال",
  "warning": "الرجاء إدخال الإسناد المكاني الصحيح WKID!",
  "tfWarning": "الرجاء إدخال تحويل سطح الأنساب الصحيح WKID!",
  "spinnerLabel": "تحويل لإحداثيات إلى: ",
  "decimalPlace": "الأماكن العشرية",
  "separator": "إظهار ألف فاصل",
  "getVersionError": "يتعذر الحصول على إصدار خدمة الشكل الهندسي",
  "add": "إضافة النظام الإحداثي الناتج",
  "edit": "تحرير النظام الإحداثي",
  "output": "النظام الإحداثي الناتج",
  "cName": "اسم النظام الإحداثي",
  "units": "عرض الوحدات: ",
  "datum": "تحويل مَرجع الإسناد",
  "tName": "اسم التحويل",
  "tWKIDPlaceHolder": "WKID للتحويل",
  "forward": "استخدام التحويل الأمامي",
  "ok": "موافق",
  "cancel": "إلغاء الأمر",
  "olderVersion": "لا تدعم خدمة الشكل الهندسي عملية التحويل",
  "REPEATING_ERROR": " يوجد النظام الإحداثي في القائمة الناتجة.",
  "Default": "الوضع الافتراضي",
  "Inches": "بوصة",
  "Foot": "قدم",
  "Yards": "ياردات",
  "Miles": "أميال",
  "Nautical_Miles": "أميال بحرية",
  "Millimeters": "ميليمتر",
  "Centimeters": "سنتيمتر",
  "Meter": "مترات",
  "Kilometers": "كيلومترات",
  "Decimeters": "ديسيميتر",
  "Decimal_Degrees": "الدرجات العشرية",
  "Degrees_Decimal_Minutes": "درجات دقائق عشرية",
  "Degree_Minutes_Seconds": "الدرجات بالدقائق والثواني",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "ترتيب عرض الإحداثيات:",
  "lonLatTips": "خطوط الطول / دوائر العرض (X، Y)",
  "latLonTips": "دوائر العرض / خطوط الطول (X، Y)"
});