define({
  "instruction": "Valige ja konfigureerige kihid, mis kuvatakse algselt atribuuditabelis.",
  "label": "Kiht",
  "show": "Näita",
  "actions": "Kihi väljade seadistamine",
  "field": "Väli",
  "alias": "Alias",
  "url": "URL",
  "sortField": "Sortimise väli",
  "sortOrderTooltips": {
    "toDescending": "Vali laskuv järjestus",
    "toAscending": "Vali tõusev järjestus"
  },
  "visible": "Nähtav",
  "linkField": "Lingi väli",
  "noLayers": "Objektikihte pole saadaval",
  "back": "Tagasi",
  "exportCSV": "Luba eksportimine CSV faili",
  "expand": "Laienda vidin alustamisel",
  "filterByExtent": "Luba vaikimisi filtreerimine kaardi ulatuse järgi",
  "allowTextSelection": "Luba teksti valimine",
  "highlightColor": "Esiletõstmise värv",
  "restore": "Taasta vaikeväärtus",
  "ok": "OK",
  "cancel": "Tühista",
  "includePoint": "Kaasa punkti koordinaadid eksporditavasse faili",
  "configureLayerFields": "Kihi väljade seadistamine",
  "result": "Salvestamine õnnestus",
  "warning": "Palun valige esimesena suvand Kuva.",
  "fieldCheckWarning": "Valitud peab olema vähemalt üks väli.",
  "unsupportQueryWarning": "Kiht peab toetama päringut, et seda kuvataks atribuuditabeli vidinas. Veenduge, et päringufunktsioon oleks teenuses sisse lülitatud.",
  "unsupportQueryLayers": "Kiht peab toetama päringut, et seda kuvataks atribuuditabeli vidinas. Veenduge, et päringu tegemise võimekus oleks teenuses sisse lülitatud.",
  "fieldName": "Nimi",
  "fieldAlias": "Alias",
  "fieldVisibility": "Nähtavus",
  "fieldActions": "Tegevused",
  "showAttachments": "Kuva manused"
});