define({
  "_widgetLabel": "Coordinata",
  "hintMessage": "Fare clic sulla mappa per ottenere le coordinate",
  "defaultLabel": "Impostazione predefinita",
  "realtimeLabel": "Spostare il mouse per ottenere le coordinate",
  "computing": "Calcolo in corso...",
  "latitudeLabel": "Latitudine",
  "longitudeLabel": "Longitudine",
  "loading": "caricamento in corso...",
  "enableClick": "Fare clic per abilitare la generazione delle coordinate mediante il clic sulla mappa",
  "disableClick": "Fare clic per disabilitare la generazione delle coordinate mediante il clic sulla mappa",
  "Default": "Impostazione predefinita",
  "Inches": "Pollici",
  "Foot": "Piedi",
  "Yards": "Iarde",
  "Miles": "Miglia",
  "Nautical_Miles": "Miglia nautiche",
  "Millimeters": "Millimetri",
  "Centimeters": "Centimetri",
  "Meter": "Metri",
  "Kilometers": "Chilometri",
  "Decimeters": "Decimetri",
  "Decimal_Degrees": "Gradi",
  "Degree_Minutes_Seconds": "Gradi minuti secondi",
  "MGRS": "MGRS",
  "USNG": "USNG"
});