define({
  "instruction": "Velkomstbildet vises før programmet er tilgjengelig.",
  "defaultContent": "Legg til tekst, koblinger og små grafikkelementer her.",
  "requireConfirm": "Krev bekreftelse for å fortsette",
  "noRequireConfirm": "Ikke krev bekreftelse for å fortsette",
  "optionText": "Alternativ som lar brukeren deaktivere velkomstbildet ved oppstart av applikasjon.",
  "confirmLabel": "Bekreftelsestekst: ",
  "confirmLabelColor": "Tekstfarge for bekreftelse",
  "defaultConfirmText": "Jeg godtar vilkårene og betingelsene ovenfor",
  "confirmOption": "Vis alltid dette velkomstbildet hver gang appen startes",
  "backgroundColor": "Bakgrunnsfarge",
  "content": "Innhold",
  "contentDescription": "Definer innholdet som skal vises i velkomstbildet.",
  "appearance": "Utseende",
  "appearanceDescription": "Angi utseende for velkomstbildet.",
  "size": "Størrelse",
  "width": "Bredde",
  "height": "Høyde",
  "custom": "Tilpasset",
  "background": "Bakgrunn",
  "colorFill": "Fargefyll",
  "imageFill": "Bildefyll",
  "chooseFile": "Velg fil",
  "noFileChosen": "Ingen fil er valgt",
  "transparency": "Gjennomsiktighet",
  "sizeFill": "Fyll",
  "sizeFit": "Tilpass",
  "sizeStretch": "Strekk for å fylle",
  "sizeCenter": "Senter",
  "sizeTile": "Flis",
  "buttonColor": "Farge for knapp",
  "buttonText": "Knappetekst",
  "buttonTextColor": "Tekstfarge for knapp",
  "contentAlign": "Innholdsjustering",
  "alignTop": "Topp",
  "alignMiddle": "Midten",
  "maskColor": "Maskefarge",
  "options": "Alternativer",
  "optionsDescription": "Angi virkemåte for velkomstbildet."
});