define({
  "id": "ID",
  "state": "Ve výchozím nastavení se souřadnice zobrazí v souřadnicovém systému aktuální mapy. Chcete-li souřadnice zobrazovat v jiných souřadnicových systémech, je nutné je nastavit spolu s příslušnými transformacemi.",
  "outputUnit": "Výstupní jednotka",
  "wkid": "Výstupní WKID",
  "label": "Název výstupního souřadnicového systému",
  "transformationWkid": "WKID transformace",
  "transformationLabel": "Popisek transformace",
  "transformForward": "Transformovat blíž",
  "actions": "Akce",
  "warning": "Zadejte platné WKID souřadnicového systému!",
  "tfWarning": "Zadejte platné WKID transformace souřadnic!",
  "spinnerLabel": "Zaokrouhlit souřadnice na: ",
  "decimalPlace": "desetinných míst",
  "separator": "Zobrazit oddělovače tisíců",
  "getVersionError": "Nelze získat verzi geometrické služby.",
  "add": "Přidat výstupní souřadnicový systém",
  "edit": "Upravit souřadnicový systém",
  "output": "Výstupní souřadnicový systém",
  "cName": "Název souřadnicového systému",
  "units": "Jednotky zobrazení: ",
  "datum": "Transformace geodetického data",
  "tName": "Název transformace",
  "tWKIDPlaceHolder": "WKID transformace",
  "forward": "Použít transformaci blíž",
  "ok": "OK",
  "cancel": "Storno",
  "olderVersion": "Geometrická služba nepodporuje transformace.",
  "REPEATING_ERROR": " Souřadnicový systém existuje ve výstupním seznamu.",
  "Default": "Výchozí",
  "Inches": "Palce",
  "Foot": "Stopy",
  "Yards": "Yardy",
  "Miles": "Míle",
  "Nautical_Miles": "Námořní míle",
  "Millimeters": "Milimetry",
  "Centimeters": "Centimetry",
  "Meter": "Metry",
  "Kilometers": "Kilometry",
  "Decimeters": "Decimetry",
  "Decimal_Degrees": "Desetinné stupně",
  "Degrees_Decimal_Minutes": "Stupně a desetinné minuty",
  "Degree_Minutes_Seconds": "Stupně minuty vteřiny",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Pořadí zobrazení souřadnic:",
  "lonLatTips": "Zeměpisná délka / zeměpisná šířka (X, Y)",
  "latLonTips": "Zeměpisná šířka / zeměpisná délka (Y, X)"
});