define({
  "_widgetLabel": "图层列表",
  "titleBasemap": "底图",
  "titleLayers": "业务图层",
  "labelLayer": "图层名称",
  "itemZoomTo": "缩放至",
  "itemTransparency": "透明度",
  "itemTransparent": "透明",
  "itemOpaque": "不透明",
  "itemMoveUp": "上移",
  "itemMoveDown": "下移",
  "itemDesc": "描述",
  "itemDownload": "下载",
  "itemToAttributeTable": "在属性表中查看",
  "itemShowItemDetails": "显示项目详细信息",
  "empty": "空",
  "removePopup": "禁用弹出窗口",
  "enablePopup": "启用弹出窗口",
  "turnAllLayersOff": "关闭所有图层",
  "turnAllLayersOn": "打开所有图层",
  "expandAllLayers": "展开所有图层",
  "collapseAlllayers": "折叠所有图层",
  "turnAllLabelsOff": "关闭所有标注",
  "turnAllLabelsOn": "打开所有标注",
  "showLabels": "显示标注",
  "hideLables": "隐藏标注"
});