define(
   ({
    _widgetLabel: "Atribuuditabel",
    ok: "OK",
    cancel: "Tühista",
    unsupportQueryWarning: "Kiht peab toetama päringut, et seda kuvataks atribuuditabeli vidinas. Veenduge, et päringufunktsioon oleks teenuses sisse lülitatud.",
    exportMessage: "Kas soovite eksportida andmed CSV faili?",
    exportFiles: "Ekspordi CSV faili",
    exportSelected: "Ekspordi valitud osa CSV formaati",
    exportAll: "Ekspordi kõik CSV formaati",
    options: "Valikud",
    zoomto: "Suumi",
    highlight: "Tõsta graafika esile",
    selectAll: "Vali kõigi lehtede kirjed",
    selectPage: "Vali praeguse lehe kirjed",
    clearSelection: "Tühista valik",
    filter: "Filter",
    setFilterTip: "Määrake filter õigesti.",
    noFilterTip: "Määratlemata filtriavaldiseta loendab see päringuülesanne kõik määratud andmeallika funktsioonid.",
    filterByExtent: "Filtreeri kaardi ulatuse järgi",
    showSelectedRecords: "Kuva valitud kirjed",
    showAllRecords: "Näita kõiki kirjeid",
    showRelatedRecords: "Kuva seotud kirjed",
    noRelatedRecords: "Seotud kirjeid pole",
    refresh: "Värskenda",
    features: "objektid",
    selected: "valitud",
    transparent: "Läbipaistvuse režiim",
    indicate: "Paiguta valitu",
    columns: "Näita/Peida veerud",
    selectionSymbol: "Valiku sümbol",
    closeMessage: "Peida tabel (laienda seda uuesti altpoolt)",
    dataNotAvailable: "Andmed ei ole saadaval!<br>Uuesti proovimiseks klikkige nuppu [Värskenda]",
    openTableTip: "Ava atribuutide tabel",
    closeTableTip: "Peida atribuutide tabel"
  })
);