define({
  "instruction": "응용프로그램이 접근할 수 있기 전에 시작 화면이 표시됩니다.",
  "defaultContent": "텍스트, 링크 및 작은 그래픽을 여기에 추가합니다.",
  "requireConfirm": "계속하려면 확인 필요",
  "noRequireConfirm": "계속할지 확인하지 않음",
  "optionText": "사용자가 응용프로그램 시작 시 스플래시 화면을 비활성화할 수 있는 옵션입니다.",
  "confirmLabel": "확인 텍스트: ",
  "confirmLabelColor": "확인 텍스트 색상",
  "defaultConfirmText": "위 사용 약관에 동의합니다.",
  "confirmOption": "앱을 실행할 때마다 항상 이 스플래시 화면 보기",
  "backgroundColor": "배경 색상",
  "content": "콘텐츠",
  "contentDescription": "스플래시 페이지에 나타나는 콘텐츠를 정의합니다.",
  "appearance": "모양",
  "appearanceDescription": "스플래시 페이지의 모양을 설정합니다.",
  "size": "크기",
  "width": "너비",
  "height": "높이",
  "custom": "사용자 정의",
  "background": "배경",
  "colorFill": "색상 채우기",
  "imageFill": "이미지 채우기",
  "chooseFile": "파일 선택",
  "noFileChosen": "선택한 파일 없음",
  "transparency": "투명도",
  "sizeFill": "채우기",
  "sizeFit": "맞춤",
  "sizeStretch": "채우기로 스트레치",
  "sizeCenter": "가운데",
  "sizeTile": "타일",
  "buttonColor": "버튼 색상",
  "buttonText": "버튼 텍스트",
  "buttonTextColor": "버튼 텍스트 색상",
  "contentAlign": "콘텐츠 정렬",
  "alignTop": "위쪽",
  "alignMiddle": "가운데",
  "maskColor": "마스크 색상",
  "options": "옵션",
  "optionsDescription": "스플래시 페이지의 동작을 설정합니다."
});