define({
  "_widgetLabel": "Liste des couches",
  "titleBasemap": "Fonds de carte",
  "titleLayers": "Couches opérationnelles",
  "labelLayer": "Nom de la couche",
  "itemZoomTo": "Zoom",
  "itemTransparency": "Transparence",
  "itemTransparent": "Transparent",
  "itemOpaque": "Opaque",
  "itemMoveUp": "Monter",
  "itemMoveDown": "Descendre",
  "itemDesc": "Description",
  "itemDownload": "Télécharger",
  "itemToAttributeTable": "Afficher dans la table attributaire",
  "itemShowItemDetails": "Afficher les détails des éléments",
  "empty": "vide",
  "removePopup": "Désactiver la fenêtre contextuelle",
  "enablePopup": "Activer la fenêtre contextuelle",
  "turnAllLayersOff": "Désactiver toutes les couches",
  "turnAllLayersOn": "Activer toutes les couches",
  "expandAllLayers": "Développer toutes les couches",
  "collapseAlllayers": "Réduire toutes les couches",
  "turnAllLabelsOff": "Désactiver toutes les étiquettes",
  "turnAllLabelsOn": "Activer toutes les étiquettes",
  "showLabels": "Afficher les étiquettes",
  "hideLables": "Masquer les étiquettes"
});