define({
  "instruction": "Selectaţi şi configuraţi straturi tematice care vor fi afişate iniţial în Tabelul de atribute.",
  "label": "Strat tematic",
  "show": "Afişare",
  "actions": "Configurare câmpuri strat tematic",
  "field": "Câmp",
  "alias": "Pseudonim",
  "visible": "Vizibil",
  "linkField": "Câmp link",
  "noLayers": "Nu este disponibil niciun strat tematic de obiecte spaţiale",
  "back": "Înapoi",
  "exportCSV": "Permiteţi exportul în CSV",
  "expand": "Extindere iniţială widget",
  "filterByExtent": "Activare implicită pentru filtrare după extinderea hărţii",
  "restore": "Restabilire valoare implicită",
  "ok": "OK",
  "cancel": "Anulare",
  "includePoint": "Includere coordonate punct în fişierul exportat",
  "configureLayerFields": "Configurare câmpuri strat tematic",
  "result": "Salvare reuşită",
  "warning": "Selectaţi mai întâi Afişare opţiune.",
  "fieldCheckWarning": "Trebuie selectat cel puţin un câmp.",
  "unsupportQueryWarning": "Stratul tematic trebuie să suporte operarea de interogări pentru a fi afişat în widgetul Tabel atribute. Asiguraţi-vă că capacitatea de interogare din serviciu este activată.",
  "unsupportQueryLayers": "Stratul tematic următor trebuie să suporte operarea de interogări pentru a fi afişat în widgetul Tabel atribute. Asiguraţi-vă că capacitatea de interogare din serviciu este activată.",
  "fieldName": "Nume",
  "fieldAlias": "Pseudonim",
  "fieldVisibility": "Vizibilitate",
  "fieldActions": "Acţiuni",
  "showAttachments": "Afişarea ataşărilor"
});