define({
  "instruction": "Sélectionnez et configurez les couches qui apparaîtront dès le début dans la table attributaire.",
  "label": "Couche",
  "show": "Afficher",
  "actions": "Configurer les champs de couche",
  "field": "Champ",
  "alias": "Alias",
  "visible": "Visible",
  "linkField": "Hyperlien",
  "noLayers": "Aucune couche d'entités disponible",
  "back": "Retour",
  "exportCSV": "Autoriser l'export au format CSV",
  "expand": "Ouvert au démarrage",
  "filterByExtent": "Activer Filtrer selon l’étendue de la carte par défaut",
  "restore": "Rétablir la valeur par défaut",
  "ok": "OK",
  "cancel": "Annuler",
  "includePoint": "Inclure les coordonnées des points dans le fichier exporté",
  "configureLayerFields": "Configurer les champs de couche",
  "result": "Enregistrement réussi",
  "warning": "Sélectionnez d'abord l'option Afficher.",
  "fieldCheckWarning": "Au moins un champ doit être sélectionné.",
  "unsupportQueryWarning": "La couche doit prendre en charge l’opération de requête pour s’afficher dans le widget Table attributaire. Vérifiez que la fonction de requête dans le service est activée.",
  "unsupportQueryLayers": "La couche suivante doit prendre en charge l'opération de requête pour s'afficher dans le widget Table attributaire. Vérifiez que la fonction de requête dans le service est activée.",
  "fieldName": "Nom",
  "fieldAlias": "Alias",
  "fieldVisibility": "Visibilité",
  "fieldActions": "Actions",
  "showAttachments": "Afficher les pièces jointes"
});