define({
  "_widgetLabel": "Koordinate",
  "hintMessage": "Za pridobitev koordinat kliknite karto",
  "defaultLabel": "Privzeto",
  "realtimeLabel": "Za pridobitev koordinat premaknite miško",
  "computing": "Računam...",
  "latitudeLabel": "Geografska širina",
  "longitudeLabel": "Geografska dolžina",
  "loading": "nalaganje...",
  "enableClick": "Kliknite, da omogočite klikanje zemljevida za pridobivanje koordinat",
  "disableClick": "Kliknite, da onemogočite klikanje zemljevida za pridobivanje koordinat",
  "Default": "Privzeto",
  "Inches": "Palci",
  "Foot": "Čevlji",
  "Yards": "Jardi",
  "Miles": "Milje",
  "Nautical_Miles": "Morske milje",
  "Millimeters": "Milimetri",
  "Centimeters": "Centimetri",
  "Meter": "Metri",
  "Kilometers": "Kilometri",
  "Decimeters": "Decimetri",
  "Decimal_Degrees": "Stopinje",
  "Degree_Minutes_Seconds": "Stopinj minut sekund",
  "MGRS": "MGRS",
  "USNG": "USNG"
});