define({
  "instruction": "Välj och konfigurera lager som kommer att visas först i attributtabellen.",
  "label": "Lager",
  "show": "Visa",
  "actions": "Konfigurera lagerfält",
  "field": "Fält",
  "alias": "Alias",
  "visible": "Synlig",
  "linkField": "Länkfält",
  "noLayers": "Inga geoobjektslager är tillgängliga",
  "back": "Bakåt",
  "exportCSV": "Tillåt export till CSV",
  "expand": "Börja med att expandera widgeten",
  "filterByExtent": "Aktivera filter enligt kartutbredning som standard",
  "restore": "Återställ till standardvärde",
  "ok": "OK",
  "cancel": "Avbryt",
  "includePoint": "Ta med punktkoordinater i den exporterade filen",
  "configureLayerFields": "Konfigurera lagerfält",
  "result": "Sparad",
  "warning": "Välj alternativet Visa först.",
  "fieldCheckWarning": "Minst ett fält måste väljas.",
  "unsupportQueryWarning": "Lagret måste ha stöd för frågeåtgärden för att visas i widgeten Attributtabell. Kontrollera att frågefunktionen i tjänsten är påslagen.",
  "unsupportQueryLayers": "Följande lager måste stödja frågeåtgärden om det ska gå att visa i widgeten Attributtabell. Kontrollera att frågefunktionen är aktiverad i tjänsten.",
  "fieldName": "Namn",
  "fieldAlias": "Alias",
  "fieldVisibility": "Synlighet",
  "fieldActions": "Åtgärder",
  "showAttachments": "Visa bifogade filer"
});