define({
  "instruction": "Başlangıçta Öznitelik Tablosunda gösterilecek katmanları seçin ve yapılandırın.",
  "label": "Katman",
  "show": "Göster",
  "actions": "Katman alanlarını yapılandır",
  "field": "Alan",
  "alias": "Takma Ad",
  "visible": "Görünür",
  "linkField": "Alan bağlantısı yap",
  "noLayers": "Detay katmanı mevcut değil",
  "back": "Geri",
  "exportCSV": "CSV'ye Aktarmaya İzin Ver",
  "expand": "İlk olarak gereci genişlet",
  "filterByExtent": "Harita yayılımına göre filtrele özelliğini varsayılan olarak etkinleştir",
  "restore": "Varsayılan değere geri yükle",
  "ok": "Tamam",
  "cancel": "İptal",
  "includePoint": "Nokta koordinatlarını dışa aktarılan dosyaya ekle",
  "configureLayerFields": "Katman Alanlarını Yapılandır",
  "result": "Başarıyla kaydedildi",
  "warning": "Göster seçeneğini önce seçin.",
  "fieldCheckWarning": "En az bir alan seçilmelidir.",
  "unsupportQueryWarning": "Öznitelik Tablosu aracını görüntülemek için katmanın sorgu işlemini desteklemesi gerekir. Servisteki sorgu yeteneğinin açık olduğundan emin olun.",
  "unsupportQueryLayers": "Öznitelik Tablosu aracını görüntülemek için aşağıdaki katmanın sorgu işlemini desteklemesi gerekir. Hizmetteki sorgu özelliğinin açık olduğundan emin olun.",
  "fieldName": "Ad",
  "fieldAlias": "Takma Ad",
  "fieldVisibility": "Görünürlük",
  "fieldActions": "İşlemler",
  "showAttachments": "Ekleri göster"
});