define({
  "id": "Id.",
  "state": "De forma predeterminada, las coordenadas se mostrarán en el sistema de coordenadas del mapa actual. Para obtener coordenadas en otros sistemas de coordenadas, debes agregarlas y especificar las transformaciones apropiadas.",
  "outputUnit": "Unidad de salida",
  "wkid": "WKID de salida",
  "label": "Nombre del sistema de coordenadas de salida",
  "transformationWkid": "WKID de transformación",
  "transformationLabel": "Etiqueta de transformación",
  "transformForward": "Transformar adelante",
  "actions": "Acciones",
  "warning": "Introduce un WKID de referencia espacial válido",
  "tfWarning": "Introduce un WKID de transformación de datum válido",
  "spinnerLabel": "Redondear coordenadas a: ",
  "decimalPlace": "posiciones decimales",
  "separator": "Mostrar separadores de miles",
  "getVersionError": "No se puede obtener la versión del servicio de geometría",
  "add": "Agregar sistema de coordenadas de salida",
  "edit": "Editar sistema de coordenadas",
  "output": "Sistema de coordenadas de salida",
  "cName": "Nombre del sistema de coordenadas",
  "units": "Mostrar unidades: ",
  "datum": "Transformación de datum",
  "tName": "Nombre de transformación",
  "tWKIDPlaceHolder": "WKID de la transformación",
  "forward": "Usar transformación adelante",
  "ok": "Aceptar",
  "cancel": "Cancelar",
  "olderVersion": "El servicio de geometría no admite la operación de transformación",
  "REPEATING_ERROR": " El sistema de coordenadas existe en la lista de salida.",
  "Default": "Predeterminado",
  "Inches": "Pulgadas",
  "Foot": "Pies",
  "Yards": "Yardas",
  "Miles": "Millas",
  "Nautical_Miles": "Millas náuticas",
  "Millimeters": "Milímetros",
  "Centimeters": "Centímetros",
  "Meter": "Metros",
  "Kilometers": "Kilómetros",
  "Decimeters": "Decímetros",
  "Decimal_Degrees": "Grados decimales",
  "Degrees_Decimal_Minutes": "Grados Minutos decimales",
  "Degree_Minutes_Seconds": "Grados minutos segundos",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Orden de visualización de coordenadas:",
  "lonLatTips": "Longitud / Latitud (X, Y)",
  "latLonTips": "Latitud / Longitud (Y, X)"
});