define({
  "id": "ID",
  "state": "Par défaut, les coordonnées s'affichent dans le système de coordonnées de la carte actuelle. Pour obtenir des coordonnées dans d'autres systèmes de coordonnées, vous devez les ajouter et indiquer les transformations appropriées.",
  "outputUnit": "Unité de sortie",
  "wkid": "WKID en sortie",
  "label": "Nom du système de coordonnées en sortie",
  "transformationWkid": "WKID de transformation",
  "transformationLabel": "Etiquette de transformation",
  "transformForward": "Transformation avant",
  "actions": "Actions",
  "warning": "Entrez un WKID de référence spatiale valide !",
  "tfWarning": "Entrez un WKID de transformation de datum valide !",
  "spinnerLabel": "Arrondir les coordonnées à : ",
  "decimalPlace": "Décimales",
  "separator": "Afficher les séparateurs de milliers",
  "getVersionError": "Impossible d'obtenir la version du service de géométrie",
  "add": "Ajouter un système de coordonnées en sortie",
  "edit": "Modifier le système de coordonnées",
  "output": "Système de coordonnées en sortie",
  "cName": "Nom du système de coordonnées",
  "units": "Afficher l'unité : ",
  "datum": "Transformation de datum",
  "tName": "Nom de la transformation",
  "tWKIDPlaceHolder": "WKID de la transformation",
  "forward": "Utiliser la transformation avant",
  "ok": "OK",
  "cancel": "Annuler",
  "olderVersion": "Le service de géométrie ne prend pas en charge l'opération de transformation",
  "REPEATING_ERROR": " Le système de coordonnées figure dans la liste en sortie.",
  "Default": "Par défaut",
  "Inches": "Pouces",
  "Foot": "Pieds",
  "Yards": "Yards",
  "Miles": "Miles",
  "Nautical_Miles": "Milles marins",
  "Millimeters": "Millimètres",
  "Centimeters": "Centimètres",
  "Meter": "Mètres",
  "Kilometers": "Kilomètres",
  "Decimeters": "Décimètres",
  "Decimal_Degrees": "Degrés décimaux",
  "Degrees_Decimal_Minutes": "Degrés minutes décimales",
  "Degree_Minutes_Seconds": "Degrés minutes secondes",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Ordre d'affichage des coordonnées :",
  "lonLatTips": "Longitude / Latitude(X, Y)",
  "latLonTips": "Latitude / Longitude(Y, X)"
});