define({
  root: ({
    instruction: "The splash screen appears before the application is accessible.",
    defaultContent: "Add text, links, and small graphics here.",
    requireConfirm: "Require confirmation to continue",
    noRequireConfirm: "Do not require confirmation to continue",
    optionText: "Option for user to disable splash screen on application startup.",
    confirmLabel: "Confirmation Texts: ",
    confirmLabelColor: "Confirmation texts color",
    defaultConfirmText: "I agree to the above terms and conditions",
    confirmOption: "Always show this splash screen every time the app launches",
    backgroundColor: "Background Color",
    content: "Content",
    contentDescription: "Define the content that displays on the splash screen.",
    appearance: "Appearance",
    appearanceDescription: "Set the appearance of the splash screen.",
    size: "Size",
    width: "Width",
    height: "Height",
    custom: "Custom",
    background: "Background",
    colorFill: "Color fill",
    imageFill: "Image fill",
    chooseFile: "Choose file",
    noFileChosen: "No file chosen",
    transparency: "Transparency",
    sizeFill: "Fill",
    sizeFit: "Fit",
    sizeStretch: "Stretch to fill",
    sizeCenter: "Center",
    sizeTile: "Tile",
    buttonColor: "Button color",
    buttonText: "Button text",
    buttonTextColor: "Button text color",
    contentAlign:"Content alignment",
    alignTop:"Top",
    alignMiddle:"Middle",
    maskColor: "Mask color",
    options: "Options",
    optionsDescription: "Set the behavior of the splash screen."
  }),
  "ar": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});