define({
  root: ({
    instruction: "Define the content that displays on the splash screen of your application. The splash screen appears before the application loads. ",
    defaultContent: "Add text, links, and small graphics here.",
    requireConfirm: "Require confirmation to continue",
    noRequireConfirm: "Do not require confirmation to continue",
    optionText: "Provide the option to show the splash screen again or not",
    confirmLabel: "Confirmation Texts: ",
    defaultConfirmText: "I agree to the above terms and conditions",
    confirmOption: "Always show this splash screen every time the app launches",
    backgroundColor: "Background Color"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});