define(
   ({
    "sourceSetting": "Hakulähteen asetukset",
    "instruction": "Lisää ja määritä geokoodauspalveluja tai kohdekarttatasoja haun lähteiksi. Nämä määritetyt lähteet määrittävät, mitä hakuruudussa voi hakea.",
    "add": "Lisää haun lähde",
    "addGeocoder": "Lisää geokooderi",
    "geocoder": "Geokooderi",
    "setLayerSource": "Määritä karttatason lähde",
    "setGeocoderURL": "Määritä geokooderin URL-osoite",
    "searchableLayer": "Kohdekarttataso",
    "name": "Nimi",
    "countryCode": "Maa- tai aluekoodit",
    "countryCodeEg": "esim. ",
    "countryCodeHint": "Jos jätät tämän arvon tyhjäksi, ohjelma etsii kaikista maista ja kaikilta alueilta",
    "generalSetting": "Yleiset asetukset",
    "allPlaceholder": "Paikkamerkkiteksti haulle kaikkialta: ",
    "showInfoWindowOnSelect": "Näytä löydetyn kohteen tai sijainnin ponnahdusikkuna",
    "searchInCurrentMapExtent": "Etsi vain nykyisestä karttalaajuudesta",
    "locatorUrl": "Geokooderin URL-osoite",
    "locatorName": "Geokooderin nimi",
    "locatorExample": "Esimerkki",
    "locatorWarning": "Tätä geokoodauspalvelun versiota ei tueta. Pienoisohjelma tukee geokoodauspalvelua 00.0 ja sitä uudempia versioita.",
    "locatorTips": "Ehdotukset eivät ole käytettävissä, koska geokoodauspalvelu ei tue ehdotustoimintoa.",
    "layerSource": "Karttatason lähde",
    "searchLayerTips": "Ehdotukset eivät ole käytettävissä, koska kohdepalvelu ei tue sivutustoimintoa.",
    "placeholder": "Muuttujan teksti",
    "searchFields": "Hakukentät",
    "displayField": "Näyttökenttä",
    "exactMatch": "Tarkka vastine",
    "maxResults": "Tulosten enimmäismäärä",
    "setSearchFields": "Määritä hakukentät",
    "set": "Aseta",
    "fieldSearchable": "haettavissa oleva",
    "fieldName": "Nimi",
    "fieldAlias": "Alias",
    "ok": "OK",
    "cancel": "Peruuta",
    "invalidUrlTip": "Syötetty URL on virheellinen, tai se ei ole käytettävissä."
  })
);