define({
  "common": {
    "apply": "ใช้",
    "ok": "ตกลง",
    "cancel": "ยกเลิก",
    "yes": "ใช่",
    "no": "ไม่",
    "next": "ถัดไป",
    "previous": "ก่อนหน้า",
    "back": "กลับ",
    "selected": "เลือก",
    "name": "ชื่อ",
    "usage": "การใช้งาน",
    "settings": "การตั้งค่า",
    "home": "หน้าหลัก",
    "link": "ลิงค์",
    "messages": "ข้อความ",
    "outputs": "ผลลัพธ์",
    "title": "ชื่อ",
    "thumbnail": "รูปย่อ",
    "url": "URL",
    "actions": "กระทำ",
    "layer": "ชั้นข้อมูล",
    "action": "ปฏิบัติ",
    "input": "ข้อมูลนำเข้า",
    "output": "ผลลัพธ์",
    "type": "ชนิด",
    "required": "ต้องการ",
    "options": "ตัวเลือก",
    "label": "ตัวอักษร",
    "tooltip": "คำแนะนำการใช้เครื่องมือ",
    "visible": "มองเห็น",
    "symbol": "สัญลักษณ์",
    "popup": "ป๊อปอัพ",
    "upload": "อัพโหลด",
    "execute": "ปฏิบัติ",
    "help": "ช่วยเหลือ",
    "executing": "กำลังดำเนินการ",
    "clear": "ลบ",
    "error": "ข้อผิดพลาด",
    "zoomTo": "ขยายไปยัง",
    "attribute": "เชิงบรรยาย",
    "exports": "ส่งออก",
    "check": "ตรวจสอบ",
    "save": "บันทึก",
    "close": "ปิด",
    "deleteText": "ลบ",
    "map": "แผนที่",
    "scene": "ซีน",
    "reset": "รีเซต",
    "icon": "ไอค่อน",
    "folder": "โฟลเดอร์",
    "share": "แบ่งปัน",
    "view": "วิว",
    "newText": "ใหม่",
    "edit": "แก้ไข",
    "wkid": "WKID",
    "table": "ตาราง",
    "zoomIn": "ขยายภาพ",
    "zoomOut": "ย่อภาพ",
    "continue1": "ต่อไป",
    "longitude": "ลองจิจูด",
    "latitude": "ละติจูด",
    "custom": "แก้ไขเอง",
    "image": "รูปภาพ",
    "font": "รูปแบบตัวอักษร",
    "text": "ข้อความ",
    "all": "ทั้งหมด",
    "number": "จำนวน",
    "percentage": "ร้อยละ",
    "unit": "หน่วย",
    "thousand": "หลักพัน",
    "billion": "พันล้าน",
    "million": "หลักล้าน",
    "none": "ไม่มีเลย",
    "field": "คอลัมน์",
    "operation": "ปฏิบัติการ",
    "disableUpdateGeometry": "ไม่สามารถอัพเดทเชิงเรขาคณิตได้",
    "preview": "ตัวอย่าง"
  },
  "errorCode": "รหัส",
  "errorMessage": "ข้อความ",
  "errorDetail": "รายละเอียด",
  "widgetPlaceholderTooltip": "ทำการตั้งค่า ไปยัง widget และคลิกที่ตัวยืดร่วม",
  "fieldStatistics": {
    "selectField": "เลือกฟิลด์",
    "statistics": "สถิติ",
    "field": "ฟิลด์",
    "count": "จำนวนค่า",
    "sum": "ยอดรวมของค่า",
    "min": "น้อยสุด",
    "max": "สูงสุด",
    "ave": "เฉลี่ย",
    "stddev": "ค่าเบี่ยงเบนมาตรฐาน"
  },
  "symbolChooser": {
    "preview": "ภาพตัวอย่าง",
    "basic": "ระดับพื้นฐาน",
    "arrows": "ลูกศร",
    "business": "ธุรกิจ",
    "cartographic": "การทำแผนที่",
    "nationalParkService": "บริการอุทยานแห่งชาติ",
    "outdoorRecreation": "นันทนาการกลางแจ้ง",
    "peoplePlaces": "สถานที่ชุมชน",
    "safetyHealth": "สุขภาพความปลอดภัย",
    "shapes": "รูปร่าง",
    "transportation": "การคมนาคม",
    "symbolSize": "ขนาดสัญลักษณ์",
    "color": "สี",
    "alpha": "อัลฟ้า",
    "outlineColor": "สีโครงร่าง",
    "outlineWidth": "ความกว้างโครงร่าง",
    "style": "สไตล์",
    "width": "ความกว้าง",
    "text": "ข้อความ",
    "fontColor": "สีตัวอักษร",
    "fontSize": "ขนาดตัวอักษร",
    "transparency": "ความโปร่งแสง",
    "solid": "สีเดียว",
    "dash": "-",
    "dot": ".",
    "dashDot": "จุด Dash",
    "dashDotDot": "จุดต่อหน้า Dash",
    "customImage": "ภาพที่กำหนดเอง",
    "chooseFile": "เลือกไฟล์",
    "noFileChoosen": "ไม่มีไฟล์ที่เลือก"
  },
  "transparency": {
    "opaque": "ความทึบแสง",
    "transparent": "ความโปร่งแสง"
  },
  "rendererChooser": {
    "domain": "โดเมน",
    "use": "ใช้",
    "singleSymbol": "เป็นสัญลักษณ์เดียว",
    "uniqueSymbol": "สัญลักษณ์ที่ไม่ซ้ำกัน",
    "color": "สี",
    "size": "ขนาด",
    "toShow": "เพื่อที่จะแสดง",
    "colors": "สี",
    "classes": "ชั้น",
    "symbolSize": "ขนาดสัญลักษณ์",
    "addValue": "เพิ่มค่า",
    "setDefaultSymbol": "ตั้งค่าสัญลักษณ์ตั้งต้น",
    "defaultSymbol": "สัญลักษณ์เริ่มต้น",
    "selectedSymbol": "เลือกสัญลักษณ์",
    "value": "ค่า",
    "label": "ป้ายชื่อ",
    "range": "ลำดับ"
  },
  "drawBox": {
    "point": "จุด",
    "line": "เส้น",
    "polyline": "เส้น",
    "freehandPolyline": "วาดเส้นแบบฟรีแฮนด์",
    "triangle": "สามเหลี่ยม",
    "extent": "ส่วนขยาย",
    "circle": "วงกลม",
    "ellipse": "วงรี",
    "polygon": "รูปปิด",
    "freehandPolygon": "รูปหลายเหลี่ยมที่ลากด้วยมือ",
    "text": "ตัวอักษร",
    "clear": "เคลียร์"
  },
  "popupConfig": {
    "title": "ชื่อ",
    "add": "เพิ่ม",
    "fields": "ฟิลด์",
    "noField": "ไม่มีฟิลด์",
    "visibility": "มองเห็น",
    "name": "ชื่อ",
    "alias": "นามแฝง",
    "actions": "การดำเนินการ"
  },
  "includeButton": {
    "include": "รวมเข้ากับ"
  },
  "loadingShelter": {
    "loading": "กำลังโหลด"
  },
  "basicServiceBrowser": {
    "noServicesFound": "ไม่พบเซอร์วิส",
    "unableConnectTo": "ไม่สามารถเชื่อมต่อไปยัง",
    "invalidUrlTip": "URL ที่คุณป้อนไม่ถูกต้องหรือไม่สามารถเข้าถึง"
  },
  "serviceBrowser": {
    "noGpFound": "ไม่พบจีโอโพรเซสซิ่งเซอร์วิส",
    "unableConnectTo": "ไม่สามารถเชื่อมต่อไปยัง"
  },
  "layerServiceBrowser": {
    "noServicesFound": "ไม่พบแมพเซอร์วิสหรือฟีเจอร์เซอร์วิส",
    "unableConnectTo": "ไม่สามารถเชื่อมต่อไปยัง"
  },
  "basicServiceChooser": {
    "validate": "ตรวจสอบ",
    "example": "ตัวอย่าง",
    "set": "ตั้งค่า"
  },
  "urlInput": {
    "invalidUrl": "Url ไม่ถูกต้อง"
  },
  "urlComboBox": {
    "invalidUrl": "Url ไม่ถูกต้อง"
  },
  "filterBuilder": {
    "addAnotherExpression": "เพิ่มเงื่อนไข",
    "addSet": "เพิ่มเซ็ต",
    "matchMsg": "แสดงฟีเจอร์ที่ในชั้นข้อมูลที่ตรงกัน ${any_or_all}ตามสูตรคำนวณต่อไปนี้",
    "matchMsgSet": "${any_or_all} ตามสูตรคำนวณนี้จะทำให้การตั้งค่าเป็นจริง",
    "all": "ทั้งหมด",
    "any": "ใดๆ",
    "value": "ค่า",
    "field": "ฟิลด์",
    "unique": "เอกลักษณ์",
    "none": "ไม่มีเลย",
    "and": "และ",
    "valueTooltip": "เพิ่มค่า",
    "fieldTooltip": "เลือกจากฟิลด์ที่มีอยู่",
    "uniqueValueTooltip": "เลือกจากค่าที่ไม่ซ้ำในฟิลด์ที่เลือก",
    "stringOperatorIs": "เป็น",
    "stringOperatorIsNot": "ไม่เป็น",
    "stringOperatorStartsWith": "เริ่มด้วย",
    "stringOperatorEndsWith": "จบด้วย",
    "stringOperatorContains": "รวมด้วย",
    "stringOperatorDoesNotContain": "ไม่รวมด้วย",
    "stringOperatorIsBlank": "ว่าง",
    "stringOperatorIsNotBlank": "ไม่ว่าง",
    "dateOperatorIsOn": "ที่อยู่บน",
    "dateOperatorIsNotOn": "ที่ไม่อยู่บน",
    "dateOperatorIsBefore": "แต่ก่อน",
    "dateOperatorIsAfter": "ที่หลัง",
    "dateOperatorIsOnOrBefore": "อยู่บนหรือก่อน",
    "dateOperatorIsOnOrAfter": "อยู่บนหรือหลัง",
    "dateOperatorMinutes": "นาที",
    "dateOperatorHours": "ชั่วโมง",
    "dateOperatorDays": "วัน",
    "dateOperatorWeeks": "สัปดาห์",
    "dateOperatorMonths": "เดือน",
    "dateOperatorYears": "ปี",
    "dateOperatorInTheLast": "ในที่สุด",
    "dateOperatorNotInTheLast": "ไม่ที่สุด",
    "dateOperatorIsBetween": "ระหว่าง",
    "dateOperatorIsNotBetween": "ไม่ระหว่าง",
    "dateOperatorIsBlank": "ว่าง",
    "dateOperatorIsNotBlank": "ไม่ว่าง",
    "numberOperatorIs": "เป็น",
    "numberOperatorIsNot": "ไม่เป็น",
    "numberOperatorIsAtLeast": "อย่างน้อย",
    "numberOperatorIsLessThan": "น้อยกว่า",
    "numberOperatorIsAtMost": "มาก",
    "numberOperatorIsGreaterThan": "มากกว่า",
    "numberOperatorIsBetween": "ระหว่าง",
    "numberOperatorIsNotBetween": "ไม่ระหว่าง",
    "numberOperatorIsBlank": "ว่าง",
    "numberOperatorIsNotBlank": "ไม่ว่าง",
    "string": "ตัวหนังสือ",
    "number": "จำนวน",
    "date": "วันที่",
    "askForValues": "สอบถามค่า",
    "prompt": "รวดเร็ว",
    "hint": "เปรียบเปรย",
    "error": {
      "invalidParams": "พารามิเตอร์ไม่ถูกต้อง",
      "invalidUrl": "Url ไม่ถูกต้อง",
      "noFilterFields": "ชั้นข้อมูลไม่มีฟิลด์ที่สามารถใช้สำหรับการสร้างตัวกรองข้อมูล",
      "invalidSQL": "สูตรคำนวณ SQL ไม่ถูกต้อง",
      "cantParseSQL": "ไม่สามารถแยกสูตรคำนวณ SQL ได้"
    },
    "caseSensitive": "กรณีไวต่อตัวอักษรพิมพ์เล็กและพิมพ์ใหญ่",
    "notSupportCaseSensitiveTip": "บริการโฮสต์ข้อมูลไม่สนับสนุนการสอบถามเป็นกรณี ๆ",
    "setFilterTip": "โปรดตั้งค่าตัวกรองให้ถูกต้อง",
    "listValues": "ค่ารายการ",
    "cascadeFilterTip": "แสดงเฉพาะค่าที่กรอง ด้วยสมการก่อนหน้านี้",
    "noneCascadeFilterTip": "ค่าที่ไม่ซ้ำทั้งหมดของข้อมูลนี้",
    "previousCascadeFilterTip": "ค่ากรองโดยสมการก่อนหน้านี้",
    "allCascadeFilterTip": "ค่ากรองโดยสมการอื่น ๆ ทั้งหมด"
  },
  "featureLayerSource": {
    "layer": "ชั้นข้อมูล",
    "browse": "เบราว์",
    "selectFromMap": "แผนที่",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "เซอร์วิส URL",
    "inputLayerUrl": "URL ชั้นข้อมูลตั้งต้น",
    "selectLayer": "เลือกชั้นข้อมูลฟีเจอร์จากแผนที่ปัจจุบัน",
    "chooseItem": "เลือกขั้นข้อมูลฟีเจอร์",
    "setServiceUrl": "ใส่ URL ของบริการข้อมูลหรือบริการแผนที่",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "เลือกชั้นข้อมูลฟีเจอร์"
  },
  "queryableLayerSource": {
    "layer": "ชั้นข้อมูล",
    "browse": "ค้นหา",
    "selectFromMap": "แผนที่",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "เซอร์วิส URL",
    "inputLayerUrl": "URL ชั้นข้อมูลตั้งต้น",
    "selectLayer": "เลือกชั้นข้อมูลจากแผนที่ปัจจุบัน",
    "chooseItem": "เลือกรายการ",
    "setServiceUrl": "ใส่  URL ของเซอร์วิส",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "เลือกชั้นข้อมูล"
  },
  "gpSource": {
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "เซอร์วิส URL",
    "selectFromOnline": "ArcGIS Online",
    "setServiceUrl": "ใส่ URL ของบริการประมวลผลทางภูมิศาสตร์",
    "chooseItem": "เลือกรายการข้อมูล GeoProcessing Service",
    "chooseTask": "เลือกรายการทำงานของ GeoProessing"
  },
  "itemSelector": {
    "map": "แผนที่",
    "selectWebMap": "เลือกเว็บแผนที่",
    "addMapFromOnlineOrPortal": "ค้นหาและเพิ่มเว็บแมพที่จะใช้ในแอพพลิเคชั่นจาก ArcGIS Online สำหรับแหล่งข้อมูลสาธารณะหรือเนื้อหาส่วนตัวที่อยู่ใน ArcGIS Online หรือในพอร์ทัล",
    "searchMapName": "ค้นหาจากชื่อแผนที่...",
    "searchNone": "เราไม่สามารถค้นหาในสิ่งที่คุณต้องการได้ โปรดลองอีกครั้งหนึ่ง",
    "groups": "กลุ่ม :",
    "noneGroups": "ไม่มีกลุ่ม",
    "signInTip": "การอยู่ในระบบของคุณหมดเวลาลงแล้ว โปรดรีเฟรชที่บราวเซอร์ใหม่อีกครั้งเพื่อทำการเข้าสู่ระบบพอร์ทัลของคุณอีกครั้ง",
    "signIn": "ลงชื่อเข้าใช้",
    "publicMap": "สาธารณะ",
    "myOrganization": "องค์กรของฉัน",
    "myGroup": "กลุ่มของฉัน",
    "myContent": "เนื้อหาของฉัน",
    "count": "นับ",
    "fromPortal": "จากพอร์ทัล",
    "fromOnline": "จาก ArcGIS.com",
    "noneThumbnail": "รูปภาพขนาดเล็กไม่สามารถใช้งานได้",
    "owner": "เจ้าของ",
    "signInTo": "ลงชื่อเข้าใช้สู่",
    "lastModified": "ปรับปรุงครั้งสุดท้าย",
    "moreDetails": "รายละเอียดเพิ่มเติม",
    "mostRecent": "ล่าสุด",
    "mostViewed": "ดูมากที่สุด",
    "highestRated": "จัดอันดับสูงสุด",
    "viewItemDetails": "ดูรายละเอียดของข้อมูล"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Service นี้ไม่รองรับการคัดกรองข้อมูล"
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "ไม่มีชั้นข้อมูลการดำเนินการบนแผนที่"
  },
  "layerInfosMenu": {
    "titleBasemap": "แผนที่ฐาน",
    "titleLayers": "ชั้นข้อมูลแสดงผล",
    "labelLayer": "ชื่อชั้นข้อมูล",
    "itemZoomTo": "ขยายไปยัง",
    "itemTransparency": "ความโปร่งแสง",
    "itemTransparent": "ความโปร่งแสง",
    "itemOpaque": "ความทึบแสง",
    "itemMoveUp": "เลื่อนขึ้น",
    "itemMoveDown": "เลื่อนลง",
    "itemDesc": "คำอธิบาย",
    "itemDownload": "ดาวน์โหลด",
    "itemToAttributeTable": "ดูในตารางแอตทริบิวต์"
  },
  "imageChooser": {
    "unsupportReaderAPI": "สิ่งที่ต้องทำ: เบราว์เซอร์ไม่สนับสนุนไฟล์อ่าน API",
    "readError": "การอ่านไฟล์ล้มเหลว",
    "unknowError": "ไม่สามารถดำเนินการได้อย่างสมบูรณ์",
    "invalidType": "ประเภทของไฟล์ไม่ถูกต้อง",
    "cropImage": "ตัดรูปภาพ",
    "exceed": "ขนาดไฟล์ห้ามเกิน 1024 KB",
    "enableFlash": "โปรดเปิดใช้งาน Adobe Flash ก่อนที่จะเรียกดูภาพ",
    "cropWaining": "กรุณาเลือกภาพที่อย่างน้อย ${width} x ${height} พิเซล",
    "toolTip": "เพื่อให้ได้ผลลัพธ์ที่ดีที่สุดควรจะเป็นภาพ ${width} พิกเซลกว้างโดย ${height} พิกเซลสูง ขนาดอื่น ๆ จะได้รับการปรับเปลี่ยนให้เหมาะสม รูปแบบภาพที่ยอมรับได้คือ: PNG, GIF และ JPEG"
  },
  "simpleTable": {
    "moveUp": "เลื่อนขึ้น",
    "moveDown": "เลื่อนลง",
    "deleteRow": "ลบทิ้ง",
    "edit": "แก้ไข"
  },
  "urlParams": {
    "invalidToken": "โทเค็นไม่ถูกต้อง",
    "validateTokenError": "โทเค็นไม่ถูกต้อง หรือข้อผิดพลาดของเครือข่าย"
  },
  "exportTo": {
    "exportTo": "ส่งออก",
    "toCSV": "นำออกเป็นไฟล์ CSV",
    "toFeatureCollection": "ส่งออกไปยังฟีเจอร์คอลเล็กชัน",
    "toGeoJSON": "ส่งออกเป็น GeoJSON"
  },
  "appState": {
    "title": "ส่วนของแอพ",
    "restoreMap": "คลิกเพื่อเรียกขอบเขตแผนที่และชั้นข้อมูลในการมองเห็น เมื่อคุณไม่ได้อยู่ที่หน้าต่างการทำงาน"
  },
  "featureActions": {
    "featureActions": "ฟีเจอร์ที่ใช้งาน",
    "ZoomTo": "ขยายไปยัง",
    "PanTo": "เลื่อนไปที่",
    "Flash": "แฟลช",
    "ShowPopup": "แสดงกล่องข้อความ pop-up",
    "CreateLayer": "สร้างชั้นข้อมูล",
    "ShowStatistics": "สถิติ...",
    "ClearSelection": "ล้างการเลือก",
    "ExportToCSV": "นำออกเป็นไฟล์ CSV",
    "ShowSelectedFeature": "แสดงเฉพาะข้อมูลที่ถูกเลือก",
    "ExportToFeatureCollection": "ส่งออกไปยังฟีเจอร์คอลเล็กชัน",
    "ExportToGeoJSON": "ส่งออกเป็น GeoJSON",
    "EditAttributes": "แก้ไขตารางเชิงบรรยาย",
    "AddMarker": "เพิ่มเครื่องหมาย",
    "RemoveMarker": "นำเครื่องหมายออก",
    "SaveToMyContent": "บันทึกไปที่เนื้อหาของฉัน"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "ชั้นข้อมูลที่มีความสัมพันธ์",
    "selectedFeatures": "ใช้การเลือกข้อมูล",
    "drawShapesTip": "วาดรูปพื้นที่ เพื่อเลือกข้อมูล",
    "pleaseDrawShapesTip": "กรุณาวาดรูปพื้นที่ เพื่อเลือกข้อมูล",
    "allFeaturesTip": "ข้อมูลทั้งหมดในชั้นข้อมูล",
    "selectFeaturesOrDrawShapesTip": "โปรดใช้ข้อมูลที่เลือกในชั้นข้อมูลนี้ หรือวาดรูปทรงบนแผนที่เพื่อจำกัดข้อมูล"
  },
  "searchDistance": {
    "applySearchDistance": "ใช้ระยะทางในการค้นหา",
    "applySearchDistanceToFeatures": "ใช้ระยะทางในการค้นหา เพื่อเลือกข้อมูล"
  },
  "units": {
    "miles": "ไมล์",
    "milesAbbr": "ไมล์",
    "kilometers": "กิโลเมตร",
    "kilometersAbbr": "กม",
    "feet": "ฟุต",
    "feetAbbr": "ฟุต",
    "meters": "เมตร",
    "metersAbbr": "ม",
    "yards": "หลา",
    "yardsAbbr": "หลา",
    "acres": "เอเคอร์",
    "acresAbbr": "เอเคอร์",
    "nauticalMiles": "ไมล์ทะเล",
    "nauticalMilesAbbr": "nmi",
    "uSSurveyFeet": "หน่วยฟุตในระยะสำรวจของ US",
    "uSSurveyFeetAbbr": "ftUS",
    "decimalDegree": "องศาทศนิยม",
    "decimalDegreeAbbr": "วัน",
    "degreeMinuteSeconds": "องศา ลิปดา ฟิลิปดา",
    "degreeMinuteSecondsAbbr": "d-m-s",
    "squareMiles": "ตารางไมล์",
    "squareMilesAbbr": "ตร.ไมล์.",
    "squareKilometer": "ตารางกิโลเมตร",
    "squareKilometerAbbr": "ตร. กม.",
    "squareFeet": "ตารางนิ้ว",
    "squareFeetAbbr": "ตร. ฟุต",
    "squareMeters": "ตารางเมตร",
    "squareMetersAbbr": "ตร. ม.",
    "squareYards": "ตารางหลา",
    "squareYardsAbbr": "ตร หลา",
    "squareUSSurveyFeet": "ตารางฟุตในระยะสำรวจของ US",
    "squareUSSurveyFeetAbbr": "ตัวย่อตารางฟุตของ US"
  },
  "featureSetChooser": {
    "select": "เลือก",
    "dragBox": "ลาก",
    "dragMouse": "ลากเม้าส์",
    "selectByRectangle": "เลือกตามสี่เหลี่ยมผืนผ้า",
    "selectFeaturesTip": "เลือกข้อมูล ด้วยการลากเป็นสี่เหลี่ยมรอบข้อมูลที่ต้องการบนแผนที่",
    "newSelectionTip": "สร้างตัวเลือกใหม่",
    "addSelectionTip": "เพิ่มการเลือก",
    "removeSelectionTip": "นำที่เลือกออก",
    "selectFromCurrentSelectionTip": "เลือกจากที่เลือกไว้แล้ว",
    "unselectAllSelectionTip": "ยกเลิกการเลือกข้อมูลที่เลือกอยู่ในปัจจุบันทั้งหมด",
    "selectByPolygon": "เลือกตามรูปหลายเหลี่ยม",
    "selectByCircle": "เลือกตามวงกลม",
    "selectByLine": "เลือกตามเส้น",
    "chooseSelectingTools": "เลือกเครื่องมือที่ใช้เลือกข้อมูล",
    "darw": "วาด",
    "drawShap": "วาด"
  },
  "widgetManager": {
    "createWidgetError": "การสร้างวิดเจ็ตมีข้อผิดพลาด",
    "createWidgetSettingPageError": "การสร้างหน้าการตั้งค่าวิดเจ็ตมีข้อผิดพลาด",
    "loadWidgetResourceError": "การโหลดข้อมูลสำหรับวิดเจ็ตมีข้อผิดพลาด"
  },
  "shareOptions": {
    "shareMap": "เลือกผู้ที่สามารถดูแอปนี้",
    "shareMapTips": "ขณะนี้แอปของคุณมีการแบ่งบันให้กับคนเหล่านี้",
    "everyone": "ใครก็ตาม",
    "theseGroups": "กลุ่มคนเหล่านี้"
  },
  "shareLink": {
    "email": "อีเมล์",
    "shareEmail": "อีเมล์",
    "facebook": "เฟสบุ๊ค",
    "shareFacebook": "เฟสบุ๊ค",
    "twitter": "ทวิตเตอร์",
    "shareTwitter": "ทวิตเตอร์",
    "googlePlus": "กูเกิ้ล+",
    "shareGooglePlus": "กูเกิ้ล+",
    "EmbedTips": "ฝังแอปในเว็บไซต์",
    "shareEmailSubject": "แบ่งปันเว็บแอป:",
    "shareEmailTxt1": "นี่คือเว็บแอปที่คุณแชร์โดยใช้ Web AppBuilder สำหรับ ArcGIS",
    "shareEmailTxt2": "คุณสามารถสร้างและแบ่งปันเว็บแอปของคุณเองด้วย Web AppBuilder สำหรับ ArcGIS ของ Esri",
    "shareEmailTxt3": "ดูที่ http://www.esri.com/software/web-appbuilder สำหรับรายละเอียดเพิ่มเติม",
    "smallSize": "เล็ก",
    "mediumSize": "กลาง",
    "largeSize": "ใหญ่",
    "customSize": "แก้ไขเอง",
    "embed": "ฝังแอปในเว็บไซต์",
    "more": "ฝังตัวเลือก",
    "changeShareSettings": "เปลี่ยนการตั้งค่าการเผยแพร่",
    "shareLinkText": "แชร์ลิงก์ไปยังแอปนี้",
    "linkOptions": "ตัวเลือกลิงค์",
    "linkOptionsUrlParameters": "เลือกพารามิเตอร์ของ URL ให้รวมอยู่ในการเชื่อมโยง",
    "currentMapExtent": "ขอบเขตแผนที่ปัจจุบัน",
    "chooseCenterWithLevel": "คลิกที่แผนที่ เพื่อกำหนดศูนย์กลางของแผนที่ ตามระดับการขยาย",
    "chooseCenterWithScale": "คลิกที่แผนที่ เพื่อกำหนดศูนย์กลางของแผนที่ ตามมาตราส่วน",
    "findLocation": "ค้นหาสถานที่ หรือข้อมูล และขยายเข้าไป",
    "findLocation_inputPlaceholder": "สถานที่ หรือข้อมูลของคุณ",
    "queryFeature": "สอบถามด้วยข้อมูล และซูมไป",
    "addMarker": "เพิ่มเครื่องหมายบนแผนที่",
    "addMarker_titlePlaceholder": "ชื่อของเครื่องหมายแบบป๊อปอัพ",
    "addMarker_symbolURL": "URL ของสัญลักษณ์เครื่องหมาย",
    "addMarker_label": "ป้ายชื่อของเครื่องหมาย",
    "popupTitle": "หัวข้อป๊อปอัพ",
    "zoomLevel": "ระดับการซูม",
    "overwirteMobileLayout": "แทนที่ขนาดหน้าจอเริ่มต้น ด้วยรูปแบบหน้าจอมือถือ",
    "language": "ตั้งค่าภาษาในการแสดงผลแอป",
    "auth": "ตรวจสอบผู้ใช้โดยอัตโนมัติ",
    "linkPreview": "ตัวอย่างลิงก์",
    "useShortenLink": "ลิงก์สั้น",
    "shareMapUrlExtent": "แชร์ขอบเขตแผนที่ปัจจุบัน",
    "shareToWebTips": "แอปนี้ไม่ได้แชร์ให้ใช้ร่วมกันแบบสาธารณะ ประชาชนจะไม่สามารถดูได้"
  },
  "webSceneLoader": {
    "webglSupportTip": "แอพพลิเคชันเว็บ 3D ไม่ได้รับการสนับสนุนในบราวเซอร์ของคุณ"
  },
  "map": {
    "basemapNotAvailable": "ไม่มีแผนที่ฐานให้ใช้งาน",
    "displayDefaultBasemap": "แสดงแผนที่ฐานเริ่มต้นแทน",
    "layerLoadedError": "ชั้นข้อมูล, ${layers} ไม่สามารถเพิ่มเข้าแผนที่ได้"
  },
  "popup": {
    "relatedTables": "ตารางเชื่อมโยง",
    "relatedRecords": "เรคคอร์ดเชื่อมโยง",
    "noRelatedRecotds": "ไม่พบแถวข้อมูลที่เกี่ยวข้อง",
    "chooseFieldTip": "เลือกตารางเพื่อแสดงรายการ",
    "saveAsPopupTitle": "เหมือนกับชื่อป๊อปอัพ"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "มีฟีเจอร์มากเกินไปในการเลือกของคุณ อาจจะใช้เวลานานในการดึงข้อมูลและแสดงผลบนแผนที่",
    "askForContinue": "คุณต้องการที่จะทำต่อหรือไม่?"
  },
  "colorPalette": {
    "transparent": "โปร่งแสง",
    "custom": "แก้ไขเอง"
  },
  "temperature": {
    "celsius": "องศาเซลเซียส",
    "fahrenheit": "องศาฟาร์เรนไฮน์"
  },
  "report": {
    "printButtonLabel": "พิมพ์",
    "reportDimensionsMsg": "รายงานชิ้นนี้ออกแบบเพื่อพิมพ์บน ${paperSize} กระดาษ",
    "unableToPrintMapMsg": "เกิดข้อผิดพลาดในขณะที่พิมพ์แผนที่(s).",
    "notesHint": "ป้อนความคิดเห็นที่นี่",
    "landscape": "แนวนอน",
    "portrait": "แนวตั้ง",
    "mapOnly": "แผนที่เท่านั้น",
    "a0": "A0",
    "a1": "A1",
    "a2": "A2",
    "a3": "A3",
    "a4": "A4",
    "a5": "A5",
    "letterANSIA": "Letter ANSI A",
    "tabloidANSIB": "Tabloid ANSI B",
    "letter": "จดหมาย",
    "legal": "ตามกฎหมาย",
    "tabloid": "Tabloid",
    "ansi_a": "ANSI A",
    "ansi_b": "ANSI B",
    "ansi_c": "ANSI C",
    "ansi_d": "ANSI D",
    "ansi_e": "ANSI E"
  },
  "snapshot": {
    "snapshot_complete": "สร้างสแนปช็อตเรียบร้อยแล้ว",
    "snapshot_failed": "ไม่สามารถสร้างสแนปช็อต",
    "snapshot_append": "สแนปซ็อต",
    "utc": "UTC"
  },
  "statisticsChart": {
    "enlarge": "ขยาย",
    "setting": "การตั้งค่า",
    "count": "นับ",
    "horizontalAxis": "แกนนอน",
    "verticalAxis": "แกนแนวตั้ง",
    "dataLabels": "ป้ายกำกับข้อมูล",
    "color": "สี"
  },
  "frameworkDatasource": {
    "setDataSource": "ตั้งค่าแหล่งข้อมูล",
    "customDataSource": "แหล่งข้อมูลเพิ่มเติม",
    "selectCustomDataTip": "เลือกแหล่งข้อมูลจากแอพพลิเคชั่นนี้",
    "widgetOutputs": "ผลลัพธ์วิดเจ็ต",
    "noExtraDsAvailable": "ไม่มีแหล่งข้อมูลเพิ่มเติมที่พร้อมใช้งาน",
    "addExtraDsTip": "ไปที่แท็บแอตทริบิวต์ของผู้สร้างและคลิกแหล่งข้อมูลเสริมเพื่อเพิ่มข้อมูล",
    "widgetOutpusListTip": "เอาต์พุตวิดเจ็ต (ถ้ามี) อยู่ที่นี่ด้วย"
  },
  "gridLayout": {
    "addWidgetTip": "เพิ่มวิดเจ็ตที่นี่ผ่านแท็บวิดเจ็ต",
    "modifyLayout": "แก้ไขหน้าเค้าโครงแผนที่",
    "dragToAdd": "ลากเพื่อเพิ่ม",
    "mapArea": "พื้นที่แผนที่"
  },
  "noEditPrivileges": "บัญชีของคุณไม่ได้รับอนุญาตให้สร้างหรือปรับเปลี่ยนข้อมูล",
  "invalidConfiguration": "วิดเจ็ตอย่างใดอย่างหนึ่งไม่ได้กำหนดค่า หรือชั้นข้อมูลที่ใช้ในการกำหนดค่าที่ไม่ได้อยู่ในแผนที่ กรุณาเปิดแอปในโหมดผู้สร้างและกำหนดค่าวิดเจ็ต"
});