define({
  "instruction": "속성 테이블에 처음 보여질 레이어를 선택하고 구성합니다.",
  "label": "레이어",
  "show": "표시",
  "actions": "레이어 필드 구성",
  "field": "필드",
  "alias": "별칭",
  "visible": "표시",
  "linkField": "링크 필드",
  "noLayers": "피처 레이어를 사용할 수 없음",
  "back": "뒤로",
  "exportCSV": "CSV로 내보내기 허용",
  "expand": "초기에 위젯 확장",
  "filterByExtent": "기본 설정에 따라 맵 범위별 필터링 활성화",
  "restore": "기본 값으로 복원",
  "ok": "확인",
  "cancel": "취소",
  "includePoint": "포인트 좌표를 내보낸 파일에 포함",
  "configureLayerFields": "레이어 필드 구성",
  "result": "저장됨",
  "warning": "보기 옵션을 먼저 선택하세요.",
  "fieldCheckWarning": "필드를 하나 이상 선택해야 합니다.",
  "unsupportQueryWarning": "속성 테이블 위젯에 표시하려면 레이어가 쿼리 작업을 지원해야 합니다. 서비스에 쿼리 기능이 켜져 있는지 확인하세요.",
  "unsupportQueryLayers": "속성 테이블 위젯에 표시하려면 다음 레이어가 쿼리 작업을 지원해야 합니다. 서비스에 쿼리 기능이 켜져 있는지 확인하세요.",
  "fieldName": "이름",
  "fieldAlias": "별칭",
  "fieldVisibility": "가시성",
  "fieldActions": "작업",
  "showAttachments": "첨부 파일 표시"
});