define({
  "instruction": "L'écran de présentation apparaît avant que l'application ne soit accessible.",
  "defaultContent": "Ajoutez du texte, des liens et des petits graphiques ici.",
  "requireConfirm": "Demander confirmation avant de poursuivre",
  "noRequireConfirm": "Ne pas demander confirmation avant de poursuivre",
  "optionText": "Possibilité pour l’utilisateur de désactiver l’écran de présentation au démarrage de l’application.",
  "confirmLabel": "Textes de confirmation : ",
  "confirmLabelColor": "Couleur du texte de confirmation",
  "defaultConfirmText": "J’accepte les conditions d’utilisation ci-dessus",
  "confirmOption": "Toujours afficher cet écran de présentation à chaque lancement de l'application",
  "backgroundColor": "Couleur d'arrière-plan",
  "content": "Contenu",
  "contentDescription": "Définir le contenu qui apparaît sur l'écran de présentation.",
  "appearance": "Apparence",
  "appearanceDescription": "Configurer l'apparence de l'écran de présentation.",
  "size": "Taille",
  "width": "Largeur",
  "height": "Hauteur",
  "custom": "Personnalisé",
  "background": "Arrière-plan",
  "colorFill": "Couleur de remplissage",
  "imageFill": "Image de remplissage",
  "chooseFile": "Choisir le fichier",
  "noFileChosen": "Aucun fichier sélectionné",
  "transparency": "Transparence",
  "sizeFill": "Remplissage",
  "sizeFit": "Ajuster",
  "sizeStretch": "Etirer pour remplir la zone",
  "sizeCenter": "Centre",
  "sizeTile": "Tuile",
  "buttonColor": "Couleur du bouton",
  "buttonText": "Texte du bouton",
  "buttonTextColor": "Couleur de texte du bouton",
  "contentAlign": "Alignement du contenu",
  "alignTop": "Haut",
  "alignMiddle": "Milieu",
  "maskColor": "Couleur du masque",
  "options": "Options",
  "optionsDescription": "Configurer le comportement de l'écran de présentation."
});