define({
  "sourceSetting": "Ustawienia źródła wyszukiwania",
  "instruction": "Dodaj i skonfiguruj usługi geokodowania lub warstwy obiektów jako źródła wyszukiwania. Źródła te określają, co można wyszukiwać w polu wyszukiwania.",
  "add": "Dodaj źródło wyszukiwania",
  "addGeocoder": "Dodaj geokoder",
  "geocoder": "Geokoder",
  "setLayerSource": "Skonfiguruj źródło warstwy",
  "setGeocoderURL": "Skonfiguruj adres URL geokodera",
  "searchableLayer": "Warstwa obiektów",
  "name": "Nazwa",
  "countryCode": "Kody kraju lub regionu",
  "countryCodeEg": "np. ",
  "countryCodeHint": "Pozostawienie pustego pola uruchomi wyszukiwanie we wszystkich krajach i regionach",
  "generalSetting": "Ustawienia ogólne",
  "allPlaceholder": "Tekst zastępczy dla wyszukiwania wszystkich: ",
  "showInfoWindowOnSelect": "Wyświetl odrębne okno ze znalezionym elementem: obiektem lub miejscem",
  "searchInCurrentMapExtent": "Wyszukaj tylko w bieżącym zasięgu mapy",
  "zoomScale": "Skala powiększenia",
  "locatorUrl": "Adres URL geokodera",
  "locatorName": "Nazwa geokodera",
  "locatorExample": "Przykład",
  "locatorWarning": "Ta wersja usługi geokodowania nie jest obsługiwana. Widżet obsługuje usługę geokodowania w wersji 10.1 i nowszych.",
  "locatorTips": "Sugestie są niedostępne ponieważ usługa geokodowania nie obsługuje funkcji sugestii.",
  "layerSource": "Źródło warstwy",
  "searchLayerTips": "Sugestie są niedostępne ponieważ usługa obiektowa nie obsługuje funkcji paginacji.",
  "placeholder": "Tekst zastępczy",
  "searchFields": "Pola wyszukiwania",
  "displayField": "Pole wyświetlania",
  "exactMatch": "Dokładne dopasowanie",
  "maxSuggestions": "Maksymalna liczba sugestii",
  "maxResults": "Maksymalna liczba wyników",
  "enableLocalSearch": "Włącz wyszukiwanie lokalne",
  "minScale": "Skala min.",
  "minScaleHint": "Kiedy skala mapy będzie większa niż ta skala, zostanie zastosowane wyszukiwanie lokalne",
  "radius": "Promień",
  "radiusHint": "Określa promień obszaru wokół bieżącego centrum mapy używanego do przyspieszenia oceny propozycji geokodowania, aby propozycje znajdujące się najbliżej lokalizacji były zwracane jako pierwsze",
  "meters": "Metry",
  "setSearchFields": "Skonfiguruj pola wyszukiwania",
  "set": "Ustaw",
  "fieldSearchable": "możliwe do wyszukiwania",
  "fieldName": "Nazwa",
  "fieldAlias": "Alias",
  "ok": "OK",
  "cancel": "Anuluj",
  "invalidUrlTip": "Adres URL ${URL} jest nieprawidłowy lub nieosiągalny."
});