define({
  "instruction": "Uvodni ekran se prikazuje pre nego što aplikacija postane dostupna.",
  "defaultContent": "Dodajte tekst, linkove i male grafičke prikaze ovde.",
  "requireConfirm": "Zahtevaj potvrdu za nastavak",
  "noRequireConfirm": "Ne zahtevaj potvrdu za nastavak",
  "optionText": "Opcija za korisnike da onemoguće uvodni ekran pri pokretanju aplikacije.",
  "confirmLabel": "Tekstovi potvrde: ",
  "confirmLabelColor": "Boja tekstova potvrde",
  "defaultConfirmText": "Saglasan sam sa gorenavedenim odredbama i uslovima",
  "confirmOption": "Prikaži ovaj uvodni ekran svaki put kada se aplikacija pokrene",
  "backgroundColor": "Boja pozadine",
  "content": "Sadržaj",
  "contentDescription": "Definišite sadržaj koji se prikazuje na uvodnom ekranu.",
  "appearance": "Izgled",
  "appearanceDescription": "Podesite izgled uvodnog ekrana.",
  "size": "Veličina",
  "width": "Širina",
  "height": "Visina",
  "custom": "Prilagođeno",
  "background": "Pozadina",
  "colorFill": "Popuna u boji",
  "imageFill": "Popuna slike",
  "chooseFile": "Izaberite datoteku",
  "noFileChosen": "Nijedna datoteka nije odabrana",
  "transparency": "Prozirnost",
  "sizeFill": "Ispuna",
  "sizeFit": "Uklapanje",
  "sizeStretch": "Razvuci za ispunu",
  "sizeCenter": "Centar",
  "sizeTile": "Tajl",
  "buttonColor": "Boja dugmeta",
  "buttonText": "Tekst dugmeta",
  "buttonTextColor": "Boja teksta dugmeta",
  "contentAlign": "Uklapanje sadržaja",
  "alignTop": "Vrh",
  "alignMiddle": "Sredina",
  "maskColor": "Boja maske",
  "options": "Opcije",
  "optionsDescription": "Podesite ponašanje uvodnog ekrana."
});