define({
  "instruction": "Layar pembuka muncul sebelum aplikasi dapat diakses.",
  "defaultContent": "Tambah teks, tautan, dan grafis kecil di sini.",
  "requireConfirm": "Memerlukan konfirmasi untuk melanjutkan",
  "noRequireConfirm": "Tidak memerlukan konfirmasi untuk melanjutkan",
  "optionText": "Opsi bagi pengguna untuk menonaktifkan layar pembuka pada saat memulai aplikasi.",
  "confirmLabel": "Teks Konfirmasi: ",
  "confirmLabelColor": "Warna teks konfirmasi",
  "defaultConfirmText": "Saya menyetujui syarat dan ketentuan di atas",
  "confirmOption": "Selalu tampilkan layar pembuka setiap kali aplikasi diluncurkan",
  "backgroundColor": "Warna Latar Belakang",
  "content": "Konten",
  "contentDescription": "Tentukan konten yang ditampilkan di layar awal.",
  "appearance": "Tampilan",
  "appearanceDescription": "Atur penampilan layar awal.",
  "size": "Ukuran",
  "width": "Lebar",
  "height": "Tinggi",
  "custom": "Kustom",
  "background": "Latar belakang",
  "colorFill": "Isian Warna",
  "imageFill": "Isian gambar",
  "chooseFile": "Pilih file",
  "noFileChosen": "Tidak ada file dipilih",
  "transparency": "Transparansi",
  "sizeFill": "Isi",
  "sizeFit": "Sesuai",
  "sizeStretch": "Bentangkan untuk mengisi (Stretch to fill)",
  "sizeCenter": "Pusat",
  "sizeTile": "Tile",
  "buttonColor": "Warna tombol",
  "buttonText": "Teks tombol",
  "buttonTextColor": "Warna teks tombol",
  "contentAlign": "Perataan konten",
  "alignTop": "Atas",
  "alignMiddle": "Tengah",
  "maskColor": "Warna mask",
  "options": "Opsi",
  "optionsDescription": "Atur perilaku layar awal."
});