define({
  "_widgetLabel": "विशेषता तालिका",
  "_featureAction_ShowRelatedRecords": "संबंधित रिकॉर्ड दिखाएँ",
  "_featureAction_ViewInTable": "विशेषता तालिका में दिखाएँ",
  "ok": "ठीक है",
  "cancel": "रद्द करें",
  "unsupportQueryWarning": "लेयर को विशेषता तालिका विजेट में प्रदर्शित करने के लिए क्वेरी कार्रवाई का समर्थन करने की जरूरत है। सुनिश्चित करें कि सेवा में क्वेरी क्षमता चालू है।",
  "exportMessage": "CSV फाइल में डेटा निर्यात करें?",
  "exportFiles": "CSV में निर्यात करें",
  "exportSelected": "चयनित को CSV में निर्यात करें",
  "exportAll": "सभी को CSV में निर्यात करें",
  "options": "विकल्प",
  "zoomto": "जूम करें",
  "highlight": "ग्राफ़िक्स को हाईलाइट करें",
  "selectAll": "सभी पृष्ठों के रिकॉर्ड चुनें",
  "selectPage": "वर्तमान पृष्ठ का रिकॉर्ड चुनें",
  "clearSelection": "चयन मिटायें",
  "filter": "फिल्टर करें",
  "setFilterTip": "कृपया फिल्टर को सही ढंग से निर्धारित करें।",
  "noFilterTip": "बिना फिल्टर समीकरण निर्धारित किए, यह क्वेरी कार्य निर्दिष्ट डेटा स्रोत में सभी सुविधाओं की सूची बनाएगा।",
  "filterByExtent": "मैप सीमा अनुसार फिल्टर करें",
  "showSelectedRecords": "चयनित रिकॉर्ड दिखाएँ",
  "showAllRecords": "सभी रिकॉर्ड दिखाएँ",
  "showRelatedRecords": "संबंधित रिकॉर्ड दिखाएँ",
  "noRelatedRecords": "कोई संबंधित रिकॉर्ड नहीं मिला",
  "attachmentColumn": "फ़ोटो और फ़ाइल",
  "refresh": "ताज़ा करें",
  "features": "फ़ीचर्स",
  "records": "रिकॉर्डों",
  "selected": "चयनित",
  "transparent": "पारदर्शी मोड",
  "indicate": "चयन का पता लगाएँ",
  "columns": "स्तंभ दिखाएँ/छिपाएँ",
  "selectionSymbol": "चयन प्रतीक",
  "closeMessage": "तालिका छिपाएँ (इसे नीचे से फिर से विस्तृत करें)",
  "dataNotAvailable": "डेटा उपलब्ध नहीं है!<br>फिर से प्रयास करने के लिए [Refresh] बटन पर क्लिक करें।",
  "openTableTip": "विशेषता तालिका को खोलें",
  "closeTableTip": "विशेषता तालिका छिपाएँ",
  "sortAsc": "बढ़ते क्रम में क्रमित करें",
  "sortDes": "घटते क्रम में क्रमित करें",
  "statistics": "आँकड़े",
  "attachments": "अनुलग्नक",
  "files": "फ़ाइलें"
});