define({
  "id": "ID",
  "state": "Koordinatene vises som standard i koordinatsystemet for gjeldende kart. Hvis vil vil ha koordinater fra andre koordinatsystem, må du legge dem til og angi nødvendige transformasjoner.",
  "outputUnit": "Utdataenhet",
  "wkid": "Utdata-WKID",
  "label": "Navn på koordinatsystem for utdata",
  "transformationWkid": "Transformasjon-WKID",
  "transformationLabel": "Transformasjonsetikett",
  "transformForward": "Transformer fremover",
  "actions": "Handlinger",
  "warning": "Angi en gyldig geografisk referanse-WKID!",
  "tfWarning": "Legg inn gyldig datumtransformasjon-WKID!",
  "spinnerLabel": "Avrund koordinater til: ",
  "decimalPlace": "desimaler",
  "separator": "Vis tusenskilletegn",
  "getVersionError": "Kan ikke hente versjonsnummer for geometritjenesten",
  "add": "Legg til koordinatsystem for utdata",
  "edit": "Rediger koordinatsystem",
  "output": "Koordinatsystem for utdata",
  "cName": "Koordinatsystemnavn",
  "units": "Visningsenheter: ",
  "datum": "Datumtransformasjon",
  "tName": "Transformasjonsnavn",
  "tWKIDPlaceHolder": "WKID for transformasjonen",
  "forward": "Bruk transformasjon fremover",
  "ok": "OK",
  "cancel": "Avbryt",
  "olderVersion": "Geometritjenesten støtter ikke transformasjonoperasjoner",
  "REPEATING_ERROR": " Koordinatsystemet finnes i resultatliste.",
  "Default": "Standard",
  "Inches": "Tommer",
  "Foot": "Fot",
  "Yards": "Yards",
  "Miles": "Miles",
  "Nautical_Miles": "Nautiske mil",
  "Millimeters": "Millimeter",
  "Centimeters": "Centimeter",
  "Meter": "Meter",
  "Kilometers": "Kilometer",
  "Decimeters": "Desimeter",
  "Decimal_Degrees": "Desimalgrader",
  "Degrees_Decimal_Minutes": "Grader desimalminutter",
  "Degree_Minutes_Seconds": "Grader minutter sekunder",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Visningsrekkefølge for koordinater:",
  "lonLatTips": "Lengdegrad/breddegrad (X, Y)",
  "latLonTips": "Breddegrad/lengdegrad(Y,X)"
});