define({
  "instruction": "Izvēlieties un konfigurējiet slāņus, kas sākotnēji tiks rādīti atribūtu tabulā.",
  "label": "Slānis",
  "show": "Parādīt",
  "actions": "Konfigurēt slāņa laukus",
  "field": "Lauks",
  "alias": "Aizstājvārds",
  "visible": "Redzams",
  "linkField": "Saistīt lauku",
  "noLayers": "Nav pieejams neviens elementu slānis",
  "back": "Atpakaļ",
  "exportCSV": "Atļaut eksportēt uz CSV",
  "expand": "Sākotnēji izvērst logrīku",
  "filterByExtent": "Aktivizēt filtrēšanu atbilstoši kartes pārklājumam pēc noklusējuma",
  "restore": "Atjaunot uz noklusējuma vērtību",
  "ok": "Labi",
  "cancel": "Atcelt",
  "includePoint": "Iekļaut punktu koordinātas uz eksportēto failu",
  "configureLayerFields": "Konfigurēt slāņa laukus",
  "result": "Saglabāšana izdevās",
  "warning": "Lūdzu, vispirms atlasiet opciju Rādīt.",
  "fieldCheckWarning": "Jābūt atlasītam vismaz vienam laukam.",
  "unsupportQueryWarning": "Slānim ir jāatbalsta vaicājuma darbība, lai rādītu atribūtu tabulas logrīkā. Nodrošiniet, lai pakalpojumā būtu ieslēgta vaicājuma iespēja.",
  "unsupportQueryLayers": "Tālāk norādītajam slānim ir jāatbalsta vaicājuma darbība, lai rādītu atribūtu tabulas logrīkā. Nodrošiniet, lai servisā būtu ieslēgta vaicājuma iespēja.",
  "fieldName": "Nosaukums",
  "fieldAlias": "Aizstājvārds",
  "fieldVisibility": "Redzamība",
  "fieldActions": "Darbības",
  "showAttachments": "Rādīt pielikumus"
});