define({
  "sourceSetting": "Pretraži postavke izvora",
  "instruction": "Dodaj i konfiguriši servise za geokodiranje ili slojeve geoobjekata kao izvore pretrage. Ovi navedeni izvori određuju šta može da se pretražuje unutar trake za pretragu.",
  "add": "Dodaj izvor pretrage",
  "addGeocoder": "Dodaj geokoder",
  "geocoder": "Geokoder",
  "setLayerSource": "Postavi izvor sloja",
  "setGeocoderURL": "Postavi URL adresu geokodera",
  "searchableLayer": "Sloj geoobjekata",
  "name": "Naziv",
  "countryCode": "Kôd(ovi) zemlje ili regiona",
  "countryCodeEg": "npr. ",
  "countryCodeHint": "Ako ova vrednost ostane prazna, pretražuju se sve zemlje i regioni",
  "generalSetting": "Opšte postavke",
  "allPlaceholder": "Tekst čuvara mesta za pretragu svega: ",
  "showInfoWindowOnSelect": "Prikaži iskačući prozor za pronađeni geoobjekat ili lokaciju",
  "searchInCurrentMapExtent": "Pretraži samo u trenutnom obuhvatu mape",
  "zoomScale": "Skala zumiranja",
  "locatorUrl": "URL adresa geokodera",
  "locatorName": "Ime geokodera",
  "locatorExample": "Primer",
  "locatorWarning": "Ova verzija servisa geokôdiranja nije podržana. Vidžet podržava samo servis geokôdiranja 10.1 i novije.",
  "locatorTips": "Predlozi nisu dostupni jer servis geokôdiranja ne podržava predloženu mogućnost.",
  "layerSource": "Izvor sloja",
  "searchLayerTips": "Predlozi nisu dostupni jer servis geoobjekata ne podržava mogućnost paginacije.",
  "placeholder": "Tekst čuvara mesta",
  "searchFields": "Polja za pretragu",
  "displayField": "Prikaži polje",
  "exactMatch": "Potpuno podudaranje",
  "maxSuggestions": "Maksimalno predloga",
  "maxResults": "Maksimalno rezultata",
  "enableLocalSearch": "Omogući lokalnu pretragu",
  "minScale": "Min. razmera",
  "minScaleHint": "Kada je razmera mape veća od ove razmere, primenjuje se lokalna pretraga",
  "radius": "Poluprečnik",
  "radiusHint": "Definiše poluprečnik oblasti oko trenutnog centra mape koja se koristi za poboljšavanje rangiranja kandidata za geokodiranje kako bi se prvo vraćali kandidati najbliži lokaciji",
  "meters": "Metri",
  "setSearchFields": "Postavi polja pretrage",
  "set": "Postavi",
  "fieldSearchable": "pretraživo",
  "fieldName": "Naziv",
  "fieldAlias": "Alias",
  "ok": "U redu",
  "cancel": "Otkaži",
  "invalidUrlTip": "URL adresa ${URL} nije validna ili nije dostupna."
});