define({
  "_widgetLabel": "Coordenada",
  "hintMessage": "Feu clic al mapa per obtenir les coordenades",
  "defaultLabel": "Per defecte",
  "realtimeLabel": "Moveu el ratolí per obtenir les coordenades",
  "computing": "S'està calculant...",
  "latitudeLabel": "Latitud",
  "longitudeLabel": "Longitud",
  "loading": "s'està carregant...",
  "enableClick": "Feu clic per habilitar l'obtenció de coordenades en fer clic al mapa",
  "disableClick": "Feu clic per deshabilitar l'obtenció de coordenades en fer clic al mapa",
  "Default": "Per defecte",
  "Inches": "Polzades",
  "Foot": "Peus",
  "Yards": "Iardes",
  "Miles": "Milles",
  "Nautical_Miles": "Milles nàutiques",
  "Millimeters": "Mil·límetres",
  "Centimeters": "Centímetres",
  "Meter": "Metres",
  "Kilometers": "Quilòmetres",
  "Decimeters": "Decímetres",
  "Decimal_Degrees": "Graus",
  "Degree_Minutes_Seconds": "Graus minuts segons",
  "MGRS": "MGRS",
  "USNG": "USNG"
});