define({
  "id": "ID",
  "state": "Theo mặc định, tọa độ sẽ hiển thị trong hệ tọa độ của bản đồ hiện tại. Để lấy tọa độ trong các hệ tọa độ khác, bạn cần thêm chúng vào và chỉ định chuyển đổi thích hợp.",
  "outputUnit": "Đơn vị đầu ra",
  "wkid": "WKID Đầu ra",
  "label": "Tên hệ tọa độ đầu ra",
  "transformationWkid": "WKID Chuyển đổi",
  "transformationLabel": "Nhãn chuyển đổi",
  "transformForward": "Chuyển đổi chuyển tiếp",
  "actions": "Các hành động",
  "warning": "Vui lòng nhập WKID tham chiếu không gian hợp lệ!",
  "tfWarning": "Vui lòng nhập WKID chuyển đổi dữ liệu hợp lệ!",
  "spinnerLabel": "Làm tròn tọa độ thành: ",
  "decimalPlace": "các chữ số thập phân",
  "separator": "Hiển thị dấu phân tách hàng nghìn",
  "getVersionError": "Không thể lấy thông tin phiên bản của dịch vụ hình học",
  "add": "Thêm hệ tọa độ đầu ra",
  "edit": "Chỉnh sửa hệ tọa độ",
  "output": "Hệ tọa độ đầu ra",
  "cName": "Tên hệ tọa độ",
  "units": "Đơn vị hiển thị: ",
  "datum": "Chuyển đổi hệ tham chiếu",
  "tName": "Tên chuyển đổi",
  "tWKIDPlaceHolder": "WKID chuyển đổi",
  "forward": "Sử dụng chuyển tiếp chuyển đổi",
  "ok": "OK",
  "cancel": "Hủy",
  "olderVersion": "Dịch vụ hình học không hỗ trợ hoạt động chuyển đổi",
  "REPEATING_ERROR": " Hệ tọa độ tồn tại trong danh sách đầu ra.",
  "Default": "Mặc định",
  "Inches": "Inch",
  "Foot": "Feet",
  "Yards": "Thước",
  "Miles": "Dặm",
  "Nautical_Miles": "Hải lý",
  "Millimeters": "Milimét",
  "Centimeters": "Xentimét",
  "Meter": "Mét",
  "Kilometers": "Kilômét",
  "Decimeters": "Đềximét",
  "Decimal_Degrees": "Độ thập phân",
  "Degrees_Decimal_Minutes": "Độ thập phân phút",
  "Degree_Minutes_Seconds": "Độ phút giây",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Thứ tự hiển thị tọa độ:",
  "lonLatTips": "Kinh độ / Vĩ độ(X, Y)",
  "latLonTips": "Vĩ độ / Kinh độ(Y, X)"
});