define({
  "id": "ID",
  "state": "기본 설정에 따라 좌표는 현재 맵의 좌표체계에서 표시됩니다. 다른 좌표체계의 좌표를 가져오려면 좌표를 추가하고 적절한 변환을 지정해야 합니다.",
  "outputUnit": "결과 단위",
  "wkid": "결과 WKID",
  "label": "결과 좌표체계 이름",
  "transformationWkid": "변환 WKID",
  "transformationLabel": "변환 레이블",
  "transformForward": "순방향 변환",
  "actions": "작업",
  "warning": "올바른 공간 기준체계 WKID를 입력하세요.",
  "tfWarning": "올바른 데이텀 변환 WKID를 입력하세요.",
  "spinnerLabel": "좌표 회전: ",
  "decimalPlace": "소수 자릿수",
  "separator": "1000단위 구분 기호 표시",
  "getVersionError": "이 버전의 지오메트리 서비스를 가져올 수 없음",
  "add": "결과 좌표체계 추가",
  "edit": "좌표체계 편집",
  "output": "결과 좌표체계",
  "cName": "좌표체계 이름",
  "units": "디스플레이 단위: ",
  "datum": "데이텀 변환",
  "tName": "변환 이름",
  "tWKIDPlaceHolder": "변환의 WKID",
  "forward": "순방향 변환 사용",
  "ok": "확인",
  "cancel": "취소",
  "olderVersion": "지오메트리 서비스는 변환 작업을 지원하지 않음",
  "REPEATING_ERROR": " 결과 목록에 좌표체계가 있습니다.",
  "Default": "기본값",
  "Inches": "인치",
  "Foot": "피트",
  "Yards": "야드",
  "Miles": "마일",
  "Nautical_Miles": "해리",
  "Millimeters": "밀리미터",
  "Centimeters": "센티미터",
  "Meter": "미터",
  "Kilometers": "킬로미터",
  "Decimeters": "데시미터",
  "Decimal_Degrees": "십진수(DD)",
  "Degrees_Decimal_Minutes": "도-분",
  "Degree_Minutes_Seconds": "도-분-초",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "좌표 표시 순서:",
  "lonLatTips": "경도/위도(X, Y)",
  "latLonTips": "위도/경도(Y, X)"
});