define(
   ({
    "sourceSetting": "Broninstellingen zoeken",
    "instruction": "Geocodeerservices of objectlagen toevoegen en configureren als zoekbronnen. Deze bepaalde bronnen bepalen wat doorzoekbaar is in het zoekvak.",
    "add": "Zoekbron toevoegen",
    "addGeocoder": "Geocoder toevoegen",
    "geocoder": "Geocoder",
    "setLayerSource": "Laagbron instellen",
    "setGeocoderURL": "Geocoder-URL instellen",
    "searchableLayer": "Objectlaag",
    "name": "Naam",
    "countryCode": "Land- of regiocode(s)",
    "countryCodeEg": "bijv. ",
    "countryCodeHint": "Laat deze waarde leeg en alle landen en regio\'s worden gezocht",
    "generalSetting": "Algemene instellingen",
    "allPlaceholder": "Plaatshoudertekst om alles te zoeken: ",
    "showInfoWindowOnSelect": "Pop-up weergeven voor gevonden object of locatie",
    "searchInCurrentMapExtent": "Alleen zoeken in huidige kaartextent",
    "locatorUrl": "Geocoder-URL",
    "locatorName": "Naam van geocoder",
    "locatorExample": "Voorbeeld",
    "locatorWarning": "Deze versie van geocodeerservice wordt niet ondersteund. De widget ondersteunt geocodeerservice 00.0 en hoger.",
    "locatorTips": "Suggesties zijn niet beschikbaar omdat de geocodeerservice geen suggesties ondersteunt.",
    "layerSource": "Laagbron",
    "searchLayerTips": "Suggesties zijn niet beschikbaar omdat de objectservice geen pagination ondersteunt.",
    "placeholder": "Tekst van tijdelijke aanduiding",
    "searchFields": "Zoekvelden",
    "displayField": "Weergaveveld:",
    "exactMatch": "Exacte overeenkomst",
    "maxResults": "Maximale resultaten",
    "setSearchFields": "Zoekvelden instellen",
    "set": "Instellen",
    "fieldSearchable": "doorzoekbaar",
    "fieldName": "Naam",
    "fieldAlias": "Alias",
    "ok": "OK",
    "cancel": "Annuleren",
    "invalidUrlTip": "De URL die u hebt ingevoerd, is ongeldig of ontoegankelijk."
  })
);