define({
  "_widgetLabel": "Réteglista",
  "titleBasemap": "Alaptérképek",
  "titleLayers": "Operatív rétegek",
  "labelLayer": "Réteg neve",
  "itemZoomTo": "Nagyítás erre:",
  "itemTransparency": "Átlátszóság",
  "itemTransparent": "Átlátszó",
  "itemOpaque": "Átlátszatlan",
  "itemMoveUp": "Feljebb",
  "itemMoveDown": "Lejjebb",
  "itemDesc": "Leírás",
  "itemDownload": "Letöltés",
  "itemToAttributeTable": "Megtekintés az Attribútumtáblában",
  "itemShowItemDetails": "Elem részleteinek megjelenítése",
  "empty": "üres",
  "removePopup": "Felugró ablak tiltása",
  "enablePopup": "Felugró ablak engedélyezése",
  "turnAllLayersOff": "Összes réteg kikapcsolása",
  "turnAllLayersOn": "Összes réteg bekapcsolása",
  "expandAllLayers": "Összes réteg kibontása",
  "collapseAlllayers": "Összes réteg bezárása",
  "turnAllLabelsOff": "Összes felirat kikapcsolása",
  "turnAllLabelsOn": "Összes felirat bekapcsolása",
  "showLabels": "Feliratok megjelenítése",
  "hideLables": "Feliratok elrejtése"
});