define({
  "_widgetLabel": "ค่าพิกัด",
  "hintMessage": "คลิกที่แผนที่เพื่อหาค่าพิกัด",
  "defaultLabel": "ค่าเริ่มต้น",
  "realtimeLabel": "เลื่อนเม้าส์ไปบนแผนที่",
  "computing": "กำลังคำนวณ...",
  "latitudeLabel": "ละติจูด",
  "longitudeLabel": "ลองจิจูด",
  "loading": "กำลังโหลด..",
  "enableClick": "คลิกเพื่อสามารถใช้งานบนแผนที่เพื่อได้รับค่าพิกัด",
  "disableClick": "คลิกเพื่อไม่สามารถใช้งานบนแผนที่เพื่อได้รับค่าพิกัด",
  "Default": "ค่าเริ่มต้น",
  "Inches": "นิ้ว",
  "Foot": "ฟุต",
  "Yards": "หลา",
  "Miles": "ไมล์",
  "Nautical_Miles": "ไมล์ทะเล",
  "Millimeters": "มิลลิเมตร",
  "Centimeters": "เซนติเมตร",
  "Meter": "เมตร",
  "Kilometers": "กิโลเมตร",
  "Decimeters": "เดซิเมตร",
  "Decimal_Degrees": "องศา",
  "Degree_Minutes_Seconds": "องศา ลิปดา ฟิลิปดา",
  "MGRS": "หน่วยอ้างอิงทางทหาร MGRS",
  "USNG": "หน่วย USNG"
});