define({
  "common": {
    "apply": "Käytä",
    "ok": "OK",
    "cancel": "Peruuta",
    "yes": "Kyllä",
    "no": "Ei",
    "next": "Seuraava",
    "previous": "Edellinen",
    "back": "Takaisin",
    "selected": "valitut",
    "name": "Nimi",
    "usage": "Käyttö",
    "settings": "Asetukset",
    "home": "Koti",
    "link": "Linkki",
    "messages": "Viestit",
    "outputs": "Tulosaineistot",
    "title": "Otsikko",
    "thumbnail": "Pikkukuva",
    "url": "URL-osoite",
    "actions": "Toimet",
    "layer": "Karttataso",
    "action": "Toimi",
    "input": "Lähtöaineisto",
    "output": "Tulosaineisto",
    "type": "Tyyppi",
    "required": "Pakollinen",
    "options": "Asetukset",
    "label": "Tunnusteksti",
    "tooltip": "Työkalun ohje",
    "visible": "Näkyvä",
    "symbol": "Symboli",
    "popup": "Ponnahdusikkuna",
    "upload": "Lähetä",
    "execute": "Suorita",
    "help": "Ohje",
    "executing": "Suorittaa",
    "clear": "Tyhjennä",
    "error": "Virhe",
    "zoomTo": "Tarkenna kohteeseen",
    "attribute": "Ominaisuustieto",
    "exports": "Vie",
    "check": "Valitse",
    "save": "Tallenna",
    "close": "Sulje",
    "deleteText": "Poista",
    "map": "Kartta",
    "scene": "Maisema",
    "reset": "Palauta",
    "icon": "Kuvake",
    "folder": "Kansio",
    "share": "Jaa",
    "view": "Näytä",
    "newText": "Uusi",
    "edit": "Muokkaa",
    "wkid": "WKID",
    "table": "Taulukko",
    "zoomIn": "Lähennä",
    "zoomOut": "Loitonna",
    "continue1": "Jatka",
    "longitude": "Pituusaste",
    "latitude": "Leveysaste",
    "custom": "Mukautettu",
    "image": "Kuva",
    "font": "Fontti",
    "text": "Teksti",
    "all": "Kaikki",
    "number": "Numero",
    "percentage": "Prosenttiosuus",
    "unit": "Yksikkö",
    "thousand": "Tuhannet",
    "billion": "Miljardit",
    "million": "Miljoonat",
    "none": "Ei mitään",
    "field": "Kenttä",
    "operation": "Toiminto",
    "disableUpdateGeometry": "Poista käytöstä geometrian päivitys",
    "preview": "Esikatselu"
  },
  "errorCode": "Koodi",
  "errorMessage": "Viesti",
  "errorDetail": "Yksityiskohta",
  "widgetPlaceholderTooltip": "Kun haluat asettaa tähän pienoisohjelman, mene Pienoisohjelmat-välilehdelle ja napsauta vastaavaa paikkamerkkiä",
  "fieldStatistics": {
    "selectField": "Valitse kenttä",
    "statistics": "Tilastotiedot",
    "field": "Kenttä",
    "count": "Arvojen määrä",
    "sum": "Arvojen summa",
    "min": "Minimi",
    "max": "Maksimi",
    "ave": "Keskiarvo",
    "stddev": "Keskihajonta"
  },
  "symbolChooser": {
    "preview": "Esikatselu",
    "basic": "Perus",
    "arrows": "Nuolet",
    "business": "Yritystoiminta",
    "cartographic": "Kartografinen",
    "nationalParkService": "Kansallispuisto",
    "outdoorRecreation": "Virkistysalue",
    "peoplePlaces": "Ihmiset ja paikat",
    "safetyHealth": "Turv., terveys",
    "shapes": "Muodot",
    "transportation": "Kuljetus",
    "symbolSize": "Symbolin koko",
    "color": "Väri",
    "alpha": "Alfa",
    "outlineColor": "Reunaviivan väri",
    "outlineWidth": "Ääriviivan leveys",
    "style": "Tyyli",
    "width": "Leveys",
    "text": "Teksti",
    "fontColor": "Fontin väri",
    "fontSize": "Fontin koko",
    "transparency": "Läpinäkyvyys",
    "solid": "Yhtenäinen",
    "dash": "Viiva",
    "dot": "Piste",
    "dashDot": "Viiva-piste",
    "dashDotDot": "Viiva-piste-piste",
    "customImage": "Mukautettu kuva",
    "chooseFile": "Valitse tiedosto",
    "noFileChoosen": "Tiedostoa ei ole valittu."
  },
  "transparency": {
    "opaque": "Läpinäkymätön",
    "transparent": "Läpinäkyvä"
  },
  "rendererChooser": {
    "domain": "Arvoalue",
    "use": "Käytä",
    "singleSymbol": "Yksi symboli",
    "uniqueSymbol": "Yksilölliset symbolit",
    "color": "Väri",
    "size": "Koko",
    "toShow": "Näyttäminen",
    "colors": "Värit",
    "classes": "Luokkaa",
    "symbolSize": "Symbolin koko",
    "addValue": "Lisää arvo",
    "setDefaultSymbol": "Aseta oletussymboli",
    "defaultSymbol": "Oletussymboli",
    "selectedSymbol": "Valittu symboli",
    "value": "Arvo",
    "label": "Tunnusteksti",
    "range": "Vaihteluväli"
  },
  "drawBox": {
    "point": "Piste",
    "line": "Viiva",
    "polyline": "Taiteviiva",
    "freehandPolyline": "Viivan piirto vapaalla kädellä",
    "triangle": "Kolmio",
    "extent": "Laajuus",
    "circle": "Ympyrä",
    "ellipse": "Ellipsi",
    "polygon": "Alue",
    "freehandPolygon": "Alueen piirto vapaalla kädellä",
    "text": "Teksti",
    "clear": "Tyhjennä"
  },
  "popupConfig": {
    "title": "Otsikko",
    "add": "Lisää",
    "fields": "Kentät",
    "noField": "Ei kenttää",
    "visibility": "Näkyvä",
    "name": "Nimi",
    "alias": "Alias",
    "actions": "Toimet"
  },
  "includeButton": {
    "include": "Sisällytä"
  },
  "loadingShelter": {
    "loading": "Ladataan"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Palvelua ei löytynyt.",
    "unableConnectTo": "Yhteyttä kohteeseen ei voi muodostaa.",
    "invalidUrlTip": "Syötetty URL on virheellinen, tai se ei ole käytettävissä."
  },
  "serviceBrowser": {
    "noGpFound": "Geoprosessointipalvelua ei löytynyt.",
    "unableConnectTo": "Yhteyttä kohteeseen ei voi muodostaa"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Karttapalvelua tai kohdepalvelua ei löytynyt.",
    "unableConnectTo": "Yhteyttä kohteeseen ei voi muodostaa"
  },
  "basicServiceChooser": {
    "validate": "Vahvista",
    "example": "Esimerkki",
    "set": "Aseta"
  },
  "urlInput": {
    "invalidUrl": "Virheellinen URL-osoite."
  },
  "urlComboBox": {
    "invalidUrl": "Virheellinen URL-osoite."
  },
  "filterBuilder": {
    "addAnotherExpression": "Lisää lauseke",
    "addSet": "Lisää sarja",
    "matchMsg": "Nouda sellaiset karttatason kohteet, jotka vastaavat ${any_or_all} seuraavia ehtolausekkeita",
    "matchMsgSet": "${any_or_all} seuraavista ehtolausekkeista ovat tosia",
    "all": "Kaikki",
    "any": "Mikä tahansa",
    "value": "Arvo",
    "field": "Kenttä",
    "unique": "Yksilöllinen",
    "none": "Ei mitään",
    "and": "ja",
    "valueTooltip": "Syötä arvo",
    "fieldTooltip": "Poimi olemassa olevasta kentästä",
    "uniqueValueTooltip": "Poimi valitun kentän yksilöllisistä arvoista",
    "stringOperatorIs": "on",
    "stringOperatorIsNot": "ei ole",
    "stringOperatorStartsWith": "alkaa merkillä",
    "stringOperatorEndsWith": "päättyy merkkiin",
    "stringOperatorContains": "sisältää",
    "stringOperatorDoesNotContain": "ei sisällä",
    "stringOperatorIsBlank": "on tyhjä",
    "stringOperatorIsNotBlank": "ei ole tyhjä",
    "dateOperatorIsOn": "on päällä",
    "dateOperatorIsNotOn": "ei ole päällä",
    "dateOperatorIsBefore": "on ennen",
    "dateOperatorIsAfter": "on jälkeen",
    "dateOperatorIsOnOrBefore": "on sama tai ennen",
    "dateOperatorIsOnOrAfter": "on sama tai jälkeen",
    "dateOperatorMinutes": "minuuttia",
    "dateOperatorHours": "tuntia",
    "dateOperatorDays": "päivää",
    "dateOperatorWeeks": "viikkoa",
    "dateOperatorMonths": "kuukautta",
    "dateOperatorYears": "vuotta",
    "dateOperatorInTheLast": "viimeisessä",
    "dateOperatorNotInTheLast": "ei viimeisessä",
    "dateOperatorIsBetween": "on välillä",
    "dateOperatorIsNotBetween": "ei ole välillä",
    "dateOperatorIsBlank": "on tyhjä",
    "dateOperatorIsNotBlank": "ei ole tyhjä",
    "numberOperatorIs": "on",
    "numberOperatorIsNot": "ei ole",
    "numberOperatorIsAtLeast": "on vähintään",
    "numberOperatorIsLessThan": "on vähemmän kuin",
    "numberOperatorIsAtMost": "on enintään",
    "numberOperatorIsGreaterThan": "on suurempi kuin",
    "numberOperatorIsBetween": "on välillä",
    "numberOperatorIsNotBetween": "ei ole välillä",
    "numberOperatorIsBlank": "on tyhjä",
    "numberOperatorIsNotBlank": "ei ole tyhjä",
    "string": "Merkkijono",
    "number": "Numero",
    "date": "Päivämäärä",
    "askForValues": "Pyydä arvoja",
    "prompt": "Kehote",
    "hint": "Vihje",
    "error": {
      "invalidParams": "Virheelliset parametrit.",
      "invalidUrl": "Virheellinen URL-osoite.",
      "noFilterFields": "Karttatasossa ei ole suodattimien luontiin soveltuvia kenttiä.",
      "invalidSQL": "Virheellinen SQL-lauseke.",
      "cantParseSQL": "SQL-lauseketta ei voi jäsentää."
    },
    "caseSensitive": "Kirjainkoolla on merkitystä",
    "notSupportCaseSensitiveTip": "Isännöidyt palvelut eivät tue kirjainkoon tunnistavaa kyselyä.",
    "setFilterTip": "Määritä suodattimet oikein.",
    "listValues": "Luettelon arvot",
    "cascadeFilterTip": "Näytä vain aiempien lausekkeiden suodattamat arvot.",
    "noneCascadeFilterTip": "Kaikki tämän kentän yksilölliset arvot",
    "previousCascadeFilterTip": "Aiempien lausekkeiden suodattamat arvot",
    "allCascadeFilterTip": "Kaikkien muiden lausekkeiden suodattamat arvot"
  },
  "featureLayerSource": {
    "layer": "Karttataso",
    "browse": "Selaa",
    "selectFromMap": "Kartta",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "Palvelun URL",
    "inputLayerUrl": "Lähtöaineiston karttatason URL-osoite",
    "selectLayer": "Valitse kohteen karttataso nykyisestä kartasta.",
    "chooseItem": "Valitse kohteen karttataso",
    "setServiceUrl": "Anna kohdepalvelun tai karttapalvelun URL-osoite.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Valitse kohdekarttataso."
  },
  "queryableLayerSource": {
    "layer": "Karttataso",
    "browse": "Selaa",
    "selectFromMap": "Kartta",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "Palvelun URL",
    "inputLayerUrl": "Lähtöaineiston karttatason URL-osoite",
    "selectLayer": "Valitse karttataso nykyisestä kartasta.",
    "chooseItem": "Valitse kohde.",
    "setServiceUrl": "Anna palvelun URL-osoite.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Valitse karttataso."
  },
  "gpSource": {
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "Palvelun URL",
    "selectFromOnline": "ArcGIS Online",
    "setServiceUrl": "Anna geoprosessointipalvelun URL-osoite.",
    "chooseItem": "Valitse geoprosessointipalvelun kohde.",
    "chooseTask": "Valitse geoprosessointipalvelun tehtävä."
  },
  "itemSelector": {
    "map": "Kartta",
    "selectWebMap": "Valitse Web-kartta",
    "addMapFromOnlineOrPortal": "Etsi ja lisää sovelluksen Web-kartta ArcGIS Onlinen julkisista lähteistä tai ArcGIS Onlinen tai portaalin yksityisestä sisällöstäsi.",
    "searchMapName": "Hae kartan nimellä...",
    "searchNone": "Emme löytäneet etsimääsi. Kokeile uudelleen.",
    "groups": "Ryhmät",
    "noneGroups": "Ei ryhmiä",
    "signInTip": "Istuntosi on vanhentunut. Päivitä selain ja kirjaudu uudelleen portaaliin.",
    "signIn": "Kirjaudu sisään",
    "publicMap": "Julkinen",
    "myOrganization": "Organisaationi",
    "myGroup": "Omat ryhmät",
    "myContent": "Oma sisältö",
    "count": "Lukumäärä",
    "fromPortal": "Portaalista",
    "fromOnline": "ArcGIS.comista",
    "noneThumbnail": "Pienkuvake ei ole käytettävissä",
    "owner": "omistaja",
    "signInTo": "Kirjaudu palveluun",
    "lastModified": "Viimeksi muokattu",
    "moreDetails": "Lisää tietoja",
    "mostRecent": "Uusin",
    "mostViewed": "Tarkastelluin",
    "highestRated": "Parhaan arvion saanut",
    "viewItemDetails": "Näytä kohteen yksityiskohdat"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Palvelu ei tue kyselyä."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Kartassa ei ole käytettävissä soveltuvaa karttatasoa."
  },
  "layerInfosMenu": {
    "titleBasemap": "Taustakartat",
    "titleLayers": "Toiminnalliset karttatasot",
    "labelLayer": "Karttatason nimi",
    "itemZoomTo": "Tarkenna kohteeseen",
    "itemTransparency": "Läpinäkyvyys",
    "itemTransparent": "Läpinäkyvä",
    "itemOpaque": "Läpinäkymätön",
    "itemMoveUp": "Siirrä ylös",
    "itemMoveDown": "Siirrä alas",
    "itemDesc": "Kuvaus",
    "itemDownload": "Lataa",
    "itemToAttributeTable": "Näytä ominaisuustaulukossa"
  },
  "imageChooser": {
    "unsupportReaderAPI": "Tehtävä: selain ei tue tiedoston lukuohjelman ohjelmointirajapintaa",
    "readError": "Tiedoston luku epäonnistui.",
    "unknowError": "toimintoja ei voi suorittaa loppuun",
    "invalidType": "Invalid file type.",
    "cropImage": "Rajaa kuva",
    "exceed": "Tiedoston koko ei saa ylittää 1024 kt",
    "enableFlash": "Ota käyttöön Adobe Flash ennen kuvaan selaamista.",
    "cropWaining": "Valitse valokuva, joka on kooltaan vähintään ${width} x ${height} pikseliä.",
    "toolTip": "Parhaan tuloksen saamiseksi kuvan tulisi olla leveydeltään ${width} pikseliä ja korkeudeltaan ${height} pikseliä. Muut koot säädetään sopivaksi. Hyväksyttyjä kuvamuotoja ovat PNG, GIF ja JPEG."
  },
  "simpleTable": {
    "moveUp": "Siirrä ylös",
    "moveDown": "Siirrä alas",
    "deleteRow": "Poista",
    "edit": "Muokkaa"
  },
  "urlParams": {
    "invalidToken": "Virheellinen tunnus",
    "validateTokenError": "Virheellinen tunnus tai verkkovirhe"
  },
  "exportTo": {
    "exportTo": "Vie",
    "toCSV": "Vie CSV-tiedostoksi",
    "toFeatureCollection": "Vie kohdekokoelmaan",
    "toGeoJSON": "Vie GeoJSON-muotoon"
  },
  "appState": {
    "title": "Sovelluksen tila",
    "restoreMap": "Palauta karttalaajuus ja karttatasojen näkyvyys tilaan, jossa ne olivat alun perin."
  },
  "featureActions": {
    "featureActions": "Kohdetoiminnot",
    "ZoomTo": "Tarkenna kohteeseen",
    "PanTo": "Vieritä kohteeseen",
    "Flash": "Väläytä",
    "ShowPopup": "Näytä ponnahdusikkuna",
    "CreateLayer": "Luo karttataso",
    "ShowStatistics": "Tilastotiedot...",
    "ClearSelection": "Tyhjennä valinnat",
    "ExportToCSV": "Vie CSV-tiedostoksi",
    "ShowSelectedFeature": "Näytä valitut kohteet",
    "ExportToFeatureCollection": "Vie kohdekokoelmaan",
    "ExportToGeoJSON": "Vie GeoJSON-muotoon",
    "EditAttributes": "Muokkaa ominaisuuksia",
    "AddMarker": "Lisää merkintä",
    "RemoveMarker": "Poista merkintä",
    "SaveToMyContent": "Tallenna omaan sisältöön"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Liittyvä karttataso",
    "selectedFeatures": "Käytä valittuja kohteita",
    "drawShapesTip": "Valitse kohteita piirtämällä muotoja",
    "pleaseDrawShapesTip": "Valitse kohteita piirtämällä muotoja",
    "allFeaturesTip": "Kaikki karttatason kohteet",
    "selectFeaturesOrDrawShapesTip": "Käytä valikoituja tämän karttatason kohteita tai piirrä kartalle muotoja kohteiden rajaamiseksi."
  },
  "searchDistance": {
    "applySearchDistance": "Käytä hakuetäisyyttä",
    "applySearchDistanceToFeatures": "Käytä hakuetäisyyttä valittuihin kohteisiin"
  },
  "units": {
    "miles": "Mailia",
    "milesAbbr": "mailia",
    "kilometers": "Kilometriä",
    "kilometersAbbr": "km",
    "feet": "Jalkaa",
    "feetAbbr": "ft",
    "meters": "Metriä",
    "metersAbbr": "m",
    "yards": "Jaardia",
    "yardsAbbr": "yd",
    "acres": "Eekkeriä",
    "acresAbbr": "eekkeriä",
    "nauticalMiles": "Meripeninkulmaa",
    "nauticalMilesAbbr": "nmi",
    "uSSurveyFeet": "jalkaa (US Survey)",
    "uSSurveyFeetAbbr": "jalkaa (US)",
    "decimalDegree": "Desimaaliasteet",
    "decimalDegreeAbbr": "pp",
    "degreeMinuteSeconds": "Astetta minuuttia sekuntia",
    "degreeMinuteSecondsAbbr": "a-m-s",
    "squareMiles": "Neliömailia",
    "squareMilesAbbr": "mi2",
    "squareKilometer": "Neliökilometriä",
    "squareKilometerAbbr": "km2",
    "squareFeet": "Neliöjalkaa",
    "squareFeetAbbr": "ft2",
    "squareMeters": "Neliömetriä",
    "squareMetersAbbr": "m2",
    "squareYards": "Neliöjaardia",
    "squareYardsAbbr": "yd2",
    "squareUSSurveyFeet": "neliöjalkaa (US Survey)",
    "squareUSSurveyFeetAbbr": "neliöjalkaa (US)"
  },
  "featureSetChooser": {
    "select": "Valitse",
    "dragBox": "Vedä",
    "dragMouse": "Vedä hiirellä",
    "selectByRectangle": "Valitse suorakulmiolla",
    "selectFeaturesTip": "Valitse kohteet vetämällä ruutu niiden ympärille kartalle",
    "newSelectionTip": "Luo uusi valinta",
    "addSelectionTip": "Lisää valinta",
    "removeSelectionTip": "Remove from selection",
    "selectFromCurrentSelectionTip": "Valitse nykyisestä valinnasta",
    "unselectAllSelectionTip": "Poista kaikkien tällä hetkellä valittujen kohteiden valinta",
    "selectByPolygon": "Valitse alueella",
    "selectByCircle": "Valitse ympyrällä",
    "selectByLine": "Valitse viivalla",
    "chooseSelectingTools": "Valitse valintatyökalut",
    "darw": "Piirrä",
    "drawShap": "Piirrä muoto"
  },
  "widgetManager": {
    "createWidgetError": "Pienoisohjelman luontivirhe",
    "createWidgetSettingPageError": "Pienoisohjelman asetussivun luontivirhe",
    "loadWidgetResourceError": "Pienoisohjelman resurssin latausvirhe"
  },
  "shareOptions": {
    "shareMap": "Valitse, ketkä voivat tarkastella tätä sovellusta",
    "shareMapTips": "Sovelluksesi on jaettu näiden ihmisten kanssa",
    "everyone": "Jokainen",
    "theseGroups": "Nämä ryhmät"
  },
  "shareLink": {
    "email": "sähköposti",
    "shareEmail": "Sähköposti",
    "facebook": "facebook",
    "shareFacebook": "Facebook",
    "twitter": "twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "Upota tämä sovellus Web-sivustoon",
    "shareEmailSubject": "Web-sovelluksen jakaminen:",
    "shareEmailTxt1": "Tässä on web-sovellus, joka jaetaan kanssasi käyttämällä Web AppBuilder for ArcGIS -sovellusta.",
    "shareEmailTxt2": "Voit luoda ja jakaa oman web-sovelluksesi Esri Web AppBuilder for ArcGIS -sovelluksella.",
    "shareEmailTxt3": "Saat lisätietoja osoitteesta http://www.esri.com/software/web-appbuilder.",
    "smallSize": "Pieni",
    "mediumSize": "Keskisuuri",
    "largeSize": "Suuri",
    "customSize": "Virhe yhteyden muodostuksessa taustakarttapalveluun. Varmista, että SSL (HTTPS) -suojaus on käytössä palvelussa. Mahdolliset lisätiedot näkyvät alla.",
    "embed": "Upota tämä sovellus Web-sivustoon",
    "more": "Upotusasetukset",
    "changeShareSettings": "Muuta jakamisasetuksia",
    "shareLinkText": "Jaa linkki tähän sovellukseen",
    "linkOptions": "Linkkiasetukset",
    "linkOptionsUrlParameters": "Valitse linkkiin sisältyvät URL-parametrit",
    "currentMapExtent": "Nykyinen kartan laajuus",
    "chooseCenterWithLevel": "Määritä kartan keskikohta zoomaustasolla napsauttamalla karttaa",
    "chooseCenterWithScale": "Määritä kartan keskikohta kartan mittakaavalla napsauttamalla karttaa",
    "findLocation": "Etsi sijainti tai kohde ja tarkenna siihen",
    "findLocation_inputPlaceholder": "Paikkasi tai kohteesi",
    "queryFeature": "Tee kysely kohteesta ja tarkenna siihen",
    "addMarker": "Lisää merkitsin karttaan",
    "addMarker_titlePlaceholder": "Merkitsimen ponnahdusikkunan otsikko",
    "addMarker_symbolURL": "Merkitsinsymbolin URL-osoite",
    "addMarker_label": "Merkitsimen selite",
    "popupTitle": "Popup-otsikko",
    "zoomLevel": "Zoomaustaso",
    "overwirteMobileLayout": "Korvaa mobiiliasettelun oletusnäyttökoko",
    "language": "Aseta sovelluksen näyttökieli",
    "auth": "Todenna käyttäjä automaattisesti",
    "linkPreview": "Linkin esikatselu",
    "useShortenLink": "Lyhyt linkki",
    "shareMapUrlExtent": "Jaa nykyisen kartan laajuus",
    "shareToWebTips": "Tätä sovellusta ei jaeta julkisesti. Ihmiset eivät ehkä voi katsella sitä."
  },
  "webSceneLoader": {
    "webglSupportTip": "Selaimesi ei tue 3D-web-sovelluksia."
  },
  "map": {
    "basemapNotAvailable": "Taustakartta ei ole käytettävissä.",
    "displayDefaultBasemap": "Näytetään oletustaustakartta sen sijaan.",
    "layerLoadedError": "Karttatasoa ${layers} ei voi lisätä karttaan."
  },
  "popup": {
    "relatedTables": "Liittyvät taulut:",
    "relatedRecords": "Liittyvät tietueet:",
    "noRelatedRecotds": "Liittyviä tietueita ei löytynyt.",
    "chooseFieldTip": "Tuo luettelo näkyviin valitsemalla ominaisuustieto",
    "saveAsPopupTitle": "Vastaa ponnahdusikkunan otsikkoa"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "Valinnassa on liikaa kohteita. Niiden noutaminen ja näyttäminen kartalla voi kestää kauan.",
    "askForContinue": "Haluatko jatkaa?"
  },
  "colorPalette": {
    "transparent": "Läpinäkyvä",
    "custom": "Mukautettu"
  },
  "temperature": {
    "celsius": "Celsius",
    "fahrenheit": "Fahrenheit"
  },
  "report": {
    "printButtonLabel": "Tulosta",
    "reportDimensionsMsg": "Tämä raportti on suunniteltu koon ${paperSize} paperille tulostamista varten",
    "unableToPrintMapMsg": "On ilmennyt virhe tulostettaessa karttaa tai karttoja.",
    "notesHint": "Kirjoita kommentit tähän",
    "landscape": "Maisema",
    "portrait": "Pysty",
    "mapOnly": "MAP_ONLY",
    "a0": "A0",
    "a1": "A1",
    "a2": "A2",
    "a3": "A3",
    "a4": "A4",
    "a5": "A5",
    "letterANSIA": "Letter ANSI A",
    "tabloidANSIB": "Tabloid ANSI B",
    "letter": "Letter",
    "legal": "Legal",
    "tabloid": "Tabloidi",
    "ansi_a": "ANSI A",
    "ansi_b": "ANSI B",
    "ansi_c": "ANSI C",
    "ansi_d": "ANSI D",
    "ansi_e": "ANSI E"
  },
  "snapshot": {
    "snapshot_complete": "Tilannevedoksen luonti onnistui.",
    "snapshot_failed": "Tilannevedoksen luonti epäonnistui.",
    "snapshot_append": "Tilannevedos",
    "utc": "UTC"
  },
  "statisticsChart": {
    "enlarge": "Laajenna",
    "setting": "Asetus",
    "count": "Lukumäärä",
    "horizontalAxis": "Vaaka-akseli",
    "verticalAxis": "Pystyakseli",
    "dataLabels": "Aineiston tunnustekstit",
    "color": "Väri"
  },
  "frameworkDatasource": {
    "setDataSource": "Määritä aineistolähde",
    "customDataSource": "Ylimääräinen aineistolähde",
    "selectCustomDataTip": "Valitse aineistolähde tästä sovelluksesta.",
    "widgetOutputs": "Pienoisohjelman tulosteet",
    "noExtraDsAvailable": "Ylimääräisiä tietolähteitä ei ole saatavissa.",
    "addExtraDsTip": "Siirry luontitoiminnon Ominaisuustieto-välilehteen ja lisää tietoja napsauttamalla ylimääräistä aineistolähdettä.",
    "widgetOutpusListTip": "Tässä luetellaan myös pienoisohjelman (mahdolliset) tulosaineistot."
  },
  "gridLayout": {
    "addWidgetTip": "Lisää pienoisohjelmat tähän Pienoisohjelma-välilehden kautta",
    "modifyLayout": "Muokkaa asettelua",
    "dragToAdd": "Lisää vetämällä",
    "mapArea": "KARTTA-ALUE"
  },
  "noEditPrivileges": "Tililläsi ei ole tietojen luonti- tai muokkausoikeuksia.",
  "invalidConfiguration": "Pienoisohjelmaa ei ole joko määritetty tai määrityksen karttatasoja ei ole enää kartassa. Avaa sovellus luontitilassa ja määritä pienoisohjelma uudelleen."
});