define({
  "_widgetLabel": "Seznam vrstev",
  "titleBasemap": "Podkladové mapy",
  "titleLayers": "Operační vrstvy",
  "labelLayer": "Jméno vrstvy",
  "itemZoomTo": "Přiblížit na",
  "itemTransparency": "Průhlednost",
  "itemTransparent": "Průhledná",
  "itemOpaque": "Neprůhledná",
  "itemMoveUp": "Přesunout nahoru",
  "itemMoveDown": "Přesunout dolů",
  "itemDesc": "Popis",
  "itemDownload": "Stáhnout",
  "itemToAttributeTable": "Zobrazit v atributové tabulce",
  "itemShowItemDetails": "Ukázat podrobnosti položky",
  "empty": "prázdné",
  "removePopup": "Zakázat vyskakovací okno",
  "enablePopup": "Povolit vyskakovací okno",
  "turnAllLayersOff": "Vypnout všechny vrstvy",
  "turnAllLayersOn": "Zapnout všechny vrstvy",
  "expandAllLayers": "Rozbalit všechny vrstvy",
  "collapseAlllayers": "Sbalit všechny vrstvy",
  "turnAllLabelsOff": "Vypnout všechny popisky",
  "turnAllLabelsOn": "Zapnout všechny popisky",
  "showLabels": "Zobrazit popisky",
  "hideLables": "Skrýt popisky"
});