define({
  "_widgetLabel": "Seznam slojev",
  "titleBasemap": "Temeljne karte",
  "titleLayers": "Operativni sloji",
  "labelLayer": "Ime sloja",
  "itemZoomTo": "Približaj na",
  "itemTransparency": "Prosojnost",
  "itemTransparent": "Prozorno",
  "itemOpaque": "Neprosojno",
  "itemMoveUp": "Premakni gor",
  "itemMoveDown": "Premakni dol",
  "itemDesc": "Opis",
  "itemDownload": "Prenesi",
  "itemToAttributeTable": "Poglej v atributni tabeli",
  "itemShowItemDetails": "Prikazujem podrobnosti elementa",
  "empty": "prazno",
  "removePopup": "Onemogoči pojavno okno",
  "enablePopup": "Omogoči pojavno okno",
  "turnAllLayersOff": "Izklopi vse sloje",
  "turnAllLayersOn": "Vklopi vse sloje",
  "expandAllLayers": "Razširi vse sloje",
  "collapseAlllayers": "Strni vse sloje",
  "turnAllLabelsOff": "Izklopi vse napise",
  "turnAllLabelsOn": "Vklopi vse napise",
  "showLabels": "Pokaži napise",
  "hideLables": "Skrij napise"
});