define({
  "instruction": "מסך הפתיחה מופיע לפני שניתן לגשת ליישום.",
  "defaultContent": "הוסף טקסט, קישורים וגרפיקות קטנות כאן.",
  "requireConfirm": "דרוש אישור כדי להמשיך",
  "noRequireConfirm": "אל תדרוש אישור כדי להמשיך",
  "optionText": "אפשרות עבור המשתמש להפוך את מסך הפתיחה ללא פעיל באתחול האפליקציה.",
  "confirmLabel": "טקסטים של אישור: ",
  "confirmLabelColor": "צבע טקסטים לאישור",
  "defaultConfirmText": "אני מסכים לתנאים ולהתניות המצוינים לעיל",
  "confirmOption": "הצג את מסך הפתיחה בכל פתיחה של האפליקציה",
  "backgroundColor": "צבע רקע",
  "content": "תוכן",
  "contentDescription": "הגדר את התוכן שמוצג במסך הפתיחה.",
  "appearance": "הופעה",
  "appearanceDescription": "הגדר את ההופעה של מסך הפתיחה.",
  "size": "גודל",
  "width": "רוחב",
  "height": "גובה",
  "custom": "מותאם",
  "background": "רקע",
  "colorFill": "מילוי צבע",
  "imageFill": "מילוי תמונה",
  "chooseFile": "בחר קובץ",
  "noFileChosen": "לא נבחר קובץ",
  "transparency": "שקיפות",
  "sizeFill": "מילוי",
  "sizeFit": "מותאם",
  "sizeStretch": "מתח עד למילוי",
  "sizeCenter": "מרכז",
  "sizeTile": "אריח",
  "buttonColor": "צבע לחצן",
  "buttonText": "טקסט לחצן",
  "buttonTextColor": "צבע טקסט לחצן",
  "contentAlign": "יישור תוכן",
  "alignTop": "עליון",
  "alignMiddle": "אמצע",
  "maskColor": "צבע מיסוך",
  "options": "אפשרויות",
  "optionsDescription": "הגדר את ההתנהגות של מסך הפתיחה."
});