define({
  "_widgetLabel": "Koordinatė",
  "hintMessage": "Spustelėkite žemėlapį, kad gautumėte koordinates",
  "defaultLabel": "Numatytasis",
  "realtimeLabel": "Norėdami gauti koordinates, perstumkite pelę",
  "computing": "Skaičiuojama...",
  "latitudeLabel": "Platuma",
  "longitudeLabel": "Ilguma",
  "loading": "įkeliama...",
  "enableClick": "Paspauskite, kad įjungtumėte žemėlapio paspaudimą koordinatėms gauti",
  "disableClick": "Paspauskite, kad išjungtumėte žemėlapio paspaudimą koordinatėms gauti",
  "Default": "Numatytasis",
  "Inches": "Coliai",
  "Foot": "Pėdos",
  "Yards": "Jardai",
  "Miles": "Mylios",
  "Nautical_Miles": "Jūrmylės",
  "Millimeters": "Milimetrai",
  "Centimeters": "Centimetrai",
  "Meter": "Metrai",
  "Kilometers": "Kilometrai",
  "Decimeters": "Decimetrai",
  "Decimal_Degrees": "Laipsniai",
  "Degree_Minutes_Seconds": "Laipsniai minutės sekundės",
  "MGRS": "MGRS",
  "USNG": "USNG"
});