define(
   ({
    _widgetLabel: "Tabela de Atributos",
    ok: "OK",
    cancel: "Cancelar",
    unsupportQueryWarning: "A camada precisa suportar a operação de consulta para aparecer no widget da Tabela de Atributo. Certifique-se que o recurso de consulta no serviço está ativado.",
    exportMessage: "Exportar dados para arquivo CSV?",
    exportFiles: "Exportar para CSV",
    exportSelected: "Exportar Selecionado para CSV",
    exportAll: "Exportar Todos para CSV",
    options: "Opções",
    zoomto: "Zoom para",
    highlight: "Destacar Gráficos",
    selectAll: "Selecionar Registros em Todas as Páginas",
    selectPage: "Selecionar Registros na Página Atual",
    clearSelection: "Limpar Seleção",
    filter: "Filtro",
    setFilterTip: "Configure o filtro corretamente.",
    noFilterTip: "Sem expressão de filtro definida, esta tarefa de consulta listará todas as feições na fonte de dados especificada.",
    filterByExtent: "Fltrar por Extensão do Mapa",
    showSelectedRecords: "Mostrar Registros Selecionados",
    showAllRecords: "Mostrar Todos os Registros",
    showRelatedRecords: "Mostrar Registros Relacionados",
    noRelatedRecords: "Nenhum Registro Relacionado",
    refresh: "Atualizar",
    features: "recursos",
    selected: "selecionado",
    transparent: "Modo Transparente",
    indicate: "Localizar Seleção",
    columns: "Mostrar/Ocultar Colunas",
    selectionSymbol: "Seleção de Símbolo",
    closeMessage: "Ocultar Tabela (expada novamente na parte inferior)",
    dataNotAvailable: "Dados não disponíveis!<br>Clique no botão [Atualizar] para tentar noamente.",
    openTableTip: "Abrir Tabela de Atributo",
    closeTableTip: "Ocultar Tabela de Atributos"
  })
);