define({
  "_widgetLabel": "Tabela de Atributos",
  "_featureAction_ShowRelatedRecords": "Mostrar registros relacionados",
  "_featureAction_ViewInTable": "Visualizar na Tabela de Atributos",
  "ok": "OK",
  "cancel": "Cancelar",
  "unsupportQueryWarning": "A camada precisa suportar a operação de consulta para aparecer no widget da Tabela de Atributo. Certifique-se que o recurso de consulta no serviço está ativado.",
  "exportMessage": "Exportar dados para arquivo CSV?",
  "exportFiles": "Exportar para CSV",
  "exportSelected": "Exportar selecionado para CSV",
  "exportAll": "Exportar todos para CSV",
  "options": "Opções",
  "zoomto": "Zoom para",
  "highlight": "Destacar gráficos",
  "selectAll": "Selecionar registros em todas as páginas",
  "selectPage": "Selecionar registros na página atual",
  "clearSelection": "Limpar seleção",
  "filter": "Filtro",
  "setFilterTip": "Configure o filtro corretamente.",
  "noFilterTip": "Sem expressões de filtro definidas, esta tarefa de consulta listará todas as feições na fonte de dados especificada.",
  "filterByExtent": "Filtrar por extensão de mapa",
  "showSelectedRecords": "Mostrar registros selecionados",
  "showAllRecords": "Mostrar todos os registros",
  "showRelatedRecords": "Mostrar registros relacionados",
  "noRelatedRecords": "Nenhum registro relacionado encontrado",
  "attachmentColumn": "Fotos e arquivos",
  "refresh": "Atualizar",
  "features": "recursos",
  "records": "registros",
  "selected": "selecionado",
  "transparent": "Modo transparente",
  "indicate": "Seleção de local",
  "columns": "Mostrar/Ocultar colunas",
  "selectionSymbol": "Símbolo de seleção",
  "closeMessage": "Ocultar tabela (expanda novamente da parte inferior)",
  "dataNotAvailable": "Dados não disponíveis!<br>Clique no botão [Atualizar] para tentar noamente.",
  "openTableTip": "Abrir Tabela de Atributo",
  "closeTableTip": "Ocultar Tabela de Atributos",
  "sortAsc": "Ordem crescente",
  "sortDes": "Ordem decrescente",
  "statistics": "Estatística",
  "attachments": "Anexos",
  "files": "arquivos"
});