define({
  "instruction": "O ecrã inicial aparece antes de a aplicação estar acessível.",
  "defaultContent": "Adicione texto, ligações e gráficos pequenos para continuar.",
  "requireConfirm": "Requer confirmação para continuar",
  "noRequireConfirm": "Não necessita de confirmação para continuar",
  "optionText": "Opção para o utilizador desactivar o écran splash no arranque da aplicação.",
  "confirmLabel": "Textos de Confirmação: ",
  "confirmLabelColor": "Cor do texto de confirmação",
  "defaultConfirmText": "Concordo com os termos e condições acima descritos",
  "confirmOption": "Exibir este ecrã inicial sempre que a aplicação for iniciada.",
  "backgroundColor": "Cor de Fundo",
  "content": "Conteúdo",
  "contentDescription": "Defina o conteúdo que é exibido no ecrã inicial.",
  "appearance": "Aspeto",
  "appearanceDescription": "Defina a aparência do ecrã inicial.",
  "size": "Dimensão",
  "width": "Largura",
  "height": "Altura",
  "custom": "Personalizar",
  "background": "Fundo",
  "colorFill": "Preenchimento de cor",
  "imageFill": "Preenchimento de imagem",
  "chooseFile": "Escolher ficheiro",
  "noFileChosen": "Nenhum ficheiro escolhido",
  "transparency": "Transparência",
  "sizeFill": "Preenchimento",
  "sizeFit": "Adaptar",
  "sizeStretch": "Esticar para preencher",
  "sizeCenter": "Centrar",
  "sizeTile": "Mosaico",
  "buttonColor": "Cor do botão",
  "buttonText": "Texto do botão",
  "buttonTextColor": "Cor do texto do botão",
  "contentAlign": "Alinhamento de conteúdo",
  "alignTop": "Superior",
  "alignMiddle": "Meio",
  "maskColor": "Cor da máscara",
  "options": "Opções",
  "optionsDescription": "Defina o comportamento do ecrã inicial."
});