define({
  "_widgetLabel": "Coordenada",
  "hintMessage": "Haz clic en el mapa para obtener coordenadas",
  "defaultLabel": "Predeterminado",
  "realtimeLabel": "Mover el ratón para obtener coordenadas",
  "computing": "Calculando...",
  "latitudeLabel": "Latitud",
  "longitudeLabel": "Longitud",
  "loading": "cargando...",
  "enableClick": "Haz clic para habilitar la obtención de coordenadas al hacer clic en el mapa",
  "disableClick": "Haz clic para deshabilitar la obtención de coordenadas al hacer clic en el mapa",
  "Default": "Predeterminado",
  "Inches": "Pulgadas",
  "Foot": "Pies",
  "Yards": "Yardas",
  "Miles": "Millas",
  "Nautical_Miles": "Millas náuticas",
  "Millimeters": "Milímetros",
  "Centimeters": "Centímetros",
  "Meter": "Metros",
  "Kilometers": "Kilómetros",
  "Decimeters": "Decímetros",
  "Decimal_Degrees": "Grados",
  "Degree_Minutes_Seconds": "Grados minutos segundos",
  "MGRS": "MGRS",
  "USNG": "USNG"
});