define({
  "instruction": "选择并配置将首先显示在属性表中的图层。",
  "label": "图层",
  "show": "显示",
  "actions": "配置图层字段",
  "field": "字段",
  "alias": "别名",
  "visible": "可见",
  "linkField": "链接字段",
  "noLayers": "没有可用的要素图层",
  "back": "返回",
  "exportCSV": "允许导出为 CSV",
  "expand": "初始展开微件",
  "filterByExtent": "默认启用按地图范围过滤",
  "restore": "恢复至默认值",
  "ok": "确定",
  "cancel": "取消",
  "includePoint": "在导出的文件中包括点坐标",
  "configureLayerFields": "配置图层字段",
  "result": "已成功保存",
  "warning": "请首先选择“显示”选项。",
  "fieldCheckWarning": "必须至少选择一个字段。",
  "unsupportQueryWarning": "要显示在“属性表”微件中，该图层需要支持查询操作。请确保服务中的查询功能已打开。",
  "unsupportQueryLayers": "要显示在“属性表”微件中，以下图层需要支持查询操作。请确保服务中的查询功能已打开。",
  "fieldName": "名称",
  "fieldAlias": "别名",
  "fieldVisibility": "可见性",
  "fieldActions": "操作",
  "showAttachments": "显示附件"
});