define({
  "common": {
    "apply": "Lietot",
    "ok": "Labi",
    "cancel": "Atcelt",
    "yes": "Jā",
    "no": "Nē",
    "next": "Tālāk",
    "previous": "Iepriekšējais",
    "back": "Atpakaļ",
    "selected": "izvēlēts",
    "name": "Nosaukums",
    "usage": "Lietojums",
    "settings": "Iestatījumi",
    "home": "Sākums",
    "link": "Saite",
    "messages": "Ziņojumi",
    "outputs": "Izvades",
    "title": "Nosaukums",
    "thumbnail": "Sīktēls",
    "url": "URL",
    "actions": "Darbības",
    "layer": "Slānis",
    "action": "Darbība",
    "input": "Ievade",
    "output": "Izvade",
    "type": "Tips",
    "required": "Nepieciešams",
    "options": "Varianti",
    "label": "Kartes teksts",
    "tooltip": "Rīka padoms",
    "visible": "Redzams",
    "symbol": "Simbols",
    "popup": "Uznirstošais logs",
    "upload": "Augšupielāde",
    "execute": "Izpildīt",
    "help": "Palīdzība",
    "executing": "Izpilda",
    "clear": "Notīrīt",
    "error": "Kļūda",
    "zoomTo": "Pietuvināt",
    "attribute": "Atribūts",
    "exports": "Eksportēt",
    "check": "Pārbaudīt",
    "save": "Saglabāt",
    "close": "Aizvērt",
    "deleteText": "Izdzēst",
    "map": "Karte",
    "scene": "Scēna",
    "reset": "Atiestatīt",
    "icon": "Ikona",
    "folder": "Mape",
    "share": "Kopīgot",
    "view": "Skats",
    "newText": "Jaunais",
    "edit": "Rediģēt",
    "wkid": "WKID",
    "table": "Tabula",
    "zoomIn": "Pietuvināt",
    "zoomOut": "Attālināt",
    "continue1": "Turpināt",
    "longitude": "Garums",
    "latitude": "Platums",
    "custom": "Pielāgots",
    "image": "Attēls",
    "font": "Fonts",
    "text": "Teksts",
    "all": "Visi",
    "number": "Numurs",
    "percentage": "Procenti",
    "unit": "Vienība",
    "thousand": "Tūkstoši",
    "billion": "Miljardi",
    "million": "Miljoni",
    "none": "Nav",
    "field": "Lauks",
    "operation": "Operācija",
    "disableUpdateGeometry": "Deaktivizēt ģeometrijas atjaunināšanu",
    "preview": "Priekšskatījums"
  },
  "errorCode": "Kods",
  "errorMessage": "Ziņojums",
  "errorDetail": "Detalizēta informācija",
  "widgetPlaceholderTooltip": "Lai to iestatītu, pārejiet uz sadaļu Logrīki un noklikšķiniet uz atbilstošā viettura",
  "fieldStatistics": {
    "selectField": "Izvēlēties lauku",
    "statistics": "Statistika",
    "field": "Lauks",
    "count": "Vērtību skaits",
    "sum": "Vērtību summa",
    "min": "Minimums",
    "max": "Maksimālais",
    "ave": "Vidējais",
    "stddev": "Standartnovirze"
  },
  "symbolChooser": {
    "preview": "Priekšskatījums",
    "basic": "Pamata",
    "arrows": "Bultiņas",
    "business": "Bizness",
    "cartographic": "Kartogrāfisks",
    "nationalParkService": "Nacionālā parka serviss",
    "outdoorRecreation": "Aktīvā atpūta",
    "peoplePlaces": "Cilvēki, vietas",
    "safetyHealth": "Veselība, drošība",
    "shapes": "Formas",
    "transportation": "Transports",
    "symbolSize": "Simbola izmērs",
    "color": "Krāsa",
    "alpha": "Alfa",
    "outlineColor": "Kontūras krāsa",
    "outlineWidth": "Kontūras platums",
    "style": "Stils",
    "width": "Platums",
    "text": "Teksts",
    "fontColor": "Fonta krāsa",
    "fontSize": "Fonta izmērs",
    "transparency": "Caurspīdīgums",
    "solid": "Tīrtoņa",
    "dash": "Svītra",
    "dot": "Punkts",
    "dashDot": "Svītra, punkts",
    "dashDotDot": "Svītra, punkts, punkts",
    "customImage": "Pielāgots attēls",
    "chooseFile": "Izvēlēties failu",
    "noFileChoosen": "Nav izvēlēts neviens fails."
  },
  "transparency": {
    "opaque": "Necaurredzams",
    "transparent": "Caurspīdīgs"
  },
  "rendererChooser": {
    "domain": "Domēns",
    "use": "Lietot",
    "singleSymbol": "Atsevišķs simbols",
    "uniqueSymbol": "Unikāli simboli",
    "color": "Krāsa",
    "size": "Lielums",
    "toShow": "Lai parādītu",
    "colors": "Krāsas",
    "classes": "Klases",
    "symbolSize": "Simbola izmērs",
    "addValue": "Pievienot vērtību",
    "setDefaultSymbol": "Iestatīt noklusējuma simbolu",
    "defaultSymbol": "Noklusējuma simbols",
    "selectedSymbol": "Izvēlētais simbols",
    "value": "Vērtība",
    "label": "Kartes teksts",
    "range": "Diapazons"
  },
  "drawBox": {
    "point": "Virsotne",
    "line": "Līnija",
    "polyline": "Līnija",
    "freehandPolyline": "Brīvrokas līnija",
    "triangle": "Trīsstūris",
    "extent": "Pārklājums",
    "circle": "Aplis",
    "ellipse": "Elipse",
    "polygon": "Laukums",
    "freehandPolygon": "Brīvrokas laukums",
    "text": "Teksts",
    "clear": "Notīrīt"
  },
  "popupConfig": {
    "title": "Virsraksts",
    "add": "Pievienot",
    "fields": "Lauki",
    "noField": "Nav lauka",
    "visibility": "Redzams",
    "name": "Nosaukums",
    "alias": "Aizstājvārds",
    "actions": "Darbības"
  },
  "includeButton": {
    "include": "Iekļaut"
  },
  "loadingShelter": {
    "loading": "Ielādē"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Nav atrasts neviens serviss.",
    "unableConnectTo": "Nevar izveidot savienojumu ar",
    "invalidUrlTip": "Jūsu ievadītais URL nav derīgs vai tam nevar piekļūt."
  },
  "serviceBrowser": {
    "noGpFound": "Nav atrasts neviens ģeodatu apstrādes serviss.",
    "unableConnectTo": "Nevar izveidot savienojumu ar"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Nav atrasts neviens karšu serviss vai elementu serviss.",
    "unableConnectTo": "Nevar izveidot savienojumu ar"
  },
  "basicServiceChooser": {
    "validate": "Pārbaudīt",
    "example": "Piemērs",
    "set": "Kopa"
  },
  "urlInput": {
    "invalidUrl": "Nederīgs URL."
  },
  "urlComboBox": {
    "invalidUrl": "Nederīgs URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Pievienot izteiksmi",
    "addSet": "Pievienot kopu",
    "matchMsg": "Iegūt slāņa elementus, kas atbilst ${any_or_all} no šādām izteiksmēm",
    "matchMsgSet": "${any_or_all} no šādām izteiksmēm šajā kopā ir patiesi",
    "all": "Visi",
    "any": "Jebkurš",
    "value": "Vērtība",
    "field": "Lauks",
    "unique": "Unikāls",
    "none": "Neviens",
    "and": "un",
    "valueTooltip": "Ievadiet vērtību",
    "fieldTooltip": "Izmeklēt no esošā lauka",
    "uniqueValueTooltip": "Izmeklēt unikālas vērtības no atlasītā lauka",
    "stringOperatorIs": "ir",
    "stringOperatorIsNot": "nav",
    "stringOperatorStartsWith": "sākas ar",
    "stringOperatorEndsWith": "beidzas ar",
    "stringOperatorContains": "ietver",
    "stringOperatorDoesNotContain": "neietver",
    "stringOperatorIsBlank": "ir tukšs",
    "stringOperatorIsNotBlank": "nav tukšs",
    "dateOperatorIsOn": "ir šajā datumā",
    "dateOperatorIsNotOn": "nav šajā datumā",
    "dateOperatorIsBefore": "ir pirms",
    "dateOperatorIsAfter": "ir pēc",
    "dateOperatorIsOnOrBefore": "ir uz vai pirms",
    "dateOperatorIsOnOrAfter": "ir uz vai pēc",
    "dateOperatorMinutes": "minūtes",
    "dateOperatorHours": "stundas",
    "dateOperatorDays": "dienas",
    "dateOperatorWeeks": "nedēļas",
    "dateOperatorMonths": "mēneši",
    "dateOperatorYears": "gadi",
    "dateOperatorInTheLast": "pagātnē",
    "dateOperatorNotInTheLast": "nav pagātnē",
    "dateOperatorIsBetween": "ir starp",
    "dateOperatorIsNotBetween": "nav starp",
    "dateOperatorIsBlank": "ir tukšs",
    "dateOperatorIsNotBlank": "nav tukšs",
    "numberOperatorIs": "ir",
    "numberOperatorIsNot": "nav",
    "numberOperatorIsAtLeast": "ir vismaz",
    "numberOperatorIsLessThan": "ir mazāks nekā",
    "numberOperatorIsAtMost": "ir visvairāk",
    "numberOperatorIsGreaterThan": "ir lielāks nekā",
    "numberOperatorIsBetween": "ir starp",
    "numberOperatorIsNotBetween": "nav starp",
    "numberOperatorIsBlank": "ir tukšs",
    "numberOperatorIsNotBlank": "nav tukšs",
    "string": "Virkne",
    "number": "Skaitlis",
    "date": "Datums",
    "askForValues": "Jautāt vērtības",
    "prompt": "Uzvedne",
    "hint": "Mājiens",
    "error": {
      "invalidParams": "Nederīgi parametri.",
      "invalidUrl": "Nederīgs URL.",
      "noFilterFields": "Slānī nav lauku, ko var izmantot filtru veidošanai.",
      "invalidSQL": "Nederīga SQL izteiksme.",
      "cantParseSQL": "SQL izteiksmi nevar parsēt."
    },
    "caseSensitive": "Reģistrjutīgs",
    "notSupportCaseSensitiveTip": "Viesotie servisi neatbalsta reģistrjutīgu vaicājumu.",
    "setFilterTip": "Lūdzu, pareizi iestatiet filtrus.",
    "listValues": "Vērtību saraksts",
    "cascadeFilterTip": "Rādīt tikai iepriekšējo izteiksmju filtrētās vērtības.",
    "noneCascadeFilterTip": "Visas šī lauka unikālās vērtības",
    "previousCascadeFilterTip": "Iepriekšējo izteiksmju filtrētās vērtības",
    "allCascadeFilterTip": "Visu citu izteiksmju filtrētās vērtības"
  },
  "featureLayerSource": {
    "layer": "Slānis",
    "browse": "Pārlūkot",
    "selectFromMap": "Karte",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "Servisa URL",
    "inputLayerUrl": "Ievadīt slāņa URL",
    "selectLayer": "Izvēlieties elementu slāni no pašreizējās kartes.",
    "chooseItem": "Izvēlieties elementu slāņa vienību.",
    "setServiceUrl": "Ievadiet elementu servisa vai karšu pakalpojuma URL.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Izvēlieties elementu slāni."
  },
  "queryableLayerSource": {
    "layer": "Slānis",
    "browse": "Pārlūks",
    "selectFromMap": "Karte",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "Servisa URL",
    "inputLayerUrl": "Ievadīt slāņa URL",
    "selectLayer": "Atlasiet slāni no pašreizējās kartes.",
    "chooseItem": "Izvēlieties vienumu.",
    "setServiceUrl": "Ievadiet pakalpojuma URL.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "Izvēlieties slāni."
  },
  "gpSource": {
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "Servisa URL",
    "selectFromOnline": "ArcGIS Online",
    "setServiceUrl": "Ievadiet ģeogrāfisko datu apstrādes pakalpojuma vietrādi URL.",
    "chooseItem": "Izvēlieties ģeogrāfisko datu apstrādes pakalpojuma vienumu.",
    "chooseTask": "Izvēlieties ģeogrāfisko datu apstrādes uzdevumu."
  },
  "itemSelector": {
    "map": "Karte",
    "selectWebMap": "Izvēlēties tīmekļa karti",
    "addMapFromOnlineOrPortal": "Atrodiet un pievienojiet web karti aplikācijā no ArcGIS Online publiskajiem resursiem vai sava privātā satura pakalpojumā ArcGIS Online vai Portal.",
    "searchMapName": "Meklēt pēc kartes nosaukuma...",
    "searchNone": "Neizdevās atrast to, ko meklējāt. Mēģiniet vēlreiz.",
    "groups": "Grupas",
    "noneGroups": "Nav grupu",
    "signInTip": "Jūsu pieteikšanās sesija ir beigusies; lai vēlreiz pierakstītos savā portālā, atsvaidziniet pārlūku.",
    "signIn": "Pierakstīties",
    "publicMap": "Publisks",
    "myOrganization": "Organizācija",
    "myGroup": "Manas Grupas",
    "myContent": "Mans saturs",
    "count": "Skaits",
    "fromPortal": "no Portal",
    "fromOnline": "no ArcGIS.com",
    "noneThumbnail": "Sīktēls nav pieejams",
    "owner": "īpašnieks",
    "signInTo": "Pierakstīties",
    "lastModified": "Pēdējo reizi modificēts",
    "moreDetails": "Vairāk detaļu",
    "mostRecent": "Jaunākās izmaiņas",
    "mostViewed": "Visvairāk skatījumu",
    "highestRated": "Augstākais novērtējums",
    "viewItemDetails": "Skatīt detalizētu informāciju par vienumu"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Pakalpojums neatbalsta vaicājumu."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Kartē nav pieejams neviens piemērots slānis."
  },
  "layerInfosMenu": {
    "titleBasemap": "Pamatkartes",
    "titleLayers": "Operacionālie slāņi",
    "labelLayer": "Slāņa nosaukums",
    "itemZoomTo": "Pietuvināt",
    "itemTransparency": "Caurspīdīgums",
    "itemTransparent": "Caurspīdīgs",
    "itemOpaque": "Necaurredzams",
    "itemMoveUp": "Pārvietot uz augšu",
    "itemMoveDown": "Pārvietot uz leju",
    "itemDesc": "Apraksts",
    "itemDownload": "Lejupielāde",
    "itemToAttributeTable": "Skatīt atribūtu tabulā"
  },
  "imageChooser": {
    "unsupportReaderAPI": "Todo: pārlūks neatbalsta faila lasītāja API",
    "readError": "Neizdevās nolasīt failu.",
    "unknowError": "nevar pabeigt darbības",
    "invalidType": "Nederīgs faila tips.",
    "cropImage": "Apgriezt attēlu",
    "exceed": "Faila lielums nedrīkst pārsniegt 1024 KB",
    "enableFlash": "Lai pārlūkotu uz attēlu, aktivizējiet Adobe Flash.",
    "cropWaining": "Lūdzu, izvēlieties fotoattēlu, kura izmēri ir vismaz ${width} x ${height} pikseļi.",
    "toolTip": "Lai sasniegtu labākos rezultātus, attēla platumam jābūt ${width} pikseļiem un tā augstumam jābūt ${height} pikseļiem. Citi izmēri tiks pielāgoti, lai atbilstu. Akceptētie attēla formāti ir: PNG, GIF un JPEG."
  },
  "simpleTable": {
    "moveUp": "Pārvietot uz augšu",
    "moveDown": "Pārvietot uz leju",
    "deleteRow": "Dzēst",
    "edit": "Rediģēt"
  },
  "urlParams": {
    "invalidToken": "Nederīga pilnvara",
    "validateTokenError": "Nederīga pilnvara vai tīkla kļūda"
  },
  "exportTo": {
    "exportTo": "Eksportēt",
    "toCSV": "Eksports uz CSV failu",
    "toFeatureCollection": "Eksportēt uz elementu kolekciju",
    "toGeoJSON": "Eksportēt uz GeoJSON"
  },
  "appState": {
    "title": "Lietotnes stāvoklis",
    "restoreMap": "Noklikšķiniet, lai atjaunotu kartes pārklājumu un slāņu redzamību kāda tā bija, kad pārtraucāt darbu."
  },
  "featureActions": {
    "featureActions": "Elementu darbības",
    "ZoomTo": "Pietuvināt",
    "PanTo": "Pārbīdīt uz",
    "Flash": "Izgaismošana",
    "ShowPopup": "Rādīt uznirstošo logu",
    "CreateLayer": "Izveidot slāni",
    "ShowStatistics": "Statistika...",
    "ClearSelection": "Notīrīt izvēli",
    "ExportToCSV": "Eksports uz CSV failu",
    "ShowSelectedFeature": "Rādīt atlasītos elementus",
    "ExportToFeatureCollection": "Eksportēt uz elementu kolekciju",
    "ExportToGeoJSON": "Eksportēt uz GeoJSON",
    "EditAttributes": "Rediģēt atribūtus",
    "AddMarker": "Pievienot marķieri",
    "RemoveMarker": "Noņemt marķieri",
    "SaveToMyContent": "Saglabāšana sadaļā Mans saturs"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Saistītais slānis",
    "selectedFeatures": "Izmantot atlasītos elementus",
    "drawShapesTip": "Zīmēt formas, lai atlasītu elementus",
    "pleaseDrawShapesTip": "Lūdzu, zīmējiet formas, lai atlasītu elementus",
    "allFeaturesTip": "Visi elementi slānī",
    "selectFeaturesOrDrawShapesTip": "Izmantojiet atlasītos elementus šajā slānī vai zīmējiet formas kartē, lai ierobežotu elementus."
  },
  "searchDistance": {
    "applySearchDistance": "Lietot meklēšanas attālumu",
    "applySearchDistanceToFeatures": "Atlasītajiem elementiem lietot meklēšanas attālumu"
  },
  "units": {
    "miles": "Jūdzes",
    "milesAbbr": "jūdzes",
    "kilometers": "Kilometri",
    "kilometersAbbr": "km",
    "feet": "Pēdas",
    "feetAbbr": "pēdas",
    "meters": "Metri",
    "metersAbbr": "m",
    "yards": "Jardi",
    "yardsAbbr": "jardi",
    "acres": "Akri",
    "acresAbbr": "akri",
    "nauticalMiles": "Jūras jūdzes",
    "nauticalMilesAbbr": "jūras jūdzes",
    "uSSurveyFeet": "ASV mērāmā pēda",
    "uSSurveyFeetAbbr": "ASV pēda",
    "decimalDegree": "Decimālie grādi",
    "decimalDegreeAbbr": "dg",
    "degreeMinuteSeconds": "Grādi minūtes sekundes",
    "degreeMinuteSecondsAbbr": "g° m’ s’’",
    "squareMiles": "Kvadrātjūdzes",
    "squareMilesAbbr": "kv jūdzes",
    "squareKilometer": "Kvadrātkilometri",
    "squareKilometerAbbr": "kv km",
    "squareFeet": "Kvadrātpēdas",
    "squareFeetAbbr": "kv pēdas",
    "squareMeters": "Kvadrātmetri",
    "squareMetersAbbr": "kv m",
    "squareYards": "Kvadrātjardi",
    "squareYardsAbbr": "kv jardi",
    "squareUSSurveyFeet": "ASV mērāmā kvadrātpēda",
    "squareUSSurveyFeetAbbr": "ASV kv pēda"
  },
  "featureSetChooser": {
    "select": "Izvēlēties",
    "dragBox": "Vilkt",
    "dragMouse": "Pavilkt peli",
    "selectByRectangle": "Izvēlēties pēc taisnstūra",
    "selectFeaturesTip": "Izvēlēties elementus, kartē apvelkot ap tiem lodziņu",
    "newSelectionTip": "Izveidot jaunu izvēli",
    "addSelectionTip": "Pievienot izvēlētajam",
    "removeSelectionTip": "Izņemt no izvēles",
    "selectFromCurrentSelectionTip": "Izvēlēties no pašreizējās izvēles",
    "unselectAllSelectionTip": "Noņemt izvēli visiem pašreiz izvēlētajiem elementiem",
    "selectByPolygon": "Atlasīt pēc laukuma",
    "selectByCircle": "Atlasīt pēc apļa",
    "selectByLine": "Atlasīt pēc līnijas",
    "chooseSelectingTools": "Izvēlēties atlases rīkus",
    "darw": "Zīmēt",
    "drawShap": "Uzzīmēt formu"
  },
  "widgetManager": {
    "createWidgetError": "Izveidot logrīka kļūdu",
    "createWidgetSettingPageError": "Izveidot logrīka iestatījuma lapas kļūdu",
    "loadWidgetResourceError": "Ielādēt logrīka resursa kļūdu"
  },
  "shareOptions": {
    "shareMap": "Izvēlieties, kas varēs skatīt šo lietojumprogrammu",
    "shareMapTips": "Jūsu lietojumprogramma pašlaik tiek kopīgota ar šīm personām",
    "everyone": "Ikviens",
    "theseGroups": "Šīs grupas"
  },
  "shareLink": {
    "email": "epasts",
    "shareEmail": "E-pasts",
    "facebook": "facebook",
    "shareFacebook": "Facebook",
    "twitter": "twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "Iegult šo lietojumprogrammu tīmekļa vietnē",
    "shareEmailSubject": "Tīmekļa lietojumprogrammas kopīgošana:",
    "shareEmailTxt1": "Šī tīmekļa lietojumprogramma tiek ar jums kopīgota, izmantojot Web AppBuilder for ArcGIS.",
    "shareEmailTxt2": "Varat izveidot un kopīgot savu tīmekļa lietojumprogrammu, izmantojot Esri Web AppBuilder for ArcGIS.",
    "shareEmailTxt3": "Plašāku informāciju skatiet vietnē http://www.esri.com/software/web-appbuilder.",
    "smallSize": "Mazs",
    "mediumSize": "Vidējs",
    "largeSize": "Liels",
    "customSize": "Pielāgots",
    "embed": "Iegult šo lietojumprogrammu tīmekļa vietnē",
    "more": "Iegulšanas opcijas",
    "changeShareSettings": "Mainīt koplietošanas iestatījumus",
    "shareLinkText": "Kopīgot saiti uz šo lietojumprogrammu",
    "linkOptions": "Saites opcijas",
    "linkOptionsUrlParameters": "Atlasīt saitē iekļautos URL parametrus",
    "currentMapExtent": "Pašreizējais kartes pārklājums",
    "chooseCenterWithLevel": "Noklikšķināt uz kartes, lai definētu kartes centru ar mērogmaiņas līmeni",
    "chooseCenterWithScale": "Noklikšķināt uz kartes, lai definētu kartes centru ar kartes mērogu",
    "findLocation": "Atrast izvietojumu vai elementu un mērogojiet uz to",
    "findLocation_inputPlaceholder": "Jūsu vieta vai elements",
    "queryFeature": "Izveidojiet elementa vaicājumu un mērogojiet uz to",
    "addMarker": "Pievienot kartē marķieri",
    "addMarker_titlePlaceholder": "Marķiera uznirstošā loga simbols",
    "addMarker_symbolURL": "Marķiera simbola URL",
    "addMarker_label": "Marķiera kartes teksts",
    "popupTitle": "Uznirstošā loga virsraksts",
    "zoomLevel": "Mērogmaiņas līmenis",
    "overwirteMobileLayout": "Pārrakstīt mobilā izkārtojuma noklusējuma ekrāna izmēru",
    "language": "Iestatīt lietojumprogrammas attēlojuma valodu",
    "auth": "Automātiski autentificēt lietotāju",
    "linkPreview": "Saites priekšskatījums",
    "useShortenLink": "Īsā saite",
    "shareMapUrlExtent": "Koplietot pašreizējās kartes pārklājumu",
    "shareToWebTips": "Šī lietojumprogramma netiek koplietota publiski. Iespējams, personas nevarēs to skatīt."
  },
  "webSceneLoader": {
    "webglSupportTip": "Jūsu pārlūkā netiek atbalstītas 3D tīmekļa lietotnes."
  },
  "map": {
    "basemapNotAvailable": "Pamatkarte nav pieejama.",
    "displayDefaultBasemap": "Tā vietā tiek rādīta noklusējuma pamatkarte.",
    "layerLoadedError": "Slāni ${layer} nevar pievienot kartei."
  },
  "popup": {
    "relatedTables": "Saistītās tabulas:",
    "relatedRecords": "Saistītie ieraksti:",
    "noRelatedRecotds": "Nav atrasts neviens saistīts ieraksts.",
    "chooseFieldTip": "Izvēlieties atribūtu saraksta rādīšanai",
    "saveAsPopupTitle": "Tāds pats kā uznirstošais virsraksts"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "Jūsu izvēlē ir pārāk daudz elementu. Iespējams, būs nepieciešams ilgs laiks, lai tos izgūtu un parādītu kartē.",
    "askForContinue": "Vai vēlaties turpināt?"
  },
  "colorPalette": {
    "transparent": "Caurspīdīgs",
    "custom": "Pielāgots"
  },
  "temperature": {
    "celsius": "Celsija",
    "fahrenheit": "Fārenheita"
  },
  "report": {
    "printButtonLabel": "Drukāt",
    "reportDimensionsMsg": "Šis pārskats ir plānots drukāšanai uz ${paperSize} formāta papīra",
    "unableToPrintMapMsg": "Drukājot karti(-es), radās kļūda.",
    "notesHint": "Šeit ievadiet komentārus",
    "landscape": "Ainava",
    "portrait": "Portrets",
    "mapOnly": "MAP_ONLY",
    "a0": "A0",
    "a1": "A1",
    "a2": "A2",
    "a3": "A3",
    "a4": "A4",
    "a5": "A5",
    "letterANSIA": "Letter ANSI A",
    "tabloidANSIB": "Tabloid ANSI B",
    "letter": "Letter",
    "legal": "Legal",
    "tabloid": "Tabloid",
    "ansi_a": "ANSI A",
    "ansi_b": "ANSI B",
    "ansi_c": "ANSI C",
    "ansi_d": "ANSI D",
    "ansi_e": "ANSI E"
  },
  "snapshot": {
    "snapshot_complete": "Momentuzņēmums veiksmīgi izveidots.",
    "snapshot_failed": "Neizdevās izveidot momentuzņēmumu.",
    "snapshot_append": "Momentuzņēmums",
    "utc": "UTC"
  },
  "statisticsChart": {
    "enlarge": "Palielināt",
    "setting": "Iestatījums",
    "count": "Skaits",
    "horizontalAxis": "Horizontālā ass",
    "verticalAxis": "Vertikālā ass",
    "dataLabels": "Datu nosaukumi",
    "color": "Krāsa"
  },
  "frameworkDatasource": {
    "setDataSource": "Iestatīt datu avotu",
    "customDataSource": "Papildu datu avots",
    "selectCustomDataTip": "Atlasiet datu avotu no šīs lietotnes.",
    "widgetOutputs": "Logrīku attēlošana",
    "noExtraDsAvailable": "Nav pieejami papildu datu avoti.",
    "addExtraDsTip": "Dodieties uz veidotāja cilni Atribūts un noklikšķiniet uz Papildu datu avots, lai pievienotu datus.",
    "widgetOutpusListTip": "Šeit ir norādītas arī logrīku izvades, ja tādas ir."
  },
  "gridLayout": {
    "addWidgetTip": "Pievienojiet šeit logrīkus, izmantojot cilni Logrīki",
    "modifyLayout": "Modificēt izkārtojumu",
    "dragToAdd": "Velciet, lai pievienotu",
    "mapArea": "KARTES LAUKUMS"
  },
  "noEditPrivileges": "Jūsu kontam nav piešķirta atļauja izveidot vai modificēt datus.",
  "invalidConfiguration": "Logrīks nav konfigurēts vai konfigurētie slāņi vairs nav kartē. Lūdzu, atveriet programmu veidotāja režīmā un konfigurējiet logrīku atkārtoti."
});