define(
   ({
    _widgetLabel: "Atributová tabulka",
    ok: "OK",
    cancel: "Storno",
    unsupportQueryWarning: "Vrstva musí podporovat operace dané založené na dotazu, aby bylo možné ji zobrazovat ve widgetu Atributová tabulka. Ujistěte se, že je ve službě aktivní možnost dotazování.",
    exportMessage: "Přejete si exportovat data do CSV souboru ?",
    exportFiles: "Exportovat do CSV",
    exportSelected: "Exportovat vybrané do CSV",
    exportAll: "Exportovat vše do CSV",
    options: "Možnosti",
    zoomto: "Přiblížit na",
    highlight: "Zvýraznit grafiku",
    selectAll: "Vybrat záznamy na všech stránkách",
    selectPage: "Vybrat záznamy na aktuální stránce",
    clearSelection: "Zrušit výběr",
    filter: "Filtr",
    setFilterTip: "Nastavte filtr správně.",
    noFilterTip: "Pokud nedefinujete výraz filtru, tato dotazovací úloha zobrazí všechny prvky v zadaném zdroji dat.",
    filterByExtent: "Filtrovat podle rozsahu mapy",
    showSelectedRecords: "Zobrazit vybrané záznamy",
    showAllRecords: "Zobrazit všechny záznamy",
    showRelatedRecords: "Zobrazit související záznamy",
    noRelatedRecords: "Žádné související záznamy",
    refresh: "Obnovit",
    features: "prvků",
    selected: "vybrané",
    transparent: "Režim průhlednosti",
    indicate: "Najít výběr",
    columns: "Zobrazit/Skrýt sloupce",
    selectionSymbol: "Symbol výběru",
    closeMessage: "Skrýt tabulku (znovu ji rozbalit zespodu)",
    dataNotAvailable: "Data nejsou k dispozici!<br>Zkuste to znovu kliknutím na tlačítko [Obnovit].",
    openTableTip: "Otevřít atributovou tabulku",
    closeTableTip: "Skrýt atributovou tabulku"
  })
);