define({
  "sourceSetting": "Meklēšanas avota iestatījumi",
  "instruction": "Pievienojiet un konfigurējiet ģeokodēšanas pakalpojumus vai elementu slāņus kā meklēšanas avotus. Šie norādītie avoti nosaka, ko var meklēt meklēšanas lodziņā.",
  "add": "Pievienot meklēšanas avotu",
  "addGeocoder": "Pievienot ģeokodētāju",
  "geocoder": "Ģeokodētājs",
  "setLayerSource": "Iestatīt slāņa avotu",
  "setGeocoderURL": "Iestatīt ģeokodētāja vietrādi URL",
  "searchableLayer": "Elementu slānis",
  "name": "Nosaukums",
  "countryCode": "Valsts vai reģiona kods(-i)",
  "countryCodeEg": "piem., ",
  "countryCodeHint": "Ja šī vērtība tiks atstāta tukša, tiks meklētas visas valstis un reģioni.",
  "generalSetting": "Vispārīgi iestatījumi",
  "allPlaceholder": "Viettura teksts visu vērtību meklēšanai: ",
  "showInfoWindowOnSelect": "Rādīt atrastā elementa vai izvietojuma uznirstošo logu",
  "searchInCurrentMapExtent": "Meklēt tikai pašreizējā kartes pārklājumā",
  "zoomScale": "Mērogmaiņas skala",
  "locatorUrl": "Ģeokodētāja URL",
  "locatorName": "Ģeokodētāja vārds",
  "locatorExample": "Piemērs",
  "locatorWarning": "Šī ģeokodēšanas pakalpojuma versija netiek atbalstīta. Logrīks atbalsta ģeokodēšanas pakalpojuma versiju 10.1 un jaunākas.",
  "locatorTips": "Ieteikumi nav pieejami, jo ģeokodēšanas pakalpojums neatbalsta ieteikšanas iespēju.",
  "layerSource": "Slāņa avots",
  "searchLayerTips": "Ieteikumi nav pieejami, jo elementu pakalpojums neatbalsta lappušu numerācijas iespēju.",
  "placeholder": "Viettura teksts",
  "searchFields": "Meklēšanas lauki",
  "displayField": "Rādīt lauku",
  "exactMatch": "Precīza atbilstība",
  "maxSuggestions": "Maksimālais ieteikumu skaits",
  "maxResults": "Maks. rezultātu skaits",
  "enableLocalSearch": "Iespējot lokālo meklēšanu",
  "minScale": "Minimālo vērtību mērogs",
  "minScaleHint": "Ja kartes mērogs ir lielāks par šo mērogu, tiks lietota lokālā meklēšana",
  "radius": "Rādiuss",
  "radiusHint": "Norāda tā apgabala rādiusu ap pašreizējo kartes centru, kas tiek izmantots, lai uzlabotu ģeokodēšanas kandidātu rangu, lai vispirms tiktu atgriezti izvietojumam tuvākie kandidāti",
  "meters": "Metri",
  "setSearchFields": "Iestatīt meklēšanas laukus",
  "set": "Uzstādīt",
  "fieldSearchable": "meklējams",
  "fieldName": "Nosaukums",
  "fieldAlias": "Aizstājvārds",
  "ok": "Labi",
  "cancel": "Atcelt",
  "invalidUrlTip": "URL ${URL} nav derīgs vai tam nevar piekļūt."
});