define(
   ({
    "sourceSetting": "Meklēšanas avota iestatījumi",
    "instruction": "Pievienojiet un konfigurējiet ģeokodēšanas pakalpojumus vai elementu slāņus kā meklēšanas avotus. Šie norādītie avoti nosaka, kādus vienumus var meklēt meklēšanas lodziņā.",
    "add": "Pievienot meklēšanas avotu",
    "addGeocoder": "Pievienot ģeokodētāju",
    "geocoder": "Ģeokodētājs",
    "setLayerSource": "Iestatīt slāņa avotu",
    "setGeocoderURL": "Iestatīt ģeokodētāja vietrādi URL",
    "searchableLayer": "Elementu slānis",
    "name": "Nosaukums",
    "countryCode": "Valsts vai reģiona kods(-i)",
    "countryCodeEg": "piem., ",
    "countryCodeHint": "Ja šī vērtība tiks atstāta tukša, tiks meklētas visas valstis un reģioni.",
    "generalSetting": "Vispārējie iestatījumi",
    "allPlaceholder": "Viettura teksts visu vērtību meklēšanai: ",
    "showInfoWindowOnSelect": "Rādīt atrastā elementa vai atrašanās vietas uznirstošo logu",
    "searchInCurrentMapExtent": "Meklēt tikai pašreizējā kartes pārklājumā",
    "locatorUrl": "Ģeokodētāja URL",
    "locatorName": "Ģeokodētāja vārds",
    "locatorExample": "Piemērs",
    "locatorWarning": "Šī ģeokodēšanas pakalpojuma versija netiek atbalstīta. Šis logrīks atbalsta ģeokodēšanas pakalpojuma versiju 00.0 un jaunākas.",
    "locatorTips": "Ieteikumi nav pieejami, jo ģeokodēšanas pakalpojums neatbalsta ieteikšanas iespēju.",
    "layerSource": "Slāņa avots",
    "searchLayerTips": "Ieteikumi nav pieejami, jo elementu pakalpojums neatbalsta lappušu numerācijas iespēju.",
    "placeholder": "Viettura teksts",
    "searchFields": "Meklēšanas lauki",
    "displayField": "Rādīt lauku",
    "exactMatch": "Precīza atbilstība",
    "maxResults": "Maks. rezultātu skaits",
    "setSearchFields": "Iestatīt meklēšanas laukus",
    "set": "Kopa",
    "fieldSearchable": "meklējams",
    "fieldName": "Nosaukums",
    "fieldAlias": "Aizstājvārds",
    "ok": "Labi",
    "cancel": "Atcelt",
    "invalidUrlTip": "Jūsu ievadītais URL nav derīgs vai tam nevar piekļūt."
  })
);