define({
  "instruction": "स्प्लैश स्क्रीन ऐप्लिकेशन के सुलभ होने से पहले प्रकट होती है।",
  "defaultContent": "टेक्स्ट, लिंक, और छोटे ग्राफिक्स को यहाँ जोड़ें।",
  "requireConfirm": "जारी रखने के लिए पुष्टि की आवश्यकता है",
  "noRequireConfirm": "जारी रखने के लिए पुष्टि की आवश्यकता नहीं है",
  "optionText": "ऐप्लिकेशन शुरू होने पर स्प्लैश स्क्रीन को निष्क्रिय करने के लिए उपयोगकर्ता के लिए विकल्प।",
  "confirmLabel": "पुष्टिकरण पाठ: ",
  "confirmLabelColor": "पुष्टिकरण पाठ का रंग",
  "defaultConfirmText": "मैं उक्त नियम एवं शर्तों से सहमत हूँ",
  "confirmOption": "हमेशा ऐप्लिकेशन शुरू होने पर यह स्प्लैश स्क्रीन दिखाएँ",
  "backgroundColor": "पृष्ठभूमि रंग",
  "content": "सामग्री",
  "contentDescription": "स्प्लैश स्क्रीन पर प्रदर्शित होने वाली सामग्री निर्धारित करें।",
  "appearance": "दिखावट",
  "appearanceDescription": "स्प्लैश स्क्रीन की दिखावट निर्धारित करें।",
  "size": "आकार",
  "width": "चौड़ाई",
  "height": "ऊंचाई",
  "custom": "कस्टम",
  "background": "पृष्ठभूमि",
  "colorFill": "रंग भरें",
  "imageFill": "छवि भरें",
  "chooseFile": "फ़ाइल का चयन करें",
  "noFileChosen": "कोई फ़ाइल नहीं चुनी गई",
  "transparency": "पारदर्शिता",
  "sizeFill": "भरें",
  "sizeFit": "फ़िट",
  "sizeStretch": "भरने तक स्ट्रेच करें",
  "sizeCenter": "केंद्र",
  "sizeTile": "टाइल",
  "buttonColor": "बटन का रंग",
  "buttonText": "बटन का पाठ",
  "buttonTextColor": "बटन के पाठ का रंग",
  "contentAlign": "वस्तु संरेखण",
  "alignTop": "शीर्ष",
  "alignMiddle": "मध्य",
  "maskColor": "मास्क का रंग",
  "options": "विकल्प",
  "optionsDescription": "स्प्लैश स्क्रीन का व्यवहार निर्धारित करें।"
});