define({
  "instruction": "Izaberi i konfiguriši slojeve koji će biti inicijalno prikazani u atributnoj tabeli.",
  "label": "Sloj",
  "show": "Prikaži",
  "actions": "Konfigurišite polja sloja",
  "field": "Polje",
  "alias": "Pseudonim",
  "visible": "Vidljivo",
  "linkField": "Link polja",
  "noLayers": "Nema dostupnih slojeva geoobjekata",
  "back": "Nazad",
  "exportCSV": "Omogući izvoz u CSV",
  "expand": "Inicijalno proširi vidžet",
  "filterByExtent": "Podrazumevano omogući filter po obuhvatu mape",
  "restore": "Vrati na podrazumevanu vrednost",
  "ok": "U redu",
  "cancel": "Otkaži",
  "includePoint": "Uključi koordinate tačke u izvezenu datoteku",
  "configureLayerFields": "Konfigurišite polja sloja",
  "result": "Uspešno sačuvano",
  "warning": "Najpre izaberite „Prikaži opcije“.",
  "fieldCheckWarning": "Bar jedno polje mora da bude izabrano.",
  "unsupportQueryWarning": "Sloj mora da podržava radnju upita da bi se prikazao u vidžetu „Atributna tabela“. Postarajte se da je mogućnost izvršavanja upita u servisu uključena.",
  "unsupportQueryLayers": "Sledeći sloj mora da podržava radnju upita da bi se prikazao u vidžetu „Atributna tabela“. Postarajte se da je mogućnost izvršavanja upita u servisu uključena.",
  "fieldName": "Naziv",
  "fieldAlias": "Pseudonim",
  "fieldVisibility": "Vidljivost",
  "fieldActions": "Radnje",
  "showAttachments": "Prikaži priloge"
});