define({
  "sourceSetting": "Configurações da fonte de pesquisa",
  "instruction": "Adicione e configure serviços de geocódigo ou camadas de feição como fontes de pesquisa. Estas fontes especificadas determinam o que é pesquisável dentro da caixa de pesquisa.",
  "add": "Adicionar fonte de pesquisa",
  "addGeocoder": "Adicionar geocodificador",
  "geocoder": "Geocodificador",
  "setLayerSource": "Configurar fonte de camada",
  "setGeocoderURL": "Configurar URL do geocodificador",
  "searchableLayer": "Camada de feição",
  "name": "Nome",
  "countryCode": "Códigos de região ou país",
  "countryCodeEg": "por exemplo ",
  "countryCodeHint": "Deixar este valor em branco pesquisará todos os países e regiões",
  "generalSetting": "Configurações gerais",
  "allPlaceholder": "Texto de local reservado para pesquisar todos: ",
  "showInfoWindowOnSelect": "Mostrar pop-up do local ou feição localizada",
  "searchInCurrentMapExtent": "Somente pesquisar na extensão de mapa atual",
  "zoomScale": "Escala de zoom",
  "locatorUrl": "URL do Geocodificador",
  "locatorName": "Nome do geocodificador",
  "locatorExample": "Exemplo",
  "locatorWarning": "Esta versão do serviço de geocodificação não é suportada. O widget suporta o serviço de geocodificação 10.1 e superior.",
  "locatorTips": "As sugestões não estão disponíveis, pois o serviço de geocodificação não suporta o recursos de sugestão.",
  "layerSource": "Fonte da camada",
  "searchLayerTips": "As sugestões não estão disponíveis, pois o serviço da feição não suporta o recursos de paginação.",
  "placeholder": "Texto do placeholder",
  "searchFields": "Campos de pesquisa",
  "displayField": "Campo de visualização",
  "exactMatch": "Combinação exata",
  "maxSuggestions": "Máximo de sugestões",
  "maxResults": "Máximo de resultados",
  "enableLocalSearch": "Habilitar pesquisa de local",
  "minScale": "Escala mínima",
  "minScaleHint": "Quando a escala do mapa for maior que esta escala, a pesquisa de local será aplicada",
  "radius": "Raio",
  "radiusHint": "Especifica o raio de uma área ao redor do centro do mapa atual que é utilizado para impulsionar o grau de candidatos de geocodificação de forma que os candidatos mais próximos ao local sejam retornados primeiro",
  "meters": "Metros",
  "setSearchFields": "Configurar campos de pesquisa",
  "set": "Configurar",
  "fieldSearchable": "pesquisável",
  "fieldName": "Nome",
  "fieldAlias": "Nome Alternativo",
  "ok": "OK",
  "cancel": "Cancelar",
  "invalidUrlTip": "A URL ${URL} é inválida ou inacessível."
});