define(
   ({
    "sourceSetting": "Configurações da Fonte de Pesquisa",
    "instruction": "Adicione e configure serviços de geocódigo ou camadas de feição como fontes de pesquisa. Estas fontes especificadas determinam o que é pesquisável dentro da caixa de pesquisa.",
    "add": "Adicionar Fonte de Pesquisa",
    "addGeocoder": "Adicionar Geocodificador",
    "geocoder": "Geocodificador",
    "setLayerSource": "Configurar Origem da Camada",
    "setGeocoderURL": "Configurar URL do Geocodificador",
    "searchableLayer": "Camada de Feição",
    "name": "Nome",
    "countryCode": "Códigos de Região e País",
    "countryCodeEg": "por exemplo ",
    "countryCodeHint": "Deixar este valor em branco pesquisará todos os países e regiões",
    "generalSetting": "Configurações Gerais",
    "allPlaceholder": "Texto de local reservado para pesquisar todos: ",
    "showInfoWindowOnSelect": "Mostrar pop-up do local ou feição localizada",
    "searchInCurrentMapExtent": "Somente pesquisar na extensão de mapa atual",
    "locatorUrl": "URL do Geocodificador",
    "locatorName": "Nome do Geocodificador",
    "locatorExample": "Exemplo",
    "locatorWarning": "Esta versão do serviço de geocodificação não é suportado. O widget suporta serviço de geocodificação 00.0 e superior.",
    "locatorTips": "As sugestões não estão disponíveis, pois o serviço de geocodificação não suporta o recursos de sugestão.",
    "layerSource": "Origem da Camada",
    "searchLayerTips": "As sugestões não estão disponíveis, pois o serviço da feição não suporta o recursos de paginação.",
    "placeholder": "Texto do Placeholder",
    "searchFields": "Pesquisar Campos",
    "displayField": "Campo de Visualização",
    "exactMatch": "Combinação Exata",
    "maxResults": "Máximo de Resultados",
    "setSearchFields": "Configurar Campos de Pesquisa",
    "set": "Configurar",
    "fieldSearchable": "pesquisável",
    "fieldName": "Nome",
    "fieldAlias": "Nome Alternativo",
    "ok": "OK",
    "cancel": "Cancelar",
    "invalidUrlTip": "O URL que você inseriu é inválido ou inacessível."
  })
);