define(
   ({
    _widgetLabel: "Atributų lentelė",
    ok: "Gerai",
    cancel: "Atšaukti",
    unsupportQueryWarning: "Kad būtų rodomas atributų lentelės valdiklyje šis sluoksnis turi palaikyti užklausas. Įsitikinkite, kad paslaugoje įjungta užklausų galimybė.",
    exportMessage: "Eksportuoti duomenis į CSV formato failą?",
    exportFiles: "Eksportuoti į CSV",
    exportSelected: "Eksportuoti pasirinkimą į CSV",
    exportAll: "Eksportuoti viską į CSV",
    options: "Parinktys",
    zoomto: "Parodyti visą",
    highlight: "Išryškinti grafinius elementus",
    selectAll: "Pasirinkti įrašus visuose puslapiuose",
    selectPage: "Pasirinkti įrašus dabartiniame puslapyje",
    clearSelection: "Valyti išranką",
    filter: "Filtruoti",
    setFilterTip: "Nustatykite filtrą tinkamai.",
    noFilterTip: "Nenustačius filtro sąlygos, ši užklausos užduotis nurodys visus nurodyto duomenų šaltinio elementus.",
    filterByExtent: "Filtruoti pagal žemėlapio aprėptį",
    showSelectedRecords: "Rodyti išrinktus įrašus",
    showAllRecords: "Rodyti visus įrašus",
    showRelatedRecords: "Rodyti susijusius įrašus",
    noRelatedRecords: "Nėra susijusių įrašų",
    refresh: "Atnaujinti",
    features: "elementai",
    selected: "pasirinkta",
    transparent: "Permatomumo režimas",
    indicate: "Rasti išranką",
    columns: "Rodyti/Slėpti stulpelius",
    selectionSymbol: "Išrankos simbolis",
    closeMessage: "Slėpti lentelę (išplėsti vėl nuo apačios)",
    dataNotAvailable: "Domenų nėra!<br>Bandykite dar kartą spustelėdami mygtuką [Atnaujinti]",
    openTableTip: "Atidaryti atributų lentelę",
    closeTableTip: "Slėpti atributų lentelę"
  })
);