define({
  "id": "ID",
  "state": "În mod implicit, coordonatele vor fi afişate în sistemul de coordonate actual al hărţii. Pentru a obţine coordonate în alte sisteme de coordonate, trebuie să le adăugaţi şi să specificaţi transformările necesare.",
  "outputUnit": "Unitate rezultat",
  "wkid": "WKID rezultat",
  "label": "Nume sistem de coordonate de ieşire",
  "transformationWkid": "WKID transformare",
  "transformationLabel": "Etichetă transformare",
  "transformForward": "Avansare transformare",
  "actions": "Acţiuni",
  "warning": "Introduceţi un WKID de referinţă spaţială valid!",
  "tfWarning": "Introduceţi un WKID pentru transformarea datelor valid!",
  "spinnerLabel": "Rotunjire coordonate la: ",
  "decimalPlace": "zecimale",
  "separator": "Afişare separatori mii",
  "getVersionError": "Nu se poate obţine versiunea serviciului de geometrie",
  "add": "Adăugare sistem de coordonate de ieşire",
  "edit": "Editare sistem de coordonate",
  "output": "Sistem de coordonate de ieşire",
  "cName": "Nume sistem de coordonate",
  "units": "Unităţi afişate: ",
  "datum": "Transformare linie de bază",
  "tName": "Nume transformare",
  "tWKIDPlaceHolder": "WKID al transformării",
  "forward": "Utilizare transformare înainte",
  "ok": "OK",
  "cancel": "Anulare",
  "olderVersion": "Serviciul de geometrie nu acceptă operaţia de transformare",
  "REPEATING_ERROR": " Sistemul de coordonate există în lista de ieşire.",
  "Default": "Implicit",
  "Inches": "Inci",
  "Foot": "Ft",
  "Yards": "Yarzi",
  "Miles": "Mile",
  "Nautical_Miles": "Mile marine",
  "Millimeters": "Milimetri",
  "Centimeters": "Centimetri",
  "Meter": "Metri",
  "Kilometers": "Kilometri",
  "Decimeters": "Decimetri",
  "Decimal_Degrees": "Grade zecimale",
  "Degrees_Decimal_Minutes": "Grade zecimale minute",
  "Degree_Minutes_Seconds": "Grade minute secunde",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Ordine de afişare coordonate:",
  "lonLatTips": "Longitudine/Latitudine (X, Y)",
  "latLonTips": "Latitudine/Longitudine (Y, X)"
});