define({
  root: ({
    _widgetLabel: "Attribute Table",
    ok: "OK",
    cancel: "Cancel",
    unsupportQueryWarning: "The layer needs to support query operation to display in Attribute Table widget. Make sure the query capability in the service is turned on.",
    exportMessage: "Export data to CSV file?",
    exportFiles: "Export to CSV",
    exportSelected: "Export Selected to CSV",
    exportAll: "Export All to CSV",
    options: "Options",
    zoomto: "Zoom to",
    highlight: "Highlight Graphics",
    selectAll: "Select Records in All Pages",
    selectPage: "Select Records in Current Page",
    clearSelection: "Clear Selection",
    filter: "Filter",
    setFilterTip: "Please set filter correctly.",
    noFilterTip: "Without filter expression defined, this query task will list all features in the specified data source.",
    filterByExtent: "Filter by Map Extent",
    showSelectedRecords: "Show Selected Records",
    showAllRecords: "Show All Records",
    showRelatedRecords: "Show Related Records",
    noRelatedRecords: "No Related Records",
    refresh: "Refresh",
    features: "features",
    selected: "selected",
    transparent: "Transparent Mode",
    indicate: "Locate Selection",
    columns: "Show/Hide Columns",
    selectionSymbol: "Selection Symbol",
    closeMessage: "Hide Table (expand it again from the bottom)",
    dataNotAvailable: "Data not available!<br>Click [Refresh] button to try again.",
    openTableTip: "Open Attribute Table",
    closeTableTip: "Hide Attribute Table"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});