define(
   ({
    id: 'ID',
    state: "Por defeito, as coordenadas serão exibidas no sistema de coordenadas do mapa atual. Para obter coordenadas noutros sistemas de coordenadas, necessita de adicioná-las e definir as transformações apropriadas.",
    outputUnit: "Unidade de Saída",
    wkid: "WKID de Saída",
    label: "Nome do Sistema de Coordenadas de Saída",
    transformationWkid: "WKID de Transformação",
    transformationLabel: "Rótulo de Transformação",
    transformForward: "Transformar para a Frente",
    actions: "Ações",
    warning: "Por favor, insira um WKID de referência espacial válido!",
    tfWarning: "Por favor, insira um datum de transformação WKID válido!",
    spinnerLabel: "Arredondar coordenadas para: ",
    decimalPlace: "casas decimais",
    separator: "Exibir separadores de milhares",
    getVersionError: "Não é possível obter a versão do Serviço de Geometria",

    add: "Adicionar Sistema de Coordenadas de Saída",
    edit: "Editar Sistema de Coordenadas",
    output: "Sistema de Coordenadas de Saída",
    cName: "Nome do Sistema de Coordenadas",
    units: "Exibir Unidades: ",
    datum: "Transformação datum",
    tName: "Nome da transformação",
    tWKIDPlaceHolder: "WKID da transformação",
    forward: "Utilizar transformação para a frente",
    ok: "OK",
    cancel: 'Cancelar',
    olderVersion: "O Serviço de Geometria não suporta operação de transformação.",
    REPEATING_ERROR: " O sistema de coordenadas existe na lista de saída.",

    Default: "Padrão",
    Inches: "Polegadas",
    Foot: "Pés",
    Yards: "Jardas",
    Miles: "Milhas",
    Nautical_Miles: "Milhas Náuticas",
    Millimeters: "Milímetros",
    Centimeters: "Centímetros",
    Meter: "Metros",
    Kilometers: "Quilômetros",
    Decimeters: "Decímetros",
    Decimal_Degrees: "Graus Decimais",
    Degree_Minutes_Seconds: "Graus Minutos Segundos",
    MGRS: "MGRS",
    USNG: "USNG"
  })
);