define({
  "id": "ID",
  "state": "Por defeito, as coordenadas serão exibidas no sistema de coordenadas do mapa atual. Para obter coordenadas noutros sistemas de coordenadas, necessita de adicioná-las e definir as transformações apropriadas.",
  "outputUnit": "Unidade de Saída",
  "wkid": "WKID de Saída",
  "label": "Nome do sistema de coordenadas de saída",
  "transformationWkid": "WKID de Transformação",
  "transformationLabel": "Rótulo de transformação",
  "transformForward": "Transformar para a frente",
  "actions": "Ações",
  "warning": "Por favor, insira um WKID de referência espacial válido!",
  "tfWarning": "Por favor, insira um datum de transformação WKID válido!",
  "spinnerLabel": "Arredondar coordenadas para: ",
  "decimalPlace": "casas decimais",
  "separator": "Exibir separadores de milhares",
  "getVersionError": "Não é possível obter a versão do serviço de geometria",
  "add": "Adicionar sistema de coordenadas saída",
  "edit": "Editar sistema de coordenadas",
  "output": "Sistema de coordenadas de saída",
  "cName": "Nome do sistema de coordenadas",
  "units": "Exibir unidades: ",
  "datum": "Transformação datum",
  "tName": "Bome da transformação",
  "tWKIDPlaceHolder": "WKID da transformação",
  "forward": "Utilizar transformação para a frente",
  "ok": "OK",
  "cancel": "Cancelar",
  "olderVersion": "O serviço de geometria não suporta a operação de transformação.",
  "REPEATING_ERROR": " O sistema de coordenadas existe na lista de saída.",
  "Default": "Padrão",
  "Inches": "Polegadas",
  "Foot": "Pés",
  "Yards": "Jardas",
  "Miles": "Milhas",
  "Nautical_Miles": "Milhas Náuticas",
  "Millimeters": "Milímetros",
  "Centimeters": "Centímetros",
  "Meter": "Metros",
  "Kilometers": "Quilômetros",
  "Decimeters": "Decímetros",
  "Decimal_Degrees": "Graus decimais",
  "Degrees_Decimal_Minutes": "Graus decimais minutos",
  "Degree_Minutes_Seconds": "Graus minutos segundos",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Ordem de exibição de coordenadas:",
  "lonLatTips": "Longitude / Latitude(X, Y)",
  "latLonTips": "Latitude / Longitude(Y, X)"
});