define({
  "_widgetLabel": "Lista de Camadas",
  "titleBasemap": "Mapas base",
  "titleLayers": "Camadas operacionais",
  "labelLayer": "Nome da camada",
  "itemZoomTo": "Efetuar zoom para",
  "itemTransparency": "Transparência",
  "itemTransparent": "Transparente",
  "itemOpaque": "Opaco",
  "itemMoveUp": "Mover para cima",
  "itemMoveDown": "Mover para baixo",
  "itemDesc": "Descrição",
  "itemDownload": "Descarregar",
  "itemToAttributeTable": "Visualizar em Tabela de Atributos",
  "itemShowItemDetails": "Exibir detalhes de itens",
  "empty": "vazio",
  "removePopup": "Desativar janela pop-up",
  "enablePopup": "Ativar janela pop-up",
  "turnAllLayersOff": "Desativar todas as camadas",
  "turnAllLayersOn": "Ativar todas as camadas",
  "expandAllLayers": "Expandir todas as camadas",
  "collapseAlllayers": "Fechar todas as camadas",
  "turnAllLabelsOff": "Desativar todos os rótulos",
  "turnAllLabelsOn": "Ativar todos os rótulos",
  "showLabels": "Exibir rótulos",
  "hideLables": "Ocultar rótulos"
});