define({
  "instruction": "Ecranul de pornire apare înainte ca aplicaţia să poată fi accesată.",
  "defaultContent": "Adăugaţi text, legături şi alte imagini mici aici.",
  "requireConfirm": "Pentru a continua, este necesară confirmarea",
  "noRequireConfirm": "Nu este necesară confirmarea pentru a continua",
  "optionText": "Opţiune pentru utilizator pentru dezactivarea ecranului de pornire la pornirea aplicaţiei.",
  "confirmLabel": "Texte de confirmare: ",
  "confirmLabelColor": "Culoare texte de confirmare",
  "defaultConfirmText": "Sunt de acord cu termenii şi condiţiile de mai sus",
  "confirmOption": "Afişaţi acest ecran de pornire de fiecare dată când este lansată aplicaţia",
  "backgroundColor": "Culoare fundal",
  "content": "Conţinut",
  "contentDescription": "Definiţi conţinutul care este afişat pe ecranul de pornire.",
  "appearance": "Aspect",
  "appearanceDescription": "Setaţi aspectul ecranului de pornire.",
  "size": "Dimensiune",
  "width": "Lăţime",
  "height": "Înălţime",
  "custom": "Personalizat",
  "background": "Fundal",
  "colorFill": "Umplere cu culoare",
  "imageFill": "Umplere cu imagine",
  "chooseFile": "Alegere fişier",
  "noFileChosen": "Niciun fişier selectat",
  "transparency": "Transparenţă",
  "sizeFill": "Umplere",
  "sizeFit": "Potrivire",
  "sizeStretch": "Întindere pentru umplere",
  "sizeCenter": "Centru",
  "sizeTile": "Tile",
  "buttonColor": "Culoare buton",
  "buttonText": "Culoare text",
  "buttonTextColor": "Culoare text de buton",
  "contentAlign": "Aliniere conţinut",
  "alignTop": "Sus",
  "alignMiddle": "Mijloc",
  "maskColor": "Culoare mască",
  "options": "Opţiuni",
  "optionsDescription": "Setaţi comportamentul ecranului de pornire."
});