define(
   ({
    id: 'ID',
    state: "Per impostazione predefinita, le coordinate verranno visualizzate nel sistema di coordinate della mappa corrente. Per ottenere le coordinate in altri sistemi di coordinate, è necessario aggiungerle e specificare le trasformazioni appropriate.",
    outputUnit: "Unità di output",
    wkid: "WKID di output",
    label: "Nome sistema di coordinate di output",
    transformationWkid: "WKID trasformazione",
    transformationLabel: "Etichetta trasformazione",
    transformForward: "Trasformazione in avanti",
    actions: "Azioni",
    warning: "Immettere un WKID valido per i riferimenti spaziali.",
    tfWarning: "Immettere un WKID valido per la trasformazione dei riferimenti.",
    spinnerLabel: "Arrotonda le coordinate a: ",
    decimalPlace: "posizioni decimali",
    separator: "Mostra separatore di migliaia",
    getVersionError: "Impossibile ottenere la versione del servizio Geometria",

    add: "Aggiungi sistema di coordinate di output",
    edit: "Modifica sistema di coordinate",
    output: "Sistema di coordinate di output",
    cName: "Nome sistema di coordinate",
    units: "Unità visualizzazione: ",
    datum: "Trasformazione riferimenti",
    tName: "Nome trasformazione",
    tWKIDPlaceHolder: "WKID della trasformazione",
    forward: "Usa trasformazione in avanti",
    ok: "OK",
    cancel: 'Annulla',
    olderVersion: "Il servizio geometria non supporta l\'operazione di trasformazione",
    REPEATING_ERROR: " Il sistema di coordinate è presente nell\'elenco di output.",

    Default: "Impostazione predefinita",
    Inches: "Pollici",
    Foot: "Piedi",
    Yards: "Iarde",
    Miles: "Miglia",
    Nautical_Miles: "Miglia nautiche",
    Millimeters: "Millimetri",
    Centimeters: "Centimetri",
    Meter: "Metri",
    Kilometers: "Chilometri",
    Decimeters: "Decimetri",
    Decimal_Degrees: "Gradi decimali",
    Degree_Minutes_Seconds: "Gradi minuti secondi",
    MGRS: "MGRS",
    USNG: "USNG"
  })
);