define({
  "sourceSetting": "स्रोत सेटिंग खोजें",
  "instruction": "Geocode सेवाओं या फीचर लेयरों को खोज स्रोतों के रूप में जोड़ें और कॉन्फ़िगर करें। ये निर्दिष्ट स्रोत निर्धारित करते हैं कि खोज बॉक्स के भीतर क्या खोज योग्य है।",
  "add": "खोज स्रोत जोड़ें",
  "addGeocoder": "geocoder जोड़ें",
  "geocoder": "Geocoding",
  "setLayerSource": "लेयर स्रोत को सेट करें",
  "setGeocoderURL": "geocoder का URL सेट करें",
  "searchableLayer": "फ़ीचर लेयर",
  "name": "नाम",
  "countryCode": "देश या क्षेत्र कोड",
  "countryCodeEg": "जैसे ",
  "countryCodeHint": "इस मान को खाली छोड़ने से सभी देशों और क्षेत्रों की खोज होगी",
  "generalSetting": "सामान्य सेटिंग्स",
  "allPlaceholder": "सभी खोज के लिए प्लेसहोल्डर पाठ: ",
  "showInfoWindowOnSelect": "पाई गई फीचर या स्थान के लिए पॉप-अप दिखाएं",
  "searchInCurrentMapExtent": "केवल वर्तमान मानचित्र सीमा में खोज करता है",
  "zoomScale": "स्केल को ज़ूम करें",
  "locatorUrl": "जियोकोडर URL",
  "locatorName": "जियोकोडर का नाम",
  "locatorExample": "उदाहरण",
  "locatorWarning": "Geocoding सेवा का यह संस्करण समर्थित नहीं है। यह विजेट Geocoding सेवा 10.1 और ऊपर को समर्थन करता है।",
  "locatorTips": "सुझाव उपलब्ध नहीं हैं क्योंकि Geocoding सेवा सुझाव क्षमता का का समर्थन नहीं करता है।",
  "layerSource": "लेयर स्रोत को सेट करें",
  "searchLayerTips": "सुझाव उपलब्ध नहीं हैं क्योंकि सुविधा सेवा पृष्ठ अंकन क्षमता का समर्थन नहीं करती है।",
  "placeholder": "प्लेसहोल्डर टेक्स्ट",
  "searchFields": "फ़ील्ड खोजें",
  "displayField": "डिस्प्ले फील्ड्स",
  "exactMatch": "सटीक मिलान",
  "maxSuggestions": "अधिकतम सुझाव",
  "maxResults": "अधिकतम परिणाम",
  "enableLocalSearch": "स्थानीय खोज को सक्षम करें",
  "minScale": "न्यूनतम स्केल",
  "minScaleHint": "जब मानचित्र स्केल इस स्केल से बड़ा होता है, तो स्थानीय खोज को लागू किया जाएगा",
  "radius": "त्रिज्या",
  "radiusHint": "मौजूदा मानचित्र केंद्र के चारों ओर एक क्षेत्रफल की त्रिज्या निर्दिष्ट करें जिसे Geocoding उम्मीदवारों के रैंक को बढ़ावा देने के लिए प्रयोग किया जाता है ताकि स्थान के निकटतम उम्मीदवार पहले प्राप्त हों",
  "meters": "मीटर",
  "setSearchFields": "खोज फ़ील्ड को सेट करें",
  "set": "सेट करें",
  "fieldSearchable": "खोज योग्य",
  "fieldName": "नाम",
  "fieldAlias": "उपनाम",
  "ok": "ठीक है",
  "cancel": "रद्द करें",
  "invalidUrlTip": "URL ${URL} अवैध या दुर्गम है।"
});