define(
   ({
    id: 'ID',
    state: "Por padrão, as coordenadas serão exibidas no sistema de coordenadas do mapa atual. Para obter as coordenadas em outros sistemas de coordenadas, é necessário adicioná-los e especificar as transformações apropriadas.",
    outputUnit: "Unidade de Saída",
    wkid: "WKID de Saída",
    label: "Nome do Sistema de Coordenadas de Saída",
    transformationWkid: "WKID da Transformação",
    transformationLabel: "Rótulo da Transformação",
    transformForward: "Transformação Direta",
    actions: "Ações",
    warning: "Insira um WKID de referência espacial válido!",
    tfWarning: "Insira um WKID de transformação de datum válido!",
    spinnerLabel: "Arredondar coordenadas para: ",
    decimalPlace: "casas decimais",
    separator: "Mostrar separadores de milhar",
    getVersionError: "Não é possível obter a versão do Serviço de Geometria",

    add: "Adicionar Sistema de Coordenadas de Saída",
    edit: "Editar Sistema de Coordenadas",
    output: "Sistema de Coordenadas de Saída",
    cName: "Nome do Sistema de Coordenadas",
    units: "Unidades de Exibição: ",
    datum: "Transformação de Datum",
    tName: "Nome da Transformação",
    tWKIDPlaceHolder: "WKID da transformação",
    forward: "Utilizar transformação direta",
    ok: "OK",
    cancel: 'Cancelar',
    olderVersion: "O Serviço de Geometria não suporta a operação de transformação",
    REPEATING_ERROR: " O sistema de coordenadas existe na lista de saída.",

    Default: "Padrão",
    Inches: "Polegadas",
    Foot: "Pés",
    Yards: "Jardas",
    Miles: "Milhas",
    Nautical_Miles: "Milhas Náuticas",
    Millimeters: "Milímetros",
    Centimeters: "Centímetros",
    Meter: "Metros",
    Kilometers: "Quilômetros",
    Decimeters: "Decímetros",
    Decimal_Degrees: "Graus Decimais",
    Degree_Minutes_Seconds: "Graus Minutos Segundos",
    MGRS: "MGRS",
    USNG: "USNG"
  })
);