define({
  "id": "ID",
  "state": "Por padrão, as coordenadas serão exibidas no sistema de coordenadas do mapa atual. Para obter as coordenadas em outros sistemas de coordenadas, é necessário adicioná-los e especificar as transformações apropriadas.",
  "outputUnit": "Unidade de Saída",
  "wkid": "WKID de Saída",
  "label": "Nome do sistema de coordenadas de saída",
  "transformationWkid": "WKID da Transformação",
  "transformationLabel": "Rótulo de transformação",
  "transformForward": "Transformar adiante",
  "actions": "Ações",
  "warning": "Insira um WKID de referência espacial válido!",
  "tfWarning": "Insira um WKID de transformação de datum válido!",
  "spinnerLabel": "Arredondar coordenadas para: ",
  "decimalPlace": "casas decimais",
  "separator": "Mostrar separadores de milhar",
  "getVersionError": "Não é possível obter a versão do serviço de geometria",
  "add": "Adicionar sistema de coordenadas de saída",
  "edit": "Editar sistema de coordenadas",
  "output": "Sistema de Coordenadas de Saída",
  "cName": "Nome do Sistema de Coordenadas",
  "units": "Exibir Unidades: ",
  "datum": "Transformação de datum",
  "tName": "Nome da Transformação",
  "tWKIDPlaceHolder": "WKID da transformação",
  "forward": "Utilizar transformação direta",
  "ok": "OK",
  "cancel": "Cancelar",
  "olderVersion": "O serviço de geometria não suporta a operação de transformação",
  "REPEATING_ERROR": " O sistema de coordenadas existe na lista de saída.",
  "Default": "Padrão",
  "Inches": "Polegadas",
  "Foot": "Pés",
  "Yards": "Jardas",
  "Miles": "Milhas",
  "Nautical_Miles": "Milhas náuticas",
  "Millimeters": "Milímetros",
  "Centimeters": "Centímetros",
  "Meter": "Metros",
  "Kilometers": "Quilômetros",
  "Decimeters": "Decímetros",
  "Decimal_Degrees": "Graus Decimais",
  "Degrees_Decimal_Minutes": "Graus minutos decimais",
  "Degree_Minutes_Seconds": "Graus minutos segundos",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Ordem de visualização de coordenadas:",
  "lonLatTips": "Longitude, Latitude (X, Y)",
  "latLonTips": "Latitude, Longitude (Y, X)"
});