define({
  "instruction": "Wählen Sie Layer aus, die zuerst in der Attributtabelle angezeigt werden, und konfigurieren Sie sie.",
  "label": "Layer",
  "show": "Anzeigen",
  "actions": "Layer-Felder konfigurieren",
  "field": "Feld",
  "alias": "Alias",
  "visible": "Sichtbar",
  "linkField": "Link-Feld",
  "noLayers": "Keine Feature-Layer verfügbar",
  "back": "Zurück",
  "exportCSV": "Export in CSV zulassen",
  "expand": "Zuerst das Widget erweitern",
  "filterByExtent": "Option \"Nach Kartenausdehnung filtern\" standardmäßig aktivieren",
  "restore": "Standardwert wiederherstellen",
  "ok": "OK",
  "cancel": "Abbrechen",
  "includePoint": "Punktkoordinaten in die exportierte Datei einbeziehen",
  "configureLayerFields": "Layer-Felder konfigurieren",
  "result": "Erfolgreich gespeichert",
  "warning": "Wählen Sie zuerst die Option \"Anzeigen\" aus.",
  "fieldCheckWarning": "Es muss mindestens ein Feld ausgewählt werden.",
  "unsupportQueryWarning": "Der Layer muss die Abfrageoperation unterstützen, um im Widget der Attributtabelle angezeigt zu werden. Stellen Sie sicher, dass die Abfragefunktion in dem Service aktiviert ist.",
  "unsupportQueryLayers": "Der folgende Layer muss die Abfrageoperation unterstützen, um im Widget der Attributtabelle angezeigt zu werden. Stellen Sie sicher, dass die Abfragefunktion in dem Service aktiviert ist.",
  "fieldName": "Name",
  "fieldAlias": "Alias",
  "fieldVisibility": "Sichtbarkeit",
  "fieldActions": "Aktionen",
  "showAttachments": "Anlagen anzeigen"
});