define({
  "instruction": "Ekran powitalny jest wyświetlany do czasu, kiedy już można korzystać z aplikacji.",
  "defaultContent": "Tutaj możesz dodać tekst, łącza oraz niewielkie elementy graficzne.",
  "requireConfirm": "Wymagaj potwierdzenia w celu kontynuowania",
  "noRequireConfirm": "Potwierdzenie nie jest wymagane, aby kontynuować",
  "optionText": "Opcja wyłączenia przez użytkownika wyświetlania ekranu powitalnego podczas uruchamiania aplikacji.",
  "confirmLabel": "Tekst potwierdzenia: ",
  "confirmLabelColor": "Kolor tekstu potwierdzenia",
  "defaultConfirmText": "Akceptuję powyższe warunki.",
  "confirmOption": "Pokazuj ten ekran powitalny przy każdorazowym uruchomieniu aplikacji",
  "backgroundColor": "Kolor tła",
  "content": "Zawartość",
  "contentDescription": "Zdefiniuj zawartość wyświetlaną na ekranie powitalnym.",
  "appearance": "Wygląd",
  "appearanceDescription": "Skonfiguruj wygląd ekranu powitalnego.",
  "size": "Rozmiar",
  "width": "Szerokość",
  "height": "Wysokość",
  "custom": "Niestandardowy",
  "background": "Tło",
  "colorFill": "Wypełnienie kolorem",
  "imageFill": "Wypełnienie obrazem",
  "chooseFile": "Wybierz plik",
  "noFileChosen": "Nie wybrano pliku",
  "transparency": "Przezroczystość",
  "sizeFill": "Wypełnienie",
  "sizeFit": "Dopasuj",
  "sizeStretch": "Rozciągnij, aby wypełnić",
  "sizeCenter": "Środek",
  "sizeTile": "Kafel",
  "buttonColor": "Kolor przycisku",
  "buttonText": "Tekst przycisku",
  "buttonTextColor": "Kolor tekstu przycisku",
  "contentAlign": "Wyrównanie zawartości",
  "alignTop": "Góra",
  "alignMiddle": "Na środku",
  "maskColor": "Kolor maski",
  "options": "Opcje",
  "optionsDescription": "Ustaw zachowanie ekranu powitalnego."
});