define({
  "_widgetLabel": "Öznitelik Tablosu",
  "_featureAction_ShowRelatedRecords": "İlgili kayıtları göster",
  "_featureAction_ViewInTable": "Öznitelik Tablosunda Görüntüle",
  "ok": "Tamam",
  "cancel": "İptal",
  "unsupportQueryWarning": "Öznitelik Tablosu aracını görüntülemek için katmanın sorgu işlemini desteklemesi gerekir. Servisteki sorgu yeteneğinin açık olduğundan emin olun.",
  "exportMessage": "Veriler CSV dosyasına aktarılsın mı?",
  "exportFiles": "CSV'ye Aktar",
  "exportSelected": "Seçilenleri CSV dosyasına aktar",
  "exportAll": "Tümünü CSV dosyasına aktar",
  "options": "Seçenekler",
  "zoomto": "Şuna Yakınlaştır",
  "highlight": "Grafikleri vurgula",
  "selectAll": "Tüm sayfalardaki kayıtları seç",
  "selectPage": "Geçerli sayfadaki kayıtları seç",
  "clearSelection": "Seçimi temizle",
  "filter": "Filtrele",
  "setFilterTip": "Filtreleri düzgün şekilde ayarlayın.",
  "noFilterTip": "Tanımlı filtre ifadesi olmadan, bu sorgu görevi belirtilen veri kaynağındaki tüm detayları listeler.",
  "filterByExtent": "Harita yayılımına göre filtrele",
  "showSelectedRecords": "Seçilen kayıtları göster",
  "showAllRecords": "Tüm kayıtları göster",
  "showRelatedRecords": "İlgili kayıtları göster",
  "noRelatedRecords": "İlgili kayıt bulunamadı",
  "attachmentColumn": "Fotoğraflar ve dosyalar",
  "refresh": "Yenile",
  "features": "detaylar",
  "records": "kayıtları",
  "selected": "seçili",
  "transparent": "Saydam mod",
  "indicate": "Seçimi bul",
  "columns": "Sütunları göster/gizle",
  "selectionSymbol": "Seçim sembolü",
  "closeMessage": "Tabloyu gizle (yeniden alttan genişletin)",
  "dataNotAvailable": "Veri yok!<br>Yeniden denemek için [Yenile] düğmesine tıklayın.",
  "openTableTip": "Öznitelik Tablosunu Aç",
  "closeTableTip": "Öznitelik Tablosunu Gizle",
  "sortAsc": "Artan sıralama",
  "sortDes": "Azalan sıralama",
  "statistics": "İstatistikler",
  "attachments": "Ekler",
  "files": "dosyalar"
});