define(
   ({
    _widgetLabel: "Öznitelik Tablosu",
    ok: "Tamam",
    cancel: "İptal",
    unsupportQueryWarning: "Öznitelik Tablosu aracını görüntülemek için katmanın sorgu işlemini desteklemesi gerekir. Servisteki sorgu yeteneğinin açık olduğundan emin olun.",
    exportMessage: "Veriler CSV dosyasına aktarılsın mı?",
    exportFiles: "CSV\'ye Aktar",
    exportSelected: "Seçilenleri CSV Dosyasına Aktar",
    exportAll: "Tümünü CSV Dosyasına Aktar",
    options: "Seçenekler",
    zoomto: "Şuna Yakınlaştır",
    highlight: "Grafikleri Vurgula",
    selectAll: "Tüm Sayfalardaki Kayıtları Seç",
    selectPage: "Geçerli Sayfadaki Kayıtları Seç",
    clearSelection: "Seçimi Temizle",
    filter: "Filtrele",
    setFilterTip: "Filtreyi düzgün şekilde ayarlayın.",
    noFilterTip: "Tanımlı filtre ifadesi olmadan, bu sorgu görevi belirtilen veri kaynağındaki tüm detayları listeleyecektir.",
    filterByExtent: "Harita Yayılımına Göre Filtrele",
    showSelectedRecords: "Seçili Kayıtları Göster",
    showAllRecords: "Tüm Kayıtları Göster",
    showRelatedRecords: "İlgili Kayıtları Göster",
    noRelatedRecords: "İlgili Kayıt Yok",
    refresh: "Yenile",
    features: "detaylar",
    selected: "seçili",
    transparent: "Saydam Mod",
    indicate: "Yerel Ayar Seçimi",
    columns: "Sütunları Göster/Gizle",
    selectionSymbol: "Seçim Simgesi",
    closeMessage: "Tabloyu Gizle (yeniden alttan genişletin)",
    dataNotAvailable: "Veri yok!<br>Yeniden denemek için [Yenile] düğmesine tıklayın.",
    openTableTip: "Öznitelik Tablosunu Aç",
    closeTableTip: "Öznitelik Tablosunu Gizle"
  })
);