define({
  "_widgetLabel": "Координаты",
  "hintMessage": "Щелкните карту, чтобы получить координаты",
  "defaultLabel": "По умолчанию",
  "realtimeLabel": "Переместите курсор, чтобы получить координаты",
  "computing": "Вычисление...",
  "latitudeLabel": "Широта",
  "longitudeLabel": "Долгота",
  "loading": "загрузка...",
  "enableClick": "Щелкните, чтобы включить получение координат по щелчку на карте",
  "disableClick": "Щелкните, чтобы отключить получение координат по щелчку на карте",
  "Default": "По умолчанию",
  "Inches": "Дюймы",
  "Foot": "Футы",
  "Yards": "Ярды",
  "Miles": "Мили",
  "Nautical_Miles": "Морские мили",
  "Millimeters": "Миллиметры",
  "Centimeters": "Сантиметры",
  "Meter": "Метры",
  "Kilometers": "Километры",
  "Decimeters": "Дециметры",
  "Decimal_Degrees": "Градусы",
  "Degree_Minutes_Seconds": "Градусы минуты секунды",
  "MGRS": "MGRS",
  "USNG": "USNG"
});