define({
  "instruction": "Az üdvözlőablak az alkalmazás megnyitása előtt jelenik meg.",
  "defaultContent": "Itt adhatja hozzá a szövegeket, linkeket és kis méretű grafikákat.",
  "requireConfirm": "Megerősítés kérése a folytatáshoz",
  "noRequireConfirm": "Ne kérjen megerősítést a folytatáshoz",
  "optionText": "Beállítás, amellyel a felhasználó letilthatja az alkalmazás indításakor megjelenő üdvözlőablakot.",
  "confirmLabel": "Megerősítő szövegek: ",
  "confirmLabelColor": "Megerősítő szövegek színe",
  "defaultConfirmText": "Elfogadom a fenti felhasználási feltételeket",
  "confirmOption": "Az alkalmazás minden indításakor jelenjen meg ez az üdvözlőablak",
  "backgroundColor": "Háttérszín",
  "content": "Tartalom",
  "contentDescription": "Határozza meg az üdvözlőablakban megjelenő tartalmat.",
  "appearance": "Megjelenés",
  "appearanceDescription": "Állítsa be az üdvözlőablak megjelenését.",
  "size": "Méret",
  "width": "Szélesség",
  "height": "Magasság",
  "custom": "Egyéni",
  "background": "Háttér",
  "colorFill": "Színkitöltés",
  "imageFill": "Képkitöltés",
  "chooseFile": "Válasszon fájlt",
  "noFileChosen": "Nincs kiválasztva fájl",
  "transparency": "Átlátszóság",
  "sizeFill": "Kitöltés",
  "sizeFit": "Igazítás",
  "sizeStretch": "Méretre nyújtás",
  "sizeCenter": "Középen",
  "sizeTile": "Csempe",
  "buttonColor": "Gombszín",
  "buttonText": "Gombfelirat",
  "buttonTextColor": "Gombfelirat színe",
  "contentAlign": "Tartalomigazítás",
  "alignTop": "Fent",
  "alignMiddle": "Középre",
  "maskColor": "Maszkszín",
  "options": "Beállítások",
  "optionsDescription": "Állítsa be az üdvözlőablak viselkedését."
});