define({
  "instruction": "Chọn và cấu hình các lớp sẽ được hiển thị ban đầu trong Bảng Thuộc tính.",
  "label": "Lớp",
  "show": "Hiển thị",
  "actions": "Cấu hình trường của lớp dữ liệu",
  "field": "Trường",
  "alias": "Bí danh",
  "visible": "Hiển thị",
  "linkField": "Trường liên kết",
  "noLayers": "Không có lớp đối tượng nào",
  "back": "Quay lại",
  "exportCSV": "Cho phép xuất ra CSV",
  "expand": "Mở rộng tiện ích lúc ban đầu",
  "filterByExtent": "Bật lọc theo phạm vi bản đồ mặc định",
  "restore": "Khôi phục về giá trị mặc định",
  "ok": "OK",
  "cancel": "Hủy",
  "includePoint": "Bao gồm tọa độ điểm tới tệp được xuất",
  "configureLayerFields": "Cấu hình Trường Lớp",
  "result": "Đã lưu thành công",
  "warning": "Vui lòng chọn tùy chọn Hiển thị trước.",
  "fieldCheckWarning": "Phải chọn ít nhất một trường.",
  "unsupportQueryWarning": "Lớp cần hỗ trợ hoạt động truy vấn để hiển thị trong tiện ích Bảng Thuộc tính. Đảm bảo khả năng truy vấn trong dịch vụ được bật.",
  "unsupportQueryLayers": "Lớp sau cần hỗ trợ hoạt động truy vấn để hiển thị trong tiện ích Bảng Thuộc tính. Chắc chắn rằng khả năng truy vấn trong dịch vụ đã được bật.",
  "fieldName": "Tên",
  "fieldAlias": "Bí danh",
  "fieldVisibility": "Khả năng hiển thị",
  "fieldActions": "Các hành động",
  "showAttachments": "Hiển thị tệp đính kèm"
});