define({
  "_widgetLabel": "निर्देशांक",
  "hintMessage": "निर्देशांक प्राप्त करने के लिए मानचित्र क्लिक करें",
  "defaultLabel": "डिफॉल्ट",
  "realtimeLabel": "निर्देशांक प्राप्त करने के लिए माउस हिलाएं",
  "computing": "कम्प्यूटिंग...",
  "latitudeLabel": "अक्षांश",
  "longitudeLabel": "देशान्तर",
  "loading": "लोड हो रहा है ...",
  "enableClick": "सक्षम होने के लिए क्लिक करें निर्देशांक प्राप्त करने के लिए मानचित्र पर क्लिक करें",
  "disableClick": "अक्षम करने के लिए क्लिक करें निर्देशांक प्राप्त करने के लिए मानचित्र पर क्लिक करें",
  "Default": "डिफॉल्ट",
  "Inches": "इंच",
  "Foot": "फ़ीट",
  "Yards": "गज",
  "Miles": "मील",
  "Nautical_Miles": "समुद्री मील",
  "Millimeters": "मिलीमीटर",
  "Centimeters": "सेंटीमीटर",
  "Meter": "मीटर",
  "Kilometers": "किलोमीटर",
  "Decimeters": "डेसीमीटर",
  "Decimal_Degrees": "डिग्री",
  "Degree_Minutes_Seconds": "डिग्री मिनट सेकंड",
  "MGRS": "MGRS",
  "USNG": "USNG"
});