define({
  "instruction": "Màn hình splash xuất hiện trước khi có thể truy cập vào ứng dụng.",
  "defaultContent": "Thêm văn bản, liên kết và đồ họa nhỏ ở đây.",
  "requireConfirm": "Yêu cầu xác nhận để tiếp tục",
  "noRequireConfirm": "Không yêu cầu xác nhận để tiếp tục",
  "optionText": "Tùy chọn dành cho người sử dụng để tắt màn hình splash khi khởi động ứng dụng.",
  "confirmLabel": "Văn bản xác nhận: ",
  "confirmLabelColor": "Màu văn bản xác nhận",
  "defaultConfirmText": "Tôi đồng ý với các điều khoản và điều kiện bên trên",
  "confirmOption": "Luôn hiển thị màn hình splash này mỗi khi khởi chạy ứng dụng",
  "backgroundColor": "Màu Nền",
  "content": "Nội dung",
  "contentDescription": "Xác định nội dung hiển thị trên màn hình splash.",
  "appearance": "Giao diện",
  "appearanceDescription": "Thiết lập giao diện của màn hình splash.",
  "size": "Kích cỡ",
  "width": "Chiều rộng",
  "height": "Chiều cao",
  "custom": "Tùy chỉnh",
  "background": "Nền",
  "colorFill": "Đổ màu",
  "imageFill": "Đổ hình ảnh",
  "chooseFile": "Chọn tệp",
  "noFileChosen": "Không có tệp được chọn",
  "transparency": "Độ trong suốt",
  "sizeFill": "Tô",
  "sizeFit": "Đặt vừa",
  "sizeStretch": "Kéo để đổ",
  "sizeCenter": "Tâm",
  "sizeTile": "Tile",
  "buttonColor": "Nút màu",
  "buttonText": "Văn bản của nút",
  "buttonTextColor": "Màu văn bản của nút",
  "contentAlign": "Căn chỉnh nội dung",
  "alignTop": "Trên cùng",
  "alignMiddle": "Giữa",
  "maskColor": "Màu mặt nạ",
  "options": "Tùy chọn",
  "optionsDescription": "Thiết lập hành vi của màn hình splash."
});