define({
  "_widgetLabel": "Lagerlista",
  "titleBasemap": "Baskartor",
  "titleLayers": "Funktionslager",
  "labelLayer": "Lagernamn",
  "itemZoomTo": "Zooma till",
  "itemTransparency": "Transparens",
  "itemTransparent": "Transparent",
  "itemOpaque": "Opak",
  "itemMoveUp": "Flytta uppåt",
  "itemMoveDown": "Flytta nedåt",
  "itemDesc": "Beskrivning",
  "itemDownload": "Hämta",
  "itemToAttributeTable": "Visa i attributtabell",
  "itemShowItemDetails": "Visa objektinformation",
  "empty": "tom",
  "removePopup": "Inaktivera popupfönster",
  "enablePopup": "Aktivera popupfönster",
  "turnAllLayersOff": "Inaktivera alla lager",
  "turnAllLayersOn": "Aktivera alla lager",
  "expandAllLayers": "Expandera alla lager",
  "collapseAlllayers": "Dölj alla lager",
  "turnAllLabelsOff": "Inaktivera alla etiketter",
  "turnAllLabelsOn": "Aktivera alla etiketter",
  "showLabels": "Visa etiketter",
  "hideLables": "Dölj etiketter"
});