define({
  "common": {
    "apply": "लागू करें",
    "ok": "ठीक है",
    "cancel": "रद्द करें",
    "yes": "हाँ",
    "no": "नहीं",
    "next": "अगला",
    "previous": "पिछला",
    "back": "पीछे जाएँ",
    "selected": "चयनित",
    "name": "नाम",
    "usage": "उपयोग",
    "settings": "सेटिंग्स",
    "home": "होम",
    "link": "लिंक",
    "messages": "संदेश",
    "outputs": "आउटपुट",
    "title": "शीर्षक",
    "thumbnail": "थंबनेल",
    "url": "URL",
    "actions": "कार्रवाइयाँ",
    "layer": "लेयर",
    "action": "कार्रवाई",
    "input": "इनपुट",
    "output": "आउटपुट",
    "type": "प्रकार",
    "required": "अनिवार्य",
    "options": "विकल्प",
    "label": "लेबल",
    "tooltip": "टूलटिप",
    "visible": "दृश्य",
    "symbol": "चिह्न",
    "popup": "पॉप-अप",
    "upload": "अपलोड करें",
    "execute": "निष्पादित करें",
    "help": "सहायता",
    "executing": "निष्पादित करना",
    "clear": "हटाएं",
    "error": "त्रुटि",
    "zoomTo": "जूम करें",
    "attribute": "विशेषता",
    "exports": "निर्यात करें",
    "check": "जाँच करें",
    "save": "सहेजें",
    "close": "बंद करें",
    "deleteText": "हटाएँ",
    "map": "मानचित्र",
    "scene": "दृश्य",
    "reset": "रीसेट करें",
    "icon": "आइकॉन",
    "folder": "फ़ोल्डर",
    "share": "साझा करें",
    "view": "दृश्य",
    "newText": "नया",
    "edit": "संपादित करें",
    "wkid": "WKID",
    "table": "तालिका",
    "zoomIn": "ज़ूम इन",
    "zoomOut": "जूम आउट",
    "continue1": "जारी रखें",
    "longitude": "देशान्तर",
    "latitude": "अक्षांश",
    "custom": "कस्टम",
    "image": "छवि",
    "font": "फॉन्ट",
    "text": "पाठ",
    "all": "सभी",
    "number": "संख्या",
    "percentage": "प्रतिशत",
    "unit": "इकाई",
    "thousand": "हज़ार",
    "billion": "बिलीयन",
    "million": "मिलीयन",
    "none": "कोई नहीं",
    "field": "फ़ील्ड",
    "operation": "परिचालन",
    "disableUpdateGeometry": "Geometry अपडेट को अक्षम करें",
    "preview": "पूर्वावलोकन करें"
  },
  "errorCode": "कोड",
  "errorMessage": "संदेश",
  "errorDetail": "विवरण",
  "widgetPlaceholderTooltip": "इसे निर्धारित करने के लिए, विजेट्स पर जाएं और संबंधित प्लेसहोल्डर पर क्लिक करें",
  "fieldStatistics": {
    "selectField": "फ़ील्ड का चयन करें",
    "statistics": "आँकड़े",
    "field": "फ़ील्ड",
    "count": "मानों की संख्या",
    "sum": "मानों का योग",
    "min": "न्यूनतम",
    "max": "अधिकतम",
    "ave": "औसत",
    "stddev": "मानक विचलन"
  },
  "symbolChooser": {
    "preview": "पूर्वावलोकन करें",
    "basic": "बेसिक",
    "arrows": "तीर",
    "business": "व्यापार",
    "cartographic": "कार्टोग्राफिक",
    "nationalParkService": "राष्ट्रीय पार्क सर्विस",
    "outdoorRecreation": "बाहरी मनोरंजन",
    "peoplePlaces": "सार्वजनिक स्थान",
    "safetyHealth": "सुरक्षा स्वास्थ्य",
    "shapes": "आकृतियाँ",
    "transportation": "यातायात",
    "symbolSize": "चिन्ह का आकार",
    "color": "रंग",
    "alpha": "अल्फा",
    "outlineColor": "बाह्यरेखा का रंग",
    "outlineWidth": "बाह्यरेखा की चौड़ाई",
    "style": "शैली",
    "width": "चौड़ाई",
    "text": "पाठ",
    "fontColor": "फ़ॉन्ट का रंग",
    "fontSize": "फ़ॉन्ट का आकर",
    "transparency": "पारदर्शिता",
    "solid": "ठोस",
    "dash": "डैश",
    "dot": "बिंदु",
    "dashDot": "डैश डॉट",
    "dashDotDot": "डैश डॉट डॉट",
    "customImage": "कस्टम छवि",
    "chooseFile": "फ़ाइल का चयन करें",
    "noFileChoosen": "किसी फाइल एक चयन नहीं किया गया है।"
  },
  "transparency": {
    "opaque": "अपारदर्शी",
    "transparent": "पारदर्शी"
  },
  "rendererChooser": {
    "domain": "डोमेन",
    "use": "उपयोग करें",
    "singleSymbol": "एकल प्रतीक",
    "uniqueSymbol": "अद्वितीय या अनोखे सिंबल या चिन्ह",
    "color": "रंग",
    "size": "आकार",
    "toShow": "दिखाने के लिए",
    "colors": "रंग",
    "classes": "कक्षाएँ या वर्ग",
    "symbolSize": "चिन्ह का आकार",
    "addValue": "मान जोड़ें",
    "setDefaultSymbol": "डिफ़ॉल्ट प्रतीक सेट करें",
    "defaultSymbol": "डिफ़ॉल्ट चिन्ह",
    "selectedSymbol": "चयनित प्रतीक",
    "value": "मान",
    "label": "लेबल",
    "range": "सीमा"
  },
  "drawBox": {
    "point": "बिन्दु",
    "line": "रेखा",
    "polyline": "बहुरेखा",
    "freehandPolyline": "मुक्तहस्त बहुरेखा",
    "triangle": "त्रिभुज",
    "extent": "सीमा",
    "circle": "वृत्त",
    "ellipse": "अंडाकार",
    "polygon": "बहुभुज",
    "freehandPolygon": "मुक्तहस्त बहुभुज",
    "text": "पाठ",
    "clear": "हटाएं"
  },
  "popupConfig": {
    "title": "शीर्षक",
    "add": "जोड़ें",
    "fields": "फ़ील्ड्स",
    "noField": "कोई फील्ड नहीं",
    "visibility": "दृश्य",
    "name": "नाम",
    "alias": "उपनाम",
    "actions": "कार्रवाइयाँ"
  },
  "includeButton": {
    "include": "शामिल करें"
  },
  "loadingShelter": {
    "loading": "लोड हो रहा है"
  },
  "basicServiceBrowser": {
    "noServicesFound": "कोई सेवा नहीं मिली।",
    "unableConnectTo": "इससे कनेक्ट करने में असमर्थ",
    "invalidUrlTip": "आपके द्वारा दर्ज किया गया URL अमान्य या पहुँच योग्य नहीं है."
  },
  "serviceBrowser": {
    "noGpFound": "कोई जियोप्रोसेसिंग सेवा नहीं मिली।",
    "unableConnectTo": "इससे कनेक्ट करने में असमर्थ"
  },
  "layerServiceBrowser": {
    "noServicesFound": "कोई मैप संबंधी सेवा या सुविधा सेवा नहीं मिली।",
    "unableConnectTo": "इससे कनेक्ट करने में असमर्थ"
  },
  "basicServiceChooser": {
    "validate": "मान्य करें",
    "example": "उदाहरण",
    "set": "सेट करें"
  },
  "urlInput": {
    "invalidUrl": "अमान्य URL."
  },
  "urlComboBox": {
    "invalidUrl": "अमान्य URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "अभिव्यक्ति जोड़ें",
    "addSet": "कोई सेट जोड़ें",
    "matchMsg": "लेयर में फीचर प्राप्त करें जो निम्न समीकरणों से मेल ${any_or_all} खाती हैं।",
    "matchMsgSet": "इस सेट की निम्न अभिव्यक्तियों में से ${any_or_all} सही हैं",
    "all": "सभी",
    "any": "कोई",
    "value": "मान",
    "field": "फ़ील्ड",
    "unique": "अद्वितीय",
    "none": "कोई नहीं",
    "and": "और",
    "valueTooltip": "मान दर्ज करें",
    "fieldTooltip": "मौजूदा फ़ील्ड में से चुनें",
    "uniqueValueTooltip": "चयनित फ़ील्ड में अद्वितीय मानों में से चुनें",
    "stringOperatorIs": "है",
    "stringOperatorIsNot": "नहीं है",
    "stringOperatorStartsWith": "इससे प्रारंभ होने वाला",
    "stringOperatorEndsWith": "इस पर समाप्त होने वाला",
    "stringOperatorContains": "शामिल करता है",
    "stringOperatorDoesNotContain": "इसमें शामिल नहीं",
    "stringOperatorIsBlank": "खाली है",
    "stringOperatorIsNotBlank": "खाली नहीं है",
    "dateOperatorIsOn": "पर है",
    "dateOperatorIsNotOn": "पर नहीं है",
    "dateOperatorIsBefore": "पहले का है",
    "dateOperatorIsAfter": "बाद का है",
    "dateOperatorIsOnOrBefore": "इस दिनांक को या उससे पहले है",
    "dateOperatorIsOnOrAfter": "इस दिनांक को या उसके बाद है",
    "dateOperatorMinutes": "मिनट",
    "dateOperatorHours": "घंटे",
    "dateOperatorDays": "दिन",
    "dateOperatorWeeks": "सप्ताह",
    "dateOperatorMonths": "महीने",
    "dateOperatorYears": "वर्ष",
    "dateOperatorInTheLast": "अंतिम में",
    "dateOperatorNotInTheLast": "अंतिम में नहीं",
    "dateOperatorIsBetween": "बीच में",
    "dateOperatorIsNotBetween": "बीच का नहीं है",
    "dateOperatorIsBlank": "खाली है",
    "dateOperatorIsNotBlank": "खाली नहीं है",
    "numberOperatorIs": "है",
    "numberOperatorIsNot": "नहीं है",
    "numberOperatorIsAtLeast": "कम से कम",
    "numberOperatorIsLessThan": "से कम",
    "numberOperatorIsAtMost": "अधिकतम है",
    "numberOperatorIsGreaterThan": "से अधिक है",
    "numberOperatorIsBetween": "बीच में",
    "numberOperatorIsNotBetween": "बीच का नहीं है",
    "numberOperatorIsBlank": "खाली है",
    "numberOperatorIsNotBlank": "खाली नहीं है",
    "string": "स्ट्रिंग",
    "number": "संख्या",
    "date": "तिथि",
    "askForValues": "मानों के बारे में पूछें",
    "prompt": "संकेत",
    "hint": "परोक्ष संकेत",
    "error": {
      "invalidParams": "अमान्य पैरामीटर।",
      "invalidUrl": "अमान्य URL.",
      "noFilterFields": "लेयर में कोई फ़ील्ड नहीं हैं, जिन्हें फिल्टर बनाने के लिए इस्तेमाल किया जा सकता है।",
      "invalidSQL": "अमान्य SQL समीकरण।",
      "cantParseSQL": "SQL समीकरण को पार्स नहीं किया जा सकता है।"
    },
    "caseSensitive": "अक्षर संवेदनशील",
    "notSupportCaseSensitiveTip": "होस्ट की गई सेवाएं अक्षर संवेदनशील क्वेरी को समर्थित नहीं करती हैं।",
    "setFilterTip": "कृपया फिल्टर को सही ढंग से निर्धारित करें।",
    "listValues": "मानों को सूचीबद्ध करें",
    "cascadeFilterTip": "केवल पिछले समीकरणों द्वारा फ़िल्टर मान दिखाएँ।",
    "noneCascadeFilterTip": "इस फील्ड के सभी यूनीक मान",
    "previousCascadeFilterTip": "पिछले समीकरणों द्वारा फ़िल्टर मान",
    "allCascadeFilterTip": "अन्य सभी समीकरणों द्वारा फ़िल्टर मान"
  },
  "featureLayerSource": {
    "layer": "लेयर",
    "browse": "ब्राउज करें",
    "selectFromMap": "मानचित्र",
    "selectFromPortal": "ArcGIS का पोर्टल",
    "addServiceUrl": "सेवा URL",
    "inputLayerUrl": "इनपुट लेयर URL",
    "selectLayer": "वर्तमान मानचित्र से एक फीचर लेयर का चयन करें।",
    "chooseItem": "फ़ीचर लेयर आइटम चुनें.",
    "setServiceUrl": "सुविधा सेवा या मैप संबंधी सेवा का URL दर्ज करें।",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "फ़ीचर लेयर चुनें."
  },
  "queryableLayerSource": {
    "layer": "लेयर",
    "browse": "ब्राउज करें",
    "selectFromMap": "मानचित्र",
    "selectFromPortal": "ArcGIS का पोर्टल",
    "addServiceUrl": "सेवा URL",
    "inputLayerUrl": "इनपुट लेयर URL",
    "selectLayer": "वर्तमान मानचित्र से एक लेयर का चयन करें।",
    "chooseItem": "किसी आइटम का चयन करें।",
    "setServiceUrl": "सेवा का URL दर्ज करें।",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "एक लेयर का चयन करें।"
  },
  "gpSource": {
    "selectFromPortal": "ArcGIS का पोर्टल",
    "addServiceUrl": "सेवा URL",
    "selectFromOnline": "ArcGIS Online",
    "setServiceUrl": "जियोप्रोसेसिंग सेवा का URL दर्ज करें।",
    "chooseItem": "एक geoprocessing सेवा आइटम का चयन करें।",
    "chooseTask": "एक geoprocessing कार्य चुनें।"
  },
  "itemSelector": {
    "map": "मानचित्र",
    "selectWebMap": "वेब मैप चुनें",
    "addMapFromOnlineOrPortal": "ArcGIS ऑनलाइन सार्वजनिक संसाधनों या ArcGIS ऑनलाइन या पोर्टल में अपनी निजी सामग्री से ऐप्लिकेशन में एक वेब मानचित्र खोजें या जोड़ें।",
    "searchMapName": "मानचित्र नाम से खोजें...",
    "searchNone": "हम आप जो खोज रहे थे उन्हें खोज नहीं पाए। कृपया पुन: प्रयास करें।",
    "groups": "समूह",
    "noneGroups": "कोई समूह नहीं",
    "signInTip": "आपका लॉग इन सत्र समाप्त हो गया है, फिर से अपने पोर्टल में साइन इन करने के लिए कृपया अपने ब्राउज़र को ताज़ा करें।",
    "signIn": "साइन इन करें",
    "publicMap": "सार्वजनिक",
    "myOrganization": "मेरा संगठन",
    "myGroup": "मेरे समूह",
    "myContent": "मेरी सामग्री",
    "count": "गणना",
    "fromPortal": "पोर्टल से",
    "fromOnline": "ArcGIS.com से",
    "noneThumbnail": "थंबनेल उपलब्ध नहीं है",
    "owner": "स्वामी",
    "signInTo": "यहाँ साइन इन करें",
    "lastModified": "अंतिम संशोधन",
    "moreDetails": "अधिक जानकारी",
    "mostRecent": "सबसे हाल का",
    "mostViewed": "सबसे ज्यादा देखा गया",
    "highestRated": "सर्वोच्च रेट किए गए",
    "viewItemDetails": "आइटम विवरण देखें"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "सेवा क्वेरी का समर्थन नहीं करती है।"
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "मानचित्र में कोई उचित लेयर उपलब्ध नहीं है।"
  },
  "layerInfosMenu": {
    "titleBasemap": "बेसमैप",
    "titleLayers": "ऑपरेशनल लेयर्स",
    "labelLayer": "लेयर का नाम",
    "itemZoomTo": "जूम करें",
    "itemTransparency": "पारदर्शिता",
    "itemTransparent": "पारदर्शी",
    "itemOpaque": "अपारदर्शी",
    "itemMoveUp": "ऊपर जाएँ",
    "itemMoveDown": "नीचे जाएँ",
    "itemDesc": "विवरण",
    "itemDownload": "डाउनलोड करें",
    "itemToAttributeTable": "विशेषता तालिका में दिखाएँ"
  },
  "imageChooser": {
    "unsupportReaderAPI": "कार्यसूची: ब्राउज़र फ़ाइल रीडर API का समर्थन नहीं करता है",
    "readError": "फ़ाइल को पढ़ने में विफल।",
    "unknowError": "कार्यों को पूरा करने में असमर्थ",
    "invalidType": "अमान्य फ़ाइल प्रकार।",
    "cropImage": "तस्वीर क्रॉप करें",
    "exceed": "फ़ाइल का आकार 1024 KB से अधिक नहीं हो सकता है",
    "enableFlash": "कृपया एक छवि ब्राउज़ करने से पहले एडोब फ्लैश को सक्षम करें।",
    "cropWaining": "कृपया ऐसे तस्वीर का चयन करें जिसके कम से कम ${width} x ${height} पिक्सल हों।",
    "toolTip": "सबसे अच्छा परिणामों के लिए, छवि ${width} पिक्सेल चौड़ी x ${height} पिक्सेल उंची होनी चाहिए। अन्य आकार फिट करने के लिए समायोजित किए जाएंगे। स्वीकार्य छवि फॉर्मेट हैं: PNG, GIF और JPEG।"
  },
  "simpleTable": {
    "moveUp": "ऊपर जाएँ",
    "moveDown": "नीचे जाएँ",
    "deleteRow": "हटाएँ",
    "edit": "संपादित करें"
  },
  "urlParams": {
    "invalidToken": "अमान्य टोकन",
    "validateTokenError": "अमान्य टोकन या नेटवर्क त्रुटि"
  },
  "exportTo": {
    "exportTo": "निर्यात करें",
    "toCSV": "CSV फ़ाइल पर निर्यात करें",
    "toFeatureCollection": "सुविधा संग्रह पर निर्यात करें",
    "toGeoJSON": "GeoJSON पर निर्यात करें"
  },
  "appState": {
    "title": "ऐप की स्थिति",
    "restoreMap": "जहाँ से अपने छोड़ा था वहां से मानचित्र सीमा और लेयर की दृश्यता को बहाल करने के लिए क्लिक करें।"
  },
  "featureActions": {
    "featureActions": "फ़ीचर क्रियाएं",
    "ZoomTo": "जूम करें",
    "PanTo": "इस पर पैन करें",
    "Flash": "फ़्लैश",
    "ShowPopup": "पॉपअप दिखाएँ",
    "CreateLayer": "लेयर बनाएँ",
    "ShowStatistics": "आँकड़े...",
    "ClearSelection": "चयन मिटायें",
    "ExportToCSV": "CSV फ़ाइल पर निर्यात करें",
    "ShowSelectedFeature": "चयनित सुविधाएँ दिखाएँ",
    "ExportToFeatureCollection": "सुविधा संग्रह पर निर्यात करें",
    "ExportToGeoJSON": "GeoJSON पर निर्यात करें",
    "EditAttributes": "विशेषताओं को संपादित करें",
    "AddMarker": "एक मार्कर जोड़े",
    "RemoveMarker": "मार्कर निकालें",
    "SaveToMyContent": "मेरी सामग्री में सहेजें"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "संबंधित लेयर",
    "selectedFeatures": "चयनित फीचर्स का प्रयोग करें",
    "drawShapesTip": "फीचर्स का चयन करने के लिए आकार बनाएँ",
    "pleaseDrawShapesTip": "कृपया फीचर्स का चयन करने के लिए आकार बनाएँ",
    "allFeaturesTip": "लेयर में सभी फीचर्स",
    "selectFeaturesOrDrawShapesTip": "कृप्या इस लेयर में चयनित सुविधाओं का उपयोग करें या सुविधाओं को सीमित करने के लिए मैप पर आकार बनाएँ।"
  },
  "searchDistance": {
    "applySearchDistance": "एक खोज दूरी लागू करें",
    "applySearchDistanceToFeatures": "चयनित फीचर्स के लिए एक खोज दूरी लागू करें"
  },
  "units": {
    "miles": "मील",
    "milesAbbr": "mi",
    "kilometers": "किलोमीटर",
    "kilometersAbbr": "km",
    "feet": "फ़ीट",
    "feetAbbr": "ft",
    "meters": "मीटर",
    "metersAbbr": "m",
    "yards": "गज",
    "yardsAbbr": "गज",
    "acres": "एकड़",
    "acresAbbr": "एकड़",
    "nauticalMiles": "समुद्री मील",
    "nauticalMilesAbbr": "nmi",
    "uSSurveyFeet": "यूएस सर्वेक्षण फ़ीट",
    "uSSurveyFeetAbbr": "ftUS",
    "decimalDegree": "दशमलव डिग्रीज़",
    "decimalDegreeAbbr": "dd",
    "degreeMinuteSeconds": "डिग्री मिनट सेकंड",
    "degreeMinuteSecondsAbbr": "दिन-मि-से.",
    "squareMiles": "वर्ग मील",
    "squareMilesAbbr": "वर्ग मील",
    "squareKilometer": "वर्ग किलोमीटर",
    "squareKilometerAbbr": "वर्ग किमी",
    "squareFeet": "वर्ग फीट",
    "squareFeetAbbr": "वर्ग फीट",
    "squareMeters": "वर्ग मीटर",
    "squareMetersAbbr": "वर्ग मीटर",
    "squareYards": "वर्ग गज",
    "squareYardsAbbr": "वर्ग गज",
    "squareUSSurveyFeet": "वर्ग यूएस सर्वे फ़ीट",
    "squareUSSurveyFeetAbbr": "वर्ग मूल यूएस"
  },
  "featureSetChooser": {
    "select": "चुनें",
    "dragBox": "खींचें",
    "dragMouse": "माउस खींचें",
    "selectByRectangle": "आयत के अनुसार चयन करें",
    "selectFeaturesTip": "मानचित्र पर उनके चारों ओर बॉक्स खींचकर फीचर्स का चयन करें",
    "newSelectionTip": "नया चयन बनाएं",
    "addSelectionTip": "चयन में जोड़ें",
    "removeSelectionTip": "चयन से हटाएँ",
    "selectFromCurrentSelectionTip": "वर्तमान चयन से चुनें",
    "unselectAllSelectionTip": "वर्तमान में चयनित सभी फीचर्स को अचयनित करें",
    "selectByPolygon": "बहुभुज के अनुसार चयन करें",
    "selectByCircle": "वृत्त के अनुसार चयन करें",
    "selectByLine": "रेखा के अनुसार चयन करें",
    "chooseSelectingTools": "चयन करने वाले टूल्स चुनें",
    "darw": "बनाएं",
    "drawShap": "एक आकार बनाएं"
  },
  "widgetManager": {
    "createWidgetError": "विजेट त्रुटि बनाएं",
    "createWidgetSettingPageError": "विजेट सेटिंग पृष्ठ त्रुटि बनाएं",
    "loadWidgetResourceError": "विजेट संसाधन त्रुटी लोड करें"
  },
  "shareOptions": {
    "shareMap": "चुनें जो इस ऐप्लीकेशन को देख सकते हैं",
    "shareMapTips": "आपकी ऐप्लिकेशन वर्तमान में इन लोगों के साथ साझा है",
    "everyone": "हर कोई",
    "theseGroups": "इन समूहों से"
  },
  "shareLink": {
    "email": "ईमेल",
    "shareEmail": "ईमेल",
    "facebook": "facebook",
    "shareFacebook": "Facebook",
    "twitter": "twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "इस ऐप्लीकेशन को एक वेबसाइट में सम्मिलित करें",
    "shareEmailSubject": "वेब ऐप्लीकेशन साझा करना:",
    "shareEmailTxt1": "यहाँ ArcGIS के लिए वेब AppBuilder का उपयोग करके एक वेब ऐप्लीकेशन आपके साथ साझा की गई है।",
    "shareEmailTxt2": "आप ArcGIS के लिए ESRI वेब AppBuilder के साथ अपने स्वयं की वेब ऐप्लीकेशन बना और साझा कर सकते हैं।",
    "shareEmailTxt3": "जानकारी के लिए http://www.esri.com/software/web-appbuilder पर जाएं।",
    "smallSize": "छोटा",
    "mediumSize": "मध्यम",
    "largeSize": "बड़ा",
    "customSize": "कस्टम",
    "embed": "इस ऐप्लीकेशन को एक वेबसाइट में सम्मिलित करें",
    "more": "इंबेड विकल्प",
    "changeShareSettings": "साझा करने से संबंधित सेटिंग बदलें",
    "shareLinkText": "इस ऐप्लिकेशन का लिंक साझा करें",
    "linkOptions": "लिंक के विकल्प",
    "linkOptionsUrlParameters": "चुनिंदा URL पैरामीटर लिंक में शामिल हैं",
    "currentMapExtent": "वर्तमान मानचित्र सीमा",
    "chooseCenterWithLevel": "ज़ूम स्तर के साथ मानचित्र केंद्र निर्धारित करने के लिए मानचित्र पर क्लिक करें",
    "chooseCenterWithScale": "मानचित्र स्केल के साथ मानचित्र केंद्र निर्धारित करने के लिए मानचित्र पर क्लिक करें",
    "findLocation": "स्थान या फीचर खोजें और इस तक ज़ूम करें",
    "findLocation_inputPlaceholder": "आपकी जगह या फीचर",
    "queryFeature": "एक फीचर को क्वेरी करें और इस तक ज़ूम करें",
    "addMarker": "मानचित्र पर एक मार्कर जोड़ें",
    "addMarker_titlePlaceholder": "मार्कर पॉप-अप का शीर्षक",
    "addMarker_symbolURL": "मार्कर प्रतीक का URL",
    "addMarker_label": "मार्कर लेबल",
    "popupTitle": "पॉप-अप का शीर्षक",
    "zoomLevel": "ज़ूम स्तर",
    "overwirteMobileLayout": "मोबाइल लेआउट का अधिलेखित डिफ़ॉल्ट स्क्रीन आकार",
    "language": "ऐप्लीकेशन की डिस्प्ले भाषा सेट करें",
    "auth": "एक उपयोगकर्ता को स्वचालित रूप से प्रमाणित करता है",
    "linkPreview": "लिंक का पूर्वावलोकन",
    "useShortenLink": "छोटा लिंक",
    "shareMapUrlExtent": "मानचित्र की वर्तमान सीमा साझा करें",
    "shareToWebTips": "यह ऐप्लीकेशन जनता के साथ साझा नहीं है। शायद लोग यह देखने में सक्षम नहीं होंगे।"
  },
  "webSceneLoader": {
    "webglSupportTip": "3D वेब ऐप्लीकेशन आपके ब्राउज़र पर समर्थित नहीं हैं।"
  },
  "map": {
    "basemapNotAvailable": "बेसमैप उपलब्ध नहीं है।",
    "displayDefaultBasemap": "इसके बजाय डिफ़ॉल्ट बेसमैप प्रदर्शित किया जा रहा है।",
    "layerLoadedError": "लेयर, ${लेयरों} को मानचित्र में नहीं जोड़ा जा सकता है।"
  },
  "popup": {
    "relatedTables": "संबंधित तालिका:",
    "relatedRecords": "संबंधित रिकॉर्ड:",
    "noRelatedRecotds": "कोई संबंधित रिकॉर्ड नहीं मिला।",
    "chooseFieldTip": "सूची दिखाने के लिए कोई विशेषता चुनें",
    "saveAsPopupTitle": "पॉप-अप शीर्षक के समान"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "आपके चयन में कई विशेषताएं हैं। उन्हें मानचित्र पर प्रदर्शित करने और पुनर्प्राप्त करने के लिए लंबा समय लग सकता है।",
    "askForContinue": "क्या आप जारी रखना चाहते हैं?"
  },
  "colorPalette": {
    "transparent": "पारदर्शी",
    "custom": "कस्टम"
  },
  "temperature": {
    "celsius": "सेल्सियस",
    "fahrenheit": "फारेनहाइट"
  },
  "report": {
    "printButtonLabel": "प्रिंट करें",
    "reportDimensionsMsg": "यह रिपोर्ट पर ${paperSize} कागज पर मुद्रित करने के लिए बनायी गई है",
    "unableToPrintMapMsg": "मानचित्र(त्रों) को मुद्रित करते समय कोई त्रुटि हुई।",
    "notesHint": "टिप्पणियाँ यहाँ पर दर्ज करें",
    "landscape": "लैंडस्केप",
    "portrait": "पोर्ट्रेट",
    "mapOnly": "केवल_मानचित्र",
    "a0": "A0",
    "a1": "A1",
    "a2": "A2",
    "a3": "A3",
    "a4": "A4",
    "a5": "A5",
    "letterANSIA": "पत्र ANSI ए",
    "tabloidANSIB": "छोटे आकार का समाचार पत्र ANSI बी",
    "letter": "पत्र",
    "legal": "कानूनी",
    "tabloid": "छोटे आकार का समाचार पत्र",
    "ansi_a": "ANSI A",
    "ansi_b": "ANSI B",
    "ansi_c": "ANSI C",
    "ansi_d": "ANSI D",
    "ansi_e": "ANSI E"
  },
  "snapshot": {
    "snapshot_complete": "स्नैपशॉट बनाना विफल रहा।",
    "snapshot_failed": "स्नैपशॉट को बनाने में विफल रहा है।",
    "snapshot_append": "लेयर",
    "utc": "UTC"
  },
  "statisticsChart": {
    "enlarge": "बड़ा करें",
    "setting": "सेटिंग",
    "count": "गणना करें",
    "horizontalAxis": "क्षैतिज अक्ष",
    "verticalAxis": "ऊर्ध्वाधर अक्ष",
    "dataLabels": "डेटा लेबल",
    "color": "रंग"
  },
  "frameworkDatasource": {
    "setDataSource": "डेटा स्रोत सेट करें",
    "customDataSource": "अतिरिक्त डेटा स्रोत",
    "selectCustomDataTip": "इस एप्लिकेशन से किसी डेटा स्रोत का चयन करें।",
    "widgetOutputs": "विजेट आउटपुट",
    "noExtraDsAvailable": "कोई अतिरिक्त डेटा स्रोत उपलब्ध नहीं है।",
    "addExtraDsTip": "बिल्डर के विशेषता टैब पर जाएँ और डेटा जोड़ने हेतु अतिरिक्त डेटा स्रोत क्लिक करें।",
    "widgetOutpusListTip": "विजेट आउटपुट (यदि कोई है) यहाँ सूचीबद्ध हैं।"
  },
  "gridLayout": {
    "addWidgetTip": "विजेट टैब के माध्यम से यहाँ पर विजेट जोड़ें",
    "modifyLayout": "लेआउट संशोधित करें",
    "dragToAdd": "जोड़ने के लिए खींचें",
    "mapArea": "मैप क्षेत्र"
  },
  "noEditPrivileges": "आपके खाते को बनाने या डेटा संशोधित करने की अनुमति नहीं है।",
  "invalidConfiguration": "विजेट या तो कॉन्फ़िगर नहीं है या कॉन्फ़िगर में लेयर अब मानचित्र में नहीं हैं। कृपया ऐप को बिल्डर मोड में खोलें और विजेट को फिर से कॉन्फ़िगर करें।"
});