define({
  "id": "ID",
  "state": "Koordinātas pēc noklusējuma tiks rādītas pašreizējās kartes koordinātu sistēmā. Lai koordinātes iegūtu citās koordinātu sistēmās, tās ir jāpievieno un jānorāda attiecīgās transformācijas.",
  "outputUnit": "Izvades mērvienība",
  "wkid": "Izvades WKID",
  "label": "Izvades koordinātu sistēmas nosaukums",
  "transformationWkid": "Transformācijas WKID",
  "transformationLabel": "Transformācijas nosaukums",
  "transformForward": "Transformēt uz priekšu",
  "actions": "Darbības",
  "warning": "Lūdzu, ievadiet derīgu telpiskās atskaites WKID!",
  "tfWarning": "Lūdzu, ievadiet derīgu dotā lieluma transformācijas WKID!",
  "spinnerLabel": "Noapaļot koordinātas līdz: ",
  "decimalPlace": "decimālvietai (ām)",
  "separator": "Rādīt tūkstošdaļu atdalītājus",
  "getVersionError": "Nevar iegūt ģeometrijas servisa versiju",
  "add": "Pievienot izvades koordinātu sistēmu",
  "edit": "Rediģēt koordinātu sistēmu",
  "output": "Izvades koordinātu sistēma",
  "cName": "Koordināšu sistēmas nosaukums",
  "units": "Rādāmās vienības: ",
  "datum": "Dotā lieluma transformācija",
  "tName": "Transformācijas nosaukums",
  "tWKIDPlaceHolder": "Transformācijas WKID",
  "forward": "Izmantot transformāciju uz priekšu",
  "ok": "Labi",
  "cancel": "Atcelt",
  "olderVersion": "Ģeometrijas pakalpojums neatbalsta transformācijas darbību",
  "REPEATING_ERROR": " Koordinātu sistēma pastāv izvades sarakstā.",
  "Default": "Noklusējums",
  "Inches": "Collas",
  "Foot": "Pēdas",
  "Yards": "Jardi",
  "Miles": "Jūdzes",
  "Nautical_Miles": "Jūras jūdzes",
  "Millimeters": "Milimetri",
  "Centimeters": "Centimetri",
  "Meter": "Metri",
  "Kilometers": "Kilometri",
  "Decimeters": "Decimetri",
  "Decimal_Degrees": "Decimālie grādi",
  "Degrees_Decimal_Minutes": "Grādi decimālminūtes",
  "Degree_Minutes_Seconds": "Grādi minūtes sekundes",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Koordinātu parādīšanas secība:",
  "lonLatTips": "Garums/platums (X, Y)",
  "latLonTips": "Platums/garums (Y, X)"
});