define({
  "instruction": "Selecione e configure camadas que serão mostradas na Tabela de Atributos inicialmente.",
  "label": "Camada",
  "show": "Mostrar",
  "actions": "Configurar campos de camada",
  "field": "Campo",
  "alias": "Nome Alternativo",
  "visible": "Visível",
  "linkField": "Campo de vínculo",
  "noLayers": "Nenhuma camada de feição está disponível",
  "back": "Voltar",
  "exportCSV": "Permitir exportação para CSV",
  "expand": "Expandir inicialmente o widget",
  "filterByExtent": "Habilitar Filtrar por Extensão de Mapa por padrão",
  "restore": "Restaurar para valor padrão",
  "ok": "OK",
  "cancel": "Cancelar",
  "includePoint": "Inlcuir coordenadas de ponto no arquivo exportado",
  "configureLayerFields": "Configurar Campos da Camada",
  "result": "Salvo com sucesso",
  "warning": "Selecione a primeira opção de Mostrar.",
  "fieldCheckWarning": "Pelo menos um campo deve ser selecionado.",
  "unsupportQueryWarning": "A camada precisa suportar a operação de consulta para aparecer no widget da Tabela de Atributo. Certifique-se que o recurso de consulta no serviço está ativado.",
  "unsupportQueryLayers": "A seguinte camada precisa suportar a operação de consulta para aparecer no widget da Tabela de Atributo. Certifique-se que o recurso de consulta no serviço está ativado.",
  "fieldName": "Nome",
  "fieldAlias": "Nome Alternativo",
  "fieldVisibility": "Visibilidade",
  "fieldActions": "Ações",
  "showAttachments": "Mostrar anexos"
});