define({
  "instruction": "Het opstartscherm verschijnt vóór de applicatie toegankelijk is.",
  "defaultContent": "Voeg hier tekst, koppelingen en kleine afbeeldingen toe.",
  "requireConfirm": "Bevestiging vereisen om door te gaan",
  "noRequireConfirm": "Geen bevestiging vereist om door te gaan",
  "optionText": "Optie voor gebruiker om het welkomstscherm uit te schakelen bij openen van de app.",
  "confirmLabel": "Bevestigingsteksten: ",
  "confirmLabelColor": "Bevestiging tekstkleur",
  "defaultConfirmText": "Ik ga akkoord met de bovenstaande gebruiksvoorwaarden en bepalingen",
  "confirmOption": "Dit splash-scherm altijd weergeven wanneer de app gestart wordt",
  "backgroundColor": "Achtergrondkleur",
  "content": "Content",
  "contentDescription": "Bepaal de content die wordt weergegeven op het opstartscherm.",
  "appearance": "Weergave",
  "appearanceDescription": "De opmaak van het opstartscherm instellen.",
  "size": "Grootte",
  "width": "Breedte",
  "height": "Hoogte",
  "custom": "Aangepast",
  "background": "Achtergrond",
  "colorFill": "Kleurvulling",
  "imageFill": "Beeldvulling",
  "chooseFile": "Bestand kiezen",
  "noFileChosen": "Geen bestand gekozen",
  "transparency": "Transparant",
  "sizeFill": "Vulling",
  "sizeFit": "Passend maken",
  "sizeStretch": "Uitrekken om te vullen",
  "sizeCenter": "Centreren",
  "sizeTile": "Tile",
  "buttonColor": "Knopkleur",
  "buttonText": "Knoptekst",
  "buttonTextColor": "Knoptekstkleur",
  "contentAlign": "Contentuitlijning",
  "alignTop": "Boven",
  "alignMiddle": "Midden",
  "maskColor": "Maskerkleur",
  "options": "Opties",
  "optionsDescription": "Het gedrag van het opstartscherm instellen."
});