define({
  "instruction": "Válassza ki és konfigurálja az Attribútum táblában kezdetben megjelenő rétegeket.",
  "label": "Réteg",
  "show": "Mutassa",
  "actions": "Rétegmezők konfigurálása",
  "field": "Mező",
  "alias": "Aliasnév",
  "url": "URL",
  "sortField": "Rendezés mező",
  "sortOrderTooltips": {
    "toDescending": "Váltás csökkenő sorrendre",
    "toAscending": "Váltás növekvő sorrendre"
  },
  "visible": "Látható",
  "linkField": "Hivatkozásmező",
  "noLayers": "Nem érhetők el vektoros rétegek",
  "back": "Vissza",
  "exportCSV": "CSV export engedélyezése",
  "expand": "A widget kezdeti kibontása",
  "filterByExtent": "A „Szűrés térképkiterjedés szerint” beállítás alapértelmezett engedélyezése",
  "allowTextSelection": "Szöveg kijelölésének engedélyezése",
  "highlightColor": "Kiemelés színe",
  "restore": "Visszaállítás az alapértelmezett értékre",
  "ok": "OK",
  "cancel": "Mégse",
  "includePoint": "Az exportált fájl tartalmazza a pontok koordinátáit is",
  "configureLayerFields": "Rétegmezők konfigurálása",
  "result": "Sikeresen mentve",
  "warning": "Először válassza ki a Megjelenítés beállítást.",
  "fieldCheckWarning": "Legalább egy mezőt ki kell választani.",
  "unsupportQueryWarning": "A rétegnek támogatnia kell a lekérdezési műveletet, hogy megjelenhessen az Attribute Table widgetben. Győződjön meg arról, hogy a szolgáltatás lekérdezési funkciója be van kapcsolva.",
  "unsupportQueryLayers": "A következő rétegnek támogatnia kell a lekérdezési műveletet, hogy megjelenhessen az Attribute Table widgetben. Győződjön meg arról, hogy a szolgáltatás lekérdezési funkciója be van kapcsolva.",
  "fieldName": "Név",
  "fieldAlias": "Aliasnév",
  "fieldVisibility": "Láthatóság",
  "fieldActions": "Műveletek",
  "showAttachments": "Csatolmányok megjelenítése"
});