define(
   ({
    "sourceSetting": "Setări sursă căutare",
    "instruction": "Adăugaţi şi configuraţi straturi tematice de servicii sau obiecte spaţiale de geocodificare ca surse de căutare. Aceste surse specificate determină ceea ce poate fi căutat în caseta de căutare.",
    "add": "Adăugare sursă căutare",
    "addGeocoder": "Adăugare geocodificator",
    "geocoder": "Geocodificator",
    "setLayerSource": "Setare sursă straturi tematice",
    "setGeocoderURL": "Setare URL geocodificator",
    "searchableLayer": "Strat tematic de obiecte spațiale",
    "name": "Nume",
    "countryCode": "Cod(uri) ţară sau regiune",
    "countryCodeEg": "de ex. ",
    "countryCodeHint": "Dacă lăsaţi această valoare necompletată, vor fi căutate toate ţările şi regiunile",
    "generalSetting": "Setări generale",
    "allPlaceholder": "Text substituent pentru căutarea tuturor: ",
    "showInfoWindowOnSelect": "Afişaţi fereastra pop-up pentru obiectul spaţial sau locul găsit",
    "searchInCurrentMapExtent": "Căutaţi doar în extinderea de hartă curentă",
    "locatorUrl": "URL geocodificator",
    "locatorName": "Nume geocodificator",
    "locatorExample": "Exemplu",
    "locatorWarning": "Această versiune de serviciu de geocodificare nu este acceptată. Widgetul acceptă serviciul de geocodificare 00.0 şi versiunile ulterioare.",
    "locatorTips": "Sugestiile nu sunt disponibile, deoarece serviciul de geocodificare nu acceptă capacitatea de sugestie.",
    "layerSource": "Sursă straturi tematice",
    "searchLayerTips": "Sugestiile nu sunt disponibile, deoarece serviciul de obiecte spaţiale nu acceptă capacitatea de paginare.",
    "placeholder": "Text substituent",
    "searchFields": "Câmpuri de căutare",
    "displayField": "Câmp de afişare",
    "exactMatch": "Potrivire exactă",
    "maxResults": "Număr maxim de rezultate",
    "setSearchFields": "Setare câmpuri de căutare",
    "set": "Setare",
    "fieldSearchable": "poate fi căutat",
    "fieldName": "Nume",
    "fieldAlias": "Pseudonim",
    "ok": "OK",
    "cancel": "Anulare",
    "invalidUrlTip": "Adresa URL pe care aţi introdus-o este nevalidă sau inaccesibilă."
  })
);