define({
  "sourceSetting": "Setări sursă căutare",
  "instruction": "Adăugaţi şi configuraţi servicii de geocodificare sau straturi tematice de obiecte spaţiale ca surse de căutare. Aceste surse specificate stabilesc ce este căutabil în cadrul casetei de căutare.",
  "add": "Adăugare sursă căutare",
  "addGeocoder": "Adăugare geocodificator",
  "geocoder": "Geocodificator",
  "setLayerSource": "Setare sursă straturi tematice",
  "setGeocoderURL": "Setare URL geocodificator",
  "searchableLayer": "Strat tematic de obiecte spaţiale",
  "name": "Nume",
  "countryCode": "Cod(uri) ţară sau regiune",
  "countryCodeEg": "de ex. ",
  "countryCodeHint": "Dacă lăsaţi această valoare necompletată, vor fi căutate toate ţările şi regiunile",
  "generalSetting": "Setări generale",
  "allPlaceholder": "Text substituent pentru căutarea tuturor: ",
  "showInfoWindowOnSelect": "Afişaţi fereastra pop-up pentru obiectul spaţial sau locul găsit",
  "searchInCurrentMapExtent": "Căutaţi doar în extinderea de hartă curentă",
  "zoomScale": "Scară de transfocare",
  "locatorUrl": "URL geocodificator",
  "locatorName": "Nume geocodificator",
  "locatorExample": "Exemplu",
  "locatorWarning": "Această versiune de serviciu de geocodificare nu este acceptată. Widgetul acceptă serviciul de geocodificare versiunea 10.1 sau ulterioară.",
  "locatorTips": "Sugestiile nu sunt disponibile, deoarece serviciul de geocodificare nu acceptă capacitatea de sugestie.",
  "layerSource": "Sursă straturi tematice",
  "searchLayerTips": "Sugestiile nu sunt disponibile, deoarece serviciul de obiecte spaţiale nu acceptă capacitatea de paginare.",
  "placeholder": "Text substituent",
  "searchFields": "Câmpuri de căutare",
  "displayField": "Câmp de afişare",
  "exactMatch": "Potrivire exactă",
  "maxSuggestions": "Sugestii de valori maxime",
  "maxResults": "Număr maxim de rezultate",
  "enableLocalSearch": "Activare căutare locală",
  "minScale": "Scară minimă",
  "minScaleHint": "Dacă scara hărţii este mai mare decât această scară, va fi aplicată căutarea locală",
  "radius": "Rază",
  "radiusHint": "Specifică raza unei suprafeţe din jurul centrului actual al hărţii, utilizată pentru a creşte clasificarea candidaţilor de geocodificare, astfel încât candidaţii cei mai apropiaţi de locaţie să fie returnaţi primii",
  "meters": "Metri",
  "setSearchFields": "Setare câmpuri de căutare",
  "set": "Setare",
  "fieldSearchable": "poate fi căutat",
  "fieldName": "Nume",
  "fieldAlias": "Pseudonim",
  "ok": "OK",
  "cancel": "Anulare",
  "invalidUrlTip": "Adresa URL ${URL} este nevalidă sau inaccesibilă."
});