define({
  "_widgetLabel": "좌표",
  "hintMessage": "좌표를 가져오려면 맵 클릭",
  "defaultLabel": "기본값",
  "realtimeLabel": "좌표를 가져오려면 마우스를 이동하세요.",
  "computing": "계산 중...",
  "latitudeLabel": "위도",
  "longitudeLabel": "경도",
  "loading": "불러오는 중...",
  "enableClick": "맵을 클릭하여 좌표 가져오기를 활성화하려면 클릭",
  "disableClick": "맵을 클릭하여 좌표 가져오기를 비활성화하려면 클릭",
  "Default": "기본값",
  "Inches": "인치",
  "Foot": "피트",
  "Yards": "야드",
  "Miles": "마일",
  "Nautical_Miles": "해리",
  "Millimeters": "밀리미터",
  "Centimeters": "센티미터",
  "Meter": "미터",
  "Kilometers": "킬로미터",
  "Decimeters": "데시미터",
  "Decimal_Degrees": "도",
  "Degree_Minutes_Seconds": "도-분-초",
  "MGRS": "MGRS",
  "USNG": "USNG"
});