define({
  "_widgetLabel": "Tọa độ",
  "hintMessage": "Bấm vào bản đồ để lấy tọa độ",
  "defaultLabel": "Mặc định",
  "realtimeLabel": "Di chuyển chuột để lấy tọa độ",
  "computing": "Đang tính toán...",
  "latitudeLabel": "Vĩ độ",
  "longitudeLabel": "Kinh độ",
  "loading": "đang tải...",
  "enableClick": "Bấm để bật tùy chọn bấm vào bản đồ để nhận tọa độ",
  "disableClick": "Bấm để tắt tùy chọn bấm vào bản đồ để nhận tọa độ",
  "Default": "Mặc định",
  "Inches": "Inch",
  "Foot": "Feet",
  "Yards": "Thước",
  "Miles": "Dặm",
  "Nautical_Miles": "Hải lý",
  "Millimeters": "Milimét",
  "Centimeters": "Xentimét",
  "Meter": "Mét",
  "Kilometers": "Kilômét",
  "Decimeters": "Đềximét",
  "Decimal_Degrees": "Độ",
  "Degree_Minutes_Seconds": "Độ phút giây",
  "MGRS": "MGRS",
  "USNG": "USNG"
});