define({
  "_widgetLabel": "Listă de straturi tematice",
  "titleBasemap": "Hărţi fundal",
  "titleLayers": "Straturi tematice operaţionale",
  "labelLayer": "Nume strat tematic",
  "itemZoomTo": "Transfocare la",
  "itemTransparency": "Transparenţă",
  "itemTransparent": "Transparent",
  "itemOpaque": "Opac",
  "itemMoveUp": "Deplasare în sus",
  "itemMoveDown": "Deplasare în jos",
  "itemDesc": "Descriere",
  "itemDownload": "Descărcare",
  "itemToAttributeTable": "Vizualizare în tabelul de atribute",
  "itemShowItemDetails": "Afişare detalii element",
  "empty": "gol",
  "removePopup": "Dezactivare pop-up",
  "enablePopup": "Activare pop-up",
  "turnAllLayersOff": "Dezactivaţi toate straturile tematice",
  "turnAllLayersOn": "Activaţi toate straturile tematice",
  "expandAllLayers": "Extindeţi toate straturile tematice",
  "collapseAlllayers": "Restrângeţi toate straturile tematice",
  "turnAllLabelsOff": "Dezactivaţi toate etichetele",
  "turnAllLabelsOn": "Activaţi toate etichetele",
  "showLabels": "Afişaţi etichetele",
  "hideLables": "Ascundeţi etichetele"
});