define({
  "instruction": "Vælg og konfigurér lag, der først skal vises i attributtabellen.",
  "label": "Lag",
  "show": "Vis",
  "actions": "Konfigurér lagfelter",
  "field": "Felt",
  "alias": "Alias",
  "url": "URL",
  "sortField": "Sortér felt",
  "sortOrderTooltips": {
    "toDescending": "Skift til faldende rækkefølge",
    "toAscending": "Skift til stigende rækkefølge"
  },
  "visible": "Synlig",
  "linkField": "Link-felt",
  "noLayers": "Der er ingen tilgængelige vektorlag",
  "back": "Tilbage",
  "exportCSV": "Tillad eksport til CSV",
  "expand": "Udvid først widget'en",
  "filterByExtent": "Aktivér filter efter kortudstrækning som standard",
  "allowTextSelection": "Tillad markering af tekst",
  "highlightColor": "Fremhævningsfarve",
  "restore": "Gendan standardværdien",
  "ok": "OK",
  "cancel": "Annuller",
  "includePoint": "Medtag punktkoordinater i den eksporterede fil",
  "configureLayerFields": "Konfigurér lagfelter",
  "result": "Gemt",
  "warning": "Vælg Vis-indstillingen først.",
  "fieldCheckWarning": "Mindst ét felt skal være valgt.",
  "unsupportQueryWarning": "Laget skal understøtte, at forespørgsler bliver vist i attributtabel-widget. Kontrollér, at forespørgselsfunktionen er aktiveret i tjenesten.",
  "unsupportQueryLayers": "Følgende lag skal understøtte, at forespørgsler bliver vist i attributtabel-widget. Kontrollér, at forespørgselsfunktionen er aktiveret i tjenesten.",
  "fieldName": "Navn",
  "fieldAlias": "Alias",
  "fieldVisibility": "Synlighed",
  "fieldActions": "Handlinger",
  "showAttachments": "Vis vedhæftninger"
});