define({
  "instruction": "La pantalla de presentació apareix abans que es pugui accedir a l'aplicació.",
  "defaultContent": "Afegiu text, enllaços i gràfics petits aquí.",
  "requireConfirm": "Demana confirmació per continuar",
  "noRequireConfirm": "No demanis confirmació per continuar",
  "optionText": "Opció que permet que l'usuari deshabiliti la pantalla de presentació en iniciar l'aplicació.",
  "confirmLabel": "Textos de confirmació: ",
  "confirmLabelColor": "Color dels textos de confirmació",
  "defaultConfirmText": "Accepto els termes i condicions anteriors",
  "confirmOption": "Mostra aquesta pantalla de presentació cada vegada que s'iniciï l'aplicació",
  "backgroundColor": "Color de fons",
  "content": "Contingut",
  "contentDescription": "Definiu el contingut que es mostra a la pantalla de presentació.",
  "appearance": "Aparença",
  "appearanceDescription": "Definiu l'aparença de la pantalla de presentació.",
  "size": "Mida",
  "width": "Amplada",
  "height": "Altura",
  "custom": "Personalitzat",
  "background": "Fons",
  "colorFill": "Emplenament de color",
  "imageFill": "Emplenament d'imatge",
  "chooseFile": "Trieu un fitxer",
  "noFileChosen": "No s'ha seleccionat cap fitxer",
  "transparency": "Transparència",
  "sizeFill": "Emplenament",
  "sizeFit": "Ajust",
  "sizeStretch": "Estira fins emplenar",
  "sizeCenter": "Centre",
  "sizeTile": "Tessel·la",
  "buttonColor": "Color del botó",
  "buttonText": "Text del botó",
  "buttonTextColor": "Color del text del botó",
  "contentAlign": "Alineació del contingut",
  "alignTop": "Superior",
  "alignMiddle": "Al mig",
  "maskColor": "Color de màscara",
  "options": "Opcions",
  "optionsDescription": "Definiu el comportament de la pantalla de presentació."
});