define({
  "common": {
    "apply": "בצע",
    "ok": "אישור",
    "cancel": "ביטול",
    "yes": "כן",
    "no": "לא",
    "next": "הבא",
    "previous": "הקודם",
    "back": "חזור",
    "selected": "נבחר",
    "name": "שם",
    "usage": "שימוש",
    "settings": "הגדרות",
    "home": "דף הבית",
    "link": "קישור",
    "messages": "הודעות",
    "outputs": "פלט",
    "title": "כותרת",
    "thumbnail": "תמונה ממוזערת",
    "url": "URL",
    "actions": "פעולות",
    "layer": "שכבה",
    "action": "פעולה",
    "input": "קלט",
    "output": "פלט",
    "type": "סוג",
    "required": "נדרש",
    "options": "אפשרויות",
    "label": "תווית",
    "tooltip": "בועית מידע",
    "visible": "נראה",
    "symbol": "סמל",
    "popup": "חלון קופץ",
    "upload": "טען",
    "execute": "בצע",
    "help": "עזרה",
    "executing": "מבצע",
    "clear": "נקה",
    "error": "שגיאה",
    "zoomTo": "התמקד אל",
    "attribute": "מאפיין",
    "exports": "ייצא",
    "check": "בדיקה",
    "save": "שמירה",
    "close": "סגור",
    "deleteText": "מחיקה",
    "map": "מפה",
    "scene": "סצנה",
    "reset": "אפס",
    "icon": "סמל",
    "folder": "תיקייה",
    "share": "שתף",
    "view": "מבט",
    "newText": "חדש",
    "edit": "עריכה",
    "wkid": "WKID",
    "table": "טבלה",
    "zoomIn": "התמקד פנימה",
    "zoomOut": "התמקד החוצה",
    "continue1": "המשך",
    "longitude": "קו אורך",
    "latitude": "קו רוחב",
    "custom": "מותאם",
    "image": "תמונה",
    "font": "גופן",
    "text": "טקסט",
    "all": "הכל",
    "number": "מספר",
    "percentage": "אחוז",
    "unit": "יחידה",
    "thousand": "אלף",
    "billion": "מיליארד",
    "million": "מיליון",
    "none": "ללא",
    "field": "שדה",
    "operation": "תפעולי",
    "disableUpdateGeometry": "חסום עדכון גיאומטריה",
    "preview": "תצוגה מקדימה"
  },
  "errorCode": "קוד",
  "errorMessage": "הודעה",
  "errorDetail": "פרט",
  "widgetPlaceholderTooltip": "כדי להגדיר זאת, עבור ללשונית:\"ווידג'ט\" ולחץ על מספר המיקום המתאים",
  "fieldStatistics": {
    "selectField": "בחר שדה",
    "statistics": "סטטיסטיקה",
    "field": "שדה",
    "count": "מספר ערכים",
    "sum": "סיכום ערכים",
    "min": "מינימום",
    "max": "מקסימום",
    "ave": "ממוצע",
    "stddev": "סטיית תקן"
  },
  "symbolChooser": {
    "preview": "תצוגה מקדימה",
    "basic": "בסיסי",
    "arrows": "חיצים",
    "business": "עסקים",
    "cartographic": "קרטוגרפיה",
    "nationalParkService": "שירות הפארקים הלאומי",
    "outdoorRecreation": "נופש בטבע",
    "peoplePlaces": "מקומות ואנשים",
    "safetyHealth": "בטיחות ובריאות",
    "shapes": "צורות",
    "transportation": "תחבורה",
    "symbolSize": "גודל סמל",
    "color": "צבע",
    "alpha": "אלפא",
    "outlineColor": "צבע קו תיחום",
    "outlineWidth": "רוחב קו תוחם",
    "style": "סגנון",
    "width": "רוחב",
    "text": "טקסט",
    "fontColor": "צבע גופן",
    "fontSize": "גודל גופן",
    "transparency": "שקיפות",
    "solid": "מלא",
    "dash": "מקווקו",
    "dot": "נקודה",
    "dashDot": "קו נקודה",
    "dashDotDot": "קו נקודה נקודה",
    "customImage": "תמונה מותאמת אישית",
    "chooseFile": "בחר קובץ",
    "noFileChoosen": "לא נבחר קובץ."
  },
  "transparency": {
    "opaque": "אטום",
    "transparent": "שקוף"
  },
  "rendererChooser": {
    "domain": "דומיין",
    "use": "עם",
    "singleSymbol": "סמל יחיד",
    "uniqueSymbol": "סמלים ייחודיים",
    "color": "צבע",
    "size": "גודל",
    "toShow": "כדי להציג",
    "colors": "צבעים",
    "classes": "קבוצות",
    "symbolSize": "גודל סמל",
    "addValue": "הוסף ערך",
    "setDefaultSymbol": "הגדר סמל ברירת מחדל",
    "defaultSymbol": "סמל ברירת מחדל",
    "selectedSymbol": "סמל נבחר",
    "value": "ערך",
    "label": "תווית",
    "range": "טווח"
  },
  "drawBox": {
    "point": "נקודה",
    "line": "קו",
    "polyline": "קו",
    "freehandPolyline": "קו בשרטוט חופשי",
    "triangle": "משולש",
    "extent": "תיחום",
    "circle": "מעגל",
    "ellipse": "אליפסה",
    "polygon": "פוליגון",
    "freehandPolygon": "פוליגון בשרטוט חופשי",
    "text": "טקסט",
    "clear": "נקה"
  },
  "popupConfig": {
    "title": "כותרת",
    "add": "הוסף",
    "fields": "שדות",
    "noField": "אין שדה",
    "visibility": "ניראה",
    "name": "שם",
    "alias": "כינוי",
    "actions": "פעולות"
  },
  "includeButton": {
    "include": "כלול"
  },
  "loadingShelter": {
    "loading": "טוען"
  },
  "basicServiceBrowser": {
    "noServicesFound": "לא נמצא שירות.",
    "unableConnectTo": "לא יכול להתחבר",
    "invalidUrlTip": "ה-URL שהזנת לא חוקי או שלא ניתן לגשת אליו."
  },
  "serviceBrowser": {
    "noGpFound": "לא נמצא שירות geoprocessing.",
    "unableConnectTo": "לא יכול להתחבר"
  },
  "layerServiceBrowser": {
    "noServicesFound": "לא נמצאו שירותי מפה או שירותי ישויות.",
    "unableConnectTo": "לא יכול להתחבר"
  },
  "basicServiceChooser": {
    "validate": "אימות",
    "example": "דוגמא",
    "set": "הגדר"
  },
  "urlInput": {
    "invalidUrl": "URL לא חוקי."
  },
  "urlComboBox": {
    "invalidUrl": "URL לא חוקי."
  },
  "filterBuilder": {
    "addAnotherExpression": "הוסף ביטוי",
    "addSet": "הוסף סידרה",
    "matchMsg": "קבל ישויות בשכבה שתואמת ${any_or_all} מהביטויים הבאים",
    "matchMsgSet": "${any_or_all} מהביטויים הבאים בסט זה הם נכונים",
    "all": "הכל",
    "any": "כלשהו",
    "value": "ערך",
    "field": "שדה",
    "unique": "ייחודי",
    "none": "ללא",
    "and": "וגם",
    "valueTooltip": "הכנס ערך",
    "fieldTooltip": "בחר מתוך שדה קיים",
    "uniqueValueTooltip": "בחר מתוך ערכים ייחודיים בשדה הנבחר",
    "stringOperatorIs": "הוא",
    "stringOperatorIsNot": "אינו",
    "stringOperatorStartsWith": "מתחיל עם",
    "stringOperatorEndsWith": "מסתיים ב",
    "stringOperatorContains": "מכיל",
    "stringOperatorDoesNotContain": "לא מכיל",
    "stringOperatorIsBlank": "ריק",
    "stringOperatorIsNotBlank": "אינו ריק",
    "dateOperatorIsOn": "הוא ב-",
    "dateOperatorIsNotOn": "אינו ב-",
    "dateOperatorIsBefore": "הוא לפני",
    "dateOperatorIsAfter": "הוא אחרי",
    "dateOperatorIsOnOrBefore": "חל בתאריך או לפני",
    "dateOperatorIsOnOrAfter": "חל בתאריך או אחרי",
    "dateOperatorMinutes": "דקות",
    "dateOperatorHours": "שעות",
    "dateOperatorDays": "ימים",
    "dateOperatorWeeks": "שבועות",
    "dateOperatorMonths": "חודשים",
    "dateOperatorYears": "שנים",
    "dateOperatorInTheLast": "בסוף",
    "dateOperatorNotInTheLast": "לא בסוף",
    "dateOperatorIsBetween": "בין",
    "dateOperatorIsNotBetween": "לא נמצא בין",
    "dateOperatorIsBlank": "ריק",
    "dateOperatorIsNotBlank": "אינו ריק",
    "numberOperatorIs": "הוא",
    "numberOperatorIsNot": "אינו",
    "numberOperatorIsAtLeast": "הוא לפחות",
    "numberOperatorIsLessThan": "הוא פחות מ-",
    "numberOperatorIsAtMost": "הוא לכל היותר",
    "numberOperatorIsGreaterThan": "הוא גדול מ-",
    "numberOperatorIsBetween": "בין",
    "numberOperatorIsNotBetween": "לא נמצא בין",
    "numberOperatorIsBlank": "ריק",
    "numberOperatorIsNotBlank": "אינו ריק",
    "string": "מחרוזת",
    "number": "מספר",
    "date": "תאריך",
    "askForValues": "בקש ערכים",
    "prompt": "בקשה להזנה",
    "hint": "רמז",
    "error": {
      "invalidParams": "פרמטרים לא חוקיים.",
      "invalidUrl": "URL לא חוקי.",
      "noFilterFields": "לשכבה אין שדות בהם ניתן להשתמש ליצירת מסננים.",
      "invalidSQL": "ביטוי SQL לא חוקי.",
      "cantParseSQL": "לא ניתן לפענח את ביטוי ה-SQL."
    },
    "caseSensitive": "משתנה ממקרה למקרה",
    "notSupportCaseSensitiveTip": "השירותים המתארחים אינם תומכים בשאילתא תלויית רישיות.",
    "setFilterTip": "הגדר בבקשה מסננים תקינים.",
    "listValues": "רשום ערכים",
    "cascadeFilterTip": "הצג רק ערכים שסוננו לפי ביטויים קודמים.",
    "noneCascadeFilterTip": "כל הערכים היחודיים של שדה זה",
    "previousCascadeFilterTip": "ערכים שסוננו לפי ביטויים קודמים",
    "allCascadeFilterTip": "ערכים שסוננו לפי כל הביטויים האחרים"
  },
  "featureLayerSource": {
    "layer": "שכבה",
    "browse": "דפדף",
    "selectFromMap": "מפה",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL של השירות",
    "inputLayerUrl": "URL של שכבת הקלט",
    "selectLayer": "בחר שכבת ישויות מהמפה הנוכחית.",
    "chooseItem": "בחר פריט שכבת ישויות.",
    "setServiceUrl": "הכנס URL של שירות ישויות או שירות מפה.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "בחר שכבת ישויות."
  },
  "queryableLayerSource": {
    "layer": "שכבה",
    "browse": "נתב",
    "selectFromMap": "מפה",
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL של השירות",
    "inputLayerUrl": "URL של שכבת הקלט",
    "selectLayer": "בחר שכבה מהמפה הנוכחית.",
    "chooseItem": "בחר פריט.",
    "setServiceUrl": "הזן את כתובת ה-URL של השירות.",
    "selectFromOnline": "ArcGIS Online",
    "chooseLayer": "בחר שכבה."
  },
  "gpSource": {
    "selectFromPortal": "Portal for ArcGIS",
    "addServiceUrl": "URL של השירות",
    "selectFromOnline": "ArcGIS Online",
    "setServiceUrl": "הזן את כתובת ה- URL של שירות Geoprocessing.",
    "chooseItem": "בחר פריט שירות של עיבוד גיאוגרפי.",
    "chooseTask": "בחר משימת עיבוד גיאוגרפי."
  },
  "itemSelector": {
    "map": "מפה",
    "selectWebMap": "בחר Web Map",
    "addMapFromOnlineOrPortal": "מצא והוסף Web Map מתוך המקורות הציבוריים של ArcGIS Online, התוכן הפרטי שלך בתוך ArcGIS Online או הפורטל.",
    "searchMapName": "חפש לפי שם מפה...",
    "searchNone": "לא מצאנו את מה שחיפשת. נסה בבקשה שנית.",
    "groups": "קבוצות",
    "noneGroups": "אין קבוצות",
    "signInTip": "פג תוקף משך זמן ההתחברות. רענן בבקשה את הדפדפן שלך בשביל להתחבר לפורטל שלך שוב.",
    "signIn": "התחבר",
    "publicMap": "כללי",
    "myOrganization": "הארגון שלי",
    "myGroup": "הקבוצות שלי",
    "myContent": "התוכן שלי",
    "count": "מונה",
    "fromPortal": "מהפורטל",
    "fromOnline": "מתוך ArcGIS.com",
    "noneThumbnail": "תמונה ממוזערת אינה זמינה",
    "owner": "יוצר",
    "signInTo": "התחבר אל",
    "lastModified": "שונה לאחרונה",
    "moreDetails": "פרטים נוספים",
    "mostRecent": "העדכני ביותר",
    "mostViewed": "הנצפה ביותר",
    "highestRated": "בעל הדירוג הגבוה ביותר",
    "viewItemDetails": "הצג תיאור פריט"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "השירות אינו תומך בשאילתה."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "אין שכבה מתאימה זמינה במפה."
  },
  "layerInfosMenu": {
    "titleBasemap": "מפות בסיס",
    "titleLayers": "שכבות תפעוליות",
    "labelLayer": "שם שכבה",
    "itemZoomTo": "התמקד אל",
    "itemTransparency": "שקיפות",
    "itemTransparent": "שקוף",
    "itemOpaque": "אטום",
    "itemMoveUp": "הזז למעלה",
    "itemMoveDown": "הזז למטה",
    "itemDesc": "תיאור",
    "itemDownload": "הורד",
    "itemToAttributeTable": "הצג בטבלת מאפיינים"
  },
  "imageChooser": {
    "unsupportReaderAPI": "לביצוע: הדפדפן לא תומך ב-API של קריאת קבצים",
    "readError": "קריאת הקובץ נכשלה.",
    "unknowError": "לא ניתן להשלים את ביצוע הפעולות.",
    "invalidType": "סוג קובץ לא חוקי.",
    "cropImage": "חתוך תמונה",
    "exceed": "גודל הקובץ אינו יכול להיות יותר מ-‎1024 KB",
    "enableFlash": "הפעל את Adobe Flash לפני דפדוף לתמונה.",
    "cropWaining": "בחר תמונה שגודלה לפחות ${width}‏ x‏ ${height} פיקסלים.",
    "toolTip": "לקבלת תוצאות מיטביות, הקובץ צריך להיות ברוחב של ${width} פיקסלים ובגובה של ${height} פיקסלים. גדלים אחרים יותאמו. פורמטים של תמונות שיתקבלו הם: PNG,‏ GIF ו-JPEG."
  },
  "simpleTable": {
    "moveUp": "הזז למעלה",
    "moveDown": "הזז למטה",
    "deleteRow": "מחק",
    "edit": "עריכה"
  },
  "urlParams": {
    "invalidToken": "קוד גישה לא חוקי",
    "validateTokenError": "קוד גישה לא חוקי או שגיאה ברשת"
  },
  "exportTo": {
    "exportTo": "יצוא",
    "toCSV": "ייצא לקובץ CSV",
    "toFeatureCollection": "ייצא לאוסף ישויות",
    "toGeoJSON": "ייצא אל GeoJSON"
  },
  "appState": {
    "title": "מצב האפליקציה",
    "restoreMap": "לחץ כדי לשחזר את תיחום המפה וניראות השכבות היכן שהפסקת."
  },
  "featureActions": {
    "featureActions": "פעולות על ישות",
    "ZoomTo": "התמקד אל",
    "PanTo": "עבור אל",
    "Flash": "הבהוב",
    "ShowPopup": "הצג חלונית קופצת",
    "CreateLayer": "צור שכבה",
    "ShowStatistics": "סטטיסטיקה...",
    "ClearSelection": "נקה בחירה",
    "ExportToCSV": "ייצא לקובץ CSV",
    "ShowSelectedFeature": "הצג ישויות נבחרות",
    "ExportToFeatureCollection": "ייצא לאוסף ישויות",
    "ExportToGeoJSON": "ייצא אל GeoJSON",
    "EditAttributes": "ערוך מאפיינים",
    "AddMarker": "הוסף סמן",
    "RemoveMarker": "הסר סמן",
    "SaveToMyContent": "שמור בתכולה שלי"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "שכבה מקושרת",
    "selectedFeatures": "השתמש בישויות נבחרות",
    "drawShapesTip": "צייר צורות כדי לבחור ישויות",
    "pleaseDrawShapesTip": "צייר צורות כדי לבחור ישויות",
    "allFeaturesTip": "כל הישויות בשכבה",
    "selectFeaturesOrDrawShapesTip": "השתמש בישויות נבחרות בשכבה זו כדי לצייר צורות על המפה במטרה להגביל ישויות."
  },
  "searchDistance": {
    "applySearchDistance": "החל מרחק חיפוש",
    "applySearchDistanceToFeatures": "החל מרחק חיפוש על ישויות נבחרות"
  },
  "units": {
    "miles": "מיילים",
    "milesAbbr": "מייל",
    "kilometers": "קילומטרים",
    "kilometersAbbr": "ק\"מ",
    "feet": "רגל",
    "feetAbbr": "רגל",
    "meters": "מטרים",
    "metersAbbr": "מ'",
    "yards": "יארדים",
    "yardsAbbr": "יארד",
    "acres": "אקרים",
    "acresAbbr": "אקרים",
    "nauticalMiles": "מיילים ימיים",
    "nauticalMilesAbbr": "nmi",
    "uSSurveyFeet": "US survey feet",
    "uSSurveyFeetAbbr": "ftUS",
    "decimalDegree": "מעלות עשרוניות",
    "decimalDegreeAbbr": "מעלות עשרוניות",
    "degreeMinuteSeconds": "מעלה דקה שניות",
    "degreeMinuteSecondsAbbr": "d-m-s",
    "squareMiles": "מיילים רבועים",
    "squareMilesAbbr": "מיילים רבועים",
    "squareKilometer": "קילומטרים רבועים",
    "squareKilometerAbbr": "קמ''ר",
    "squareFeet": "רגל רבוע",
    "squareFeetAbbr": "רגל רבוע",
    "squareMeters": "מטרים רבועים",
    "squareMetersAbbr": "מ''ר",
    "squareYards": "יארד רבוע",
    "squareYardsAbbr": "יארד רבוע",
    "squareUSSurveyFeet": "Square US survey feet",
    "squareUSSurveyFeetAbbr": "sq ftUS"
  },
  "featureSetChooser": {
    "select": "בחר",
    "dragBox": "גרור",
    "dragMouse": "גרור את העכבר",
    "selectByRectangle": "בחר בעזרת מלבן",
    "selectFeaturesTip": "בחר ישויות על ידי שרטוט מלבן סביבן במפה באמצעות גרירה",
    "newSelectionTip": "צור בחירה חדשה",
    "addSelectionTip": "הוסף לנבחרים",
    "removeSelectionTip": "הסר מהבחירה",
    "selectFromCurrentSelectionTip": "בחר מתוך הרשומות הנבחרות",
    "unselectAllSelectionTip": "בטל את הבחירה בכל הישויות הנבחרות הנוכחיות",
    "selectByPolygon": "בחירה לפי פוליגון",
    "selectByCircle": "בחירה לפי מעגל",
    "selectByLine": "בחירה לפי קו",
    "chooseSelectingTools": "בחר כלי בחירה",
    "darw": "שרטוט",
    "drawShap": "שרטט צורה"
  },
  "widgetManager": {
    "createWidgetError": "שגיאה ביצירת ווידג'ט",
    "createWidgetSettingPageError": "שגיאה בדף ההגדרות ליצירת ווידג'ט",
    "loadWidgetResourceError": "שגיאת משאב בטעינת ווידג'ט"
  },
  "shareOptions": {
    "shareMap": "בחר מי יוכל להציג אפליקציה זו",
    "shareMapTips": "האפליקציה שלך מוגדרת לשיתוף עם אנשים אלה",
    "everyone": "כולם",
    "theseGroups": "קבוצות אלה"
  },
  "shareLink": {
    "email": "דוא\"ל",
    "shareEmail": "דוא\"ל",
    "facebook": "פייסבוק",
    "shareFacebook": "פייסבוק",
    "twitter": "טוויטר",
    "shareTwitter": "טוויטר",
    "googlePlus": "Google+‎",
    "shareGooglePlus": "Google+‎",
    "EmbedTips": "הטמע אפליקציה זו באתר",
    "shareEmailSubject": "שיתוף אפליקציית אינטרנט:",
    "shareEmailTxt1": "זו אפליקציית אינטרנט שמשותפת איתך באמצעות Web AppBuilder for ArcGIS.",
    "shareEmailTxt2": "באפשרותך ליצור אפליקציית אינטרנט משלך ולשתף אותה באמצעות Esri Web AppBuilder for ArcGIS.",
    "shareEmailTxt3": "לקבלת פרטים, בקר בכתובת http://www.esri.com/software/web-appbuilder.",
    "smallSize": "קטן",
    "mediumSize": "בינוני",
    "largeSize": "גדול",
    "customSize": "מותאם",
    "embed": "הטמע אפליקציה זו באתר",
    "more": "אפשרויות הטמעה",
    "changeShareSettings": "שנה הגדרות שיתוף",
    "shareLinkText": "שתף קישור לאפליקציה זו",
    "linkOptions": "אפשרויות קישור",
    "linkOptionsUrlParameters": "בחר פרמטרי URL הנכללים בקישור",
    "currentMapExtent": "תיחום המפה הנוכחי",
    "chooseCenterWithLevel": "לחץ על המפה כדי להגדיר את מרכז המפה עם רמת ההתמקדות",
    "chooseCenterWithScale": "לחץ על המפה כדי להגדיר את מרכז המפה עם קנה מידה של מפה",
    "findLocation": "מצא את המיקום או הישות ובצע פעולת התמקדות",
    "findLocation_inputPlaceholder": "המקום או הישות שלך",
    "queryFeature": "שלח שאילתא לגבי ישות ובצע פעולת התמקדות",
    "addMarker": "הוסף סימול למפה",
    "addMarker_titlePlaceholder": "כותרת חלון קופץ של הסמן",
    "addMarker_symbolURL": "כתובת ה-URL של סמל הסימול",
    "addMarker_label": "תווית סימול",
    "popupTitle": "כותרת חלון קופץ",
    "zoomLevel": "רמת התמקדות",
    "overwirteMobileLayout": "דרוס את גודל המסך המוגדר כברירת מחדל של הסידור במכשירים ניידים",
    "language": "הגדר את שפת התצוגה של האפליקציה",
    "auth": "אמת משתמש באופן אוטומטי",
    "linkPreview": "תצוגה מקדימה של הקישור",
    "useShortenLink": "קישור קצר",
    "shareMapUrlExtent": "שתף את תיחום המפה הנוכחי",
    "shareToWebTips": "אפליקציה זו אינה משותפת עם הציבור. ייתכן שאנשים לא יוכלו להציג אותה."
  },
  "webSceneLoader": {
    "webglSupportTip": "אפליקציות אינטרנט בתלת-ממד אינן נתמכות בדפדפן שלך."
  },
  "map": {
    "basemapNotAvailable": "מפת הבסיס לא זמינה.",
    "displayDefaultBasemap": "מציג במקום זאת את מפת הבסיס שהוגדרה כברירת מחדל.",
    "layerLoadedError": "לא ניתן להוסיף למפה את השכבה ${layers}."
  },
  "popup": {
    "relatedTables": "טבלאות מקושרות:",
    "relatedRecords": "רשומות מקושרות:",
    "noRelatedRecotds": "לא נמצאו רשומות קשורות.",
    "chooseFieldTip": "בחר מאפיין להצגת הרשימה",
    "saveAsPopupTitle": "זהה לכותרת החלון הקופץ"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "יש יותר מדי ישויות בבחירה. ייתכן שאחזורם והצגתם על המפה יימשך זמן רב.",
    "askForContinue": "האם ברצונך להמשיך?"
  },
  "colorPalette": {
    "transparent": "שקוף",
    "custom": "מותאם"
  },
  "temperature": {
    "celsius": "צלזיוס",
    "fahrenheit": "פרנהייט"
  },
  "report": {
    "printButtonLabel": "הדפס",
    "reportDimensionsMsg": "דוח זה תוכנן להדפסה על-גבי נייר ${paperSize}",
    "unableToPrintMapMsg": "אירעה שגיאה בעת הדפסת המפה/ות.",
    "notesHint": "הזן הערות כאן",
    "landscape": "נוף",
    "portrait": "לאורך",
    "mapOnly": "MAP_ONLY",
    "a0": "A0",
    "a1": "A1",
    "a2": "A2",
    "a3": "A3",
    "a4": "A4",
    "a5": "A5",
    "letterANSIA": "Letter ANSI A",
    "tabloidANSIB": "Tabloid ANSI B",
    "letter": "Letter",
    "legal": "Legal",
    "tabloid": "Tabloid",
    "ansi_a": "ANSI A",
    "ansi_b": "ANSI B",
    "ansi_c": "ANSI C",
    "ansi_d": "ANSI D",
    "ansi_e": "ANSI E"
  },
  "snapshot": {
    "snapshot_complete": "הצלחה ביצירת צילום בזק.",
    "snapshot_failed": "כשל ביצירת צילום בזק.",
    "snapshot_append": "צילום בזק",
    "utc": "זמן אוניברסלי מתואם- UTC"
  },
  "statisticsChart": {
    "enlarge": "הגדל",
    "setting": "הגדרה",
    "count": "מונה",
    "horizontalAxis": "ציר אופקי",
    "verticalAxis": "ציר אנכי",
    "dataLabels": "תוויות נתונים",
    "color": "צבע"
  },
  "frameworkDatasource": {
    "setDataSource": "הגדר מקור נתונים",
    "customDataSource": "מקור נתונים נוסף",
    "selectCustomDataTip": "בחר מקור נתונים מאפליקציה זו.",
    "widgetOutputs": "פלט ווידג'ט",
    "noExtraDsAvailable": "מקורות נתונים נוספים לא זמינים.",
    "addExtraDsTip": "עבור לכרטיסייה 'מאפיין' של הבונה, ולחץ על 'מקור נתונים נוסף' כדי להוסיף מידע.",
    "widgetOutpusListTip": "גם ווידג'טים של פלט (אם הם קיימים) רשומים כאן."
  },
  "gridLayout": {
    "addWidgetTip": "הוסף ווידג'טים לכאן דרך הכרטיסיה 'ווידג'ט'",
    "modifyLayout": "שנה פריסה",
    "dragToAdd": "גרור כדי להוסיף",
    "mapArea": "אזור מפה"
  },
  "noEditPrivileges": "לחשבונך אין הרשאות ליצור נתונים או לשנות אותם.",
  "invalidConfiguration": "תצורת הווידג'ט לא הוגדרה או שהשכבות בתצורה אינן נמצאות עוד במפה. פתח את האפליקציה במצב עריכה והגדר מחדש את תצורת הווידג'ט."
});