define(
   ({
    "sourceSetting": "원본 설정 검색",
    "instruction": "지오코드 서비스 또는 피처 레이어를 검색 원본으로 추가하고 구성합니다. 이러한 지정된 원본은 검색 상자 내에서 검색 가능한 항목을 확인합니다.",
    "add": "검색 원본 추가",
    "addGeocoder": "지오코더 추가",
    "geocoder": "지오코더",
    "setLayerSource": "레이어 원본 설정",
    "setGeocoderURL": "지오코더 URL 설정",
    "searchableLayer": "피처 레이어",
    "name": "이름",
    "countryCode": "국가 또는 지역 코드",
    "countryCodeEg": "예: ",
    "countryCodeHint": "이 값을 비워 두면 모든 국가와 지역이 검색됩니다.",
    "generalSetting": "일반 설정",
    "allPlaceholder": "모두 검색하기 위한 플레이스 홀더 텍스트: ",
    "showInfoWindowOnSelect": "발견한 피처 또는 위치에 대해 팝업 보기",
    "searchInCurrentMapExtent": "현재 맵 범위에서만 검색",
    "locatorUrl": "지오코더 URL",
    "locatorName": "지오코더 이름",
    "locatorExample": "예시",
    "locatorWarning": "이 버전의 지오코딩 서비스는 지원되지 않습니다. 위젯이 지오코딩 서비스 00.0 이상을 지원합니다.",
    "locatorTips": "지오코딩 서비스에서 추천 기능을 지원하지 않기 때문에 추천을 사용할 수 없습니다.",
    "layerSource": "레이어 원본",
    "searchLayerTips": "피처 서비스에서 페이지 매김 기능을 지원하지 않기 때문에 제안 사항을 사용할 수 없습니다.",
    "placeholder": "플레이스 홀더 텍스트",
    "searchFields": "검색 필드",
    "displayField": "디스플레이 필드",
    "exactMatch": "정확히 일치",
    "maxResults": "최대 결과",
    "setSearchFields": "검색 필드 설정",
    "set": "설정",
    "fieldSearchable": "검색 가능",
    "fieldName": "이름",
    "fieldAlias": "별칭",
    "ok": "확인",
    "cancel": "취소",
    "invalidUrlTip": "입력한 URL이 잘못되었거나 접근할 수 없습니다."
  })
);