define({
  "_widgetLabel": "Tabela de Atributos",
  "_featureAction_ShowRelatedRecords": "Exibir registos relacionados",
  "_featureAction_ViewInTable": "Visualizar em Tabela de Atributos",
  "ok": "OK",
  "cancel": "Cancelar",
  "unsupportQueryWarning": "A camada tem de suportar operações de consulta para ser exibida no widget de Tabela de Atributos. Garanta que a capacidade de consulta está ligada no serviço.",
  "exportMessage": "Exportar dados para ficheiro CSV?",
  "exportFiles": "Exportar para CSV",
  "exportSelected": "Exportar selecionados para CSV",
  "exportAll": "Exportar todos para CSV",
  "options": "Opções",
  "zoomto": "Efetuar zoom para",
  "highlight": "Destacar gráficos",
  "selectAll": "Selecionar registos em todas as páginas",
  "selectPage": "Selecionar registos na página atual",
  "clearSelection": "Limpar seleção",
  "filter": "Filtro",
  "setFilterTip": "Por favor, defina os filtros corretamente.",
  "noFilterTip": "Sem expressões de filtro definidas, esta tarefa de consulta irá listar todos os elementos na fonte de dados especificada.",
  "filterByExtent": "Filtrar por extensão de mapa",
  "showSelectedRecords": "Exibir registos selecionados",
  "showAllRecords": "Exibir todos os registos",
  "showRelatedRecords": "Exibir registos relacionados",
  "noRelatedRecords": "Não foram encontrados registos relacionados",
  "attachmentColumn": "Fotografias e ficheiros",
  "refresh": "Atualizar",
  "features": "elementos",
  "records": "registos",
  "selected": "selecionado",
  "transparent": "Modo transparente",
  "indicate": "Localizar seleção",
  "columns": "Exibir/Ocultar colunas",
  "selectionSymbol": "Símbolo de seleção",
  "closeMessage": "Ocultar tabela (Voltar a expandi-la a partir do fundo)",
  "dataNotAvailable": "Dados não disponíveis!<br>Clique no botão [Atualizar] para fazer uma tentativa",
  "openTableTip": "Abrir tabela de atributos",
  "closeTableTip": "Esconder a tabela de atributos",
  "sortAsc": "Ordem crescente",
  "sortDes": "Ordem decrescente",
  "statistics": "Estatísticas",
  "attachments": "Anexos",
  "files": "ficheiros"
});