define({
  "sourceSetting": "Nastavitve vira iskanja",
  "instruction": "Dodajte in konfigurirajte geokodirne storitve ali geoobjektne sloje kot vire iskanja. Ti viri določajo, kaj je mogoče iskati znotraj iskalnega polja.",
  "add": "Dodajte vir iskanja",
  "addGeocoder": "Dodajte geokodirnik",
  "geocoder": "Geokodirnik",
  "setLayerSource": "Nastavi vir sloja",
  "setGeocoderURL": "Nastavi URL geokodirnika",
  "searchableLayer": "Geoobjektni sloj",
  "name": "Ime",
  "countryCode": "Šifre države ali regije",
  "countryCodeEg": "npr. ",
  "countryCodeHint": "Če to vrednost pustite prazno, bo iskanje potekalo po vseh državah in regijah",
  "generalSetting": "Splošne nastavitve",
  "allPlaceholder": "Nadomestno besedilo za iskanje: ",
  "showInfoWindowOnSelect": "Pokaži pojavno okno za najdeni geoobjekt ali lokacijo",
  "showInfoWindowOnSelect2": "Prikaži pojavno okno, ko je najden geoobjekt ali lokacija.",
  "searchInCurrentMapExtent": "Išči samo v trenutnem obsegu karte",
  "zoomScale": "Povečava merila",
  "locatorUrl": "URL geokodirnika",
  "locatorName": "Ime geokodirnika",
  "locatorExample": "Primer",
  "locatorWarning": "Ta različica geokodirnih storitev ni podprta. Pripomoček podpira različico geokodirne storitve 10.1 in novejšo.",
  "locatorTips": "Priporočila niso na voljo, ker geokodirna storitev ne podpira predlagane možnosti.",
  "layerSource": "Vir sloja",
  "searchLayerTips": "Predlogi niso na voljo, ker geoobjektna storitev ne podpira možnosti številčenja strani.",
  "placeholder": "Nadomestno besedilo",
  "searchFields": "Iskalna polja",
  "displayField": "Prikaži polje",
  "exactMatch": "Natančno ujemanje",
  "maxSuggestions": "Maksimalno predlogov",
  "maxResults": "Maksimalno rezultatov",
  "enableLocalSearch": "Omogoči lokalno iskanje",
  "minScale": "Minimalno merilo",
  "minScaleHint": "Ko je merilo karte večje od tega merila, bo uporabljeno lokalno iskanje",
  "radius": "Polmer",
  "radiusHint": "Določa polmer območja okrog trenutnega središča karte, ki je uporabljeno za povečanje števila kandidatov za geokodiranje, tako da so najprej prikazani kandidati, ki so najbližji lokaciji",
  "meters": "Metri",
  "setSearchFields": "Nastavi iskalna polja",
  "set": "Nastavi",
  "fieldSearchable": "iskanje omogočeno",
  "fieldName": "Ime",
  "fieldAlias": "Vzdevek",
  "ok": "V redu",
  "cancel": "Prekliči",
  "invalidUrlTip": "URL ${URL} ni veljaven ali dostopen."
});