define(
   ({
    _widgetLabel: "Attributtabelle",
    ok: "OK",
    cancel: "Abbrechen",
    unsupportQueryWarning: "Der Layer muss die Abfrageoperation unterstützen, um im Widget der Attributtabelle angezeigt zu werden. Stellen Sie sicher, dass die Abfragefunktion in dem Service aktiviert ist.",
    exportMessage: "Daten in CSV-Datei exportieren?",
    exportFiles: "In CSV exportieren",
    exportSelected: "Ausgewählte Elemente in CSV exportieren",
    exportAll: "Alle Elemente in CSV exportieren",
    options: "Optionen",
    zoomto: "Zoomen auf",
    highlight: "Grafiken hervorheben",
    selectAll: "Datensätze auf allen Seiten auswählen",
    selectPage: "Datensätze auf aktueller Seite auswählen",
    clearSelection: "Auswahl aufheben",
    filter: "Filter",
    setFilterTip: "Legen Sie den Filter ordnungsgemäß fest.",
    noFilterTip: "Dieser Abfrage-Task listet alle Features in der angegebenen Datenquelle ohne definierten Filterausdruck auf.",
    filterByExtent: "Nach Kartenausdehnung filtern",
    showSelectedRecords: "Ausgewählte Datensätze anzeigen",
    showAllRecords: "Alle Datensätze anzeigen",
    showRelatedRecords: "Zugehörige Datensätze anzeigen",
    noRelatedRecords: "Keine zugehörigen Datensätze",
    refresh: "Aktualisieren",
    features: "Features",
    selected: "ausgewählt",
    transparent: "Transparentmodus",
    indicate: "Auswahl suchen",
    columns: "Spalten ein-/ausblenden",
    selectionSymbol: "Auswahlsymbol",
    closeMessage: "Tabelle ausblenden (von unten wieder einblenden)",
    dataNotAvailable: "Daten nicht verfügbar!<br>Klicken Sie auf die Schaltfläche [Aktualisieren], um es erneut zu versuchen.",
    openTableTip: "Attributtabelle öffnen",
    closeTableTip: "Attributtabelle ausblenden"
  })
);