define({
  "instruction": "Selecciona y configura las capas que se mostrarán en la tabla de atributos al principio.",
  "label": "Capa",
  "show": "Mostrar",
  "actions": "Configurar campos de capa",
  "field": "Campo",
  "alias": "Alias",
  "url": "Dirección URL",
  "sortField": "El campo de ordenación",
  "sortOrderTooltips": {
    "toDescending": "Cambiar a orden descendente",
    "toAscending": "Cambiar a orden ascendente"
  },
  "visible": "Visible",
  "linkField": "Campo de vínculo",
  "noLayers": "No hay capas de entidades disponibles",
  "back": "Atrás",
  "exportCSV": "Permitir exportación a CSV",
  "expand": "Expandir inicialmente el widget",
  "filterByExtent": "Habilitar Filtrar por extensión de mapa de forma predeterminada",
  "allowTextSelection": "Permitir selección de texto",
  "highlightColor": "Resaltar color",
  "restore": "Restaurar al valor predeterminado",
  "ok": "Aceptar",
  "cancel": "Cancelar",
  "includePoint": "Incluir coordenadas de punto en el archivo exportado",
  "configureLayerFields": "Configurar campos de capa",
  "result": "Guardado correctamente",
  "warning": "Selecciona primero la opción Mostrar.",
  "fieldCheckWarning": "Se debe seleccionar al menos un campo.",
  "unsupportQueryWarning": "La capa debe ser compatible con la operación de consulta para aparecer en el widget Tabla de atributos. Asegúrate de que la función de consulta en el servicio está activada.",
  "unsupportQueryLayers": "La capa siguiente debe ser compatible con la operación de consulta para aparecer en el widget Tabla de atributos. Asegúrate de que la función de consulta en el servicio está activada.",
  "fieldName": "Nombre",
  "fieldAlias": "Alias",
  "fieldVisibility": "Visibilidad",
  "fieldActions": "Acciones",
  "showAttachments": "Mostrar archivos adjuntos"
});