define({
  "id": "ID",
  "state": "默认情况下，该坐标将显示在当前地图的坐标系中。要获取其他坐标系中的坐标，您需要添加这些坐标系并指定相应变换。",
  "outputUnit": "输出单位",
  "wkid": "输出 WKID",
  "label": "输出坐标系名称",
  "transformationWkid": "变换 WKID",
  "transformationLabel": "变换标注",
  "transformForward": "正向变换",
  "actions": "操作",
  "warning": "请输入有效的空间参考 WKID!",
  "tfWarning": "请输入有效的基准面变换 WKID!",
  "spinnerLabel": "将坐标四舍五入为: ",
  "decimalPlace": "小数位数",
  "separator": "显示千位分隔符",
  "getVersionError": "无法获取几何服务的版本",
  "add": "添加输出坐标系",
  "edit": "编辑坐标系",
  "output": "输出坐标系",
  "cName": "坐标系名称",
  "units": "显示单位： ",
  "datum": "基准面变换",
  "tName": "变换名称",
  "tWKIDPlaceHolder": "变换的 WKID",
  "forward": "使用正向变换",
  "ok": "确定",
  "cancel": "取消",
  "olderVersion": "几何服务不支持变换操作",
  "REPEATING_ERROR": " 输出列表中存在坐标系。",
  "Default": "默认值",
  "Inches": "英寸",
  "Foot": "英尺",
  "Yards": "码",
  "Miles": "英里",
  "Nautical_Miles": "海里",
  "Millimeters": "毫米",
  "Centimeters": "厘米",
  "Meter": "米",
  "Kilometers": "千米",
  "Decimeters": "分米",
  "Decimal_Degrees": "十进制度",
  "Degrees_Decimal_Minutes": "度十进制分",
  "Degree_Minutes_Seconds": "度分秒",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "坐标显示顺序：",
  "lonLatTips": "经度/纬度(X,Y)",
  "latLonTips": "纬度/经度(Y,X)"
});