define({
  "_widgetLabel": "Llista de capes",
  "titleBasemap": "Mapes base",
  "titleLayers": "Capes operatives",
  "labelLayer": "Nom de la capa",
  "itemZoomTo": "Aplica el zoom a",
  "itemTransparency": "Transparència",
  "itemTransparent": "Transparent",
  "itemOpaque": "Opac",
  "itemMoveUp": "Mou cap amunt",
  "itemMoveDown": "Mou cap avall",
  "itemDesc": "Descripció",
  "itemDownload": "Baixa",
  "itemToAttributeTable": "Visualitza a la taula d'atributs",
  "itemShowItemDetails": "Mostra els detalls de l'element",
  "empty": "buit",
  "removePopup": "Deshabilita la finestra emergent",
  "enablePopup": "Habilita la finestra emergent",
  "turnAllLayersOff": "Desactiva totes les capes",
  "turnAllLayersOn": "Activa totes les capes",
  "expandAllLayers": "Expandeix totes les capes",
  "collapseAlllayers": "Contrau totes les capes",
  "turnAllLabelsOff": "Desactiva totes les etiquetes",
  "turnAllLabelsOn": "Activa totes les etiquetes",
  "showLabels": "Mostra les etiquetes",
  "hideLables": "Amaga les etiquetes"
});