define({
  "_widgetLabel": "레이어 목록",
  "titleBasemap": "베이스맵",
  "titleLayers": "운영 레이어",
  "labelLayer": "레이어 이름",
  "itemZoomTo": "확대",
  "itemTransparency": "투명도",
  "itemTransparent": "투명",
  "itemOpaque": "불투명",
  "itemMoveUp": "위로 이동",
  "itemMoveDown": "아래로 이동",
  "itemDesc": "설명",
  "itemDownload": "다운로드",
  "itemToAttributeTable": "속성 테이블에서 보기",
  "itemShowItemDetails": "항목 세부정보 보기",
  "empty": "비어 있음",
  "removePopup": "팝업 비활성화",
  "enablePopup": "팝업 활성화",
  "turnAllLayersOff": "모든 레이어 끄기",
  "turnAllLayersOn": "모든 레이어 켜기",
  "expandAllLayers": "모든 레이어 확장",
  "collapseAlllayers": "모든 레이어 축소",
  "turnAllLabelsOff": "모든 레이블 끄기",
  "turnAllLabelsOn": "모든 레이블 켜기",
  "showLabels": "레이블 보기",
  "hideLables": "레이블 숨기기"
});