define({
  "id": "ID",
  "state": "Vaikimisi kuvatakse koordinaadid praeguse kaardi koordinaatsüsteemis. Koordinaatide kuvamiseks muudes koordinaatsüsteemides peate need eraldi lisama ja määrama vastavad transformatsioonid.",
  "outputUnit": "Väljundi ühik",
  "wkid": "Väljundi WKID",
  "label": "Väljundi koordinaatsüsteemi nimi",
  "transformationWkid": "Teisenduse WKID",
  "transformationLabel": "Transformatsiooni märgis",
  "transformForward": "Transformeeri edasi",
  "actions": "Tegevused",
  "warning": "Sisestage koordinaatsüsteemi õige WKID!",
  "tfWarning": "Sisestage daatumi transformatsiooni õige WKID!",
  "spinnerLabel": "Ümarda koordinaadid: ",
  "decimalPlace": "kümnendkohad",
  "separator": "Kuva tuhandike eraldajad",
  "getVersionError": "Ei saa geomeetriateenuse versiooni avada",
  "add": "Lisa väljundi koordinaatsüsteem",
  "edit": "Muuda koordinaatsüsteemi",
  "output": "Väljundi koordinaatsüsteem",
  "cName": "Koordinaatsüsteemi nimi",
  "units": "Kuvamise ühikud: ",
  "datum": "Daatumi transformatsioon",
  "tName": "Transformatsiooni nimi",
  "tWKIDPlaceHolder": "Transformatsiooni WKID",
  "forward": "Kasuta edasi transformatsiooni",
  "ok": "OK",
  "cancel": "Tühista",
  "olderVersion": "Geomeetriateenus ei toeta transformatsiooni toimingut",
  "REPEATING_ERROR": " Koordinaatsüsteem on väljundite loendis.",
  "Default": "Vaikimisi",
  "Inches": "Tolli",
  "Foot": "Jalga",
  "Yards": "Jardi",
  "Miles": "Miili",
  "Nautical_Miles": "Meremiili",
  "Millimeters": "Millimeetrit",
  "Centimeters": "Sentimeetrit",
  "Meter": "Meetrit",
  "Kilometers": "Kilomeetrit",
  "Decimeters": "Detsimeetrit",
  "Decimal_Degrees": "Kümnendkraadid",
  "Degrees_Decimal_Minutes": "Kraadid kümnendminutid",
  "Degree_Minutes_Seconds": "Kraadid minutid sekundid",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Koordinaatide kuvamise järjekord:",
  "lonLatTips": "Pikkuskraad/laiuskraad(X, Y)",
  "latLonTips": "Laiuskraad/pikkuskraad(Y, X)"
});