define({
  "id": "ID",
  "state": "Per defecte, les coordenades es mostraran al sistema de coordenades del mapa actual. Per obtenir coordenades en altres sistemes de coordenades, les heu d'afegir i especificar les transformacions adequades.",
  "outputUnit": "Unitat de sortida",
  "wkid": "WKID de sortida",
  "label": "Nom del sistema de coordenades de sortida",
  "transformationWkid": "WKID de transformació",
  "transformationLabel": "Etiqueta de transformació",
  "transformForward": "Transforma endavant",
  "actions": "Accions",
  "warning": "Introduïu un WKID de referència espacial vàlid.",
  "tfWarning": "Introduïu un WKID de transformació de dàtum vàlid.",
  "spinnerLabel": "Arrodoneix coordenades a: ",
  "decimalPlace": "posicions decimals",
  "separator": "Mostra els separadors de milers",
  "getVersionError": "No es pot obtenir la versió del servei de geometria",
  "add": "Afegeix el sistema de coordenades de sortida",
  "edit": "Edita el sistema de coordenades",
  "output": "Sistema de coordenades de sortida",
  "cName": "Nom del sistema de coordenades",
  "units": "Mostra les unitats: ",
  "datum": "Transformació de dàtum",
  "tName": "Nom de transformació",
  "tWKIDPlaceHolder": "WKID de la transformació",
  "forward": "Utilitza la transformació endavant",
  "ok": "D'acord",
  "cancel": "Cancel·la",
  "olderVersion": "El servei de geometria no admet l'operació de transformació",
  "REPEATING_ERROR": " El sistema de coordenades existeix a la llista de sortida.",
  "Default": "Per defecte",
  "Inches": "Polzades",
  "Foot": "Peus",
  "Yards": "Iardes",
  "Miles": "Milles",
  "Nautical_Miles": "Milles nàutiques",
  "Millimeters": "Mil·límetres",
  "Centimeters": "Centímetres",
  "Meter": "Metres",
  "Kilometers": "Quilòmetres",
  "Decimeters": "Decímetres",
  "Decimal_Degrees": "Graus decimals",
  "Degrees_Decimal_Minutes": "Graus minuts decimals",
  "Degree_Minutes_Seconds": "Graus minuts segons",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Ordre de visualització de coordenades:",
  "lonLatTips": "Longitud/latitud (X, Y)",
  "latLonTips": "Latitud/longitud (Y, X)"
});