define({
  "instruction": "Seleccione e configure camadas que irão ser mostrados inicialmente na Tabela de Atributo.",
  "label": "Camada",
  "show": "Exibir",
  "actions": "Configurar campos de camadas",
  "field": "Campo",
  "alias": "Nome Alternativo",
  "visible": "Visível",
  "linkField": "Campo de ligação",
  "noLayers": "Não há camadas de elementos disponíveis",
  "back": "Regressar",
  "exportCSV": "Permitir exportar para CSV",
  "expand": "Expandir o widget inicialmente",
  "filterByExtent": "Ativar Filtrar por extensão de mapa por defeito",
  "restore": "Restaurar para valor padrão",
  "ok": "OK",
  "cancel": "Cancelar",
  "includePoint": "Incluir coordenadas de ponto no ficheiro exportado",
  "configureLayerFields": "Configurar Campos de Camadas",
  "result": "Guardado com sucesso",
  "warning": "Por favor seleccione a opcção Mostrar primeiro.",
  "fieldCheckWarning": "Pelo menos um campo tem de ser selecionado.",
  "unsupportQueryWarning": "A camada tem de suportar operações de consulta para ser exibida no widget de Tabela de Atributos. Garanta que a capacidade de consulta está ligada no serviço.",
  "unsupportQueryLayers": "As seguintes camadas têm de suportar operações de consulta para serem exibidas no widget de Tabela de Atributos. Garanta que a capacidade de consulta está ligada no serviço.",
  "fieldName": "Nome",
  "fieldAlias": "Nome Alternativo",
  "fieldVisibility": "Visibilidade",
  "fieldActions": "Ações",
  "showAttachments": "Exibir anexos"
});