define({
  "_widgetLabel": "רשימת שכבות",
  "titleBasemap": "מפות בסיס",
  "titleLayers": "שכבות תפעוליות",
  "labelLayer": "שם שכבה",
  "itemZoomTo": "התמקד אל",
  "itemTransparency": "שקיפות",
  "itemTransparent": "שקוף",
  "itemOpaque": "אטום",
  "itemMoveUp": "הזז למעלה",
  "itemMoveDown": "הזז למטה",
  "itemDesc": "תיאור",
  "itemDownload": "הורדה",
  "itemToAttributeTable": "הצג בטבלת מאפיינים",
  "itemShowItemDetails": "הצג פרטי פריט",
  "empty": "ריק",
  "removePopup": "השבת חלון קופץ",
  "enablePopup": "הפוך חלונית קופצת לפעילה",
  "turnAllLayersOff": "כבה את כל השכבות",
  "turnAllLayersOn": "הדלק את כל השכבות",
  "expandAllLayers": "הרחב את כל השכבות",
  "collapseAlllayers": "כווץ את כל השכבות",
  "turnAllLabelsOff": "כבה את כל התוויות",
  "turnAllLabelsOn": "הדלק את כל התוויות",
  "showLabels": "הצג תוויות",
  "hideLables": "הסתר תוויות"
});