define({
  "_widgetLabel": "ตารางข้อมูลคุณลักษณะ",
  "_featureAction_ShowRelatedRecords": "แสดงแถวข้อมูลที่เกี่ยวข้อง",
  "_featureAction_ViewInTable": "ดูในตารางแอตทริบิวต์",
  "ok": "ตกลง",
  "cancel": "ยกเลิก",
  "unsupportQueryWarning": "ชั้นข้อมูลต้องมีการสนับสนุนการดำเนินการค้นหาจะแสดงในคุณลักษณะเครื่องมือตาราง ความสามารถในการตรวจสอบให้แน่ใจแบบสอบถามในการให้บริการที่มีการเปิด",
  "exportMessage": "นำข้อมูลออกเป็นไฟล์ CSV?",
  "exportFiles": "นำออกเป็น CSV",
  "exportSelected": "นำออกข้อมูลที่เลือกไปเป็นไฟล์ CSV",
  "exportAll": "นำออกทั้งหมดไปเป็นไฟล์ CSV",
  "options": "ตัวเลือก",
  "zoomto": "ขยายไปยัง",
  "highlight": "ไฮไลต์กราฟิก",
  "selectAll": "เลือกแถวข้อมูลในทุกหน้า",
  "selectPage": "เลือกแถวข้อมูลในหน้าปัจจุบัน",
  "clearSelection": "ล้างการเลือก",
  "filter": "ตัวกรอง",
  "setFilterTip": "โปรดตั้งค่าตัวกรองให้ถูกต้อง",
  "noFilterTip": "หากไม่มีเงื่อนไขของตัวกรองที่กำหนดไว้ การค้นหานี้จะแสดงรายการข้อมูลทั้งหมดในแหล่งข้อมูลที่ระบุ",
  "filterByExtent": "กรองตามขอบเขตแผนที่",
  "showSelectedRecords": "แสดงแถวข้อมูลที่เลือก",
  "showAllRecords": "แสดงแถวข้อมูลทั้งหมด",
  "showRelatedRecords": "แสดงแถวข้อมูลที่เกี่ยวข้อง",
  "noRelatedRecords": "ไม่พบค่าที่เกี่ยวข้อง",
  "attachmentColumn": "รูปภาพและไฟล์",
  "refresh": "รีเฟรช",
  "features": "ฟีเจอร์",
  "records": "บันทึก",
  "selected": "ที่เลือกไว้",
  "transparent": "โหมดโปร่งใส",
  "indicate": "ค้นหาตัวเลือก",
  "columns": "แสดง / ซ่อนคอลัมน์",
  "selectionSymbol": "การเลือกสัญลักษณ์",
  "closeMessage": "ซ่อนตาราง (ขยายอีกครั้งจากด้านล่าง)",
  "dataNotAvailable": "ข้อมูลไม่ปรากฎ!<br>คลิกที่ปุ่ม [Refresh]เพื่อลองใหม่อีกครั้ง",
  "openTableTip": "เปิดตารางข้อมูลคุณลักษณะ",
  "closeTableTip": "ซ่อนตารางเชิงบรรยาย",
  "sortAsc": "จัดเรียงจากน้อยไปมาก",
  "sortDes": "จัดเรียงจากมากไปน้อย",
  "statistics": "สถิติ",
  "attachments": "แนบ",
  "files": "ไฟล์"
});