define({
  "instruction": "Než bude aplikace dostupná, zobrazí se úvodní obrazovka.",
  "defaultContent": "Zde můžete přidat text, odkazy a malé obrázky.",
  "requireConfirm": "Vyžadovat potvrzení k pokračování",
  "noRequireConfirm": "Nevyžadovat potvrzení k pokračování",
  "optionText": "Možnost uživatele deaktivovat úvodní obrazovku po spuštění aplikace.",
  "confirmLabel": "Potvrzovací texty: ",
  "confirmLabelColor": "Potvrzení barev textů",
  "defaultConfirmText": "Souhlasím s výše uvedenými podmínkami a ujednáními",
  "confirmOption": "Zobrazovat tuto úvodní obrazovku při každém spuštění aplikace",
  "backgroundColor": "Barva pozadí",
  "content": "Obsah",
  "contentDescription": "Umožňuje definovat obsah zobrazený na úvodní obrazovce.",
  "appearance": "Vzhled",
  "appearanceDescription": "Umožňuje nastavit vzhled úvodní obrazovky.",
  "size": "Velikost",
  "width": "Šířka",
  "height": "Výška",
  "custom": "Vlastní",
  "background": "Pozadí",
  "colorFill": "Výplň barvou",
  "imageFill": "Výplň obrazem",
  "chooseFile": "Vybrat soubor",
  "noFileChosen": "Není vybrán žádný soubor.",
  "transparency": "Průhlednost",
  "sizeFill": "Výplň",
  "sizeFit": "Přizpůsobit",
  "sizeStretch": "Vyplnit roztažením",
  "sizeCenter": "Střed",
  "sizeTile": "Dlaždice",
  "buttonColor": "Barva tlačítka",
  "buttonText": "Text tlačítka",
  "buttonTextColor": "Barva textu tlačítka",
  "contentAlign": "Zarovnání obsahu",
  "alignTop": "Nahoře",
  "alignMiddle": "Prostředku",
  "maskColor": "Barva masky",
  "options": "Možnosti",
  "optionsDescription": "Umožňuje nastavit chování úvodní obrazovky."
});